### ISSUE TITLE
Error: Error: Resource Group "test-eastus2-poc-rg01" was not found    on ../TerraformModules/AzureFirewall/main.tf line 1, in data "azurerm_resource_group" "this":    1: data "azurerm_resource_group" "this" {

### ISSUE THREAD

**Issue by ManyaSinghal** [terraform-providers/terraform-provider-azurerm#10002]
Hello Team

I am using the new version of the terraform 0.14.03 and getting the above error while i am deploying RG from anther module and calling that rg in firewall module and getting the error. in Firewall module i am using data source to call the RG.

Can anyone help me on this as i am stuck on this

**Comment by tombuildsstuff** [comment]
hi @ManyaSinghal 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by ManyaSinghal** [comment]
Hello Tom

Is this the issue with the terrform version 0.14.0 because when i changed it back to 12.28 it worked fine.
