### ISSUE TITLE
azurerm provider fails when refreshing existing resources

### ISSUE THREAD

**Issue by calinmarina** [terraform-providers/terraform-provider-azurerm#1005]
### Terraform Version
```bash
bash-4.2$ terraform -v
Terraform v0.11.4
+ provider.azurerm v1.3.0
+ provider.null v1.0.0
+ provider.random v1.1.0
+ provider.template v1.0.0
```
Note. we initially encountered this problem with terraform v0.11.3 and azurerm v1.2.0, just after azurerm and terraform updated to 1.2 and 11.4 respectively in March 15, 2018 so upgraded but still no luck

### Affected Resource(s)
Please list the resources as a list, for example:
- module.key_vault.azurerm_key_vault.kv
- module.app.azurerm_application_insights.appinsights

It appears to affect multiple resources, it may be an issue with Terraform's core, as we get other modules showing the same `unexpected EOF` message in other builds but vault definitely comes up everytime 

### Terraform Configuration Files
https://gist.github.com/calinmarina/bd0fd8236b7a523423f64ffb03875999

### Debug Output and Panic Output
https://gist.github.com/calinmarina/e5cbc60084f77ca324bdb5a8083fd47e

### Expected Behavior
`terraform apply` should have run smooth updating resources as before

### Actual Behavior
terraform panicked with `unexpected EOF` for several resources.
Note. nothing changed on the code side, it's exactly the same code running to update previously built resources by the same scripts.

### Steps to Reproduce
see console log in the attached gist but example of steps to follow on top of existing resources:
1. `terraform init -reconfigure -backend-config storage_account_name=mgmtstatestorenonprod -backend-config container_name=mgmtstatestorecontaineraat -backend-config resource_group_name=mgmt-state-store-nonprod -backend-config key=em-anno-app/aat/terraform.tfstate`
2. `terraform get -update=true`
3. `terraform plan -var env=aat -var name=em-anno-app -var subscription=nonprod`

### Important Factoids
- removing the existing resources and running again seems to solve the problem

**Comment by calinmarina** [comment]
@phassingerhi it doesn't seem to be the same issue described in #974 to be honest... they didn't have any panic there and although I listed both keyvault and appinsights as it was shown in the console log, checking panic log only shows problems related to getting response on keyvault through Azure's management API (management.azure.com)
... see my comments on #974

**Comment by tombuildsstuff** [comment]
hey @calinmarina 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this unfortunately the logs aren't particularly insightful - would it be possible to answer the following so that we could investigate this further:

1. What permissions does the Service Principal you're using have on the Azure Key Vault instance?
2. Are there multiple active users on the Azure Subscription? There's a rate limit set by Azure but it's fairly high - given this is only affecting KeyVault I believe it's more likely to be a permissions issue - but would you be able to check this limit? It's returned in the HTTP headers which can either be viewed via `TF_LOG=DEBUG terraform plan ..` or via an HTTP Proxy such as Fiddler / Charles depending on your platform.

@phassingerhi the issue you've encountered is unfortunately an unrelated regression which shipped in v0.11.4, which was fixed in v0.11.5 - would you be able to upgrade to the latest version and take another look?

Thanks!

**Comment by phassingerhi** [comment]
@tombuildsstuff - Confirmed, running on v0.11.6 now works.

**Comment by simongh** [comment]
I seem to still have the same issue. I'm using 0.11.7 & 1.3.3 of the azure provider. Having a keyvault seems to cause a panic if I try running terraform plan.

If I remove the keyvault, then the plan works fine.

I tried making a test plan with a keyvault & that works ok. The only significant difference between my test area & the one above, is above there is significant drift between terraform & Azure after 4 web apps have had MSI enabled on them and added to KV.

I haven't yet found a way round this or way of testing if this is the issue.

**Comment by tombuildsstuff** [comment]
@simongh so that we could take a look into this - would you be able to provide a link to the panic/crash log?

**Comment by tombuildsstuff** [comment]
@simongh thanks for posting that - this is the relevant crash line:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.3.3/azurerm/resource_arm_key_vault.go#L376

I'm actually looking into this resource at the moment - so I'll try and open a PR to fix this.

Thanks!

**Comment by tombuildsstuff** [comment]
@simongh PR #1081 also now includes a fix for the crash you've provided above - thanks again :)

**Comment by tombuildsstuff** [comment]
hey @simongh 

Just to let you know that v1.4.0 of the Azure Provider has been released which includes the fix for this :)

Thanks!
