### ISSUE TITLE
Support for MySQL General Tier

### ISSUE THREAD

**Issue by dapolloxp** [terraform-providers/terraform-provider-azurerm#10058]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The current terraform provider for MySQL has a hardcoded entry for the Basic Tier. This should be parameterized to allow for the GeneralPurpose type.

tier := mysql.Basic
	if sku := resp.Sku; sku != nil {
		d.Set("sku_name", sku.Name)
		tier = sku.Tier
	}

### New or Affected Resource(s)

* azurerm_mysql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_mysql_server" "example" {
  name                = "example-mysqlserver"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  administrator_login          = "mysqladminun"
  administrator_login_password = "H@Sh1CoR3!"

  sku_name   = "B_Gen5_2"
  **tier = "GeneralPurpose"**
  storage_mb = 5120
  version    = "5.7"

  auto_grow_enabled                 = true
  backup_retention_days             = 7
  geo_redundant_backup_enabled      = false
  infrastructure_encryption_enabled = false
  public_network_access_enabled     = true
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @dapolloxp 

Thanks for opening this issue.

Support for this is already available via [the `sku_name` field](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mysql_server#sku_name) - the code you've highlighted above is a fallback for if this isn't included in the API response, which defaults to `basic` since originally there weren't different sku's for this, so some older resources don't return this in the response.

As mentioned in the documentation, the value for the Tier is inferred from the `sku_name`, which is `Tier + Family + Cores`, for example `GP_Gen5_8` - in the Terraform Configuration above your using `B` (Basic) rather than `GP` (GeneralPurpose), which is why this value is being set to Basic. Since this should be resolved by updating the Terraform Configuration I'm going to close this issue for the moment, but should you have further usage questions [you should be able to get further help on the Discuss forum](https://discuss.hashicorp.com).

Thanks!
