### ISSUE TITLE
Terraform unable to handle success StatusCode

### ISSUE THREAD

**Issue by Phydeauxman** [terraform-providers/terraform-provider-azurerm#1012]
I have a configuration to deploy an App Service Plan into an existing App Service Environment v2.  The app service plan creates fine but terraform errors out on the returned StatusCode of 201.

### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.3.0

### Affected Resource(s)
- azurerm_app_service_plan

### Terraform Configuration Files
```hcl
provider "azurerm" {
  subscription_id = "${var.sub_id}"
}

data "terraform_remote_state" "ase" {
  backend = "azurerm"

  config {
    storage_account_name = "${var.tfstate_storage_account}"
    container_name       = "${var.tfstate_container}"
    key                  = "${var.tfstate_asestate_file}"
    access_key           = "${var.tfstate_access_key}"
  }
}

resource "azurerm_app_service_plan" "asp1" {
  name                = "${var.asp1_name}"
  location            = "${var.region}"
  resource_group_name = "${data.terraform_remote_state.ase.asergname}"

  sku {
    tier = "${var.asp1_sku_tier}"
    size = "${var.asp1_sku_size}"
  }

  properties {
    app_service_environment_id = "${data.terraform_remote_state.ase.aseResourceId}"
  }
}
```

### Expected Behavior
The App Service Plan should have been provisioned and terraform should have completed successfully by updating the state file with data from the successful deployment

### Actual Behavior
Terraform errors out with the following error:
```hcl
Error: Error applying plan:

1 error(s) occurred:

* azurerm_app_service_plan.asp1: 1 error(s) occurred:

* azurerm_app_service_plan.asp1: web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=201 -- Original Error: autorest/azure: Service returned an error. Status=201 Code="Unknown" Message="Unknown service error"
```

### Steps to Reproduce

1. Ensure existing App Service Environment v2 is in place
2. `terraform apply`

### Important Factoids
Below is the status code from the Azure Activity events generated by the deployment:
```hcl
"status": {
        "value": "Succeeded",
        "localizedValue": "Succeeded"
    },
    "subStatus": {
        "value": "Created",
        "localizedValue": "Created (HTTP Status Code: 201)"
    },
```

**Comment by tombuildsstuff** [comment]
hi @Phydeauxman 

Thanks for opening this issue :)

Unfortunately this is a bug in the Azure API where the status code `201` can be returned from the API but isn't actually a supported status code according to the SDK/Swagger definition (which is why an errors being returned).

The [latest update is available in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/917#issuecomment-373831347), but we're currently waiting for the Web/App Service team to confirm that this is a valid status code returned from the API, to allow the Swagger file which defines the API that the Azure SDK is generated from to be updated. Rather than having multiple issues tracking the same thing, I'm going to close this in favour of #917.

Thanks!

**Comment by Phydeauxman** [comment]
@tombuildsstuff Thanks for the info.  Guess for now I will deploy with an embedded ARM template.
