### ISSUE TITLE
Terraform don't support Eventhub with captureEnabled feature

### ISSUE THREAD

**Issue by lbsolar** [terraform-providers/terraform-provider-azurerm#1016]
Hi there,

Currently, terraform only support limited features on Eventhub which is not matched with our use case. We have already submitted request to Azure terraform enhancing these features.
Detail: https://www.terraform.io/docs/providers/azurerm/r/eventhub.html

We are waiting for the update for Azure terraform team.

**Comment by tombuildsstuff** [comment]
hi @lbsolar 

Thanks for opening this issue :)

Would it be possible for you to give us some more information on which fields you're looking to use that are missing?

Thanks!

**Comment by anoff** [comment]
I just deployed an EH with capture block and it worked for me. Maybe you need to update the `azurerm` provider?

```HCL
resource "azurerm_eventhub" "logging" {
  name                = "ingest"
  namespace_name      = "${azurerm_eventhub_namespace.logging.name}"
  resource_group_name = "${azurerm_resource_group.base.name}"
  partition_count     = 6
  message_retention   = 1

  capture_description {
    enabled  = true
    encoding = "Avro"

    destination {
      name = "EventHubArchive.AzureBlockBlob"

      archive_name_format = "{Namespace}/{EventHub}/{PartitionId}/{Year}-{Month}-{Day}T{Hour}:{Minute}:{Second}"
      blob_container_name = "${azurerm_storage_container.logging.name}"
      storage_account_id  = "${azurerm_storage_account.logs.id}"
    }
  }
}
```

You can also specify capture interval / block size: https://www.terraform.io/docs/providers/azurerm/r/eventhub.html#interval_in_seconds

Resulting EH capture config

![image](https://user-images.githubusercontent.com/7142618/37899962-2f4d43e2-30ed-11e8-8b95-4c512baa4d49.png)

**Comment by tombuildsstuff** [comment]
hey @lbsolar

As @anoff has posted - it's possible to configure an EventHub with `captureEnabled` using Terraform [since v1.0.1 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#101-january-12-2018) which is [documented on the Terraform Website](https://www.terraform.io/docs/providers/azurerm/r/eventhub.html#capture_description). Would you be able to update and take a look? You can do this by pinning the version of the AzureRM Provider in the `provider `block:

```
provider "azurerm" {
  version = "=1.2.3"
}
```

As we've not heard back from you here I'm going to close this issue for the moment - but we'll be sure to take another look if something's missing :)

Thanks!
