### ISSUE TITLE
Azure Managed HSM keys for SSE encryption

### ISSUE THREAD

**Issue by bg2132332** [terraform-providers/terraform-provider-azurerm#10208]
Please add support for Managed HSMs -- particularly for storage CMK encryption.  We can provision a managed HSM outside of Terraform and we can even provision the key using APIs, but we create storage with Terraform and need ability to use a Managed HSM key for encryption at rest.  We receive key ID validation errors.   I'm sure that you have the same validation errors everywhere where vault_key_id is used.  According to Microsoft docs, the key vault key ID and managed HSM key ID should be interchangeable and so this appears to be only Terraform provider problem with validation of values.

**Comment by tombuildsstuff** [comment]
hi @bg2132332 

Thanks for opening this issue.

Unfortunately there's not enough context in this issue description to determine the extent of changes (for example which resources, examples etc) which need to be made to support this - when opening issues we ask that users complete the issue template which contains the information we require, as such [would you mind opening a new issue completing the Feature Request template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Feature_Request.md&title=Support+for+%5Bthing%5D) so that we have all of the relevant details here?

Thanks!
