### ISSUE TITLE
azurerm_api_management_api_operation template_parameter Invalid Reference

### ISSUE THREAD

**Issue by dan-git-s** [terraform-providers/terraform-provider-azurerm#10205]
Adding template parameter to azurerm_api_management_api_operation is returning invalid reference error.

### Affected Resource(s)

azurerm_api_management_api_operation

### Debug Output

_Error: Invalid reference

in resource "azurerm_api_management_api_operation" "api_operations":
type = bool

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name._

### Terraform Configuration

_resource "azurerm_api_management_api_operation" "api_operations" {
  operation_id        = var.apim_apis[count.index].OperationId
  api_name            = azurerm_api_management_api.apim_api[count.index].name
  api_management_name = azurerm_api_management_api.apim_api[count.index].api_management_name
  resource_group_name = azurerm_api_management_api.apim_api[count.index].resource_group_name
  display_name        = format("%s %s", var.apim_apis[count.index].OperationId, "operation")
  method              = var.apim_apis[count.index].OperationVerb
  url_template        = var.apim_apis[count.index].url_template
  description         = var.apim_apis[count.index].OperationDescription

  response {
    status_code = 200
  }
  **dynamic "template_parameter" {
  for_each = var.apim_apis[count.index].template_parameter == true ? [1] : []
  content { 
   required = true
   type = bool
   name = "IsDaily"   
    }**
}_

**Comment by tombuildsstuff** [comment]
hi @dan-git-s 

Taking a look through here this appears to be an issue with the Terraform Configuration, the field `type` within the `template_parameter` block is a string, as such this'd need to be `"bool"` rather than the literal value `bool` here, which is why your getting this error:

```
_Error: Invalid reference

in resource "azurerm_api_management_api_operation" "api_operations":
type = bool

A reference to a resource type must be followed by at least one attribute
access, specifying the resource name._
```

Unfortunately this error message from Terraform Core isn't particularly clear, but it's assuming that `bool` is a reference to another resource here (such as an interpolation of some kind) - as such [I'd suggest opening an issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) about this so that they can improve this error message here.

Since this appears to be a question regarding Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment - but should you have further questions I'd point you towards [the community discuss forum](https://discuss.hashicorp.com).

Thanks!
