### ISSUE TITLE
Terraform don't support prevent_destroy using variable

### ISSUE THREAD

**Issue by lbsolar** [terraform-providers/terraform-provider-azurerm#1021]
Hi there,

On terraform lifecycle part, Terraform don't support prevent_destroy using variable.

for example:
lifecycle {
prevent_destroy = “$

{var.prevent_destroy}
”
}

https://github.com/hashicorp/terraform/issues/3116

**Comment by tombuildsstuff** [comment]
hey @lbsolar 

Thanks for opening this issue :)

The `lifestyle` block is a part of Terraform Core (vs the Azure/`azurerm_` functionality which is part of this Provider repository). Given this functionality comes from Terraform Core and [there's already an issue tracking this feature request](https://github.com/hashicorp/terraform/issues/3116) - I'm going to close this issue in favour of that one (since, that repository is where this feature request would need to be implemented).

Thanks!
