### ISSUE TITLE
Working sample should include ability to connect to a VM in Terraform.io

### ISSUE THREAD

**Issue by achandmsft** [terraform-providers/terraform-provider-azurerm#1022]
The examples in azurerm_virtual_machine in [Terraform.io](http://aka.ms/terraform) are incomplete as it doesn't create a public IP or network security to connect to the VM. Fix documentation to do the same.

**Comment by tombuildsstuff** [comment]
@achandmsft so the reason we haven't done this so far is that the connection/IP address used to access the VM depends on where users are connecting from; e.g. we can only use a Public IP if the NSG's are configured correctly vs using a Private IP if Terraform's being run with access to that network; or the connections will fail.

Rather than extending the examples in the VM resource - I'd suggest it'd be better to add two complete examples to the `examples/` folder (one for using a Public IP and one for using a Private/internal IP) and link to that from the VM Resource documentation in a dedicated "running provisioners on a virtual machine" section - what do you think?

**Comment by berney** [comment]
I think you need more examples examples, but you also need documentation around those examples explaining someone how it works, why it's the way it is. A "worked example". A lot of the documentation is very sparse, it doesn't really explain what anything is, what it means, why you would use it, how you would use it. Beginners have to experiment a lot until they begin to understand.

**Comment by tombuildsstuff** [comment]
This is now available via https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples/virtual-machines/provisioners which is reliant on v1.12 of the AzureRM Provider (which is the next release) - once that's out these examples should work as intended.

Thanks!
