### ISSUE TITLE
Is there no way to select all logs for monitoring a ressource for Azure

### ISSUE THREAD

**Issue by rdeletoille** [terraform-providers/terraform-provider-azurerm#10220]
Hi, i would like to know if there is a way to select all logs whatever the ressource i want to monitor on Azure.

If not, does that mean i need to create each log list for the different ressource i need to monitor because logs are different depends on the ressource ?

resource "azurerm_monitor_diagnostic_setting" "example" {
  name               = "example"
  target_resource_id = XXXX
  log_analytics_workspace_id = XXXX

  log {
    category = "TriggerRuns"   Is there a way to select all logs here ???

    retention_policy {
      enabled = false
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = true
    }
  }
}

**Comment by tombuildsstuff** [comment]
hi @rdeletoille 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
