### ISSUE TITLE
api_management_resource: Impossible to create a APIM instance with Consumption tier SKU

### ISSUE THREAD

**Issue by larsmaes** [terraform-providers/terraform-provider-azurerm#10269]
When I apply a plan with api_management_resource sku Consumption_0 i get this error:

Error: `sign_in` is not support for sku tier `Consumption`

i have already tried to omit the sign_in but this defaults to true in the plan.
setting sign_in to false also doesnt help

**Comment by tombuildsstuff** [comment]
hi @larsmaes 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
