### ISSUE TITLE
azurerm_kubernetes_cluster not appending tags to all resources

### ISSUE THREAD

**Issue by CGCampbell07** [terraform-providers/terraform-provider-azurerm#10287]
So when creating an azurerm_kubernetes_cluster it tries to create a load balancer in its own resource group and in my subscription it fails as we have a tag policy put in place on the subscription. At first i tried to exclude the resource group in the policy but the load balancer creates a new resource group that the aks is not in and currently no way around this issue unless we disable the policy.

**Comment by tombuildsstuff** [comment]
hi @CGCampbell07 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
