### ISSUE TITLE
Terraform Hub/Spoke Provider failure on Azure DevOps, but works on Jenkins

### ISSUE THREAD

**Issue by craigthackerx** [terraform-providers/terraform-provider-azurerm#10331]
**Terraform Version**
Terraform 0.14.4

**Affected Resource(s)**
AzureRM Authentication

**Terraform Configuration Files**

`provider.tf`
___
```
provider "azurerm" {

  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = true
    }
    virtual_machine {
      delete_os_disk_on_deletion = false
    }
    virtual_machine_scale_set {
      roll_instances_when_required = true
    }
  }
}

variable "hub_arm_subscription_id" {
  type = string
}
variable "hub_arm_client_id" {
  type = string
}
variable "hub_arm_client_secret" {
  type = string
}
variable "hub_arm_tenant_id" {
  type = string
}


provider "azurerm" {
  alias   = "HubNameAlias"

  client_id       = var.hub_arm_client_id
  client_secret   = var.hub_arm_client_secret
  tenant_id       = var.hub_arm_tenant_id
  subscription_id = var.hub_arm_subscription_id

  features {
    key_vault {
      recover_soft_deleted_key_vaults = true
      purge_soft_delete_on_destroy    = true
    }
    virtual_machine {
      delete_os_disk_on_deletion = false
    }
    virtual_machine_scale_set {
      roll_instances_when_required = true
    }
  }
}

terraform {
  backend "azurerm" {}
}

```
_____

I've been try to help migrate our terraform builds from a Jenkinsfile pipeline to an Azure DevOps pipeline.  

I have the same Terraform for the project hosted in Azure Repos, and have replicated a like-for-like approach with Azure Pipelines with Jenkinsfile.  

The Jenkins build works as expected and deploys using the same code and uses the same service principle, however, the Azure Pipeline gets the following error:
```
Error: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc0008c5b00), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:400, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc000ebf830)}

 on provider.tf line 31, in provider "azurerm":
  31: provider "azurerm" {

```

I'm not sure what the error really means.  Azure DevOps has access directly to our tenancy and gets the variables from the `provider.tf` through pipeline variables set.  I have noticed a similar issue [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/5780).  The error from my message is directly flagging `provider.tf` line 31 (copied above).

Any ideas what's making it fail here?

**Comment by favoretti** [comment]
I know I'm not really answering your question directly, but did you have a look at https://github.com/charleszipp/azure-pipelines-tasks-terraform ? 

We use config similar to yours, create a secure env file in Library that sets credentials with TFVAR_blah and it all seems to work quite well.

**Comment by craigthackerx** [comment]
> I know I'm not really answering your question directly, but did you have a look at https://github.com/charleszipp/azure-pipelines-tasks-terraform ?
> 
> We use config similar to yours, create a secure env file in Library that sets credentials with TFVAR_blah and it all seems to work quite well.

Ill give it a try.  We aren't using any of the tasks right now, just old-school powershell tasks in Jenkins and in the pipelines:

`Jenkinsfile`
___
```
{
 powershell '''
                                
       Set-Location $Env:CODE_PATH

      terraform init -backend-config="storage_account_name=$Env:STORAGE_ACCOUNT" -backend config="container_name=$Env:STORAGE_CONTAINER" -backend config="key=blah.terraform.tfstate"
      '''
}
```

`azure-pipeline.yml`
___

```
 - powershell: |
              Set-Location $(CODE_PATH) ; `
              terraform init 
              -backend-config="storage_account_name=$(SA_NAME)" 
              -backend-config="container_name=$(STORAGE_CONTAINER)"
              -backend-config="key=blah.terraform.tfstate"
```

Mainly because we are storing our states inside a storage account in our hub, and deploying our spokes using a service principle.

**Comment by tombuildsstuff** [comment]
@craigthackerx due to behavioural differences in the Azure CLI when using a Service Principal and a User Account - we don't support using the Azure CLI with a Service Principal, which is the root-cause of that error here. Unfortunately it appears that your using an older version of the Azure Provider which doesn't wrap this error message - you can see which version your running using `terraform providers` (the latest is `v2.44.0` at the time of writing) and then upgrade using `terraform init -upgrade`.

For the authentication question, you should either be able to use [the Service Principal by defining it via Env Vars/inline](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/service_principal_client_secret) or [a Managed Identity](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/managed_service_identity) on the Virtual Machine. However since this is a question regarding Terraform Configuration which should be fixed by upgrading rather than a bug in the Azure Provider - I'm going to close this issue for the moment, but I'd point you towards [the community discuss forum](https://discuss.hashicorp.com) should that not work.

Thanks!
