### ISSUE TITLE
Trying to create new sql database in an already created elastic pool but getting error

### ISSUE THREAD

**Issue by kulpreetm** [terraform-providers/terraform-provider-azurerm#10350]
I wrote this code:
resource "azurerm_mssql_database" "mssql_database" {
  name           = "${var.sql_database_name}"
  server_id      = azurerm_sql_server.mssql_server_primary.id
  create_mode    = "Default" //Needs to be updated
  license_type   = "LicenseIncluded" 
  sku_name       = "ElasticPool"
  elastic_pool_name = "test"
  zone_redundant = false

I get below error :

Error: Unsupported argument
  on ms_sql_server_database.tf line 59, in resource "azurerm_mssql_database" "mssql_database":
  59:   elastic_pool_name = "test"
An argument named "elastic_pool_name" is not expected here.

CAN SOMEONE PLEASE TELL ME WHAT ARGUMENT SHOULD I USE FOR MENTIONING THE NAME OF ELASTIC POOL ?

**Comment by tombuildsstuff** [comment]
hi @kulpreetm 

Thanks for opening this issue.

Taking a look through this appears to be an issue with the Terraform Configuration being used, rather than a bug in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [on the Community Discuss Forum](https://discuss.hashicorp.com).

In this instance it appears your trying to use a field which doesn't exist, [the documentation for the `azurerm_mssql_database` resource supports [the field `elastic_pool_id`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/mssql_database#elastic_pool_id) which can be used to provision this inside of an Elastic Pool

As mentioned above, since this an issue with the Terraform Configuration being used, rather than a bug in the Azure Provider - I'm going to close this issue for the moment - but should you have further questions I'd recommend checking out [the Community Discuss Forum](https://discuss.hashicorp.com).

Thanks!
