### ISSUE TITLE
application gateway identity_ids always gets flagged as a change

### ISSUE THREAD

**Issue by abrignola** [terraform-providers/terraform-provider-azurerm#10408]
This is regarding the same exact issue flagged [here  ](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6444) and [here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6456) 

The suggested solution does not work in my scenario because I create the MSI as part of the same terraform run so I cannot use a data block. I need to be able to correctly flag changes to the App Gateway resource and I dont particularly want to have to add the identity to the lifecycle - ignore_changes argument.

**Comment by tombuildsstuff** [comment]
@abrignola there's a fix for this in newer versions of the provider - please upgrade to the latest version (at the time of writing that's v2.45.1) and if this is still happening [please open a new issue completing the issue template which contains all of the information we need to diagnose this](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md) so that we can investigate further. However since this should be fixed by updating the version of the provider being used I'm going to close this issue for the moment.

Thanks!
