### ISSUE TITLE
agentpool name not applied to related resources

### ISSUE THREAD

**Issue by yene** [terraform-providers/terraform-provider-azurerm#10418]
## Steps
```terraform
resource "azurerm_kubernetes_cluster_node_pool" "demo_node_pool" {
  name                  = "demo"
  kubernetes_cluster_id = data.azurerm_kubernetes_cluster.aks.id
  vm_size               = "Standard_D4s_v3"
  node_count            = 1
  vnet_subnet_id        = data.azurerm_subnet.subnet.id
  os_disk_size_gb       = 64 // default: 100
  os_disk_type          = "Ephemeral"
  mode                  = "System"
  max_pods              = 90
  orchestrator_version  = "1.18.10"

}

```

## expected resources
aks-demo-13926898-vmss
aks-demo-13926898-routetable
aks-demo-13926898-nsg

## actual created resources
aks-demo-13926898-vmss
aks-agentpool-13926898-routetable
aks-agentpool-13926898-nsg

**Comment by aristosvo** [comment]
Hi @yene !

I've not tested it myself, but I expect the NSG and RouteTable are shared with multiple pools in your cluster, while the VMSS is for your specific nodepool.

Anyway, this is most likely default behavior of the Azure API, there is not a lot Terraform can do to change that.

**Comment by tombuildsstuff** [comment]
hi @yene 

As @aristosvo has mentioned this naming comes from the AKS API here which, last time I checked, was deploying an ARM Template (or two) behind the scenes when the AKS API is hit to create/update both the Cluster and any Node Pools, which is where I'd guess these values are coming from.

Since at this time [the AKS Node Pool API](https://docs.microsoft.com/en-us/rest/api/aks/agentpools/createorupdate) doesn't expose any options for naming, as such I'd [suggest opening an issue with the AKS Team](https://github.com/Azure/AKS/issues) to confirm if this is something the Service Team plan to support going forwards - however since this is a question for AKS rather than something for Terraform/the Azure Provider, I'm going to close this issue for the moment.

Thanks!
