### ISSUE TITLE
@tombuildsstuff  weirdly event if the account is already created, the error still the same.

### ISSUE THREAD

**Issue by cuntoulishifu** [terraform-providers/terraform-provider-azurerm#10424]
@tombuildsstuff  weirdly event if the account is already created, the error still the same.
I've to create the runbook first to be able to push configuration using terraform.

_Originally posted by @cp3hu in https://github.com/terraform-providers/terraform-provider-azurerm/issues/2811#issuecomment-460258710_

**Comment by cuntoulishifu** [comment]
I have the same problem...
just to try creating a runbook by terraofrm [doc](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/automation_runbook) 

but it does not work, when I do 'terraform plan' all is good; but if do 'terraform apply' it will return a error - 'Error: Error retrieving Automation Runbook "Get-AzureVMTutorial" (Account "xxxxxx-ac" / Resource Group "RG_XXXX"): automation.RunbookClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/xxxxxx-ac/runbooks/Get-AzureVMTutorial' under resource group 'RG_XXXX' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"'

I am sure that I've created the xxxxxx-ac, I can see it in my RG_XXXX.

Could any one help me with resolve this error? 

Thanks a looooooooooooooooooot~

**Comment by tombuildsstuff** [comment]
hi @cuntoulishifu 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
