### ISSUE TITLE
r/(linux|windows)_virtual_machine_scale_set: promote extensions to GA

### ISSUE THREAD

**Issue by hbuckle** [terraform-providers/terraform-provider-azurerm#10431]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was wondering if the ARM_PROVIDER_VMSS_EXTENSIONS_BETA will move out of beta at any point? I don't want to start implementing it while it is still in beta

### New or Affected Resource(s)

* azurerm_windows_virtual_machine_scale_set
* azurerm_linux_virtual_machine_scale_set

**Comment by tombuildsstuff** [comment]
hey @hbuckle 

Thanks for opening this issue.

I'd actually been thinking about the same thing this morning (and just reached out to @jackofallops about this) - at this point in time the design for this shouldn't change (which is why the Extensions functionality is behind a Beta flag, incase the design needed to change) - so it should be possible to promote this from Beta to GA. From our side we'd originally planned to GA the Extensions and Data Disks functionality at the same time, but whilst the Data Disks functionality is being worked on, unfortunately the design has gone through several revisions - so it's a little delayed.

I'm going to leave this issue open tracking this, whilst there's some known issues with Extensions which need looking into (#7002) this should otherwise be fine to go GA in the next release or so 👍

Thanks!

**Comment by hbuckle** [comment]
Great stuff, thanks for the update
