### ISSUE TITLE
azurerm_shared_image_versions not working for image deployment

### ISSUE THREAD

**Issue by eodonoghue** [terraform-providers/terraform-provider-azurerm#10433]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version: 0.13.5 AzureRM Provider: 2.37.0

Please note, I also upgraded to Terraform 14.5 and AzureRM provider to 2.45.0 to test but got the same results

### Affected Resource(s)

azurerm_shared_image_versions

### Terraform Configuration Files
// declaring variable with tags to be used to find image
variable "image_tags" {
  type = map(string)
  default = {
    buildnumber        = "xxxx"
  }
}

// Importing image from shared image gallery based on a tag
data "azurerm_shared_image_versions" "tagged_image_gallery" {
  provider = azurerm.build-sub
  
  tags_filter         = var.image_tags
  image_name          = "sample-img"
  gallery_name        = "samplegallery"
  resource_group_name = "rg-image-gallery"
}

module "linux_machine" {
 ~ 
  image_id              = data.azurerm_shared_image_versions.tagged_image_gallery.images.0.managed_image_id
                                  
}

### Debug Output

Error: creating Linux Virtual Machine "machinename" (Resource Group "rg-name): compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Image sharing not supported for subscription."

--->

### Expected Behaviour

Linux machine should have deployed with the correct image

### Actual Behaviour

Terraform plan ran successfully but the apply failed to deploy the image with error "Image sharing not supported for subscription."

### Steps to Reproduce

 - Create shared image galley
 - populate it with image definitions and apply tags to definitions
 - use the azurerm_shared_image_versions resource to import an image from this gallery based on tags
 - deploy the imported image to a linux virtual machine or linux virtual machine scaleset 

1. `terraform apply`

### Important Factoids
I can see the image exists by using the same value used for the image_is as an output
output "tagged_image_managed_image_id" {
  value = data.azurerm_shared_image_versions.tagged_image_gallery.images.0.managed_image_id

Up until now, we have been using azurerm_shared_image_version to import the "latest" images from a shared image gallery and deploy to a machine without issue. We also want to have the option to deploy an image using tags. Unfortunately, azurerm_shared_image_version does not have this functionality but I found azurerm_shared_image_versions which offers image import via tags. But its attribute references do not contain an image id, just a managed image id. I'm not sure if this can be used to deploy an image and this may be the issue.

I have deployed the same image using the azurerm_shared_image_version so I know it is not an image issue.

eg
data "azurerm_shared_image_version" "latest_image_gallery" {
  provider = azurerm.build-sub

 name                = "0.0.0310"
image_name          = "sample-img"
  gallery_name        = "samplegallery"
  resource_group_name = "rg-image-gallery"
}

module "linux_machine" {
 ~ 
  image_id              = data.azurerm_shared_image_version.epmp_latest_image_gallery.id
]

### References
Feature request created asking for more documentation on this resource including examples of how it is used. eg It is not obvious how to use an attribute reference that is in a block. I also asked in this for a combination of azurerm_shared_image_version and azurerm_shared_image_versions so the same code base can be used to deploy latest or with tags, just the configuration variables set on the workspace should change: 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/10414

* #0000

**Comment by tombuildsstuff** [comment]
hi @eodonoghue 

Thanks for opening this issue.

Taking a look through this appears to be a configuration issue where multiple Subscriptions are being used, as the Azure API is returning `Image sharing not supported for subscription.` which indicates that the Shared Image Gallery is in one subscription and the Linux VM is being provisioned in another. As such I'd double-check that the subscriptions being used are the same, or if your attempting to do this cross-subscription that the subscription the VM is being deployed into can pull from the Shared Image Gallery.

For the usage question regarding how to use items within a nested list, this is more a usability feedback for Terraform Core (so I'd point you towards [the community Discuss forum](https://discuss.hashicorp.com)) - however [the documentation for this is available here](https://www.terraform.io/docs/language/expressions/references.html#references-to-resource-attributes). With regards to the examples of how to use this resource, rather than having multiple issues open tracking the same thing I'm going to consolidate that into #10414.

Since most of the issues mentioned above are usage questions (or requests for examples tracked in another issue), rather than an issue in the Azure Provider, I'm going to close this issue for the moment - but should you have further usage questions I'd point you towards [the community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by eodonoghue** [comment]
Hi Tom,

It is not an issue with multiple subscriptions as I am using almost identical code to import the same image using azurerm_shared_image_version. I suspect it is an issue with the attributes available in both resources. azurerm_shared_image_version has the attribute "id" which can be used successfully as the "source_image_id" for deploying a virtual linux machine: azurerm_linux_virtual_machine. 

azurerm_shared_image_versions does not have a straight forward "id" and instead has "managed_image_id" Using this in the azurerm_linux_virtual_machine as the "source_image_id" results in the error. They point to different things.

"id" attribute for azurerm_shared_image_version is:
"/subscriptions/<subscription id>/resourceGroups/rg-xxx-image-gallery-xxxxxx/providers/Microsoft.Compute/galleries/xxximggallery/images/xxx-xxxx-img/versions/0.0.0310"

"managed_image_id" attribute for azurerm_shared_image_versions is: 
"/subscriptions/<subscription id>/resourceGroups/rg-xxx-image-gallery-xxxxxx/providers/Microsoft.Compute/images/xxx-xxxx_8100_0310"

**Comment by jackofallops** [comment]
Hi @eodonoghue - Is the image replicated to the target region in which you're trying to use it? (this information is in the datasource details as a list of `target_region`) The ID's in both data sources you reference are provided by the service, we just surface them in the provider, so I don't believe that's the issue, however, it's not beyond the realms of possibility that an erroneous message is being returned by the service in this case.

**Comment by eodonoghue** [comment]
Hi,

I am deploying this image successfully to a linux machine, in the same module\folder, without issue using azurerm_shared_image_version. I use the attribute “id” as the source_image_id for the linux machine.
Eg data.azurerm_shared_image_version.epmp_latest_image_gallery.id

When attempting to deploy this image to a linux machine in the same module\folder as stated above, using azurerm_shared_image_versions it fails. In this instance I use the attribute “managed_image_id” as the source_image_id for the virtual machine.

So it is not an image issue.

“id” in azurerm_shared_image_version and “managed_image_id” in azurerm_shared_image_versions resolve to very different values but there is no equivalent “id” in the azurerm_shared_image_versions and I think this is the issue.

**Comment by amandabasara** [comment]
@jackofallops - tagging Steve so he gets a notification about the recent comment.

> Hi, I am deploying this image successfully to a linux machine, in the same module\folder, without issue using azurerm_shared_image_version. I use the attribute “id” as the source_image_id for the linux machine. Eg data.azurerm_shared_image_version.epmp_latest_image_gallery.id When attempting to deploy this image to a linux machine in the same module\folder as stated above, using azurerm_shared_image_versions it fails.
...
...
...

**Comment by amandabasara** [comment]
**Feedback:**

The image you're trying to reference is _not_ replicated to the location (region) you're trying to deploy to.

This is because, **Images** accessed via the **Gallery ID** are provided by a _different_ service layer than the direct Image ID's from the other data source.

Using the **Collection ID** like in your use case is not advised. This is because the **index position** of the image is not guaranteed to stay the same if something modifies the versions or images. It means that they would end up deploying an **unexpected image** or **recreating an existing machine** because the **Image ID** would be different.

Overall, the provider is working as expected and the singular version of the data source is more appropriate for your use case; `azurerm_shared_image_version`.
