### ISSUE TITLE
Cannot read AzureRM App Service Plan

### ISSUE THREAD

**Issue by LeveniukVladyslavAllUnic** [terraform-providers/terraform-provider-azurerm#10457]
I am trying to create App Service Plan and getting this error

Error: Cannot read AzureRM App Service Plan "x100invest-auth-api-dev-neu" (resource group "x100-invest") ID

  on ../../../modules/function_app/main.tf line 12, in resource "azurerm_app_service_plan" "app_service_plan":
  12: resource "azurerm_app_service_plan" "app_service_plan" {

After second run terraform said that app service plan already exists and fails

Azure portal not shows this App Service Plan
Azure CLI shows this App Service Plan
Azure CLI can't delete this App Service Plan

Tried 2.38.0, 2.44.0, 2.45.1 and no result.

After several(10-30) runs with CLI I am able to delete App Service Plan
And sometimes I can run terraform correctly

**Comment by tombuildsstuff** [comment]
hi @LeveniukVladyslavAllUnic 

Thanks for opening this issue.

Unfortunately there's not enough information above for us to diagnose this - which is why we ask users [complete the issue template when opening an issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md), since it contains all of the information we need. Taking a look through I'd guess this is related to using an older version of Terraform Core where the dependencies between modules weren't calculated correctly/consistently prior to 0.14, but unfortunately there's not enough context above to confirm that.

As such I'm going to close this issue for the moment, but I'd suggest upgrading to the latest version of Terraform Core (0.14.x) and the Azure Provider (v2.45.1 at the time of writing) - if that doesn't work feel free to reopen this issue [completing the bug report form, which contains the additional context we need](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md) and we can take another look :)

Thanks!
