### ISSUE TITLE
Authenticating to Azure using the Azure cli returns 'authentication error'

### ISSUE THREAD

**Issue by martynas-m** [terraform-providers/terraform-provider-azurerm#10541]
following azure provider guide at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/guides/azure_cli.
versions:
```
> terraform version
Terraform v0.14.6
+ provider registry.terraform.io/hashicorp/azurerm v2.46.1


>az --version
azure-cli                         2.19.1

core                              2.19.1
telemetry                          1.0.6

Python location '/opt/azure-cli/bin/python'
Extensions directory '/home/martynas/.azure/cliextensions'

Python (Linux) 3.9.1 (default, Feb  6 2021, 06:49:13) 
[GCC 10.2.0]

Legal docs and information: aka.ms/AzureCliLegal


Your CLI is up-to-date.
```
Have logged in to azure:
```
> az account show
{
  "environmentName": "AzureCloud",
  "homeTenantId": "xxx",
  "id": "xxx",
  "isDefault": true,
  "managedByTenants": [],
  "name": "xxx",
  "state": "Enabled",
  "tenantId": "xxx",
  "user": {
    "name": "xxx,
    "type": "user"
  }
}
```
trying very basic script to create `resource group`:
```
# Configure the Azure provider
terraform {
  required_providers {
    azurerm = {
      source = "hashicorp/azurerm"
      version = ">= 2.26"
    }
  }
}

provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "test-rg"
  location = "northeurope"
}
```

when running `terraform plan` after very long wait get this error:
```
Error: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure sending request: StatusCode=0 -- Original Error: Get "https://management.azure.com/subscriptions/xxx/providers?api-version=2016-02-01": dial tcp: lookup management.azure.com on [::1]:53: read udp [::1]:49204->[::1]:53: read: connection refused

  on main.tf line 11, in provider "azurerm":
  11: provider "azurerm" {

```
if I click on link in error, I get following error:
```
{"error":{"code":"AuthenticationFailed","message":"Authentication failed. The 'Authorization' header is missing."}}
```
note, if I use azure cli command  to create `resource group` from same command line, it works:
```
> az group create --name test-az-cli --location northeurope
{
  "id": "/subscriptions/xxx/resourceGroups/test-az-cli",
  "location": "northeurope",
  "managedBy": null,
  "name": "test-az-cli",
  "properties": {
    "provisioningState": "Succeeded"
  },
  "tags": null,
  "type": "Microsoft.Resources/resourceGroups"
}
```

It seems terraform can not use azure cli current logged in user. Or there is something missing in guide pages.

**Comment by martynas-m** [comment]
any comments?

**Comment by jimmythomson** [comment]
This may not be useful info, but I see this issue on my Linux machine, but not on my Mac.

**Comment by tombuildsstuff** [comment]
hi @martynas-m 

Thanks for opening this issue.

Taking a look through here this appears to be a networking issue on the host being used, where the Provider can't communicate using IPv6 to `management.azure.com` (the `[::1]:53: read udp [::1]:49204->[::1]:53: read: connection refused` part of this). Whilst the Provider itself doesn't make direct use of IPv6 (we speak to hostnames directly), it appears that an IPv6 address is being returned but isn't routable - as such I'd recommend confirming that it's possible to access `management.azure.com` on port `443` using IPv6 (or alternatively disabling IPv6 otherwise, if it's not routable).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by jimmythomson** [comment]
@martynas-m - in case it's relavant to you, or anyone else reading this, I'm using Arch Linux and had previously setup `systemd-resolved` for network name resolution. I'd missed the symlink part of the installation mentioned here: https://wiki.archlinux.org/title/Systemd-resolved#Configuration - after adding that it started working for me.
