### ISSUE TITLE
Error creating / access storage accounts

### ISSUE THREAD

**Issue by yanxke** [terraform-providers/terraform-provider-azurerm#10584]
Terraform 0.14.6
AzureRM provider  2.47.0

Error: Error reading queue properties for AzureRM Storage Account "XXXX": queues.Client#GetServiceProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthenticationFailed" Message="Server failed to authenticate the request. Make sure the value of Authorization header is formed correctly including the signature.\nRequestId:XXXXX\nTime:2021-02-14T22:21:38.2004062Z"

It was working fine just yesterday.

**Comment by tombuildsstuff** [comment]
hi @yanxke 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
