### ISSUE TITLE
How to enable  monitor insight for vmss in azure

### ISSUE THREAD

**Issue by Vj1422github** [terraform-providers/terraform-provider-azurerm#10601]
How to enable  monitor insight for vmss in azure

**Comment by tombuildsstuff** [comment]
hi @Vj1422github 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
