### ISSUE TITLE
Creation of azure_policy_definition fails probably because of  'eventual consistency' of Azure API

### ISSUE THREAD

**Issue by bec-zxh** [terraform-providers/terraform-provider-azurerm#10630]
### Terraform 
version: 2.47.0

### Impacted resources:
* `azurerm_policy_definition`
* `azurerm_policy_set_definition (probably)`
* `azurerm_policy_assignment (probably)`

## Input file to Terraform module
```json
{
  "display_name": "Check if all resources are deployed in correct location.",
  "mode": "All",
  "metadata": {
    "category": "General"
  },
  "policy_rule": {
    "if": {
      "not": {
        "field": "location",
        "in": "[parameters('allowedLocations')]"
      }
    },
    "then": {
      "effect": "audit"
    }
  },
  "parameters": {
    "allowedLocations": {
      "type": "Array",
      "metadata": {
        "description": "The list of allowed locations for resources.",
        "displayName": "Allowed locations",
        "strongType": "location"
      }
    }
  }
}
```

## Terraform module code working on list of decoded json files
```hcl
resource "random_string" "policy_definition_name" {
  length  = 24
  special = false
  upper   = false
  number  = false
}

resource "azurerm_policy_definition" "policy" {
  for_each = local.policy_definitions

  name         = random_string.policy_definition_name.result
  policy_type  = "Custom"
  mode         = each.value.mode
  display_name = each.value.display_name
  metadata     = jsonencode(each.value.metadata)
  policy_rule  = jsonencode(each.value.policy_rule)
  parameters   = jsonencode(each.value.parameters)
}
```

### Debug Output
```
azurerm_policy_definition.policy["audit_location"]: Creating...

Error: A resource with the ID "/subscriptions/271c4ae2-d7eb-4ad6-bb41-689720ff5107/providers/Microsoft.Authorization/policyDefinitions/xwtxoqdbbvbuglbdvmbwwgql" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_policy_definition" for more information.

  on main.tf line 20, in resource "azurerm_policy_definition" "policy":
  20: resource "azurerm_policy_definition" "policy" {
```

### Expected Behaviour

Azure policy definition should be created correctly.

### Actual Behaviour

Creation fails because of problem with parameters definition.
Also resource is being created but not kept in Terraform state.

### Steps to Reproduce

Occurs randomly on azure_policy_definition creation

**Comment by tombuildsstuff** [comment]
hi @bec-zxh 

Taking a look through here it appears that the same random string is being used as a name for all of the resources, when this needs to be unique per resource - which is why Terraform's detected that an existing resource exists here.

Due to the Azure API being (mostly) Upserts - that is creating a resource if it doesn't exist, but updating it if it does - Terraform checks for the presence of an existing resource with the same identifier during creation, to ensure that we don't adopt resources unintentionally. As such you should be able to fix this by updating the names to be unique per resource (such as generating a unique name for each Policy Definition) - since the name is a unique identifier for these resources.

Since this is a question regarding Terraform Configuration, rather than a bug in the Azure Provider I'm going to close this issue for the moment - but should you have further usage questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by bec-zxh** [comment]
Problem was 'for_each' on azure_policy_definition but just one random_string for names.
It had to fail.
Sorry to bother you.
