### ISSUE TITLE
azurerm_postgresql_active_directory_administrator takes too long to deploy/destroy

### ISSUE THREAD

**Issue by MilheiroSantos** [terraform-providers/terraform-provider-azurerm#10701]
Hi! I'm trying to deploy an `azurerm_postgresql_active_directory_administrator` resource and deploying this resource takes around 10 minutes to deploy and destroy. In the portal, adding an AD admin is much faster (around 2minutes). 

### Community Note
* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.48.0

### Affected Resource(s)
* `azurerm_postgresql_active_directory_administrator`

### Terraform Configuration Files
```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.48.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = "=1.4.0"
    }
  }
}

provider "azuread" {}
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "this" {
  name     = "test-rg"
  location = "West Europe"
}

resource "azurerm_postgresql_server" "this" {
  name                = "test-psql"
  location            = azurerm_resource_group.this.location
  resource_group_name = azurerm_resource_group.this.name

  administrator_login          = "psqladmin"
  administrator_login_password = "somePassword!"

  sku_name   = "GP_Gen5_2"
  version    = "11"
  storage_mb = 51200

  ssl_enforcement_enabled = true
}

data "azurerm_client_config" "current" {}

resource "azuread_group" "group" {
  display_name = "TestGroup"
}

resource "azurerm_postgresql_active_directory_administrator" "this" {
  server_name         = azurerm_postgresql_server.this.name
  resource_group_name = azurerm_resource_group.this.name
  tenant_id           = data.azurerm_client_config.current.tenant_id

  login = azuread_group.group.name
  object_id = azuread_group.group.object_id
}
```

### Debug Output
https://gist.github.com/MilheiroSantos/95ae148be445c225ca66024be9bfdaa1

### Expected Behaviour
The resource `azurerm_postgresql_active_directory_administrator` should take around 2min to deploy/destroy. This would be in line with the time taken in the azure Portal.

### Actual Behaviour
The resource `azurerm_postgresql_active_directory_administrator` takes around 10m to deploy/destroy

### Steps to Reproduce
1. `terraform apply`
2. `terraform destroy`

**Comment by tombuildsstuff** [comment]
hey @MilheiroSantos 

Terraform leans on the Azure API here, using [the Future concept](https://github.com/terraform-providers/terraform-provider-azurerm/blob/a38f862a98a787bf1ba547ebcc8a4921b6c5d920/azurerm/internal/services/postgres/postgresql_aad_administrator_resource.go#L101-L108) within the Azure SDK for Go to say "Create this then wait for it to become Ready" (as we do with other resources). In this instance it appears this is an issue within the Azure API, my guess is that the Azure Portal is deploying an ARM Template behind the scenes, rather than using this API here - which would lead to the speed difference (since this is only firing the initial request rather than waiting until the API says it's finished provisioning).

Since this appears to be an issue within the Azure API, rather than something specific to Terraform here - I'm going to close this issue for the moment - but I'd suggest [reopening this on the Azure API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the API Team should be able to investigate this further (since once this is fixed in the API, Terraform will speed up automatically).

Thanks!

**Comment by MilheiroSantos** [comment]
Awesome! Thank you very much for your help!
