### ISSUE TITLE
Does Terraform have provider for Azure China Cloud?

### ISSUE THREAD

**Issue by syedinfy** [terraform-providers/terraform-provider-azurerm#10705]
Does Terraform have provider for Azure China Cloud?  Or can we use azurerm for Azure China Cloud? Please help me.

I had used azurerm provider & tried to create infrastructure in Azure China CLoud. But i am unable to do so.

**Comment by tombuildsstuff** [comment]
hi @syedinfy 

[The `environment` field within the `provider` block](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs#environment) allows you to connect to different Azure Environments.

This forum is for Bug Reports and Feature Requests, as such we direct questions towards [the Community Discuss forum](https://discuss.hashicorp.com) - since this is a usage question I'm going to close this issue for the moment, but should you have further questions I'd point you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
