### ISSUE TITLE
Terraform import fails due to mismatch of Resource ID

### ISSUE THREAD

**Issue by meduriraghava** [terraform-providers/terraform-provider-azurerm#10709]
### Affected Resource(s)

azurerm_cdn_endpoint
```terraform
resource "azurerm_container_registry" "XXX_acr" {
	name 					        = var.container_registry_name
	resource_group_name 	                 = var.resource_group_name
	location			                 	      = var.region
	sku						        = "Basic"
	admin_enabled			    = false
}
```

### Expected Behaviour

Terraform should be able to import the resource into a state file

### Actual Behaviour

Error: Cannot import non-existent remote object

While attempting to import an existing object to
azurerm_cdn_endpoint.trend_card_endpoint, the provider detected that no object
exists with the given id. Only pre-existing objects can be imported; check
that the id is correct and that it is associated with the provider's
configured region or endpoint, or use "terraform apply" to create a new remote
object for this resource.

### Steps to Reproduce

terraform import azurerm_cdn_endpoint.<resource namee> /subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Cdn/profiles/XXX/endpoints/XXX.azureedge.net

**Note:**

I have noticed a Resource Id mismatch from the terraform expectation vs in Azure actual resource Id.

Terraform expecting: /subscriptions/XXX/resourceGroups/XXX/
As per resource ID which created: /subscriptions/XXXX/resourcegroups/XXX

1. Please note the "g" above
2. we are using the latest azure module i.e., 2.48.0

**Comment by tombuildsstuff** [comment]
hi @meduriraghava 

Thanks for opening this issue.

Taking a look through it appears the resource in question doesn't exist at import time, which is why Terraform is returning this error - however unfortunately your example configuration and resource id's/logs above don't match up, so there's not enough information for us to confirm the specific issue here. Whilst Terraform is concerned with the casing of the Resource ID's to a point, the `resourcegroups` verses `resourceGroups` at import time won't make a difference here - it's plausible the Subscription ID used for authenticating to the current subscription (for example coming from the Azure CLI) doesn't match the one in the Resource ID.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
