### ISSUE TITLE
cosmosdb virtual_network_rule forces an id

### ISSUE THREAD

**Issue by tommyforlini** [terraform-providers/terraform-provider-azurerm#10720]
When creating an `azurerm_cosmosdb_account` the optional block `virtual_network_rule` when declared requires the `id` attribute.
Reference: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account#virtual_network_rule

We have a scenario when some teams will want to supply a vnet rule and sometimes other teams will not!
The `id` attribute must be a valid vnet URI and cannot be `""` or `" "` or `{}` or `[]` or `null`

### Valid scenario with config:
- var.enable_virtual_network_filter = true
- var.virtual_network_id = "/subscriptions/XXX/resourceGroups/XXX/providers/Microsoft.Network/virtualNetworks/XXX/subnets/Servers"

```
resource "azurerm_cosmosdb_account" "cosmosdb-account" {
   
	is_virtual_network_filter_enabled  = var.enable_virtual_network_filter

	virtual_network_rule  {
		id = var.virtual_network_id
	}
}
```

### Invalid scenario with config:
- var.enable_virtual_network_filter = false
- var.virtual_network_id = ""

```
resource "azurerm_cosmosdb_account" "cosmosdb-account" {
   
	is_virtual_network_filter_enabled  = var.enable_virtual_network_filter

	virtual_network_rule  {
		id = var.virtual_network_id
	}
}
```

Is there a way to have `id` be less restrictive and when a null/blank/empty valid is supplied, that it be treated as a skipped terraform action?

**Comment by tombuildsstuff** [comment]
hi @tommyforlini

In this instance you should be able to coalesce the `virtual_network_rule` block, rather than the `id` field within it - for example:

```
virtual_network_rule = var.virtual_network_id != "" ? [{ id = var.virtual_network_id }] : null
```

Since this is a configuration issue (and this forum is focused on bugs/feature requests), I'm going to close this issue for the moment - but should you have further usage questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
