### ISSUE TITLE
azurerm remote backend:  statefile always downloaded

### ISSUE THREAD

**Issue by marchesir** [terraform-providers/terraform-provider-azurerm#10749]
hi,

im using azurerm with remote state storage backend which stores the statefile in azure storage as reccomended.
i was under the impression the statefile stays on the remote storage but have noticed the following where terraform is run from:
.terraform
  providers
 terraform.tfstate --> all secrets  are visible in clear text 

is this expected behaviour? it seems to be poor from security point of view considering the promise of using secure backend being encrpyted on disk and in transit.

iv seen this on all versions of terraform from v0.12 to latest stable and tried on latest azurerm v2.49.0 and on old version backto v2.0.0.

regards

**Comment by tombuildsstuff** [comment]
hi @marchesir 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by marchesir** [comment]
thanks @tombuildsstuff i have posted my question on the terraform community forum
