### ISSUE TITLE
Expected application_type to be one of [web other java MobileCenter phone store ios Node.JS], got Web

### ISSUE THREAD

**Issue by SpartanDoll** [terraform-providers/terraform-provider-azurerm#10862]
**Previous Terraform Version**: 0.13.0
**AzureRM Version**: 2.13.0

**New Version Terraform**: 0.14.0
**AzureRM Version**: 2.13.0

**Affected Resource(s)**:
azurerm_application_insights

When we upgraded to version 0.14.0 of Terraform we get the following error:
"Expected application_type to be one of [web other java MobileCenter phone store ios Node.JS], got Web."

We know it is case sensitive but our environment is already set  "Web".

I read this issue since it was the same issue we are running into:

https://github.com/terraform-providers/terraform-provider-azurerm/issues/6259

We do have the following code set: but it seems to have no effect:
  lifecycle {
      ignore_changes = [
        application_type
      ]
    }

We still get the same error.  This is blocking us.  How can we resolve this issue?  Thank you in advance.

**Comment by tombuildsstuff** [comment]
hi @SpartanDoll 

Thanks for opening this issue.

the casing you're specifying is `Web` but the validation for this requires `web` - as per the message above: `Expected application_type to be one of [web other java MobileCenter phone store ios Node.JS], got Web.` - as such it should be possible to fix this by updating the casing from `web` to `Web` to match what the API needs and thus Terraform is validating for here.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
