### ISSUE TITLE
Support for automatically mounting a blob container or fileshare to a vm during provisioning stage

### ISSUE THREAD

**Issue by rbavery** [terraform-providers/terraform-provider-azurerm#10883]
Use-cases
Allows users to easily work with cloud storage using the local filesystem, which is common in data science.

Attempted Solutions
There's very little support on google for this, the main suggestion is to manually edit /etc/fstab after provisioning the vm to persistently mount the vm: https://www.reddit.com/r/AZURE/comments/f7ohk7/how_to_mount_azure_file_share_automatically_in/
https://stackoverflow.com/questions/61505944/get-mount-script-from-azure-file-share-terraform

**Comment by tombuildsstuff** [comment]
hi @rbavery 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
