### ISSUE TITLE
Changing tags in resource_group forces replacement of lot of resource

### ISSUE THREAD

**Issue by lsmadja** [terraform-providers/terraform-provider-azurerm#10895]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.14.7
hashicorp/azurerm v2.50.0

### Affected Resource(s)

* `azurerm_resource_group`
* `azurerm_linux_virtual_machine`
* `data.azurerm_image`

### Terraform Configuration Files

```hcl
```

### Expected Behaviour

Plan just change Tags of resource_group

### Actual Behaviour

TF Plan want forces replacement of a lot of resource like azurerm_linux_virtual_machine, data.azurerm_image and the tags of resource_group.

If i change the tags manualy in Azure Console, afeter, no changes are need with TF Plan

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @lsmadja 

Thanks for opening this issue.

Taking a look through here unfortunately this sounds like a configuration error, but unfortunately there's not enough information above for us to investigate further. Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
