### ISSUE TITLE
Support for ADLS container soft delete

### ISSUE THREAD

**Issue by Pravallika1995** [terraform-providers/terraform-provider-azurerm#10910]
azurerm_storage_data_lake_gen2_filesystem
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_data_lake_gen2_filesystem

Is support available from terraform to enable soft delete adls container?
![image](https://user-images.githubusercontent.com/44968251/110579213-51a36780-818c-11eb-906e-1f60060130a5.png)

**Comment by Pravallika1995** [comment]
Any update on this?

Is there a plan to provide support for the request?

**Comment by jcanizalez** [comment]
Hi @Pravallika1995 

I raised a PR #11131 in order to get this feature. Please take note new attribute container_retention_policy will be included in azurerm_storage_account.blob_properties  https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#blob_properties

Because this feature is part of blob service and not specific for azurerm_storage_data_lake_gen2_filesystem
