### ISSUE TITLE
azurerm_backup_protected_file_share is not working

### ISSUE THREAD

**Issue by sean-t-shen** [terraform-providers/terraform-provider-azurerm#10927]
I have a regular Azure file share, and I need terraform to help me configure backup for it.

After following the instructions documented here, I am getting the error:

Error: Error creating/udpating Azure File Share backup item "AzureFileShare;confluence-fs-backup" (Vault "confluence-rvault"): backup.ProtectedItemsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="BMSUserErrorDataSourceObjectNotFound" Message="Item not found.\r\nSelected item might have been deleted. Please check if item is registered to the vault."

  on jira-confluence-backup.tf line 74, in resource "azurerm_backup_protected_file_share" "confluence":
  74: resource "azurerm_backup_protected_file_share" "confluence" {

**Comment by sean-t-shen** [comment]
My storage account detail is this
===============================
Performance/Access tier
:
Standard/Hot
Replication
:
Geo-redundant storage (GRS)
Account kind
:
StorageV2 (general purpose v2)

===============================

The CIFS file share under this storage account is called "confluence-fs-backup"

Appreciate the help in advance.
Sean

**Comment by tombuildsstuff** [comment]
hi @sean-t-shen 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
