### ISSUE TITLE
Use a system assigned identity with an aks cluster and BYO Private DNS Zone

### ISSUE THREAD

**Issue by MikeForster100** [terraform-providers/terraform-provider-azurerm#10940]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Amending my AKS cluster terraform script to use a user assigned identity instead of a system assigned identity to try to enable byo private dns zones gives me errors on my disk encryption set for the nodes........ expects a system managed identity only.

Would be so much easier to use a system identity :)

### New or Affected Resource(s)

If i set this to user assigned identity i get an error from my disk encryption set which is expecting a system managed identity

azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @MikeForster100 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
