### ISSUE TITLE
azurerm_kubernetes_cluster with aci_connector_linux  enabled

### ISSUE THREAD

**Issue by bcochofel** [terraform-providers/terraform-provider-azurerm#10966]
I'm deploying an AKS cluster with ACI connector enabled and the aci-connector-linux pod is always in crashloopback. Checking the logs I've noticed that the identity that gots created doesn't have permissions if we provide the aci subnet on different RG and that identity doesn't get exported. 

I'm using azurerm v2.51.0

**Comment by bcochofel** [comment]
Is there a way we can get the identity that gets created so we can add the role assignment? What role does the identity needs?

**Comment by tombuildsstuff** [comment]
hi @bcochofel 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by bcochofel** [comment]
Hi @tombuildsstuff thanks for the answer. I thought that this could be something that could be added to the resource since the other identities that get created you can access after the apply like

```
azurerm_kubernetes_cluster.aks.addon_profile[0].oms_agent[0].oms_agent_identity[0].object_id
```

and this one (the one that's created for the ACI connector add-on) is not exported. This way we could add the role assignment after the cluster deployed.

Thanks anyway
