### ISSUE TITLE
Problem to create azure netapp volume

### ISSUE THREAD

**Issue by Lynda-Ferhat** [terraform-providers/terraform-provider-azurerm#10976]
I have a problem deploying a netapp volume on azure:

protocols = ["CIFS","NFSv3"]

Error: An argument named "protocols" is not expected here.

Thank you

**Comment by tombuildsstuff** [comment]
hi @Lynda-Ferhat 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
