### ISSUE TITLE
azurerm_kubernetes_cluster: Destroy does not destroy object

### ISSUE THREAD

**Issue by Ycallaer** [terraform-providers/terraform-provider-azurerm#1101]
### Terraform Version
Terraform v0.11.4
+ provider.azurerm v1.3.2
+ provider.null v1.0.0

### Affected Resource(s)
azurerm_kubernetes_cluster

### Terraform Configuration Files
```hcl
resource "azurerm_kubernetes_cluster" "kube_cluster" {
  name                = "${var.kubernetesClusterName}"
  location            = "${data.azurerm_resource_group.kafka_aks_res_group.location}"
  resource_group_name = "${data.azurerm_resource_group.kafka_aks_res_group.name}"
  dns_prefix          = "${var.kubernetesClusterName}"

  linux_profile {
    admin_username = "${var.adminUsersname}"

    ssh_key {
      key_data = "${var.sshKeyData}"
    }
  }

  agent_pool_profile {
    name            = "${var.PoolName}"
    count           = "${var.PoolNodeCount}"
    vm_size         = "${var.PoolVmSize}"
    os_type         = "Linux"
    os_disk_size_gb = "${var.PoolDiskSizeGb}"
  }

  service_principal {
    client_id     = "${var.azureClientId}"
    client_secret = "${var.azureClientSecret}"
  }

  tags {
    Environment = "Production"
  }
}
```

### Expected Behavior
When running terraform destroy I would have expected the Container service to be destroyed

### Actual Behavior
```
terraform destroy
data.azurerm_resource_group.kafka_aks_res_group: Refreshing state...
Do you really want to destroy?
  Terraform will destroy all your managed infrastructure, as shown above.
  There is no undo. Only 'yes' will be accepted to confirm.

  Enter a value: yes


Destroy complete! Resources: 0 destroyed.
```
It detected no resources were destroyed

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1.  Just create a kubernetes cluster on azure but select a machine type that doesn't exist in the region
2. after terraform apply you will get an error
3. Changed the value of the server type , then terraform apply which resulted in an error that VM type could not be updated
4. Run `terraform destroy`, it will show that 0 resources were destroyed and the managed container service will still be there in the portal

As an extra note: It is important to let the initial deployment fail (by using invalid server type for instance). If the deployment goes through fine the destroy works just fine

**Comment by tombuildsstuff** [comment]
hi @Ycallaer 

Thanks for opening this issue :)

> As an extra note: It is important to let the initial deployment fail (by using invalid server type for instance). If the deployment goes through fine the destroy works just fine

Terraform can only manage resources that have been successfully provisioned; when a provisioning failure happens (such as in this case) the Operator needs to decide how to proceed - such as deleting the failed resource (such as when there's a capacity issue in Azure) or by Importing it back into Terraform using [the `terraform import` command](https://www.terraform.io/docs/import/index.html). 

Whilst we may be able to do something to determine how to recover automatically, there's no guarantee that wouldn't cause issues elsewhere since no two environments are the same (which is why the operator needs to decide how to proceed).

In most cases (across all Terraform providers) provisioning and other failures on creation typically mean the resource wasn't created and there's typically nothing to clean up. This however isn't true for Azure and some other APIs. We current don't offer any more convenient way to recover from such scenarios, but it is something we might look into in the future

> Terraform Version
>> Terraform v0.11.4

Unfortunately Terraform v0.11.4 shipped with a bug on Windows where resources weren't tracked in the state - would it be possible for you to upgrade to Terraform v0.11.6 and take another look?

Thanks!

**Comment by Ycallaer** [comment]
Hi Tom,
Ok thanks for the explanation, I upgraded to the new version but the failure still exists.
I get that terraform only manages successful executed statements, but it does create a part of the deployment namely the "Container service (managed)".

What is weird is that after the failed deploy the `terraform refresh` does not state that the state file is empty ( so it has knowledge of an object)

```
terraform refresh
data.azurerm_resource_group.kafka_aks_res_group: Refreshing state...
```
After running destroy (which doesn't do anything) the same command states that there is nothing in the state file

```
terraform refresh
Empty or non-existent state file.

Refresh will do nothing. Refresh does not error or return an erroneous
exit status because many automation scripts use refresh, plan, then apply
and may not have a state file yet for the first run.
```
Might indeed be azure specific, just wanted to verify if it is a bug or known behaviour

**Comment by tombuildsstuff** [comment]
hey @Ycallaer 

> Empty or non-existent state file.

Based on this line in the console output the resources created using Terraform 0.11.4 weren't added to the Statefile which keeps track of all of the resources Terraform's interacted with (which is the known issue).
As such for Terraform to track these issues you can Import these resources into Terraform (via `terraform import`) such [as like this for a Kubernetes Cluster](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#import) - after which time this should work as expected. This'll also work as expected for any new resources created via `terraform apply`.

Hope that helps :)

**Comment by lukemao** [comment]
Hey @tombuildsstuff 
I am still having this issue with version 0.11.11_linux_amd64

I am using terraform on Google Cloud
