### ISSUE TITLE
for existing resources that don't exist in state, option to skip & import it to state, or recreate it

### ISSUE THREAD

**Issue by smartpcr** [terraform-providers/terraform-provider-azurerm#11050]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I am creating over 1000 of azurerm_monitor_metric_alert using loop, with different thresholds and severities for ~100 resources.  When I have "resource already exist" error, it's impossible to use `terraform import` and specify each resource_id

Would like the option to just skip them if resource already exists and add the resource to state.

### New or Affected Resource(s)

* azurerm_monitor_metric_alert 

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_monitor_metric_alert" "alert_sev2" {
  create_option {
    overwrite = true
    fail_on_existing = false
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @smartpcr 

Thanks for opening this issue

In version 2.0 of the Azure Provider we fixed a bug where resources that already existed in Azure could be "adopted" by Terraform, since Azure has Upsert API's for a lot of API's (more details can be found in #2807). This is important because whilst some Azure API's have Upsert API's - certain fields can only be changed on existing resources by deleting/re-creating these resources.

As such when attempting to "create" a resource in version 2.0 or later of the Azure Provider, we first check for the presence of an existing resource with the same Name and Resource Group in Azure - and if this exists we ask that users import this via the error you're seeing. Since Terraform is Stateful (and tracks the State of resources in it's Statefile) - these resources which Terraform may think it can "create" (but already exist) need to be imported into the Statefile via Terraform's Import functionality. 

As such you'll need to import these existing resources into the Statefile so that Terraform can detect changes to them - details of how to import each resource can be found in the documentation for each resource ([for example, here's how to import an App Service](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#import)) - [more details on Terraform Import can be found here](https://www.terraform.io/docs/import/index.html).

Whilst as you've mentioned that may initially sound like a lot of work, it's worth noting that Terraform's import functionality is scriptable - there's tooling like [Terraformer](https://github.com/GoogleCloudPlatform/terraformer) (and [how to use that with Azure](https://github.com/GoogleCloudPlatform/terraformer#use-with-azure)) which should help you to import these resources into the state so that these can be tracked.

However from Terraform's side this behaviour is intentional to workaround bugs in the Azure API's - and as such isn't something we plan to provide a feature-flag for at this time - so whilst I'd like to thank you for opening this feature request I'm going to close this for the moment.

Thanks!
