### ISSUE TITLE
Storage Shares attached to "BlobStorage" storage account will break state

### ISSUE THREAD

**Issue by benny-gold** [terraform-providers/terraform-provider-azurerm#1105]
Hi there,

### Terraform Version
terraform 0.11.6
azurerm v1.1.1

### Affected Resource(s)
-azurerm_storage_account
-azurerm_storage_share

### Terraform Configuration Files
```hcl
resource "azurerm_storage_account" "test" {
  name                     = "issueteststorage"
  resource_group_name      = "${azurerm_resource_group.test.name}"
  location                 = "${var.location}"
  account_tier             = "${var.account_tier}"
  account_replication_type = "${var.account_replication_type}"

  account_kind = "BlobStorage"
  tags         = "${local.common_tags}"
}

resource "azurerm_storage_share" "shares" {
  name = "${lookup(var.test, count.index)}"

  resource_group_name  = "${azurerm_resource_group.test.name}"
  storage_account_name = "${azurerm_storage_account.test.name}"
  count                = 6
}
```

### Debug Output
https://gist.github.com/benny-gold/8f0a8867cd3e77e01d0a3ab8ba46268d

### Panic Output
n/a

### Expected Behavior
Changing the storage type to BlobStorage and commenting out the `azurerm_storage_share` resource(s) should allow you to recover from this.

### Actual Behavior
A storage account that is (mistakenly) created as `account_kind = "BlobStorage"` with `azurerm_storage_share` resource(s) attached to it will fail (correctly) - The issue is that your state file is updated with the file shares which cannot be queried. Updating state or deleting storage account manually is required. 

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply` - observe failure
1. Change `account_kind` to `Storage`
1. `terraform apply` - observe failure
1. Comment out/Remove `azurerm_storage_share` resource
1. `terraform refresh` - observe failure

### Important Factoids
n/a
### References
n/a

**Comment by tombuildsstuff** [comment]
hey @KyleMartin901 

Thanks for opening this issue.

Taking a look into this unfortunately this appears to be a bug in Terraform Core and as such would need to be fixed there. There's an upstream issue tracking this (https://github.com/hashicorp/terraform/issues/8099) where the Terraform Core team should be able to take a look and make a fix; but once the fix is added that should automatically become available to all providers. Since this isn't something we're able to work around in the Azure Provider directly; for the moment I'm going to close this in favour of the upstream issue https://github.com/hashicorp/terraform/issues/8099 - would you mind subscribing to that issue for updates?

Thanks!
