### ISSUE TITLE
azurerm_monitor_diagnostic_Setting - Error already exists - to be managed via Terraform this resource needs to be imported into the State.

### ISSUE THREAD

**Issue by mikeTM3** [terraform-providers/terraform-provider-azurerm#11070]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Version = Terraform v0.14.8

### Affected Resource(s)

* `azurerm_monitor_diagnostic_Setting`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
https://www.dropbox.com/s/jj3umbrveilihhk/terraformdatabase.zip?dl=0

### Debug Output

https://www.dropbox.com/s/4punljlpwz6rg1k/terraform%20debug%20output.txt?dl=0

### Expected Behaviour

Empty Azure resource group with no resources. Terraform script should create the azure monitor diagnostic setting with no errors

### Actual Behaviour

Terraform script runs, creates the azure monitor diagnostic setting but complains that the resource already exists
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @mikeTM3 

Thanks for opening this issue.

Monitor diagnostic rules live outside of the scope of a resource group in Azure and thus aren't subject to its cleanup lifecycle, whilst it's possible the resource group may not (or no longer) exist, it appears that the monitor setting is still be around, since it's still retrievable, hence this error during import.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
