### ISSUE TITLE
Question: Can we export ARM template from terraform?

### ISSUE THREAD

**Issue by TsuyoshiUshio** [terraform-providers/terraform-provider-azurerm#1119]
Hi, 

I'm wondering if we can export ARM template from terraform? 

IMO, Terraform is the best platform to deploy Azure resources. I always use it. (thank you!) ARM template is not human readable, however, it doesn't have any dependency. For this reason, sometimes, I'd like to write script with terraform, then want to convert to ARM template. Can we do it technically? If we can, and if you like, I'd like to contribute it.

**Comment by tombuildsstuff** [comment]
hi @TsuyoshiUshio 

Thanks for opening this issue :)

> ARM template is not human readable, however, it doesn't have any dependency

I'm not fully sure what you mean by this - would you be able to clarify it further?

If you're looking to use automation with Terraform (such as templating Terraform, as an example), Terraform also supports JSON as an input format in addition to HCL; however in general HCL is considerably more readable.

> I'd like to write script with terraform, then want to convert to ARM template

We have no plans to implement support for this at this time unfortunately; whilst Azure does allow for exporting ARM Templates via the Portal - that's only supported for a subset of resources (and there's an ever-growing scope). Due to this, we'd be unable to accept this as a pull request into Terraform unfortunately.

It's possible to export an ARM Template from a Resource Group through the Azure CLI, as shown below:

```
$ az group export --name tom-devrg
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
...
```

.. however as stated above this only works for resources where this functionality is supported by Azure (e.g. Key Vault Access Policies are unsupported), as shown in this output from the Azure CLI:

```
Export template operation completed with errors. Some resources were not exported. Please see details for more information.
Could not get resources of the type 'Microsoft.KeyVault/vaults/accessPolicies'. Resources of this type will not be exported.
```

Out of interest what's the problem you're looking to solve by exporting the Terraform configuration to ARM Templates?

Thanks!
