### ISSUE TITLE
Support for embedding Azure Bicep code in Terraform modules (similar to existing ARM support)

### ISSUE THREAD

**Issue by WascawyWabbit** [terraform-providers/terraform-provider-azurerm#11206]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Project Bicep makes working with ARM templates a LOT easier, but it lacks the config drift protection of Terraform's separate state file.  By contrast, the AzureRM provider for Terraform is always lagging behind on support for the latest features in Azure.

Please support the embedding of Bicep code in the AzureRM Terraform provider to allow for zero day feature support (albeit without full state file protection), without the need to mess with ARM templates directly.

### New or Affected Resource(s)

All Azure resources that are not yet supported in full by the Terraform AzureRM provider.

### Potential Terraform Configuration

No sample code.

### References

None.

**Comment by MattiasAng** [comment]
Bicep is just a layer on top of ARM templates that converts Bicep-language (?) in to ARM templates, hence there is no API or conversion API that Microsoft provides.
You can use this workaround to first compile bicep file with a local-exec and then use the ARM-template that gets generated. 

Bicep-file for creating a storage account:

````
resource stg 'Microsoft.Storage/storageAccounts@2019-06-01' = {
  name: 'storageacc12381249'
  location: 'westeurope'
  sku: {
    name: 'Standard_LRS'
  }
  kind: 'StorageV2'
  properties: {
    supportsHttpsTrafficOnly: true
  }
}

````
Terraform:
````hcl
provider "azurerm" {
  features{}
}

resource "null_resource" "example" {
  provisioner "local-exec" {
    command = "bicep build test.bicep"
  }
}

data "local_file" "foo" {
    depends_on = [ null_resource.example ]
    filename = "${path.module}/test.json"
}

resource "azurerm_resource_group_template_deployment" "example" {
    name = "example-deployment"
    resource_group_name = "example-rg"
    template_content = data.local_file.foo.content

    deployment_mode = "Complete"
}
````

**Comment by tombuildsstuff** [comment]
hey @WascawyWabbit 

Thanks for opening this issue.

As @MattiasAng has mentioned above, Bicep ultimately compiles their templating language down to ARM Templates - so ultimately support for this is already available in Terraform via the `azurerm_resource_group_template_deployment` and `azurerm_subscription_resource_group` resources.

Whilst it's possible there's a separate API for Bicep deployments in the future, at this point in time supporting these natively within Terraform would be either wrapping the Bicep binary, or reimplementing support for the entire compiler (and it's ongoing changes) within Terraform - if I'm being honest I don't think that's something we'll support natively within the provider. That said, as @MattiasAng has mentioned this can be achieved using a `null_resource` to compile the templates using the `bicep` CLI - and then the `azurerm_resource_group_template_deployment` and `azurerm_subscription_resource_group` resources to deploy the compiled template with Terraform.

However since this isn't something we plan to support natively, whilst I'd like to thank you for opening this Feature Request I'm going to close this issue for the moment.

Thanks!

**Comment by WascawyWabbit** [comment]
Cheers for the excellent workaround :)

For info, you can already deploy bicep code directly to Azure without the need to first transpile into ARM.  Microsoft is putting a lot behind the bicep project.  Shame they don't put as much behind timely releases of Azure APIs supporting the latest features.

(yes i know the issue is closed).
