### ISSUE TITLE
`azurerm_virtual_machine_extension` 'RunCommandWindows' failed when 'CustomScriptExtension' is provisioned.

### ISSUE THREAD

**Issue by channyein87** [terraform-providers/terraform-provider-azurerm#11218]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v0.13.5 (v2.20.0)

### Affected Resource(s)

* `azurerm_virtual_machine_extension `

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "custom-script" {
  name                 = "custom-script"
  virtual_machine_id   = azurerm_virtual_machine.example.id
  publisher            = "Microsoft.Compute"
  type                 = "CustomScriptExtension"
  type_handler_version = "1.9"

  settings = <<SETTINGS
    {
        "commandToExecute": "Write-Host 'Hello'"
    }
SETTINGS
}

resource "azurerm_virtual_machine_extension" "run-command" {
  name                 = "run-command"
  virtual_machine_id   = azurerm_virtual_machine.example.id
  publisher            = "Microsoft.CPlat.Core"
  type                 = "RunCommandWindows"
  type_handler_version = "1.1.8"

  settings = <<SETTINGS
    {
        "commandToExecute": "$PSVersionTable.PSVersion.ToString()"
    }
SETTINGS
}
```

### Expected Behaviour

```json
{
      "code": "ComponentStatus/StdOut/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "7.1.3",
      "time": null
    },
    {
      "code": "ComponentStatus/StdErr/succeeded",
      "displayStatus": "Provisioning succeeded",
      "level": "Info",
      "message": "",
      "time": null
    }
```

### Actual Behaviour

```
Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'run-command' with handler 'Microsoft.CPlat.Core.RunCommandWindows' already added or specified in input."
```

**Comment by tombuildsstuff** [comment]
hi @channyein87 

Thanks for opening this issue.

Looking at the API response here this appears to be a configuration issue, where multiple VM Extensions of the same type (in this instance `RunCommandWindows` cannot be added - I'm unfamiliar with this extension, but this looks like the latest incarnation of the `CustomScriptExtension` which has the same issue, where only a single instance of this can be provisioned on a Virtual Machine - which is a limitation of the Azure Platform.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
