### ISSUE TITLE
Support for specifying Subscription when creating a Resource Group

### ISSUE THREAD

**Issue by dschwinn** [terraform-providers/terraform-provider-azurerm#11313]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the Azure Portal when I create a Resource Group I am required to choose a Subscription to associate it with.  In the azurerm_resource_group I do not have the option to specify a Subscription.

![2021-04-13_13-45-16](https://user-images.githubusercontent.com/27773052/114597327-a2f8b800-9c5e-11eb-8fc3-36bce2b27575.png)

### New or Affected Resource(s)

azurerm_resource_group 

### Potential Terraform Configuration

```hcl
resource "azurerm_management_group" "this" {
  display_name               = var.management_scope
  parent_management_group_id = data.azurerm_management_group.parent_management_scope.id
  subscription_ids           = [azurerm_subscription.this.subscription_id]
}


resource "azurerm_subscription" "this" {
  subscription_name = var.management_scope
  billing_scope_id  = data.azurerm_billing_mca_account_scope.this.id
}

resource "azurerm_resource_group" "this" {
  name            = var.management_scope
  location        = "East US"
  subscription_id = azurerm_subscription.this.id
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @dschwinn 

Thanks for opening this issue.

This is achievable by setting the `subscription_id` on the provider block and then using that aliased provider using the `provider = azurerm.{providerName}` syntax [as documented here](https://www.terraform.io/docs/language/providers/configuration.html#alias-multiple-provider-configurations). Unfortunately we have no plans to introduce a `subscription_id` field onto every resource since this workflow can be achieved at the Provider level instead (which ultimately provides the same functionality when used in conjunction with a provider alias).

Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
