### ISSUE TITLE
Feature Request: azurerm_policy_assignment - add support for setting sku

### ISSUE THREAD

**Issue by russellds** [terraform-providers/terraform-provider-azurerm#1137]
Please add support for setting the sku for Azure Policy Assignments. By default the sku is "Free Tier" which doesn't support compliance tracking for Policy Assignments. Being able to set the sku to the "Standard Tier" would allow for complaince tracking.

**Comment by JasonNguyenTX** [comment]
Hi there, is there any plan on adding tier support for policy assignment?

**Comment by olohmann** [comment]
This policy SKU feature is obsolete: see [https://docs.microsoft.com/en-us/rest/api/resources/policyassignments/create#definitions](https://docs.microsoft.com/en-us/rest/api/resources/policyassignments/create#definitions)

It states: 
> The policy sku. This property is optional, obsolete, and will be ignored.

IMHO this can be closed.

**Comment by tombuildsstuff** [comment]
👋 

Taking a look into this I'd agree with @olohmann that since support for setting the SKU is deprecated (both for the Create and Create By ID API call) and as such is ignored by the API that it's not necessary to add support for this functionality at this time. If there's a different source which shows this functionality is still supported (through some other mechanism) please let us know and we can take a look into this - but for the moment I'm going to close this issue.

Thanks!
