### ISSUE TITLE
Bug: azurerm_policy_assignment errors out from azure 404 (sporadic)

### ISSUE THREAD

**Issue by tiny-dancer** [terraform-providers/terraform-provider-azurerm#1147]
Sporadically receiving TF errors on policy assignments from azure 404 responses

### Terraform Version
Terraform v0.11.5

### Affected Resource(s)
- azurerm_policy_assignment

### Terraform Configuration Files
```hcl
resource "azurerm_policy_assignment" "monitor_unprotected_web_app" {
  name                 = "monitor_unprotected_web_app"
  scope                = "/subscriptions/${data.azurerm_client_config.current.subscription_id}"
  policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/201ea587-7c90-41c3-910f-c280ae01cfd6"
  description          = "Monitor unprotected web application in Security Center"
  display_name         = "Monitor unprotected web application in Security Center"
}
```

### Debug Output
```
* module.bootstrap_subscription_policies.azurerm_policy_assignment.monitor_unprotected_web_app: 1 error(s) occurred:

* azurerm_policy_assignment.monitor_unprotected_web_app: Error waiting for Policy Assignment "monitor_unprotected_web_app" to become available: Error issuing read request in policyAssignmentRefreshFunc for Policy Assignment "monitor_unprotected_web_app" (Scope: "/subscriptions/****"): policy.AssignmentsClient#Get: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="PolicyAssignmentNotFound" Message="The policy assignment 'monitor_unprotected_web_app' is not found."
```

### Expected Behavior
Correctly assignment built-in policy to subscription

### Actual Behavior
404 response from azure causes terraform to return an error

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. `terraform apply`

### Important Factoids
This is assigning a built-in policy to azure (no dependencies within terraform)

### References
- https://github.com/terraform-providers/terraform-provider-azurerm/issues/49

**Comment by pixelicous** [comment]
@tombuildsstuff @katbyte Hi, this issue still seem to exist on 1.4.0 with latest terraform, all of the sudden all our executions started failing for no apparent reason, we didn't change anything in our code, we use direct plugins/providers from a dedicated folder. 
After upgrading to 1.7.0 this is gone! however! it might be something temporarily because we never had issues till today, so i think this is intermittent and might be related to azure as well???

**Comment by pixelicous** [comment]
@tombuildsstuff @katbyte Guys i can confirm this is happening as well. We didn't get this issue at all for many months, out of the blue this has started for us.
We are on terraform 0.11.7 and we were on azurerm provider 1.4.0. after updating to 1.7.0 we receive it less, but it is still happening, we had 5 nightly executions from which 1 has failed due to this.

Removed original names from log below.
I couldn't find anything interesting from the logs, i can forward whatever is needed as we kept them (we run all executions with TRACE)
> 
> * azurerm_storage_account.storage: Error creating Azure Storage Account "storage_account_name": storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'rg_name' could not be found."
> 2018/06/17 17:57:22 [ERROR] root.TenantOnBoard: eval: *terraform.EvalSequence, err: 1 error(s) occurred:
> 
> * azurerm_storage_account.stoage: Error creating Azure Storage Account "storage_account_name": storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'rg_name' could not be found."

**Comment by pixelicous** [comment]
Actually it seems like i hijacked this thread, i have 404 errors on resource group not found but for keyvault and storage account

**Comment by tiny-dancer** [comment]
We're also getting it on storage container

**Comment by slawchod** [comment]
Hi,

We are facing quite similar issue during policy assignment. However instead of 404 we got 500:

* azurerm_policy_assignment.workflows: policy.AssignmentsClient#Create: Failure responding to request: StatusCode=500 -- Original Error: autorest/azure: Service returned an error. Status=500 Code="InternalResourceIdentityError" Message="There was a problem communicating with the identity service. Diagnostic information: timestamp '20190606T103109Z', subscription id '', tracking id 'd*****-****-****-****-*********', request correlation id '******-****-****-****-*************'."
