### ISSUE TITLE
Support for 'AzureActiveDirectoryDiagnostics' kind in azurerm_sentinel_data_connector_*

### ISSUE THREAD

**Issue by madsaune** [terraform-providers/terraform-provider-azurerm#11565]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Today I tried to deploy "Azure Active Directory" connector in Azure Sentinel with Terraform and discovered that the resource "azurerm_sentinel_data_connector_azure_active_directory" actually deploys the "Azure Active Directory Identity Protection" connector in Sentinel instead which is not the same as "Azure Active Directory" connector.

In code, the "Azure Active Directory Identity Protection" connector is refered to as `kind: AzureActiveDirectory` which is a little confusing, since they also have the "Azure Active Directory" connector which is not related to this.

I'm not very experienced with any Azure SDK, Azure REST API or the Azure Powershell module, but I have not found anything related to the "Azure Active Directory" connector when looking. I only found one reference in another repository and there it's referenced as `kind: AzureActiveDirectoryDiagnostics`.

[Link 1](https://github.com/javiersoriano/sentinel-all-in-one/blob/a79b593e954d3a59b5916fa5436fc9c5fe697e56/connectors.json#L17-L30)
[Link 2](https://github.com/javiersoriano/sentinel-all-in-one/blob/a79b593e954d3a59b5916fa5436fc9c5fe697e56/SentinelallInOne.ps1#L345-L376)

As you might notice, in link 2, they use the `/providers/microsoft.aadiam/diagnosticSettings/AzureSentinel_${Workspace}?api-version=2017-04-01` resource instead of `securityInsights`. This indicates that maybe it belongs in the `azuread` provider, but since the Sentinel resource belongs to `azurerm` I decided to try here first.

Maybe I'm looking in the wrong place, or maybe Microsoft has not implemented this in their public API/SDKs yet, but if anyone knows how to implement this, I would be very happy!

### New or Affected Resource(s)

* azurerm_sentinel_data_connector_azure_active_directory_diagnostics

### Potential Terraform Configuration

As far as I understand, this connector allows you to choose which log types you want to stream, therefor you must be able to configure which log types you want to enable.

```hcl
resource "azurerm_sentinel_data_connector_azure_active_directory_diagnostics" "example" {
  name = ""
  log_analytics_workspace_id = ""
  log_types = ["AuditLogs", "SignInLogs", "NonInteractiveUserSignInLogs", "ServicePrincipalSignInLogs", "ManagedIdentitySignInLogs", "ProvisioningLogs", "ADFSSignInLogs"]
}
```

### References

* [https://github.com/javiersoriano/sentinel-all-in-one](https://github.com/javiersoriano/sentinel-all-in-one)
* [https://docs.microsoft.com/en-us/azure/sentinel/connect-azure-active-directory](https://docs.microsoft.com/en-us/azure/sentinel/connect-azure-active-directory)

**Comment by magodo** [comment]
@madsaune Thank you for submitting this issue 👍

The reason why we are not naming `azurerm_sentinel_data_connector_azure_active_directory` to be "Azure Active Directory Identity Protection", as which is shown on Portal, is based on its [definition in Swagger](https://github.com/Azure/azure-rest-api-specs/blob/142e0d8163a263b948f7a4d9e852102205da5441/specification/securityinsights/resource-manager/Microsoft.SecurityInsights/preview/2019-01-01-preview/SecurityInsights.json#L4889), where the Azure API names this "variant" of data connector as `AzureActiveDirectory`. This is the same practice we did for other data connectors. Choosing the Swagger definition rather than the brand name is that the former tends to be more stable than the latter. While, I'm still sorry for the confusion.

Back to the AAD Diagnostics resource you are seeking, unfortunately as you have already seen, the APIs are calling against the `microsoft.aadiam` provider, which is in the scope of AzureAD Terraform provider. The data connector itself is actually modifying the diagnostics of the AAD.

Therefore, ultimately we will need a `azuread_diagnostic_setting` resource in AzureAD provider, which has the similar schema as [`azurerm_monitor_diagnostic_setting`](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_diagnostic_setting) does, and persumably a `azuread_diagnostic_categories` data source, analogous to [`azurerm_monitor_diagnostics_categories`]( https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/monitor_diagnostic_categories).

Ping @manicminer for awareness.

**Comment by manicminer** [comment]
Hi @madsaune and @magodo, although the microsoft.aadiam RP relates to AAD, because it's still a resource manager API it should be implemented as part of AzureRM rather than AzureAD :)
