### ISSUE TITLE
Case-problem with subscriptions in resource ids

### ISSUE THREAD

**Issue by dploeger** [terraform-providers/terraform-provider-azurerm#11590]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.15.1
on linux_amd64
+ provider registry.terraform.io/hashicorp/azurerm v2.57.0

### Affected Resource(s)

* `azurerm_subnet`
* `azurerm_key_vault`

(and maybe more)

### Terraform Configuration Files

```hcl
resource "azurerm_network_security_group" "network-security-group" {
  location            = var.location
  name                = "${lower(var.project)}${lower(var.stage)}netsg"
  resource_group_name = var.resource_group
}

resource "azurerm_subnet_network_security_group_association" "network-security-group-association" {
  network_security_group_id = azurerm_network_security_group.network-security-group.id
  subnet_id                 = azurerm_subnet.default-subnet.id
}
```

### Expected Behaviour

After the first apply, there shouldn't be any changes for a next apply (if nothing was changed in the terraform files)

### Actual Behaviour

After applying, the Azure API stores the subscription part of the resource ids of the noted resources in lower case. The Terraform state, however uses the upper case. This results in changes like this:

```
  # module.azure-network.azurerm_subnet_network_security_group_association.network-security-group-association must be replaced
-/+ resource "azurerm_subnet_network_security_group_association" "network-security-group-association" {
      ~ id                        = "/subscriptions/abcdef12-1234-abcd-1234-123456789012/resourceGroups/chmdevresourcegroup/providers/Microsoft.Network/virtualNetworks/chmdevnetvnetwork/subnets/default" -> (known after apply)
      ~ subnet_id                 = "/subscriptions/abcdef12-1234-abcd-1234-123456789012/resourceGroups/chmdevresourcegroup/providers/Microsoft.Network/virtualNetworks/myvnetwork/subnets/default" -> "/subscriptions/ABCDEF12-1234-ABCD-1234-123456789012/resourceGroups/chmdevresourcegroup/providers/Microsoft.Network/virtualNetworks/myvnetwork/subnets/default" # forces replacement
        # (1 unchanged attribute hidden)
    }
```
### Steps to Reproduce

1. `terraform apply`
2. `terraform apply`

**Comment by dploeger** [comment]
A possible workaround for azurerm_subnet would be the following:

```hcl
resource "azurerm_network_security_group" "network-security-group" {
  location            = var.location
  name                = "${lower(var.project)}${lower(var.stage)}netsg"
  resource_group_name = var.resource_group
}

locals {
  subnet_id = replace(
    replace(lower(azurerm_subnet.default-subnet.id), "microsoft.network/virtualnetworks", "Microsoft.Network/virtualNetworks"),
    "resourcegroups",
    "resourceGroups"
  )
}

resource "azurerm_subnet_network_security_group_association" "network-security-group-association" {
  network_security_group_id = azurerm_network_security_group.network-security-group.id
  subnet_id                 = local.subnet_id
}
```

**Comment by magodo** [comment]
@dploeger Thank you for openning this issue!

The fact here is that the Provider will store the ID segment (e.g. the subscription id, the subnet name) as what is returned from the Azure API via the `GET` operation, where the Azure will (for most resources) return the ID by lowercasing the subscription ID. Persumbly you have specified your subscription ID in uppercase when creating the subnet, which results into the diff as shown above.

The ideal solution for this mismatch is to ask service team to not changing the case in the response, there are a bunch of related issues being opened here: https://github.com/Azure/azure-rest-api-specs/issues?q=is%3Aissue+is%3Aopen+in%3Atitle+case (while there is slow progress going forward).

Another way to workaround this is to specify your subscription ID via lowercase at the first place (e.g. in the `ARM_SUBSCRIPTION_ID` environment variable).

Since this is more an Azure issue than the provider, I'm gonna close this issue for now. Please feel free to reopen it if you have any further question, or ask in one of the [Community Resources](https://www.terraform.io/community.html).
