### ISSUE TITLE
Front Door: Upgrade 2.57 -> 2.58 breaks on existing FD instances with inline HTTPS configuration

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#11623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

AzureRM: 2.57 & 2.58
Terraform: 0.14.11

### Affected Resource(s)

* `azurerm_frontdoor`
* `azurerm_frontdoor_custom_https_configuration`

### Terraform Configuration Files

For 2.57

```hcl
resource "azurerm_frontdoor" "fd" {
  name                                         = "sample-frontdoor-brc"
  resource_group_name                          = azurerm_resource_group.rg.name
  enforce_backend_pools_certificate_name_check = true
  tags = {
    "Version" = "4.0.2"
  }

  backend_pool {
    health_probe_name   = "health-probe"
    load_balancing_name = "backend-lb"
    name                = "backend"
    backend {
      address     = "www.bing.com"
      host_header = "www.bing.com"
      http_port   = 80
      https_port  = 443
    }
  }

  backend_pool_load_balancing {
    name = "backend-lb"
  }

  backend_pool_health_probe {
    <snipped for brevity>
  }

  frontend_endpoint {
    name      = "default"
    host_name = "sample-frontdoor-brc.azurefd.net"
  }

  frontend_endpoint {
    name      = "custom"
    host_name = "sample-frontdoor-brc.sandbox.provider.engineering"

    custom_https_provisioning_enabled = true
    custom_https_configuration {
      certificate_source = "FrontDoor"
    }
  }

  routing_rule {
     <snipped for brevity>
  }
}
```

For 2.58

```hcl
resource "azurerm_frontdoor" "fd" {
  name                                         = "sample-frontdoor-brc"
  resource_group_name                          = azurerm_resource_group.rg.name
  enforce_backend_pools_certificate_name_check = true
  tags = {
    "Version" = "4.0.2"
  }

  backend_pool {
    <snipped for brevity>
  }

  backend_pool_load_balancing {
    name = "backend-lb"
  }

  backend_pool_health_probe {
    <snipped for brevity>
  }

  frontend_endpoint {
    name      = "default"
    host_name = "sample-frontdoor-brc.azurefd.net"
  }

  frontend_endpoint {
    name      = "custom"
    host_name = "sample-frontdoor-brc.sandbox.provider.engineering"
  }

  routing_rule {
     <snipped for brevity>
  }
}

resource "azurerm_frontdoor_custom_https_configuration" "fd_custom_url" {
  frontend_endpoint_id              = azurerm_frontdoor.fd.frontend_endpoint[1].id
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

### Debug Output

Post a comment below if it is needed. I have to make sure that the debug output does not contain any sensitive info before I put it here in the issue or in a paste bin.

### Panic Output

N/A

### Expected Behaviour

Unsure really. Are we supposed to delete the Front Door first before going from 2.57 to 2.58? Or is it supposed to just ignore the existing certificate on the Front Door.

### Actual Behaviour

First error when running `terraform apply`:

```text
azurerm_frontdoor.fd: Modifying... [id=/subscriptions/[redacted]/resourceGroups/frontdoor-issue-brc/providers/Microsoft.Network/frontDoors/sample-frontdoor-brc]
azurerm_frontdoor.fd: Modifications complete after 3s [id=/subscriptions/[redacted]/resourceGroups/frontdoor-issue-brc/providers/Microsoft.Network/frontDoors/sample-frontdoor-brc]
azurerm_frontdoor_custom_https_configuration.fd_custom_url: Creating...

Error: updating Custom HTTPS configuration for Frontend Endpoint "custom"
(Front Door "sample-frontdoor-brc" / Resource Group "frontdoor-issue-brc"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "custom" (Resource Group "frontdoor-issue-brc"): enabling Custom Domain HTTPS for Frontend Endpoint: frontdoor.FrontendEndpointsClient#EnableHTTPS: Failure sending request: StatusCode=0 -- Original Error: Code="BadRequest" Message="That action isn’t allowed in this profile."
```

Second error when running `terraform apply`:

```text
azurerm_frontdoor_custom_https_configuration.fd_custom_url: Creating...

Error: updating Custom HTTPS configuration for Frontend Endpoint "custom" (Front Door "sample-frontdoor-brc" / Resource Group "frontdoor-issue-brc"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "custom"
(Resource Group "frontdoor-issue-brc"): enabling Custom Domain HTTPS for Frontend Endpoint:
frontdoor.FrontendEndpointsClient#EnableHTTPS: Failure sending request: StatusCode=0 -- Original Error:
Code="OperationNotAllowed" Message="Frontend endpoint custom is already secured with a managed certificate.
Only the Minimum TLS Version property for a managed certificate configuration can be updated. All other updates are not suppored."
```

### Steps to Reproduce

1. Pin your configuration to AzureRM 2.57 (or earlier)
2. Create a Front Door resource using the custom HTTPS configuration inline resource
3. `terraform apply`
4. DO NOT DESTROY!
5. Remove the pinned version so that AzureRM 2.58 can be downloaded
    1. You may have to run `terraform init -upgrade` because of the lock file
6. Remove the inline configuration in `azurerm_frontdoor`.
7. Add the custom HTTPS configuration through `azurerm_frontdoor_custom_https_configuration`
8. `terraform apply`
9. Change **nothing** and run `terraform apply` for the second error

### Important Factoids

N/A

### References

* #11456

**Comment by WodansSon** [comment]
@bcline760, thank you for opening this issue and I apologize for any confusion around the changes to Frontdoor in the v.2.58.0 release. Per the [CHANGELOG.md](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v2.58.0): 

UPGRADE NOTES

* `azurerm_frontdoor` - The `custom_https_provisioning_enabled` field and the `custom_https_configuration` block have been deprecated and has been removed as they are no longer supported. (#11456)

This is a **breaking change** that was made to the resource during the **v2.58.0** release. I should have made it more clear in the UPGRADE NOTES that you would need to manually migrate your existing settings(inline custom HTTPS settings in the main frontdoor resource) which are no longer supported, to the format 

```terraform
resource "azurerm_frontdoor_custom_https_configuration" "fd_custom_url" {
  frontend_endpoint_id              = azurerm_frontdoor.fd.frontend_endpoint[1].id
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

@timja, makes a good point in the referenced PR #11456:
> Referencing by index seems too risky, as indexes will get shuffled when you add/remove endpoints

@JayDoubleu suggested a slick workaround for the index issue:  
> I ended up with something similar `${azurerm_frontdoor.example.id}/frontendEndpoints/${local.custom_frontend_name}`
This way I don't need `depends_on` as referencing main front door adds it to dependency graph.

So to work around this issue, due to the **breaking change** what I believe you will need to do (**NOTE:** this is only for existing Frontdoor resources) will be:

**Hard Way:**
1) Delete your custom HTTPS endpoint and your inline custom HTTPS configuration settings from your configuration file.
2) `Terraform apply`, this will remove the custom HTTPS settings and reference and avoid the errors after upgrading.
3) Upgrade to `v2.58.0` of the Terraform provider
4) Manually migrate your custom HTTPS settings to the dedicated `azurerm_frontdoor_custom_https_configuration` resource and add your custom HTTPS endpoint back into your configuration file.
5) `Terraform apply`

**Easy Way:**
1) `Terraform destroy`
2) Upgrade to `v2.58.0` of the Terraform provider
3) Manually migrate your custom HTTPS settings to the dedicated `azurerm_frontdoor_custom_https_configuration` resource and remove your existing inline custom HTTPS configuration settings from your configuration file.
4) `Terraform apply`

So at the end of the day with all of these suggestions your configuration file should end up looking something like this:

<details>
  <summary>Updated Configuration file</summary>

```terraform
locals {
  custom_frontend_name  = "custom"
}

resource "azurerm_frontdoor" "fd" {
  name                                         = "sample-frontdoor-brc"
  resource_group_name                          = azurerm_resource_group.rg.name
  enforce_backend_pools_certificate_name_check = true
  tags = {
    "Version" = "4.0.2"
  }

  backend_pool {
    <snipped for brevity>
  }

  backend_pool_load_balancing {
    name = "backend-lb"
  }

  backend_pool_health_probe {
    <snipped for brevity>
  }

  frontend_endpoint {
    name      = "default"
    host_name = "sample-frontdoor-brc.azurefd.net"
  }

  frontend_endpoint {
    name      = "custom"
    host_name = "sample-frontdoor-brc.sandbox.provider.engineering"
  }

  routing_rule {
     <snipped for brevity>
  }
}

resource "azurerm_frontdoor_custom_https_configuration" "fd_custom_url" {
  frontend_endpoint_id              = "${azurerm_frontdoor.example.id}/frontendEndpoints/${local.custom_frontend_name}"
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```
</details>

HTH, again sorry for all of the moving pieces but given all of the issue this resource was having these **breaking changes** was really the only way forward to fixing them. If this comment has answered all of your questions feel free to close the issue and thanks again for opening this. 🚀

**Comment by timja** [comment]
> Delete your custom HTTPS endpoint and your inline custom HTTPS configuration settings from your configuration file.
Terraform apply, this will remove the custom HTTPS settings and reference and avoid the errors after upgrading.
Upgrade to v2.58.0 of the Terraform provider
Manually migrate your custom HTTPS settings to the dedicated azurerm_frontdoor_custom_https_configuration resource and add your custom HTTPS endpoint back into your configuration file.
Terraform apply

I didn't have to do anything migrating have an azurerm_frontdoor (from 2.41.0) with inline custom_https_configuration to the separate resource, the first apply just worked

**Comment by bcline760** [comment]
@WodansSon This is helpful and is there a way to have this info not lost within this issue? I can't image I'd be the only one going "why can't I upgrade"?

**Comment by WodansSon** [comment]
> @WodansSon This is helpful and is there a way to have this info not lost within this issue? I can't image I'd be the only one going "why can't I upgrade"?

The only way I could think of where this info would not get lost is to add an `v2.58.0 Upgrade` or `Frontdoor best practices` section to the documentation, but we would have to get HashiCorp approval for that as it is not a normal format for their documentation. However, with Frontdoor, I think they might make an exception given it's history. 🙂 

> Imma throw this out knowing I'm still pretty new to the provider architecture, is there anyway for the provider to be able to pull from the Front Door API any existing certificates that were created the old way and then made into the new way? I'm thinking of a terraform import command.

Not to my knowledge, there are two parts here. The configuration file needs to change and the state file needs to change, there is nothing we can do about the configuration file, while we could remove these values from the state file there my still be some referential integrity issues that would arise by doing that. Like the custom frontend endpoint still exists and if we remove the values from the state file that would cause a conflict I believe, for example. Which is why, if it is possible to destroy the current Frontdoor instance, is the cleanest way to do that, but I understand that might not be possible for some mission critical infrastructure. 🤔

**Comment by timja** [comment]
Normally the issue would be pinned for a few weeks if there’s action for people to take.

but it only happens in some edge case, my setup appears to be the same as above and I didn’t need to do anything outside moving the resource from inline to separate resource

**Comment by cpressland** [comment]
So far, I've had mixed success with this version, we've not been able to configure Front Door in Terraform for nearly a year now, so its had lots of Azure Portal modifications. On the plus side, Terraform can now manage the Front Door object itself just fine, but custom HTTPS resources are completely broken for us.

We began with a front door sub resource as follows:

```
     frontend_endpoint {
         name = "api-staging-gb-bink-com"
         host_name = "api.staging.gb.bink.com"
         custom_https_provisioning_enabled = true
         custom_https_configuration {
             certificate_source = "AzureKeyVault"
             azure_key_vault_certificate_vault_id = azurerm_key_vault.frontdoor.id
             azure_key_vault_certificate_secret_name = "gb-bink-com"
             azure_key_vault_certificate_secret_version = "latest"
         }
         web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.policy.id
     }
```

this was modified to:

```
     frontend_endpoint {
         name = "api-staging-gb-bink-com"
         host_name = "api.staging.gb.bink.com"
         web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.policy.id
     }
```

and then an additional resource added:

```
resource "azurerm_frontdoor_custom_https_configuration" "api_staging_gb_bink_com" {
    frontend_endpoint_id = azurerm_frontdoor.frontdoor.frontend_endpoints["api-staging-gb-bink-com"]
    custom_https_provisioning_enabled = true

    custom_https_configuration {
        certificate_source = "AzureKeyVault"
        azure_key_vault_certificate_vault_id = azurerm_key_vault.frontdoor.id
        azure_key_vault_certificate_secret_name = "gb-bink-com"
        azure_key_vault_certificate_secret_version = "latest"
    }
}
```

On the initial Terraform apply the Front Door object itself was modified and all Custom HTTPS Certificates were deprovisioned as expected. However, when attempting to add the new resource type we get the following error:

```
Error: updating Custom HTTPS configuration for Frontend Endpoint "api-staging-gb-bink-com" (Front Door "bink-frontdoor" / Resource Group "frontdoor"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "api-staging-gb-bink-com" (Resource Group "frontdoor"): waiting to enable Custom Domain HTTPS for Frontend Endpoint: Code="None" Message=""
```

The above led me here, and I attempted to remove all associated records completely as per the recommendations in "The Hard Way" from @WodansSon - unfortunately after completing this we still had the same error:

```
Error: updating Custom HTTPS configuration for Frontend Endpoint "api-staging-gb-bink-com" (Front Door "bink-frontdoor" / Resource Group "frontdoor"): unable to enable/update Custom Domain HTTPS for Frontend Endpoint "api-staging-gb-bink-com" (Resource Group "frontdoor"): waiting to enable Custom Domain HTTPS for Frontend Endpoint: Code="None" Message=""
```

Checking the JSON payload in resources.azure.com showed that above resource didn't change all that much between applies, obviously it disappeared, but when it came back it was identical beyond a slight ordering difference.

I then attempted to create this resource with:

```
    custom_https_configuration {
        certificate_source = "FrontDoor"
    }
```

Which worked! As such, I still think we have an issue here when using Azure Key Vault with a `azurerm_frontdoor_custom_https_configuration` resource. Any suggestions on this @WodansSon?

**Comment by timja** [comment]
Are you putting the literal string latest in or is that referring to a version? If you want the latest version you should not specify a version (leave out the attribute)

**Comment by cpressland** [comment]
Good shout @timja! That did it! Weird that a literal string of 'latest' worked on the old config?

**Comment by WodansSon** [comment]
@timja @cpressland 

> Are you putting the literal string latest in or is that referring to a version? If you want the latest version you should not specify a version (leave out the attribute)

I am seeing this confusion creep in more and more... thinking about putting a check in the code if it sees latest just to ignore it and send an empty string instead or maybe a validation rule that would error out if the word latest was passed as the version field value. 🤔

**Comment by WodansSon** [comment]
@bcline760, I think I see what is happening here. In your old version of the Frontdoor(v2.57.0), with the inline custom HTTPS settings, the custom frontend endpoint was correctly provisioned, exists and already has a Frontdoor managed key. Then you update your configuration, remove the inline settings and add the new custom HTTPS configuration resource:

```terraform
resource "azurerm_frontdoor_custom_https_configuration" "fd_custom_url" {
  frontend_endpoint_id              = azurerm_frontdoor.fd.frontend_endpoint[1].id
  custom_https_provisioning_enabled = true

  custom_https_configuration {
    certificate_source = "FrontDoor"
  }
}
```

When you run the `apply` Terraform detects that there is a new resource that needs to be provisioned (because it does not exist in the state file but does exist in the configuration file), and will attempt to provision the "new" custom HTTPS configuration resource. But when it attempts to provision this "new" resource, the Frontdoor API figures out that it actually already exists because it was already provisioned with the inline syntax in a previous release of the provider. Which means when Terraform calls the Update API for the endpoint, Frontdoor says, what do you mean I already have that so it returns the error you are seeing. If this hypothesis is correct I see two paths forward at this point:

1) You need to update your configuration and delete that endpoint along with the inline custom HTTPS settings and `apply` those changes. Then add the endpoint back into the configuration file along with the new `azurerm_frontdoor_custom_https_configuration` resource and apply those changes. Doing this offers another issue, since you reference the `frontend_endpoint_id` by `index` which will change because the endpoint has just been deleted and added back into the configuration file and by being added back into the configuration file changing its index. To avoid the index issue, I would change the logic in your configuration file for the `azurerm_frontdoor_custom_https_configuration` `frontend_endpoint_id` field to use the `${azurerm_frontdoor.example.id}/frontendEndpoints/${local.custom_frontend_name}` syntax mentioned above. In theory doing this that would avoid the issue you are currently hitting an get the configuration file and that state file back into alignment and you would no longer hit this issue, but you would see down time for that end point while this reconfiguration happens.

2) I would have to add code to the `azurerm_frontdoor_custom_https_configuration` resource to first attempt to get the endpoint, if it finds it, then look in the state file to see if it also finds it there, if I find in in Azure, the configuration file and not in the state file, skip the call to update API and only modify the state file with the new values that were returned from the configuration file with the values from the `GET` call to Azure. Since the `azurerm_frontdoor_custom_https_configuration` currently does not support import functionality. If this was a perfect world, the proper workflow for this scenario would be to:
   1. Upgrade provider to v2.58.0 
   2. Remove the inline custom HTTPS configuration values from your configuration file
   3. Create a `azurerm_frontdoor_custom_https_configuration` resource stub in your configuration file where you would like to import the new `azurerm_frontdoor_custom_https_configuration` resource.
   4. Call import on the `azurerm_frontdoor_custom_https_configuration` resource to update the state file with the correct values for this resource which currently exist in Azure.
   5. Update your configuration file to include the correct values for the imported `azurerm_frontdoor_custom_https_configuration` resource
   6. Run Terraform plan

If all 6 of the previous steps were completed correctly, Terraform should then see that all is good again with the world and tell you that the infrastructure is up to date and no changes are required. However, that is still a very complex and difficult way to correct this issue.

So if possible, I believe option 1 here is the easiest and the best choice for success... granted, it will cause your frontend endpoint to be down for the amount of time it takes for Frontdoor to remove and then re-provision your certificate (20 minutes or so) and I understand that is not a great solution, but given the current state of the API that, in my opinion, is the best we can do at this point in time.

**Comment by WodansSon** [comment]
@bcline760, I was able to repro the issue. This is a state management issue and it is exactly what I thought was happening here. Once you upgrade to v2.58.0, since the new `azurerm_frontdoor_custom_https_configuration` does not exist in the state file it wants to provision it as a brand new resource, but since this resource already exists you are basically trying to re-enable an existing resource which is why you are getting that error. 

To get around this issue I had to add the below `State file entry` into my state file. Once I did that and I ran a plan Terraform said that the infrastructure was up to date and everything worked as expected. 

<details>
  <summary>State file entry</summary>

```terraform
    {
      "mode": "managed",
      "type": "azurerm_frontdoor_custom_https_configuration",
      "name": "custom",
      "provider": "provider.azurerm",
      "instances": [
        {
          "schema_version": 1,
          "attributes": {
            "custom_https_configuration": [
              {
                "azure_key_vault_certificate_secret_name": "",
                "azure_key_vault_certificate_secret_version": "",
                "azure_key_vault_certificate_vault_id": "",
                "certificate_source": "FrontDoor",
                "minimum_tls_version": "1.2",
                "provisioning_state": "Enabled",
                "provisioning_substate": "CertificateDeployed"
              }
            ],
            "custom_https_provisioning_enabled": true,
            "frontend_endpoint_id": "/subscriptions/XXXXX/resourceGroups/XXXXX-11623-frontdoor-repro/providers/Microsoft.Network/frontDoors/acctest-fd-001-test/frontendEndpoints/custom",
            "id": "/subscriptions/XXXXX/resourceGroups/XXXXX-11623-frontdoor-repro/providers/Microsoft.Network/frontDoors/acctest-fd-001-test/customHttpsConfiguration/custom",
            "timeouts": null
          },
          "private": "XXXXX",
          "dependencies": [
            "azurerm_frontdoor.test",
            "azurerm_resource_group.test"
          ]
        }
      ]
    },
``` 
</details>

<details>
  <summary>Added Configuration resources</summary>

```terraform
locals {
  default_frontend_name = "default"
  custom_frontend_name  = "custom"
}

resource "azurerm_frontdoor_custom_https_configuration" "default" {
 frontend_endpoint_id              = "${azurerm_frontdoor.test.id}/frontendEndpoints/${local.default_frontend_name}"
 custom_https_provisioning_enabled = false
}

resource "azurerm_frontdoor_custom_https_configuration" "custom" {
 frontend_endpoint_id              = "${azurerm_frontdoor.test.id}/frontendEndpoints/${local.custom_frontend_name}"
 custom_https_provisioning_enabled = true

 custom_https_configuration {
   certificate_source = "FrontDoor"
 }
}
```
</details>

There are two possible fixes here:

1) Delete the endpoints that have custom HTTPS configuration enabled, run apply, upgrade to v2.58.0 re-add the endpoint and add the new `azurerm_frontdoor_custom_https_configuration` resource into the configuration and re-run apply.
2) Modify the code to support import of this resource.

If import worked for the `azurerm_frontdoor_custom_https_configuration` resource all you would have to do would be:

1) upgrade to v2.58.0
2) update your configuration file with `azurerm_frontdoor_custom_https_configuration` stubs for **ALL** existing frontend endpoints
3) run the import command for each of your existing endpoints to get the new `azurerm_frontdoor_custom_https_configuration` resource into your state file

Which is the normal order of doing things like this in terraform, however the `azurerm_frontdoor_custom_https_configuration` does not support import so that is not an option at this point in time.

**Comment by timja** [comment]
Right so appears to be a front door managed cert issue, if you’re providing your own cert it works
