### ISSUE TITLE
How to access primary_key if there is no virtual_network_rule

### ISSUE THREAD

**Issue by namshiynwa** [terraform-providers/terraform-provider-azurerm#11702]
How to access primary_key if virtual_network_rule is empty. Currently primary key is only available inside virtual_network_rule. But in my case virtual_network_rule  is empty but cosmos account does have a primary key. How to access it from cosmostdb_account data source?

**Comment by tombuildsstuff** [comment]
hi @namshiynwa 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by namshiynwa** [comment]
this is not a question, this will be a feature request. As of now, there is no option in the cosmos account data source to fetch the primary key if it has no virtual network rule (which is optional). In my case, I want to get the primary key of a cosmos account for which there is no virtual network rule. Currently primary key is inside the virtual network rule in the data source. Can you please put it outside the virtual network block if possible, consider this as  a feature enhancement, not a question
