### ISSUE TITLE
When creating a data_disk under VM the name of the data disk is required as opposed to Azure cli where it is optional

### ISSUE THREAD

**Issue by oded-dd** [terraform-providers/terraform-provider-azurerm#1170]
### Terraform Version
Terraform v0.11.2                                                             
+ provider.azurerm v1.3.3

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_machine

### Terraform Configuration Files
```hcl
module "elasticsearch_cold_resource" {
  source                          = "../../../../modules/base/azurerm_vm_resource"

  subnet_name                     = "${var.subnet_name}"
  subnet_vnet_name                = "${var.subnet_vnet_name}"
  subnet_resource_group_name      = "${var.subnet_resource_group_name}"

  location                        = "${var.location}"

  instance_count                  = 8
  instance_name                   = "prod-elasticsearch-cold"
  vm_size                         = "Standard_D8_v3"

  storage_data_disk               = [
    {
      lun = 0
      managed_disk_type = "Standard_LRS"
      caching = "ReadWrite"
      create_option = "Empty"
      disk_size_gb = 512
    },
    {
      lun = 1
      managed_disk_type = "Standard_LRS"
      caching = "ReadWrite"
      create_option = "Empty"
      disk_size_gb = 512
    },
  ]
```

### Debug Output
Error: module.elasticsearch_cold_resource.azurerm_virtual_machine.this[0]: "storage_data_disk.0.name": required field is not set
Error: module.elasticsearch_cold_resource.azurerm_virtual_machine.this[1]: "storage_data_disk.1.name": required field is not set

### Expected Behavior
As Azure API create a unique name in case name was not provided, I would expect this field to be optional.

### Actual Behavior
An error indicating the name field is required. Terraform `apply` fails

**Comment by tombuildsstuff** [comment]
hi @oded-dd 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We recently opened #5550 which adds support for the new Virtual Machine resources - and I'm able to confirm that this is fixed in the new Virtual Machine resources - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine` resource.

In order to get feedback on these new resources we'll be launching support for these new resources as an opt-in Beta in an upcoming 1.x release of the Azure Provider and ultimately release these as "GA" in the upcoming 2.0 release. We'll post an update in #2807 when both the opt-in Beta (1.x) & GA (2.0) are available - as such I'd recommend subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
