### ISSUE TITLE
Question about app_service 

### ISSUE THREAD

**Issue by seitosan** [terraform-providers/terraform-provider-azurerm#1174]
Hi There

I have a question. I would deploy app_service with custom git. How can I do this ? 

Regards,

**Comment by tombuildsstuff** [comment]
hi @seitosan 

Thanks for opening this issue :)

At this time Terraform only natively provisioning [the `LocalGit` Source Control](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#scm_type) type for an App Service due to a bug in the Azure API. We're working on adding support for the other types (such as Github, BitBucket etc) and that works being tracked in #1104 / #1121. Should you wish to provision an App Service with a Custom Git repository in the interim - you can make use of [the `azurerm_template_deployment` resource](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html) to deploy an ARM Template from within Terraform just to configure the Source Control section.

Since this feature request is being tracked elsewhere - I'm going to close this issue for the moment.

Thanks!

**Comment by seitosan** [comment]
Yes thanks for this news. I have already try with template deployment but the deployment failed due  a timeout. 

do you know if it is possible to add or at least if there is an issue to add the timeouts on this resource?

Best regards

**Comment by tombuildsstuff** [comment]
@seitosan 

> do you know if it is possible to add or at least if there is an issue to add the timeouts on this resource?

Support for this is being tracked in #171 - we're in a position where we can add these now the SDK supports it, so we'll look into this in the future.

Thanks!

**Comment by seitosan** [comment]
Perfect thanks a lot. I follow this with intention :)
