### ISSUE TITLE
disk_encryption_set_id unavailable in storage_os_disk block of azurerm_virtual_machine

### ISSUE THREAD

**Issue by speccenini** [terraform-providers/terraform-provider-azurerm#11776]
Hi all,

unfortunately I noticed the disk_encryption_set_id is unavailable in storage_os_disk block of azurerm_virtual_machine resource declaration.

It turned out that we are asked to implement CMK for an already existing infra and in our code the OS disk was created within the azurerm_virtual_machine resource.

So, we can update the other disks of the machines but not the OS one... I don't know how to manage it without changing a lot the code and recreating the whole tfstate file.

Would be possible to add it?

**Comment by tombuildsstuff** [comment]
hi @speccenini 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!
