### ISSUE TITLE
Support for ARM Template of Azure to Terraform Script

### ISSUE THREAD

**Issue by Anand0583** [terraform-providers/terraform-provider-azurerm#11775]
I wanted to know whether there is a way or existing tools to convert the existing ARM Templates being deployed to Terraform Scripts and also whether there is a tool to convert ARM Templates of Azure to Terraform Scripts for a different Cloud Provider.

Please let me know the comments or suggestions.

**Comment by tombuildsstuff** [comment]
hi @Anand0583 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
