### ISSUE TITLE
Support for choosing Managment Group in Azure when create a subscription via terrafrom

### ISSUE THREAD

**Issue by Yurii-Shpik** [terraform-providers/terraform-provider-azurerm#11780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is there any possibility to create a subscription inside of the particular Management group in Azure, not in the root MG and put it inside the configuration as some property?  
### New or Affected Resource(s)

* azurerm_subscription

### Potential Terraform Configuration

```hcl
terraform {
  backend "azurerm" {}
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~>2.5"
    }
  }
  required_version = ">0.12.0"

}
provider "azurerm" {
  features {}
}

data "azurerm_billing_enrollment_account_scope" "sb" {
  billing_account_name    = "xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxx"
  enrollment_account_name = "right@emal.com"
}
resource "azurerm_subscription" "sb" {
  subscription_name = "Super New Test Subscription"
  billing_scope_id  = data.azurerm_billing_enrollment_account_scope.sb.id
}
```

**Comment by tombuildsstuff** [comment]
hi @Yurii-Shpik 

Thanks for opening this issue.

Support for assigning Subscriptions to Management Groups can be achieved using [the `azurerm_management_group_subscription_association ` resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/management_group_subscription_association) (or within the `azurerm_management_group` resource) - as such unfortunately we don't plan to add this field to the `azurerm_subscription` resource directly.

Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
