### ISSUE TITLE
When I try to execute the terraform plan for every next plan it asks to recreate the Internal Load Balancer Backend Pool with VMSS, for backend_address.

### ISSUE THREAD

**Issue by garigoyal22** [terraform-providers/terraform-provider-azurerm#11781]
When I try to execute the terraform plan for every next plan it asks to recreate the Internal Load Balancer Backend Pool with VMSS, for backend_address.

terraform plan>

 resource "azurerm_lb_backend_address_pool" "azurelbbackend" {
        id                        = "/subscriptions/XXXXXXXXXX/resourceGroups/XXXXXX/providers/Microsoft.Network/loadBalancers/XXXXX/backendAddressPools/XXXXXX"
        name                      = "XXXXXX"
        # (5 unchanged attributes hidden)

      - backend_address {
          - name = "XXXXXXX" -> null
        }
    }

**Comment by tombuildsstuff** [comment]
hi @garigoyal22 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
