### ISSUE TITLE
Creating a subnet never completes

### ISSUE THREAD

**Issue by yuvipanda** [terraform-providers/terraform-provider-azurerm#118]
### Terraform Version
Terraform v0.9.8

### Affected Resource(s)
- azurem_subnet

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "summer17" {
  name     = "summer17"
  location = "West US"
}

resource "azurerm_virtual_network" "summer17" {
  name                = "summer17"
  address_space       = ["10.0.0.0/8"]
  resource_group_name = "${azurerm_resource_group.summer17.name}"
  location = "${azurerm_resource_group.summer17.location}"
}

resource "azurerm_subnet" "summer17" {
  name                 = "summer17"
  resource_group_name  = "${azurerm_resource_group.summer17.name}"
  virtual_network_name = "${azurerm_virtual_network.summer17.name}"
  address_prefix       = "10.1.0.0/16"
}
```

### Debug Output
https://gist.github.com/anonymous/c3f29db46cac1487619e8d9c9fe515c6

### Expected Behavior
It should've created the resource group, network + subnet.

### Actual Behavior
It got stuck at creating the subnet forever. I waited for upto 30 minutes before giving up. Tried multiple times, same behavior.

### Steps to Reproduce
1. `terraform apply`
2. Wait for it to complete
3. Wait forever

**Comment by tombuildsstuff** [comment]
Hi @yuvipanda 

Thanks for opening this issue :)

From what I can see, this issue has been fixed in #6 (which has been merged). Until that's released, you can workaround the deadlock issue you're seeing by renaming either the Virtual Network or the Subnet's name (for example by suffixing `vn` and `sn`) - or by [compiling a pre-release version of the AzureRM Provider from `master`](https://github.com/terraform-providers/terraform-provider-azurerm#building-the-provider) if you're comfortable with that.

Seeing as this issue appears to be fixed - I'm going to close this issue out for the moment. Would you be able to confirm if one of the above solutions solves your issue in the interim?

Thanks!
