### ISSUE TITLE
azurerm_key_vault_secret should depands on azurerm_key_vault_access_policy

### ISSUE THREAD

**Issue by vanmash** [terraform-providers/terraform-provider-azurerm#11850]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_key_vault_secret` 
* `azurerm_key_vault_access_policy`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

resources should have been created in that order (default `depands_on`)

1. `azurerm_key_vault`
2. `azurerm_key_vault_access_policy`
3. `azurerm_key_vault_secret`

### Actual Behaviour
creation of `azurerm_key_vault_secret` starts before `azurerm_key_vault_access_policy` is ready

### Steps to Reproduce

1. prepare main.tf with `azurerm_key_vault`, `azurerm_key_vault_access_policy`, `azurerm_key_vault_secret`
2. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @vanmash 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by vanmash** [comment]
Dear @tombuildsstuff 

please help me understand.
This wasn't a question. It was, in fact, bug report.
In certain configurations `terraform` tries to create `azurerm_key_vault_secret` *before* `azurerm_key_vault_access_policy` is created. As a result `terraform apply` fails. 

A workaround is to add `depands_on azurerm_key_vault_access_policy` on every secret.

Is it not a bug?

best
Maciek
