### ISSUE TITLE
Monitor services in azure

### ISSUE THREAD

**Issue by ashishsme14** [terraform-providers/terraform-provider-azurerm#11851]
Our task is -

- Write a terraform script in azmonitor.tf to create a storage account, storage container, storage blob to monitor and send log reports everyday.

- Define the variables resourcegroup and location in the variables.tf file, and call those variables in the azmonitor.tf file using string interpolation syntax

With help of vi command we created variables.tf file as

```
variable "resourcegroup"
{
default = "user-ktywkgjskfgc"
}
variable "location"
{ 
default = ["East US"]
}
```

In normal way we can create storage account as -

`az storage account create --resource-group $user-ofbujdqwzbib --name $storageccountName --location $location`

how to call those variables in the azmonitor.tf and above command in tf file we are not sure. Please suggest us expertise advice.

**Comment by tombuildsstuff** [comment]
hi @ashishsme14 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
