### ISSUE TITLE
Feature Request: Support for Azure Database for MySQL

### ISSUE THREAD

**Issue by bajorgensen** [terraform-providers/terraform-provider-azurerm#1195]
hi.

Now that the service have gone GA, I think support should be added to Terraform.
As this is a fully managed service I suppose that this will become the preferred way to set up MySQL in the future.

**Comment by tombuildsstuff** [comment]
hey @bajorgensen 

Thanks for opening this issue :)

Terraform's supported Azure Database for MySQL for a while now, and it's available in the [azurerm_mysql_server](https://www.terraform.io/docs/providers/azurerm/r/mysql_server.html), [azurerm_mysql_database](https://www.terraform.io/docs/providers/azurerm/r/mysql_database.html) , [azurerm_mysql_firewall_rule](https://www.terraform.io/docs/providers/azurerm/r/mysql_firewall_rule.html) and [azurerm_mysql_configuration](https://www.terraform.io/docs/providers/azurerm/r/mysql_configuration.html) resources.

Whilst these resources are usable at the moment they're still using the old pricing SKU's - however there's a PR tracking upgrading these resources to using the GA API's (#1063) which we're working through at the moment. Rather than having multiple issues tracking the same feature request I'm going to close this issue in favour of #1063 

Thanks!
