### ISSUE TITLE
azurerm_subscription data provider attributes marked as "computed"

### ISSUE THREAD

**Issue by thejohnbackes** [terraform-providers/terraform-provider-azurerm#11976]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.14.7
+ provider registry.terraform.io/hashicorp/azurerm v2.60.0
```

### Affected Resource(s)

* `data.azurerm_subscription`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp

data "azurerm_subscription" "current" {}
```

### Debug Output

```hcl
terraform console
> data.azurerm_subscription.current.subscription_id
(known after apply)
```

### Expected Behaviour

The data provider should be able to read subscription information during `terraform plan`, as it is a resource that _already exists_. These are marked as "Computed" attributes, which seems inaccurate.

### Actual Behaviour

"known after apply" means that this value can't be used for certain operations like "for_each"

```hcl
terraform console
> data.azurerm_subscription.current.subscription_id
(known after apply)
```

### Steps to Reproduce

1. `terraform plan`

### References

See: https://stackoverflow.com/questions/52557578/fetched-vs-computed-values-in-terraform-data-sources

* #0000

**Comment by magodo** [comment]
Given the [data source lifecycle](https://www.terraform.io/docs/language/data-sources/index.html#data-source-lifecycle):

> If the arguments of a data instance contain no references to computed values, such as attributes of resources that have not yet been created, then the data instance will be read and its state updated during Terraform's "refresh" phase, which by default runs prior to creating a plan. 

As `terraform plan` actually only maintain the refresh in the memory, rather than writing it back to the state. So you didn't see the  output from the `terraform console` or `terraform show`. Instead, you shall run `terraform refresh` or `terraform plan -refresh` (v1.15.0+).

**Comment by thejohnbackes** [comment]
terraform refresh runs before plan, so I should not have the issue of being unable to use the azure subscription values as keys. But I believe because they are marked in the provider as computed fields they show as not known until apply.

**Comment by magodo** [comment]
Given following config, I can use the subscription display name as keys for a `for_each` expr:

```hcl
provider "azurerm" {
  features {}
}

data "azurerm_subscription" "current" {}

resource "null_resource" "test" {
  for_each = toset([data.azurerm_subscription.current.display_name])
  triggers = {
    name = each.value
  }
}
```

Execution:

```bash
💤 tf plan

An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  + create

Terraform will perform the following actions:

  # null_resource.test["Spinnaker Demo"] will be created
  + resource "null_resource" "test" {
      + id       = (known after apply)
      + triggers = {
          + "name" = "Spinnaker Demo"
        }
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

**Comment by tombuildsstuff** [comment]
hi @thejohnbackes 

A field which is Computed in Terraform is a field where the value is retrieved from the API - as such for a data source (where these fields are not user-configurable, since they're read-only values populated from the API) these fields should be Computed (and as such whilst I'd like to thank you for the contribution in #11978, I'm going to close that PR for the moment).

That said, unfortunately this appears to be a bug in Terraform Core rather than the AzureRM Provider - since your using an older version of Terraform Core I'd suggest first upgrading to the latest version of Terraform Core (v0.15.4 at the time of writing) and if you're still encountering this issue [opening an issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone from that team should be able to take a look.

Thanks!
