### ISSUE TITLE
Error in azurerm_role_assignment

### ISSUE THREAD

**Issue by HL-Sibelco** [terraform-providers/terraform-provider-azurerm#12060]
In this code
```
resource "azurerm_role_assignment" "role_assignment_name" {
  scope                = var.rbac_scope_id
  role_definition_name = var.rbac_role_name
  principal_id         = var.principal_id
}
```
I'm getting this error
```
2021-06-04T09:34:10.3860839Z Error: Provider produced inconsistent result after apply
2021-06-04T09:34:10.3861369Z 
2021-06-04T09:34:10.3861847Z When applying changes to
2021-06-04T09:34:10.3862760Z module.provision_keyvaults[0].module.kv_create["pwd-002"].module.kv_roles_aadgroups["Contributor"].module.rbac-assign-aadgroup-by-role-name.azurerm_role_assignment.role_assignment_name,
2021-06-04T09:34:10.3863640Z provider "provider[\"registry.terraform.io/hashicorp/azurerm\"]" produced
2021-06-04T09:34:10.3864333Z an unexpected new value: Root resource was present, but now absent.
2021-06-04T09:34:10.3864899Z 
2021-06-04T09:34:10.3865489Z This is a bug in the provider, which should be reported in the provider's
2021-06-04T09:34:10.3866035Z own issue tracker.
```
providers.tf
```
provider "azurerm" {
  alias           = "main"
  tenant_id       = var.tenant_id
  subscription_id = var.providers_azurerm["main"].subscription_id

  features {
    key_vault {
      purge_soft_delete_on_destroy = true
      recover_soft_deleted_key_vaults = true
    }
  }
}

provider "azurerm" {
  tenant_id       = var.tenant_id
  subscription_id = var.providers_azurerm["subscription"].subscription_id
  
  features {
    key_vault {
      purge_soft_delete_on_destroy = true
      recover_soft_deleted_key_vaults = true
    }
  }
}
```

If more files would be needed, just ask
[RawTF.TXT](https://github.com/terraform-providers/terraform-provider-azurerm/files/6597481/RawTF.TXT)

**Comment by torivara** [comment]
I am experiencing the exact same thing. This was working as expected in version 2.61.0 of the provider, but it looks like 2.62.0 somehow introduces this bug.

Using Terraform v 0.15.4 and azurerm v 2.62.0.

First this error happens, then the role assignment does not go into the terraform state. Subsequent runs complain that the resource already exists, as the role assignment is created but not recorded in tfstate.

**Comment by cosminstirbu** [comment]
We have a similar issue.

After upgrading from `2.61.0` to `2.62.0` `terraform plan` reported that our `azurerm_role_assignment` was deleted so then it will attempt to created it. When attempting to created it, obviously it failed because the role assignment already exists.

I have tried importing the `azurerm_role_assignment` as per https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/role_assignment using `terraform import "{resourceId}|{scope}"`.

The command fails with both 2.61.0 and 2.62.0.

`2.61.0 error:  Error: Error loading Role Assignment "...": authorization.RoleAssignmentsClient#GetByID: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'northeurope' and API version '2020-04-01-preview' for type 'virtualNetworks'. The supported api-versions are '2014-12-01-preview, 2015-05-01-preview, 2015-06-15, 2016-03-30, 2016-06-01, 2016-07-01, 2016-08-01, 2016-09-01, 2016-10-01, 2016-11-01, 2016-12-01, 2017-03-01, 2017-04-01, 2017-06-01, 2017-08-01, 2017-09-01, 2017-10-01, 2017-11-01, 2018-01-01, 2018-02-01, 2018-03-01, 2018-04-01, 2018-05-01, 2018-06-01, 2018-07-01, 2018-08-01, 2018-10-01, 2018-11-01, 2018-12-01, 2019-02-01, 2019-04-01, 2019-06-01, 2019-07-01, 2019-08-01, 2019-09-01, 2019-11-01, 2019-12-01, 2020-01-01, 2020-03-01, 2020-04-01, 2020-05-01, 2020-06-01, 2020-07-01, 2020-08-01, 2020-11-01, 2021-01-01, 2021-02-01'. The supported locations are 'westus, eastus, northeurope, westeurope, eastasia, southeastasia, northcentralus, southcentralus, centralus, eastus2, japaneast, japanwest, brazilsouth, australiaeast, australiasoutheast, centralindia, southindia, westindia, canadacentral, canadaeast, westcentralus, westus2, ukwest, uksouth, koreacentral, koreasouth, francecentral, australiacentral, southafricanorth, uaenorth, switzerlandnorth, germanywestcentral, norwayeast, westus3, jioindiawest'."`

`2.62.0 error: Error: Error loading Role Assignment "...": authorization.RoleAssignmentsClient#GetByID: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedQuery" Message="'tenantId' query parameter '/subscriptions/***/resourceGroups/dev-rg/providers/Microsoft.Network/virtualNetworks/dev-vnet' must be a well formed Guid and it can be used only in case of a cross tenant request."`

At the moment we are stuck. We're going to try to use older versions as well until we manage to import the resource.

**Comment by cosminstirbu** [comment]
Since we didn't manage to import the resource we ended up deleting it.

We then pinned azurerm to version `2.61.0` which recreated the `azurerm_role_assignment` successfully.

For now we'll stick to version `2.61.0`.

**Comment by dhmoto17** [comment]
I also have a similar issue that I'm working through.  Provider 2.62 removed the role assignment objects from the terraform state for a log analytics resource and so is planning to recreate the role assignements.  It then fails as the assignment already exists. However when I checked another role assignment on a resource group it appears to plan with no changes as expected.

I have set the provider to 2.61 and planned against a different log analytics resource and it again plans with no changes, suggesting it is an issue introduced in 2.62.

**Comment by TPPWC** [comment]
We have the same problem. We set a role assignment on a synapse workspace resource. When one of our user runs the pipeline again the plan states, that the role assignment will be created although it is already there and the apply fails.

I don't know if manualy removing the resource from the state is the right way since we are using Terraform Enterprise Server.

kr

tom

**Comment by tjololo** [comment]
Seems like 2.62 has a bug so that it cannot retrieve azurerm_role_assignment running plan with terraform v0.15.5 and 2.62 the plan output reports the azurerm_role_assignment as "has been deleted". Terraform will then try to create it as it is present in the configuration.

**Comment by mandarsj** [comment]
I had the same issue as suddenly today my pipeline started breaking on azure role assignment with 409 resource already exists error.
Henceforth I will pin to 2.61.. i suppose it is the only solution. It seems it broke tfstate file as well.

**Comment by HarleyB123** [comment]
On a little search around and DEBUG output (export TF_LOG to DEBUG to see the same):

It appears that AzureRM itself receives a 404:

```
2021-06-04T16:43:31.124+0100 [DEBUG] provider.terraform-provider-azurerm_v2.62.0_x5: [DEBUG] AzureRM Response for https://management.azure.com//subscriptions/redacted/resourceGroups/roger/providers/Microsoft.Authorization/roleAssignments/redacted?api-version=2020-04-01-preview: 
2021-06-04T16:43:31.124+0100 [DEBUG] provider.terraform-provider-azurerm_v2.62.0_x5: HTTP/2.0 404 Not Found
```

I *think* that updating the SDK for Go in Azure [here](https://github.com/terraform-providers/terraform-provider-azurerm/pull/11813/files) has an impact, as it's a breaking change as there is a breaking path in the CHANGELOG for that release [here](https://github.com/Azure/azure-sdk-for-go/blob/master/CHANGELOG.md#v5430), with details [here](https://github.com/Azure/azure-sdk-for-go/blob/v54.3.0/services/preview/authorization/mgmt/2020-04-01-preview/authorization/CHANGELOG.md).

**Comment by TPPWC** [comment]
Well we tried to pin the version to 2.61 and still does not work. I even checked the state and the role_assignment is not there and we removed it manually in the portal. Kind stuck with all the deployments now....

**Comment by mandarsj** [comment]
I believe role assignment module has been broken,  deleted the tfstate and clean the infrastructure and it still would not work.

**Comment by dhmoto17** [comment]
We had some issues removing assignments in the UI so we used az cli instead.  We were getting errors from the terraform apply :

`Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."`

I checked what was still assigned with 

```
az role assignment list --scope "/subscriptions/<full path to object where assignment is>"
```

Then deleted each one with
```
az role delete --ids "id from one of the assignments listed in the previous command"
```

Once we had fully removed all the assignments that were in the plan the terraform apply succeeded, with azurerm 2.61.

**Comment by mandarsj** [comment]
It seems as though, role assignments are completed, but do not enter tfstate file. what is a good way to handle this till it's fixed?
The next time the script runs, it will not detect role assignments in tfstate hence will try to recreate and will throw the above error of 409 ,  Already exists.

**Comment by drdamour** [comment]
getting same, 2.61 gave me no list of assignments, 2.62 gave me a ton...now my roles are all messed up :(

**Comment by Jared-Wolff23** [comment]
I was having similar problems.  Downgrading to 2.61 fixed the problem.

After upgrading to 2.62 some of the role assignments disappeared from the state file and I was unable to import them.  I tried deleting one of the role assignments and recreating it with TF but then I got the error reported here.  After downgrading, I was able to import the missing role assignments.

**Comment by man0s** [comment]
I'm also facing the same issue. I've downgraded to 2.61 to fix the problem.

**Comment by aristosvo** [comment]
The problem is around role assignments on resource level. Temporary workaround is downgrading or assignments on resource groups instead.

I've submitted a draft PR with an acceptance test plus a direction how to solve the problem, but this will cause some other resources to break I'm afraid (at least the unit tests). Will check tomorrow if I can solve it or wait for the HC maintainers on Monday.

**Comment by katlimruiz** [comment]
Same here, I upgraded to 2.62 and started to get the same error.

First the plan showed me that it was going to delete and create my Azure Container Registry links with my AKS clusters (to do AcrPull). So I went ahead to apply them since sometimes the cloud pushes more fields or so on.

But then after it applied the changes, it returned the same error `Error: Provider produced inconsistent result after apply`.

I downgraded to 2.61, and now the plan and apply works correctly.

**Comment by aristosvo** [comment]
The fix PR is already out there (https://github.com/terraform-providers/terraform-provider-azurerm/pull/12076), I've mentioned it in the contributors Slack channel already.

The best way to show the importance of this issue is by adding a 👍!

**Comment by drdamour** [comment]
i'm surprised that when i reverted to 2.61 (after applying with 2.62 and all my assignments being removed from state) that an apply with 2.61 didn't find all my assignments already present and just update state..and instead i have to import each specifically.

**Comment by aristosvo** [comment]
@drdamour sorry to hear that!! Especially as those IDs are not the most straightforward 😒

As mentioned in the PR as well:
> Dependent on your experience with the Azure provider forTerraform.., a dangerous and wild option is to remove the logic which is preventing recreating unimported resources for this specific resource, build your custom Azure TF provider and run it against your projects...?

Don't keep me responsible if it goes wrong😅 don't have time to write all the instructions down either 🙂

**Comment by TPPWC** [comment]
Is there any update on this issue? One of our customer is not able to downgrade to 2.61 and importing the missing role does not work as well.

**Comment by aristosvo** [comment]
Don't hold your breath! A hotfix is in the making!

🥳🥳🥳🥳
