### ISSUE TITLE
Terraform error : Provider produced inconsistent result after apply

### ISSUE THREAD

**Issue by rajatb2** [terraform-providers/terraform-provider-azurerm#12105]
![image](https://user-images.githubusercontent.com/84705947/121124587-cdbc5280-c842-11eb-99ec-d658bc882de8.png)
I am getting this issue on terraform. I am also getting role assignment already exists issue.
![image](https://user-images.githubusercontent.com/84705947/121124633-e0368c00-c842-11eb-946d-548e9b24023c.png)
when i run terraform apply it creates resources and and show unknown role assignments and on re-run it show resource exist error,
i am using count function on my aks module , can this be the cause of error.

**Comment by aristosvo** [comment]
@rajatb2 Thanks for submitting!

I believe this is a duplicate of #12057 and #12060, the solution is in the works and hopefully ready for the release of this week.

Until then, the best solution is to roll back to 2.61, remove your role assignments manually in the Portal and recreate them.

Another option is to define the scope on resource group instead of resource.

**Comment by rajatb2** [comment]
@aristosvo  while defining scope on resource group , again i am getting the same issue " Provider produced inconsistent result after apply ", I deleted all the role assignments manually and then try to recreate them but it seems like some of them get created and some named as unknown.

**Comment by aristosvo** [comment]
@rajatb2 Can you retry it with 2.62.1? This should've fixed the problems we had with `azurerm_role_assignment`

**Comment by rajatb2** [comment]
@aristosvo thansk , this issue has been resolved . closing this issue
