### ISSUE TITLE
Unable to create Multiple version of Same API in Azure APIM.

### ISSUE THREAD

**Issue by sbhattach** [terraform-providers/terraform-provider-azurerm#12131]
Using azure **azurerm_api_management_api_version_set**  we can create a single version of a API(Sya v1),
But when we need two version(say V1, V2) of the same API it could not able to create like below,

![image](https://user-images.githubusercontent.com/9097417/121306463-7db1be80-c91c-11eb-9206-9005a6629c88.png)

It will be great help if you can help us to achieve that.

**New or Affected Resource(s)**
azurerm_api_management_api_version_set/azurerm_api_management_api

**Comment by mgupta14** [comment]
Yes, same issue...Kindly help

**Comment by vgopalji** [comment]
facing a similar issue.....pls help

**Comment by tombuildsstuff** [comment]
hi @sbhattach 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
