### ISSUE TITLE
Support for generic user_assigned_identity assignment outside lifecycle of assigned resource

### ISSUE THREAD

**Issue by AdamCoulterOz** [terraform-providers/terraform-provider-azurerm#12151]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Assigning user assigned identities to resources is currently resource specific. This constrains adding / removing user assigned identities to the assignment resource lifecycle. There is potential to make this generic so that any resource which supports having an `azurerm_user_assigned_identity` assignment to use a new generic resource to decouple the lifecycle.

### New or Affected Resource(s)

azurerm_user_assigned_identity_assignment

### Potential Terraform Configuration

```hcl
resource "azurerm_user_assigned_identity" "example" {
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  name                = "example-identity-name"
}

resource "azurerm_user_assigned_identity_assignment" "example_assignment" {
  target = azurerm_linux_virtual_machine.example.id
  user_assigned_identity = azurerm_user_assigned_identity.example.id
}
```

### References

The Azure API for user assigned identity assignment uses a PATCH model already, with the following general model:

```HTTP
PATCH /subscriptions/<subId>/resourceGroups/<resGroupName>/providers/<providerName>/<resourceType>/<resourceName> HTTP/1.1
Host: management.azure.com
Content-Type: application/json
Content-Length: 148

{
	"location": "azure-region",
	"identity": {
		"type": "userassigned",
		"userAssignedIdentities": {
			"<userAssignedIdentitiyArmId>": {}
		}
	}
}
```

It would need to be able to manage individual assignments too, and I'm not sure if the patch API would directly support that or not, or if it would be necessary to manage around any other assignments from other lifecycles.

**Comment by tombuildsstuff** [comment]
hey @AdamCoulterOz 

Thanks for opening this issue.

Unfortunately the User Assigned Identity implementation differs between different API's, and the Update methods available differ between POST/PUT (which requires the full object to be sent) and PATCH (which requires just the diff) - and again each API implements this (and the behaviours) differently.

Generally speaking the Azure API differs from other cloud providers here insofar as the Azure API's mutate resources whereas other cloud providers have "association" resources which mirror the approach your describing above - which unfortunately exacerbates the problem since each API can have a slightly different handling of Managed Identities. From our side we've raised [this issue here](https://github.com/Azure/azure-sdk-for-go/issues/14409) which'd make it both easier/quicker to add these on new resources (using the inlined fashion) - and (if the API's become consistent) could enable a separate resource as described above.

However since this isn't currently possible due to the design of the Azure API - whilst I'd like to thank you for opening this issue I'm going to close this issue in favour of https://github.com/Azure/azure-sdk-for-go/issues/14409 which is tracking making these consistent within the Azure API's (and SDK's).

Thanks!

**Comment by AdamCoulterOz** [comment]
@tombuildsstuff - I completely agree and that was going through my head when I was writing this. It seems to be rather systemic, as it seems the individual services on Azure share very little in terms of at least API interfaces for common functionality. For example, supporting role based access permissions, monitoring / logging, even the "properties" section isn't at least partially shared.

Can you advise how best to manage partial lifecycle in that case then? Because it has been rejected from terraform core, with the direction to create resources such as the one I suggested to work around it...

https://github.com/hashicorp/terraform/issues/17352#issuecomment-550549330

> For that reason, we'd suggest opening more specific feature request issues for the use-cases shared here within the specific providers they relate to. The provider teams can evaluate whether there's a possible resource-type-specific or provider-specific solution to a specific problem, which makes it easier to apply pragmatism to find a solution. 

So it kinda feels like there isn't a '_pragmatism_' being applied here.

**Comment by tombuildsstuff** [comment]
@AdamCoulterOz 

> I completely agree and that was going through my head when I was writing this. It seems to be rather systemic, as it seems the individual services on Azure share very little in terms of at least API interfaces for common functionality. For example, supporting role based access permissions, monitoring / logging, even the "properties" section isn't at least partially shared.

From our side whilst I don't have specifics to share at this point, the "common interfaces" problem is something we're working to address in the medium-term - so that should help with regards to adding this to more resources, but I don't have a timeframe for that right now.

> Can you advise how best to manage partial lifecycle in that case then? Because it has been rejected from terraform core, with the direction to create resources such as the one I suggested to work around it...

As Terraform Core has mentioned these use-cases are provider specific - in this instance I don't think there's much we can do due to the design of the API at present - that said as mentioned above this is something we're looking to fix in the medium-term.

We've recently added some [common schema/logic for Identity](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/azurerm/internal/identity) within the Provider to make it easier to add support for Managed Identity on resources which support it - so adding this to existing resources is now quicker than previously.

In the interim the best thing we can do here is to add support for these identity blocks as they appear - the common schema/logic mentioned above makes this considerably quicker - whilst we're working on the "common interfaces" problem.

Whilst I'd agree the ideal scenario would be providing a generic resource for this assignment, whilst we can potentially work around the lack of common types - that the behaviour differs between different API's (insofar as some have to be added at creation and others can be added via update) makes that unfeasible at the moment - so I'd suggest [opening an issue on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) about that specifically.

Ultimately that Azure mutates existing objects rather than having "association" resources (like other cloud providers) is a larger design issue - perhaps @JeffreyRichter has thoughts here?

**Comment by JeffreyRichter** [comment]
I'm afraid I don't have enough context to fully understand this issue and my focus is not on ARM. So, someone from the ARM team would have to pick up the baton for this issue and then I'm happy to assist with the design change if something comes of this. I'll send mail to some other to make them aware of this issue.
