### ISSUE TITLE
Not able to assign role assignments(Access Control-IAM) for scope Resource Group to users/groups from Azure active directory.

### ISSUE THREAD

**Issue by avadhut0111** [terraform-providers/terraform-provider-azurerm#12187]
data "azurerm_subscription" "primary" {
}

resource "azurerm_role_assignment" "role" {
  scope                = data.azurerm_subscription.primary.id 
  role_definition_name = "Reader"
  principal_id         = var.object-id
}

Error: 1mauthorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed"

**Comment by tombuildsstuff** [comment]
hi @avadhut0111 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
