### ISSUE TITLE
Not able to assign ACL to azure storage container's for users/groups from Azure active directory using below terraform code.

### ISSUE THREAD

**Issue by avadhut0111** [terraform-providers/terraform-provider-azurerm#12186]
resource "azurerm_storage_container" "storage-container" {
  name                  = var.container-name
  storage_account_name  = azurerm_storage_account.storage-account.name
  container_access_type = "private"

ace {
    id          = var.object-id
    permissions = "rwx"
    scope       = "access"
    type        = "user"
  }
}

**Comment by tombuildsstuff** [comment]
hi @avadhut0111 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
