### ISSUE TITLE
create EVEN HUB with  Private endpoint connections

### ISSUE THREAD

**Issue by eliyahu77** [terraform-providers/terraform-provider-azurerm#12193]
HI * , 
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub_namespace

needed to create EVEN HUB  with Private endpoint connections , and Firewalls and virtual networks options.

my questions is did I miss any option on the current modules that terraform provide or
the options will be available in the future and if yes , when on which version of terraform it going to be implements 

BR Eliyahu

**Comment by tombuildsstuff** [comment]
hi @eliyahu77 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
