### ISSUE TITLE
Support for updating Service Endpoints in Subnet

### ISSUE THREAD

**Issue by owaisaamir** [terraform-providers/terraform-provider-azurerm#12223]
### Community Note
Please vote on this issue by adding a 👍 reaction to the original issue to help the community and maintainers prioritize this request
Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Resource to add or remove any service endpoint association after the subnet is created.

### New or Affected Resource(s)
azurerm_subnet_service_endpoints

### Potential Terraform Configuration
```
resource "azurerm_subnet_service_endpoints" "example" {
  subnet_name         = "example_subnet"
  resource_group_name = "example_rg"

  //  .... other params ....

  service_endpoints = [
    "Microsoft.Sql",
    "Microsoft.Storage"
  ]
}
```

**Comment by tombuildsstuff** [comment]
hi @owaisaamir 

This is achievable by importing the `azurerm_subnet` into Terraform and then updating the configuration - unfortunately we don't plan to introduce a separate resource for this since this would conflict with [the field inlined within the Subnet resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/subnet#service_endpoints) (and is a 1:1 with the subnet).

Since this isn't something we plan to support as a separate resource, whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment.

Thanks!
