### ISSUE TITLE
System assigned identity still enabled when using identity type UserAssigned (azurerm_virtual_machine)

### ISSUE THREAD

**Issue by alexisbonnin** [terraform-providers/terraform-provider-azurerm#12229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
- azurerm provider : 2.63.0
- terraform : 0.13.5
### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "main" {
  identity {
    type = "UserAssigned"
    identity_ids = [<managed identities id list>]
  }
}
```

### Expected Behaviour

According to [azurerm_virtual_machine documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/virtual_machine#identity), if identity type if set to `UserAssigned`, system assigned identity should be disabled.

### Actual Behaviour

Even if azurerm_virtual_machine identity type is set to `UserAssigned`, system assigned identity is still enabled.

### Steps to Reproduce

1. `terraform plan`
```hcl
+ resource "azurerm_virtual_machine" "main" {
      + identity {
          + identity_ids = [<managed identities id list>]
          + principal_id = (known after apply)
          + type         = "UserAssigned"
        }
  }
```

2. `terraform apply` (azure virtual machine json definition)
```json
{
  "type": "Microsoft.Compute/virtualMachines",
  "identity": {
      "type": "SystemAssigned",
      "principalId": "aaaaaaa-aaaa-aaaa-aaaaaaaaaa",
      "tenantId": "aaaaaaa-aaaa-aaaa-aaaaaaaaaa"
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @alexisbonnin 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!

**Comment by alexisbonnin** [comment]
Hi @tombuildsstuff 

Thank you for the quicks response.

It seems like this issue is also happening for `azurerm_linux_virtual_machine`. Indeed, when creating a Linux Virtual Machine with identity type `UserAssigned`, the resulted Virtual Machine appears to have a `SystemAssigned`identity.

Should I create a new ticket or update this one ?

Regards.
