### ISSUE TITLE
azurerm_data_factory - customer_managed_key_id property 

### ISSUE THREAD

**Issue by luongcu** [terraform-providers/terraform-provider-azurerm#12254]
Error with any version => 0.15.2
Error: "customer_managed_key_id": all of `customer_managed_key_id,identity.0.identity_ids` must be specified
with  "identity = SystemAssigned"   and  customer_managed_key_id = var.customer_managed_key_id  and the default of the var is null.

NOTES: works perfectly with 0.15.1 ONLY.

**Comment by tombuildsstuff** [comment]
hi @luongcu 

Thanks for opening this issue.

Taking a look through this appears to be a configuration question - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by luongcu** [comment]
Hi  @tombuildsstuff
Sorry, I did not provide enough description, this is not a question as its more of an issue.
Steps to repro:
1. Assign "identity = SystemAssigned" &
2. customer_managed_key_id = var.customer_managed_key_id where default value of this is null. NOTE: if we specify the same property to be "null" directly it works a well.

Though we wont need this value to be specified as identity is being set as "SystemAssigned".

So this particular configuration works as intended in TF v 0.15.1 but throws the error for all other versions including latest 1.0
customer_managed_key_id,identity.0.identity_ids.
