### ISSUE TITLE
Add userName Property to azurerm_data_factory_linked_service_sql_server

### ISSUE THREAD

**Issue by NickBishop2112** [terraform-providers/terraform-provider-azurerm#12274]
Can the userName property be added to  azurerm_data_factory_linked_service_sql_server artifact as it is currently missing.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

2.63.0

### Affected Resource(s)

azurerm_data_factory_linked_service_sql_server artifact

### Terraform Configuration Files

Example as per document
### Expected Behaviour

Should create linked service with userName property

### Actual Behaviour

Have to create linked service via Powershell.

### Steps to Reproduce

Documentation does not list userName

**Comment by tombuildsstuff** [comment]
hi @NickBishop2112 

Thanks for opening this issue.

Taking a look through here it appears that this can be achieved using [the connection string, using the `User ID=` component](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/data_factory_linked_service_sql_server#connection_string) (as shown in the Example Usage) - as such this should already be possible.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by NickBishop2112** [comment]
I will try out the fix.

**Comment by NickBishop2112** [comment]
@tombuildsstuff .  Please re-open as the connection string can not have the user id as using Integrated Security ie connection string in the Key Vault is: Data Source=serverurl;Initial Catalog=FooBar;Integrated Security=True

Also, the ADF UI ask for the user name: 
![image](https://user-images.githubusercontent.com/30340714/122592726-962c8200-d05c-11eb-847e-7161f8928563.png)
