### ISSUE TITLE
DNS Zone and Records are always recreated

### ISSUE THREAD

**Issue by Theragus** [terraform-providers/terraform-provider-azurerm#1229]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

When i define a DNS Zone or a Record Terraform always tries to recreate it. There seems to be a problem with case sensitive in the Names of the Resources.
![image](https://user-images.githubusercontent.com/38653346/39999088-56d7341a-5788-11e8-89fc-561e03e8e0b9.png)

**Comment by Theragus** [comment]
Also an error occurs when there are Uppercases in the DNS Zones Name when i try to apply the DNS Records.
![image](https://user-images.githubusercontent.com/38653346/40001028-9476fe86-578d-11e8-90bf-c4b9277243d0.png)

**Comment by draggeta** [comment]
While I'm not having this issue, I've seen this happen too often with colleagues. I've submitted a PR to make it so that Terraform converts all names to lower case.

**Comment by tombuildsstuff** [comment]
hi @Theragus 

Thanks for opening this issue - sorry for the delayed response here!

> When i define a DNS Zone or a Record Terraform always tries to recreate it. There seems to be a problem with case sensitive in the Names of the Resources.

From what I can see in the diff above this appears to be working with a pre-created resource with Terraform? Terraform requires that existing resources are imported into the state prior to being managed by Terraform ([more info on using `terraform import` can be found here](https://www.terraform.io/docs/commands/import.html) and on the documentation for each resource) - however there's currently a bug in the AzureRM Provider where this isn't the case due to most of the Azure API's being Upserts.

We've recently noticed this behaviour and have opened a fix for this as a part of #1746 - where attempting to use an existing resource will show an error saying "please import by doing ..." during resource creation. The reason for doing this is that it allows Terraform to properly understand the resource lifecycle; for example, some fields can't be Upserted, so Terraform knows the resource needs to be recreated rather than modifying it in-place.

Would you be able to take a look and see if using `terraform import` to bring the existing resource into the state and then ensuring the casing in the Terraform Configuration matches the name of the resource works for you?

> While I'm not having this issue, I've seen this happen too often with colleagues. I've submitted a PR to make it so that Terraform converts all names of for Azure DNS resources to lowercase.

@draggeta whilst making the `name` field case insensitive is one possible approach to work around this - we're actually planning on making the provider case sensitive (for fields where there's Constant/Enum values) where it's not at present to better match the behaviour of the other Providers (such as AWS and GCP) as a part of an upcoming major version bump (2.0).

Given this is a question about Terraform Configuration/Import rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll keep responding 😄)

Thanks!

**Comment by draggeta** [comment]
@tombuildsstuff I think I understand the reasoning, I don't completely agree with the "case sensitive" part. 

This issue doesn't only occur with an import, but also when creating a new resource. Any record or zone you create, is converted by Azure to lowercase. So if someone creates a zone with name "Contoso.com" in terraform, Azure automatically creates a zone with the name "contoso.com". Later applies make it so that these are different and need to be changed.

On the other hand, if you meant that you will validate that all records/zones are lowercase, then I do understand where you guys are going 😄
