### ISSUE TITLE
Ignore changes in tags not working in provider.azurerm: v1.44.0

### ISSUE THREAD

**Issue by chowmean** [terraform-providers/terraform-provider-azurerm#12291]
Hi I am using terraform 0.11 and using the below to ignore the changes to ignore the changes to tag. 
```
lifecycle {
    ignore_changes = [
 
      tags,
    ]
 }
```

This is not working and giving me syntax error
```machine.tf: At 63:7: unexpected token while parsing list: IDENT```

Terraform: v0.11.13
provider.azurerm: v1.44.0

**Comment by tombuildsstuff** [comment]
hi @chowmean 

Thanks for opening this issue.

Terraform v0.11.13 (which came out in March 2019) and v1.44.0 (which came out in Feb 2020) of the Azure Provider are both very old and unsupported at this time- as such the syntax being used is incompatible with that version. Since both of those versions are now unsupported, I'd encourage you to upgrade to the latest version of Terraform Core (v1.0) and the Azure Provider (v2.64.0) at the time of writing - but since these are unsupported I'm going to close this issue for the moment.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
