### ISSUE TITLE
azurerm_virtual_network omits plan data when using `terraform show -json`

### ISSUE THREAD

**Issue by noelbundick** [terraform-providers/terraform-provider-azurerm#12324]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v1.0.0
on linux_amd64
```

### Affected Resource(s)

* `azurerm_azurerm_virtual_network`

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "=2.61.0"
    }
  }
}

provider "azurerm" {
  features {
  }
}

resource "azurerm_resource_group" "rg" {
  name     = "test-rg99"
  location = "westus2"
}

resource "azurerm_network_security_group" "nsg1" {
  name                = "nsg1"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  security_rule {
    access                     = "allow"
    description                = "value"
    destination_address_prefix = "*"
    destination_port_range     = "80"
    direction                  = "inbound"
    name                       = "allow http"
    priority                   = 100
    protocol                   = "tcp"
    source_address_prefix      = "*"
    source_port_range          = "*"
  }
}

resource "azurerm_virtual_network" "vnet1" {
  name                = "vnet1"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  address_space       = ["10.0.0.0/16"]

  subnet {
    address_prefix = "10.0.0.0/24"
    name           = "subnet1"
    security_group = azurerm_network_security_group.nsg1.id
  }

}
```

### Debug Output

https://gist.github.com/noelbundick/9cdb1d7960b6970f2c861fd7e16f1626

### Panic Output

No panic

### Expected Behaviour

The JSON output for the plan should include the references from vnet1.subnet1 -> nsg1

### Actual Behaviour

The schema for `azurerm_virtual_network` explicitly defines `subnet` as `SchemaConfigModeAttr` versus `SchemaConfigModeAuto`, so it gets dropped when marshaling to JSON. There is no way to see the link from subnet to NSG in the generated JSON for the plan.

https://github.com/terraform-providers/terraform-provider-azurerm/blob/3c98880fcc47305d2a5cc5cdf8d77d983cb35da2/azurerm/internal/services/network/virtual_network_resource.go#L113

### Steps to Reproduce

1. `terraform plan -out=azurerm.tfplan`
2. `terraform show -json azurerm.tfplan`

### Important Factoids

I have tested that the one-line schema change resolves my problem, but I want to start a discussion on whether that's the correct fix, or if that will cause breakage elsewhere for the provider.

**Comment by tombuildsstuff** [comment]
hey @noelbundick 

Taking a look through here unfortunately this appears to be a bug with Terraform Core rather than a Provider specific bug, since the JSON Plan should be outputting all values - as such [would you mind opening an issue on the Terraform Core repository](https://github.com/hashicorp/terraform) where someone from that team should be able to take a look?

From the Provider side, the use of `SchemaConfigModeAttr` here is intentional since this allows assignment via `= []` (or `= var.subnets`) which is important when users want to force the removal of all subnets from the virtual_network resource. Use of `SchemaConfigModeAuto` means that this wouldn't be possible, since this field is both `Optional` and `Computed` (since it's possible for users to configure subnets both inline within the Virtual Network resource and using the separate Subnet resource).

Thanks!
