### ISSUE TITLE
app service: Additional config options

### ISSUE THREAD

**Issue by Midacts** [terraform-providers/terraform-provider-azurerm#1236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Is it possible to create:
-diagnostic logs
-SSL settings
-Custom domains

in an azurerm_app_service

### New or Affected Resource(s)

azurerm_app_service

**Comment by tombuildsstuff** [comment]
hi @Midacts 

Thanks for opening this issue - apologies for the delayed response here!

Since this issue was opened we've added support for specifying Custom Domains for an App Service via [the `azurerm_app_service_custom_hostname_binding.html` resource](https://www.terraform.io/docs/providers/azurerm/r/app_service_custom_hostname_binding.html).

Taking a look at the outstanding feature requests - there's issues open tracking support for [SSL Certificate support for App Service](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1136) and [Diagnostic Logs for App Service](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1082) - as such rather than keeping multiple issues open requesting support for the same thing I'm going to close this issue in favour of those two, would you mind subscribing to those issues for updates?

Thanks!

**Comment by Midacts** [comment]
Sounds good.
Thanks for your work on this and for the links.
