### ISSUE TITLE
Getting Error: azurerm_redis_cache.redis: "redis_configuration.0.maxclients": this field cannot be set

### ISSUE THREAD

**Issue by nagoh** [terraform-providers/terraform-provider-azurerm#1237]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a commen

### Terraform Version

1.5.0 

### Affected Resource(s)

* azurerm_redis_cache

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "1.4"
}

resource "azurerm_redis_cache" "redis" {
  name                = "my-redis"
  location            = "Australia East"
  resource_group_name = "my-resource-group"
  capacity            = 0
  family              = "C"
  sku_name            = "Basic"
  enable_non_ssl_port = false

  redis_configuration {
    maxclients = 256
  }
}
```

### Debug Output

azurerm_redis_cache.redis: "redis_configuration.0.maxclients": this field cannot be set

This has just started to happen after upgrade to v1.5.0. Removing the `maxclients` property allows the provisioning to continue. Though this documentation does not suggest it has changed? https://www.terraform.io/docs/providers/azurerm/r/redis_cache.html

**Comment by tombuildsstuff** [comment]
hey @nagoh 

Thanks for opening this issue :)

In v1.5.0 we changed this field from user-specifiable -> read only as the field can't be configured in the Azure API (such that it'll only ever return a fixed value depending on the SKU). We've [documented this in the upgrade notes for v1.5.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.5.0/CHANGELOG.md#150-may-14-2018) - however we missed these examples from the documentation; apologies about this I'll send a PR to remove these later today. Unfortunately since this field is no longer user configurable at the Azure API side - exposing it in Terraform was misleading (such that it'd constantly show changes needed unless you happened to pick one of the values aligned with a given SKU).

Thanks!
