### ISSUE TITLE
Error: The terraform-provider-azurerm_v2.67.0_x5.exe plugin crashed!

### ISSUE THREAD

**Issue by nietakipawel** [terraform-providers/terraform-provider-azurerm#12570]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

```
azurerm_private_dns_zone
```

### Terraform Configuration Files

```
resource "azurerm_kubernetes_cluster" "aks" {
  name                    = "aks-${var.short_location}-idp-${var.proj_code}-${var.env}-001"
  location                = var.location
  kubernetes_version      = var.kube_version
  resource_group_name     = azurerm_resource_group.rg002.name
  private_cluster_enabled = true
  dns_prefix          = "${var.short_location}-idp-${var.proj_code}-${var.env}"
  node_resource_group = "rg-idp-${var.proj_code}-${var.env}-003"

  private_dns_zone_id = azurerm_private_dns_zone.idp.id
```

### Panic Output

Stack trace from the terraform-provider-azurerm_v2.67.0_x5.exe plugin:

panic: runtime error: invalid memory address or nil pointer dereference
[signal 0xc0000005 code=0x0 addr=0x48 pc=0x5a8fe04]

goroutine 526 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/privatedns.resourcePrivateDnsZoneDelete(0xc001482380, 0x615a6e0, 0xc000b5b880, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/privatedns/private_dns_zone_resource.go:269 +0x244
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).delete(0xc000dd3500, 0x70b2b48, 0xc0010e4600, 0xc001482380, 0x615a6e0, 0xc000b5b880, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:369 +0x1fb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).Apply(0xc000dd3500, 0x70b2b48, 0xc0010e4600, 0xc000b7c150, 0xc00105e600, 0x615a6e0, 0xc000b5b880, 0x0, 0x0, 0x0, ...)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:428 +0x8f7
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ApplyResourceChange(0xc000005f68, 0x70b2b48, 0xc0010e4600, 0xc0000ebea0, 0xc0010e4600, 0x6624a20, 0xc001b17400)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:955 +0x8ef
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ApplyResourceChange(0xc00133f720, 0x70b2bf0, 0xc0010e4600, 0xc000b7c070, 0xc00133f720, 0xc001b174d0, 0xc001097ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:332 +0xb6
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ApplyResourceChange_Handler(0x6624a20, 0xc00133f720, 0x70b2bf0, 0xc001b174d0, 0xc0000e9920, 0x0, 0x70b2bf0, 0xc001b174d0, 0xc000d54000, 0x326)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:380 +0x222
google.golang.org/grpc.(*Server).processUnaryRPC(0xc000838380, 0x70fd098, 0xc00008d080, 0xc000d210e0, 0xc001328960, 0xa5f1ae0, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc000838380, 0x70fd098, 0xc00008d080, 0xc000d210e0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc000a88190, 0xc000838380, 0x70fd098, 0xc00008d080, 0xc000d210e0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xb2
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.67.0_x5.exe plugin crashed!

### Expected Behaviour

private DNS zone link, deployed as part of AKS cluster build, will be destroyed

### Actual Behaviour

panic: runtime error: invalid memory address or nil pointer dereference

### Steps to Reproduce

1. `terraform destroy`

**Comment by enorlando** [comment]
I have a similar issue where importing the `azurerm_logic_app_workflow` resource crashes the plugin. 

Error: Plugin did not respond
│ 
│ The plugin encountered an error, and failed to respond to the plugin.(*GRPCProvider).ReadResource call. The plugin logs may contain more details.
╵


Stack trace from the terraform-provider-azurerm_v2.68.0_x5 plugin:

panic: interface conversion: interface {} is nil, not string

goroutine 46 [running]:
github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/logic.resourceLogicAppWorkflowRead(0xc00011f180, 0x62999e0, 0xc000e70a80, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/azurerm/internal/services/logic/logic_app_workflow_resource.go:310 +0xf71
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).read(0xc000e1a0e0, 0x71ffb08, 0xc001b40180, 0xc00011f180, 0x62999e0, 0xc000e70a80, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:335 +0x1ee
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*Resource).RefreshWithoutUpgrade(0xc000e1a0e0, 0x71ffb08, 0xc001b40180, 0xc0007dc460, 0x62999e0, 0xc000e70a80, 0xc00011a710, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/resource.go:624 +0x1cb
github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema.(*GRPCProviderServer).ReadResource(0xc000722210, 0x71ffb08, 0xc001b40180, 0xc001b401c0, 0xc001b40180, 0x100b705, 0x65ad180)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema/grpc_provider.go:575 +0x43b
github.com/hashicorp/terraform-plugin-go/tfprotov5/server.(*server).ReadResource(0xc001cb1900, 0x71ffbb0, 0xc001b40180, 0xc001b460c0, 0xc001cb1900, 0xc001bbe1e0, 0xc0010f1ba0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/server/server.go:298 +0x105
github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5._Provider_ReadResource_Handler(0x6768140, 0xc001cb1900, 0x71ffbb0, 0xc001bbe1e0, 0xc001b46060, 0x0, 0x71ffbb0, 0xc001bbe1e0, 0xc001b48600, 0x2c4)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/github.com/hashicorp/terraform-plugin-go/tfprotov5/internal/tfplugin5/tfplugin5_grpc.pb.go:344 +0x214
google.golang.org/grpc.(*Server).processUnaryRPC(0xc00022a8c0, 0x724a198, 0xc000299500, 0xc000dc06c0, 0xc0013c0e10, 0xa764d30, 0x0, 0x0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1292 +0x52b
google.golang.org/grpc.(*Server).handleStream(0xc00022a8c0, 0x724a198, 0xc000299500, 0xc000dc06c0, 0x0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:1617 +0xd0c
google.golang.org/grpc.(*Server).serveStreams.func1.2(0xc001096040, 0xc00022a8c0, 0x724a198, 0xc000299500, 0xc000dc06c0)
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:940 +0xab
created by google.golang.org/grpc.(*Server).serveStreams.func1
        /opt/teamcity-agent/work/5d79fe75d4460a2f/src/github.com/terraform-providers/terraform-provider-azurerm/vendor/google.golang.org/grpc/server.go:938 +0x1fd

Error: The terraform-provider-azurerm_v2.68.0_x5 plugin crashed!

This is always indicative of a bug within the plugin. It would be immensely
helpful if you could report the crash with the plugin's maintainers so that it
can be fixed. The output above should help diagnose the issue.
