### ISSUE TITLE
App Service Code fails with  <nil> error

### ISSUE THREAD

**Issue by pvladimi** [terraform-providers/terraform-provider-azurerm#1259]
I cloned the repo for the App Service and was not provision the App Service. Getting this error:

Error: Error applying plan:

1 error(s) occurred:

* azurerm_app_service.default: 1 error(s) occurred:

* azurerm_app_service.default: web.AppsClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: failed request: autorest/azure: Service returned an error. Status=<nil> <nil>

**Comment by katbyte** [comment]
Hi @pvcnt,

Sorry to hear your having issues, but before I help I am going to need some more information:
- What version of terraform and the provider are you using? you can get this by running `terraform -v`
- What repository/terraform are you referring to?
- Could you post the full terraform HCL config that is leading to this error?

Thanks 🙂

**Comment by pvladimi** [comment]
Hi Katbyte,
Thank you for stepping in here. I'm using Terraform v0.11.7
The repo i cloned is in my Original Post: App Service.

Could you please clone that repo, point it to Azure and try 
to execute and see if that works for you or not?

**Comment by tombuildsstuff** [comment]
@pvladimi from what I can see the issue is that an App Service / Function App etc already exists using that name - newer versions of the AzureRM Provider included a clearer message for this issue. Would you be able to update to a more recent version of the Provider, which should solve this issue (by making the error message clearer). You can do this via:

```
provider "azurerm" {
  version = "=1.5.0"
}
```

and then running `terraform init -upgrade`. Once that's done - attempting to re-run `terraform apply` should show a clearer error message.

Thanks!

**Comment by pvladimi** [comment]
Excellent. That solved the issue. Thanks Tom.
