### ISSUE TITLE
UserAssigned is not supported in API Management resource even though docs says they're in PREVIEW.

### ISSUE THREAD

**Issue by nairraghunathgopinath** [terraform-providers/terraform-provider-azurerm#12638]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
![image](https://user-images.githubusercontent.com/84505580/126107921-b5ab5854-cb74-4a38-96c6-6a2547d1b64f.png)

### Expected Behaviour

Should allow create api-management resource with userassigned identity.
### Actual Behaviour

![image](https://user-images.githubusercontent.com/84505580/126107937-82ccce61-786e-4bf4-8e04-34c945164f59.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by nairraghunathgopinath** [comment]
As per docs https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/api_management says identity_ids are available for the public preview of the azurerm_api_management resource for UserAssigned Identity.

**Comment by tombuildsstuff** [comment]
hi @nairraghunathgopinath 

Taking a look through here it appears that your using an older version of the Azure Provider which doesn't support this field  (whereas the documentation is from the latest release) - as such I believe that upgrading to the latest version (`v2.68.0` at the time of writing) and re-running your Terraform Configuration should fix this.

Alternatively documentation for earlier versions of the Azure Provider can be found [on the Terraform Registry](https://registry.terraform.io/providers/hashicorp/azurerm/latest) in the 'Versions' bar:

![Screenshot 2021-07-19 at 08 52 53](https://user-images.githubusercontent.com/666005/126115762-731fde88-efa1-4840-9658-635c960e8c13.png)

Since upgrading to the latest version of the Azure Provider should resolve this issue I'm going to close this issue for the moment - but should you have any further usage questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by nairraghunathgopinath** [comment]
Thank you @tombuildsstuff  I see after upgrading to latest v2.0.68 i can see the feature available.
