### ISSUE TITLE
New version of key not generating

### ISSUE THREAD

**Issue by nitmatgeo** [terraform-providers/terraform-provider-azurerm#12639]
Unable to create a new version of key using azurerm_key_vault_key when the key is already present. Can we not create a new version of key via terraform?
AzureKeyvault key

**Comment by tombuildsstuff** [comment]
hi @nitmatgeo 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
