### ISSUE TITLE
Error: Network Interface was Not Found!

### ISSUE THREAD

**Issue by l3112** [terraform-providers/terraform-provider-azurerm#12656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_network_interface`

### Terraform Configuration Files

```
https://gist.github.com/l3112/16222a287187594440b6aad1b7d1c692
```

### Expected Behaviour

The following would be created:
    Virtual Network
    Network Interface
    Virtual Machine that attaches to the interface and is in the Vnet.

### Actual Behaviour

    Error: Network Interface “Net-Connection” (Resource Group “Admins”) was not found!

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

- The fact that it doesn't say "referencing an unknown object" as if the resource was totally not there makes me think this is incorrect.
- You can see in the gist that it is there at line 65.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @l3112 

Thanks for opening this issue.

Taking a look through this appears to be a configuration question - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
