### ISSUE TITLE
azurerm_eventhub_namespace_disaster_recovery_config is not working

### ISSUE THREAD

**Issue by SamratGunner** [terraform-providers/terraform-provider-azurerm#12675]
Error: creating Disaster Recovery Config: (Name "replicate-evenhub-poc" / Namespace Name "eventhub-primary-poc" / Resource Group "eventhub-replication"): disasterrecoveryconfigs.DisasterRecoveryConfigsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Alias 'replicate-evenhub-poc' is not availble, please use a different name. CorrelationId: ca8551a1-5050-26f1-95a5-af8cd4eed524"

**Comment by tombuildsstuff** [comment]
hi @SamratGunner 

Thanks for opening this issue.

Taking a look through here the Azure API is saying that the name is unavailable - as such picking a different (globally unique) name should fix this.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
