### ISSUE TITLE
Resource Discovery

### ISSUE THREAD

**Issue by adamhinsight** [terraform-providers/terraform-provider-azurerm#12702]
I would love to see resource discovery capability similar to whats offered by the OCI Provider but for Azure.

**Comment by tombuildsstuff** [comment]
hi @adamhinsight 

Thanks for opening this issue.

Taking a look through here unfortunately there's not enough information for us to take a look into this - when opening issues we ask that users [complete the issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Feature_Request.md&title=Support+for+%5Bthing%5D) which whilst a little long contains all of the information we need. Since there's not enough information for us to determine a path forward here I'm going to close this issue for the moment, but feel free to [open a new issue completing the issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Feature_Request.md&title=Support+for+%5Bthing%5D) and we'll take a look.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
