### ISSUE TITLE
Support for discovery of existing Azure Resources deployed with AzureRM

### ISSUE THREAD

**Issue by adamhinsight** [terraform-providers/terraform-provider-azurerm#12703]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Support for discovery of existing Azure Resources deployed with AzureRM

The ability for an existing resource deployed in Azure i.e. a VNet to be discovered by Terraform Provider AzureRM and generated into a terraform template (.tf) in the proper format to be used as a repeatable template elsewhere. This is great for environments that did not have the ability to start off with Terraform to begin with and want to migrate to Terraform, but have no ability to create the templates for whats already been deployed without Terraform. This also allows for the ability to deploy existing Azure configured resources in a standard way without having to rewrite the configuration from scratch thus improving efficiency for similar resources deployed elsewhere.

This can effect all AzureRM resources as the scope is not limited to one resource. 

### Potential Terraform Configuration

No template really to give as an example of this, but it would be binary thats generated that can discover resources from the Azure API and then generate pre-formatted terraform templates based on what the binary discovers. It would leverage the API secret/access key or other form of credentials to interface and perform the discovery.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @adamhinsight 

Thanks for opening this issue.

Taking a look through this appears to be already possible through the use of Data Sources (for example [for a Virtual Network](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/data-sources/virtual_network)) within the Provider - or using external tooling like [Terraformer](https://github.com/GoogleCloudPlatform/terraformer) which will look up existing resources and then generate both the Terraform Configuration and import these into the state for you. In addition there's [also Terraform Modules available on the Terraform Registry](https://registry.terraform.io) for both Azure and other Providers which can be used to build from for new resources - which may be worth looking into.

Since this functionality already appears to be available I'm going to close this issue for the moment, but if there's a Data Source which isn't supported by the Provider feel free to open an issue and we can take a look into that - and if there's functionality missing from Terraformer I'd suggest opening an issue in the Terraformer repository where someone should be able to take a look :)

Thanks!
