### ISSUE TITLE
Improve ACR integration during AKS cluster creation

### ISSUE THREAD

**Issue by giovannifl** [terraform-providers/terraform-provider-azurerm#12729]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AZ CLI allows with a single command to attach a new or an existing AKS cluster to an ACR Registry.
What happens is that:
- A new User Managed identity is created in Azure AD and it is assigned to AKS Nodes ( to be more specific, to its Virtual machine scale set identity)
- The ACR Pull permission on the ACR is assigned to this new identity

Terraform azurerm_kubernetes_cluster resource doesn't support this and the only way to do this is to still use a Service Principal

https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration

This feature has already been requested here:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/4636

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "aks" {

  acr_id = "........../Microsoft.ContainerRegistry/registries/myRegistry"
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @giovannifl 

Thanks for opening this issue.

Taking a look through here this appears to be a feature request for AKS rather than specific to Terraform, since there's no field exposed for this through the AKS Resource Manager API at this time.

Whilst this behaviour makes sense within the Azure CLI and PowerShell (since they're not tracking the lifecycle of these resources) - Terraform intentionally only makes changes to the Resources which are defined in the plan/config, as such we have no plans to mirror the behaviour of the Azure CLI (since this'd violate a fundamental behaviour of Terraform insofar as we only make the changes shown in the plan), instead recommending that folks use a role assignment for this.

Should this field become available within the Azure API (such that this can be added/removed) then we'll take another look into this - but at this time unfortunately this isn't something we plan to implement. As such I'd suggest [opening an issue on the AKS repository](https://github.com/Azure/AKS) where someone from that team should be able to take a look.

Thanks!

**Comment by giovannifl** [comment]
Thanks @tombuildsstuff ,
After some digging, I've discovered that this feature is already available but it is a little hidden:

Below links show that using azurerm_kubernetes_clusteraks.kubelet_identity[0].object_id will resolve this issue: 
https://newbedev.com/how-to-give-permissions-to-aks-to-access-acr-via-terraform
https://stackoverflow.com/questions/59978060/how-to-give-permissions-to-aks-to-access-acr-via-terraform

What happens is that using above identity will automatically execute what the "--attach-acr" switch does

My humble suggestion is to include this somewhere in Terraform / Azure documentation

Thanks
