### ISSUE TITLE
Terraform init - Does not download plugin

### ISSUE THREAD

**Issue by GioSebis** [terraform-providers/terraform-provider-azurerm#12726]
Hi there,

I just started using Terraform and I am trying to import my Azure resources into Terraform.

But I have a problem and I hope you can help me.

I run code `terraform init `to download plugin for provider (Azure) and I get a success massage. However no plugin is downloaded and no **.terraform** is created.

My code:

```
provider "azurerm" {
    version = "~>2.0"
    features {}
}
```

Terminal

```
PS C:\Terraform> terraform init

Initializing the backend…

Initializing provider plugins…

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running “terraform plan” to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

I am very grateful for any advice = ))

**Comment by tombuildsstuff** [comment]
hi @GioSebis 

Thanks for opening this issue.

Terraform will only download the Provider when there's some Data Sources/Resources using it - taking a look through here it appears that whilst there's a Provider block Terraform has determined that the Provider isn't necessary (since there's no Data Sources/Resources) and thus hasn't downloaded it at init time, as such adding a Data Source/Resource to the configuration should add a usage which'll enable this to be downloaded at `init` time.

Since this is a usage question about Terraform Core, I'm going to close this issue for the moment, but if that doesn't work I'd suggest [opening an issue on the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
