### ISSUE TITLE
Error creating APIM resource with publisher_email using plus addressing

### ISSUE THREAD

**Issue by sbyrnes-weblogix** [terraform-providers/terraform-provider-azurerm#12740]
resource "azurerm_api_management" "example" {
  name                = "example-apim"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  publisher_name      = "My Company"
  publisher_email     = "admin+apim@testcompany.com"
  sku_name = "Developer_1"
}

Will result in error when creating the resource of

Error: creating/updating API Management Service "ivynrl-ttest-apim" (Resource Group "ivynrl-ttest-apim-rg"): apimanagement.ServiceClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: Code="InvalidParameters" Message="Invalid parameter: Invalid publisher email address admin+apim@testcompany.com."

**Comment by sbyrnes-weblogix** [comment]
TestApimModule 2021-07-26T09:36:10Z logger.go:66: Initializing provider plugins...
TestApimModule 2021-07-26T09:36:10Z logger.go:66: - Finding latest version of hashicorp/random...
TestApimModule 2021-07-26T09:36:10Z logger.go:66: - Finding hashicorp/azurerm versions matching ">= 2.61.0, < 3.0.0"...
TestApimModule 2021-07-26T09:36:10Z logger.go:66: - Installing hashicorp/random v3.1.0...
TestApimModule 2021-07-26T09:36:11Z logger.go:66: - Installed hashicorp/random v3.1.0 (self-signed, key ID 34365D9472D7468F)
TestApimModule 2021-07-26T09:36:11Z logger.go:66: - Installing hashicorp/azurerm v2.69.0...
TestApimModule 2021-07-26T09:36:12Z logger.go:66: - Installed hashicorp/azurerm v2.69.0 (self-signed, key ID 34365D9472D7468F)

**Comment by tombuildsstuff** [comment]
hi @sbyrnes-weblogix 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
