### ISSUE TITLE
azurerm_subnet_nat_gateway_association cannot handle if subnet is already associated to another nat_gateway  

### ISSUE THREAD

**Issue by Sudharma** [terraform-providers/terraform-provider-azurerm#12755]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.69.0
```

### Affected Resource(s)

* `azurerm_subnet_nat_gateway_association`

### Problem statement

When associating an existing subnet to a nat gateway via resource `azurerm_subnet_nat_gateway_association`. Terraform aborts with an Error because the subnet is already associated to another nat gateway which shouldnt be the case since azure allows it.

### Expected Behaviour

The subnet should be successfully associated to the nat gateway.

### Actual Behaviour

```
A resource with the ID "/subscriptions/xxx/resourceGroups/RG-test-default/providers/Microsoft.Network/virtualNetworks/VNET-default/subnets/SN-default" already exists - to be managed via Terraform this resource needs t
o be imported into the State. Please see the resource documentation for "azurerm_subnet_nat_gateway_association" for more information
```

**Comment by jackofallops** [comment]
Hi @Sudharma - The response you are getting is by design, the provider won't remove/replace the existing association automatically if it is not currently managed by Terraform. To do so, you can import the item as suggested in the error message, after which if you update the configuration to your new settings terraform will replace it with the new values. I hope this helps.

**Comment by Sudharma** [comment]
Thanks @jackofallops  for the reply. However Azure allows to associate the subnet to multiple nat gateways so technically terraform also should allow right?Could you please consider the  behavior of azure as the solution? I feel importing it and adapting the state is quite a work-around.

**Comment by jackofallops** [comment]
> Thanks @jackofallops for the reply. However Azure allows to associate the subnet to multiple nat gateways so technically terraform also should allow right?Could you please consider the behavior of azure as the solution? I feel importing it and adapting the state is quite a work-around.

afaik Subnets can only have 1 associated NAT Gateway, are you able to point at the docs that show otherwise? (Portal shows a single entry drop down in the config also fwiw)
![image](https://user-images.githubusercontent.com/11830746/127834689-c8cd4a1d-200f-4406-a44c-ede6eee23b43.png)

As to the behaviour, the provider design is to not overwrite existing resources on creation, but to ensure the conscious choice to take ownership of the resource. We have no plans to change this behaviour since it works around other behavioural issues in the Azure API. If a subnet already has an association created outside of Terraform, the only options are to remove it, or import it.

**Comment by Sudharma** [comment]
you are right , my bad! I had 2 different Vnets with almost same names hence it got me confused.! Thank you for your elaboration.
