### ISSUE TITLE
Terraform support for new region

### ISSUE THREAD

**Issue by BharathDundi1** [terraform-providers/terraform-provider-azurerm#12752]
Hi team,

As part of our Azure subscription, we have the locations "jiowestindia" and "jiocentralindia" that have been added recently. These regions are only exclusive to our subscription as we are currently under the "Reliance Group". We would request that the above regions be added to the list of accepted locations in the Azure terraform provider as these are currently not recognized at the moment.

**Comment by tombuildsstuff** [comment]
hi @BharathDundi1 

The list of Azure Locations validates in the Azure Provider isn't hard-coded within the provider but instead [obtained from the Azure MetaData endpoint](https://management.azure.com/metadata/endpoints?api-version=2018-01-01) - as such for this to be added to this validation this would need to be exposed in this endpoint.

Whilst [it's possible to opt-out of enhanced location validation using this environment variable](https://github.com/terraform-providers/terraform-provider-azurerm/blob/c499bbb05de05fd15003a8b0f21d258da100e993/azurerm/internal/features/enhanced_validation.go#L14-L16) ultimately that region would need to be added to the metadata endpoint, so I'd suggest reaching out to the ARM Team who should be able to advise how to get the new region added to that endpoint.

Since this should be fixed by adding this data to the metadata endpoint (and can be worked around in the interim), whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment - but I believe the ARM Team should be able to confirm how to get the new regions added to that list when it becomes more broadly available.

Thanks!

**Comment by BharathDundi1** [comment]
Hi Tom,

Thank you for the update on this
