### ISSUE TITLE
Support for remediation/detection of Provisioning State: Failed on azurerm_firewall resource

### ISSUE THREAD

**Issue by crawfs** [terraform-providers/terraform-provider-azurerm#12760]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

If a configuration change is applied to an Azure Firewall that leaves the resources in a "Failed" provisioning state subsequent plans for the same configuration will show no changes required, despite the previous change leaving the resource in a failed state. Azure documentation suggests that to fix this state you should re-apply your configuration (see references) however this is not done by terraform due to the lack of any changes detected.

### New or Affected Resource(s)

* azurerm_firewall
* azurerm_firewall_application_rule_collection
* azurerm_firewall_nat_rule_collection
* azurerm_firewall_network_rule_collection
* azurerm_firewall_policy
* azurerm_firewall_policy_rule_collection_group

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

https://docs.microsoft.com/en-us/azure/firewall/firewall-faq#what-does--provisioning-state--failed--mean-

* #0000

**Comment by tombuildsstuff** [comment]
hi @crawfs 

Thanks for opening this issue.

Terraform intentionally only tracks resources once the platform (this applies to all providers AWS, Azure etc) has both Successfully deployed the resource and it's also ready for use (for example the DNS Name is replicated etc). Within the Azure Platform that means a `ProvisioningState` of `Succeeded` - since a `ProvisioningState` of `Failed` can mean multiple things - including both "this resource will never recover" and "this resource may become available later". This also applies to updates where resources may have staged an update but haven't provisioned it, as is the case here - which is arguably an API bug (since the new state shouldn't be returned from the API until it's rolled out).

Due to the fact that the Azure API can be ambiguous in the meaning of "Failed" that varies on a per-Resource Provider basis, unfortunately Terraform has no means of knowing whether a particular resource will become available at a given point in time - as such it's unfortunate but we require the user to determine if this resource will recover or not (since redeploying this resource, or deleting + reprovisioning could cause a further outage for example).

Whilst certain Azure API's return a sub-status in addition to `ProvisioningState`, unfortunately the Firewall API doesn't do so, as such there's no way for us to know if re-running this update would correct things or make things worse, so we require the operator to determine how to proceed here (by tainting the firewall rule, for example).

Since the Azure API's don't provide the level of granularity to determine how to proceed here, unfortunately I'm going to have to close this issue for the moment - but I'd suggest [opening an issue on the Azure Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs) so that the Firewall team can see this use-case and consider this going forward.

Thanks!
