### ISSUE TITLE
Azure kusto database table creation.

### ISSUE THREAD

**Issue by rizukp** [terraform-providers/terraform-provider-azurerm#12776]
while trying to create eventhub connection using azurerm_kusto_eventhub_data_connection , the terraform is looking for existing table resulting in following error

  Error: Error waiting for completion of Kusto Event Hub Data Connection "eventhub-data-connection" (Resource Group "ABCDEV", Cluster "adxs", Database: "my-kusto-database"): Code="EventHubValidationErorFound" Message="[BadRequest] Validation Errors found: table does not exist"

#12776 @tf-release-bot @StephenWeatherford

**Comment by tombuildsstuff** [comment]
hi @rizukp 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
