### ISSUE TITLE
App Service Plan API version "2021-01-15" not available in china yet

### ISSUE THREAD

**Issue by kankomi** [terraform-providers/terraform-provider-azurerm#12786]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "api-rg-pro"
  location = "chinaeast2"
}

resource "azurerm_app_service_plan" "example" {
  name                = "api-appserviceplan-pro"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}
```

### Panic Output
```
Error making Read request on App Service Plan "..." (Resource Group "..."): web.AppServicePlansClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="NoRegisteredProviderFound" Message="No registered resource provider found for location 'chinaeast2' and API version '2021-01-15' for type 'serverFarms'. The supported api-versions are '2020-12-01, 2020-10-01, 2020-09-01, 2020-06-01, 2019-08-01, 2018-11-01, 2018-02-01, 2017-08-01, 2016-09-01, 2016-03-01, 2015-08-01, 2015-07-01, 2015-06-01, 2015-05-01, 2015-04-01, 2015-02-01, 2014-11-01, 2014-06-01, 2014-04-01, 2014-04-01-preview'. The supported locations are 'chinanorth, chinanorth2, chinaeast, chinaeast2'."
```

### Expected Behaviour

Terraform should use the correct API version while reading the cloud state.

### Actual Behaviour

It seems the API version is lagging behind in the Azure China cloud, leading to this error.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

This problem occurs in Azure China. When rolling back to 2.69.0 `terraform apply` is working again.

### References

* #12635

**Comment by tombuildsstuff** [comment]
hi @kankomi 

Unfortunately in this instance this is something which'd need to be fixed by Microsoft rather than the Azure Provider - once an API is available in Azure Public it's supposed to be rolled out to the different Azure Environments within ~3 months - as such this API should be available in China (even if it's not right now).

Whilst Terraform could look to conditionally support different API versions depending on the environment being used, unfortunately that'd break support for Azure Public where this new functionality is necessary and as such we tend to target Azure Public API's a quarter (or so) after they become available (since at that point these should be available in other Azure Environments, such as China and Germany).

As you've mentioned to workaround this you can pin to an older version of the Provider until support for this updated API is rolled out in Azure China - but ultimately this needs Microsoft to deploy those API's within Azure China, so I'd recommend reaching out to Microsoft Support here who should be able to give a timeframe/update.

Thanks!

**Comment by MRinalducci** [comment]
Hi @kankomi,

Btw there is the same issue on region West Europe...
