### ISSUE TITLE
Circular Dependency - Support for configuring Event Hub Namespace firewall rules with a dedicated TF resource

### ISSUE THREAD

**Issue by mlcooper** [terraform-providers/terraform-provider-azurerm#12791]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have hit a circular dependency issue with deploying an Event Hub Namespace that gets used by a Logic App. Here is the synopsis:

The firewall is enabled on all of my Event Hub Namespaces (for better security, etc). I have Azure Logic Apps that connect to these Event Hub Namespaces, so you must configure the Connection IP's of the Logic Apps in the firewall permitted list of the Event Hubs.  In order for TF to obtain the connection IP's of the Logic Apps, TF must create the Logic App (they're different in every region).

So the Event Hub creation depends on the output of the Logic App creation to obtain the IP's to put in its firewall. However, the Logic Apps are being deployed in TF via ARM template (with `azurerm_resource_group_template_deployment`). The issue is that the Logic App ARM template deployment fails because it can't find the Event Hub Namespace it's supposed to connect to. And TF won't create the Event Hub Namespace until it gets  the info it needs from the Logic App.  And thus the circular dependency.

Picture of circular dependency:
![image](https://user-images.githubusercontent.com/9505606/127665151-dfaf43d1-0b3e-4858-8b3c-4672057be69d.png)

### New or Affected Resource(s)

* azurerm_eventhub_namespace_network_rule_set

### Potential Terraform Configuration

If I could create the Event Hub Namespace with `azurerm_eventhub_namespace` and then _separately_ configure its firewall with `azurerm_eventhub_namespace_network_rule_set`, I _believe_ I could eliminate this circular dependency.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @mlcooper 

Thanks for opening this issue.

Taking a look through here whilst this issue is manifesting in EventHubs, it appears this is actually a design limitation of Azure Logic Apps which means that non-trivial usage ends up creating circular dependencies.

Due to the design of the Azure Logic Apps API, namely where the Workflow payload is a JSON blob which references itself (and other resources) - it's incredibly easy to end up with a circular reference. Having spent a considerable amount of time researching different solutions to supporting Logic Apps in Terraform - we ended up settling on using separate resources to be able to provision Logic Apps in Terraform, which whilst not ideal insofar as it differs from the API's - allows you to workaround these circular references.

Whilst Logic Apps works well in the Portal and static configurations - arguably it's current design is unsuitable for more dynamic scenarios where the configuration can change (or needs to be piped through as we do today) - as such we believe that the design of the Logic Apps API is the root-cause for this, and whilst this is manifesting in the EventHubs resources, this would need to be fixed within the Logic Apps API.

From Terraform's side unfortunately we have no plans to add a separate resource for managing the Network Rule Sets for an EventHub Namespace here - and as such I'm going to close this issue for the moment. That said, I'd suggest reaching out to the Azure Logic Apps team here, since this is design issue would need to be fixed within the Azure Logic Apps service to remove these circular references (by, for example splitting the API out into different endpoints - which would enable separate resources as we use in Terraform which avoids the circular reference issue).

Thanks!
