### ISSUE TITLE
Terraform destroys and recreates AKS user node pool when changing max_count parameter

### ISSUE THREAD

**Issue by mikedizzle** [terraform-providers/terraform-provider-azurerm#12795]
The operation of updating the max nodes when autoscaling is enabled should be non breaking. You can change the min/max nodes via the portal or AZ CLI no problem. If you make the same change in a azurerm_kubernetes_cluster_node_pool block of a running node pool, Terraform has to tear it down and recreate it. 

Please help! :)

**Comment by mikedizzle** [comment]
Forgot to mention: terraform -v = 1.0.3

**Comment by tombuildsstuff** [comment]
hi @mikedizzle 

Thanks for opening this issue.

Taking a look through here both the `min_count` and `max_count` fields within the `azurerm_kubernetes_cluster_node_pool` resource aren't marked as ForceNew, as such changing them wouldn't cause this behaviour - but it's likely changing another field is doing so.

Unfortunately since the issue template hasn't been used we're missing the information we need to look into this, as such I'm going to close this issue for the moment, but feel free to open a new issue [using the issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?assignees=&labels=&template=Bug_Report.md) and we can take another look.

Thanks!

**Comment by mikedizzle** [comment]
Thanks @tombuildsstuff! Next time I will make sure to use the template. Turns out that I did not specify vnet_subnet_id in my nodepool resources. This was causing my updates to be destructive.
