### ISSUE TITLE
azurerm_virtual_machine . delete_(data|os)_disk[s]_on_termination for freshly imported resources

### ISSUE THREAD

**Issue by dweomer** [terraform-providers/terraform-provider-azurerm#1279]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```
Terraform v0.11.7
+ provider.azurerm v1.5.0
```

### Affected Resource(s)

* `azurerm_virtual_machine`
  - `delete_data_disks_on_termination`
  - `delete_os_disk_on_termination`

### Terraform Configuration Files

Caveat: I have used Terraform for some years but am new to working with Azure resources.

I am trying to write some Terraform spec for resources, that were apparently created by hand, for the purpose of import and subsequent management thereof. It seems that there is a mismatch between the defaults for `delete_data_disks_on_termination` and `delete_os_disk_on_termination` in Azure vs what gets imported. I am unable to determine the default values for these via the Azure console and they are missing from the `terraform.tfstate`. It appears that Terraform treats these as `bool` values which means that Go defaults them to `false` and so there is always a detected difference.

### Debug Output

```
  ~ azurerm_virtual_machine.vm1
      delete_data_disks_on_termination: "" => "false"
      delete_os_disk_on_termination:    "" => "false"
```

### Panic Output

n/a

### Expected Behavior

If my resource definitions are complete, I expect that after import that no resources need updating.

### Actual Behavior

VM resources always need updating after import.

### Steps to Reproduce

1. create a virtual machine by hand
2. write some HCL to capture the resource definition
3. `terraform import` for VM resource
4. check your work by invoking `terraform plan` to see if there is a delta: there always will be based on the missing values for `delete_data_disks_on_termination` and `delete_os_disk_on_termination`

**Comment by dweomer** [comment]
I added the values for these, by hand, the the `terraform.tfstate` file and subsequent `terraform plan` shows no deltas. Maybe the gap is in the import code?

**Comment by jomeier** [comment]
Hi,

correcting this took us two days with a chain of sed/grep commands. Is it so hard to implement the import delete_os_disk_on_termination correctly in the terraform azure provider?

Thank you and best regards,

Josef

**Comment by tombuildsstuff** [comment]
hi @dweomer 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We recently opened #5550 which adds support for the new Virtual Machine resources - and I'm able to confirm that this is fixed in the new Virtual Machine resources - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine` resource.

For the new resources we've moved these behavioural features from the Resource to the Provider block - so it'll be possible to define them centrally, rather than on each resource:

```
provider "azurerm" {
  features {
    virtual_machine {
      delete_os_disk_on_deletion = true
    }
  }
}
```

It's worth noting this only affects the new resources - the existing `azurerm_virtual_machine` resource will continue to use the in-line toggles; and that it's possible [to use multiple providers with aliases](https://www.terraform.io/docs/configuration/providers.html#alias-multiple-provider-instances) to configure different behaviours; for example:

```
provider "azurerm" {
  alias = "delete-things"
  features {
    virtual_machine {
      delete_os_disk_on_deletion = true
    }
  }
}

provider "azurerm" {
  alias = "save-things"
  features {
    virtual_machine {
      delete_os_disk_on_deletion = false
    }
  }
}

resource "azurerm_linux_virtual_machine" "first" {
  provider = "azurerm.delete-things"
}

resource "azurerm_linux_virtual_machine" "second" {
  provider = "azurerm.save-things"
}
```

In order to get feedback on these new resources we'll be launching support for these new resources as an opt-in Beta in an upcoming 1.x release of the Azure Provider and ultimately release these as "GA" in the upcoming 2.0 release. We'll post an update in #2807 when both the opt-in Beta (1.x) & GA (2.0) are available - as such I'd recommend subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
