### ISSUE TITLE
CosmosDB Account not found error while trying to create

### ISSUE THREAD

**Issue by pallabganai** [terraform-providers/terraform-provider-azurerm#12806]
I am trying to create an Azure cosmos account using terraform. I am executing the apply command after logging in as subscription owner.

My script is as simple as below -
```
data "azurerm_cosmosdb_account" "example" {
  name                = "tfex-cosmosdb-account"
  resource_group_name = "computervisionboxterraform6"
}
```

Error message is -

```
╷
│ Error: Error: CosmosDB Account "tfex-cosmosdb-account" (Resource Group "computervisionboxterraform6") was not found
│
│   with data.azurerm_cosmosdb_account.example,
│   on mongo.tf line 1, in data "azurerm_cosmosdb_account" "example":
│    1: data "azurerm_cosmosdb_account" "example" {
│
╵
```

What is wrong here? Why it is trying to looking for an account when I am trying to create a new one?

**Comment by tombuildsstuff** [comment]
hi @pallabganai

Thanks for opening this issue.

A Data Source looks up an existing Resource - whereas a Resource will manage the lifecycle of a resource (including Create-Read-Update-Delete). In the example above your using a Data Source rather than the Resource - as such switching to use the Resource will allow you to provision a new CosmosDB Account, [see the documentation for more information](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/cosmosdb_account).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by pallabganai** [comment]
Silly, rookie mistake. Thanks for quick reply.
