### ISSUE TITLE
TF azurerm_virtual_machine resource does not detect 'version' update.

### ISSUE THREAD

**Issue by AdilKhan1117** [terraform-providers/terraform-provider-azurerm#12812]
Hi,

Update azurerm_virtual_machine 'version' does not detect an update if version is updated. 

I have updated Palo Alto VM from 9.0.1 to 10.0.6 and TF plan did not detect this at all.

**Comment by tombuildsstuff** [comment]
hi @AdilKhan1117 

Taking a look through here the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward.

Thanks!

**Comment by AdilKhan1117** [comment]
thank you very much @tombuildsstuff

**Comment by xpillons** [comment]
@tombuildsstuff can you please backport this in the `azurerm_virtual_machine` because the `azurerm_linux_virtual_machine` doesn't cover yet all the scenarios provided by `azurerm_virtual_machine`.
Please see issue #12953

**Comment by xpillons** [comment]
Thanks Tom, I understand. When is this expected ?
