### ISSUE TITLE
[Not Working] target_resource_location for azurerm_monitor_metric_alert

### ISSUE THREAD

**Issue by nitmatgeo** [terraform-providers/terraform-provider-azurerm#12858]
The [azurerm_monitor_metric_alert](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_metric_alert#target_resource_location) offers a parameter `target_resource_location` which is required when scope is assigned at subscription level. Azure allows to create metric alerts scoped to entire subscription inclusive across any location but Terraform is forcing one region and not allowing list of locations. Location value of 'global' is also not recognized. There must be some error issue in Terraform API.

**Comment by tombuildsstuff** [comment]
hi @nitmatgeo 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by nitmatgeo** [comment]
@tombuildsstuff  I am sure, this is either a bug or a minor enhancement within azurerm_monitor_metric_alert. I request you to please reconsider, this is not a question even if I may have sounded so. Please let me know if I need to explain the issue further.

**Comment by nitmatgeo** [comment]
@tombuildsstuff Error message is below and when I hardcode the value of _targetResourceRegion_ with a specific location there is no error; but in that case, the metric gets applied only for resources in specified region whereas, in azure I am able to configure it across all regions!

│ **Error:** Error creating or updating metric alert "alerts-pocabc01" (resource group "testMonitoring"): insights.MetricAlertsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="targetResourceRegion property is missing or invalid. Activity ID: 8xxxxxxxxxxxxxxxxxxxxxxxx4."
