### ISSUE TITLE
How can I connect using service-principale

### ISSUE THREAD

**Issue by seitosan** [terraform-providers/terraform-provider-azurerm#1297]
Hi, 

when i try to connect with : 

```shell
az login --service-principal -u $CLIENT_ID -p $CLIENT_SECRET --tenant $TENANT_ID
```
and I run terraform plan i have : 

```
provider.azurerm: No valid (unexpired) Azure CLI Auth Tokens found. Please run `az login` 
```

have you any Idea how to can I connect using service-principal ?

**Comment by seitosan** [comment]
```
terraform version
Terraform v0.11.7
+ provider.azurerm v1.6.0
+ provider.random v1.3.1

```

**Comment by tombuildsstuff** [comment]
hi @seitosan 

Thanks for opening this issue.

We support authenticating as a Service Principal either by specifying the Client ID and Client Secret as Environment Variables - or by specifying them in-line; however we don't support authenticating as a Service Principal via the Azure CLI. 

The Terraform Website contains information on [creating and configuring a Service Principal](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html) and then [how to use specify these parameters either in the `provider` block or as Environment Variables](https://www.terraform.io/docs/providers/azurerm/index.html#argument-reference) - would you be able to take a look? Since this is a question rather than a bug in Terraform - I'm going to close this issue for the moment.

Thanks!

**Comment by seitosan** [comment]
Thanks a lot. Best regards
