### ISSUE TITLE
broken data azurerm_subnet route_table_id: not functioning

### ISSUE THREAD

**Issue by bernadinm** [terraform-providers/terraform-provider-azurerm#1337]
### Terraform Version

```
$ terraform -v
Terraform v0.11.7
+ provider.azurerm v1.5.0
```

### Affected Resource(s)

```hcl
data "azurerm_subnet" "public" {
  name                 = "cisco-csr-subnet-public"
  virtual_network_name = "${data.azurerm_virtual_network.current.name}"
  resource_group_name  = "${data.azurerm_resource_group.rg.name}"
  route_table_id       = "${azurerm_route_table.RTPublic.id}" # Not functioning 
}
```

### Debug Output

```hcl
Error: data.azurerm_subnet.public: "route_table_id": this field cannot be set
```
### Expected Behavior

I expected that an existing subnet will be associated with an existing routing table. 

### Actual Behavior

Terraform failed. 

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

There does not see to be any other way to do this in terraform. The data resource is the most appropriate resource to achieve linking an existing subnet to a routing table. Currently it is possible within the Azure Portal UI to associate the subnet to the routing table, but not with terraform at the moment.

**Comment by tombuildsstuff** [comment]
hi @bernadinm 

Thanks for opening this issue, apologies for the delayed response here!

Data Sources in Terraform are for referencing information about existing resources (e.g. getting the ID of a Storage Account) - rather than for modifying information about them.

It's possible to import an existing resource into Terraform [using  the`terraform import` command](https://www.terraform.io/docs/import/index.html) - which can then be managed via the `azurerm_route_table` Resource. for instance [here's how to import a Route Table into the State](https://www.terraform.io/docs/providers/azurerm/r/route_table.html#import):

```
terraform import azurerm_route_table.test /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.Network/routeTables/mytable1
```

Once the existing Resource has been imported into Terraform, it's then possible to change the value of this property via the `azurerm_route_table` resource. Would you be able to take a look and see if this resolves your issue?

Since this is a question about Terraform rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue to take a look/respond 😄)

Thanks!

**Comment by bernadinm** [comment]
Thank you @tombuildsstuff, if this is the case then what we're missing is this resource here `route_table_association` in the same way we have it for AWS. 

https://www.terraform.io/docs/providers/aws/r/route_table_association.html

Do you recommend me making a separate feature request to ask for this resource in `terraform-provider-azurerm` provider?
```
data "azurerm_subnet" "public" {
  name                 = "mysubnet"
  virtual_network_name = "some-resource-group"
}

data "azurerm_route_table" "test" {
  name                = "myroutetable"
  resource_group_name = "some-resource-group"
}

resource "azurerm_route_table_association" "a" {
  subnet_id      = "${data.azurerm_subnet.public.id}"
  route_table_id = "${data.azurerm_route_table.test.id}"
}
```

**Comment by tombuildsstuff** [comment]
hi @bernadinm 

Unfortunately the Azure API isn't designed in such a way that this is possible (in general the API generally prefers creating monolithic resources rather than composable resources) - whilst it _technically_ is possible to implement this resource by hacking around the `azurerm_subnet` resource, it'd lead to us having conflicts with that resource; as such the only way we could implement this safely would be to deprecate the field `route_table_id` from the subnet resource in favour of this new resource.

That said - I think this could make sense as a change but needs some more thought; would you mind opening a new issue specifically about this?

Thanks!
