### ISSUE TITLE
azurerm_notification_hub ID was missing the `notificationHubs` element. 

### ISSUE THREAD

**Issue by bkulkarnisononi** [terraform-providers/terraform-provider-azurerm#13691]
azurerm_notification_hub  is giving  "ID was missing the `notificationHubs` element. " error when trying to run through Azure devops Pipelines.

I checked the following.
resource syntax is correct.
the resource is untainted in remote state file.

I tried to create the notification hub through azure portal and import it in terraform. the result lands in same error through pipeline.
Thanks in advance for your input. 

here is raw log from pipeline.

2021-10-11T12:25:45.0033609Z Error: ID was missing the `notificationHubs` element
2021-10-11T12:25:45.0033916Z 
2021-10-11T12:25:45.0034039Z 
2021-10-11T12:25:45.0034421Z Com***leted Terraform Plan.
2021-10-11T12:25:45.0034847Z Ski***ed Terraform A***ly.
2021-10-11T12:25:45.0069230Z ##[error]Bash wrote one or more lines to the standard error stream.
2021-10-11T12:25:45.0081079Z ##[error]
Error: ID was missing the `notificationHubs` element

**Comment by tombuildsstuff** [comment]
hi @bkulkarnisononi 

Thanks for opening this issue.

Per [the import documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/notification_hub#import) the Resource ID for a Notification Hub ID should be in the format `/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.NotificationHubs/namespaces/namespace1/notificationHubs/hub1` - as such Terraform is raising an error that this isn't the case. As such I'd recommend checking the casing on the Notification Hub ID when importing this resource to fix this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
