### ISSUE TITLE
Error : updating Authentication Settings for Function App "function-name": web.AppsClient#UpdateAuthSettings: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Cannot execute the request for site "function-name" because the site is running on auth version v2."

### ISSUE THREAD

**Issue by HamzaHAMADI** [terraform-providers/terraform-provider-azurerm#13795]
Hello All,

I'm trying to deploy an Azure Function with the "Authentication" part and I want to use the Microsoft identity provider :
![137925238-c8058714-92ab-4f8f-a1e8-eac490240bd4](https://user-images.githubusercontent.com/22317916/137933729-0d9d57d6-deeb-43dc-a427-ef25f038b217.png)

But i think that terraform-provider-azurerm not support the auth V2.
i have this error :
"updating Authentication Settings for Function App "function-name": web.AppsClient#UpdateAuthSettings: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="BadRequest" Message="Cannot execute the request for site "function-name" because the site is running on auth version v2.""

Can you help me to resolve this problem.

**Comment by stephybun** [comment]
Hi @HamzaHAMADI.

Thanks for opening this issue. This appears to be a usage question rather than a bug in the Azure Provider. We encourage users to raise broader questions like this in one of the [Community Resources](https://www.terraform.io/community.html) or in our [Slack Channel](https://terraform-azure.slack.com/). Since this forum is intended for feature requests and bugs in the Azure Provider I am going to close this issue for the moment.

Thanks!
