### ISSUE TITLE
Feature Request: Allow Service Bus Topic Subscriptions to be created in a "disabled" state

### ISSUE THREAD

**Issue by mjgpy3** [terraform-providers/terraform-provider-azurerm#146]
Some azure infrastructure (functions specifically) auto-create a "parent subscription" in ServiceBus from which children filter. This is nice but, in some cases, children handle all messages and the parent gets filled (wasting space). As a workaround, I currently manually create the parent subscription and immediately disable it.

**Comment by tombuildsstuff** [comment]
Hey @mjgpy3

Thanks for opening this issue :)

So that we can take a look into this, would you mind clarifying what you mean by a `Subscription`? Azure uses the term `Subscriptions` in several contexts, I'm assuming you mean an Azure Subscription - however it could also be a couple of other things e.g. Service Bus Subscription

Thanks! :)

**Comment by mjgpy3** [comment]
@tombuildsstuff I'm talking about Service Bus Subscriptions -- thanks for the timely reply!

**Comment by tombuildsstuff** [comment]
Awesome - thanks for confirming that @mjgpy3 - I'll take a look :)

**Comment by tombuildsstuff** [comment]
Hey @mjgpy3 

Just to let you know that I've opened #150 which allows Service Bus Topic's to be set to `Disabled` or `Active` :)

Thanks!

**Comment by mjgpy3** [comment]
@tombuildsstuff awesome, thank you!
