### ISSUE TITLE
Add support for Run Command

### ISSUE THREAD

**Issue by giskou** [terraform-providers/terraform-provider-azurerm#1480]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for Run Command [1]

This requires the azure agent to be running on the host.
Note that this is different from using azurerm_virtual_machine_extension [2]
The later crates a new resouce in azure and does not give any info about the output of the command.

### New or Affected Resource(s)

* azurerm_virtual_machine_run_command

### Potential Terraform Configuration

```hcl
resource "azurerm_virtual_machine_run_command" "test" {
  name = "uptime"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_machine_name = "${azurerm_virtual_machine.test.name}"
  command = "uptime"
  parameters = "-p"
  script = "${file("script.sh")}"   # optional
}
```

### References

* [1] https://docs.microsoft.com/en-us/rest/api/compute/virtual%20machines%20run%20commands/runcommand
* [2] https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html

**Comment by tombuildsstuff** [comment]
hi @giskou 

Thanks for opening this issue :)

Taking a quick look into this - from what I can see I believe these commands are executed directly on a machine and then the output is returned, which means it probably doesn't fit as a resource within Terraform since there's no way for us to detect if a commands already been run or not. Given there's no way for us to add support for this resource in Terraform - I'm going to close this issue for the moment.

That said - I believe you should be able to use [the `remote-exec` provisioner](https://www.terraform.io/docs/provisioners/remote-exec.html) to achieve the same thing - would you be able to take a look and see if this works for you?

Thanks!
