### ISSUE TITLE
Can I manually delete provisioned resources in azure when using terraform?

### ISSUE THREAD

**Issue by rocifier** [terraform-providers/terraform-provider-azurerm#1492]
When I provisioned a resource group in azure using terraform, I made a mistake. So I went into the portal and deleted the resource group. I was then unable to run or apply any plan in terraform. The error provided was 404 resource group not found as in bug #49.

**Comment by tombuildsstuff** [comment]
hi @rocifier 

Thanks for opening this issue :)

> When I provisioned a resource group in azure using terraform, I made a mistake. So I went into the portal and deleted the resource group. I was then unable to run or apply any plan in terraform.

Terraform's got two different kinds of resources which are handled differently here:

1. Resources - for which if the resource doesn't exist (such as it's been manually deleted in the Portal), Terraform will suggest re-creating it as part of a plan
2. Data Sources - for which the referenced object must exist, otherwise the plan would fail.

Based on the comment above it sounds like you're using a Resource to provision the Resource Group - but would you be able to show the Terraform Configuration you're using to achieve this?

Thanks!

**Comment by tombuildsstuff** [comment]
Closing this since we've not heard back here.
