### ISSUE TITLE
Virtual machine extension Linux

### ISSUE THREAD

**Issue by Gomory666** [terraform-providers/terraform-provider-azurerm#1506]
Hello,

Terraform v0.11.7

I have a problem with "virtual machine extension" for linux

My code block :  

`resource "azurerm_virtual_machine_extension" "postfix" {
  name                 = "configure-postfix"
  location             = "${var.location}"
  resource_group_name  = "${var.resource_group_name}"
  virtual_machine_name = "${element(azurerm_virtual_machine.postfix.*.name, count.index)}"
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

  settings = <<SETTINGS
     {
        "skipDos2Unix":true,
          "autoUpgradeMinorVersion": true,
         "fileUris": "${var.script_configuration_path}install_postfix.sh"
     }
 SETTINGS

  protected_settings = <<PROTECTED_SETTINGS
  {
      "commandToExecute": "bash install_postfix.sh"
  }
PROTECTED_SETTINGS

  tags {
    environment = "${var.environment}"
  }`

When I try to deploy it, I had this error : 

* azurerm_virtual_machine_extension.postfix: 1 error(s) occurred:

* azurerm_virtual_machine_extension.postfix: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'publisher' is not allowed." Target="publisher"

Thanks for you help

**Comment by tombuildsstuff** [comment]
hi @Gomory666 

Thanks for opening this issue :)

The error message you're seeing: `Changing property 'publisher' is not allowed` indicates that there's already a VM Extension been run on this Virtual Machine named `configure-postfix`. Would you be able to remove this extension - then this should work as expected?

Since this is a question regarding Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment.

Thanks!

**Comment by Gomory666** [comment]
Thanks for your answer, it's now good
