### ISSUE TITLE
Azure terraform_remote_state requires extra creds

### ISSUE THREAD

**Issue by stonefury** [terraform-providers/terraform-provider-azurerm#1514]
I’ve read about keeping state files separate which then leads to requiring remote state access via the data object. But with azure at least I am required to provide separate credentials for accessing the state file, even though my current az login or creds for the current plan already has the privilege to read the state file. 

There is no way to share the creds already in use, and no mechanism to get those keys. Do I need to add scripting for each component where I request the access key for that component prior to running terraform?  So if I need to access the state file in some other component I ask it for it’s key and then inject that into my plan via tfvars?

I just see this environment where I separate my state files per component and now I need to pass their access keys all over be place where I need to read their state file. 

Tnx

**Comment by tombuildsstuff** [comment]
hey @stonefury 

Thanks for opening this issue :)

> There is no way to share the creds already in use, and no mechanism to get those keys. Do I need to add scripting for each component where I request the access key for that component prior to running terraform? So if I need to access the state file in some other component I ask it for it’s key and then inject that into my plan via tfvars?

So the `terraform_remote_state` data source comes from the Terraform provider which is separate from the AzureRM Provider and lives within Terraform Core (for various reasons). In order to be able to reuse your existing credentials, the Backend would need to be updated to use the additional auth types this provider now supports; which has previously been requested [in this issue which I'm going to close this in favour of](https://github.com/hashicorp/terraform/issues/16763).

Regarding how to access that in the interim - you should be able to use an external script to get those and set the relevant Environment Variables. Another possible approach would be to make use of Data Sources to access the properties you need.

Thanks!
