### ISSUE TITLE
I can't join a second vm in availability_set

### ISSUE THREAD

**Issue by Gomory666** [terraform-providers/terraform-provider-azurerm#1526]
Hello everybody,

I have a problem with availability_set I can't join a second machine to my availibity-set created before 

My code 

```
resource "azurerm_availability_set" "mail-as" {
  name                         = "${var.availability_set_name}${count.index +1}"
  location                     = "${var.location}"
  resource_group_name          = "${var.resource_group_name}"
  platform_fault_domain_count  = "${var.platform_fault_domain_count}"
  platform_update_domain_count = "${var.platform_update_domain_count}"
  managed                      = true
  tags                         = "${var.tags}"
}

resource "azurerm_virtual_machine" "postfix" {
  count                            = "${var.vm_count}"
  name                             = "${var.vm_name_prefix}${count.index + 1}"
  location                         = "${var.location}"
  resource_group_name              = "${var.resource_group_name}"
  network_interface_ids            = ["${azurerm_network_interface.postfix.*.id[count.index]}"]
  availability_set_id              = "${azurerm_availability_set.mail-as.id}"
  delete_os_disk_on_termination    = "${var.delete_os_disk_on_termination}"
  delete_data_disks_on_termination = "${var.delete_data_disks_on_termination}"
  vm_size                          = "${var.vm_size}"

  boot_diagnostics {
    enabled     = "${var.boot_diagnostics_enabed}"
    storage_uri = "${var.boot_diagnostics_enabed == "true" ? data.terraform_remote_state.storage.storage_account_primary_blob_endpoints[0] : "" }"
  }

  storage_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04.0-LTS"
    version   = "latest"
  }

  storage_os_disk {
    name              = "${var.vm_name_prefix}${count.index + 1}-System"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }

  # Optional data disks
  storage_data_disk {
    name          = "${var.vm_name_prefix}${count.index + 1}-Logs"
    disk_size_gb  = "${var.vm_log_disk_size}"
    create_option = "Empty"
    caching       = "ReadWrite"
    lun           = 1
  }

  os_profile {
    computer_name  = "${var.vm_name_prefix}${count.index + 1}"
    admin_username = "${var.vm_admin_username}"
    admin_password = "${var.vm_admin_password}"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }

  tags = "${var.tags}"
}
```

Error message 
```
* azurerm_virtual_machine.postfix.0: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'availabilitySet.id' is not allowed." Target="availabilitySet.id"
```

**Comment by tombuildsstuff** [comment]
hi @Gomory666 

Thanks for opening this issue :)

> Changing property 'availabilitySet.id' is not allowed.

In this instance the Virtual Machine you're provisioning already exists, but Azure says it's not possible to modify the Availability Set ID.

Terraform stores the state of the world as it knows it in a Statefile (generally `terraform.tfstate`) - which we use to determine when resources should be re-created. In this instance if the Virtual Machine were present in the Statefile - Terraform would ask you if you want to delete and recreate the Virtual Machine, since that's the only way to get to that state. As you're seeing this error message from the Azure API it means that this Virtual Machine isn't in your statefile / was created outside of Terraform; it's possible to import this Virtual Machine into Terraform using `terraform import`, at which point running `terraform plan` or `terraform apply` will show you that Terraform needs to recreate this Virtual Machine. There's more information about Importing a Virtual Machine [available in the documentation](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#import). Alternatively you should be able to achieve the same thing by deleting this Virtual Machine in the Azure Portal/via the CLI.

Since this question is regarding Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment.

Thanks!
