### ISSUE TITLE
plan failed if image not found for data.azurerm_image

### ISSUE THREAD

**Issue by lfuentes-lbn** [terraform-providers/terraform-provider-azurerm#1559]
Hello,
I've got terraform code which works (as far I know) until today. Some changes have been done to add data disks for a particular virtual machine. For information, all virtual machines created with terraform use an azurerm_image created with Packer.

What is surprising me today is that it seem that `terraform plan` now failed if the image use for `data.azurerm_image` doesn't exist yet. If I remember well, that was not an issue some weeks ago. All is working well (plan and apply) if I launch Packer first for create the image.

This make me sad because we use gitlab's CI/CD:

- when you push in a branch a check pipeline start in order to check if packer's syntax is ok and if terraform is ok
- if ok, a manuel pipeline can be triggered in order to create the image with packer and then launch the terraform apply.

How can I said to the "terraform plan" to not care about the image used exist or not ?

edit: only workaround I found is to use `--refresh=false` for the plan

**Comment by tombuildsstuff** [comment]
hi @lfuentes-lbn 

Thanks for opening this issue :)

> What is surprising me today is that it seem that terraform plan now failed if the image use for data.azurerm_image doesn't exist yet. If I remember well, that was not an issue some weeks ago. All is working well (plan and apply) if I launch Packer first for create the image.

In older versions of the AzureRM Provider a bug was present which returned `nil` rather than an error when an item defined in a Data Source didn't exist. So that we could make the behaviour of the AzureRM Provider more like the other Providers - in v1.5 of the AzureRM Provider we updated this behaviour to return an error rather than nil when an item defined in a Data Source couldn't be found.

Assuming that your images have some consistency in their naming (for example the names are suffixed with the build time), it should be possible to work around this by using the `name_regex` and `sort_descending` attributes in the `azurerm_image` data source together to obtain the latest image.

> if ok, a manuel pipeline can be triggered in order to create the image with packer and then launch the terraform apply.

Whilst it's outside the scope of this issue (and I don't have all the context) - it sounds like it could be beneficial to split this into two steps, one to provision the Packer image and one to handle Terraform; since you don't necessarily want to re-build a Packer image to scale the number of instances involved?

Since this is a question regarding Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!
