### ISSUE TITLE
Feature Request: Azure Database for PostgreSQL

### ISSUE THREAD

**Issue by mooperd** [terraform-providers/terraform-provider-azurerm#158]
Hi, What is the support for the new postgresql databases?

@whiskeyjay - Are you a Microsoft person?

**Comment by tombuildsstuff** [comment]
Hey @mooperd 

Thanks for opening this issue :)

I've started looking into this previously - and in order to add support for both the Postgres and MySQL Databases we first we need Swagger which covers the relevant Azure API's - and then once that's done to update the Azure SDK for Go to include these API's which will allow us to add support for these services.

There's [a Pull Request open for adding the Swagger for both Postgresql and MySQL here](https://github.com/Azure/azure-rest-api-specs/pull/1338) - once that's merged we should be able to proceed fairly quickly here :)

Until that's supported natively - you can use the `azurerm_template_deployment` resource to deploy these services via Terraform - but there's also downsides to this approach (since Terraform doesn't know about the resources within the ARM Template).

Thanks!

**Comment by tombuildsstuff** [comment]
Hey @mooperd 

An update: [the Swagger PR's](https://github.com/Azure/azure-rest-api-specs/pull/1338) been merged - and a PR has been opened to [add these SDK's to the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go/pull/681). Once that's been merged and released we'll take a look into adding these resources :)

Thanks!

**Comment by tombuildsstuff** [comment]
👋 

So I've taken a look into supporting this this afternoon and [added support for most of the PostgreSQL resources (Servers / Databases / Firewall Rules) into this branch](https://github.com/terraform-providers/terraform-provider-azurerm/compare/postgresql?expand=1).

Whilst doing this, I noticed a bug in the Swagger which needs to be fixed first - and as such [I've opened this PR](https://github.com/Azure/azure-rest-api-specs/pull/1391) which allows us to specify a `adminLogin` and `adminPassword` at create time. Once that PR is merged, we can generate the SDK and then finish up here :)

Thanks!

**Comment by mooperd** [comment]
That was a whirlwind of activity. Thanks for picking it up!

**Comment by mooperd** [comment]
@tombuildsstuff Do you have an idea when this might be landing in master? I saw there was some activity in the Swagger repo.

**Comment by tombuildsstuff** [comment]
@mooperd not right now unfortunately, this needs a fix in [the AutoRest code generator](https://github.com/Azure/autorest) to allow a working version of the Postgres Go SDK to be generated - at which point we can progress with this :)

**Comment by tombuildsstuff** [comment]
@mooperd just to let you know that this has landed in the Azure SDK v10.2.1 - I've opened #209 which updates this Provider to that version, at which point we can proceed with this :)

**Comment by tombuildsstuff** [comment]
@mooperd I've spent a little while rebasing this branch today and have opened #210 which includes support for the PostgreSQL resources :)
