### ISSUE TITLE
Feature Request: Data source for Azure Location

### ISSUE THREAD

**Issue by Ashex** [terraform-providers/terraform-provider-azurerm#1591]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be incredibly helpful to have a data source that simply returns details about the specified location, defaulting to the current one. 

The key benefit is when working with modules since they by design inherit the provider (or specified) when sourced. This would allow us to simply use a data source rather than requiring a location variable be passed to every single module since the the azurerm provider would already been initialised with the location.

This would ideally behave the same was at the [aws_region](https://www.terraform.io/docs/providers/aws/d/region.html) data source.

### New or Affected Resource(s)

* azurerm_location

### Potential Terraform Configuration

```hcl

#Inherit default location provided
data "azurerm_location" "this" {
}

# Use specified location
data "azurerm_location" "specified" {
  location = "northeurope"
}

resource "azurerm_resource_group" "rg" {
  name     = "${local.name}"
  location = "${data.azurerm_location.this.name}"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet"
  location            = "${data.azurerm_location.this.name}"
  address_space       = ["172.10.0.0/19"]
  resource_group_name = "${azurerm_resource_group.rg.name}"
}
```

**Comment by tombuildsstuff** [comment]
hi @Ashex 

Thanks for opening this issue :)

In the AWS Provider the location's specified in the Provider block (since there are API's per AWS region) - which allows us to expose a data source with this information. By contrast in Azure the location's required on certain top-level resources such as Resource Groups or Virtual Machines which is then populated based on the given resource. Whilst it'd be possible for us to provide a Data Source which returns the value you're passing in, it'd be the same as providing a variable which will be specified anyway.

Instead - since a Resource Group name is required on all top-level resources where the location's required, I'd suggest one alternative here would be to pull this information from the `azurerm_resource_group` data source; such as below:

```
data "azurerm_resource_group" "test" {
  name = "my-resource-group"
}

output "location" {
  value = "${data.azurerm_resource_group.test.location}"
}
```

It's also possible to do the same thing with the Resource Group resource, which means this can be threaded through via that resource, rather than hard-coded in each resource; to use an example from your code sample:

```
resource "azurerm_resource_group" "rg" {
  name     = "${local.name}"
  location = "North Europe"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "vnet"
  location            = "${azurerm_resource_group.rg.location}"
  address_space       = ["172.10.0.0/19"]
  resource_group_name = "${azurerm_resource_group.rg.name}"
}
```

Would you be able to take a look and see if that works for you? It's also possible to do this with other resources using the `location` field too, such as the `azurerm_virtual_machine` resource. Given this information isn't available to us - and there's no region specific information (other than Quota's, for which Terraform's not really the right place to expose that information); I'm going to close this issue for the moment.

Thanks!
