### ISSUE TITLE
Support Attaching multiple Disks azurerm_virtual_machine_data_disk_attachment 

### ISSUE THREAD

**Issue by nirmalparekh1984** [terraform-providers/terraform-provider-azurerm#1594]
### Description
Requesting enhancement for azurerm_virtual_machine_data_disk_attachment to support attaching multiple data disk to a VM.
Current implementation attaches 1 disk at a time. With Windows VM, this process becomes very slow when say more than 1 disk is required to be attached. As after every disk attach, VM update is called. Once VM update is done, only then the next disk is attached and again VM Update is called.

VM update, considerable, slows down the process.

Suggestion is to allow attaching multiple disk and then run VM update only once.

### New or Affected Resource(s)
* azurerm_virtual_machine_data_disk_attachment

### Potential Terraform Configuration
```
 resource "azurerm_virtual_machine_data_disk_attachment" "attach_disk" {   
  depends_on         = ["azurerm_virtual_machine.vm"]
  managed_disk_ids    = "${azurerm_managed_disk.md.*.id}"
  virtual_machine_id = "${local.vm_id}"
  lun                = ["0","",""]    # or autoincrement lun from the first number provided
  caching            = "ReadWrite"
}
```

### Current Terraform Implementation
```
resource "azurerm_virtual_machine_data_disk_attachment" "attach_disk" {
  depends_on         = ["azurerm_virtual_machine.vm"]
  count              =      "${var.disks_per_vm}"
  managed_disk_id    = "${element(azurerm_managed_disk.md.*.id, count.index)}"
  virtual_machine_id = "${local.vm_id}"
  lun                = "${count.index%var.disks_per_vm}"
  caching            = "ReadWrite"
}
```

**Comment by nirmalparekh1984** [comment]
for 3 disks per VM - it too me more than 24 mins for disk attachment to complete
```
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.1: Still creating... (24m20s elapsed)
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.3: Still creating... (24m20s elapsed)
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.1: Still creating... (24m30s elapsed)
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.3: Still creating... (24m30s elapsed)
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.1: Still creating... (24m40s elapsed)
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.3: Still creating... (24m40s elapsed)
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.3: Still creating... (24m50s elapsed)
module.create_vm.virtual_machine.azurerm_virtual_machine_data_disk_attachment.attach_disk.1: Still creating... (24m50s elapsed)
```

**Comment by tombuildsstuff** [comment]
hi @nirmalparekh1984 

Thanks for opening this issue :)

> Current implementation attaches 1 disk at a time. With Windows VM, this process becomes very slow when say more than 1 disk is required to be attached. As after every disk attach, VM update is called. Once VM update is done, only then the next disk is attached and again VM Update is called.

Within the `azurerm_virtual_machine_data_disk_attachment` resource we have to lock due to limitations of the Azure API - where only one change can be made to a VM at a time (I believe this is because it interacts with the VM Agent on the machine, but I may be wrong) otherwise the API returns an error; as such I don't think there's a way for us to work around this in the short-term.

That said - it should be possible to do the same thing using the `storage_data_disk` block in the `azurerm_virtual_machine` resource with [some of the upcoming changes to Terraform 0.12](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each) - which allows for these blocks to be specified dynamically. Whilst it's not ideal, in the interim this allows for static lists of disks to be attached in the same fashion. Given there's no immediate path forward for this issue - I'm going to suggest we close this for the moment.

Thanks!
