### ISSUE TITLE
azurerm_virtual_machine_scale_set: mismatch on apply

### ISSUE THREAD

**Issue by Supermathie** [terraform-providers/terraform-provider-azurerm#1616]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.9.0
+ provider.random v1.3.1
+ provider.template v1.0.0

### Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Terraform Configuration Files

Output of terraform plan and apply attached:
[terraform.bugreport.txt.asc.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/2211326/terraform.bugreport.txt.asc.txt)

### Expected Behavior

Application of plan without error

### Actual Behavior

    Terraform Version: 0.11.7
    Resource ID: azurerm_virtual_machine_scale_set.app
    Mismatch reason: attribute mismatch: network_profile.1854554140.ip_configuration.0.application_gateway_backend_address_pool_ids.1842515611

### Steps to Reproduce

1. `terraform apply`

### References

* Ø

**Comment by tombuildsstuff** [comment]
hi @Supermathie 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We've recently opened the PR for the first of these new resources #4518 - and I'm able to confirm that this bug is now fixed in the new Virtual Machine Scale Set resource - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine_scale_set` resource.

We've posted an update in #2807 with more information on this (we plan to release the new Virtual Machine / Virtual Machine Scale Set resources in a Beta form in a future 1.x version of the Azure Provider and subsequently release them as "GA" in 2.0) - but as we plan to post additional status updates for 2.0 in #2807 I'd suggest subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
