### ISSUE TITLE
403 when creating container app_service

### ISSUE THREAD

**Issue by ndarilek** [terraform-providers/terraform-provider-azurerm#1633]
Using the newly-released v1.10.0 with the following configuration:

```
resource "azurerm_resource_group" "app" {
  name = "app-${terraform.workspace}"
  location = "West US"
}

resource "azurerm_app_service_plan" "plan" {
  name = "plan"
  location = "${azurerm_resource_group.app.location}"
  resource_group_name = "${azurerm_resource_group.app.name}"
  kind = "Linux"
  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_app_service" "app" {
  name = "loconomics-${terraform.workspace}"
  location = "${azurerm_resource_group.app.location}"
  resource_group_name = "${azurerm_resource_group.app.name}"
  app_service_plan_id = "${azurerm_app_service_plan.plan.id}"
  site_config {
    linux_fx_version = "DOCKER|loconomics/loconomics"
  }
  app_settings {
    "WEBSITES_PORT" = "1337"
    WEBSITES_ENABLE_APP_SERVICE_STORAGE = "false"
  }
}
```

Unfortunately, every attempt to access my container throws a 403. There don't appear to be any errors when running `terraform apply`.

Is there any way to debug this further from the command line? I'm blind, Azure's web portal has some pretty huge accessibility issues, and that's why I'm trying to manage this all via Terraform. I seem to recall that viewing container/deployment logs for Linux containers may not be supported via the command line. Any other debugging tips?

Thanks.

**Comment by tombuildsstuff** [comment]
hey @ndarilek 

Thanks for opening this issue :)

> Is there any way to debug this further from the command line?

So there's two things needed order to provision a Linux App Service plan: setting the `kind` field to `Linux` and setting `reserved` to `true`; if the `reserved` field isn't set to `true` then a Windows App Service Plan is provisioned even if you've specified a Linux one. Unfortunately this is by design in the API - that said I believe we should be able to work around this by adding validation that when a Linux App Service Plan is provisioned, the `reserved` flag must be set to true - which would avoid this issue.

Regarding the Terraform Configuration that you've posted - that'd make this:

```
resource "azurerm_resource_group" "app" {
  name     = "app-${terraform.workspace}"
  location = "West US"
}

resource "azurerm_app_service_plan" "plan" {
  name                = "plan"
  location            = "${azurerm_resource_group.app.location}"
  resource_group_name = "${azurerm_resource_group.app.name}"
  kind                = "Linux"

  sku {
    tier = "Standard"
    size = "S1"
  }

  properties {
    reserved = true
  }
}

resource "azurerm_app_service" "app" {
  name                = "loconomics-${terraform.workspace}"
  location            = "${azurerm_resource_group.app.location}"
  resource_group_name = "${azurerm_resource_group.app.name}"
  app_service_plan_id = "${azurerm_app_service_plan.plan.id}"

  site_config {
    linux_fx_version = "DOCKER|loconomics/loconomics"
  }

  app_settings {
    "WEBSITES_PORT"                       = "1337"
    "WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "false"
  }
}
```

(I've also added quotes around the key `WEBSITES_ENABLE_APP_SERVICE_STORAGE` - but that's purely so it matches the other key)

I can confirm that when provisioning this updated Terraform Configuration that the Docker Container is accessible at https://loconomics-default.azurewebsites.net/.

I'm going to leave this issue open until the validation issue I mentioned above is fixed - but would you be able to take a look and confirm if this works for you?

Thanks!

**Comment by ndarilek** [comment]
Yes, I can confirm that this works for me. Thanks!

While we're on the subject of validations:
 * Should the container name be parenthesized? I.e. `linux_fx_version = "DOCKER|loconomics/loconomics"` vs. `linux_fx_version = "DOCKER|(loconomics/loconomics)"`?) The docs golang example has it parenthesized, which didn't work for me in the first attempt.
 * Do I need to set `"WEBSITES_ENABLE_APP_SERVICE_STORAGE" = "false"`? I set that based on the template in the original issue, but I don't know if it's needed. I'm going to test without it, but if it is required then that may be another validation candidate.

Thanks again. I've really been struggling with this one.

**Comment by tombuildsstuff** [comment]
hi @ndarilek 

Sorry for the delayed response here!

Just to let you know that I've added some examples for using Containers within an App Service in #2913 which should help clarify this.

Thanks!
