### ISSUE TITLE
No connection could be made because the target machine actively refused it

### ISSUE THREAD

**Issue by jonymaldo** [terraform-providers/terraform-provider-azurerm#1639]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
provider.azurerm v1.10.0

### Affected Resource(s)

* azurerm_virtual_machine
* provisioner "file"

### Terraform Configuration Files

https://gist.github.com/jonymaldo/99739d0d0bd81dd11bb816f8bcb4f86c

### Expected Behavior
Upload the file  named 'UpdateBPM.ps1' to BPM virtual machine

### Actual Behavior
https://gist.github.com/jonymaldo/723f24ec5092c7962621d2b5b6dd55a4

### Steps to Reproduce

1. `terraform apply -parallelism=6`

**Comment by tombuildsstuff** [comment]
hey @jonymaldo 

Thanks for opening this issue :)

Unlike other Providers - the Azure Provider doesn't set the connection information for Virtual Machines at this time, as such this information needs to be specified in the connection block. I've opened #1645 (which I'm going to close this in favour of) to ensure this information is set on the Virtual Machine resource so that users don't need to set this information. Would you be able to take a look and see if setting the IP Address in the connection block solves this issue for you?

Thanks!

**Comment by jonymaldo** [comment]
@tombuildsstuff  thanks by your fast response, I setting the IP address in the connection block, ***but doesn't work***, the response is '''unknown error Post http://{{IP_ADDRESS}}:5985/wsman: dial tcp {{IP_ADDRESS}}:5985: connectex: A connection attempt failed because the connected party did not properly respond after a period of time, or established connection failed because connected host has failed to respond.''' , I update  the **Terraform Configuration Files** in the gist

Thanks
