### ISSUE TITLE
Tags support in azurerm_virtual_network

### ISSUE THREAD

**Issue by AGregersen** [terraform-providers/terraform-provider-azurerm#1651]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Support in Terraform for adding tags on this type of resource in Azure.

### New or Affected Resource(s)

* azurerm_virtual_network

* #0000

**Comment by tombuildsstuff** [comment]
hi @AGregersen 

Thanks for opening this issue :)


The `azurerm_virtual_network` Resource supports setting tags on the Virtual Network [via the `tags` property](https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html#tags) - would you be able to take a look and see if this is what you're looking for?

Since this is a question regarding Terraform Configuration rather than a bug in the AzureRM Provider I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!
