### ISSUE TITLE
azurerm_management_lock is automatically updated if locked resource changes

### ISSUE THREAD

**Issue by anoff** [terraform-providers/terraform-provider-azurerm#1653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

```text
▶ tf -v
Terraform v0.11.7
+ provider.azurerm v1.11.0
```

### Affected Resource(s)

* azurerm_management_lock

### Terraform Configuration Files

```hcl
resource "azurerm_management_lock" "group-1" {
  name       = "resource-rg1"
  scope      = "${azurerm_resource_group.test.id}"
  lock_level = "CanNotDelete"
  notes      = "Do not kill"
}

resource "azurerm_resource_group" "test" {
  name     = "testResourceGroup1"
  location = "westeurope"
}
```

### Expected Behavior

Terraform creates a lock on the resource group `test` and when changes to the resource would cause a deletion of the resource group terraform fails due to an active lock.

Locks can be used to prevent accidental removal of resources via TF recipe changes.

### Actual Behavior

Terraform also changes the lock.

Locks only prevent manual changes to the infrastructure; changes to resources via TF are unlocked automatically.

### Steps to Reproduce

Deploy above example

Change recipe to a new resource group name

```hcl
resource "azurerm_management_lock" "group-1" {
  name       = "resource-rg1"
  scope      = "${azurerm_resource_group.test.id}"
  lock_level = "CanNotDelete"
  notes      = "Do not kill"
}

resource "azurerm_resource_group" "test" {
  name     = "testResourceGroup123"
  location = "westeurope"
}
```

plan or apply

```text
Terraform will perform the following actions:

-/+ azurerm_management_lock.group-1 (new resource required)
      id:         "/subscriptions/XX/resourceGroups/testResourceGroup1/providers/Microsoft.Authorization/locks/resource-rg1" => <computed> (forces new resource)
      lock_level: "CanNotDelete" => "CanNotDelete"
      name:       "resource-rg1" => "resource-rg1"
      notes:      "Do not kill" => "Do not kill"
      scope:      "/subscriptions/XX/resourceGroups/testResourceGroup1" => "${azurerm_resource_group.test.id}" (forces new resource)

-/+ azurerm_resource_group.test (new resource required)
      id:         "/subscriptions/XX/resourceGroups/testResourceGroup1" => <computed> (forces new resource)
      location:   "westeurope" => "westeurope"
      name:       "testResourceGroup1" => "testResourceGroup123" (forces new resource)
      tags.%:     "0" => <computed>


Plan: 2 to add, 0 to change, 2 to destroy.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @anoff

Thanks for opening this issue :)

Terraform treats the Management Lock resource the same way it does any other resource - in that should changes need to be made to it the Management Lock will appear in your plan requesting that changes occur. It's possible to exclude the Management Lock resource from changes by using either [the `ignore_changes` or the `prevent_destroy` properties in the `lifecycle` block](
https://www.terraform.io/docs/configuration/resources.html#prevent_destroy) to ensure this resource isn't deleted by Terraform - which I believe should be the feature you're after here (since this will allow Azure to enforce the Management Lock when attempting to delete the Resource Group). Would you be able to take a look and see if this works for you?

Since this is a question regarding Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding :smile:)

Thanks!
