### ISSUE TITLE
azurerm_virtual_machine tries to change name of a disk rather than detach/create/attach

### ISSUE THREAD

**Issue by Supermathie** [terraform-providers/terraform-provider-azurerm#1668]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.7
+ provider.azurerm v1.11.0
+ provider.random v1.3.1
+ provider.template v1.0.0

### Affected Resource(s)

* azurerm_virtual_machine

### Terraform Configuration Files

```diff
 azurerm_virtual_machine {
   …
-  # swap
+  # data disks
   storage_data_disk {
-    name              = "build-swap"
+    name              = "build-data"
     managed_disk_type = "Standard_LRS"
     create_option     = "Empty"
     lun               = 0
-    disk_size_gb      = "${var.swap_size}"
+    disk_size_gb      = "${var.data_size}"
   }
 }
```

### Expected Behavior

terraform should

* detach disk
* destroy old disk
* create disk
* attach disk

### Actual Behavior

```
  ~ module.monitor.azurerm_virtual_machine.monitor[0]
      storage_data_disk.0.disk_size_gb:         "2" => "32"
      storage_data_disk.0.name:                 "monitor-0-swap" => "monitor-0-data"
…

* azurerm_virtual_machine.monitor.0: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'dataDisk.name' is not allowed." Target="dataDisk.name"

```

### Steps to Reproduce

1. `terraform apply`

### References

* Ø

**Comment by jackofallops** [comment]
Closing this issue as we're currently working on version 2.0 of the Azure Provider which we previously announced in #2807. 

As a part of this we're introducing five new resources which will supersede the existing azurerm_virtual_machine and azurerm_virtual_machine_scale_set resources:

azurerm_linux_virtual_machine
azurerm_linux_virtual_machine_scale_set
azurerm_virtual_machine_scale_set_extension
azurerm_windows_virtual_machine
azurerm_windows_virtual_machine_scale_set

We recently opened #5550 which adds support for the new Virtual Machine resources - which require attaching Data Disks using the azurerm_managed_disk and azurerm_virtual_machine_data_disk_attachment resources rather than having them defined inline, which allows for more granular control/flexibility when modifying disks. Since the existing Virtual Machine resource is being superseded, unfortunately we have no plans to backport this to the existing azurerm_virtual_machine resource - however we’ll be publishing information on the new resources (and how you can opt-into the Beta) in the near-future.

Thanks
