### ISSUE TITLE
data_lake_store documentation `Pay As You Go` and `Monthly Commitment Tier` should be broke out into two seperate code samples

### ISSUE THREAD

**Issue by jeffreyCline** [terraform-providers/terraform-provider-azurerm#1672]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)
`data_lake_store.html.markdown`

### Expected Behavior
* The code sample should just work as is when you copy and paste it out of the docs.
* Import statement should work once you enter your subscription information.

### Actual Behavior
```
Error: azurerm_resource_group.test: resource repeated multiple times
```
The import string is also wrong, it points to the `Resource Group` and not the `Data Lake Store` instance:

Import for `Pay As You Go`:
```
terraform import azurerm_data_lake_store.consumption /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.DataLakeStore/accounts/mydatalakeaccount
```
Import for `Monthly Commitment Tier`:
```
terraform import azurerm_data_lake_store.monthly /subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/mygroup1/providers/Microsoft.DataLakeStore/accounts/mydatalakeaccount
```

### Steps to Reproduce
```
terraform init
```

### References
[PR #1219 ](https://github.com/terraform-providers/terraform-provider-azurerm/pull/1219/files)

**Comment by tombuildsstuff** [comment]
@jeffreyCline 

> Expected Behavior
> > The code sample should just work as is when you copy and paste it out of the docs.

It's worth noting the code samples aren't intended to be copy-pasteable but are instead references (which is why they're titled `Example Usage`). In a lot of the smaller resources these examples are copy-pastable, but in general they'll require some tweaking from users to match their environment (for instance Data Sources require that actual resources exist) and we're going to be doing more to make these more readable in future (e.g. #1665 simplifies the VM Documentation by moving the examples out, and I expect VMSS will be a good candidate to do next)

> Actual Behavior
>> Error: azurerm_resource_group.test: resource repeated multiple times
> The import string is also wrong, it points to the Resource Group and not the Data Lake Store instance:

The error you're seeing here is because the `azurerm_resource_group` is defined multiple times in code (this would also fail for other terraform commands like plan) - would you be able to remove it and take a look?

Thanks!
