### ISSUE TITLE
"Preview roles are not supported" for azurerm_role_assignment

### ISSUE THREAD

**Issue by ams0** [terraform-providers/terraform-provider-azurerm#1692]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [Terraform community resources](https://www.terraform.io/docs/extend/community/index.html)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

---
Using:
Terraform v0.11.7
+ provider.azurerm v1.11.0

When trying to assign the role "Storage Blob Data Reader (Preview)" to a Managed User Identity I have the `Preview roles are not supported` error; however, it looks like it could be done in azure-sdk-for-go (https://github.com/Azure/azure-sdk-for-go/issues/1895). What am I missing?

**Comment by ams0** [comment]
Any update on this? It would greatly help to be able to assign this preview roles via Terraform!

**Comment by tombuildsstuff** [comment]
hey @ams0 

Thanks for opening this issue / apologies for the delayed response here!

This [behaviour is currently intentional](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_role_assignment.go#L179) as we don't support Data Actions within Terraform at the current time (although that's being tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1538) - however once #1538 has been fixed/merged, I believe we should be able to remove this check.

Thanks!

**Comment by cwiederspan** [comment]
it looks like #1538 is closed out and running. Given that, any ETA on an update for this issue?

**Comment by ms1111** [comment]
As a workaround, I was able to use `az role definition list` to find the full ID of the built-in preview role I wanted like to use in my subscription. For example:

```
resource "azurerm_role_assignment" "assignment" {
  scope = "${azurerm_storage_account.account.id}"
  # "Storage Blob Data Contributor (Preview)"
  role_definition_id = "/subscriptions/${local.subscription_id}/providers/Microsoft.Authorization/roleDefinitions/ba92f5b4-2d11-453d-a403-e96b0029c9fe"
  principal_id = ...
}
```
