### ISSUE TITLE
Feature Request: Split Arguments from Azure Application Gateway to their own Resources

### ISSUE THREAD

**Issue by Parvez-dkda** [terraform-providers/terraform-provider-azurerm#1694]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

My intentions are to deploy a Single Application Gateway for multiple Back-end servers.  The issue is that all Back-end servers will not be deployed at the same time, but as new systems are enrolled.  I created two terraform modules one to create the VMs and another to create the base infrastructure.  Every time there is a new Back-end VM enrolled, I would create a new TF for this system, which would essentially add a new entry in the application gateway.

### New or Affected Resource(s)

Affected
* azurerm_application_gateway

New
* azurerm_gateway_backend_address_pool
* azurerm_http_listener
* azurerm_request_routing_rule

### Potential Terraform Configuration

```
resource "gateway_backend_address_pool" "test" {
    name = "pool-test"
    application_gateways_ids = "${azurerm_application_gateways.test.*.id"
  }

resource  "http_listener" "test" {
    name                           = "http-test"
    application_gateways_ids = "${azurerm_application_gateways.test.*.id"
    frontend_ip_configuration_name = "FrontEnd_cfg"
    frontend_port_name             = "Port-80"
    protocol                       = "Http"
    host_name                      = "test.contoso.com"
  }

resource "request_routing_rule" "test" {
    name                       = "rule-test"
    application_gateways_ids = "${azurerm_application_gateways.test.*.id"
    rule_type                  = "Basic"
    http_listener_name         = "${azurerm_http_listener.test.name}"
    backend_address_pool_name  = "${azurerm_gateway_backend_address_pool.test.name}"
    backend_http_settings_name = "${azurerm_application_gateways.test..backend_address_pool.id"
  }

```

### References

* https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html

**Comment by tombuildsstuff** [comment]
hi @Parvez-dkda 

Thanks for opening this issue :)

This has previously been requested in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1542 which is currently being tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1576 due to a bug in the upstream API. At this point in time there's two things blocking this enhancement:

1) the API requires all of these fields exist when the Application Gateway is created
2) the Application Gateway API is broken - which is being tracked in #1576

Once both of these issues are fixed it should be possible to investigate adding support for this - however for the moment I'd suggest following #1576 for updates, which I'm going to close this issue in favour of.

Thanks!

**Comment by Parvez-dkda** [comment]
Hi @tombuildsstuff 
Thanks for the update!
