### ISSUE TITLE
How to link a azurerm schedule with a runbook using terraform under automation account

### ISSUE THREAD

**Issue by biswanathmoharana2014** [terraform-providers/terraform-provider-azurerm#1711]
Hi Team,
could you please advice on how to link a azurerm_automation_runbook present under automation account to the azurerm_automation_schedule using terraform.

**Comment by jcmaasb** [comment]
Hi Team,
Is there a forecast to modify / add some resource to solve this situation? 
Recently I tried to create the necessary resources in an automation account and I ran into the same problem.

**Comment by holmesb** [comment]
I'm getting the impression this is a feature request.  I can't see any way of linking an Azure Automation Runbook to a schedule.  Can @Kemyke or @katbyte confirm?  I expect we need functionality like powershell's [Register-AzureRmAutomationScheduledRunbook](https://docs.microsoft.com/en-us/powershell/module/azurerm.automation/register-azurermautomationscheduledrunbook?view=azurermps-6.8.1)

**Comment by tombuildsstuff** [comment]
hi @biswanathmoharana2014 @jcmaasb @holmesb 

Thanks for opening this issue :)

This behaviour is currently unsupported by Terraform - however taking a quick look into this it should be possible to add this once an SDK is available. This'd probably become it's own resource `azurerm_automation_scheduled_runbook` (which doesn't currently exist) - since there's a feature request for this now open in the form of #1955 - I'm going to close this issue in favour of that one, please subscribe to that issue for updates.

Thanks!
