### ISSUE TITLE
NIC change resource group

### ISSUE THREAD

**Issue by OffColour** [terraform-providers/terraform-provider-azurerm#1733]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Changing the resource group should not always force a new resource. It's possible move a resource between resource groups in the Azure portal, but Terraform forces a new resource.
If you try to do this with a NIC, it fails because the NIC is already in use on a VM and you can't have a VM without a NIC.

Only way to resolve via Terraform is to destroy the VM in one run, have the NIC destroyed/created and then recreate the VM.

I've seen a similar issue regarding changing resource group names that was closed last year on the grounds that resources could not be moved between groups. As this is no longer true, can this wider enhancement be added?

### New or Affected Resource(s)

* azurerm_network_interface

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by magodo** [comment]
@OffColour Thank you for submitting this interesting requirement :+1: 

I think the similar issue you mentioned is #109, though the clarification might not true today, while it still applies to azurerm provider that resource group acts as *hard environment, that is immutable, not a metadata reference pointer to switch/migrate resources from one to the other*.
To support the [move resource functionality](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription) is something we can hardly support in terraform. As you know, terraform engine resolves the dependency between resources based on referenced attributes or explicit `depends_on` directive. But in the context of `move resource`, it asks users to [manage the dependency and ensure all the dependent resources are moved to the same resource group/subscription as a whole](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription#frequently-asked-questions), which is non-trivial to implement in terraform provider.

On the other hand, maybe this kind of ad-hoc operation is not a fit to use terraform at all, either because it is rare and short-lived. I would suggest you do the following workaround:

1. Use portal/cli/pwsh to do the movement task on your resource
2. Run `terraform destroy --target=<the moved resource>` to remove the resource. As this resource has been moved to another resource group/subscription, the ID of this resource will be changed and terraform will not actually remove it, but only remove the entry from statefile
3. Modify terraform config to reflect the movement (e.g. modify the `resource_group_name` to the target group)
4. Run `terraform import <the moved resource> <the new ID of the moved resource>` to import the moved resource back to the management of terraform

I hope the above workaround helpful. As we are not planning to support resource movement in the near future, and the issue has been last for a long time, I'm gonna close it for now. If you have further questions or the workaround above doesn't work for you, then please feel free to using one of the [Community Resources](https://www.terraform.io/community.html) to ask.
