### ISSUE TITLE
Creating App Service Plan on an Existing App Service Environment

### ISSUE THREAD

**Issue by rifaterdemsahin** [terraform-providers/terraform-provider-azurerm#1735]
* [Configuration]
 Terraform v0.11.7
+ provider.azurerm v1.12.0
* [State] 
Blocked
* [Provisioner]
Azure

* [Steps]
Creating App Service Environment which is Isolated fails, Standart one succeeds

* [IaC]
resource "azurerm_app_service_plan" "aselinuxserviceplan" {
  depends_on          = ["azurerm_resource_group.trn_services"] 
  name                = "ServicePlanLinux${var.environment}"
  location            = "${var.region}"
  resource_group_name = "${var.servicesresourcegroup}"
  kind 		      = "linux"
  sku {
    tier = "Isolated"
    size = "I1"
    capacity = "1"
  }
  properties {
    per_site_scaling = "false"
    reserved = "true"
  }

 tags {
    environment = "${var.environment}",description="Linux box for the containers"
  }
}

* [Error]
Error: Error applying plan:

1 error(s) occurred:

* azurerm_app_service_plan.aselinuxserviceplan: 1 error(s) occurred:

* azurerm_app_service_plan.aselinuxserviceplan: web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

Need to learn what I am missing here. Cheers

**Comment by senthamaraiarasi1** [comment]
it is working for me

**Comment by tombuildsstuff** [comment]
hi @rifaterdemsahin 

Sorry for the delayed response here.

Earlier versions of the Azure Provider didn't correctly expose error messages due to a bug in the Azure SDK - as such I believe this has been fixed (or rather, the underlying error is now exposed). Since I believe this has been fixed I'm going to close this issue for the moment - but please let us know if this is still broken for you on a newer version of the Azure Provider (the current version is v1.32.1) and we'll take another look.

Thanks!
