### ISSUE TITLE
using multiple providers azurerm and azuread causes "features": required field is not set

### ISSUE THREAD

**Issue by ImperiumTakp** [terraform-providers/terraform-provider-azurerm#17539]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

3.201.18

### AzureRM Provider Version

3.12.0

### Affected Resource(s)/Data Source(s)

azuread_group

### Terraform Configuration Files

```hcl
provider "azurerm" {
  skip_provider_registration = true
  subscription_id = var.subscriptionID
  alias = "rm"
  features {}
}

provider "azuread" {
  skip_provider_registration = true
  alias = "ad"
}

terraform {
  backend "azurerm" {
    container_name = lower(var.tfstate)
    key            = "terraform.${lower(var.tfstate)}"
  }
}

terraform {
  required_providers {
    azuread = {
      source  = "hashicorp/azuread"
      version = "~> 2.0.0"
    }
  }
}


data "azuread_group" "ad_grp" {
  display_name     = var.adContributorGroup
  security_enabled = true
}
```

### Debug Output/Panic Output

```shell
data.azuread_group.ad_grp: Read complete after 0s [id=balfksfghfgafgsdfghafgasdfgdsfghdf]
╷
│ Error: Insufficient features blocks
│ 
│   on <empty> line 0:
│   (source code not available)
│ 
│ At least 1 "features" blocks are required.
╵
##[warning]Can't find loc string for key: TerraformPlanFailed
##[error]Error: TerraformPlanFailed 1
```

### Steps to Reproduce

terraform plan -lock=false -out plan.tfplan

**Comment by tombuildsstuff** [comment]
hi @ImperiumTakp 

Thanks for opening this issue.

Taking a look through here this is an issue with the Terraform Configuration being used, for example a resource being provisioned using the `azurerm` provider without the `rm` alias set - which would use an unaliased instance of the provider (and would raise this error, since there's no instance of the "azurerm" provider defined without an alias, and hence the `features` block isn't set for it).

Since this is a configuration issue rather than a bug in the Azure Provider I'm going to close this issue for the moment, but you should be able to fix this by checking the resources being used which aren't using an aliased provider - but should you have further configuration questions I'd direct you towards [the Community Discuss forum](https://discuss.hashicorp.com).

Thanks!
