### ISSUE TITLE
azurerm_sql_database: add support for vCore licensing

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#1779]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add support for the [vCore licensing model](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-service-tiers-vcore) now present in Azure SQL.

### New or Affected Resource(s)

* azurerm_sql_database

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_database" "test" {
  name                = "mysqldatabase"
  resource_group_name = "best_rg_ever"
  location = "West US"
  server_name = "mysqlserver1"
  vcore = 2
}
```

### References

May be similar to request for vCore support in SQL Elastic Pools (#1745).

**Comment by tombuildsstuff** [comment]
hey @kjhosein 

Thanks for opening this issue :)

Support for the vCore Licencing Model has previously been requested in 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1745 which, so that we don't have multiple issues open tracking the same thing - I'm going to close this issue in favour of 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1745 - would you mind subscribing to that issue for updates?

Thanks!

**Comment by kjhosein** [comment]
Thx for the reply Tom. I could be wrong on this, but shouldn't these be different issues, since I could have a SQL database without building a SQL Elastic Pool? From a TF perspective, wouldn't  you have to write the vCore functionality into both resources?

**Comment by liamjbennett** [comment]
@tombuildsstuff just ran into this issue again. Can we re-open?
