### ISSUE TITLE
azurerm_storage_account_sas reveals sensitive data in console

### ISSUE THREAD

**Issue by subesokun** [terraform-providers/terraform-provider-azurerm#1809]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

v0.11.8

### Affected Resource(s)

* azurerm_storage_account_sas

### Expected Behavior

SAS URL query string should be marked as sensitive.

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

sas_url_query_string = <sensitive>
```
### Actual Behavior

SAS URL query string gets printed.

```
Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

Outputs:

sas_url_query_string = ?sv=2017-07-29&ss=b&srt=s&sp=rl&se=...
```

### Steps to Reproduce

1. `terraform apply`

**Comment by subesokun** [comment]
Just wanted to ask, is there any short term fix possible to include it in the next release?

**Comment by tombuildsstuff** [comment]
hi @subesokun 

Thanks for opening this issue :)

Within Terraform Resources and Data Sources can mark their fields as Sensitive or not in the Schema used, which is the case with the `sas` field in the `azurerm_storage_account_sas ` Data Source. However as this value's being used in an output - an additional field needs to be set in order for this to be [marked as sensitive](https://www.terraform.io/docs/configuration/outputs.html#sensitive) in the console.

Would you be able to take a look and see if setting the `sensitive` flag to `true` in the output works for you? There's an example of this below:

```
data "azurerm_storage_account_sas" "test" {
  # ...
}

output "sas_url_query_string" {
  value     = "${data.azurerm_storage_account_sas.test.sas}"
  sensitive = true
}
```

In the interim - since this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by subesokun** [comment]
@tombuildsstuff Thanks for the clarification! Yes that solves my issue :) Sorry I've mixed it up with the previous issues regarding sensitive data in the azurerm resources.
