### ISSUE TITLE
VM Identity block inflexible when used in a module.

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#1813]
### Terraform Version

```
Terraform v0.11.8
+ provider.azurerm v1.13.0
```

### Affected Resource(s)

`azurerm_virtual_machine`

### Terraform Configuration Files

main.tf - https://gist.github.com/rohrerb/52fb32bc248a5ad9fecc44c1af8d9f95

### Actual Behavior

We use the same VM Module with 50 different types of VM's.  We only want MSI Identity to be enabled on a select few VMs. 

### Steps to Reproduce

1. `bulid a vm module'
2.  Attepmt to use a variable to control whether or not Identity type is configured or not. 

  ```
identity {
    type = "${var.enable_msi ? "SystemAssigned" : ""}"
   } 
```

> Error: module.wbox.azurerm_virtual_machine.vm: expected identity.0.type to be one of [SystemAssigned UserAssigned], got

We would prefer not to duplicate our module just to have this one resource field enabled.  Is there a way that the API could take a empty string?   

Any help or guidance would be appreciated.

-Brandon

**Comment by tombuildsstuff** [comment]
hey @rohrerb 

Thanks for opening this issue :)

> Is there a way that the API could take a empty string?

We use blocks to signify the presence of an object, as such I think allowing an empty string value here would cause more confusion (for instance, when the `object_id` field is unset). That said - it should be  possible to work around this by passing in the identity block here:

```
variable "msi_block_identity" {
  type = "map"
  default = {
    "type" = "SystemAssigned"
  }
}


resource "azurerm_virtual_machine" "test" {
  # ...
  identity = "${var.msi_block_identity}"
  # ...
}
```

Would you be able to take a look and see if that works for you? Since this is a configuration question rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by rohrerb** [comment]
Hi @tombuildsstuff 

No luck getting this to work...

main.tf - https://gist.github.com/rohrerb/fae778135b6938a4131540b544907683

**Result:**
`
Error: azurerm_virtual_machine.vm: identity: should be a list`

My end goal would be to use a variable to toggle identity on / off...

` identity = "${var.enable_msi ? var.msi_block_identity : ""}"`

**Comment by tombuildsstuff** [comment]
@rohrerb 
> Error: azurerm_virtual_machine.vm: identity: should be a list

given that's a list it should be possible to do `identity = ["${var.msi_block_identity}"]`

> My end goal would be to use a variable to toggle identity on / off...
