### ISSUE TITLE
Resource 'data.azurerm_public_ip.gateway-public-ip' does not have attribute 'ip_address' for variable 'data.azurerm_public_ip.gateway-public-ip.ip_address'

### ISSUE THREAD

**Issue by edwins-genebygene** [terraform-providers/terraform-provider-azurerm#1826]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.13.0

### Affected Resource(s)

* azurerm_public_ip

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "ag-ip" {
  name                         = "${var.instance_name}_app-gateway-ip"
  resource_group_name          = "${var.resourceGroupName}"
  location                     = "${var.resourceGroupLocation}"
  public_ip_address_allocation = "dynamic"
  idle_timeout_in_minutes      = 4
}
...

data "azurerm_public_ip" "gateway-public-ip" {
  name                = "${azurerm_public_ip.ag-ip.name}"
  resource_group_name = "${var.resourceGroupName}"
}

output "appGatewayIp" {
  value = "${data.azurerm_public_ip.gateway-public-ip.ip_address}"
}
```

### Expected Behavior

It should output public IP address

### Actual Behavior

Errors out while running plan with the following error: 

```
module.qa.module.azure-networking.output.appGatewayIp: Resource 'data.azurerm_public_ip.gateway-public-ip' does not have attribute 'ip_address' for variable 'data.azurerm_public_ip.gateway-public-ip.ip_address'
```

### Steps to Reproduce

1. `terraform apply`

**Comment by edwins-genebygene** [comment]
Adding `depends_on = ["azurerm_application_gateway.ag"]` seems to have fixed the problem 🤷

**Comment by tombuildsstuff** [comment]
hi @edwins-genebygene 

Thanks for opening this issue :)

In this instance the Dynamic Public IP isn't available until it's attached to something, for instance in your case above (without the `depends_on`) the Public IP will be retrieved prior to the Public IP being attached to the Application Gateway. It's also possible to reference fields on the Application Gateway in order to be able to infer the dependency ordering - as can be seen in this sample: https://www.terraform.io/docs/providers/azurerm/d/public_ip.html#example-usage-retrieve-the-dynamic-public-ip-of-a-new-vm-

Since you've managed to get this working and that this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment.

Thanks!

**Comment by edwins-genebygene** [comment]
Thank you!
