### ISSUE TITLE
Resource to Enable Azure Providers

### ISSUE THREAD

**Issue by tomvachon** [terraform-providers/terraform-provider-azurerm#1832]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be great if we had a resource akin to [Google Project Service](https://www.terraform.io/docs/providers/google/r/google_project_service.html) which would allow us to turn on the Azure providers in code.  This would allow modules to declaratively state which providers they need enabled.

### New or Affected Resource(s)

* azurerm_provider_service

### Potential Terraform Configuration

```hcl
resource "azurerm_provider_service" "providers" {
  subscription_id = "your-subscription-id"
  tenant_id = "your-tenant-id"
  provider_namespaces = ["Microsoft.Example", "Microsoft.Foo", "Microsoft.Bar"]
}
```

### References

* https://docs.microsoft.com/en-us/rest/api/resources/providers/register

**Comment by tombuildsstuff** [comment]
hey @tomvachon 

Thanks for opening this issue :)

Terraform currently does automatic registration of [any Resource Providers that Terraform supports as part of the Terraform run](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/provider.go#L364-L395) - in the use-case outlined above, is the intention to deploy resources which aren't supported via Terraform? Whilst it's possible to [opt-out of the Resource Provider Registration](https://www.terraform.io/docs/providers/azurerm/#skip_provider_registration) - we don't recommend it since things can fail with an error about the Resource Provider not being registered (whilst you could potentially disable this behaviour, we'd need to ensure the `Microsoft.Resources` Resource Provider was registered to be able to register any Resource Providers).

Thanks!

**Comment by Humoiz** [comment]
I`m working on this resource. Will send out a PR tonight or tomorrow.
