### ISSUE TITLE
AKS cluster with static IP address destroy issue

### ISSUE THREAD

**Issue by andrey-moor** [terraform-providers/terraform-provider-azurerm#1837]
**Goal:** Provision AKS cluster with public static IP address (JFYI: https://docs.microsoft.com/en-us/azure/aks/static-ip).

**Resource definition snippet:**
```
resource "azurerm_kubernetes_cluster" "kubernetes" {
  ...
}

resource "azurerm_public_ip" "kubernetes" {
  resource_group_name  = "${azurerm_kubernetes_cluster.kubernetes.node_resource_group}"
  ...
}
```

**Issue:**
The AKS cluster and static IP address are provisioned successfully using `terraform apply` command. A service defined in Kubernetes also able to use just created IP address (by setting `loadBalancerIP` property to the IP address value of static IP address defined above).

The issue happens during execution of `terraform destroy` command: based on the resource definition above static IP address depends on the AKS cluster as it should be deployed to the same resource group as a Kubernetes load balancer. So when Terraform tried to destroy resources, it starts from IP address and fails as it is still assigned to a service and being used by AKS load balancer. 

Is there any way to force Terraform to destroy AKS cluster first in this case (as it will remove the load balancer and release IP address)? Any other thoughts?

**Comment by andrey-moor** [comment]
Any suggestions?

**Comment by matyaskov** [comment]
We're also struggeling with this problem.

**Comment by tombuildsstuff** [comment]
hey @andrey-moor 

Thanks for opening this issue - apologies for the delayed response here!

Unfortunately since the Public IP is attached to the AKS cluster outside of Terraform (by AKS) - as you've mentioned Terraform is unable to determine that this needs to be detached before deleting the Public IP (since there's no Explicit or Implicit Dependency configured) - as such the best option would be to use `depends_on` attribute to ensure the AKS cluster is deleted before the Public IP. It may be possible for Terraform to infer this if you're using [the Kubernetes Provider](https://github.com/terraform-providers/terraform-provider-kubernetes) to manage this (since there'd be an explicit dependency configured)

Since this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (however we'll continue responding 😄)

Thanks!

**Comment by jambt** [comment]
Just a quick update, because I ran into a similar problem: Using the Kubernetes Provider did not help. Although a link is created between the Kubernetes service and the public IP, there is an eventually consistency bug. The service is deleted immediately, but azure recognizes it only a few minutes thereafter and allows for deletion of the IP address.

Thus, the first attempt to destroy fails.

**Comment by cmeyertons** [comment]
@andrey-moor great stuff!  this did the trick.

in your snippet, is it a typo to still be using the AKS cluster resource group for the public IP?  I ended up just creating a separating resource group and referencing that.

also, don't calling out you need to give access to your cluster's service principal for that new resource group if you go this route:

tf
```tf
resource "azurerm_resource_group" "aks-ip-rg" {
  name = "${local.aks_name}-ip"
  location = "${var.location}"
}

resource "azurerm_public_ip" "aks-ip" {
  name = "${local.aks_name}-ip"
  location = "${azurerm_resource_group.aks-ip-rg.location}"
  resource_group_name = "${azurerm_resource_group.aks-ip-rg.name}"
  public_ip_address_allocation = "static"
  domain_name_label = "${local.aks_name}"
}

resource "azurerm_role_assignment" "aks-ip-rg" {
  scope                = "${azurerm_resource_group.aks-ip-rg.id}"
  role_definition_name = "Contributor"
  principal_id         = "${module.aks-service-principal.id}"
}

resource "azurerm_kubernetes_cluster" "aks" {
    depends_on = [ "azurerm_public_ip.aks-ip" ]
    ....

   service_principal {
        client_id     = "${module.aks-service-principal.application_id}"
        client_secret = "${module.aks-service-principal.password}"
    }
}
```
values.yaml
```
istio:
  gateways:
    istio-ingressgateway:
      loadBalancerIP: "YOUR_IP"
      serviceAnnotations:
        service.beta.kubernetes.io/azure-load-balancer-resource-group: IP_RG_NAME_HERE
```

Cheers!

**Comment by andrey-moor** [comment]
@cmeyertons good catch thank you
