### ISSUE TITLE
scm_type ExternalGit beeing removed by terraform

### ISSUE THREAD

**Issue by thoregilk** [terraform-providers/terraform-provider-azurerm#1840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.13.0
+ provider.null v1.0.0

### Affected Resource(s)

azurerm_app_service

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "default" {

        name                = "${module.internal_label.id}"
        location            = "${var.location}"
        resource_group_name = "${var.resource_group_name}"
        app_service_plan_id = "${var.app_service_plan_id}"

        tags                = "${module.null_label.tags}"

        site_config {
          default_documents = "${var.default_documents}"
          php_version = "${var.php_version}"
         }      

}

```

### Expected Behavior

When running terraform apply, it should do nothing since the scm_type is not yet supported in terraform and portal is the only way to configure this, so it should do nothing and leave the configuration as it is.

### Actual Behavior

~ module.webapp_monitor.azurerm_app_service.default
      site_config.0.scm_type:                                                "ExternalGit" => "None"

### Steps to Reproduce

1. `terraform apply`

### References

* #1104

**Comment by tombuildsstuff** [comment]
hi @thoregilk 

Thanks for opening this issue :)

Since Terraform can manage the `scm_type` block - removing the block (since it's not defined) is probably the correct behaviour (although this can be ignored using the `ignore_changes` attribute in the `lifecycle` block). That said, since we support configuring this block we should also support setting the field `scm_type` to other Types (such as `ExternalGit`). There's an issue tracking support for this in #1104 which I'm going to close this in favour of - would you mind subscribing to that for updates?

Thanks!
