### ISSUE TITLE
Application Insights application_type doesn't set type to Java Web

### ISSUE THREAD

**Issue by frvi** [terraform-providers/terraform-provider-azurerm#1871]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform v0.11.8
* provider.azurerm v1.13.0
* provider.random v2.0.0

### Affected Resource(s)

* azurerm_application_insights

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights" "insights" {
    name = "some-insights"
    location = "westeurope"
    resource_group_name = "resourcegroup"
    application_type = "java"
}
```

### Expected Behavior

Application Insights -> Configure -> Properties
**Type** should be `Java web` (it is if created from dashboard, and select Java as type)

### Actual Behavior

Application Insights -> Configure -> Properties
**Type** is `ASP.NET`

**Comment by sawyerh** [comment]
This also happens when setting `application_type` to `web`

**Comment by tombuildsstuff** [comment]
hi @frvi @sawyerh 

Thanks for opening this issue :)

Taking a look into this this is because the field `application_type` is case insensitive in Terraform whereas the API requires that the casing matches exactly. As a part of the next major version of the AzureRM Provider (2.0) we're planning on making the provider case-sensitive for the fields which are currently case insensitive to match the behaviour of other Terraform Providers - as such this'll be rolled up as a part of this work.

In the interim it should be possible to work around this by using Title Case (e.g. `Web`, `Java`, `Other`). Would you be able to take a look and see if that works for you?

Thanks!
