### ISSUE TITLE
Application Gateway independent resources

### ISSUE THREAD

**Issue by OffColour** [terraform-providers/terraform-provider-azurerm#1893]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

From the Application Gateway, break out probe, http_listener, request_routing_rule and backend_http_setting as separate resources in line with the way the Load Balancer is implemented.
When running a multi site app gateway, these setting are heavily tied into the deployment of websites and would be useful to define away from the App Gateway itself and delegate to a DevOps team.

### New or Affected Resource(s)

* azurerm_ag_healthprobe
* azurerm_ag_backend_http_settings
* azurerm_ag_http_listener
* azurerm_ag_ssl_certificate
* azurerm_ag_request_routing_rule

* #0000

**Comment by tombuildsstuff** [comment]
hi @OffColour 

Thanks for opening this issue :)

This feature request is blocked on the Azure API not supporting it at this time - however it's currently being tracked in #1576 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #1576 - please subscribe to that for updates.

Thanks!
