### ISSUE TITLE
Support a new managed disk type StandardSSD_LRS 

### ISSUE THREAD

**Issue by ira-bryndzei** [terraform-providers/terraform-provider-azurerm#1895]
Hello Terraform Team!
### Description
Azure now supports standard SSD disk disk type which is called StandardSSD_LRS. Could you please add support for StandardSSD_LRS disk type for azurerm_virtual_machine resource.
### New or Affected Resource(s)

* azurerm_virtual_machine 

### Potential Terraform Configuration

```hcl

```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @ira-bryndzei

Thanks for opening this issue :)

Support for the Standard SSD disk type has previously been requested in #1432 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one - would you mind subscribing to that for updates?

Thanks!

**Comment by rifaterdemsahin** [comment]
any updates?
