### ISSUE TITLE
How to add inbound IP filtering to Logic Apps

### ISSUE THREAD

**Issue by alastairtree** [terraform-providers/terraform-provider-azurerm#1924]
Is it possible to create a logic app using terraform with the inbound IP address filter configured? The docs for that in an ARM template are at https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app#setting-ip-ranges-on-the-resource-definition

E.g

![image](https://user-images.githubusercontent.com/6273429/45501599-91cf2e00-b779-11e8-94b3-7816b4bbcdc0.png)

**Comment by tombuildsstuff** [comment]
hi @alastairtree 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look at the link mentioned above it should be possible to achieve this using [the `azurerm_logic_app_trigger_custom` resource](https://www.terraform.io/docs/providers/azurerm/r/logic_app_trigger_custom.html) which allows a custom Trigger to be defined. Using the code [from this example](https://docs.microsoft.com/en-us/azure/logic-apps/logic-apps-securing-a-logic-app#setting-ip-ranges-on-the-resource-definition) I believe the relevant Terraform Configuration should look something like this:

```
resource "azurerm_resource_group" "test" {
  name     = "workflow-resources"
  location = "East US"
}

resource "azurerm_logic_app_workflow" "test" {
  name                = "workflow1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_logic_app_trigger_custom" "test" {
  name         = "example-trigger"
  logic_app_id = "${azurerm_logic_app_workflow.test.id}"

  body = <<BODY
{
    "allowedCallerIpAddresses": [
    {
      "addressRange": "192.168.12.0/23"
    },
    {
      "addressRange": "2001:0db8::/64"
    }
  ]
}
BODY
}
```

Would you be able to take a look and see if this works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by alastairtree** [comment]
@tombuildsstuff sorry for the delay, but this does not work. The error is below

`
autorest/azure: Service returned an error. Status=400 Code="InvalidRequestContent" Message="The request content is not valid and could not be deserialized: 'Could not find member 'allowedCallerIpAddresses' on object of type 'FlowTemplateTrigger'. Path 'properties.definition.triggers.example-trigger.allowedCallerIpAddresses', line 1, position 435.'."
`

My suspicion is that this approach will not work, the accessControl property is on the root workflow object at 
properties.accessControl.triggers.allowedCallerIpAddresses and not on the trigger at properties.definition.triggers.TRIGGER_NAME.allowedCallerIpAddresses.

Think this will need a change to the azurerm_logic_app_workflow resource to support that new property?
