### ISSUE TITLE
Apply updates existing infrastructure, even if it's not in the state.

### ISSUE THREAD

**Issue by craigmonson** [terraform-providers/terraform-provider-azurerm#1946]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

Terraform v0.11.8
+ provider.azurerm v1.15.0

### Affected Resource(s)

_That I know of_

* azurerm_resource_group
* azurerm_public_ip

### Terraform Configuration Files

```hcl
N/A
```

### Debug Output

N/A (Sorry, it's impossible for me to get as I'm not going to duplicate the apply.)

### Panic Output

N/A - Didn't panic

### Expected Behavior

Expecting terraform to error because the infrastructure already exists, and to not move forward until it's imported.

### Actual Behavior

It automatically imported those resources, and applied changes to them (in the form of tags as far as I can tell).

### Steps to Reproduce

1. create a template that has an already existing azurerm_resource_group and do something minor, like add a tag.
2. plan
3. apply
4. Take a look at the resource groups tags, and see it's been altered, note the resource in the state / do a `terraform show`

### References

*

**Comment by tombuildsstuff** [comment]
hi @craigmonson 

Thanks for opening this issue :)

Terraform will set ensure the fields set on any resources match the values set in the state - such that any changes not specified in Terraform (e.g. extra tags) will be removed in favour of the expected configuration.

There's currently a bug in the AzureRM Provider (due to the nature of the Azure API's being Upserts, rather than separate Create/Update methods as in other API's) where resources don't have to exist in the State prior to being used by Terraform (such that Terraform will silently update them). We've got a fix for this coming in #1746 - where Terraform will now require that resources which already exist are imported into the state (via `terraform import`).

Would you be able to take a look and see if importing the resource in the state works for you? Since there's a fix for this coming in #1746 I'm going to close this issue in favour of that one for the moment.

Thanks!
