### ISSUE TITLE
Kubernetes service: Code="NodesNotReady" Message=""

### ISSUE THREAD

**Issue by kvolkovich-sc** [terraform-providers/terraform-provider-azurerm#1969]
Can't create Azure Kubernetes cluster using Terraform.

`"azurerm" (1.14.0)` / `"azurerm" (1.15.0)`

```
Still creating... (50m20s elapsed)
...
Code="NodesNotReady" Message=""
```

All `kube-system` pods are in `pending` state because there are no sufficient nodes to run.

I have tried with different node pool vm sizes and regions. Same results.

Cluster creation using wizard at Azure portal with the same configuration always finishing with success.

Issue started to reproduce about 18 September 2018. Before this date it where work normally with same configuration.

Terraform logs (sensitive data removed):

[tf-apply.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/2407694/tf-apply.log)

There are no any unsuccessfully finished events in `MC_` resource group according to Azure Activity Log.

**Comment by kvolkovich-sc** [comment]
I found a problem. Its not an issue of **terraform-provider-azurerm**.

Its an issue of AKS/ACS.

Details here: https://github.com/Azure/AKS/issues/659

**Comment by tombuildsstuff** [comment]
hey @kvolkovich-sc 

Thanks for opening this issue :)

Taking a look at the output above I'd agree that this is an error on the Azure side - Terraform's polling until it receives a hard-error (as can be seen above). Since this is upstream issue is being tracked in https://github.com/Azure/AKS/issues/659 (and there's a workaround available) - I'm going to close this issue in favour of that one.

Thanks!
