### ISSUE TITLE
Support Auth users on web apps using siteAuthSettings

### ISSUE THREAD

**Issue by szaroubi** [terraform-providers/terraform-provider-azurerm#1992]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Would it be possible to add the support for SiteAuthSettings (if I am not mistaken).
It is the functionality that permits to add `Authentication / Authorization`

Go into a Azure Function (or even an App Service) and client on `Authentication / Authorization`
![image](https://user-images.githubusercontent.com/7586983/46221570-ff6c8400-c34d-11e8-81c5-2f7565147687.png)

Then fill up the form to the side.

![image](https://user-images.githubusercontent.com/7586983/46221832-d1d40a80-c34e-11e8-85ca-bc79236983ac.png)

This functionality doesn't seem to be available in the golang SDK or in this platform.

I would be willing to contribute code if someone guides me.

### New or Affected Resource(s)

* azurerm_app_service
* Maybe more that I am not familiar with

### Potential Terraform Configuration
```hcl
site_config = {
    siteAuthSettings = {
        default = "Google"
        googleClientId = "xyzabc123"
        googleClientSecret = "SomeVerySecretString000"
        googleOAuthScopes = "SomeScope"
    }
}
```

### References

[Documentation of the .NET SDK](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.websites.models.siteauthsettings?view=azure-dotnet)

**Comment by szaroubi** [comment]
Under `$GOPATH$\src\github.com\terraform-providers\terraform-provider-azurerm\vendor\github.com\Azure\azure-sdk-for-go\services\web\mgmt\2018-02-01\web\apps.go`

There seems to be `func (client AppsClient) UpdateAuthSettings`

Is that the method I need to somehow call ?

**Comment by szaroubi** [comment]
@metacpp , I was wondering if there is anything I can do to help move this along.
I am willing to write code, tests, documentation, let me know and thank you again for your help.

**Comment by tombuildsstuff** [comment]
hey @szaroubi 

Apologies for the delayed reply here!

This isn't on our short-term roadmap of things we're planning on implementing but we'd happily accept a community PR for this in the interim.

As you've discovered in the comment above - there's an `UpdateAuthSettings` method which looks like a good candidate for this, presumably there's a GetAuthSettings method to read that back too? It's worth noting that the `secret` values in the response (e.g. the Client Secrets) may not necessarily be returned from the API (since we set these values into the state to allow us to diff them).

With regards to building support for this, this should need the following doing:

- add the new fields to the schema ([example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L136-L164))
- parse those fields out in an expand function here ([example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L379)) - in this case since this is a separate method it'd be good to call this after `d.SetID` [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L435)
- read the values back from Azure ([example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L461-L464)) and then persist them into the state ([example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster.go#L478-L481))
- [add an acceptance test for this](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster_test.go#L72-L99) which spins up a Terraform configuration as shown [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_kubernetes_cluster_test.go#L357)
- add these new fields to the docs ([which can be found here](https://github.com/terraform-providers/terraform-provider-azurerm/blame/master/website/docs/r/kubernetes_cluster.html.markdown#L209))

Hope that helps - please let us know if we can be of any help here :)

Thanks!

**Comment by szaroubi** [comment]
@tombuildsstuff , this seems a bit more complicated than my previous commit.
I will start with the instructions that you have provided (they seem clear for now).
But I might need some hand holding, is there a direct channel or something more responsive than comments on this ticket that can use to get answers when I throw my hands onto this problem ?

Thank you again and looking forward in committing soon.

**Comment by joakimhew** [comment]
I'm considering contributing on this issue unless you've already come a long way @szaroubi ?
