### ISSUE TITLE
Feature Request: Management Groups

### ISSUE THREAD

**Issue by istairbn** [terraform-providers/terraform-provider-azurerm#1999]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

One of the recent releases at Microsoft Ignite was Management Groups: the concept of hierarchically applying policies to all subscriptions. 

See here: https://docs.microsoft.com/en-us/azure/governance/management-groups/index

Since most of our management is controlled through Terraform and we would like to keep our policy "as code" - this would be useful to add to the ARM provider. 
Given that groups can nest in a parent/child relationship but subscriptions inherit once, it might make sense to the split the entity and relationship. 

### New or Affected Resource(s)

* azurerm_management_group: would create a membership group.
 - Name (required) - Name of group
 - Parent (Optional) - Group under which it's nested. Empty means top level. 

* azurerm_management_group_member: would add a subscription to a group
 - Subscription_Id (Required) -  ID of the subscription being assigned
 - Management_Group (Required) - Name of Management Group to add

### Potential Terraform Configuration
```hcl

resource "azurerm_management_group" "parent" {
  name = "test"
}

resource "azurerm_management_group" "child" {
  name  = "test2"
  parent = "test"
}

resource "azurerm_management_group_member" "nested" {
  subscription_id = "00000-00000-00000-00000"
  name                = "test2"
}

```

**Comment by tombuildsstuff** [comment]
hi @istairbn 

Thanks for opening this issue :)

Support for both creating Management Groups and assigning Subscriptions to a Management Group is already available in Terraform - and can be found in [the `azurerm_management_group ` resource](https://www.terraform.io/docs/providers/azurerm/r/management_group.html), which shipped [in v1.14 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1140-september-06-2018) - would you be able to take a look and see if this works for you?

Since this is a question about a resource rather than an issue in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!
