### ISSUE TITLE
Cannot scale an HDInsight cluster with azurerm_template_deployment

### ISSUE THREAD

**Issue by iszekely** [terraform-providers/terraform-provider-azurerm#2030]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

* Terraform v0.11.8
* provider.azurerm v1.16.0
* provider.null v1.0.0

### Affected Resource(s)

* azurerm_template_deployment

### Terraform Configuration Files

https://www.dropbox.com/s/5vyj5pp0dw2hqhy/hditest.zip?dl=0

### Expected Behavior

After changing the cluster worker node count parameter, the HDInsight cluster should scale up or down accordingly.

### Actual Behavior

The apply runs without error but nothing happens in the cluster. Neither the Azure Portal nor the Ambari show any ongoing change.

```
azurerm_template_deployment.hdinsight_template: Still modifying... (ID: /subscriptions/********-****-****-****-...Microsoft.Resources/deployments/hditst, 1m0s elapsed)
azurerm_template_deployment.hdinsight_template: Modifications complete after 1m1s (ID: /subscriptions/********-****-****-****-...Microsoft.Resources/deployments/hditst)

Apply complete! Resources: 0 added, 1 changed, 0 destroyed.
```

### Steps to Reproduce

1. Fill in the missing variables in env.tfvars (subscription id, tenant id, your company public IP)
1. `terraform apply`
1. Modify `hdinsight_cluster_worker_node_count` in `env.tfvars`
1. `terraform apply`

### References

Might be related to this. It could be the parse error that causes Terraform to see a change in the state.

* #2029

**Comment by tombuildsstuff** [comment]
hi @iszekely 

Thanks for opening this issue - apologies for the delayed response here!

I had a conversation with somebody at HashiConf about this who reached out to Microsoft about this - and it appears this is actually a limitation of the ARM Template Deployment API (which internally calls the HDInsights API, which only allows for scaling the cluster via the `scale` endpoint - as opposed to just updating the count via redeploying the template).

Since this is an issue specific to deploying HDInsight via an ARM Template (which is also broken when trying to scale an HDInsight Cluster outside of Terraform e.g. using the Azure CLI) - I'm not sure there's much we can do to work around this, unfortunately. I'd [suggest opening an issue about this on the ARM Templates repository](https://github.com/Azure/azure-quickstart-templates) - however I believe the best approach to solving this would be to support the HDInsight resource natively in Terraform. There's an issue tracking support for this in #37 - and we've spent some time looking into this previously in the form of #1267 - but I believe we may need to change our approach there to have a Terraform resource for each type of cluster (e.g. Hadoop etc) so the validation can be more useful (as unfortunately the API is very generic).

All that to say - unfortunately I don't believe this is something we can fix in Terraform and as such I'm going to close this issue for the moment - ultimately I believe #37 (which requests native support for the HDInsight resources) will provide a solution for this issue, but I'm unable to give a timeframe for that at this time.

Thanks!

**Comment by iszekely** [comment]
Hi @tombuildsstuff 

Thank you for your answer. I've seen the linked issues (even voted on it) but those had been open for a long time, therefore we had to go for the ARM template deployment. It would be great if the implementation was released.

Best regards.
