### ISSUE TITLE
Unknown Tenant Id, not able to go through terraform plan

### ISSUE THREAD

**Issue by tappoz** [terraform-providers/terraform-provider-azurerm#2031]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

- Terraform v0.11.8
- provider.azurerm v1.16.0
- azure-cli 2.0.46
- Debian GNU/Linux 9.5 (stretch)

### Affected Resource(s)

* azurerm_resource_group

### Terraform Configuration Files

```hcl
provider "azurerm" {
  subscription_id = "<GUID>"
  tentant_id      = "<GUID>"
  client_id       = "<GUID>"
  client_secret   = "<GUID>"
}

resource "azurerm_resource_group" "resource_gp" {
  name = "TfDemoRg"
  location = "westeurope"

  tags {
    Owner = "FOO"
  }
}
```

### Expected Behavior

Being able to create a resource group

### Actual Behavior

Seeing an error message on the command line saying: `Error: provider.azurerm: : invalid or unknown key: tentant_id`.

### Steps to Reproduce

1. `az ad sp create-for-rbac -n "FooApp" --role="Contributor" --scope="/subscriptions/<MY_SUBSCRIPTION_ID>"`
2. Copy paste the GUIDs in the output inside the script
    - the JSON `appId` becomes tf azurerm `client_id`
    - the JSON `password` becomes tf azurerm `client_secret`
    - the JSON `tenant` becomes tf azurerm `tenant_id`
    - I've also added the Subscription ID as the tf azurerm `subscription_id`
3. `terraform init`
4. `terraform plan`

These commands don't show any error message:

- `az account set --subscription="SUBSCRIPTION_ID"`
- `az login --service-principal -u CLIENT_ID -p CLIENT_SECRET --tenant TENANT_ID`

**Comment by tombuildsstuff** [comment]
hey @tappoz 

Thanks for opening this issue :)

Taking a look at the Provider block specified above:

```
provider "azurerm" {
  subscription_id = "<GUID>"
  tentant_id      = "<GUID>"
  client_id       = "<GUID>"
  client_secret   = "<GUID>"
}
```

The field `tentant_id` in the block has a typo (it should be `tenant_id`) - which is why you're seeing the following error:

> Seeing an error message on the command line saying: Error: provider.azurerm: : invalid or unknown key: tentant_id.

Would you be able to update the Provider block to specify `tenant_id` instead of `tentant_id ` and see if this works for you? One thing of note - if you're using a Service Principal you may wish to specify these values as Environment Variables ([details of which can be found here](https://www.terraform.io/docs/providers/azurerm/index.html#argument-reference)) rather than in-line (so for example it's less likely these could be accidently checked into source control).

Since this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by tappoz** [comment]
@tombuildsstuff thanks for the details :) yes, that typo now makes me feel ashamed, I am a bit new to this terraform syntax and I did not realize this was some sort of "compilation error", anyway thanks again for the support.
