### ISSUE TITLE
New Resource: Management Groups

### ISSUE THREAD

**Issue by lawrenae** [terraform-providers/terraform-provider-azurerm#2036]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I did not see anything in the issues list for this enhancement already - apologies if I missed it.

I'd like to build and manage management groups (and consequently the subscriptions underneath them) via terraform (https://docs.microsoft.com/en-us/azure/governance/management-groups/index)

### New or Affected Resource(s)

I imagine something like this, but am easily convinced of otherwise:

```hcl
resource "azurerm_management_group" "group1" {
    name = "foo"

    #optional
    parent_management_group = "bar" 
}

resource "azurerm_role_assignment" "test" {
  scope                = "${azurerm_management_group.group1.id}"
  role_definition_name = "Reader"
  principal_id         = "${data.azurerm_client_config.test.service_principal_object_id}"
}

resource "azurerm_subscription" "subscription1" {
    # other subscription details
  
    # optional
    parent_management_group = "${azurerm_management_group.group1.id}"
}

```

### References

* https://docs.microsoft.com/en-us/azure/governance/management-groups/index
* https://github.com/Azure/azure-rest-api-specs/blob/master/specification/managementgroups/resource-manager/Microsoft.Management/preview/2018-03-01-preview/examples/PutManagementGroup.json

**Comment by tombuildsstuff** [comment]
hi @lawrenae 

Thanks for opening this issue :)

Management Groups are already supported by the AzureRM Provider and can be found [in the `azurerm_management_group` resource](https://www.terraform.io/docs/providers/azurerm/r/management_group.html) - which can be used like so:

```hcl
resource "azurerm_management_group" "test" {
  display_name = "My Group"
}
```

.. or optionally by specifying the Subscription ID's which should be contained within this Management Group like so:

```hcl
data "azurerm_subscription" "current" {}

resource "azurerm_management_group" "test" {
  display_name = "My Group"
  subscription_ids = [
    "${data.azurerm_subscription.current.id}"
  ]
}
```

Would you be able to take a look and see if that works for you? Since support for Management Groups is already available I'm going to close this issue for the moment, but we'll continue responding 😄

Thanks!

**Comment by lawrenae** [comment]
thanks @tombuildsstuff. I dont know how I missed this. Thanks for the pointer. :)
