### ISSUE TITLE
public_ip_address_id does for load balancer does not accept empty value anymore 

### ISSUE THREAD

**Issue by bsenellart** [terraform-providers/terraform-provider-azurerm#21368]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Version

1.14

### AzureRM Provider Version

3.50.0

### Affected Resource(s)/Data Source(s)

azurerm_lb

### Terraform Configuration Files

```hcl
resource "azurerm_lb" "azlb" {
  name                = coalesce(var.lb_name, var.defaults.lb_name)
  location            = var.location
  resource_group_name = var.rg_name
  sku                 = var.lb_sku
  tags                = var.tags

  frontend_ip_configuration {
    name                          = var.frontend_name
    public_ip_address_id          = var.public_lb ? join("", azurerm_public_ip.azlb.*.id) : ""
    subnet_id                     = var.frontend_subnet_id
    private_ip_address            = var.frontend_private_ip_address
    private_ip_address_allocation = var.frontend_private_ip_address_allocation
  }
}
```

### Debug Output/Panic Output

```shell
Error: parsing Azure ID: parse "": empty url
Experimental features are subject to breaking changes in future minor or patch
releases, based on feedback.
If you have feedback on the design of this feature, please open a GitHub issue
to discuss it.
  on .terraform/azurerm-load-balancer/20-main.tf line 29, in resource "azurerm_lb" "azlb":
  29:     public_ip_address_id          = var.public_lb ? join("", azurerm_public_ip.azlb.*.id) : ""
```

### Expected Behaviour

The `public_ip_address_id ` should accept empty value such as `public_ip_address_id = ""`

### Actual Behaviour

The `public_ip_address_id ` used to accept empty value when
Since the update to version 3.50.0 it retrun an error 

### Steps to Reproduce

deploy an private azure lb with an empty `public_ip_address_id`

**Comment by tombuildsstuff** [comment]
hi @bsenellart 

Thanks for opening this issue.

Taking a look through here, whilst it was previously possible to specify an empty value for this field instead of `null` - this was actually a bug (insofar as the value `null` should be being specified instead of an empty string) and was fixes in #21129.

Whilst earlier versions of the Provider may have supported this configuration unintentionally, this was unsupported - when specifying a field in Terraform that should be conditionally ignored, the value should be set to `null` rather than an empty string, which means that this can be fixed by updating the Terraform Configuration being specified as so:

>     public_ip_address_id          = var.public_lb ? join("", azurerm_public_ip.azlb.*.id) : null

However since an empty string shouldn't have been a supported value for this field, and this bug has been fixed - whilst I'd like to thank you for reaching out I'm going to close this issue for the moment, but as mentioned above you can fix this by specifying `null` instead of an empty string (which also works in earlier version of the Provider).

Thanks!

**Comment by tombuildsstuff** [comment]
@Sang317 indeed, you can either omit the field or set it to `null` (in a conditional) to not set a value for that field - an empty string is not (and shouldn't have previously been) a supported value.

**Comment by Sang317** [comment]
@tombuildsstuff  
worked 
thank you .
