### ISSUE TITLE
Support for API management version 2022-08-01

### ISSUE THREAD

**Issue by xaviergxf** [terraform-providers/terraform-provider-azurerm#21543]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Community Note

* Please vote on this issue by adding a :thumbsup: [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure API management will deprecate versions prior to 2021-08-01 in 09.2023 [https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023](https://learn.microsoft.com/en-us/azure/api-management/breaking-changes/api-version-retirement-sep-2023). 

The following underlying issue is opened [https://github.com/Azure/azure-sdk-for-go/issues/20701](https://github.com/Azure/azure-sdk-for-go/issues/20701)

### New or Affected Resource(s)/Data Source(s)

azurerm_api_management

**Comment by tombuildsstuff** [comment]
hey @xaviergxf 

Thanks for opening this issue.

At this point in time we're actually moving off of the "Track1" `Azure/azure-sdk-for-go` in favour of `hashicorp/go-azure-sdk` - as such whilst I'd like to thank you for being proactive in opening an issue on the Azure SDK repository - at this point in time their focus is on the "Track2" SDK which unfortunately we're not planning to adopt.

Instead support for this would need to be added to `hashicorp/go-azure-sdk` - at this point in time that supports [API Version `2021-08-01`](https://github.com/hashicorp/go-azure-sdk/tree/main/resource-manager/apimanagement/2021-08-01), however [support for `2022-08-01` is blocked on this issue, which comes down to a data issue within the Swagger itself](https://github.com/hashicorp/pandora/issues/2236).

As such in the interim we should be able to use API Version `2021-08-01` here (for which some components of this Service have already been switched across) which'll fix the immediate issue - and then when `2022-08-01` becomes available we can look to update to that version of the API instead.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @xaviergxf 

Taking another look into this one, it appears that we're already exclusively using API Version `2021-08-01` and this deprecation only affects API versions older than that:

```
 $ cd github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2021-08-01/apimanagement
 $ grep -h -R "APIVersion = " | sort | uniq
	const APIVersion = "2021-08-01"
```

As such I don't believe there's anything else needed from our side for this one at the moment. These changes have been shipping in the Provider for a while now, so if you're using the latest version of the Provider then you'll be making use of this API Version.

As mentioned above we're in the process of migrating from `Azure/azure-sdk-for-go` to `hashicorp/go-azure-sdk` - I've just taken a look into https://github.com/hashicorp/pandora/issues/2236 and it appears the blocking issue has since been resolved, so I'll import support for the next API Version (`2022-08-01`) now and then we can look to migrate to that version too.

However since I believe all the changes needed for this one have shipped, I'm going to close this issue for the moment.

Thanks!
