### ISSUE TITLE
Resource Subnet_network_security_group_association will not stay associated

### ISSUE THREAD

**Issue by whytoe** [terraform-providers/terraform-provider-azurerm#2178]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform v0.11.10
+ provider.azurerm v1.17.0

### Affected Resource(s)

* azurerm_subnet_network_security_group_association

### Terraform Configuration Files

```
module "data_nsg_link" {
  source = "git::ssh://mystuff@mydomain.com"
  subnet_id = "${module.data_subnet.subnet_id}"
  nsg_id = "${module.data_nsg.nsg_id}"
}
```

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

No Change to resources

### Actual Behavior

```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ module.app_subnet.azurerm_subnet.subnet
      network_security_group_id: "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Network/networkSecurityGroups/nsg01" => ""

  ~ module.data_subnet.azurerm_subnet.subnet
      network_security_group_id: "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Network/networkSecurityGroups/nsg02" => ""

  ~ module.gtwy_subnet.azurerm_subnet.subnet
      network_security_group_id: "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Network/networkSecurityGroups/nsg03" => ""

  ~ module.pres_subnet.azurerm_subnet.subnet
      network_security_group_id: "/subscriptions/mysub/resourceGroups/myrg/providers/Microsoft.Network/networkSecurityGroups/nsg04" => ""


Plan: 0 to add, 4 to change, 0 to destroy.

```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @whytoe 

Thanks for opening this issue :)

As [mentioned in the documentation](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html) since this field currently exists both on the `azurerm_subnet` resource and the `azurerm_subnet_network_security_group_association` resource - at this time this field must be specified in both places to ensure it remains associated.

Whilst I appreciate this isn't ideal, the alternative would be a breaking change to the `azurerm_subnet` resource - which is planned for v2.0.0 of the AzureRM Provider (which we're planning at the moment) which will include removing the `network_security_group_id` field from the `azurerm_subnet` resource.

Since this is currently by design (and has a planned fix in the near future) - I'm going to close this issue for the moment.

Thanks!

**Comment by whytoe** [comment]
Thanks @tombuildsstuff I must have missed that documentation
