### ISSUE TITLE
Feature Request: Set azurerm_iothub shared access policies

### ISSUE THREAD

**Issue by polarking** [terraform-providers/terraform-provider-azurerm#2201]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Hey!
It would be great to be able to set shared access policies for IoT Hubs.

### New or Affected Resource(s)

* azurerm_iothub

### Potential Terraform Configuration
This could potentially be configured like so:

```hcl
resource "azurerm_iothub_shared_access_policy" "sap" {
  name            = "sap"
  iothub_id       = "${azurerm_iothub.iothub.id}"
  registry_read   = true
  registry_write  = true
  service_connect = true
  device_connect  = true
}

```

**Comment by tombuildsstuff** [comment]
hi @polarking 

Thanks for opening this issue :)

Taking a quick look into this I don't believe support for this is available in [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) - would you mind opening a feature request on that repository for this to be added to the SDK, so that we could look to implement support for this?

Thanks!

**Comment by polarking** [comment]
Thanks @tombuildsstuff 
I've setup a feature request in the SDK repo: https://github.com/Azure/azure-sdk-for-go/issues/3200
