### ISSUE TITLE
Azure Scale Set - Cannot retrieve VM private ip's via resource

### ISSUE THREAD

**Issue by guitarrapc** [terraform-providers/terraform-provider-azurerm#2211]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm wondering how can I retrieve scale set VM's private IP address with Terraform-provider-azurerm. I think there are no resources nor data resources directly return VM IP's.

### New or Affected Resource(s)

* azurerm_virtual_machine_scale_set

### Potential Terraform Configuration

I think it better return backend vm ips from existing azurerm_virtual_machine_scale_set resource.

```hcl
resource "azurerm_virtual_machine_scale_set" "test" {
  name                = "test"
  location            = "eastus"
  resource_group_name = "${data.azurerm_resource_group.current.name}"
  upgrade_policy_mode = "Manual"
  priority            = "Regular"

  sku {
    name     = "${local.vmsize}"
    tier     = "Standard"
    capacity = "${local.capacity}"
  }
  storage_profile_image_reference {
    id = "${data.azurerm_image.manage.id}"
  }
  storage_profile_os_disk {
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Premium_LRS"
  }
  os_profile {
    computer_name_prefix = "test"
    admin_username       = "username_you_like"
    admin_password       = "xxxxxxxxxxxxxxxxx"
  }
  os_profile_linux_config {
    disable_password_authentication = true

    ssh_keys {
      path     = "/home/username_you_like/.ssh/authorized_keys"
      key_data = "${file("${local.ssh_pub_key}")}"
    }
  }
  network_profile {
    name    = "terraformnetworkprofile"
    primary = true

    ip_configuration {
      name                                   = "IPConfiguration"
      subnet_id                              = "${azurerm_subnet.default.id}"
      load_balancer_backend_address_pool_ids = ["${azurerm_lb_backend_address_pool.bpepool.id}"]
    }
  }
  boot_diagnostics {
    enabled     = true
    storage_uri = "${azurerm_storage_account.test.primary_blob_endpoint}"
  }
}
```

### References

There seems no community resolution.

> https://stackoverflow.com/questions/53087114/how-can-i-retrieve-azure-scale-sets-vm-private-ip-addresses-via-terraform/53098032#53098032

**Comment by tombuildsstuff** [comment]
hi @guitarrapc 

Thanks for opening this issue :)

Unfortunately retrieving the Private IP Addresses of instances within a VM Scale Set isn't supported by Terraform at this time - this is due to the fact that these values are likely to change between Terraform runs (for instance where instances within a VM Scale Set may be replaced by other instances) - and as such this could lead to a broken Terraform Configuration during a run.

That said - it should be possible to retrieve this information using the Azure CLI and then access this information from within Terraform using the External Data Source. Given this isn't something that we plan to support in the AzureRM Provider at this time I'm going to close this issue for the moment.

Thanks!

**Comment by guitarrapc** [comment]
Thanks @tombuildsstuff , I agree with your decision and I do use az cli and call back in terraform to retrieve ips. Many thanks!
