### ISSUE TITLE
terraform import Error - azurerm_databricks_workspace 

### ISSUE THREAD

**Issue by andyt530** [terraform-providers/terraform-provider-azurerm#2225]
Hi

Terraform v0.11.10
provider.azurerm: version = "~> 1.18"

Using terraform import on a databricks workspace I get a validation error about the minimum length of the workspace name that looks incorrect:

# File auto generate by az2tf see https://github.com/andyt530/az2tf
resource "azurerm_databricks_workspace" "rg-databrick__eda" {
	 **name = "eda"**
	 resource_group_name = "rg-databrick"
	 location = "westeurope"
	 sku = "Standard"
}

azurerm_databricks_workspace.rg-databrick__eda: Importing from ID "/subscriptions/mysubid/resourceGroups/rg-databrick/providers/Microsoft.Resources/deployments/Microsoft.Databricks"...
azurerm_databricks_workspace.rg-databrick__eda: Import complete!
  Imported azurerm_databricks_workspace (ID: /subscriptions/mysubid/resourceGroups/rg-databrick/providers/Microsoft.Resources/deployments/Microsoft.Databricks)
azurerm_databricks_workspace.rg-databrick__eda: Refreshing state... (ID: /subscriptions/mysubid-...urces/deployments/Microsoft.Databricks)

Error: azurerm_databricks_workspace.rg-databrick__eda (import id: /subscriptions/mysubidresourceGroups/rg-databrick/providers/Microsoft.Resources/deployments/Microsoft.Databricks): 1 error(s) occurred:

* import azurerm_databricks_workspace.rg-databrick__eda result: /subscriptions/mysubid/resourceGroups/rg-databrick/providers/Microsoft.Resources/deployments/Microsoft.Databricks: azurerm_databricks_workspace.rg-databrick__eda: Error making Read request on Azure Databricks Workspace : databricks.WorkspacesClient#Get: Invalid input: **autorest/validation: validation failed: parameter=workspaceName constraint=MinLength **value=""** details: value length must be greater than or equal to 3**

Also - as previously reported in issue 2214 - there seems to be an inconsistency with the sku names - resources.azure.com - reports the sku as "standard" lowercase
.....
      "value": "standard"
...... 

- but Terraform seems to want "Standard" - uppercase S

**Comment by tombuildsstuff** [comment]
hi @andyt530 

Thanks for opening this issue :)

Taking a look into this, the ID being provided for importing the DataBricks Workspace is incorrect (from above it's using `/subscriptions/mysubid/resourceGroups/rg-databrick/providers/Microsoft.Resources/deployments/Microsoft.Databricks` rather than the format `/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Databricks/workspaces/{workspaceName}`) - as such I'm wondering if this may be a bug in az2tf? Would you be able to take a look and see if using an ID with this format works for you?

Since this is a question rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄).

Thanks!
