### ISSUE TITLE
InvalidApiVersionParameter - azurerm_managed_disk

### ISSUE THREAD

**Issue by kenlukas** [terraform-providers/terraform-provider-azurerm#223]
### Terraform Version
Terraform v0.10.0

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_managed_disk

### Debug Output
* module.vnet.azurerm_managed_disk.jump_server_disk: 1 error(s) occurred:

* azurerm_managed_disk.jump_server_disk: disk.DisksClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2016-04-30-preview' is invalid. The supported versions are '2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

### Expected Behavior
Disk should have been created

### Actual Behavior
Failure with Status code 400 - InvalidApiVersionParameter

### Steps to Reproduce
1. `terraform apply`

### Important Factoids
Here's the code snippet that's failing
```
resource "azurerm_managed_disk" "jump_server_disk" {
  name                 = "jump_server_storage"
  location             = "${var.location}"
  resource_group_name  = "${azurerm_resource_group.default.id}"
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "20"
}
```

### References
This appears to be similar to the following:
- https://github.com/terraform-providers/terraform-provider-azurerm/issues/192

**Comment by tombuildsstuff** [comment]
Hey @kenlukas 

Thanks for opening this issue :)

So that we can take a look into this - would it be possible to know which Azure region you saw this error in? In addition, are there any specific configurations about the account you're using? (For instance: is the user you're using restricted in any way / what permissions does it have on the Subscription?)

Thanks!

**Comment by kenlukas** [comment]
Hi @tombuildsstuff 
The region is 'East US'
I'm using a Service Principal that has the out of the box 'Contributor' role.

As an fyi, the os disk gets created without issue by the azurerm_virtual_machine resource.

Thanks!

**Comment by tombuildsstuff** [comment]
@kenlukas awesome, thanks!

So I've been able to reproduce this - the issue is in the Terraform configuration posted above, the Resource Group Name is actually it's ID (not a name), which causes an error at Azure's end.

For instance, here's a full config:

```
resource "azurerm_resource_group" "test" {
  name = "tharvey-dev"
  location = "eastus"
}

resource "azurerm_managed_disk" "jump_server_disk" {
  name                 = "jump_server_storage"
  location             = "${azurerm_resource_group.test.location}"
  resource_group_name  = "${azurerm_resource_group.test.id}"
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "20"
}
```

which returns the error you're seeing:
```
disk.DisksClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2016-04-30-preview' is invalid. The supported versions are '2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."
```

When updating the `resource_group_name` from the `name` to the `id` this works as expected:
```
resource "azurerm_resource_group" "test" {
  name = "tharvey-dev"
  location = "eastus"
}

resource "azurerm_managed_disk" "jump_server_disk" {
  name                 = "jump_server_storage"
  location             = "${azurerm_resource_group.test.location}"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  storage_account_type = "Standard_LRS"
  create_option        = "Empty"
  disk_size_gb         = "20"
}
```

Would it be possible for you to try updating your config? We should _probably_ be catching this as part of the validation (and I'll open a separate issue for that) - but this should solve the issue :)

Thanks!

**Comment by kenlukas** [comment]
Hi @tombuildsstuff ,

That worked.  Thanks for your help.

-Ken
