### ISSUE TITLE
Support private cluster option for kubernetes clusters

### ISSUE THREAD

**Issue by benjamingorman** [terraform-providers/terraform-provider-azurerm#2241]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This PR (https://github.com/Azure/acs-engine/pull/2326) recently added the support for provisioning 'private' kubernetes clusters (i.e. without a public IP address). It would be nice if `terraform-provider-azurem` supported this option so that private clusters could be provisioned using terraform.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
resource "azurerm_kubernetes_cluster" "cluster" {
  enable_private_cluster = true
  ...
}
```

### References

* #0000

**Comment by anvarich** [comment]
you messed with ACS and AKS, AKS doesn't provide this feature by it nature of AKS is PaaS. acs-engine which you mentioned is just azurerm templating engine (it generate 4r lines of json from one small json which you feed to them).

**Comment by tombuildsstuff** [comment]
hi @benjamingorman 

Thanks for opening this issue :)

AKS is built on AKS Engine (which was/is originally ACS Engine) - so these changes are /technically/ available to be provisioned, but at this point [aren't available in the Azure API](https://docs.microsoft.com/en-us/rest/api/aks/managedclusters/createorupdate) so we're unable to add support for this functionality.

As @anvarich has mentioned since this is a feature specific to AKS/ACS Engine - it'd need to be added to the Resource Manager API in order for Terraform to support this; as such [I'd recommend opening an issue on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs/issues) if you'd like to see support for this, so that the AKS Team could investigate supporting this functionality within AKS. However since this isn't something we're currently able to support within Terraform (as there's no support in the API/SDK for it) - I'm going to close this issue for the moment.

Thanks!
