### ISSUE TITLE
LinuxConfiguration Support in Compute Resource Provider

### ISSUE THREAD

**Issue by danielsollondon** [terraform-providers/terraform-provider-azurerm#2264]
In the CRP API version 2018-06-01 we added support for :
  "linuxConfiguration": {
    "provisionVMAgent": false
  }
 
This is not available in azurerm_virtual_machine in os_profile_linux_config.

Can you advise when this can be made available?

Thanks,

**Comment by danielsollondon** [comment]
what is the rough ETA for 2.0.0?

**Comment by tombuildsstuff** [comment]
@danielsollondon we're still trying to scope it to determine roughly what should be in 2.0 - so there's timeline at this point - but a rough gues-timate would be early next year.

Whilst it'd be possible for someone to include this in the `azurerm_virtual_machine` resource before then (and we're happy to accept a PR for this in the interim, it'd need to include a state migration but we can assist/guide this) - we're looking at splitting the VM and VMSS resources into 2 resources for each (a Linux/Windows VM and a Linux/Windows VMSS resource). As such I believe 2.0 would be the best time to add support for this new field since we'll be reevaluating these resources anyway.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @danielsollondon 

Apologies for the delayed update here!

Over the past few months we've been working on the functionality coming in version 2.0 of the Azure Provider (outlined in #2807). We've just released version 1.43 of the Azure Provider which allows you to opt-in to the Beta of these upcoming features, including the new `azurerm_linux_virtual_machine` resource which supports configuring `provision_vm_agent`.

Unfortunately there's no plans to backport this to the existing `azurerm_virtual_machine` resource - however the new `azurerm_linux_virtual_machine` resource will go GA in version 2.0 of the Azure Provider in the coming weeks.

Since this functionality is available in [the new `azurerm_linux_virtual_machine` resource](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) (which can be used [by opting into the beta](https://www.terraform.io/docs/providers/azurerm/guides/2.0-beta.html)) I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
