### ISSUE TITLE
No change on plan/apply when changing from x to 0 routes in azurerm_route_table

### ISSUE THREAD

**Issue by ewierschke** [terraform-providers/terraform-provider-azurerm#2272]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.7
+ provider.azurerm v1.18.0

### Affected Resource(s)

* azurerm_route_table

### Terraform Configuration Files

```hcl
resource "azurerm_route_table" "test" {
  name                = "${var.subnet1_name}-routetable"
  location            = "${data.azurerm_resource_group.test.location}"
  resource_group_name = "${data.azurerm_resource_group.test.name}"

  # route {
    # name                   = "example"
    # address_prefix         = "10.100.0.0/14"
    # next_hop_type          = "VirtualAppliance"
    # next_hop_in_ip_address = "10.10.1.1"
  # }
}
```

### Expected Behavior

When removing the last route within a route table, the azurerm_route_table resource should remain but the route should be removed from the route table.

### Actual Behavior

When removing the last route from code, the route table resource does not change, and route cannot be removed using a simple apply.

### Steps to Reproduce

1. `terraform apply`

### References

*https://github.com/terraform-providers/terraform-provider-azurerm/issues/39

**Comment by tombuildsstuff** [comment]
hi @ewierschke 

Thanks for opening this issue :)

Taking a look into this, in this case the sub-block `route` is Optional+Computed - which means that it's configured in such a way that it'll allow it to be configured outside of this resource (for example, using the `azurerm_route` resource) - such that commenting this block out as-is will mean Terraform ignores the value of this field (as you're seeing). It's possible to specify that you'd like there to be no routes for this Route Table by specifying an empty list (as shown below) - would you be able to take a look and see if that works for you?

```
resource "azurerm_route_table" "test" {
  name                = "${var.subnet1_name}-routetable"
  location            = "${data.azurerm_resource_group.test.location}"
  resource_group_name = "${data.azurerm_resource_group.test.name}"
  route               = []
}
```

Since this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (however we'll continue responding 😄)

Thanks!

**Comment by ewierschke** [comment]
Thanks for the quick reply.  The empty list approach you provided works great.
