### ISSUE TITLE
provision_vm_agent behavior regression.

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#2277]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.10
+ provider.azurerm v1.17.0
```

### Affected Resource(s)

* azurerm_virtual_machine

### Important Factoids

The default in all Azure-provided deployment methods (portal, cli, powershell) deploy Windows VM with the VM Agent enabled.

This commit from @tombuildsstuff seems to have been lost only a few days later and did not make the migration to this repo:
https://github.com/hashicorp/terraform/issues/9995

April 21, 2017: 
https://github.com/hashicorp/terraform/blob/e453f3c05a6b7fb8e25df378ee8827fca2d5ee24/builtin/providers/azurerm/resource_arm_virtual_machine.go#L354-L358

April 25, 2017:
https://github.com/hashicorp/terraform/blob/5121995100e3d87561f978c3aed0199bf705da95/builtin/providers/azurerm/resource_arm_virtual_machine.go#L356-L359

All of @tombuildsstuff commits that day seem to have been removed and didn't make it in the migration.

Then, after moving to this repo, a new issue then did not identify this or chose to just document the departure from official deployment defaults.
#28 

Maybe we should reopen #28 to work on a change to the defaults?

Also, osProfile changes cause a failure in apply because these setting cannot be changed. But there are use cases where users don't care about currently deployed vm changes, I wonder if there would be interest in ignoring these and not failing.

**Comment by tombuildsstuff** [comment]
hi @mbrancato 

Thanks for opening this issue :)

> All of @tombuildsstuff commits that day seem to have been removed and didn't make it in the migration.
> Then, after moving to this repo, a new issue then did not identify this or chose to just document the departure from official deployment defaults.

Prior to the AzureRM Provider being split out it was part of the Terraform Core repository - as a part of this split out we migrated over all issues for each Provider into the Providers repo (so that we could keep better track of them). Regarding the code migration - we took the Provider code at the last point release of 0.9.x and migrated this over to the new repositories - and re-released these as `v0.1.0`.

[Taking a look at the code for v0.9.11](https://github.com/hashicorp/terraform/blob/v0.9.11/builtin/providers/azurerm/resource_arm_virtual_machine.go#L357-L360) - this default was set to `false` (since that's the default value for a bool) - as such I believe this was transferred over correctly.

In the original issue (https://github.com/hashicorp/terraform/issues/9995) / the new issue #28 - we were investigating flipping this default value from `false` to `true`. After [prototyping this in the form of this commit](https://github.com/hashicorp/terraform/blob/e453f3c05a6b7fb8e25df378ee8827fca2d5ee24/builtin/providers/azurerm/resource_arm_virtual_machine.go#L354-L358) we decided that whilst this'd bring the default into line with the Azure deployment options - ultimately this was the wrong approach since it'd involve a breaking configuration change to existing Virtual Machines. It's also worth noting the default values change from time-to-time in Azure (as in this case) - such that providing the defaults are documented ([as in this case](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#provision_vm_agent)) - it should be possible for users to decide for themselves.

> Maybe we should reopen #28 to work on a change to the defaults?

In this particular case I don't believe this'd be the right approach, since it'd break existing Terraform Configurations - instead we're thinking about replacing the `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources with two new resources for each (a Linux/Windows VM/VMSS resource) which'd allow us to fix a bunch of minor issues where the API behaviour has diverged from when it first launched (for example, it's now possible to update customData, whereas before it wasn't, so the resource is designed around this).

Whilst I appreciate changing this prior to these new resources could help some users migrating over from ARM Templates (or CLI/similar) - I believe it's better to make this breaking change in the form of these new resources instead (which means users have a migration path). This is being planned for the 2.0 release - and we'll be providing more information about this in the near future; but since this is a question (rather than a bug in Terraform) I'm going to close this issue for the moment. Once we've prototyped how these new resources should work a little further - we'll be opening a new issue for this work (which we'll link to here).

Thanks!
