### ISSUE TITLE
Support configuring allowExtensionOperations

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#2298]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.10
+ provider.azurerm v1.17.0
```

### Affected Resource(s)

* azurerm_virtual_machine

### Important Factoids

The Terraform AzureRM provider currently sets the `provision_vm_agent` setting default as false per #28 and #2277. Because of this, the AzureRM provider needs a way to set the `osProfile.allowExtensionOperations` value. It seems to otherwise be undocumented (except for here: https://github.com/Azure/WALinuxAgent/wiki/VMs-without-WALinuxAgent#disable-extension-operations) that by setting `provision_vm_agent` to false, the `osProfile.allowExtensionOperations` is also set to false. This will mean a number of scenarios that involve extensions to the VM will never be possible, even with the VM agent manually provisioned by the user.

A user can enable this on a per vm basis using the Azure CLI as such:
```
az vm update -n hostname -g groupname  --set osProfile.allowExtensionOperations=true
```

The best use-case I've found so far is that `azurerm_recovery_services_protected_vm` will never work with a vm that has `provision_vm_agent = false` because the backup extension will never install with `osProfile.allowExtensionOperations`.

**Comment by tombuildsstuff** [comment]
hey @mbrancato 

Thanks for opening this issue :)

As a part of the 2.0 release we're planning on deprecating the existing `azurerm_virtual_machine` (and `azurerm_virtual_machine_scale_set` resources in favour of a Linux/Windows equivalent (e.g. something like a `azurerm_linux_virtual_machine` / `azurerm_windows_virtual_machine` resource). This allows us to update the schema to better reflect the how these resources are now used, since there's been some changes to API defaults over the years.

As such I believe this'd be best done as a part of that work - and so I've assigned this to the 2.0 milestone for the moment :)

Thanks!

**Comment by usvyatsky** [comment]
I have a fix for this - how do I contribute?

**Comment by tombuildsstuff** [comment]
hi @mbrancato 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We recently opened #5550 which adds support for the new Virtual Machine resources - and I'm able to confirm that this is fixed in the new Virtual Machine resources - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine` resource.

In order to get feedback on these new resources we'll be launching support for these new resources as an opt-in Beta in an upcoming 1.x release of the Azure Provider and ultimately release these as "GA" in the upcoming 2.0 release. We'll post an update in #2807 when both the opt-in Beta (1.x) & GA (2.0) are available - as such I'd recommend subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
