### ISSUE TITLE
Several Feature Enhancement Requests

### ISSUE THREAD

**Issue by MVP072000** [terraform-providers/terraform-provider-azurerm#2312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

Azure Provider – customer can’t do any of these via Terraform, and deploy via ARM JSON or PowerShell
1. API app ‘kind’ of service. -  I submitted a request a while back & they added a “kind” field to the app_service_plan, but it needed to actually be added to the app_service (https://github.com/terraform-providers/terraform-provider-azurerm/issues/443).  Unfortunately I didn’t catch that at first and just noticed it's still an issue.

2. Autoscaling for app services (documentation suggests it’s there, but so far doesn’t successfully deploy for us)
3. Enable configuration of scheduled web app backup to storage account, including database (for wordpress sites)
4. Add certificate from key vault to web app
5. Addition of extensions to web apps
6. Connect web app to App Insights
7. Add connection to “External Repository Project” to web app (we often need wordpress or similar sites & point to github repos on build)
8. Enable diagnostic logging for all resource types & push to storage or event hub

@bethcornils @bcornils

**Comment by tombuildsstuff** [comment]
hi @MVP072000 

Thanks for opening this issue :)

Since there's a bunch of different feature requests here - I'm going to ask that we close this in favour of multiple Github issues to be able to track this:

> API app ‘kind’ of service. - I submitted a request a while back & they added a “kind” field to the app_service_plan, but it needed to actually be added to the app_service (#443). Unfortunately I didn’t catch that at first and just noticed it's still an issue.

This is being tracked in #443 - please subscribe to that issue for updates.

> Autoscaling for app services (documentation suggests it’s there, but so far doesn’t successfully deploy for us)

This should be supported using [the `azurerm_ autoscale_setting` resource](https://www.terraform.io/docs/providers/azurerm/r/autoscale_setting.html).

> Enable configuration of scheduled web app backup to storage account, including database (for wordpress sites)

There's no issue open for this at this time - would you mind opening a new issue for this?

> Add certificate from key vault to web app

This isn't possible in the same manor as ARM Templates due to the fact there's no support for this in the Azure API - whilst it appears this is possible via an ARM Template (since there's references to a Key Vault Item ID) - my understanding is that the ARM Template Deployment API actually retrieves this information from the Key Vault and then passes this onto the downstream API.

We've raised this with the Azure API teams in the past about adding a `key_vault_item_id` type field and were told instead it'd be better to pull the information out from the Key Vault Certificate API (in the same manner as the ARM Template Deployment API presumably is) - and then submit this to the API. This could be achieved using the `azurerm_key_vault_certificate` Resource - or potentially using a Data Source for this purpose in the future (but this Data Source doesn't exist at this time - please open a Feature Request if you'd like to see support for this).

> Addition of extensions to web apps

There's no issue open for this at this time - would you mind opening a new issue for this? Would you be able to include an example for the extensions you're trying to use here (which would help with test data 😄)

> Connect web app to App Insights

This is possible at the moment, but there's some future enhancements available depending on a feature request in the Azure API - but there's a feature request tracking this here #1303

> Add connection to “External Repository Project” to web app (we often need wordpress or similar sites & point to github repos on build)

This is being tracked in #1104 - please subscribe to that issue for updates.

> Enable diagnostic logging for all resource types & push to storage or event hub

This is being tracked in #657 with a PR in #1291 - please subscribe to that issue for updates.

---

Would you mind subscribing to the issues which are already open above & opening any new issues where applicable? Since this is a collection of issues (which is going to be hard to track) I'm going to close this issue for the moment in favour of the individual issues.

Thanks!

**Comment by MVP072000** [comment]
Thanks Tom!  I will address the requests in your email in the next few days!

Thanks,
Mary P.
214-505-2323
mpolyakova@hashicorp.com

**Comment by MVP072000** [comment]
Tom,
Want to thank you for addressing my ticket so fast and with so much detail. You are speed lightning fast and both myself and the customer are beyond grateful!

Sent from my iPhone
214-505-2323
