### ISSUE TITLE
Error message not reflective of actual behavior for key vault

### ISSUE THREAD

**Issue by pabowers** [terraform-providers/terraform-provider-azurerm#2318]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* azurerm_key_vault
* azurerm_key_vault_certificate

### Terraform Configuration Files

Essentially the config is just that the name of the keyvault being created has 30 characters. I am not sure what the required length is, but the error does not reflect this.
### Debug Output

https://gist.github.com/pabowers/2be9adcdd283dea0cc8d138949c77ce8

### Expected Behavior

Error telling me that the issue is with the resource name

### Actual Behavior

The failure message gave me no indication of the actual problem.  It just said that the resource was not found.
### Steps to Reproduce

2. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @pabowers 

Thanks for opening this issue :)

> Essentially the config is just that the name of the keyvault being created has 30 characters. I am not sure what the required length is, but the error does not reflect this.

Taking a look at the error message here this is hard to diagnose without the associated Terraform Configuration - so that we can take a look into this would you be able to provide a Terraform Configuration which gives this error?

Thanks!

**Comment by pabowers** [comment]
Hi @tombuildsstuff 
I am using a configuration that I am working on [here](https://github.com/Azure/sap-hana).  Specifically, for the single-node-hana module.  You need  to enable the flag for windows bastion host and set username and password for the windows machine.  Try with setting the azure resource group variable to something long, for example `page-dummy-resource-group-name`.  This will trigger the error as shown above.  Please let me know if you have any questions.

Thanks

**Comment by tombuildsstuff** [comment]
hey @pabowers 

Thanks for getting back to us here - apologies for the delayed response here!

Taking a look at the error being returned here this appears to be a bug in Terraform Core prior to v12 where the dependency graph wasn't being populated correctly; as such I believe updating to using the latest version of Terraform 0.12 should fix this issue - would you be able to take a look and see if upgrading works for you?

Since I believe upgrading to the latest version of Terraform Core should fix this issue I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
