### ISSUE TITLE
data.azurerm_azuread_group

### ISSUE THREAD

**Issue by lawrenae** [terraform-providers/terraform-provider-azurerm#2326]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

My Basic desire is to *not* have to figure out the objectID of a group by hand before assigning roles to it in terraform. 

Today, I have to do something like this:
```sh
az ad group show --group my_cool_group
```
in order to retrieve the objectId, then hard code that id into a `locals` block in terraform and then refer to it in `azurerm_role_assignment`

Based on my reading of the API and the go client, this looks doable, but am not sure what roles/permissions are required yet

### New or Affected Data Source(s)

* azurerm_azuread_group

### Potential Terraform Configuration

```hcl
data "azurerm_azuread_group" "test" {
     display_name = "my_cool_group"
}

resource "azurerm_role_assignment" "azure_cloud_support_as_owner_owner" {
  scope                = "${azurerm_resource_group.current.id}"
  role_definition_name = "Owner"
  principal_id         = "${data.azurerm_azuread_group.test.id}"
}

```

### References

*  https://docs.microsoft.com/en-us/rest/api/graphrbac/groups/get

**Comment by tombuildsstuff** [comment]
hi @lawrenae 

Thanks for opening this issue :)

Support for a Data Source for Groups has previously been requested in #1272 which, rather than having multiple issues tracking the same thing I'm going to close this issue in favour of - please subscribe to that issue for updates. We've recently opened a proposal to move the Azure Active Directory resources out into their own Provider - which is being tracked in #2322 which may also be worth subscribing too.

Thanks!
