### ISSUE TITLE
AzureRM: Service Fabric node_type instance_count not working as expected

### ISSUE THREAD

**Issue by iharrington** [terraform-providers/terraform-provider-azurerm#2360]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.11.10`

### Affected Resource(s)

* azurerm_service_fabric_cluster

### Terraform Configuration Files

```hcl
###############
# Service Fabric Params
#
instance_count: 5
sf_node_name: nt1vm
reliability_level: Silver
upgrade_mode: Automatic
vm_image: Windows
client_endpoint_port: 19000
http_endpoint_port: 19080
thumbprint: xxxxXXxxxxxxxxxxxxXXXxx <--redacted
app_start_port: 20000
app_end_port: 30000
ephemeral_start_port: 49152
ephemeral_end_port: 65534
fabric_setting_name: Security
fabric_setting_param_value: EncryptAndSign
protected_account_key_name: StorageAccountKey1
```

### Expected Behavior

5 nodes are created

### Actual Behavior

0 nodes are created

### Steps to Reproduce

1. `terraform apply`

### References

[Your docs](https://www.terraform.io/docs/providers/azurerm/r/service_fabric_cluster.html#instance_count)

**Comment by tombuildsstuff** [comment]
hi @iharrington 

Thanks for opening this issue :)

The Service Fabric Cluster will only provision the Service Fabric Cluster resource - and not any associated worker nodes (which instead need to be provisioned using a VM Scale Set and a VM Extension). Whilst we don't have an example for that at this time - there's more information on the other resources necessary to build a Service Fabric Cluster [in this thread](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1948#issuecomment-425039537). That said if you're looking for a fully managed Service Fabric cluster you may wish to investigate Service Fabric Mesh instead, whilst we don't support this natively in Terraform at this time - please open a feature request if you'd like to see support for this.

Since this is a question about Terraform Configuration rather than a bug in Terraform - I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!

**Comment by iharrington** [comment]
@tombuildsstuff Is there any way to get the vm scale set to appear as nodes within service fabric? Are they able to be linked together?

**Comment by tombuildsstuff** [comment]
@iharrington this is also achievable through Terraform using a Virtual Machine Scale Set with the Service Fabric Virtual Machine Extension installed (which is the key component here) - as such the ARM Template should be portable to Terraform :)
