### ISSUE TITLE
AKS RBAC implementation unable to access kube dashboard

### ISSUE THREAD

**Issue by btai24** [terraform-providers/terraform-provider-azurerm#2362]
So I added RBAC w/ Azure AD to my kubernetes cluster, but when I try to run kubectl proxy I am prompted with:
```
To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code <redacted> to authenticate.
```
and when I do that, I am shown this error:
```
Sign in
Sorry, but we’re having trouble signing you in.

AADSTS50001: The application named <app uuid> was not found in the tenant named <tenant uuid>. This can happen if the application has not been installed by the administrator of the tenant or consented to by any user in the tenant. You might have sent your authentication request to the wrong tenant.
```
Here is some of my HCL for the AKS cluster:
```hcl
resource "azurerm_kubernetes_cluster" "aks_cluster" {
  ...
  service_principal {
    client_id     = "${azurerm_azuread_service_principal.service_principal.application_id}"
    client_secret = "${random_string.service_principal_password.result}"
  }

  role_based_access_control {
    azure_active_directory {
      client_app_id     = "${azurerm_azuread_service_principal.service_principal.application_id}"
      server_app_id     = "${azurerm_azuread_service_principal.service_principal.id}"
      server_app_secret = "${random_string.service_principal_password.result}"
    }
  }

  network_profile {
    network_plugin = "azure"
  }

  depends_on = [
    "azurerm_azuread_service_principal.service_principal",
  ]
...
}

esource "azurerm_azuread_application" "service_principal_app" {
  name = "${local.name}-aks"
}

resource "azurerm_azuread_service_principal" "service_principal" {
  application_id = "${azurerm_azuread_application.service_principal_app.application_id}"
}

resource "random_string" "service_principal_password" {
  length  = 16
  special = true

  keepers = {
    service_principal = "${azurerm_azuread_service_principal.service_principal.id}"
  }
}
```
Should I not be using the same service principal + application for RBAC?

**Comment by joakimhellum-in** [comment]
Normally there would be 3 Azure AD applications (at least for production):
- [Create AKS service principal](https://docs.microsoft.com/en-us/azure/aks/kubernetes-service-principal#delegate-access-to-other-azure-resources) (`client_id` and `client_secret`) 
  - Will be used to manage Azure resources.
- [Create client application](https://docs.microsoft.com/en-us/azure/aks/aad-integration#create-client-application) (`client_app_id`) 
  - Will be used to manage Azure AD logins with kubectl.
- [Create server application](https://docs.microsoft.com/en-us/azure/aks/aad-integration#create-server-application) (`server_app_id` and `server_app_secret`) 
  - Will be used to get Azure AD users and group memberships.
Because they do very different things, it is probably recommended to have 3 Azure AD applications fort his.

**Comment by btai24** [comment]
@joakimhellum-in thanks! that was the documentation I needed. seems like some of the steps cant be done with terraform.

**Comment by jpetitte** [comment]
I'm hitting the same questions. @joakimhellum-in do you know if those 3 AD applications can be built with Terraform? It seems like [azuread_application](https://www.terraform.io/docs/providers/azurerm/r/azuread_application.html) doesn't have the proper configuration options or attribute references, but I'm hoping I'm missing something.

**Comment by matelang** [comment]
I have opened a feature request for this on the `azuread` provider. I'm posting it here for reference:
https://github.com/terraform-providers/terraform-provider-azuread/issues/104

**Comment by matelang** [comment]
I think a good enough resolution is provided on the issue from the AD provider I linked above (https://github.com/terraform-providers/terraform-provider-azuread/issues/104).

Special thanks to @dbourcet for the snippet!

**Comment by dbourcet** [comment]
As I read this question a lot, I just created a [repo](https://github.com/dbourcet/aks-rbac-azure-ad) which sums it up. This is the very recent 0.4.0 version of the azuread Terraform provider which allow to Terraform all this, and this version has one week or so, that is why there is not much documentation online yet.

**Comment by matelang** [comment]
@dbourcet you :metal: ! :bowing_man:

**Comment by tombuildsstuff** [comment]
👋

Passing through here, since it appears the fix for this is in the AzureAD Provider - for the moment I'm going to suggest that we close this in favour of https://github.com/terraform-providers/terraform-provider-azuread/issues/104 - should something specific be required within AzureRM here we can re-open this and take another look :)

Thanks!
