### ISSUE TITLE
Feature Request: data source for azurerm_storage_blob

### ISSUE THREAD

**Issue by zgqallen** [terraform-providers/terraform-provider-azurerm#2380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
We may create a resource of azurerm_storage_blob firstly, and then we need to access some blob data in a specific path of the container, but I found there was no data source to access the blob data quickly.

### New or Affected Resource(s)

* azurerm_storage_blob - data source

### Potential Terraform Configuration

```hcl
data "azurerm_storage_blob" "testsb" {
  resource_group_name    = "${azurerm_resource_group.test.name}"
  storage_account_name   = "${azurerm_storage_account.test.name}"
  storage_container_name = "${azurerm_storage_container.test.name}"
  path = 'test/testa'
  ....
}

output blob_content {
      value = ${azure_storage_blob.testsb.content}
}
```

### References

Reference GCP: data "google_storage_object_signed_url" "storage_object"

* #0000

**Comment by tombuildsstuff** [comment]
hi @zgqallen 

Thanks for opening this issue :)

Taking a look at the way the Google provider implements this (in the `google_storage_object_signed_url` Data Source) - which exposes the URI of an access token which can be used to download the file. It should be possible to achieve the same behaviour using [the `azurerm_storage_account_sas` data source](https://www.terraform.io/docs/providers/azurerm/d/storage_account_sas.html) and the `azurerm_storage_blob` resource to combine this information together to give this URI.

Whilst we could add a Data Source to expose the path for a Blob within a given Storage Account/Container - since most of the information required to construct the URI would need to be specified to get the Blob's URI anyway (e.g. the account name, container name and blob path) - such that the only thing you'd gain from the data source would be the domain name used for the storage account. Unfortunately since all properties are saved into the state - we wouldn't be able to add a `content` property exposing the content of the Blob, since this'd mean storing large amounts of binary data in the Statefile.

In either case it should be possible to download the file contents by first constructing the Blob URI (and a SAS Token, for Private Blob's) - and then using this URL in conjunction with either [the External provider](https://www.terraform.io/docs/providers/external/data_source.html) or [a Local Provisioner](https://www.terraform.io/docs/provisioners/local-exec.html) to download this to a local file. Once this file is available in the local working directory it should be possible to access the content using the `${file("path")}` interpolation function.

Given that you'd still need to append the SAS Token anyway - would a Data Source to expose the URI of the Blob still be useful?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @zgqallen 

Since we've not heard back from you here I'm going to close this issue for the moment - but please let us know if exposing the URI of the Blob would be useful and we can take another look.

Thanks!
