### ISSUE TITLE
Terraform Gets 404 and Fails but resource is created. (Service Bus Auth Rule)

### ISSUE THREAD

**Issue by iharrington** [terraform-providers/terraform-provider-azurerm#2419]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.11.10`
`terraform-provider-azurerm_v1.19.0_x4`

### Affected Resource(s)

* azurerm_servicebus_topic_authorization_rule

### Expected Behavior

Create Service Bus Authorization rules before proceeding.

### Actual Behavior

This issue seems to be similar to other issues reported regarding dependancies (See references). It seems to have started recently as I believe I ran my script from scratch (no existing resources or state file) and it ran all the way through. When I try and apply (manually or using Ansible) I get a 404 on first run, but subsequent runs it work without issue. The resource that says is not existent is created by they time I check the Azure GUI. I tried explicitly stating the dependencies using `depends_on` to no avail. it seems to only fail on  `azurerm_servicebus_topic_authorization_rule`s though I am also creating an Event Hub and creating `azurerm_eventhub_authorization_rule`s. I am creating multiple of both and it doesn't fail on the same Service Bus Auth rule each time.

### Steps to Reproduce

1. `terraform apply`

### References

[#532](https://github.com/terraform-providers/terraform-provider-azurerm/issues/532)

* #2419

I can provide examples as needed. please advise.

**Comment by iharrington** [comment]
Side note `azurerm_servicebus_namespace_authorization_rule` also are being created and work as expected (no errors so far and ran this 10+ times today)

**Comment by tombuildsstuff** [comment]
hi @iharrington 

Thanks for opening this issue :)

So that we can take a look into this would you be able to provide the Terraform Configuration that you're using?

Thanks!

**Comment by iharrington** [comment]
We use ansible to fill in the configuration file, I'm not sure how much info you need. Here is the redacted ansible config fie and terraform config file. Let me know if you need more.
[redact_config.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/2640555/redact_config.txt) . <-- yaml

config.tf:
```
variable env {}
variable country {}
variable region {}
variable product {}
variable location {}
variable subscription_id {}
variable client_id {}
variable client_secret {}
variable tenant_id {}
variable CreatedBy {}
variable CreationDate {}
```

**Comment by tombuildsstuff** [comment]
hey @iharrington

Would it be possible to post the full Terraform Configuration being used - the only attachment I can see is the Ansible section / some variables in the Terraform section?

On a (semi) related note the Terraform Configuration defined above may work today but will require configuration changes from Terraform 0.12 onwards - variables need to be quoted e.g.

```
variable "env" {}
```

rather than

```
variable env {}
```

The undeprecated (e.g. quoted) syntax is valid in both Terraform 0.11 and 0.12 - so you should be able to use that syntax today / it won't cause any breaking changes :)

Thanks!

**Comment by tombuildsstuff** [comment]
👋 

Apologies for the delayed reply here!

Unfortunately there's not enough information above for us to dig into this - in particular we require a Terraform Configuration, rather than the variables file. As there's not enough information in this issue I'm going to close this issue for the moment, however if you can provide a reproducible Terraform Configuration showing this then we should be able to take another look.

Thanks!
