### ISSUE TITLE
Private DNS and azurerm_dns records length not set?

### ISSUE THREAD

**Issue by jameskeane** [terraform-providers/terraform-provider-azurerm#2423]
I'm noticing unnecessary tainting when planning a change that adds a new record to a private dns zone (using count).

<img width="836" alt="screen shot 2018-11-30 at 12 32 48 pm" src="https://user-images.githubusercontent.com/186679/49305039-1b9ab780-f49c-11e8-868b-cf8c9fed4503.png">

Why is `records.#` showing as `""`? It's set correctly (`=1`) in my local state.

**Comment by tombuildsstuff** [comment]
hi @jameskeane 

Thanks for opening this issue :)

Current versions of Terraform (e.g. 0.11.x and below) implement `count` in a different manner such that whilst elements are created in the graph they don't necessarily have all the information populated during the plan (and as such computed values, such as the number `#` of `records`) and as such may be shown as changed.

The next version of Terraform Core (Terraform 0.12) brings some major enhancements to the that Terraform; including fixing the way that `count` works such that it's more consistent in scenarios such as this. At this point 0.12 is still in Alpha (beta 2) at the time of writing - however from what I can see [it appears this fixes the issue you're seeing with computed fields](https://github.com/hashicorp/terraform/issues/18349#issuecomment-434856352).

Whilst there's not a whole bunch we can do in the AzureRM Provider to work around the `count` issue in the interim unfortunately (since it's a Core issue) - if the `name` and `zone_name` fields are the same for all of the resources it should be possible to use the combined IP Address/CNAME values for the `records` field, like so:

```
resource "azurerm_resource_group" "test" {
  name     = "issue2423-resources"
  location = "West Europe"
}

resource "azurerm_dns_zone" "test" {
  name                = "mydomain.com"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_public_ip" "test" {
  count = 3
  name                         = "example-pip${count.index}"
  location                     = "${azurerm_resource_group.test.location}"
  resource_group_name          = "${azurerm_resource_group.test.name}"
  public_ip_address_allocation = "static"
}

resource "azurerm_dns_a_record" "test" {
  name                = "example"
  resource_group_name = "${azurerm_resource_group.test.name}"
  zone_name           = "${azurerm_dns_zone.test.name}"
  ttl                 = 300
  records             = ["${azurerm_public_ip.test.*.ip_address}"]
}
```

Would you be able to take a look and see if that works for you? Given this is an issue in Terraform Core (which will be fixed as a part of 0.12) - I'm going to close this issue for the moment (however we'll continue responding 😄)

Thanks!
