### ISSUE TITLE
[v0.10.0] delete_os_disk_on_termination issue

### ISSUE THREAD

**Issue by donestefan** [terraform-providers/terraform-provider-azurerm#243]
### Terraform Version
Terraform v0.10.0
terraform-provider-azurerm_v0.1.4_x4

### Affected Resource(s)
azurerm_virtual_machine

### Terraform Configuration Files
```hcl
resource "azurerm_virtual_machine" "test" {
  name                  = "test"
  delete_os_disk_on_termination = false
...
  storage_os_disk {
    name              = "osdisk123"
    create_option     = "FromImage"
    os_type           = "linux"
  }
}
```

### Expected Behavior
storage_os_disk "osdisk123" is created only once on first vm creation.
Since "delete_os_disk_on_termination = false" is set, the existing disk should be reused when terraform triggers a re-deployment of the vm (e.g. after the machine config changes).

### Actual Behavior
Every vm re-deployment (e.g. after adding a NIC or a data_disk) causes an error message "Disk osdisk123 already exists in resource group test-rg. Only CreateOption.Attach is supported."
I guess this means terraform tries to create another disk with the same name. 
Since "delete_os_disk_on_termination = false" is set, terraform should realize that the resource is already created - and it should try to reuse it.

**Comment by shibug** [comment]
This happens for delete_data_disk_on_termination also.

**Comment by harijayms** [comment]
Adding a NIC or data disk doesn't delete and create the VM again, so this is expected in some sense, need to look further.

**Comment by donestefan** [comment]
Hmmm... It's been a while ago.
But as far as I remember almost every config change resulted in the destruction/recreation of the VM.
But you can probably use `terraform taint azurerm_virtual_machine.test` to run into the `Disk already exists` error message.

**Comment by tombuildsstuff** [comment]
Hey @donestefan 

Thanks for opening this issue - apologies for the delayed response here

> Since "delete_os_disk_on_termination = false" is set, terraform should realize that the resource is already created - and it should try to reuse it.

Some background: this is due to the way the underlying Azure API works - where existing disks need to be marked as `Attach` instead of `Empty` / `FromImage` (otherwise you see an error).

Whilst we could take the approach of sending `Attach` to the Azure API instead of `Empty` / `FromImage` when the disk already exists - this would lead to a perpetual state diff (where the user would constantly see changes needing to be made as the State in Azure didn't match the Code). Unfortunately this means this approach isn't really viable (at least, without masking the real state to the Operator).

Instead, I think a better approach would be to raise a Enhancement Request for the Azure API's on [the Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs/issues) to support `CreateOrAttach` or `FromImageOrAttach` as Create Options. This would allow Terraform, the Azure Portal and ARM Templates to accurately reflect the state of infrastructure in Azure, rather than masking the real state from the user.

Given I don't think we have an immediate solution to this issue, I'm going to suggest we close this issue for the moment - that said please feel free to re-open this if you want us to investigate this further :)

Thanks!
