### ISSUE TITLE
Omitting connection_string leaves existing ones intact

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#2434]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.10
+ provider.azurerm v1.19.0
### Affected Resource(s)

* azurerm_app_service
* azurerm_app_service_slot

### Expected Behavior

If `connection_string` is not specified, I expect Terraform to delete the existing ones.

### Actual Behavior

Existing connection strings remain untouched.

**Comment by tombuildsstuff** [comment]
hi @Leon99 

Thanks for opening this issue :)

App Services in Azure are a bit of a special case due to slots - where it's possible to configure the App Settings/Connection Strings either on the top-level App Service, or within a Slot which eventually becomes the active slot (via [the `azurerm_app_service_active_slot` resource](https://www.terraform.io/docs/providers/azurerm/r/app_service_active_slot.html)). In this particular case the App Settings/Connection String fields are Optional+Computed, what this means is that if the user defines them in-line, we'll manage these properties; however if these values are omitted we'll read the values from Azure. This is because these values may be overwritten by a Slot becoming active (and thus users may want to manage the settings for a Slot independently from the settings for App Service).

That said - it's possible to ensure these values are reset by setting them to an empty value e.g.

```
resource "azurerm_app_service" "test" {
  app_settings = {}
  connection_strings = []
}
```

Would you be able to take a look and see if this works for you?

With regards to the App Service Slot resource - since these aren't overwritten I believe these could probably have the Computed removed, but this would require some further investigation.

Thanks!

**Comment by Leon99** [comment]
Thanks for the thorough explanation @tombuildsstuff. `connection_string = []` did the trick.

**Comment by tombuildsstuff** [comment]
Closing since this appears to be resolved 👍
