### ISSUE TITLE
Feature Request: AKS node information 

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#2468]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like for the `azurerm_kubernetes_cluster` data source to allow pulling information like a list of nodes that were provisioned. It currently will return the resource group (predictable naming) and other information, but since the nodes have a random integer, we can't build the node ID information.

My use case is to automatically add them to Azure Monitor using `azure_monitor_*` resources using Terraform.

Other options that may work would be to read resources from the resource group created, or maybe some other resource listing.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
data "azurerm_kubernetes_cluster" "test" {
  name                = "myakscluster"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

resource "azurerm_monitor_metric_alert" "aks-node-cpu" {
  name                = "aks-cpu-metricalert"
  resource_group_name = "${azurerm_resource_group.test.name}"
  scopes              = ["${data.azurerm_kubernetes_cluster.test.node.*.id}"]
  description         = "Monitor Node CPU for average > 90% usage."

  criteria {
    metric_namespace = "Microsoft.Compute/virtualMachines"
    metric_name      = "Percentage CPU"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 90
  }

  action {
    action_group_id = "${azurerm_monitor_action_group.test.id}"
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @mbrancato 

Thanks for opening this issue :)

Taking a quick look into this it appears the fields necessary for this aren't directly exposed from the Kubernetes API. As such whilst we could potentially lookup the Virtual Machines present within the Resource Group created by AKS, it's possible these Virtual Machines could be changed outside of a Terraform Run (and thus lead to phantom changes to the Terraform Configuration).

Given that AKS can manage the nodes within the Resource Group outside of Terraform - and thus changes can be made outside of Terraform runs - I'm wondering if it'd be possible to achieve this using using Log Analytics/OMS, since there's a native integration there? Here's an [example](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/kubernetes/monitoring/main.tf#L13-L24) of what I mean - what do you think?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @mbrancato 

Taking another look into this, since AKS is provisioning a separate Resource Group for the Cluster Nodes - I believe there's two different ways of achieving this:

1. Scoping the `azurerm_monitor_metric_alert` to Virtual Machines within the Resource Group, for example:

```
data "azurerm_kubernetes_cluster" "test" {
  name                = "myakscluster"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

# the location should always be the same as the AKS cluster, so let's infer it
data "azurerm_resource_group" "nodes" {
  name = "${data.azurerm_kubernetes_cluster.test.node_resource_group}"
  location = "${data.azurerm_kubernetes_cluster.test.location}"
}

# we should be able to scope to the RG since we're only targeting VM's inside it
resource "azurerm_monitor_metric_alert" "aks-node-cpu" {
  name                = "aks-cpu-metricalert"
  resource_group_name = "${azurerm_resource_group.test.name}"
  scopes              = ["${data. azurerm_resource_group.nodes.id}"] # or possibly {id}/virtualMachines?
  description         = "Monitor Node CPU for average > 90% usage."

  criteria {
    metric_namespace = "Microsoft.Compute/virtualMachines"
    metric_name      = "Percentage CPU"
    aggregation      = "Average"
    operator         = "GreaterThan"
    threshold        = 90
  }

  action {
    action_group_id = "${azurerm_monitor_action_group.test.id}"
  }
}
```

2. We could look to implement a new Data Source for which returned the ID's of all Virtual Machines within a Resource Group; however this wouldn't be idempotent (since the nodes can be created between Terraform runs) - and as such I believe the other approach could be a better option here?

Since we've not heard back from you here I'm going to close this issue for the moment - however if that doesn't work for you please let us know and we'll take another look :)

Thanks!

**Comment by derekrprice** [comment]
@tombuildsstuff, I am going to attempt to implement your last solution, above, for some metrics alerts, but I have a use case that it does not fit.  I want to build azurerm_connection_monitor instances to monitor network connectivity to external resources.  These require an actual VM to be specified as a source - a resource group will not do as the scope.
