### ISSUE TITLE
Support RBAC data role assignments for storage entities

### ISSUE THREAD

**Issue by perbergland** [terraform-providers/terraform-provider-azurerm#2482]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

RBAC support for storage will be out of preview soon so it should be supported in terraform similar to how other RBAC role assignments work.

### New or Affected Resource(s)

* azurerm_storage_container
* azurerm_storage_account

### References

* #1070 

https://docs.microsoft.com/en-us/azure/storage/common/storage-auth-aad-rbac

**Comment by tombuildsstuff** [comment]
hi @perbergland 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this I believe this functionality should be available via [the `azurerm_role_assignment` resource](https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html) which allows for any Azure Role (built-in or custom) to be assigned to a specific scope (in this case the Storage Container) - would you be able to take a look and see if that works for you?

Since this is a question regarding Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment; however please let us know if that doesn't work for you and we'll take another look :)

Thanks!
