### ISSUE TITLE
Using network_plugin = "kubenet" in azurerm_kubernetes_cluster leads to unreliable DNS in pods, unfortunately "kubenet" is the default.

### ISSUE THREAD

**Issue by omichels** [terraform-providers/terraform-provider-azurerm#2496]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.10
+ provider.azurerm v1.19.0
+ provider.kubernetes v1.4.0
+ provider.random v2.0.0

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl

resource "azurerm_kubernetes_cluster" "k8scluster3" {
  name     = "k8scluster3"
  location = "${var.location}"
  resource_group_name = "${var.resource_group_name}"
  dns_prefix          = "${random_string.fqdn.result}"
...
  azurerm_kubernetes_cluster {
    network_plugin = "kubenet"
  }

}
```

### Expected Behavior

cluster should be created, the pods should be able to use dns service

### Actual Behavior

the cluster gets created, BUT the dns service is unrealiable. 
I was using an init-containter in a replication controller to pull configuration data from an azure blob storage. Most (but not all REST requests) timed-out with "no such host" 

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by omichels** [comment]
switchting to 
network_plugin = "azure"
resolved my issues

**Comment by tombuildsstuff** [comment]
hi @omichels 

Thanks for opening this issue :)

Taking a look into this this appears to be an issue with Azure Kubernetes Service itself, rather than something specific to Terraform - as such I'd encourage you [to file an issue on the AKS repository](https://github.com/Azure/aks-engine). One alternate option would be to use a Subnet on a Virtual Network instead ([there's an example of how to do that in Terraform here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/kubernetes/advanced-networking/main.tf)) - which would allow you to configure a custom route table as necessary (although one is configured by default now too, IIRC).

Since this is an issue with AKS (as a service) rather than something specific to Terraform - I don't think there's a lot we can do to work around this, unfortunately (outside of switching to the `azure` network type, as described above). That said the AKS Team should be able to help diagnose this further, and I'd recommend [opening an issue on that repository](https://github.com/Azure/aks-engine); but since this is an issue with the service I'm going to close this issue for the moment.

Thanks!
