### ISSUE TITLE
Provider requiring `az` to be present even when credentials already exist

### ISSUE THREAD

**Issue by rikonor** [terraform-providers/terraform-provider-azurerm#2509]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.11.10
+ provider.azurerm v1.20.0
```

### Affected Resource(s)

* azurerm_provider

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version         = "1.20"
  subscription_id = "${var.subscription_id}"
}
```

### Debug Output

[Gist](https://gist.github.com/rikonor/db53ef1cfbefad08b078a284dd423985)

### Panic Output

No panic occurred.

### Expected Behavior

The provider should have picked up Azure credentials from `~/.azure`.

### Actual Behavior

The provider exited because it was not able to find `az`:

```
Error: Error refreshing state: 1 error(s) occurred:
* provider.azurerm: Error obtaining Authorization Token from the Azure CLI: Error launching Azure CLI: exec: "az": executable file not found in $PATH
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hey @rikonor

Thanks for opening this issue :)

As a part of the 1.20 release we've modified the way that the Azure CLI authentication works such that we now attempt to parse a token from the Azure CLI, rather than reading the authentication files directly. This change came as a part of fixing #502, where in versions of the AzureRM Provider prior to 1.20, Terraform could only read the contents of the authentication files stored in `~/.azure` and (since we didn't own the files) were unable to persist the updated access tokens; as such this meant Terraform could only work when the access tokens were still valid, which timed out after an hour.

In order to work around this, as you've mentioned we now shell out to the Azure CLI to retrieve an access token which can be used. Since this is an internal change to the Azure CLI authentication (although we documented this has changed in 1.20 in the Azure CLI Authentication docs) - we now assume that the Azure CLI is available on users PATH, since we need to shell out to it. It's worth noting [we recommend using the Azure CLI only when authentication on your local machine](https://www.terraform.io/docs/providers/azurerm/index.html#authenticating-to-azure) - we instead recommend either a Service Principal or Managed Service Identity when non-interactively (for example when running from a CI Server)

Out of interest, what's the scenario you're running where the Azure CLI credentials are available in ~/.azure, but the Azure CLI isn't? I'm assuming the Azure CLI is installed in a custom directory/not on your PATH?

Thanks!

**Comment by rikonor** [comment]
Hi @tombuildsstuff,

Thank you for the explanation.

My scenario is that I'm running Terraform in a Docker container and the Azure CLI in a different container. Both containers expose a volume on the host machine at `~/.azure`, so when you authenticate using the Azure CLI container, you are able to use those credentials from the Terraform container.

This is for working locally, so I do agree that a way around this would be to use a Service Principal. That said, I'd be curious to know if having some sort of fallback in case `az` is not available would be a reasonable option here? Or whether you guys absolutely want to require `az` to be available.

Thanks for the response!

**Comment by tombuildsstuff** [comment]
@rikonor got it, thanks for the the extra information about your use case :)

> My scenario is that I'm running Terraform in a Docker container and the Azure CLI in a different container. Both containers expose a volume on the host machine at ~/.azure, so when you authenticate using the Azure CLI container, you are able to use those credentials from the Terraform container.

> That said, I'd be curious to know if having some sort of fallback in case az is not available would be a reasonable option here? Or whether you guys absolutely want to require az to be available.

Whilst I can understand that works prior to the v1.20 release, using the Azure CLI for authenticating in this manner isn't officially supported (since the intended use-case here is that users are running Terraform locally, with the Azure CLI installed locally) - as such whilst we could update the code to still use the original parsing logic, that then re-opens #502 which sends us back to square one 🙃 - as such I think we need to assume that `az` is available somewhere.

One option we could take here would be to allow users to specify a custom path to the Azure CLI - but unfortunately I don't believe that'd help in your scenario?

Given the scenario you've described, I'd suggest the simplest transition would be to switch to using a Service Principal with a Client Certificate for authentication. I believe it should be possible to implement this in a similar manner to how you're doing this at the moment - by generating a (time-limited?) Certificate and a Service Principal from the Azure CLI container, then using this in Terraform. From Terraform's perspective you'd then just need to specify the variables `client_certificate_path` and `client_certificate_password` in the provider block (or as Environment Variables) - which should allow this to continue working in a similar manner to how it is today.

Would that approach work for you?

Thanks!t

**Comment by rikonor** [comment]
Hi @tombuildsstuff,

Yes, in theory that would work. The Azure account I'm using is slightly locked down, but I believe I should be able to make it work.

Just out of curiosity, though, would it be not feasible to just fallback to the old parsing logic assuming `az` is not available?

Thanks!

**Comment by rikonor** [comment]
Hi @tombuildsstuff,

> Technically, yes - however that'd then mean the credentials expire after an hour again ...

Wouldn't that only be true for the case where `az` wasn't present? So whilst in my case I would have to re-authenticate manually, cases where `az` is present wouldn't be impacted.

> Apologies that this change has impeded your workflow ...

No worries, and thank you for taking the time to walk through this with me!
