### ISSUE TITLE
Kubernetes cluster creation should automatically create service principal

### ISSUE THREAD

**Issue by logankp** [terraform-providers/terraform-provider-azurerm#2510]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Creating an Azure Kubernetes Service should not require creating a service principal. When creating an AKS cluster through the portal and the command line, Azure can automatically create a service principal. I think the provider should do the same if the service_principal block of "azurerm_kubernetes_cluster" is not specified.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "kubernetes" {
  name                = "${var.kubernetes_cluster_name}"
  location            = "${azurerm_resource_group.resource_group.location}"
  resource_group_name = "${azurerm_resource_group.resource_group.name}"
  dns_prefix          = "${var.dns_prefix}"
  kubernetes_version  = "${var.kubernetes_version}"

  agent_pool_profile {
    name    = "default"
    count   = 1
    vm_size = "Standard_DS1_v2"
    os_type = "Linux"

    vnet_subnet_id = "${azurerm_subnet.kubernetes.id}"
  }
#No service_prinicpal block!

  addon_profile {
    http_application_routing {
      enabled = true
    }
  }

  network_profile {
    network_plugin = "azure"
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @logankp 

Thanks for opening this issue :)

We've spent some time looking into this previously - and initially wondered if it'd be worth reusing the Service Principal credentials being used when Terraform is running as a Service Principal, or spinning one up dynamically if the user doesn't specify a Service Principal.

After taking a look into that approach, we found in order to do this effectively we'd need to make a lot of assumptions about the environment in which we're running. For example, we could reuse the credentials for the Service Principal that Terraform is using, however this assumes that the credentials are sufficiently locked down. Alternatively we could generate a new Service Principal and assign that, but that both assumes the user running Terraform has permissions to do so; and also assumes that the permissions we'd assign don't need to change over time.

Given these assumptions we ultimately ended up deciding against this approach, since whilst this'd make the Day 0 approach simpler (in terms of not having to specify the credentials in-line) - it makes the Day 1+ operations harder since we'd need to assume the permissions required.


Instead I believe it'd be better to create a Terraform Module which provisions a Service Principal with the permissions required by AKS - and to reference this instead. This has a couple of benefits over Terraform doing this for you: firstly that it's possible for operators to choose when to upgrade independently from the version of the Terraform Provider being used; and secondly this allows organizations to customize this themselves, per any policy requirements they may have.

From Terraform's side, we've recently opened #2322 which discusses splitting the Azure Active Directory resources out of the AzureRM Provider and into a new, AzureAD Provider. I'd suggest that once this is done, it'd be beneficial to build a Terraform Module which generates a Service Principal with the permissions required for AKS.

Whilst we appreciate the feature request - unfortunately this isn't something we're planning to implement based on the number of assumptions of the environment we're running in which'd be required; and as such I'm going to close this issue for the moment.

Thanks!

**Comment by PaulRudin** [comment]
The portal just creates a new service principal when a new cluster is created without providing an existing sp. It's not clear why creating via terraform should be any different - just make the sp optional, and create one if it's not provide, surely?
