### ISSUE TITLE
Creation of azurerm_kubernetes_cluster errors and is missing from state

### ISSUE THREAD

**Issue by clstokes** [terraform-providers/terraform-provider-azurerm#2523]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
15:42:25 [terraform-azure-aks-error] $ terraform -v
Terraform v0.11.10
+ provider.azurerm v1.20.0
```

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Terraform Configuration Files

```hcl
variable "ssh_public_key" {
  default = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQDkew7jIFOpwnSEHBtrEMxRFhH+c7nAcUoT9hqE4/nen3LoL6UG/QRtTSlLvY7KVGEhuSA0kFqsp5SwA+Z01h7Qv+HZUAU9DuyPxopjMbb+v9MwcxKvPe9fyfhwoJzgZib2LYe+6tBdEjDi1bcMsuAin2l2gok5c3i8Hzi0cX7jaYZgcYAdbBATJVy2xJ7O980Bd6fKTxGtzu5dACI1WWTGdj8/eCifa60CaMe4oqrEKa0vmkvN9MYfCyDbUv6SnrhaDrAl8+BzOmIOtROxhb72XUJBIsFBs20SeWXiTKH9zWP8mQaRKICPPompkGQoHgmM62ATczGjbqFbVAgVqutYWOBGCjBCOrWymdCRlurPZC5PSricN8JbqQ39uMgv+/qbui7PAavY6gQewXBm7+n7BKmEeS5pWtBQag7Ipg7a33FKa20hn42GV4VwJmad6TUdEfhP9o4wFuyGLo8v1jKfHxAt/tGd2iOvb8HhyQVb14gKbkPoRfweyZxge5ywKuPgLJd/rw33r1Fe/bKv3CGBgHADe+IRl6LKGSqINrf91fdeckf+0oYUX+f0QcYI8asFDLiPTA0rkaMXKqK0ysItv2fBJwjU0BpXisaXVdOW+VDe+AML0vsexp1jaaMR1LS/AY1tbTKHkiV/mj/53nJzOi0byVwcSyU0vo5ZE9UGAQ== your_email@example.com"
}

resource "azurerm_resource_group" "aks" {
  name     = "aks"
  location = "East US"
}

resource "azurerm_azuread_application" "aks" {
  name = "aks"
}

resource "azurerm_azuread_service_principal" "aksSp" {
  application_id = "${azurerm_azuread_application.aks.application_id}"
}

resource "azurerm_azuread_service_principal_password" "aksSpPassword" {
  service_principal_id = "${azurerm_azuread_service_principal.aksSp.id}"
  value                = "VT=uSgbTanZhyz@%nL9Hpd+Tfay_MRV#"
  end_date             = "2099-01-01T00:00:00Z"
}

resource "azurerm_kubernetes_cluster" "east" {
  // Global config arguments
  name                = "aksCluster-east"
  resource_group_name = "${azurerm_resource_group.aks.name}"

  linux_profile {
    admin_username = "aksuser"

    ssh_key = [{
      key_data = "${var.ssh_public_key}"
    }]
  }

  service_principal {
    client_id     = "${azurerm_azuread_application.aks.application_id}"
    client_secret = "${azurerm_azuread_service_principal_password.aksSpPassword.value}"
  }

  // Per-cluster config arguments
  location = "East US"

  agent_pool_profile {
    name    = "aksagentpool"
    count   = 2
    vm_size = "Standard_D2_v2"
  }

  dns_prefix = "east-kube"
}

resource "azurerm_kubernetes_cluster" "west" {
  // Global config arguments
  name                = "aksCluster-west"
  resource_group_name = "${azurerm_resource_group.aks.name}"

  linux_profile {
    admin_username = "aksuser"

    ssh_key = [{
      key_data = "${var.ssh_public_key}"
    }]
  }

  service_principal {
    client_id     = "${azurerm_azuread_application.aks.application_id}"
    client_secret = "${azurerm_azuread_service_principal_password.aksSpPassword.value}"
  }

  // Per-cluster config arguments
  location = "East US"
  // location = "West US"

  agent_pool_profile {
    name    = "aksagentpool"
    count   = 5
    vm_size = "Standard_D2_v2"
  }

  dns_prefix = "west-kube"
}
```

### Debug Output

https://gist.github.com/clstokes/76599de6cdbed1186173aae93d907a2f

### Expected Behavior

When creating a `azurerm_kubernetes_cluster` resource fails with an error it should be persisted into state as _tainted_.

### Actual Behavior

When creation of a `azurerm_kubernetes_cluster` resource fails with the error below it actually gets created but is not persisted into state. The Azure API responds with `201 Created` and subsequent checks respond with status of `InProgress`, but eventually the apply will error out

The included HCL configuration creates two AKS clusters in the _same_ Azure region. For a new Azure account with low account limits (i.e. max of 10 cores), this config will fail with the error:

```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_kubernetes_cluster.west: 1 error(s) occurred:

* azurerm_kubernetes_cluster.west: Error waiting for completion of Managed Kubernetes Cluster "aksCluster-west" (Resource Group "aks"): Code="OperationNotAllowed" Message="Operation results in exceeding quota limits of Core. Maximum allowed: 10, Current in use: 10, Additional requested: 2. Please read more about quota increase at https://aka.ms/ProdportalCRP/?#create/Microsoft.Support/Parameters/{\"subId\":\"dad1da46-e543-4a91-b7b4-3740c8411c30\",\"pesId\":\"15621\",\"supportTopicId\":\"32447243\"}."
```

### Steps to Reproduce

1. `terraform apply`
1. Observe `Operation results in exceeding quota limits of Core...` error.
1. `az aks list` to see both clusters are actually created.
1. `terraform show` to see only one aksCluster is actually present in state.
1. `terraform destroy` to clean up.

Note: You'll likely hit #1635 as this happens nearly 100% of the time during initial creation of `azurerm_kubernetes_cluster`'s. If so, repeat `terraform apply` until this error goes aweay.

### Important Factoids

Your Azure account must have low account limits (i.e. max of 10 cores) to reproduce this specific error though I expect other errors would result in the same behavior.

**Comment by tombuildsstuff** [comment]
hey @clstokes 

Thanks for opening this issue :)

Unfortunately the `status` field having a value of `Failed` has a few different possible meanings with Azure:

1. The resource has successfully provisioned in the past, however the latest change wasn't valid (but the resource will continue running just fine)
2. Something failed during resource provisioning (for example, a VM with a Linux configuration but a Windows HDD won't be able to boot) such that the resource isn't usable and must be recreated

The meaning of the `Failed` status also changes depending on the API and configuration being used, such that whilst we could potentially track the ID of the resource, we're unable to tell if the resource should be tainted or not. As such rather than potentially causing further issues unfortunately we require the operator to decide how's best to proceed here.

Whilst I appreciate this isn't ideal (since some other providers track the state of the resource once it's provisioned but failed - unfortunately where the `Failed` state represents completely different things (one usage meaning it's fine to continue using, the other meaning it's unusable) - means it's not possible for us to easily determine if the resource is healthy or not.

If you're interested in this functionality I'd suggest [opening an issue on the Azure Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs/issues) - however unfortunately this isn't something we're able to practically implement at this time due to the different meanings of the `Failed` status - as such I'm going to close this issue for the moment.

Thanks!
