### ISSUE TITLE
azurerm_subnet_network_security_group_association is removing and adding in each terraform apply

### ISSUE THREAD

**Issue by 1arrow** [terraform-providers/terraform-provider-azurerm#2526]
We have a resource definition like below to link NSG and subnet

resource "azurerm_subnet_network_security_group_association" "app-subnet-nsg-link" {
  count                     = "${var.app-subnet-iprange == "" ? "0" : "1"}"
  subnet_id                 = "${azurerm_subnet.app-subnet.id}"
  network_security_group_id = "${azurerm_network_security_group.app-subnet-nsg.id}"
}

app-subnet-iprange has fixed value

Every time when we do terraform apply, it removes the link..and the next terraform apply is adding it back.

**Comment by paegorov** [comment]
@1arrow this is an expected behavior. If you look into [the description of the azurerm_subnet module](https://www.terraform.io/docs/providers/azurerm/r/subnet.html), you'll see the note: 

> **NOTE**: At this time Subnet <-> Network Security Group associations need to be configured both using this field (which is now Deprecated) and/or using the `azurerm_subnet_network_security_group_association` resource. This field field is deprecated and will be removed in favour of that resource in the next major version (2.0) of the AzureRM Provider.

Therefore you need to provide BOTH the deprecated field `network_security_group_id` in the subnet resource and `azurerm_subnet_network_security_group_association` to stop recreating association.

Had the same issue and resolved it adding `network_security_group_id` to the subnet resource.

**Comment by tombuildsstuff** [comment]
hey @1arrow 

Thanks for opening this issue - apologies for the delayed response here!

As @paegorov has mentioned so that we don't break the ability to remove an NSG from a Subnet using the `azurerm_subnet` resource, at this time it's required to specify the NSG association in both the `azurerm_subnet` resource and using the `azurerm_subnet_network_security_group_association` resource. Whilst this behaviour is unexpected, unfortunately it's the only way to ensure we don't break that use-case at this time.

The next major version of the AzureRM Provider (2.0) will remove the `network_security_group_id` field from the `azurerm_subnet` resource - meaning that only the `azurerm_subnet_network_security_group_association` resource will be required to configure a Network Security Group with a Subnet - however until that time this needs to be configured in both places. Whilst the UX isn't ideal here, this behaviour is currently intentional & documented - as such I'm going to close this issue for the moment.

Thanks!

**Comment by pedrohdz** [comment]
Hey @paegorov  @tombuildsstuff 
How about the use `lifecycle.ignore_changes` instead of ? Something like:

```
resource "azurerm_subnet" "test" {
  lifecycle {
    ignore_changes = [ "network_security_group_id" ]
  }
  ...
```

The reason I ask is because I get a circular dependency given how my `azurerm_network_security_group` is configured.

**Comment by tombuildsstuff** [comment]
@pedrohdz that won't work since the value is submitted for any update of the Subnet; so whilst this isn't ideal unfortunately this needs both resources to be specified at this time. The planned next release (2.0) should resolve this by removing this field from the `azurerm_subnet` resource
