### ISSUE TITLE
Multiple VNets with multiple subs 

### ISSUE THREAD

**Issue by minneapolis29** [terraform-providers/terraform-provider-azurerm#2555]
I need to pull my question from the other forum but what i am trying to do is create multiple vnets with multiple subs: 
. creats vnets with a single vnet each: i am missing something small, i think.
Thanks in advance 
[main.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/2699563/main.txt)
[main_true.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/2699564/main_true.txt)

**Comment by tombuildsstuff** [comment]
hi @minneapolis29 

Thanks for opening this issue :)

Information on using multiple instances of a Provider (for example working across subscriptions) can be [found here](https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances) - it's possible to achieve this using the `provider` field on each resource, for example to create resource groups across subscriptions:

```
provider "azurerm" {
  subscription_id = "00000000-0000-0000-0000-000000000000"
  alias = "first"
}

provider "azurerm" {
  subscription_id = "11111111-1111-1111-1111-111111111111"
  alias = "second"
}

resource "azurerm_resource_group" "test" {
  name      = "example-rg"
  location  = "west europe"
  provider = "azurerm.first"
}

resource "azurerm_resource_group" "test2" {
  name      = "some-other-rg"
  location  = "west europe"
  provider = "azurerm.second"
}
```

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug with Terraform I'm going to close this issue for the moment.

Thanks!

**Comment by minneapolis29** [comment]
I appreciate the quick response Tom and i am sorry for the wrong forum: But i don't think i have managed to ask the right question. Could i achieve my goal with one big for loop? three vnets with three subnets each?

**Comment by tombuildsstuff** [comment]
@minneapolis29 you can use the Count metaparameter on a resource to create 3 networks with 3 subnets; but that’d only work for resources using the same provider / subscription. If you’re looking to create 3 networks/subnets with one per subscription unfortunately you’d need to duplicate the code, as far as I’m aware

**Comment by minneapolis29** [comment]
Cheers: i just came to that conclusion: but it think it makes sense to a certain degree.
Thanks again!

**Comment by minneapolis29** [comment]
I do appreciate the quick response and i don't take it for granted :)
