### ISSUE TITLE
Provisioning AD Application with Client Secret

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-azurerm#2619]
I have a setup where I provision an AKS cluster, a couple of AD applications and a few Kubernetes secrets on said AKS cluster all in the same setup. (Being able to do this is what makes Terraform awesome! 💯) However, I'm stuck on something that I don't know quite how to accomplish, and I can't find in the docs how to do it.

I want to provision an AD application with a Client Secret, and store the application's ID and secret in Kubernetes. I can get all the info I need about the application, except (naturally) the existing secrets, because they are write-only. The CLI seems to support this, through `az ad app update` with the `--password` flag:
```
--password                   : App password, aka 'client secret'.
```
and issuing `az ad app update --id <my-app-id> --password foobar --debug` shows that the `PATCH` request body includes the following property:
```
"passwordCredentials": [
  {
    "startDate": "2019-01-08T10:46:37.334155Z",
    "endDate": "2020-01-08T10:46:37.334155Z",
    "keyId": "89fef748-9f24-44d2-8ede-14477aaff058",
    "value": "foobar"
  }
]
```
Is this operation supported at all by terraform-azurerm? If not, would a PR that supports it be accepted even though #2322 is in the pipeline?

**Comment by tombuildsstuff** [comment]
hey @tomasaschan 

Thanks for opening this issue :)

>  If not, would a PR that supports it be accepted even though #2322 is in the pipeline?

As mentioned in #2322 we're currently working on splitting the AzureAD resources out into their own provider. We're currently working through the process of doing this (splitting out the repo, updating the docs/tests etc) - as such at this time we wouldn't accept a PR for that functionality in this repository unfortunately.

That said, we're pretty close to getting the split-out repository live (we're hoping to ship it this week) - once that's done (and the initial release is out) it should be possible to add support for this. We've just spun up [the repository for the AzureAD Provider here](https://github.com/terraform-providers/terraform-provider-azuread) - so I'd suggest watching that repository (or checking back later this week) for updates.

> Is this operation supported at all by terraform-azurerm?

Technically it should be at the moment (since the entire resource is `ForceNew`, the password will get deleted & re-added on change) - but it'll show up as a destroy/create on the plan. Providing there's an SDK for this API then it should be possible to update this - do you have the full URL being used?

Thanks!

**Comment by tomasaschan** [comment]
Makes perfect sense, thank you. I'll head over there and start watching for progress! :)

**Comment by tomasaschan** [comment]
PS: If there are any specific things you want/need help with on that, do log issues for them and tag with "intro-level" or something. If/when I have some extra time I can take a look and see if there's anything within reach for me.

**Comment by tombuildsstuff** [comment]
👍 will do - thanks @tomasaschan :)
