### ISSUE TITLE
resource "azurerm_automation_dsc_configuration" "lcm"

### ISSUE THREAD

**Issue by TheMoroccanBoss** [terraform-providers/terraform-provider-azurerm#2661]
Quick question about content_embedding in DSC config:
when i invoke sthg like this: it throws errors about syntax why? dsc.tf: At 38:55: literal not terminated
resource "azurerm_automation_dsc_configuration" "lcm" {
 ...
   content_embedded        = "configuration TestConfig 
{
    Node IsWebServer
    {
        WindowsFeature IIS
        {
            Ensure               = "Present"
            Name                 = "Web-Server"
            #IncludeAllSubFeature = $true
        }
    }   
}"

**Comment by TheMoroccanBoss** [comment]
is there to embed a ps1 script right within the content_embedded statement?
Thanks again guys!

**Comment by tombuildsstuff** [comment]
hey @TheMoroccanBoss 

Thanks for opening this issue :)

Terraform supports the use of [HEREDOC syntax](https://infinum.co/the-capsized-eight/multiline-strings-ruby-2-3-0-the-squiggly-heredoc) to store information on multiple lines, for example:

```

resource "azurerm_automation_dsc_configuration" "foo" {
  # ...
  content_embedded = <<BODY
configuration TestConfig
{
  Node IsWebServer
  {
    WindowsFeature IIS
    {
      Ensure = "Present"
      Name = "Web-Server"
      #IncludeAllSubFeature = $true
    }
  }
}
BODY
}
```

In the example above the `<<BODY` represents the start of the HEREDOC syntax (although `BODY` could be replaced with any word) and the trailing `BODY` is where the line ends (as such any information between the two `BODY`'s is returned).

Alternatively you can source the file contents from an external file using [the `file` interpolation syntax](https://www.terraform.io/docs/configuration/interpolation.html#file-path-), for example: `foo = "${file("./path/to/file")}`.

Would you be able to take a look and see if either of these approaches works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment (however we'll continue responding 😄)

Thanks!
