### ISSUE TITLE
AuthorizationFailed azurerm

### ISSUE THREAD

**Issue by rnkhouse** [terraform-providers/terraform-provider-azurerm#2678]
I am using below code to connetc with azurerm.

    variable "subscription_id" {default = "xxxxx-xxxxx-xxxxx-xxxxx-xxxxx"}
    provider "azurerm" {
      version         = "=1.21.0"
      subscription_id = "${var.subscription_id}"
      client_id       = "xxxxx-xxxxx-xxxxx-xxxxx"
      client_secret   = "000000000000000000000000000000"
      tenant_id       = "yyyyy-yyyyy-yyyyy-yyyyy"
    }
    resource "azurerm_resource_group" "test" {
      name     = "testaks"
      location = "East US"
    }

Error on `terraform plan`:

    * provider.azurerm: Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxxxx-xxxxx-xxxxx-xxxxx' with object id 'xxxxx-xxxxx-xxxxx-xxxxx' does not have authorization to perform action 'Microsoft.Resources/subscriptions/providers/read' over scope '/subscriptions/xxxxx-xxxxx-xxxxx-xxxxx-xxxxx'."

I checked all permissions are given correctly. I also tried by creating new application in AAD.

**Comment by tombuildsstuff** [comment]
hi @rnkhouse 

Thanks for opening this issue :)

Taking a quick look into this - it appears the Service Principal has been created (and authenticates correctly) - however it doesn't have permissions to the Subscription which you're trying to use. The [information in this section should help you grant the Service Principal the necessary permissions to the Subscription](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html#3-granting-the-application-access-to-manage-resources-in-your-azure-subscription) - would you be able to take a look and see if that works for you?

Since this is a question regarding configuration within Azure I'm going to close this issue for the moment - but please let us know if that doesn't solve your issue and we'll take another look :)

Thanks!
