### ISSUE TITLE
auth-mode login for azurerm backend

### ISSUE THREAD

**Issue by bentterp** [terraform-providers/terraform-provider-azurerm#2730]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The new login auth-mode allows us to get rid of shared keys for azurerm storage, including backend.

### New or Affected Resource(s)

* backend = "azurerm"

### Potential Terraform Configuration

```hcl
data "terraform_remote_state" "foo" {
  backend = "azurerm"
  config {
    storage_account_name = "terraform123abc"
    container_name       = "terraform-state"
    key                  = "prod.terraform.tfstate"
  }
}
```

### References

* ```az storage blob download  --auth-mode login  --account-name terraform123abc --container-name terraform-state --name prod.terraform.tfstate --file -```

**Comment by bentterp** [comment]
Hmmm.. I think we need to provide the subscription ID also
```arm_subscription_id```

**Comment by tombuildsstuff** [comment]
hey @bentterp 

Thanks for opening this issue :)

We've been working on adding some additional authentication methods to the AzureRM backend in the next version of Terraform Core (v0.12), in current releases (0.11.x) of the AzureRM backend [we support authenticating using either the Storage Account Key or a Service Principal (with a Client Secret)](https://www.terraform.io/docs/backends/types/azurerm.html).

In addition to those methods - we've been working to add support in the upcoming 0.12 release of Terraform Core for the following authentication methods for the AzureRM Backend:

* the Azure CLI (v2 / `az`)
* Managed Service Identity
* a SAS Token

All of these methods are available in the Terraform 0.12 (alpha) today ([there's some documentation on this here, although it won't be on the website until 0.12 is fully released](https://github.com/hashicorp/terraform/blob/master/website/docs/backends/types/azurerm.html.md)) and will be available in any subsequent versions of Terraform Core. We're also looking to add support for a Service Principal using a Client Certificate ([there's a WIP PR for that here](https://github.com/hashicorp/terraform/pull/19606)) before the final release of 0.12 too.

My understanding is that this should be resolved by these upcoming changes since you can use the Azure CLI for authentication - would you be able to take a look and see if that would work for you?

Thanks!

**Comment by bentterp** [comment]
@tombuildsstuff Looks very promising, indeed! If I have more than one subscription associated with my login, should we specifiy subscription id? Storage account names are globally unique, but I'd guess that they can only be seen from the subscription where they belong.

I have become highly dependent on the terraform_remote_state data resource to pass information between configurations and across subscriptions/accounts :-D

Maybe it's time for me to start testing the 0.12 release - I had promised myself to wait for the second beta but .....

**Comment by tombuildsstuff** [comment]
@bentterp 

> @tombuildsstuff Looks very promising, indeed! If I have more than one subscription associated with my login, should we specifiy subscription id? Storage account names are globally unique, but I'd guess that they can only be seen from the subscription where they belong.

If you're using the Azure CLI/MSI etc to authenticate then yes - if a SAS Token/Storage Account Key is used I believe it's not required. There's examples of both in the documentation to try and make that clearer, since there's a lot of different combinations available :)

> Maybe it's time for me to start testing the 0.12 release - I had promised myself to wait for the second beta but .....

The current release of 0.12 is an Alpha, which comes pre-bundled with certain Providers (which are slightly older versions at this point) - as such be aware there's still bugs/rough-edges (so whilst it's useful to try out at this stage, I'd probably suggest not using it in Production at this time).

Since this question appears to be resolved I'm going to close this issue for the moment - but please feel free to raise any issues/bugs you find with the AzureRM Backend on [the Terraform Core repository](https://github.com/hashicorp/terraform/issues) and we'll take a look :)

Thanks!
