### ISSUE TITLE
Managing Azure users with terraform 

### ISSUE THREAD

**Issue by MovieStoreGuy** [terraform-providers/terraform-provider-azurerm#2739]
I am trying to figure out how to add external users that are part of my organisation into azure using terraform. 

I was wondering if it is possible and how I would do it?
The documentation isn't that great so an example would be most helpful.

**Comment by tombuildsstuff** [comment]
hey @MovieStoreGuy 

Thanks for opening this issue :)

Whilst we originally shipped AzureAD resources inside of the AzureRM Provider - we've recently moved these out into their own Provider so we're able to iterate on them (and track milestones/demand etc) separately. As part of this we're only adding new AzureAD resources in [the AzureAD Provider](https://github.com/terraform-providers/terraform-provider-azuread), rather than in this repository.

There's [an issue (and a PR) on the AzureAD Repository tracking support for managing Users in AzureAD through a new resource `azuread_user`](
https://github.com/terraform-providers/terraform-provider-azuread/issues/) which I'm going to close this in favour of - would you mind subscribing to that issue for updates?

Thanks!

**Comment by MovieStoreGuy** [comment]
Why not make all of these providers just one simple provider?
