### ISSUE TITLE
[feature request] Conditional frontend_ip_configuration in azurerm_lb

### ISSUE THREAD

**Issue by mwieczorek** [terraform-providers/terraform-provider-azurerm#274]
Most of the loadbalancer 'components' (like rule, probe, etc) are separate resources.
So you can manage them and create conditionally (with count).
But the frontend_ip_configuration is 'inside' azurerm_lb so it cannot be conditional.

Do you consider to make it conditional? 
F.e. is it possible to extract it to another resource? Or add some kind of argument like 'enabled=true/false'?

**Comment by jodok** [comment]
+1

**Comment by tombuildsstuff** [comment]
hi @mwieczorek @jodok 

Thanks for opening this issue - apologies for the delayed response here!

The `frontend_ip_configuration` block is required in Terraform since it's required in the Azure API - and as such we're unable to apply the same technique to this block that we have to the other resources (like rules/probes).

As such - we're unable to support this functionality until it's supported by the Azure API - instead I'd suggest opening a feature request on [the Azure Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs) where the API team can then look to support this in the future (initially creating a LB without a frontend IP configuration - and then adding them incrementally); in the interim I'm going to close this issue, but we'll look to support this behaviour should the API allow this in the future.

Thanks!
