### ISSUE TITLE
 terraform plan fails with Error building AzureRM Client: Authorisation Profile was not found

### ISSUE THREAD

**Issue by pricoppd** [terraform-providers/terraform-provider-azurerm#2751]
I have created a new release in Azure DevOps, i'm using MS build agent to run three steps, all from Powershell.

1. install terraform
2. run terraform init
3. terraform plan

Step 3 fails with  * provider.azurerm: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

the provider template is 2.0.0
the provider azurerm is 1.21.0

Any idea?

**Comment by tombuildsstuff** [comment]
hi @pricoppd 

Thanks for opening this issue :)

It appears the Build Agents are logged into the Azure CLI using a Service Principal - which we don't support since some required information isn't present (we only support authenticating using the Azure CLI as a regular user). Instead when authenticating using a Service Principal we require that the credentials are either specified as Environment Variables or in-line - there's more information (and examples) [in this guide](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html) - would you be able to take a look and see if that works for you?

Since this is a question regarding configuring Terraform rather than a bug I'm going to close this issue for the moment (but we'll continue responding 😄)

Thanks!
