### ISSUE TITLE
Runbook Creation in 1.21 give  StatusCode=404 -- Original Error: Code="ResourceNotFound"

### ISSUE THREAD

**Issue by cp3hu** [terraform-providers/terraform-provider-azurerm#2811]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_automation_runbook`

### Terraform Configuration Files

```hcl

data "local_file" "startup_ps1" {
  filename = "${path.module}/startup.ps1"
}

resource "azurerm_automation_account" "automation_account" {
  name                = "test123456"
  location             = "North Europe"
  resource_group_name = "XXX"
  sku {
    name = "Basic"
  }
}

resource "azurerm_automation_runbook" "runbook_test" {
  name                = "test123456"
  location             = "North Europe"
  resource_group_name = "XXX"
  account_name              = "test"
  log_verbose                  = "true"
  log_progress                 = "true"
  description                     = "Runbook for Starting VM"
  runbook_type                = "PowerShell"
  publish_content_link {
    uri = "${azurerm_storage_blob.automation_start_script.url}"
  }
  content = "${data.local_file.startup_ps1.content}"
}


```

### Debug Output

```shell
* azurerm_automation_runbook.runbook_start: Error setting the draft Automation Runbook "test123456" (Account "test123456" / Resource Group "XXX"): automation.RunbookDraftClient#ReplaceContent: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/test123456/runbooks/test123456' under resource group 'XXX' was not found."

```

### Expected Behavior

Runbook should be created 

### Actual Behavior

Looking for the creating  runbook which doesn't exist

### Steps to Reproduce

1. `terraform apply`

### References

Seems to be related to https://github.com/terraform-providers/terraform-provider-azurerm/issues/1980.
But setting the blob container doesn't make it works.

* #0000

**Comment by tombuildsstuff** [comment]
hey @cp3hu 

Thanks for opening this issue :)

Dependencies between resources can be specified in one of two ways - either as Implicit Dependencies or Explicit Dependencies - if neither of these exists Terraform infers there's no dependencies between these resources and can create them in any order, which is the error you're seeing above.

Terraform's Interpolation Syntax can be used to pass values between Resources, which makes an Implicit Dependency between the two resources, such that the account would be created before the Runbook. There's an example of this below:

```hcl
data "local_file" "startup_ps1" {
  filename = "${path.module}/startup.ps1"
}

resource "azurerm_automation_account" "automation_account" {
  name                = "test123456"
  location             = "North Europe"
  resource_group_name = "XXX"
  sku {
    name = "Basic"
  }
}

resource "azurerm_automation_runbook" "runbook_test" {
  name                = "test123456"
  location             = "${azurerm_automation_account.automation_account.location}"
  resource_group_name = "${azurerm_automation_account.automation_account.resource_group_name}"
  account_name              = "${azurerm_automation_account.automation_account.name}"
  # ...
}
```

More information on [Interpolation Syntax can be found in this document](https://www.terraform.io/docs/configuration/interpolation.html) - however in the example above this means that the Account will be created before the Runbook (and the values will be passed through).

It's possible to instead use an Explicit Dependency between resources using the `depends_on` attribute:

```hcl
data "local_file" "startup_ps1" {
  filename = "${path.module}/startup.ps1"
}

resource "azurerm_automation_account" "automation_account" {
  name                = "test123456"
  location             = "North Europe"
  resource_group_name = "XXX"
  sku {
    name = "Basic"
  }
}

resource "azurerm_automation_runbook" "runbook_test" {
  name                = "test123456"
  location             = "North Europe"
  resource_group_name = "XXX"
  account_name              = "test"
  # ...
  depends_on = ["azurerm_automation_account.automation_account"]
}
```

Whilst this approach works we'd generally recommend making use of an Implicit Dependency where possible since this allows for passing values between resources, reduces the total lines of code needed (vs explicit dependencies) and allows you to specify/change variables in a single place.

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment - however would you be able to take a look and see if using an Implicit Dependency works for you?

Thanks!

**Comment by cp3hu** [comment]
Weirdly event if the account is already created, the error still the same.
I've to create the runbook first to be able to push configuration using terraform.
