### ISSUE TITLE
Terraform allows creating windows/linux app service plans in same resource group

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-azurerm#2840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Bug description

Although I cannot fathom why, there's a limitation on Azure that you cannot provision app service plans with different OS configurations (Windows/Linux) in the same resource group. For example, the third command below fails:

```sh
$ az group create -n test-group # ok
$ az appservice plan create -n test-linux -g test-group --is-linux # ok
$ az appservice plan create -n test-windows -g test-group # fails:
The requested app service plan cannot be created in the current resource group
because it is hosting Linux apps. Please choose a different resource group or
create a new one.
```

However, Terraform happily applies the following config:
```hcl
resource "azurerm_resource_group" "test" {
  name     = "test-group"
  location = "westeurope"
}

resource "azurerm_app_service_plan" "linux" {
  name                = "test-linux"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  sku = {
    tier = "Standard"
    size = "S1"
  }

  kind     = "Linux"
  reserved = true
}

resource "azurerm_app_service_plan" "windows" {
  name                = "test-windows"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  sku = {
    tier = "Standard"
    size = "S1"
  }

  kind     = "Windows"
  reserved = true
}
```

The result of applying this config is that two service plans are created, with the OS determined (as far as I can tell) by which one was created first. The easiest way to control this is to do 

```
$ terraform apply -target azurerm_resource_group.test
$ terraform apply -target azurerm_app_service_plan.linux
$ terraform apply -target azurerm_app_service_plan.windows # should fail, but doesn't
```

If you now look at the created resources, both are linux service plans. Terraform realizes this if you do `terraform plan` or `terraform apply`  again, and suggests re-creating the windows plan to switch OS, and going through with that does tear down and create a new service plan - but again, with Linux.

Since this is a limitation in Azure itself, I don't think there's anything the provider can do to support the config above, but I think it should at least error out instead of silently creating a different resource than what the user asked for.

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11
+ provider.azurerm v1.21.0

**Comment by tombuildsstuff** [comment]
hey @tomasaschan 

Thanks for opening this issue :)

Taking a look into this / jotting some thoughts down - whilst we could potentially look into locking on the name of the Resource Group being used by the App Service Plan here (which would allow us to verify the other App Service Plans in the Resource Group at creation time). That said this would have the effect of slowing resource creation for other App Service Plans within the same Resource Group, such that I'm wondering if it'd be better to document this behaviour, so that users are aware of this behaviour in the interim.

Thanks!

**Comment by tomasaschan** [comment]
Hm. Yeah, depending on the size of the perf penalty that would bring, it might be a little too defensive - but OTOH I think documenting this but leaving the functionality as-is is too permissive. There should, at the very least, be a warning at the end that says "the resource we provisioned was not the one you asked for", but I'd much rather have it actually fail.

What kind of lock are we talking about on the resource group? For how long would one need to lock it to improve behavior?

**Comment by neil-yechenwei** [comment]
After do more testing, I found maybe the root cause is that service api would always create linux app service plan even if the kind field sets to "Windows/App/elastic/FunctionApp/xenon" and the Reserved field sets to true. I assume it doesn't make sense. It should throw error message if it doesn't allow this kind of scenario. So I filed an issue on Azure/azure-rest-api-specs#10067.
