### ISSUE TITLE
Issue with local-exec - az login required

### ISSUE THREAD

**Issue by Gogeta094** [terraform-providers/terraform-provider-azurerm#2864]
Having issue with running az cli script using local-exec provisioner.
Receive next error:
ERROR: Please run 'az login' to setup account
I'm running terraform using VSTS task - https://marketplace.visualstudio.com/items?itemName=petergroenewegen.PeterGroenewegen-Xpirit-Vsts-Release-Terraform
Every other(terraform native) resources are successfully created.

Is there any possibility to run azure cli using local-exec without logging in?
As account is already specified in VSTS task - it seems obvious for me, that command should run in context of that account.

**Comment by MattMencel** [comment]
What are you trying to do in your `az cli` script?

I use `az cli` in my Terraform pipelines in AzDO, but not using local-exec.

**Comment by Gogeta094** [comment]
I'm trying to create/update Cosmos DB collections, unless there is some better way to do it?
How you're using `az cli` in terraform then? Could, you, please elaborate?

**Comment by tombuildsstuff** [comment]
hi @Gogeta094

Thanks for opening this issue :)

Since Terraform is just shelling out to the Azure CLI here (and as such should be reusing the same credentials) - I believe this question may be better answered by the plugin maintainers. As such I'm going to close this in favour of the other issue you've opened on the plugin repository: https://github.com/XpiritBV/Xpirit-Vsts-Release-Terraform/issues/18

Thanks!

**Comment by Gogeta094** [comment]
Hi,
I just investigated plugin repository code - and it's using terraform init with backend config options.
I've tried the same locally - initialize terraform with tenant, clientid, client secret and subscription id - and issue reproduces, az cli in context of "local-exec" asks for login. 
Is this expected behavior?

**Comment by tombuildsstuff** [comment]
@Gogeta094 

> Is this expected behavior?

Yes, in that instance there's no credentials configured for the Azure CLI (in the default location), so you'll need to ensure those are set prior to calling it.

It's possible that Azure DevOps is overriding the default location used by the Azure CLI (on a per-build basis) - as such we'd recommend using an ARM Template (deployed using the `azurerm_template_deployment` resource), rather than the Azure CLI if the functionality isn't supported by Terraform, since this allows the same credentials to be reused.

**Comment by MattMencel** [comment]
@Gogeta094 I've stopped using the third party Terraform plugin in AzDO and just run everything natively.... it's off topic for this provider, but maybe this YAML example will help you...

```
steps:
- script: |
   az login --service-principal -u $(SPN-ID) -p $(SPN-SECRET) --tenant $(TENANT-ID)
   ACCESS_KEY=`az storage account keys list -n $(STORAGE_ACCT) -o json | jq -r '.[0].value'`
   echo "##vso[task.setvariable variable=ACCESS_KEY]$ACCESS_KEY"
  displayName: 'AZ Login and Set ACCESS_KEY'

- script: |
   cat << EOT >> terraform.tfvars
   access_key = "$(ACCESS_KEY)"
   tenant_id = "$(TENANT-ID)"
   subscription_id = "$(SUBSCRIPTION-ID)"
   client_id = "$(SPN-ID)"
   client_secret = "$(SPN-SECRET)"
   EOT
  workingDirectory: '$(terraform.path)'
  displayName: 'Create terraform.tfvars'

- script: |
   terraform init -backend-config=resource_group_name=$(RES_GRP) -backend-config=storage_account_name=$(STORAGE_ACCT) -backend-config=container_name=tf-statefiles -backend-config=key=$(state.key) -backend-config=access_key=$(ACCESS_KEY) -no-color -input=false
   terraform plan -out=tfplan -no-color -input=false
  displayName: 'Terraform Plan'
  workingDirectory: '$(terraform.path)'
  enabled: true
```

I've found I have better success doing it this way than using the plugins.

Hope that helps you.

**Comment by ahmedig** [comment]
So I had a look at the extension, and they fortunately save the Azure SPN info into environment variables.
Try this, it works!

```
$subscriptionId = $env:ARM_SUBSCRIPTION_ID
$tenantId = $env:ARM_TENANT_ID
$clientId = $env:ARM_CLIENT_ID
$secret = $env:ARM_CLIENT_SECRET

az.cmd login --service-principal --username $clientId --password $secret --tenant $tenantId
```
