### ISSUE TITLE
Azurerm_mssql_elasticpool. It is not possible to use the same resource and switch between DTU and vCore

### ISSUE THREAD

**Issue by jcmaasb** [terraform-providers/terraform-provider-azurerm#2867]
### Versions:
```hcl
Terraform v0.11.11
provider.azurerm v1.22.0
```

Hi Team,
I have been waiting for the new option of **max_size_mb** for the **resource azurerm_mssql_elasticpool** that has come out with azurerm v1.22.0 to use this resource, but I have found another problem.

In the portal it is possible to reconfigure this resource to be able to select between DTU-Based (basic, standard, premium) and vCore-Based, (general purpose, Business Critical and Gen4 / 5).

Starting with a sku_tier DTU-Based (StandardPool) configuration, sku_family can not be specified:

```hcl
Error: Error running plan: 1 error(s) occurred:

* module.sql_bigcip.azurerm_mssql_elasticpool.test: 1 error(s) occurred:

* module.sql_bigcip.azurerm_mssql_elasticpool.test: Invalid attribute 'family'(Gen4) for service tier 'Standard', remove the 'family' attribute from the configuration file
```

```hcl
resource "azurerm_mssql_elasticpool" "test" {
  count               = "${local.create_ep == 1 ? "${local.create_ep}" : 0}"
  name                = "${local.elastic_pool_name}"
  resource_group_name = "${local.rg_name}"
  location            = "${local.location}"
  server_name         = "${local.server_name}"
  max_size_gb         = 100

  sku {
    name     = "StandardPool" 
    capacity = "100" 
    tier     = "Standard"  
    family   = ""  # --> must be omitted for DTU-Based, which implies a different resource if you want to migrate to vCore-Based?
  }

  per_database_settings {
    min_capacity = 0
    max_capacity = 50
  }

  tags {
    environment = "${local.environment}"
  }
}
```

This implies that I need two resources if I need to change the sku_tier between DTU and vCores, or **_destroy/create_** the resource.

If there is no impediment to do so from the portal, it does not make sense to include it in Terraform.
I think terraform should control this situation, is it possible?

_Update:
I forgot to comment that this situation does not happen with the previous version of provider azurerm._

Thanks!!

**Comment by jeffreyCline** [comment]
@jcmaasb Thank you for opening this issue. This is by design as a **DTU** based Elasticpool SKU does not support the family attribute, the family attribute in a **vCore** based Elasticpool refers to the type of hardware is to be used by the Elasticpool, as seen in the list below.

* `Gen4` - Up to 24 logical CPUs based on Intel E5-2673 v3 (Haswell) 2.4 GHz processors, vCore = 1 PP (physical core), 7 GB per core, attached SSD
* `Gen5` - Up to 80 logical CPUs based on Intel E5-2673 v4 (Broadwell) 2.3 GHz processors, vCore=1 LP (hyper-thread), 5.1 GB per core, fast eNVM SSD

Removing the family attribute from the configuration file does not create multiple resources, it only operates on the single existing Elasticpool resource. The reason you do not see this on the Portal is because it does this modification behind the scenes for you when making the call to the API.
