### ISSUE TITLE
azurerm_private_ip 'allocation_method' is named different

### ISSUE THREAD

**Issue by tkoeck** [terraform-providers/terraform-provider-azurerm#2876]
Hi,

the attribute

allocation_method

for the resource azurerm_private_ip doesn't work anymore. You have to write

public_ip_address_allocation = "Dynamic"

You should update the documentation at

https://www.terraform.io/docs/providers/azurerm/r/public_ip.html

**Comment by tombuildsstuff** [comment]
hi @tkoeck 

Thanks for opening this issue :)

This renamed field [was introduced in v1.21 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1210-january-11-2019) - as such it won't exist in an earlier version of the provider (which is why you're seeing this error).

You should be able to upgrade the version of the Azure Provider you're using by pinning the version, for example:

```hcl
provider "azurerm" {
  version = "=1.22.0"
}
```

.. and then re-running `terraform init` which will ensure this version of the AzureRM Provider is being used. Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment

Thanks!
