### ISSUE TITLE
azurerm_app_service_plan kind deploys linux when windows is defined

### ISSUE THREAD

**Issue by BradAF** [terraform-providers/terraform-provider-azurerm#2889]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.22.0
+ provider.null v2.0.0

### Affected Resource(s)

* `azurerm_app_service`

### Terraform Configuration Files

```hcl
provider "azurerm" {
        use_msi = true
        subscription_id = "<redacted>"
}

resource "azurerm_resource_group" "tf_rg" {
        name = "DELETEME"
        location = "West Europe"
}

resource "azurerm_app_service_plan" "tf_app_plan" {
    name                = "DELETEME_plan"
    resource_group_name = "DELETEME"
    location            = "West Europe"
    kind                = "windows"

    sku {
        tier = "Standard"
        size = "S1"
    }

    properties {
        reserved = "true"
    }
}

```

### Debug Output

https://gist.github.com/BradAF/cf538b1bdab3d9f6a95de094459d025d

### Expected Behavior

An Azure Application Service Plan of kind 'windows' should have been deployed.

### Actual Behavior

An Azure Application service Plan of kind 'linux' was deployed. Subsequent terraform apply or terraform plan commands show that it recognizes the wrong kind was deployed and wants to re-create the resource. It attempts to re-create resource as kind 'windows' but it is always deployed as 'linux'.

### Steps to Reproduce

1. `terraform apply`
2. Verify resources are being created of kind `windows`.
3. Note deployed resource kind.
3. `terraform apply`
4. Note that terraform immediately sees that the resource needs to be recreated with kind 'windows'
5. Verify resources are being created of kind `windows`
6. Note deployed resource kind.

### Important Factoids

N/A

### References

N/A

* #0000

**Comment by tombuildsstuff** [comment]
hi @BradAF 

Thanks for opening this issue :)

Taking a look into this there's a couple of oddities in Azure regarding App Services which I believe are potentially relevant here:

The first is that the casing of the `sku` field in certain API's is case-sensitive for new resources (but can be case-insensitive for older resources); for example in this case I believe updating `windows` to `Windows` may solve this. Unfortunately where older/existing resources allow a different casing to be used, this means that Terraform's validation has to be slightly more lax here than we'd otherwise ideally allow.

Secondly for whatever reason Azure requires that if multiple App Service Plans are provisioned in the same Resource Group, that they all share the same operating system type (which was discovered recently) as otherwise the incorrect OS gets provisioned.

Out of interest, would you be able to take a look and confirm the following:

1. is this the only App Service Plan provisioned within the Resource Group?
2. does switching the casing of the `sku` from `windows` to `Windows` solve this for you?

Thanks!

**Comment by BradAF** [comment]
Hi @tombuildsstuff! I apologize for the delay.

1. Yes, in both the larger deployment I noticed the bug and in this specific test Resource Group, it was the only App Service Plan provisioned.

2. Unfortunately, no - I attempted to change the case and I am seeing the same issue. I have included the snippet with the loop using the uppercase sku:
![image](https://user-images.githubusercontent.com/11336928/53354483-d8ae7b80-38f4-11e9-870c-c0d559087e48.png)

**Comment by BradAF** [comment]
Is there anything else you're waiting for from me to continue, or any additional information I could provide?

**Comment by a138076** [comment]
@BradAF when have you tried `kind = "App"`

That is currently working for me

**Comment by BradAF** [comment]
Hi @a138076; I just tried to use App for deployment, and I am getting the same issue.
Deploy from scratch, it creates a linux app service plan, do terraform plan and it detects that it has deployed the kind and wants to switch to App, ad infinitum.

**Comment by sohansc** [comment]
this will work if you change 
reserved = "false"

"NOTE: When creating a Linux App Service Plan, the reserved field must be set to true, and when creating a Windows/app App Service Plan the reserved field must be set to false."
