### ISSUE TITLE
azurerm subnet network security group association - List issue

### ISSUE THREAD

**Issue by rjbartson** [terraform-providers/terraform-provider-azurerm#2895]
When using count with the azurerm_network_security_group_association and using an output variable from a different module, I get the error message "should be type sting, got list". 
This exact same method works in other resources with the same logic. Any help would be great!

### Terraform (and AzureRM Provider) Version

Terraform v0.11.11
+ provider.azurerm v1.21.0

### Affected Resource(s)

azurerm_subnet_network_security_group_association

### Terraform Configuration Files######
main - 
module "Security" {
  source             = "././Azure/Security"
  vnet_name          = "${module.Network.network_vnet_name}"
  rg_name            = "${module.Network.network_rg_name}"
  vnet_address_space = "${var.global_vnet_address_space}"
  **subnetid           = "${module.Network.network_subnet_id}"**
}
###############
network - main - 
output "network_subnet_id" {
  **value = "${azurerm_subnet.subnet.*.id}"**
}
###############
security - main -
resource "azurerm_subnet_network_security_group_association" "nsg-subnet" {
  count                     = "${length(var.vnet_name)}"
  **subnet_id                 = "${element(var.subnetid, count.index)}"**
  network_security_group_id = "${element(azurerm_network_security_group.nsg.*.id, count.index)}"
}

### Expected Behavior

3 subnets associate to 3 network security groups.

### Actual Behavior
* module.Security.var.subnetid: variable subnetid in module Security should be type string, got list

**Comment by tombuildsstuff** [comment]
hi @rjbartson 

Thanks for opening this issue :)

It's hard to tell for sure without seeing the complete code here - however I believe this is due to the variable `subnetid` within the `Security` module not having the type set, since by default (unless you set a default value/type otherwise) Terraform assumes this is a string value.

As such I believe you should be able to set the type of the variable defined within the `Security` module to be a list, which should allow this to work - for example:

```hcl
variable "subnetid" {
  type = "list"
}
```

[More information on variables can be found in the documentation](https://www.terraform.io/docs/configuration/variables.html#type) - however this should allow you to then pass in a list as is being done above (presuming a List is being returned as an output from the other module) - would you be able to take a look and see if this works for you?

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look.

Thanks!
