### ISSUE TITLE
azurerm_network_interface network_security_group association

### ISSUE THREAD

**Issue by juanjojulian** [terraform-providers/terraform-provider-azurerm#2896]
Good morning,

I did a research on documentation and issues and couldn't find how to associate a Network Security Group and a Network Interface. Using the portal you can associate an NSG to a subnet or a NIC. Using Terraform you can associate an NSG to a subnet using "azurerm_subnet_network_security_group_association" resource, but you cannot associate an NSG to a NIC. Is there any reason for this? Am I missing something?.

Thanks!

**Comment by tombuildsstuff** [comment]
hi @juanjojulian 

Thanks for opening this issue :)

At this time it's possible to configure a link between a Network Interface and a Network Security Group in one of two ways - using [the `network_security_group_id` field on the `azurerm_network_interface` resource](https://www.terraform.io/docs/providers/azurerm/r/network_interface.html#network_security_group_id) and/or using [the `azurerm_network_interface_application_security_group_association` resource](https://www.terraform.io/docs/providers/azurerm/r/network_interface_application_security_group_association.html).

In current releases of the AzureRM Provider / prior to version 2.0 both resources are required to be used to link the Network Interface to the Network Security Group (this is to prevent breaking backwards compatibility) - however once 2.0 has been released you'll only need to use the `azurerm_network_interface_application_security_group_association` resource (since the deprecated `network_security_group_id` field within the `azurerm_network_interface` resource will be removed).

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by juanjojulian** [comment]
Thanks @tombuildsstuff I will make use of "network_security_group_id" argument in the "azurerm_network_interface" resource, I didn't know it was available.

Regarding "azurerm_network_interface_**application**_security_group_association" resource, please be aware that a Application Security Group and a Network Security Group is not the same, unfortunately there is no azurerm_network_interface_**network**_security_group_association resource available in AzureRM Terraform plugin and this is what I was looking for.

**Comment by bfleming-ciena** [comment]
So no plans to add a new resource...

azurerm_network_interface_network_security_group_association

?
