### ISSUE TITLE
Issue with nested attributes

### ISSUE THREAD

**Issue by tmonk42** [terraform-providers/terraform-provider-azurerm#292]
### Terraform Version
Terraform v0.10.2

### Affected Resource(s)
- azurerm_virtual_machine_scale_set
- azurerm_container_service

If this issue appears to affect multiple resources, it may be an issue with Terraform's core, so please mention this.

### Terraform Configuration Files
We used this as our starting point: https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html
```hcl
# Started with this:
network_profile {
    name    = "TestNetworkProfile"
    primary = true

    ip_configuration {
      name      = "TestIPConfiguration"
      subnet_id = "${azurerm_subnet.test.id}"
    }
  }

# Then tried to update to this:
network_profile {
    name    = "terraformnetworkprofile"
    primary = true

    ip_configuration {
      name                                   = "TestIPConfiguration"
      subnet_id                              = "${azurerm_subnet.test.id}"
      load_balancer_backend_address_pool_ids = ["${azurerm_lb_backend_address_pool.bpepool.id}"]
      load_balancer_inbound_nat_rules_ids    = ["${element(azurerm_lb_nat_pool.lbnatpool.*.id, count.index)}"]
    }
  }
```

### Panic Output
N/A

### Expected Behavior
For all attributes of resources, changing the value should result in TF plan showing a required change to the resource, and TF apply should update the resource.

### Actual Behavior
Running TF plan after changing any of the following "nested" attributes shows 'No changes. Infrastructure is up-to-date.' Running TF apply makes no changes to these existing resources.
- azurerm_virtual_machine_scale_set/os_profile_linux_config/ssh_keys/key_data
- azurerm_virtual_machine_scale_set/network_profile/ip_configuration/load_balancer_inbound_nat_rules_ids
- azurerm_container_service/linux_profile/ssh_key/key_data

### Steps to Reproduce
1. `terraform apply`
2. Change the value of os_profile_linux_config/ssh_keys/key_data
3. `terraform plan`
4. `terraform apply`
5. Notice that key_data did not change. 

### References
N/A

**Comment by tmonk42** [comment]
This looks to be a superset of the issue reported in #92 first reported in May before the provider split.

**Comment by harijayms** [comment]
Some of the data points in the API that are immutable currently and hence the terraform behavior, this should be addressed in the documentation.

**Comment by tombuildsstuff** [comment]
hi @tmonk42 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We've recently opened the PR for the first of these new resources #4518 - and I'm able to confirm that this bug is now fixed in the new Virtual Machine Scale Set resource - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine_scale_set` resource.

We've posted an update in #2807 with more information on this (we plan to release the new Virtual Machine / Virtual Machine Scale Set resources in a Beta form in a future 1.x version of the Azure Provider and subsequently release them as "GA" in 2.0) - but as we plan to post additional status updates for 2.0 in #2807 I'd suggest subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
