### ISSUE TITLE
Key Vault ID can not be found for key vault secret data source if in different subscription

### ISSUE THREAD

**Issue by r0bnet** [terraform-providers/terraform-provider-azurerm#2921]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
$ terraform -v
Terraform v0.11.11
+ provider.azurerm v1.22.1
```

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
data "azurerm_key_vault_secret" "dl_acr_pull_key" {
  name         = "<my_secret_name>"
  vault_uri    = "https://<my_key_vault>.vault.azure.net/"
}

resource "azurerm_app_service" "presenter_app_service" {
 ...

  app_settings {
    WEBSITES_ENABLE_APP_SERVICE_STORAGE = false

    DOCKER_REGISTRY_SERVER_URL      = "https://<my_acr_name>.azurecr.io"
    DOCKER_REGISTRY_SERVER_USERNAME = "<my_acr_user>"
    DOCKER_REGISTRY_SERVER_PASSWORD = "${data.azurerm_key_vault_secret.dl_acr_pull_key.value}"
  }
  ...
}
```

### Expected Behavior

Terraform should get the secret from the given key vault (permissions are all correct).

### Actual Behavior

Seems like Terraform can not get the id of the key vault.
```
module.data_lake.module.presenter.data.azurerm_key_vault_secret.dl_acr_pull_key: data.azurerm_key_vault_secret.dl_acr_pull_key: Unable to locate the Resource ID for the Key Vault at URL "https://<my_key_vault>.vault.azure.net/": %!s(<nil>)
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Key Vault is in a different subscription than the deployment (but same tenant).
I know that there was this PR by @katbyte that might have solved this issue for 1.22.1 but it doesn't work for me.

// Update:
Okay, i tested this with a key vault in the same subscription and this seems to work but it is not an option in my case. Is this by design? Since the `vault_uri` is going to be removed from the data source i think it won't work anyway in the future. But to my understanding it should work with ANY key vault no matter in which subscription.

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/pull/2891

**Comment by r0bnet** [comment]
Okay, i tested this with a key vault in the same subscription and this seems to work but it is not an option in my case. Is this by design? Since the `vault_uri` is going to be removed from the data source i think it won't work anyway in the future. But to my understanding it should work with ANY key vault no matter in which subscription.

**Comment by brennerm** [comment]
I'm experiencing the same issue. My guess is that in version 1.22 the approach changed from identifying the vault via it's URL to identifying it through it's ID. This assumes that the account that is used to execute Terraform and the vault are in one Azure subscription. If this is not the case resolving the vault's ID fails.   
Feel free to correct me if I'm wrong.

My current workaround is to use version 1.21.0 of the azurerm provider.
```
provider "azurerm" {
  version = "1.21.0"
}
```

**Comment by tombuildsstuff** [comment]
hi @r0bnet @brennerm 

Thanks for opening this issue - apologies to hear this has broken your workflow here

> Okay, i tested this with a key vault in the same subscription and this seems to work but it is not an option in my case. Is this by design?

Unfortunately this is an unintentional breaking change, since we were unaware that the Key Vault resources were being used in this manner (without using a separate Provider block to specify the Subscription which the Key Vault is in). That said, it's possible to achieve this by using [Multiple Instances of a Provider](https://www.terraform.io/docs/configuration/providers.html#multiple-provider-instances), like so:

```hcl
provider "azurerm" {
  subscription_id = "00000000-0000-0000-0000-000000000000"
  alias           = "other"
}

data "azurerm_key_vault_secret" "dl_acr_pull_key" {
  name         = "<my_secret_name>"
  vault_uri    = "https://<my_key_vault>.vault.azure.net/"
  provider     = "azurerm.other"
}
```

At which point you should then be able to use this in the Terraform Configuration as before (since the Service Principal/User being used has permission from before) - would you be able to take a look and see if that approach works for you?

Thanks!

**Comment by r0bnet** [comment]
Hi @tombuildsstuff,

just tried what you proposed and that works. I didn't even know about that solution with different providers tbh, thanks.

But nonetheless i get the deprecation warning with your approach but at least i could also pass in the id of the key vault with the `key_vault_id`. What do you think about how this is gonna be resolved in the future? Will the `vault_uri` property be not deprecated anymore in the data provider for the vault secret? Or will we have to live with the id in that case?

**Comment by tombuildsstuff** [comment]
hi @r0bnet 

> just tried what you proposed and that works. I didn't even know about that solution with different providers tbh, thanks.

Glad to hear this is working for you 👍 

> But nonetheless i get the deprecation warning with your approach but at least i could also pass in the id of the key vault with the `key_vault_id`. What do you think about how this is gonna be resolved in the future?

Just passing in the ID of the other subscription won't work - where this resource exists in a separate subscription you'll need to use a provider alias as shown above.

>  Will the `vault_uri` property be not deprecated anymore in the data provider for the vault secret? Or will we have to live with the id in that case?

Unfortunately the previously behaviour was unintentional - as such we don't plan to reintroduce this behaviour - and the `vault_uri` field will be removed in 2.0, such that you'll need to use the `key_vault_id` field going forwards.

As we don't plan to re-introduce this functionality and there's a workaround/this is working for you, I'm going to close this issue for the moment.

Thanks!

**Comment by jamesbannan** [comment]
@tombuildsstuff I'm hitting this issue as well, and this case the workaround isn't _quite_ working for me. In my case, I'm using a Service Principal in Azure AD Tenant 1 and attempting to write a new Key Vault secret to a Key Vault in Azure AD Tenant 2.

The Terraform configuration is authenticated using a Service Principal registered in Tenant 1. This SP has been configured as multi-tenant and has Reader rights in the subscription where the Key Vault is located and has permissions in the Key Vault via an access policy.

When attempting to write to the Key Vault, the Terraform configuration fails with the following:

`Unable to list provider registration status, it is possible that this is due to invalid credentials or the service principal does not have permission to use the Resource Manager API, Azure error: resources.ProvidersClient#List: Failure responding to request: StatusCode=401 -- Original Error: autorest/azure: Service returned an error. Status=401 Code="InvalidAuthenticationTokenTenant" Message="The access token is from the wrong issuer 'https://sts.windows.net/<AZURE_AD_TENANT_1>/'. It must match the tenant 'https://sts.windows.net/<AZURE_AD_TENANT_2>/' associated with this subscription. Please use the authority (URL) 'https://login.windows.net/<AZURE_AD_TENANT_2>'`

The Terraform configuration is:

`resource "azurerm_key_vault_secret" "key-vault-secret-WebAPI-id" {
  name          = "${azuread_application.WebAPI.name}-id"
  value         = "${azuread_application.WebAPI.application_id}"
  key_vault_id  = "/subscriptions/<SUB_IN_TENANT_2>/resourceGroups/<RESOURCE_GROUP>/providers/Microsoft.KeyVault/vaults/<VAULT_NAME>"
  provider      = "azurerm.<SUB_ALIAS>"
}`

I'm pretty sure that I've got the permissions covered, but if I'm missing something I don't know what it might be.

Any ideas would be gratefully received.
