### ISSUE TITLE
Documentation issue in resource 'azurerm_key_vault_secret'

### ISSUE THREAD

**Issue by ewierschke** [terraform-providers/terraform-provider-azurerm#2927]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.11.11

* provider.azurerm v1.21.0

### Affected Resource(s)

* `azurerm_key_vault_secret`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

azurerm_key_vault_secret documentation currently lists key_vault_id as the argument to identity within which key vault to create the key vault secret resource.  Attempting creation with that argument errors with: 
```hcl
Error: azurerm_key_vault_secret.test: "vault_uri": required field is not set

Error: azurerm_key_vault_secret.test: : invalid or unknown key: key_vault_id
```

DataSource documentation appears to have the correct argument required for the resource creation.

### References

* https://www.terraform.io/docs/providers/azurerm/r/key_vault_secret.html
* https://www.terraform.io/docs/providers/azurerm/d/key_vault_secret.html

**Comment by tombuildsstuff** [comment]
hey @ewierschke 

Thanks for opening this issue :)

The documentation on the Terraform Website is for the latest released version of the Azure Provider; as such at the time of writing this is for version v1.22.1. This field was introduced in v1.22.0 - as such it doesn't exist in v1.21.0 (which is why you're seeing this error) - and you'll need to use the `vault_uri` field instead. Would you be able to take a look and see if updating to the latest version works for you? You can pin this in your code by using the following provider block and then re-running `terraform init`:

```hcl
provider "azurerm" {
  version = "=1.22.1"
}
```

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look :)

Thanks!
