### ISSUE TITLE
azurerm_dns_a_record: Does it still exist?

### ISSUE THREAD

**Issue by bcline760** [terraform-providers/terraform-provider-azurerm#2930]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```bash
Terraform v0.11.11
+ provider.azurerm v1.22.1
+ provider.null v2.0.0
+ provider.random v2.0.0
+ provider.template v2.0.0
```

### Affected Resource(s)

* `azurerm_dns_a_record`

### Terraform Configuration Files

```hcl
resource "azurerm_dns_a_record" "splunk_a_record" {
  name                = "@"
  zone_name           = "${data.azurerm_dns_zone.dns_zone.name}"
  resource_group_name = "${data.azurerm_resource_group.dnszone_resource_group.name}"
  ttl                 = 1800
  records             = ["${azurerm_public_ip.splunk_waf_search_pip.ip_address}"]
}
```

### Debug Output
Can't. Contains sensitive items.

### Expected Behavior

No error about provider not supporting Azure DNS A record.

### Actual Behavior

`Error: module.splunk_waf.azurerm_dns_zone_a_record.name: Provider doesn't support resource: azurerm_dns_zone_a_record`

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

### References

* https://www.terraform.io/docs/providers/azurerm/r/dns_a_record.html

According to this, I should be able to create a DNS A record. Still true?

**Comment by tombuildsstuff** [comment]
hi @bcline760 

Thanks for opening this issue :)

Taking a look at the error message coming back from Terraform here:

> `Error: module.splunk_waf.azurerm_dns_zone_a_record.name: Provider doesn't support resource: azurerm_dns_zone_a_record`

From this error message it looks like you're trying to use a resource `azurerm_dns_zone_a_record` (which doesn't exist) as this resource is instead named `azurerm_dns_a_record`; as such I believe this may be a typo, would you be able to take a look and see if updating this works for you?

Since this is a question about Terraform Configuration rather than a bug in Terraform, I'm going to close this issue for the moment, however please let us know if that doesn't work for you and we'll take another look.

Thanks!
