### ISSUE TITLE
azurerm_kubernetes_cluster without service-principal or ssh_key

### ISSUE THREAD

**Issue by mfow** [terraform-providers/terraform-provider-azurerm#2931]
Both `service-principal` and `ssh_key` are mandatory parameters when creating a `azurerm_kubernetes_cluster`, although AKS supports creating a cluster without an SSH key, and automatically creating and destroying a service principal along with the cluster.

https://docs.microsoft.com/en-us/cli/azure/aks?view=azure-cli-latest#az-aks-create

# Expected behavior

The `service-principal` field in `azurerm_kubernetes_cluster` is optional.
The `ssh_key` field in `linux_profile` is optional.

**Comment by tombuildsstuff** [comment]
hi @mfow 

Thanks for opening this issue / apologies for the delayed response here!

The Azure Kubernetes Service API requires that a Service Principal & SSH Key are specified to provision the cluster; whilst Terraform could look to generate these this goes against Terraform's general approach of only provisioning the resources you've asked for. That said - Terraform supports dynamically creating both [Service Principals](https://www.terraform.io/docs/providers/azuread/r/service_principal.html) and [SSH Keys](https://www.terraform.io/docs/providers/tls/r/private_key.html) - so it should be possible to achieve this entirely within Terraform Configuration, such that Terraform will generate both a Service Principal and an SSH Key which should be used; would you be able to take a look and see if that works for you?

Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
