### ISSUE TITLE
azurerm_virtual_machine_extension should also accept azurerm_virtual_machine_scale_set_name under the list of supported arguments. 

### ISSUE THREAD

**Issue by sampcoug** [terraform-providers/terraform-provider-azurerm#2957]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently the 'azurerm_virtual_machine_extension' resource only supports 'virtual_machine_name' argument to specify the name of the virtual machine. This causes a problem for those who are using 'azurerm_virtual_machine_scale_set' resource to automate the deployment of the virtual machines in a set. 

Request is to add the  'azurerm_virtual_machine_scale_set_name' in the list of supported argument.

### New or Affected Resource(s)

azurerm_virtual_machine_extension, azurerm_virtual_machine_scale_set

### References

https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html

* #0000

**Comment by tombuildsstuff** [comment]
hi @sampcoug 

Thanks for opening this issue :)

Extensions for Virtual Machine Scale Sets are configured within the `azurerm_virtual_machine_extension` resource, rather than using the VM Extension resource which is instead intended for individual Virtual Machines (which are separate from VM's created in a Scale Set). [You can find an example for how to define an extension in the documentation](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html#identity_ids) - however since this resource is targeted towards Virtual Machines (and not Virtual Machine Scale Sets) at the Azure API level, unfortunately we're unable to add support for this as this separate resource.

In the future we've been considering splitting the `extension` section out of the `azurerm_virtual_machine_scale_set` resource as a part of [the changes coming in 2.0](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2807) - but that's a future development (and not available at this time).

Thanks!

**Comment by sampcoug** [comment]
Thanks tombuildsstuff! I guess I will have to use "azurerm_virtual_machine" resource for now because 'azurerm_virtual_machine_extension' is critical to my configuration. I am very much looking forward to the new change config in verison 2.0. Having a separate extension resource for virtual_machine_scale_set would certainly help.
