### ISSUE TITLE
Terraform destroying Azure resource with a management lock

### ISSUE THREAD

**Issue by cvandal** [terraform-providers/terraform-provider-azurerm#2959]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

After successfully creating an Azure resource with a corresponding management lock and then making a change to that resource which would require it to be re-created, I would expect the management lock to prevent the Azure resource from being destroyed. However, the management lock is removed, the Azure resource is destroyed, and then the Azure resource is re-created.

We cannot utilize the `prevent_destroy` meta parameter for a lifecycle because there's no way to use a variable for its value and we need to be able to toggle the value depending on whether we're creating or destroying an environment.

### Terraform (and AzureRM Provider) Version

* `terraform v0.11.11`
* `azurerm v1.22.1`

### Affected Resource(s)

* `azurerm_kubernetes_cluster`
* `azurerm_management_lock`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  name                = "${var.cluster_name}"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.aks.name}"
  dns_prefix          = "${var.dns_prefix}"
  kubernetes_version  = "${var.kubernetes_version}"

  lifecycle {
    ignore_changes = ["agent_pool_profile.0.count", "kubernetes_version"]
  }

  agent_pool_profile {
    name           = "${var.agent_pool_name}"
    count          = 2
    vm_size        = "Standard_B2ms"
    os_type        = "Linux"
    vnet_subnet_id = "${azurerm_subnet.aks.id}"
  }

  linux_profile {
    admin_username = "${var.admin_username}"

    ssh_key {
      key_data = "${var.key_data}"
    }
  }

  service_principal {
    client_id     = "${var.client_id}"
    client_secret = "${var.client_secret}"
  }

  role_based_access_control {
    enabled = true
  }

  network_profile {
    network_plugin = "azure"
  }

  tags {
    Environment = "${var.environment}"
  }
}

resource "azurerm_management_lock" "aks" {
  name       = "aks"
  scope      = "${azurerm_kubernetes_cluster.aks.id}"
  lock_level = "CanNotDelete"
  notes      = "Safety First!"
}
```

### Debug Output

N/A

### Panic Output

N/A

### Expected Behavior

Terraform should fail to destroy the Azure resource because it has a management lock.

### Actual Behavior

Terraform successfully destroys and then re-creates the Azure resource.

### Steps to Reproduce

1. `terraform apply`
2. Make a change to the Terraform template that would require the resource to be re-created. For example, changing the meta parameter `name` for the `azurerm_kubernetes_cluster` resource.
3. `terraform apply`

### Important Factoids

N/A

### References

N/A

**Comment by tombuildsstuff** [comment]
hi @cvandal 

Thanks for opening this issue :)

> After successfully creating an Azure resource with a corresponding management lock and then making a change to that resource which would require it to be re-created, I would expect the management lock to prevent the Azure resource from being destroyed. However, the management lock is removed, the Azure resource is destroyed, and then the Azure resource is re-created.

Where Terraform's managing the Management Lock (and there's no `prevent_destroy` attribute set within the `lifecycle` block) - Terraform believes that it can delete the Management Lock (as you're seeing). As you've mentioned the way to avoid this would be to use the `prevent_destroy` attribute within the `lifecycle` block to prevent Terraform from destroying this resource.

> We cannot utilize the `prevent_destroy` meta parameter for a lifecycle because there's no way to use a variable for its value and we need to be able to toggle the value depending on whether we're creating or destroying an environment.

I'm a little confused here, if you're creating the environment then setting `prevent_destroy` should be fine, in which case I believe this could be hard-coded to `true`? This would only be an issue when destroying - which providing the Management Lock isn't present prior to running `terraform plan|apply` should successfully delete the AKS cluster (since the deleted Lock would be detected during the `refresh` which happens during the `plan`/`apply`).

Support for using variables within the `lifecycle` block is being tracked in https://github.com/hashicorp/terraform/issues/3116 - since this issue appears to be requesting support for that I'm going to close this issue in favour of that one and suggest subscribing to that issue for updates.

Thanks!

**Comment by cvandal** [comment]
Hey @tombuildsstuff, 

Thanks for your reply!

Just to clarify, I'm not running `terraform destroy` and wondering why the `azurerm_kubernetes_cluster` resource is being destroyed despite the Azure management lock. I am just updating the `azurerm_kubernetes_cluster` in a way that would force it to be re-created, and then re-running `terraform apply`.

I would have expected Terraform to receive an error from the Azure API due to the lock.

**Comment by pawelpabich** [comment]
@tombuildsstuff, the issue you linked to was opened in 2015 and was locked in 2017. What does that mean ? I'm trying to figure out whether this feature has any chances of being implemented.

**Comment by tombuildsstuff** [comment]
@cvandal 

> Just to clarify, I'm not running `terraform destroy` and wondering why the `azurerm_kubernetes_cluster` resource is being destroyed despite the Azure management lock. I am just updating the `azurerm_kubernetes_cluster` in a way that would force it to be re-created, and then re-running `terraform apply`.
> I would have expected Terraform to receive an error from the Azure API due to the lock.

Got it - so because there's a dependency between the resources (insofar as the Management Lock uses the ID of the Kubernetes Cluster), Terraform knows that when the Kubernetes Cluster needs to be recreated that the Management Lock needs to first be removed and then re-added, which is why this is happening (and should show up in the plan). Adding the `prevent_destroy` attribute to the `lifecycle` block should be sufficient to prevent this :)

---

@pawelpabich 

> @tombuildsstuff, the issue you linked to was opened in 2015 and was locked in 2017. What does that mean ? I'm trying to figure out whether this feature has any chances of being implemented.

The issue's locked because we've got enough information from comments in the issue that we believe all of the use-cases are now covered; instead most of the more recent comments are duplicates/+1's - AFAIK there's plans to work on that, but I don't have a timeline unfortunately.

Thanks!

**Comment by akorp** [comment]
It seems to be inconsistent behaviour. When I create a  `resource "azurerm_resource_group"` which has a delete lock (`resource "azurerm_management_lock"` with the scope on this resource group), then when Terraform tries to delete this resource group I am getting error which asks to remove the lock first (Error `Status=409 Code="ScopeLocked"`)

But if in the similar way I create a `resource "azurerm_key_vault"` with `resource "azurerm_management_lock"` (scope of the lock on this key_vault), then Terraform removes lock without any warnings and delete key_vault. 

Does Terraform removes lock only for some resources?

Terraform v0.12.21
Azurerm v2.0.0
