### ISSUE TITLE
Support for AKS network policies

### ISSUE THREAD

**Issue by soggychipsnz** [terraform-providers/terraform-provider-azurerm#2961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The isolation of network traffic of pods is achieved via network policies.
This feature is currently in [preview ](https://docs.microsoft.com/en-us/azure/aks/use-network-policies)
To use these a few steps need to be taken

- EnableNetworkPolicy feature flag needs to be enabled for the subscription where you will create the AKS cluster
- The newly created AKS Cluster requires the Advanced networking/Azure CNI
- When creating the cluster using the AZ cli the '--network-policy calico' parameter needs to be set

Looking at the Terraform [azurerm_kubernetes_cluster](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html) provider, I see no mention of network policy. 
Is this feature on the cards?
Without network policies, there aren't any options to isolate differing pod workloads from one another.

Thanks in advance

**Comment by mbrancato** [comment]
#2987

**Comment by tombuildsstuff** [comment]
hey @soggychipsnz 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this as @mbrancato has mentioned support for this was added in #2987 which has since been merged - since this is available in the `azurerm_kubernetes_cluster` resource I'm going to close this issue for the moment; but please let me know if that doesn't work for you and we'll take another look.

Thanks!
