### ISSUE TITLE
Configuring HTTPS for app_service_custom_domain

### ISSUE THREAD

**Issue by tomasaschan** [terraform-providers/terraform-provider-azurerm#2962]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Since #1087 we have `azurerm_custom_hostname_binding`, but I can't figure out how to configure a HTTPS certificate for that binding. Is it possible? If so, how? If not, consider this a feature request! :)

**Comment by tombuildsstuff** [comment]
hey @tomasaschan 

Thanks for opening this issue :)

Support for this is blocked on Certificate support for App Services - which is being tracked in 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1136 - where once this is added we'll look to add this functionality. Rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of #1136 - would you mind subscribing to that one for updates?

Thanks!
