### ISSUE TITLE
Storage Account's Network Rules: Add parameter to enable Storage service endpoint in subnets

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#2978]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the Azure Portal for Storage Accounts, when adding a virtual network that is allowed access to the SA (_Firewalls and virtual networks_ section), the Portal allows you to enable the Storage service endpoint in the subnet if it detects that the subnet does not already have it enabled. Screenshot:

![2019-02-28 - sa enable svc endpoint](https://user-images.githubusercontent.com/3866191/53599895-40bfc480-3b76-11e9-8d32-8e44048546a0.png)

It would be great if the TF resource could do this as well.

### Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_account" "testsa" {
  name                = "sakjht1"
  resource_group_name  = "${var.rg}"

  ...

  network_rules {
    virtual_network_subnet_ids = [ "${data.azurerm_subnet.kjh-t1-vn-subnet1.id}" ]
    enable_service_endpoint = "true"   # I'm torn as to whether true/false should be the default
  }
```

**Comment by tombuildsstuff** [comment]
hi @kjhosein 

Thanks for opening this issue :)

Unfortunately the Azure Portal deviates from the Azure API somewhat insofar as this is actually updating the Network under the hood - rather than the other way around. Whilst we could look to allow this to be configured in both the Storage Account and Subnet resources - unfortunately this would lead to a circular reference where this would need to be configured in both places; as such unfortunately these need to live in one of the resources only.

In the future we may look to move this association into a Virtual Resource (as we have done for e.g. [Subnet <-> Network Security Group associations](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html)) - which would allow this to be configured outside of these resources, at present we have no plans to implement this.

Since we're unable to add support for the feature you're requesting here (due to it introducing a circular reference) - I'm going to close this issue for the moment.

Thanks!
