### ISSUE TITLE
Storage Account's Network Rules: Don't block access if `network_rules` block is present but effectively empty

### ISSUE THREAD

**Issue by kjhosein** [terraform-providers/terraform-provider-azurerm#2979]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

In the Storage Account resource, if the `network_rules {}` block is included (even if empty), then it turns on the _Allow Access from Selected Networks_. Of course, this blocks access. This is also not the default.

![2019-02-28_network-rules](https://user-images.githubusercontent.com/3866191/53602148-ea558480-3b7b-11e9-8320-eae8a36cdeb7.png)

Request: If the `network_rules` block is empty or the `ip_rules` or `virtual_network_subnet_ids` parameters are empty, don't change the default of "Allow access from All Networks".

Use case: an unknown # of rules (including none/zero) are being passed to a module, and the default should be left as is if the # is 0.

### Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration
Sample code:

```hcl
resource "azurerm_storage_account" "test" {
  name                = "sakjht1"
  ...

  network_rules {
  }
```

**Comment by tombuildsstuff** [comment]
hi @kjhosein 

Thanks for opening this issue :)

Terraform understands the presence of an optional block (such as the `network_rules` block in this case) to indicate that this element should be configured - as such unfortunately this change isn't one we're likely to implement. That said - it's possible to achieve what you're looking for in the upcoming Terraform 0.12 by passing `null` to the `network_rules` block conditionally.

> Use case: an unknown # of rules (including none/zero) are being passed to a module, and the default should be left as is if the # is 0..

Whilst I can't speak for this specific use-case - in general I'd recommend making modules that are as specific to a problem domain as you can, rather than wrapping the resource. An alternate approach here (which is compatible with Terraform 0.11) would be to have 2 resources for the `azurerm_storage_account` resource and conditionally toggle them on via a `count` metaparameter.

Thanks!
