### ISSUE TITLE
terraform import azurerm_subnet hangs with no error

### ISSUE THREAD

**Issue by ryanmckeague** [terraform-providers/terraform-provider-azurerm#3023]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.10
+ provider.azurerm v1.22.0

### Affected Resource(s)

* `azurerm_subnet`
* `terraform import`

### Terraform Configuration Files

`terraform import module.networking.azurerm_subnet.network_vnet1_subnet1" /subscriptions/[subscription]/resourceGroups/[resource group]/providers/Microsoft.Network/virtualNetworks/[virtual network]/subnets/[subnet]`

```
resource "azurerm_subnet" "network_vnet1_subnet1" {
  name                 = "${var.vnet1_subnet1_name}"
  virtual_network_name = "${var.vnet1_name}"
  resource_group_name  = "${var.rg1_name}"
  address_prefix       = "${var.vnet1_subnet1_address_prefix}"
}
```

### Expected Behavior

Existing subnet should have been imported to defined azurerm_subnet resource

### Actual Behavior

CLI hangs with a '>'

### Steps to Reproduce

1. `terraform import module.networking.azurerm_subnet.network_vnet1_subnet1" /subscriptions/[subscription]/resourceGroups/[resource group]/providers/Microsoft.Network/virtualNetworks/[virtual network]/subnets/[subnet]`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @ryanmckeague 

Thanks for opening this issue :)

Taking a look at this this appears to be because of an extra quote, and so your terminal (e.g. bash) is continuing to prompt (via the `>` symbol because it believes there's another quote needed. If you update this command to:

> terraform import module.networking.azurerm_subnet.network_vnet1_subnet1 /subscriptions/[subscription]/resourceGroups/[resource group]/providers/Microsoft.Network/virtualNetworks/[virtual network]/subnets/[subnet]

.. at which point this should work as expected - would you be able to take a look and see if that works for you? Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look :)

Thanks!
