### ISSUE TITLE
Azurem_app_service not recognizing virtual_network_name site_config key 

### ISSUE THREAD

**Issue by davidlbyrne** [terraform-providers/terraform-provider-azurerm#3031]
### Terraform (and AzureRM Provider) Version
$ terraform -v 
Terraform v0.11.12
+ provider.azurerm v1.11.0
+ provider.random v1.3.1

### Affected Resource(s)

* azurerm_app_service

### Terraform Configuration Files

```hcl
resource "azurerm_app_service" "currencySubscriptionApi-ASE_app" {
  name                = "currencySubscriptionApi-ASE"
  location            = "${var.location}"
  resource_group_name = "${var.appservice-rg}"
  app_service_plan_id = "/subscriptions/REMOVEDFORSECURITY/resourceGroups/currencyase/providers/Microsoft.Web/serverfarms/ILB-ASE-EXT"
  site_config {
    dotnet_framework_version = "v4.0"
    virtual_network_name = "secure-network-prod"

}
  lifecycle {
    ignore_changes = "app_settings"
  }
  app_settings {
    "APPINSIGHTS_INSTRUMENTATIONKEY"            = "${azurerm_application_insights.prod.instrumentation_key}"
    "LD_SDK_KEY"                                = "blabla"
    "MobileAppsManagement_EXTENSION_VERSION"    = "latest"
    "NODE_ENV"                                  = "production"
    "SCM_COMMAND_IDLE_TIMEOUT"                  = "600"
    "WEBSITE_HTTPLOGGING_RETENTION_DAYS"        = "7"
    "WEBSITE_NODE_DEFAULT_VERSION"              = "8.11.1"

  }

}

```

### Debug Output

Not applicable 

### Panic Output

None 

### Expected Behavior

App service resource should have been associated to virtual network 

### Actual Behavior

Error: azurerm_app_service.currencySubscriptionApi-ASE_app: site_config.0: invalid or unknown key: virtual_network_name

### Steps to Reproduce

Create a app service and try to associate it to a virtual network 

1. `terraform apply`

### Important Factoids

none 
### References
https://www.terraform.io/docs/providers/azurerm/r/app_service.html

* #0000

**Comment by tombuildsstuff** [comment]
hi @davidlbyrne 

Thanks for opening this issue :)

Support for attaching App Services to a Virtual Network was [added in version v1.15.0 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1150-september-14-2018). From the description you're using quite an old version (v1.11.0) of the Provider (which is before this property was supported) - if you upgrade to the latest version (1.23.0) this should work as expected. You can do this by specifying the version in the Provider block, for example:

```hcl
provider "azurerm" {
  version = "=1.23.0"
}
```

and then re-running `terraform init` (which will then download the provider for use)

Since this is a question about Terraform Configuration rather than a bug in Terraform, I'm going to close this issue for the moment - however if upgrading to the latest version of the Provider doesn't work for you please let us know and we'll take another look :)

Thanks!
