### ISSUE TITLE
no way to set os-type or runtime version in azurerm_function_app

### ISSUE THREAD

**Issue by dagda1** [terraform-providers/terraform-provider-azurerm#3042]
There does not appear to be anyway to set the `--os-type` or `--runtime` in azurerm_function_app.

If I am using azure cli then I can do this:

`az functionapp create -g ${azurerm_resource_group.main.name}  -p ${azurerm_app_service_plan.main.id} -n ${var.storage_function_name} -s ${azurerm_storage_account.main.name} --subscription ${var.subscription_id} --os-type Linux --runtime node`

Am I right in saying none of these things are possible with `azurerm_function_app`

**Comment by tombuildsstuff** [comment]
hi @dagda1 

Thanks for opening this issue :)

It should be possible to configure these options using both App Service Plan and Function App resources; for the `os_type` this can be configured using the App Service Plan and the Runtime can be configured using the `linux_fx_version` field within the `site_config` block of the Function App resource - for example:

```hcl
resource "azurerm_app_service_plan" "test" {
  # ...
  kind = "Linux"

 sku {
    tier = "Standard"
    size = "S1"
  }

  properties {
    reserved = true
  }
}

resource "azurerm_function_app" "test" {
  # ...

  site_config {
    linux_fx_version = "node|latest"
  }
}
```

Would you be able to take a look and see if that works for you? Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by dagda1** [comment]
@tombuildsstuff that works great! thank you
