### ISSUE TITLE
azurerm_kubernetes_cluster | agent_pool_profile | os_type - incorrect documentation for possible value 'Windows'?

### ISSUE THREAD

**Issue by ivdo814a8** [terraform-providers/terraform-provider-azurerm#3069]
The documentation for azurerm_kubernetes_cluster:
/terraform-provider-azurerm/website/docs/r/kubernetes_cluster.html.markdown
lists the possible values for agent_pool_profile | os_type as 'Linux' or 'Windows'.

Is this incorrect? I currently have been finding support only for Linux as the os_type.

**Comment by tombuildsstuff** [comment]
hi @ivdo814a8 

Thanks for opening this issue.

Unfortunately there's not enough information provided above for us to be able to diagnose this - as such I'm going to have to close this issue for the moment. In order for us to take a look into this, would you mind re-opening a new issue and completing the Issue Template (which contains all of the required information, such as the version of Terraform you're using) so that we can diagnose this?

Thanks!
