### ISSUE TITLE
There is no way to set API Management Policies using the  azurerm_api_management resource

### ISSUE THREAD

**Issue by maniSbindra** [terraform-providers/terraform-provider-azurerm#3075]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently it is not possible to set **API Management Policies** (Microsoft.ApiManagement service/apis/operations/policies : https://docs.microsoft.com/en-us/azure/templates/microsoft.apimanagement/2018-06-01-preview/service/apis/operations/policies) using  **azurerm_api_management** resource . 

The way to set these polices using ARM Template is using the resource type "Microsoft.ApiManagement/service/apis/operations/policies", and setting the properties.policyContent, and properties.contentFormat values. 

One of the work arounds to get this working using terraform is to use the terraform azurerm_template_deployment resource.

It will be great if the API management policies can be set using terraform resource and attributes (policy_content and content_format).

### New or Affected Resource(s)

* azurerm_api_management

### Potential Terraform Configuration

```hcl
content_format = "xml"
policy_content = "<policy content in xml>...."

```

**Comment by tombuildsstuff** [comment]
hey @maniSbindra 

Thanks for opening this issue :)

We've got a meta issue open tracking support for new API Management resources here: 
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1177#issuecomment-467536331 which includes support for API Management Policies (which will be their own resource); rather than having multiple issues open tracking the same thing I'm going to close this in favour of #1177 - would you mind subscribing to that for updates?

Thanks!

**Comment by maniSbindra** [comment]
Thanks @tombuildsstuff
