### ISSUE TITLE
Add Support for forceUpdateTag in azurerm_virtual_machine_extension

### ISSUE THREAD

**Issue by bernadinm** [terraform-providers/terraform-provider-azurerm#309]
Since terraform allows users to dynamically change their infrastructure, it would be good if it can take advantage of the `forceUpdateTag` that Azure provides so that operators/administrators can run the azurerm_virtual_machine_extension at anytime, not just for the initial deployment of the virtual machine. 

More information on this API endpoint on Microsoft's Azure page [here](https://docs.microsoft.com/en-us/rest/api/compute/extensions/extensions-add-or-update). 
### Example JSON

```json
{  
  "location": "westus",
  "properties": {
    "publisher": "Microsoft.OSTCExtensions",
    "type": "CustomScriptForLinux",
    "typeHandlerVersion": "Extension Version e.g. 1.5",
    "autoUpgradeMinorVersion": true|false,
    "forceUpdateTag": "RerunExtension",
    "settings": {
       "fileUris": [ "scriptFilePpath", "File2path"],
       "commandToExecute": "command"
    }
  },
  "protectedSettings": {
      "StorageaccountKey": "storageaccount-key"
   }
}
```

**Comment by bernadinm** [comment]
With this addition a user can pair up a `null_resource` where they can make any dynamic changes using Terraform across any number of nodes without requiring SSH.

**Comment by bernadinm** [comment]
The feature that an operator can take advantage of is the `RerunExtension` option. With this a user can set up triggers that terraform can redeploy in the event a config on terraform's end change or if a user wants to manually trigger the redeployment of the azurerm_virtual_machine_extension.

I see that this feature may not exist already after looking at the source of the Azure terraform provider [here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_virtual_machine_extension.go#L88-L96).  Correct me if I am wrong.

**Comment by tombuildsstuff** [comment]
Hey @bernadinm 

Thanks for opening this issue :)

> With this a user can set up triggers that terraform can redeploy in the event a config on terraform's end change

Any changes made to the `azurerm_virtual_machine_extension` resource should be picked up by Terraform and thus cause changes in a` terraform plan` / `terraform apply`. If that's not the case would it be possible to give an example of this not working so we could investigate further?

> or if a user wants to manually trigger the redeployment of the azurerm_virtual_machine_extension.

Given Terraform stores all of the information in the State File - it should be possible to achieve the same thing with `terraform taint azurerm_virtual_machine_extension.test` and subsequently running `terraform plan` and `terraform apply`.

My concern with adding this field is that it would cause issues with Terraform's idempotency; and given there's a native way within Terraform of achieving this, I'm not sure if adding this field would add any additional benefit rather than just tainting & re-applying the VM Extension.

Would it be possible to take a look and see if `terraform taint` solves your issue here?

Thanks!

**Comment by tombuildsstuff** [comment]
ping @bernadinm :)

**Comment by bernadinm** [comment]
Thanks @tombuildsstuff for your help. I will attempt to try this. I figured I create this to ensure this feature exist. I'll go ahead and test this when I get free cycles.

**Comment by tombuildsstuff** [comment]
@bernadinm as we've not heard back from you here I'm going to go ahead and close this issue for the moment - but please feel free to reopen this if this doesn't work for you and we'll take another look :)

Thanks!
