### ISSUE TITLE
Add multiple OS users on azure vm via terraform

### ISSUE THREAD

**Issue by shehzadshaikh** [terraform-providers/terraform-provider-azurerm#3114]
Hi,

I want to add more than one OS user while provisioning the Linux VM on Azure cloud via terrform template. 

I'm finding it relatively challenging to adding multiple users on azure cloud either from portal or azure-cli.

Thanks,

**Comment by tombuildsstuff** [comment]
hi @shehzadshaikh 

Thanks for opening this issue :)

Unfortunately Azure doesn't expose a friendly way of doing so (e.g. via a property suggesting which users should be created) at this time - instead they provide an option to provision multiple ssh keys for the same user (which we expose in the `azurerm_virtual_machine` resource). There's multiple ways of doing this, for example by building a Virtual Machine image using [Packer](https://packer.io), using [a Cloud-Init script within the `azurerm_virtual_machine` resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html#custom_data), using a script either via [a VM Extension](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_extension.html) or [using a Provisioner within Terraform](https://www.terraform.io/docs/provisioners/remote-exec.html) to do so - as such I'd recommend taking a look into these and seeing which would be the best fit for you.

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment, however please let us know if that doesn't work for you and we'll take another look

Thanks!
