### ISSUE TITLE
use_32_bit_worker_process doesn't work

### ISSUE THREAD

**Issue by Leon99** [terraform-providers/terraform-provider-azurerm#3146]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.11.13
+ provider.azurerm v1.23.0
```
### Affected Resource(s)

* `azurerm_app_service`,`azurerm_app_service_slot`

### Expected Behavior

- switching the app service's platform from 32 to 64 Bit in the Azure portal is detected by terraform given the presence of `use_32_bit_worker_process = true` (which, BTW, worked at some point)
- removing `use_32_bit_worker_process = true` switches the app service's platform to 64 Bit given it was set to 32 bit.

### Actual Behavior

Nothing happens in the scenarios mentioned above

### Steps to Reproduce

1. `terraform apply`

**Comment by Lucretius** [comment]
I am not familiar with this azure resource but from looking at the code:

`use_32_bit_worker_process` is considered a computed property which does not change based on user input after creation.† That would explain why changing this property does nothing.

Are you able to create `app_services` from scratch with `use_32_bit_worker_process` set to `true` or `false` and just changing it/removing the property does not appear to work?



† Found this comment in the terraform schema code from which I am making this assertion:
```
	// If Computed is true, then the result of this value is computed
	// (unless specified by config) on creation.
```

**Comment by bojingo** [comment]
@Lucretius - `use_32_bit_worker_process` is most certainly an attribute we should be able to change based on user input. In the Azure Portal there is a toggle button for App Services where this can be toggled.

----------------------

Not sure this is exactly related to this issue, but I had a challenge with this attribute where I had an App Service Plan in Standard tier with an application within it that had `use_32_bit_worker_process: false`. I wanted to change this App Service Plan to Free tier to save cost on our development environment. The caveat is that `use_32_bit_worker_process` must be true for Free tier because the Free tier doesn't support 64-bit processes. So, I flipped the property to true in Terraform config definition of the App Service.

The Terraform plan was generated fine, showing both resources changing, but when I applied I got an error because the App Service Plan was attempted to be changed first, which put it in an incompatible mode so the operation failed. It should have sequenced it the other way around: update the App Service to `use_32_bit_worker_process: false` before changing the App Service Plan to the Free tier. To get past this I manually flipped the bit-ness of the App Service in the Azure Portal and then re-planned and applied the Terraform config successfully.

**Comment by Lucretius** [comment]
@bojingo thank you for the additional information here, it's really helpful.  It sounds like we want to make the `use_32_bit_worker_process` non-computed.  I believe any attempted changes to it are ignored because it's a computed property - which means that when you tried to change both that and the app service plan, it never tried to change `use_32_bit_worker_process` --- the API calls should be making one big change to the resource.
