### ISSUE TITLE
Add the overwrite argument to the azurerm_storage_blob

### ISSUE THREAD

**Issue by IvanovOleg** [terraform-providers/terraform-provider-azurerm#3147]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I keep rendered templates in the Azure Blob Storage. When I update template and run terraform again, blob content remains the same. I need an option that forces terraform to overwrite the blob.

### New or Affected Resource(s)

* azurerm_storage_blob

### Potential Terraform Configuration

```hcl
resource "azurerm_storage_blob" "testsb" {
  name = "sample.txt"

  resource_group_name    = "${azurerm_resource_group.test.name}"
  storage_account_name   = "${azurerm_storage_account.test.name}"
  storage_container_name = "${azurerm_storage_container.test.name}"

  type = "block"
  overwrite = "true"
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @IvanovOleg 

Thanks for opening this issue :)

Since Terraform's only managing the creation of the Storage Blob in the example configuration above, there's no changes for it to detect (since it still exists) - which is why you're seeing this behaviour. If you wish to manage the content outside of Terraform [you can use `terraform taint` to force a recreation of this resource](https://www.terraform.io/docs/commands/taint.html) - alternatively you can look to set this content via Terraform using [the `source` property within the `azurerm_storage_blob` resource](https://www.terraform.io/docs/providers/azurerm/r/storage_blob.html#source) to point a local file. Would you be able to take a look and see if either of those options works for you?

As this is a question about Terraform Configuration rather than a bug in Terraform, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by IvanovOleg** [comment]
@tombuildsstuff 
I use the next order template_file -> local_file -> azurerm_storage_blob.
If I change a variable for the template, I expect to see changes in the corresponding azure blob. When I run terraform, the blob contain remains the same. Imagine if I have 100 templates, I will have to manually update each blob using azure portal since terraform doesn't allow me to do it automatically. The other way is to execute **terraform taint** 100 times which is not suitable as well.

**Comment by tombuildsstuff** [comment]
@IvanovOleg there's no association between the Blob resource and the Local File in the example above (since you're just creating an empty blob, without any contents set) - as such Terraform has no way of understanding that it needs to recreate the Blob resource when the File changes. Instead you'll need to look into using the `source` parameter for this to work, so that Terraform can determine the file has changed (the `local_file` resource will get re-generated, which will trigger an update of the `blob` resource).

Hope that helps!

**Comment by IvanovOleg** [comment]
@tombuildsstuff 
local_file change doesn't trigger the azure blob change, this is the root cause of the problem

**Comment by IvanovOleg** [comment]
@tombuildsstuff, here is a part of my terraform code:
```HCL
data "template_file" "provisioning-json" {
  template = "${file("${path.module}/templates/provisioning.json.tpl")}"

  vars {
    conntrack_version      = "${var.conntrack_version}"
    azure_vnet_cni_version = "${var.azure_vnet_cni_version}"
    cni_plugins_version    = "${var.cni_plugins_version}"
    helm_version           = "${var.helm_version}"
    kubernetes_version     = "${var.k8s_version}"
    blobfuse_version       = "${var.blobfuse_version}"
    fuse_version           = "${var.fuse_version}"
    torcx_remote           = "${var.torcx_remote}"
  }
}

resource "local_file" "provisioning-json" {
  content  = "${data.template_file.provisioning-json.rendered}"
  filename = "${path.module}/.tmp/torcx/provisioning.json"
}

resource "azurerm_storage_blob" "provisioning-json" {
  name                   = "provisioning.json"
  resource_group_name    = "${azurerm_resource_group.main.name}"
  storage_account_name   = "${azurerm_storage_account.main.name}"
  storage_container_name = "${azurerm_storage_container.torcx.name}"
  source                 = "${path.module}/.tmp/torcx/provisioning.json"
  type                   = "block"

  depends_on = [
    "local_file.provisioning-json",
    "azurerm_storage_account.main",
  ]
}
```
f.e if I change the **blobfuse_version** variable and execute **terraform apply**, template and local_file resources will be updated, but azurerm_storage_blob will be the same.
