### ISSUE TITLE
Support setting of osDiskSizeGB in acs agentpoolProfile

### ISSUE THREAD

**Issue by gshiva** [terraform-providers/terraform-provider-azurerm#315]
### Terraform Version
`# terraform -v`
`Terraform v0.9.9`

### Affected Resource(s)
Please list the resources as a list, for example:
- acs

acs-engine supports setting of the agent_pool osDiskSize (Not the master but the **minion** itself)

[Please see  osDiskSizeGB param in ](https://github.com/Azure/acs-engine/blob/master/docs/clusterdefinition.md#agentpoolprofiles)

Can terraform support this setting?

**Comment by tombuildsstuff** [comment]
Hey @gshiva 

Thanks for opening this issue :)

From what I can tell this should be available in the next API Version `2017-06-28` (with a ton of other enhancements). [I've opened this issue on the Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs/issues/1386) requesting that it's added - once that's done it'll get generated into the Azure SDK for Go where we can add support for it.

Thanks!

**Comment by gshiva** [comment]
Please let us know once the SDK is updated...

Looking forward to the disksize support

**Comment by gshiva** [comment]
@tombuildsstuff - does this https://github.com/Azure/azure-rest-api-specs/pull/1956 close this ticket or is still open?

Thanks

**Comment by tombuildsstuff** [comment]
hi @gshiva 

Apologies for the delayed update here!

Microsoft's recently announced [the deprecation of Azure Container Service in favour of Azure (Managed) Kubernetes Service](https://azure.microsoft.com/en-us/updates/azure-container-service-will-retire-on-january-31-2020/).

In preparation for this [we're deprecating the `azurerm_container_service` resource in version 1.20 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2481) - as such when using a `1.x` version of the AzureRM Provider the `azurerm_container_service` will continue to function until the API is removed on the 31st January 2020.

We plan to remove support for the `azurerm_container_service` resource in version 2.0 of the AzureRM Provider - should you wish to continue using the AzureRM Provider past this date you'll need to ensure your Provider block is pinned to a 1.x version, for example:

```
provider "azurerm" {
  version = ">= 1.0.0, <= 2.0.0"
}
```

alternatively you can pin the Provider block to a specific version ([more information about version pinning can be found on the Provider page](https://www.terraform.io/docs/configuration/providers.html)):

```
provider "azurerm" {
  version = "=1.19.0"
}
```

If you're using ACS with Kubernetes Microsoft's recommendation is to migrate to using Azure (Managed) Kubernetes Service (AKS) which is available as [the `azurerm_kubernetes_cluster` resource](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html) within Terraform.

Since the `azurerm_container_service` resource is being deprecated, I'm going to close this issue for the moment.

Thanks!
