### ISSUE TITLE
question about advanced networking on aks

### ISSUE THREAD

**Issue by mnothic** [terraform-providers/terraform-provider-azurerm#3165]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

Hi guys, I have a question related to Question related to this example:
https://github.com/terraform-provider-azurerm/examples/kubernetes/advanced-networking/main.tf
so in order to understand the advanced networking configuration in AKS.
What is the reason to create those routes? in the example down below and why uses that ip segments?
```hcl
resource "azurerm_route_table" "aksrt" {
  name                = "${var.env}-aks-rt"
  location            = "${var.location}"
  resource_group_name = "${var.resource_group}"

  route {
    name                   = "default"
    address_prefix         = "10.100.0.0/14"
    next_hop_type          = "VirtualAppliance"
    next_hop_in_ip_address = "10.10.1.1"
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @mnothic 

Thanks for opening this issue :)

My understanding of this is that the AKS Cluster requires a route to be defined for it to successfully be able to route outbound traffic from pods - since this request came from the AKS Team, I'd suggest opening an issue on [the AKS repository](https://github.com/Azure/aks) to get a better explanation from them here.

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment, however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by mnothic** [comment]
Ok thanks
