### ISSUE TITLE
azurerm_azuread_service_principal_password forces new resources on Update

### ISSUE THREAD

**Issue by Spazzy757** [terraform-providers/terraform-provider-azurerm#3175]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

## Description

I am currently using Terraform to bootstrap a Kubernetes cluster, this requires you to have a service principle. The issue seems to be that when you update the Service Principles Password (As this expires) Terraform see this as a change to the dependency tree and tries to provision an entirely new cluster. Apologies if my understanding is wrong:

```
resource "azuread_application" "current" {
  name = "${var.metadata_name}"
}

// Service Principle
resource "azuread_service_principal" "current" {
  application_id = "${azuread_application.current.application_id}"
}
resource "random_string" "password" {
  length  = 64
  special = true
}

resource "azuread_service_principal_password" "current" {
  service_principal_id = "${azuread_service_principal.current.id}"
  value                = "${random_string.password.result}"
  end_date_relative    = "2160h"                                   # valid for 90 days
}

// Cluster
resource "azurerm_kubernetes_cluster" "current" {
  name                = "${var.metadata_name}"
  location            = "${data.azurerm_resource_group.current.location}"
  resource_group_name = "${data.azurerm_resource_group.current.name}"
  dns_prefix          = "${var.dns_prefix}"

  role_based_access_control = {
    enabled = true
  }

  agent_pool_profile {
    name            = "${var.agent_pool_profile_name}"
    count           = "${var.agent_pool_profile_count}"
    vm_size         = "${var.agent_pool_profile_vm_size}"
    os_type         = "${var.agent_pool_profile_os_type}"
    os_disk_size_gb = "${var.agent_pool_profile_os_disk_size_gb}"
  }

  service_principal {
    client_id     = "${azuread_application.current.application_id}"
    client_secret = "${azuread_service_principal_password.current.value}"
  }

  addon_profile {
    oms_agent {
      enabled                    = true
      log_analytics_workspace_id = "${azurerm_log_analytics_workspace.current.id}"
    }
  }

  tags = "${var.metadata_labels}"
}
```

Now as the service principle password does expire (As it should for security reasons) there should be some kind of way to update it without recreating the cluster

**Comment by tombuildsstuff** [comment]
hi @Spazzy757 

Thanks for opening this issue :)

Unfortunately the Azure API doesn't allow for modifying the password of a Service Principal once it's been updated (which is why this requires a new resource, since it instead creates a new password); in addition at this time AKS doesn't allow for the Service Principal to be updated once it's provisioned (because the API doesn't allow this). As such at this time I'm not sure there's an immediate path forward for this issue until the AKS API allows rotation of a Service Principal's password unfortunately - and as such I'm going to close this issue for the moment.

In addition, just a heads up that the `azurerm_azuread_` prefixed resources are deprecated and have been replaced by [the separate `azuread` provider](https://github.com/terraform-providers/terraform-provider-azuread) - so any enhancements to this resource would now be made in that Provider.

Thanks!
