### ISSUE TITLE
Virtual machine scale set and application gateway healthcheck probe issue when want to use rolling upgrade policy

### ISSUE THREAD

**Issue by stephanepham** [terraform-providers/terraform-provider-azurerm#3190]
Hello, 

I'm trying to use "azurerm_virtual_machine_scale_set" resource with "azurerm_application_gateway". In "azurerm_virtual_machine_scale_set" i would like to use rolling upgrade policy mode and i need to set a "health_probe_id".

For example code in VMSS part terraform : 
```health_probe_id = "${azurerm_application_gateway.network.backend_http_settings.0.probe_id}"```

Error on terraform apply : 
```
azurerm_virtual_machine_scale_set.apiserver: compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"InvalidJsonReferenceWrongType","message":"Reference Id /subscriptions/f625232e-c1db-4ce5-989a-392b6804057b/resourceGroups/us-south-central-1/providers/Microsoft.Network/applicationGateways/lb-production/probes/us-south-central-1-probe is referencing resource of a wrong type. The Id is expected to reference resources of type loadBalancers/probes. Path Properties.UpdateGroups[0].NetworkProfile.healthProbe."}]
```
it seems "health_probe_id" doesn't support load balancer application gateway.

**Comment by tombuildsstuff** [comment]
hey @stephanepham 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this this appears to be a limitation of the Azure API rather than something specific to Terraform - since the documentation for this field in Azure (`A reference to a load balancer probe used to determine the health of an instance in the virtual machine scale set`) requires the ID of a Load Balancer Probe rather than an Application Gateway Probe, I believe this isn't supported by Azure at this time and as such isn't something we'd be able to support in Terraform until Azure does.

As such I'm going to close this issue for the moment but I'd suggest [opening a feature request on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs) where the Compute team could take a look into it.

Thanks!
