### ISSUE TITLE
Error building AzureRM Client: Error populating Client ID from the Azure CLI:  No Authorization Tokens were found

### ISSUE THREAD

**Issue by aswinraaj** [terraform-providers/terraform-provider-azurerm#3191]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.11.13

### Affected Resource(s)

* `provider.azurerm`

### Terraform Configuration Files

```hcl

```

### Expected Behavior

terraform plan should work as expected

### Actual Behavior

terraform plan fails with the following error : * provider.azurerm: Error building AzureRM Client: Error populating Client ID from the Azure CLI: No Authorization Tokens were found - please re-authenticate using `az login`.

### Steps to Reproduce

1. `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @aswinraaj 

Thanks for opening this issue :)

The error you're seeing above is because you're attempting to use a Service Principal via the Azure CLI which we don't support. Instead we support using either the Azure CLI with a user account, or by using a Service Principal specified either via Environment Variables or inline ([more details can be found here](https://www.terraform.io/docs/providers/azurerm/auth/service_principal_client_secret.html)). Would you be able to take a look and see if that works for you?

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
