### ISSUE TITLE
Auto scaling in Azure via terraform

### ISSUE THREAD

**Issue by hitesh1907nayyar** [terraform-providers/terraform-provider-azurerm#3223]
Hi ,

I need to automate scaling in azure via terraform. As i am aware support for autoscaling is not enabled in azure via terraform. Can anybody suggest some of the ways through which autoscaling can be enabled automatically when a cluster is created via terraform without azure cli.

Thanks for your help.

**Comment by Lucretius** [comment]
Auto scaling kubernetes clusters?  Or auto scaling virtual machine scaling sets?  Autoscaling virtual machine scale set support is available and there is a pull request open for kubernetes cluster autoscaling support

**Comment by hitesh1907nayyar** [comment]
I am talking for enabling auto scaling for kubernetes . Is there any workaround to automate scaling request for kubernetes in azure ?

Best Regards
Hitesh Nayyar

**Comment by Lucretius** [comment]
It's a preview feature - we are working on supporting it via Terraform.  In the meantime you can probably just use a provisioner on the kubernetes resource and rely on the Azure CLI.

**Comment by tombuildsstuff** [comment]
hi @hitesh1907nayyar 

Thanks for opening this issue :)

As mentioned in #3225 - at this time we don't natively support auto-scaling in Kubernetes via Terraform; however that feature's been requested in #2502. Rather than having multiple issues tracking the same thing I'm going to close this issue in favour of #2502 - would you mind subscribing to that issue for updates?

It's worth noting that we generally recommend asking questions [on one of the Community resources](https://www.terraform.io/community.html) rather than within this repository - where there's more users available to help, whereas the issues in this repository are more intended to be used for bugs and enhancements.

Thanks!
