### ISSUE TITLE
Problem with vmms in azure for autoscaling via terraform

### ISSUE THREAD

**Issue by hitesh1907nayyar** [terraform-providers/terraform-provider-azurerm#3231]
Hi,

I need to enable auto scaling for azure in terraform. I am getting an error “Operation failed with status: 'Bad Request'. Details: AgentPool 'agentpool' has set auto scaling as enabled but is not on Virtual Machine Scale Sets, this is not allowed.”  when i enable auto scaling via azure cli.
I need to know how can i link resources azurerm_kubernetes_cluster  and azurerm_virtual_machine_scale_set so that i can modify my script and can include Virtual Machine Scale Sets instead of agent node pool.

**Comment by tombuildsstuff** [comment]
hi @hitesh1907nayyar 

Thanks for opening this issue :)

Terraform doesn't support Kubernetes Auto Scaling (or it's dependencies, VMSS agents) at this time - as such we're unable to assist with workarounds such as via the Azure CLI. Support for Auto Scaling in Kubernetes is being tracked in #2502 which I'm going to close this issue in favour of, please subscribe to that issue for updates.

It's worth noting that we generally use the issues on this repository to track bugs and enhancements in the Github project; for questions we generally recommend [using one of the Community Resources](https://www.terraform.io/community.html) since there's more people available to answer more generic Azure questions.

Thanks!
