### ISSUE TITLE
azurem provider handles manual changes in NSGs in unexpected ways

### ISSUE THREAD

**Issue by OliverGoetz** [terraform-providers/terraform-provider-azurerm#325]
### Terraform Version
Terraform v0.10.4
terraform-provider-azurerm_v0.1.7_x4

### Affected Resource(s)
Please list the resources as a list, for example:
- network security groups

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "nsg-manual-modification-bug" {
  name     = "nsg-manual-modification-bug"
  location = "East US 2"
}

resource "azurerm_network_security_group" "nsg-detached-manual-modification" {
  name = "nsg-detached-manual-modification"
  location = "${azurerm_resource_group.nsg-manual-modification-bug.location}"
  resource_group_name = "${azurerm_resource_group.nsg-manual-modification-bug.name}"
}

resource "azurerm_network_security_rule" "detached-automated-security-rule" {
  name                        = "automated-security-rule"
  priority                    = 100
  direction                   = "Inbound"
  access                      = "Allow"
  protocol                    = "TCP"
  source_port_range           = "*"
  destination_port_range      = "22"
  source_address_prefix       = "10.0.0.0/16"
  destination_address_prefix  = "*"
  resource_group_name         = "${azurerm_resource_group.nsg-manual-modification-bug.name}"
  network_security_group_name = "${azurerm_network_security_group.nsg-detached-manual-modification.name}"
}

resource "azurerm_network_security_group" "nsg-inlined-manual-modification" {
  name = "nsg-inlined-manual-modification"
  location = "${azurerm_resource_group.nsg-manual-modification-bug.location}"
  resource_group_name = "${azurerm_resource_group.nsg-manual-modification-bug.name}"

  security_rule {
    name                        = "inlined-automated-security-rule"
    priority                    = 100
    direction                   = "Inbound"
    access                      = "Allow"
    protocol                    = "TCP"
    source_port_range           = "*"
    destination_port_range      = "22"
    source_address_prefix       = "10.0.0.0/16"
    destination_address_prefix  = "*"
  }
}
```

### Expected Behavior
The expectation was that manually added security rules would be handled the same way for NSGs where the rules are defined inlined and NSGs with separate rules attached.

### Actual Behavior
For the "nsg-inlined-manual-modification" the manually added rule is removed (which is what I expected)
For the "nsg-detached-manual-modification", the manually added rule still exists and is attached to the NSG. Also, the manually added rule is reflected in the terraform.tfstate

In the UI you cannot see any structural difference between the two NSGs, which makes the different handling surprising.

Even if you regard the separately created rule as an independent resource which should not be removed by terraform, then this should also not appear in the recorded state, as it is not covered in the terraform plan.

### Steps to Reproduce
1. `terraform apply`
2. Go to https://portal.azure.com and manually add a security rule to each of the security groups "nsg-detached-manual-modification" and "nsg-inlined-manual-modification"
3. `terraform apply`

**Comment by nbering** [comment]
This sounds like expected behaviour to me (though maybe the docs need to be clearer). Specifically, when it is inlined into the security group, the configuration means "This is the complete set of rules and no others shall exist." When specific rules are enumerated as separate configuration elements, the operations are on a per-rule basis. If the rule does not exist, it is created. If a change is made the the rule, the change will be applied. If a destroy action is made against the rule it will be removed. But if a new rule is added manually, Terraform is not managing that rule.

I can see a use case (ie. compliance management) where the current behaviour is undesirable, but currently I would suggest that it is in line with the overall design of Terraform. Maybe what is needed is a sort of "negative rule", that says a port range shall not ever have a rule to open it, and if there is that resource should be deleted. Not sure how that would fit into Terraform's paradigm, though. Playing it out as a thought experiment I can see some hacky ways of achieving this, but I'm not sure the provider API would play nice with the idea.

**Comment by OliverGoetz** [comment]
Thanks for the feedback. 
Initially, I tried to go for the inlined rules, but was unable to make it work with a count in the rules (in my actual scripts I have a list of CIDR blocks and a list of ports and I'm using the count mechanism to automatically create a rule for every combination of CIDR block and port).

One thing which still puzzles me, though. You write:

> But if a new rule is added manually, Terraform is not managing that rule.

Why then does terraform put the rule in the terraform.tfstate file? If the rule is not managed by terraform, it should also not show up there, IMHO.

**Comment by nbering** [comment]
Terraform is adding it to the tfstate file for the network security group because when you run a new apply, it refreshes the state from the real state of the resource. Though terraform is aware of the additional rule, it has no need to make changes to it to make the desired state (all your other rules), reality.

One other thing to consider in understanding this behaviour is that resources - while connected through interpolation and mapped as dependencies by core in the Directed Acyclic Graph (DAG) - are not actually aware of each other. If you use the inline rules, the Network Security Group is aware of all rules it should be managing since the use of inline rules implies that there are no other rules desired.

On the other hand, the "detatched" rules are not aware of each other, so that resource can only infer your intent about that particular rule. This is pretty core to the architecture and is part of how Terraform manages to do things like infer dependencies and create/destroy resources in parallel. If resources could look at their neighbours and change their behaviour based on the presence of another resource then the dependency tree would get much more complex, probably leading to a lot of circular dependencies - which terraform does not support.

**Comment by TheLinuxNinja** [comment]
I have the same issue. I need to use a count to enumerate a set of rules based on a list of CIDRs, but I don't want to allow any manually added rules to stick around for compliance purposes. We need a way to tell TF that it should manage the complete set of rules so that it removes any rules in the NSG that are not defined in TF. I don't remember if this was an issue in the AWS provider, but I think maybe I should go look, because if it's a problem here, then it's a problem there, too.

**Comment by nbering** [comment]
@TheLinuxNinja The AWS rules as individual resources vs. inline with the security group work exactly the same way.

**Comment by tombuildsstuff** [comment]
hi @OliverGoetz @TheLinuxNinja  

Thanks for opening this issue - apologies for the delayed response here!

> I have the same issue. I need to use a count to enumerate a set of rules based on a list of CIDRs, but I don't want to allow any manually added rules to stick around for compliance purposes. We need a way to tell TF that it should manage the complete set of rules so that it removes any rules in the NSG that are not defined in TF. I don't remember if this was an issue in the AWS provider, but I think maybe I should go look, because if it's a problem here, then it's a problem there, too.

The inlined Network Security Rule sub-resource and the external Network Security Rule resource have different use-cases. The inlined Network Security Rules within the Network Security Group resource is useful when the Network Security Group needs to be completely managed by Terraform - whereas the external `azurerm_network_security_rule` resource is more useful where the Network Security Group already exists. As such the `azurerm_network_security_rule` resource will only manage resources that it knows about (incase they're also managed elsewhere), whereas the `azurerm_network_security_group` resource will ensure the rules match what's in Terraform.

There's an info box in [the `azurerm_network_security_group` resource documentation](https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html) which details this behaviour too.

In the scenarios described - it sounds like you'd be better off using the inlined `security_rule` sub- resources within the `azurerm_network_security_group` resource which allows the rules to be fully managed. Given this behaviour is intentional - I'm going to close this issue for the moment.

Thanks!
