### ISSUE TITLE
Cosmos db subnet id, why not use a list with id's instead of a Map

### ISSUE THREAD

**Issue by snerting** [terraform-providers/terraform-provider-azurerm#3257]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When using Cosmos Db and want to open for vNet, you must add a List containing a Map with subnet id's. The only field in this map is Id. Why not simplyfy this and allow using just a List who contain the subnet id's?

In my configuration I need to use both Key Vault module, and Cosmos Db module. Both need to be acccessed from same subnet. Problem is that Key Vault accept a List with subnet Id's, but Cosmos Db, need a List with a Map of Id's. This cause that I must have 2 variables with the same values, but one as a list and another as a list with map. Confusing and error prone.

Maybe there is a smart way to convert my list with id's to a list of map of id's, but I have not found a way to do it.

**Comment by tombuildsstuff** [comment]
hi @snerting 

Thanks for opening this issue.

We've represented this field in this manner since this is how it's exposed in the Azure SDK - which generally indicates that additional properties may appear in the future. Whilst this doesn't help you today - Terraform 0.12 introduces a new concept of [For Expressions](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each) which I believe should make this easier for you in the future.

Since this is a question rather than an issue with the Azure Provider I'm going to close this issue for the moment

Thanks!
