### ISSUE TITLE
Node Autoscaler support for Azure AKS

### ISSUE THREAD

**Issue by polganesh** [terraform-providers/terraform-provider-azurerm#3292]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
As per documentation available on https://docs.microsoft.com/en-us/azure/aks/cluster-autoscaler#before-you-begin now AKS provide support for Node Auto scaler with Vm Scale set. support for same is not provided in Terraform script.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @polganesh 

Thanks for opening this issue :)

Support for VMSS for the `azurerm_kubernetes_cluster` resource has previously been requested in #2900 - rather than having multiple issues open for the same feature request I'm going to close this issue in favour of that one; would you mind subscribing to that issue for updates?

Thanks!
