### ISSUE TITLE
Azure AKS encrypt OS and Data disk for worker nodes

### ISSUE THREAD

**Issue by polganesh** [terraform-providers/terraform-provider-azurerm#3293]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently, I am unable to see an option to encrypt OS and data disk for AKS worker node.
it is needed for dynamic pv for stateful set.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @polganesh 

Thanks for opening this issue :)

Taking a look into this [it appears that this functionality is not supported by AKS](https://github.com/Azure/AKS/issues/629) and as such we'd be unable to support it in Terraform at this time. If this functionality exists can you provide an example/link so that we could investigate further?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @polganesh 

Since we've not heard back from you here and [this functionality isn't supported by Azure at this time](https://github.com/Azure/AKS/issues/629#issuecomment-479942576) I'm going to close this issue for the moment. When this functionality is added by Azure we should be able to look into adding support for this - however in the interim I'm going to close this issue for the moment.

Thanks!
