### ISSUE TITLE
Optimise Fetching Azurerm key vault secret for multiple secret values.

### ISSUE THREAD

**Issue by Sudharma** [terraform-providers/terraform-provider-azurerm#3320]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently to use the key vault secret we have to fetch the vault id and then proceed to get secret values. For Eg. Below

````
# Azure File Vault Data to be fetched
data "azurerm_key_vault" "test_vault" {
  name                = "test-vault"
  resource_group_name = "test-vault-rg"
}

# Fetch Id from azure vault
data "azurerm_key_vault_secret" "tf_id" {
  name      = "tfId"
  key_vault_id = "${data.azurerm_key_vault.test_vault.id}"
}

# Fetch secret  from azure vault
data "azurerm_key_vault_secret" "tf_secret" {
  name      = "tfSecret"
  key_vault_id = "${data.azurerm_key_vault.test_vault.id}"
}
````
Can this be optimised like below.??

````
# Azure File Vault Data to be fetched
data "azurerm_key_vault" "test_vault" {
  name                = "test-vault"
  resource_group_name = "tf-vault-rg"
}

# Fetch  Id from azure vault
data "azurerm_key_vault_secret" "tf_vault_secret" {
  key_vault_id = "${data.azurerm_key_vault.test_vault.id}"
}

 ## Fetching from Vault 
  client_id               ="${data.azurerm_key_vault_secret.test_vault.tfId.value}"
  client_secret       ="${data.azurerm_key_vault_secret.test_vault.tfSecret.value}"
````
This saves some time since I have 10 secrets for which I have to repeat the same data.

### New or Affected Resource(s)

* azurerm_key_vault_secret
* azurerm_key_vault

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Sudharma 

Thanks for opening this issue :)

Whilst Terraform potentially could look to retrieve every Secret within a Key Vault - from a security perspective it's generally best to retrieve only the secrets you require (or, lock accounts down to the minimum required permissions) - as such I believe it'd be better to use the `count` parameter to achieve this.

For example - with the secrets specified in a list (below as a Local variable, but it could also come from a regular Variable) you should be able to achieve the same thing like so:

```
locals {
  secret_names = ["first", "second", "third"]
}

data "azurerm_key_vault" "example" {
  name                = "test-vault"
  resource_group_name = "tf-vault-rg"
}

data "azurerm_key_vault_secret" "example" {
  count = "${length(locals.secret_names)"
  name = "${element(locals.secret_names, count.index)}"
  key_vault_id = "${data.azurerm_key_vault.example.id}"
}

output "secrets_values" {
  value = "${data.azurerm_key_vault_secret.example.*.value}
}
```

Would you be able to take a look and see if that works for you? Since this is a question about a Terraform Configuration I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look :)

Thanks!
