### ISSUE TITLE
Azure batch Pool Application Package 

### ISSUE THREAD

**Issue by GuitaristForEver** [terraform-providers/terraform-provider-azurerm#3322]
Application Package seems to be written in the plugin go files but no examples anywhere.
can someone confirm show example for assigning application package for a batch pool in terraform

**Comment by AmitDaniel-wsc** [comment]
@katbyte Hi . Can you please help us ? 
Thanks !

**Comment by tombuildsstuff** [comment]
hi @GuitaristForEver @AmitDaniel-wsc 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow).

Thanks!
