### ISSUE TITLE
`azurerm_redis_cache` support for minimum_tls_version in clustered mode

### ISSUE THREAD

**Issue by archmangler** [terraform-providers/terraform-provider-azurerm#3337]
It appears the option to set the minimum_tls_version in the azure redis cache resource is not recognised for  premium with clustering mode.  It does however appear to be recognised for standard and basic. 

The Azure documentation for rediscache does not appear to exclude this option for rediscache in any mode: https://docs.microsoft.com/en-us/azure/azure-cache-for-redis/cache-configure

Is it possible to have this feature configurable for clustered/premium mode in Terraform?

**Comment by archmangler** [comment]
Any update on this ?

**Comment by tombuildsstuff** [comment]
hi @archmangler 

Thanks for opening this issue.

Taking a look at the code for this, there's no differentiation between the SKU's within Terraform for this field - as such I believe this is a service specific issue. If you're still encountering this issue, so that we can take a look into this would you mind opening a new issue containing the details in the issue template, which we require to debug this further?

Thanks!
