### ISSUE TITLE
Feature Request: Resource Provider

### ISSUE THREAD

**Issue by gerardaus** [terraform-providers/terraform-provider-azurerm#3339]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

A new resource that interacts with the "Resource Management Providers" API found here:
https://docs.microsoft.com/en-us/rest/api/resources/providers

### New or Affected Resource(s)

New resources:
* azurerm_resource_provider

### Potential Terraform Configuration
```
resource "azurerm_resource_provider" "example" {
    subscription_id = "1234567890"
    resource_provider_namespace = "Microsoft.Batch"
    api_version = "2017-05-01"
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
Hey @gerardaus 

Thanks for opening this issue :)

Support for a resource to register Resource Providers has previously been requested in #1832; rather than having multiple issues open tracking the same thing I’m going to close this issue in favour of that one - would you mind subscribing to that one for updates?

Thanks!
