### ISSUE TITLE
How to configure "Monitor (classic) -> Diagnostic settings (classic)" for a storage account

### ISSUE THREAD

**Issue by bricebauer** [terraform-providers/terraform-provider-azurerm#3346]
Hi,

I create a storage account on my azure subscription.

I can't find how to configure "Diagnostic settings (classic)" for my Blob Storage (in terraform).
I means, in my storage account, the block "Monitoring (classic)" and sub menu "Diagnostic settings (classic)".

anyone can say me, if this feature exist and which function must be used ?

Thx

**Comment by tombuildsstuff** [comment]
hi @bricebauer 

Thanks for opening this issue :)

Support for this can be found in [the `azurerm_monitor_diagnostic_setting` resource](https://www.terraform.io/docs/providers/azurerm/r/monitor_diagnostic_setting.html) - would you be able to take a look and see if that works for you?

Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look.

Thanks!
