### ISSUE TITLE
Active Directory Admin for azurerm_sql_server

### ISSUE THREAD

**Issue by Sahasrara** [terraform-providers/terraform-provider-azurerm#3348]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
There's no way to set Active Directory Admin for an azurerm_sql_server.

### New or Affected Resource(s)

* azurerm_sql_server

### Potential Terraform Configuration
```
resource "azurerm_sql_server" "sql_server" {
  ad_admin = "..."
}
```

### References
https://www.terraform.io/docs/providers/azurerm/r/sql_server.html

**Comment by tombuildsstuff** [comment]
Hi @Sahasrara 

Thanks for opening this issue :)

Support for configuring Azure Active Directory Administrators for a SQL Server Database can be found in [the `azurerm_sql_active_directory_administrator` resource](https://www.terraform.io/docs/providers/azurerm/r/sql_active_directory_administrator.html) - rather than within the `azurerm_sql_server` resource; would you be able to take a look and see if this works for you?

Since this is a question about Terraform configuration rather than a bug in Terraform I’m going to close this issue for the moment - but please let us know if that doesn’t work for you and we’ll take another look :)

Thanks!

**Comment by Sahasrara** [comment]
Oh i must have just missed it.  Thanks!
