### ISSUE TITLE
Expose vnet, network security group, and routetable as outputs of azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by Sahasrara** [terraform-providers/terraform-provider-azurerm#3350]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to not have to manually create all of these objects.  I'm not even sure how I'd go about doing that.  But If I specify a custom vnet, I have to create my own routetable/network security group.  If I were able to address the vnet from terraform without creating it manually (i.e. through an output), this wouldn't be an issue.  I don't know how else I can modify the vnet without manually inputing it's name as a data source and I don't want to do that.

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

I should be able to do this:

```
${azurerm_kubetnetes_cluster.cluster.vnet.id}
```

**Comment by tombuildsstuff** [comment]
hi @Sahasrara 

Thanks for opening this issue.

There's two parts to this question - to go through each of them in turn:

> I'd like to not have to manually create all of these objects. I'm not even sure how I'd go about doing that

Unfortunately this functionality isn't exposed by AKS itself - and as such this isn't something we'd be able to expose.

To be honest I don't think this is something we'd likely expose within Terraform if it were - primarily this because Terraform would have no means of tracking the properties/deletion of said Network/Subnet (which would lead to other transitory issues during deletion should users for example provision things in said network) - as such I'd suggest instead this may be a good candidate for [a Terraform Module](https://www.terraform.io/docs/modules/index.html) which wraps all of this configuration so that you only have to define this once.

> I don't know how else I can modify the vnet without manually inputing it's name as a data source and I don't want to do that.

Unfortunately since this functionality isn't exposed by AKS itself - this isn't something we'd be able to expose. At the moment the network names etc are predictable (however they have changed in the past, so this isn't something we'd hard-code & expose from Terraform) - but if you're creating a module anyway you could hard-code this as an output of a module (as described above) which may allow you to work around this.

Since unfortunately this isn't something we plan to support in Terraform I'm going to close this issue for the moment.

Thanks!
