### ISSUE TITLE
Please add azurerm_storage_account "secure transfer required" toggle

### ISSUE THREAD

**Issue by Sahasrara** [terraform-providers/terraform-provider-azurerm#3365]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Please add "Secure transfer required" option to azurerm_storage_account

### New or Affected Resource(s)

* azurerm_storage_account

### Potential Terraform Configuration

```
resource "azurerm_storage_account" "test" {
  secure_transfer_required = true
}
```

### References

https://www.terraform.io/docs/providers/azurerm/d/storage_account.html

**Comment by draggeta** [comment]
@Sahasrara I think you are looking for the `enable_https_traffic_only` option on storage accounts. 
https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#enable_https_traffic_only

**Comment by tombuildsstuff** [comment]
hi @Sahasrara 

Thanks for opening this issue :)

As @draggeta has mentioned (thanks!) I believe this functionality is available via the `enable_https_traffic_only` field within the `azurerm_storage_account` resource - would you be able to take a look and see if that works for you? Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
