### ISSUE TITLE
Referencing tag from resource group via module

### ISSUE THREAD

**Issue by jamie3** [terraform-providers/terraform-provider-azurerm#3376]
I'm creating a key vault module and within my example test:

**examples\key-vault\main.tf**

```
provider "azurerm" {
    subscription_id = "..."
}

resource "azurerm_resource_group" "resource_group" {
    name = "key-vault-test"
    location = "westus2"

    tags = {
        environment = "unittest"
    }
}

module "key_vault" {
    source = "../../"

    name = "mytest"
    resource_group_name = "${azurerm_resource_group.resource_group.name}"
}
```

**Key Vault module main.tf**

```
provider "azurerm" {
    version = ">=1.25.0"
}

data "azurerm_resource_group" "resource_group" {
  name = "${var.resource_group_name}"
}

locals {

    # Todo get environment from resource group tag - this currently doesnt work???
    #environment = "${data.azurerm_resource_group.resource_group.tags["environment"]}"

    name = "${var.name}-akv"
}

resource "azurerm_key_vault" "key_vault" {
  name                        = "${local.name}"
  location                    = "${data.azurerm_resource_group.resource_group.location}"
  resource_group_name         = "${var.resource_group_name}"
  enabled_for_disk_encryption = true

  tenant_id = "..."

  sku {
    name = "standard"
  }

  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
  }

  tags = "${data.azurerm_resource_group.resource_group.tags}"
}
```

**Expected Results**

Terraform should assign the environment in the local variable

**Actual Results**

Error: Error asking for user input: 1 error(s) occurred:

* module.key_vault.local.environment: local.environment: At column 50, line 1: map "data.azurerm_resource_group.resource_group.tags" does not have any elements so cannot determine type. in:

${data.azurerm_resource_group.resource_group.tags["environment"]}

**Comment by tombuildsstuff** [comment]
hi @jamie3 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this I believe this should be fixed by upgrading to the latest version of Terraform Core and the AzureRM Provider - would you be able to take a look and see if that works for you?

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but if that doesn't work for you I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
