### ISSUE TITLE
Please add accelerated networking to azurerm_virtual_machine_scale_set

### ISSUE THREAD

**Issue by samirageb** [terraform-providers/terraform-provider-azurerm#339]
I assume this [issue](https://github.com/Azure/azure-sdk-for-go/issues/744) is also a pre-req before this capability can be added, but wanted to get this tracked.

### Terraform Version
- Terraform 0.10.5
- AzureRM TF Provider 0.2.0

### Affected Resource(s)
- azurerm_virtual_machine_scale_set

### References
- #272

**Comment by tombuildsstuff** [comment]
Hey @samirageb 

Thanks for opening this issue :)

Your assumption is correct (as both VM's and VMSS's are part of the `Compute` SDK) - so once [the v11 SDK PR](https://github.com/Azure/azure-sdk-for-go/pull/768) has been merged we'll look into upgrading to that and then investigating supporting this functionality :)

Thanks!

**Comment by tombuildsstuff** [comment]
hi @samirageb 

Thanks for opening this issue - apologies for the delayed response here!

Support for Accelerated Networking was added in #448 which has been available in the AzureRM Provider since v0.3.1: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v0.3.1/CHANGELOG.md#031-october-21-2017

Thanks!
