### ISSUE TITLE
Support for all Azure App Service Types

### ISSUE THREAD

**Issue by michaelmercer83** [terraform-providers/terraform-provider-azurerm#3409]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Microsoft Azure offer four types of App Service (a list can be found at the bottom of the following page - https://azure.microsoft.com/en-gb/services/app-service/ )

As far as I can see only the Web App Service is catered for by Terraform? Our Dev Team have stated that they require Mobile App Service resources due to issues with authentication and the Web App Service (Microsoft have confirmed this).

Azure Json templates allow for the kind parameter to specify the type of App Service the user wants to create.

Is this something can can be resolved? We would be unable to use Terraform in our environment until such resources can be created.

### New or Affected Resource(s)

* azurerm_app_service

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/443

**Comment by tombuildsstuff** [comment]
hi @michaelmercer83 

Thanks for opening this issue :)

Support for API Apps and Mobile Apps has previously been requested in https://github.com/terraform-providers/terraform-provider-azurerm/issues/443 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one, would you mind subscribing to that one for updates? Whilst we could opt to add this to the `azurerm_app_service` resource - rather than making this resource generic (and supporting every possible combination in there), we're instead looking to create resources for each of the App Service types, which provide validation/support for the features supported by that app type.

> We would be unable to use Terraform in our environment until such resources can be created.

In the interim you should be able [to use the `azurerm_template_deployment` resource](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html) to deploy an ARM Template from within Terraform - which allows you to pass variables from Terraform into an ARM Template and out of an ARM Template into Terraform.

Thanks!

**Comment by michaelmercer83** [comment]
Hi Tom,

Thanks for taking the time to respond to the request. Great suggestion re:  the azure_template_deployment - I hadn't come across it before. That should keep me quiet for the time being :-)

**Comment by smushtaq** [comment]
Hi Tom,
I have used azurerm_template_deployment to deploy 2 api apps but the problem i am getting now is that the app_name of one resource is overriding the previous one when i do   value = ${lookup(azurerm_template_deployment.my_apiapp_template.outputs, "app_name")}

Any ideas to add an element of uniqueness to the templates and get the unique output.

**Comment by smushtaq** [comment]
Found out that the name property of the azurerm_template_deployment was not unique for both the apiapp. Using unique name property inside the template like below solved the problem

resource "azurerm_template_deployment" "my-azure-template" {
  name                = "${var.apiapp_template_name}"
 .....
}
