### ISSUE TITLE
Storage

### ISSUE THREAD

**Issue by sravan5432** [terraform-providers/terraform-provider-azurerm#3415]
Hello,

I want to copy a blob of storage acc, but there is an error throwing in it

Error:
The value for one of the HTTP headers is not in the correct format

Given Value:   https://{var.Stor_Acc}.blob.core.windows.net/<SAS>  (Storage Blob uri with SAS)

can someone help me with it

**Comment by tombuildsstuff** [comment]
hi @sravan5432 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow).

Thanks!
