### ISSUE TITLE
managed_disk - does not allow create_option = "Restore"

### ISSUE THREAD

**Issue by andyt530** [terraform-providers/terraform-provider-azurerm#3421]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform --version
Terraform v0.11.11

Provider: "azurerm" (1.27.1)...

### Affected Resource(s)

* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
resource azurerm_managed_disk RG-PROD__vm-datadisk-000 {
  name                 = "vm-datadisk-000"
  location             = "ukwest"
  resource_group_name  = "RG-PROD"
  create_option        = "Restore"
  source_resource_id   = "/subscriptions/xxxxx-xxx-xxx-xxx-xxxxx/resourceGroups/AzureBackupRG_ukwest_1/providers/Microsoft.Compute/restorePointCollections/AzureBackup_vm-02_169/restorePoints/AzureBackup_20190122_014129/disks/vm-02_disk2_4a?id=edef9810-xxxx-xxxx-xxxx-xxxxxxxxxxxxxx"
  storage_account_type = "Premium_LRS"
  disk_size_gb         = "1023"
}
```

### Expected Behavior

Plan/Apply should allow the "Restore" option - to allow creation of managed disks from backups. 

### Actual Behavior

Error: azurerm_managed_disk.RG-DWP-PROD-DR-CH-PNS-TUOINFRA__vmtuodrsql02-datadisk-000-20190124-132656: expected create_option to be one of [Copy Empty FromImage Import], got Restore

### Steps to Reproduce

1. `terraform plan .`

### References

* #0000

**Comment by r0bnet** [comment]
The create option you're looking for (`Restore`) is indeed missing and needs to be added. Question is how the restoring process is working then because in the documentation it says that `source_resource_id` is only used for `Copy`.

https://docs.microsoft.com/de-de/azure/templates/microsoft.compute/2018-09-30/disks#creationdata-object

**Comment by andyt530** [comment]
I think the documentation may need updating this is a valid combination. The Terraform was generated by az2tf (https://github.com/andyt530/az2tf). The VM was created from a restore of a backup from a recovery vault. The tool takes its information from az CLI commands to query the running environment.

**Comment by sean-nixon** [comment]
The "Restore" option also gets set on a disk created by Azure Site Recovery when failing over a VM. That results in a different sourceResourceId format: "/subscriptions/xxxxx/resourceGroups/xxxxx/providers/Microsoft.Compute/disks/xxxxx-ASRReplica/bookmark/xxxxxxxx" so that resourceId format will need to be supported as well

**Comment by sean-nixon** [comment]
Took a first stab at a PR for this one since it seemed like a simple validation change to prevent that error at least. 

I'm at a loss as to where those IDs come from. The ID of a backup recovery point in our environment looks like this:

`/Subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/rgName/providers/Microsoft.RecoveryServices/vaults/vaultname/backupFabrics/Azure/protectionContainers/IaasVMContainer;iaasvmcontainerv2;rgName;vmName/protectedItems/VM;iaasvmcontainerv2;rgName;vmName/recoveryPoints/39463654022097`

That's completely different than the ID reported in this issue. The ID of the recovery point for site recovery is also different from the one that gets set on the disk.

As far as I can tell, there's no way to actually create a disk using the Restore option using the CreateOrUpdate API for the disk. It would have to be created using the restore processes for site recovery / Azure Backup and then imported or updated in the resource configuration.
