### ISSUE TITLE
NSG gets disassociated

### ISSUE THREAD

**Issue by nprashiyer** [terraform-providers/terraform-provider-azurerm#3426]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_subnet_network_security_group_association`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet_network_security_group_association" "Web-Association" {
  subnet_id                 = "${azurerm_subnet.dev-web.id}"
  network_security_group_id = "${azurerm_network_security_group.nsg-web.id}"
}
```

### Expected Behavior

When I apply this initially, the NSG should be associated with the subnet with the mentioned ID.
When I apply again (with/without any changes to the infrastructure) , the NSG association that was initially created should remain.

### Actual Behavior

When I apply again second time (with/without any changes to the infrastructure) , the NSG gets disassociated.
When I apply again third time, it gets associated again.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @nprashiyer 

Thanks for opening this issue :)

When using the `azurerm_subnet_network_security_group_association` resource, the Network Security Group must also be attached to the Subnet using the `azurerm_subnet` resource (this is to prevent a breaking change in the Provider, which will be fixed in 2.0, when this will only be required within the `azurerm_subnet_network_security_group_association` resource). As such - so that we can take a look into this, would it be possible to see the full Terraform Configuration you're using?

Thanks!

**Comment by nprashiyer** [comment]
Thanks @tombuildsstuff  for the response.
I added the Network Security Group must also be attached to the Subnet using the `azurerm_subnet ` resource & issue does not occur.

**Comment by tombuildsstuff** [comment]
@nprashiyer glad to hear this is now working for you 👍
