### ISSUE TITLE
Assignment of new ip_configuration blocks to existing NIC?

### ISSUE THREAD

**Issue by voyera** [terraform-providers/terraform-provider-azurerm#3448]
Hey guys, first off having a great time with terraform. I'm running with an edge case with the azurerm provider where adding multiple ip_configuration to the nic would make a ubuntu 18-04 vm randomly have cloud-init request timeout at first boot (probably caused by the eth0 not being properly configured inside netplan).

So I removed the secondary ip_configuration blocks thinking I could add them after the VM has been spun up... but I can't wrap my head around how to do that. Could someone point me in the right direction?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @voyera 

Thanks for opening this issue :)

This isn't something that's possible today - but we're planning on replacing the Virtual Machine and VM Scale Set resources in the next major version of the provider (2.0) (and keeping the existing ones around) such that this should be possible (potentially via a `network_interface_attachment` resource, but we'll see).

I'd suggest subscribing to #2807 for updates - in the interim I feel like your best solution may be to reach out to the publisher of the OS Image you're using, and see if they can help further - but since is locked on #2807 I'm going to close this issue for the moment.

Thanks!

**Comment by voyera** [comment]
Thanks for the answer @tombuildsstuff  ! I will keep an eye open for 2.0 :)
