### ISSUE TITLE
Feature Request: diagnostic settings for azurerm_key_vault

### ISSUE THREAD

**Issue by mlcooper** [terraform-providers/terraform-provider-azurerm#3456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enable configuration of "Diagnostic settings" for an Azure Key Vault.  Specifically these settings:
![image](https://user-images.githubusercontent.com/9505606/57866921-2ccb4c80-77ce-11e9-9343-6a09323e12c1.png)

### New or Affected Resource(s)

`azurerm_key_vault`

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault" "vault" {
  name                = "vault01"
  location            = "westus"
  resource_group_name = "foo_group"

  tenant_id "000000-1111-22222-33333333333" 
  
  sku {
    name = "standard"
  }

  diagnostic_settings {
    name                       = "daig_01"
    archive_to_storage_account = "true"
    stream_to_event_hub        = "false"
    send_to_log_analytics      = "false"
    storage_account_name       = "storage01"
    log                        = ["AuditEvent", "AllMetrics"]
  }
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @mlcooper 

Thanks for opening this issue :)

Diagnostic Settings can be configured [using the `azurerm_monitor_diagnostic_setting` resource](https://www.terraform.io/docs/providers/azurerm/r/monitor_diagnostic_setting.html), rather than within each resource - as such I believe this should be what you're after - would you be able to take a look and see if that works for you?

Since this is a question about Terraform Configuration rather than a bug in Terraform I'm going to close this issue for the moment, however please let us know if that doesn't work for you and we'll take another look.

Thanks!
