### ISSUE TITLE
azurerm_shared_image_version target_region flexibility

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#3466]
What is the best way to create more than one target_region field blocks based on a list of regions.
```
resource "azurerm_shared_image_version" "ubuntu" {
  count               = 1
  name                = "1.0.1"
  gallery_name        = "${azurerm_shared_image_gallery.image_gallery.name}"
  image_name          = "${azurerm_shared_image.image_definition.name}"
  resource_group_name = "${azurerm_resource_group.image_gallery.name}"
  location            = "${var.location}"
  managed_image_id    = "${element(data.azurerm_image.ubuntu.*.id, count.index)}"

  target_region {
    name                   = "${azurerm_shared_image.image_definition_ubuntu.location}"
    regional_replica_count = 1
  }
}
```

Base on the list, i want to create more than one target_region blocks:
```

image_replication_regions = [
    "uksouth",
    "austrailiaeast",
    "canadacentral"
]
````

Is this doable? If not, can we get target_region turned into a resource or do we have to wait for v.12?

**Comment by rohrerb** [comment]
@tombuildsstuff  😄

**Comment by tombuildsstuff** [comment]
@rohrerb that's (number of images * number of locations) not directly possible in 0.11; but should be possible with the `foreach` feature coming in a future 0.12 release.

Taking a look at the API, since these fields can be updated - I'd agree this could make sense as a Virtual Resource but it'd require some prototyping to work out the specifics.

Since this issue is mostly a question, I'm going to close this issue for the moment - if you're interested in seeing the split-out virtual resource then would you mind opening a new issue with the full issue template?

Thanks!
