### ISSUE TITLE
terraform plan shows a change for "azurerm_postgresql_virtual_network_rule" even when there are no changes

### ISSUE THREAD

**Issue by bkarakashev** [terraform-providers/terraform-provider-azurerm#3485]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_1.28.0`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
```
An execution plan has been generated and is shown below.
Resource actions are indicated with the following symbols:
  ~ update in-place

Terraform will perform the following actions:

  ~ azurerm_postgresql_virtual_network_rule.rule
      subnet_id: "subnet_ID" => "subnet_ID (Exactly the same value)"


Plan: 0 to add, 1 to change, 0 to destroy.
```

### Expected Behavior
I am not changing the value of the subnet_id but every time I do plan after apply
I am getting 1 change.
Current value and new value of the subnet_id is exactly the same.

### Actual Behavior
What should have happened is no changes.

### Steps to Reproduce

1. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @bkarakashev

Thanks for opening this issue :)

Unfortunately it's not possible to diagnose this without seeing the Terraform Configuration and the diff being returned from Terraform here - but my guess would be that the Resource ID for the Subnet ID's being hard-coded, and uses a different casing to what's returned from Azure? To work around this, rather than hard-coding Resource ID's, we instead suggest using [the `azurerm_subnet` Data Source](https://www.terraform.io/docs/providers/azurerm/d/subnet.html) to obtain this value, for example:

```hcl
data "azurerm_subnet" "test" {
  name                 = "backend"
  virtual_network_name = "production"
  resource_group_name  = "networking"
}

output "subnet_id" {
  value = "${data.azurerm_subnet.test.id}"
}
```

So that we're able to confirm if this is the root-cause - would you be able to provide both the Terraform Configuration being used, and the diff from Terraform?

Thanks!

**Comment by bkarakashev** [comment]
Thanks all it was spelling I had the subnet_id all lower case but Terraform was expecting a couple of things Camelcase
