### ISSUE TITLE
Enable RBAC without AAD

### ISSUE THREAD

**Issue by abhiramani-iptiq** [terraform-providers/terraform-provider-azurerm#3488]
Hi
i have added this block based on example but getting error:"invalid or unknown key: role_based_access_control"

  role_based_access_control {
    enabled = "true"
  }

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @abhiramani-iptiq 

Thanks for opening this issue.

Support for Role Based Access Control was added within a recent version of the AzureRM Provider - and you're seeing this error because you're on an older version. Would it be possible for you to confirm which version of the Provider you're using, which you can get via `terraform providers`

Thanks!

**Comment by abhiramani-iptiq** [comment]
provider.azurerm: version = "~> 1.13"

**Comment by tombuildsstuff** [comment]
@abhiramani-iptiq the latest provider version is `1.28` - you can update by specifying this in the Provider block:

```
provider "azurerm" {
  version = "=1.28.0"
}
```

and then re-running `terraform init` which will download the new version. Since that should resolve this issue I'm going to close this issue for the moment, but please let us know if that doesn't solve it for you and we'll take another look :)

Thanks!
