### ISSUE TITLE
Test Defect: TestAccAzureRMEventGridEventSubscription_basic

### ISSUE THREAD

**Issue by lrxtom2** [terraform-providers/terraform-provider-azurerm#3489]
TestAccAzureRMEventGridEventSubscription_basic [Check fail]
--- FAIL: TestAccAzureRMEventGridEventSubscription_basic (206.98s)
    testing.go:568: Step 0 error: Check failed: Check 5/9 error: azurerm_eventgrid_event_subscription.test: Attribute 'included_event_types.0' expected "All", got "Microsoft.Resources.ResourceWriteSuccess"

**Comment by lrxtom2** [comment]
![image](https://user-images.githubusercontent.com/20538091/58120843-e9505400-7bba-11e9-81e1-e821235c67cb.png)

**Comment by tombuildsstuff** [comment]
hi @lrxtom2

Thanks for opening this issue :)

We run the Acceptance Tests for this project nightly via our CI Server which tracks test failures; since this isn't an issue which is impacting users (and is instead due to a change in the ordering returned from the API instead) - I'm going to close this issue for the moment, but we'll track this in our CI server.

Thanks!
