### ISSUE TITLE
azurerm_redis_cache capacity

### ISSUE THREAD

**Issue by mamoorkhan** [terraform-providers/terraform-provider-azurerm#3498]
So I am trying to figure out the different features of Azure Terraform Provider, I was looking for information, what these values mean like 

    capacity = 0

When in powershell I can easily do 

    -Size 250MB

I would like to know what size cache I am going to be deploying, is there any table for that, I can't seem to find that information.

**Comment by tombuildsstuff** [comment]
hi @mamoorkhan 

In this instance the `0` relates to the Capacity of the SKU - which comes from this page: https://azure.microsoft.com/en-gb/pricing/details/cache/ - for example `C0` is `0` which is `250MB`, `C1` is to a capacity of `1` which is `1GB`; whilst I appreciate this isn't as clear as it could be, the values for Capacity vary depending on the SKU being used - and as such we've opted to match the API's design at this time.

Since this is a question rather than a bug in Terraform - I'm going to close this issue for the moment; but please let us know if that doesn't work for you and we'll take another look :)

Thanks!
