### ISSUE TITLE
Provider doesn't support resource: azurerm_cosmosdb_mongo_collection or azurerm_cosmosdb_mongo_database

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3504]
When using version 1.27.1 I cannot seem to create a mongo database or collection. I'm given the following errors:

```
Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider "azurerm" (1.27.1)...

...

Error: azurerm_cosmosdb_mongo_collection.coyote_cosmosdb_mongo_collection: Provider doesn't support resource: azurerm_cosmosdb_mongo_collection

Error: azurerm_cosmosdb_mongo_database.coyote_cosmosdb_mongo_database: Provider doesn't support resource: azurerm_cosmosdb_mongo_database
```

**Comment by tombuildsstuff** [comment]
hi @cdesewell 

Thanks for opening this issue :)

Support for CosmosDB Mongo Database/Collections was added in v1.28 of the Provider: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md

You should be able to update to this by updating the version in your provider block:

```hcl
provider "azurerm" {
  version = "=1.28.0"
}
```

and then re-running `terraform init` which will download the new version of the Provider featuring this functionality - would you be able to take a look and see if that works for you?

Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by cdesewell** [comment]
Awesome Thanks
