### ISSUE TITLE
Add Collapse All  to Provider Documentation?

### ISSUE THREAD

**Issue by johnwildes** [terraform-providers/terraform-provider-azurerm#3511]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can you add a COLLAPSE ALL to the tree menu on the documentation site.  It's great to have around when looking for something, but difficult to navigate the document if you're just focusing on one resource at a time.

### New or Affected Resource(s)

Resource Provider documentation

**Comment by tombuildsstuff** [comment]
hey @johnwildes 

Thanks for opening this issue :)

Feature Requests for the Terraform Website are tracked outside of this repository, so that this is routed to the right team I hope you don't mind but I'm going to close and re-open this issue (unfortunately I can't move it since it's cross-org) to [the Terraform Website repository](https://github.com/hashicorp/terraform-website) - would you mind subscribing to this new issue for updates? https://github.com/hashicorp/terraform-website/issues/801

Thanks!
