### ISSUE TITLE
Does Terraform support converting Standard HDD to Premium SSD?

### ISSUE THREAD

**Issue by r0039** [terraform-providers/terraform-provider-azurerm#3515]
hello everyone, 

I have to convert the Data disk from Standard HDD to Premium SSD, but I am not sure Terraform already supported this? 

I googled, but still didn't find any document related that. Hope someone can help me this one. 

Thank you so much!

**Comment by r0039** [comment]
Microsoft instruction about converting the managed disk
https://docs.microsoft.com/en-us/azure/virtual-machines/linux/convert-disk-storage

**Comment by tombuildsstuff** [comment]
hi @r0039 

Thanks for opening this issue :)

The [`storage_account_type` field for an `azurerm_managed_disk`](https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html#storage_account_type) is updateable without reprovisioning, so providing Terraform managed that resource, yes 👍 

Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment but please let us know if that doesn't solve your issue and we'll take another look.

Thanks!
