### ISSUE TITLE
Resource to detect tenant id

### ISSUE THREAD

**Issue by timja** [terraform-providers/terraform-provider-azurerm#3516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`key_vault_access_policy`  requires a tenant id to pass, ideally you would be able to get that the current ARM connection context without having to pass it in as a variable

https://www.terraform.io/docs/providers/azurerm/r/key_vault_access_policy.html

### New or Affected Resource(s)

* azurerm_subscription

### Potential Terraform Configuration

```hcl
data "azurerm_subscription" "current" {}

output "current_tenant_id" {
  value = "${data.azurerm_subscription.current.tenant_id}"
}
```

**Comment by tombuildsstuff** [comment]
hi @timja 

Thanks for opening this issue :)

The `tenant_id` field can be obtained from [the `azurerm_client_config` Data Source](https://www.terraform.io/docs/providers/azurerm/d/client_config.html) - for example:

```
data "azurerm_client_config" "current" {}

output "tenant_id" {
  value = "${data.azurerm_client_config.current.tenant_id}"
}
```

.. which should work when authenticating as any kind of user; would you be able to take a look and see if that works for you? Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment but please let us know if that doesn't solve your issue and we'll take another look :)

Thanks!
