### ISSUE TITLE
terraform "hijacks" resources that already exist

### ISSUE THREAD

**Issue by AndyMoore** [terraform-providers/terraform-provider-azurerm#3562]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.11.13
+ provider.azurerm v1.29.0

### Affected Resource(s)

noticed that if you try to create a resource that already exists within azure, terraform will automatically import it into its state, and take ownership of it

example: I've manually created a resource group and keyvault, both called "andytest"

I then add the resources to terraform config:

```hcl
data "azurerm_client_config" "current" {}

resource "azurerm_resource_group" "andytest" {
  name     = "andytest"
  location = "${var.region}"
}

resource "azurerm_key_vault" "keyvault" {
  name                            = "andytest"
  location                        = "${azurerm_resource_group.andytest.location}"
  resource_group_name             = "${azurerm_resource_group.andytest.name}"
  tenant_id                       = "${data.azurerm_client_config.current.tenant_id}"

  enabled_for_disk_encryption     = true
  enabled_for_deployment          = true
  enabled_for_template_deployment = true

  sku {
    name = "standard"
  }
}
```

and run terraform apply

terraform not only applies successfully, but adds these to its state - this could inadvertently allow you to delete existing resources

### Expected Behavior

In other providers (aws) terraform will notice a resource already exists, and refuse to apply over the top, or add to state without explicitly telling it to via a data source

### Actual Behavior

in my case i applied a resource, noticed it clashed with something that already existed, renamed in terraform and ran apply again, and it deleted the existing resource

* #0000

**Comment by tombuildsstuff** [comment]
hi @AndyMoore 

Thanks for opening this issue :)

This is planned to be fixed 2.0 ([which is outlined here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2807) - the fix is already merged into the codebase (and is feature-flagged) - [more information is available here](https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html#changes-when-importing-existing-resources).

Since this is planned to be fixed in 2.0 (and there's a workaround) I'm going to close this issue for the moment - but please subscribe to #2807 for updates.

Thanks!
