### ISSUE TITLE
Connection Strings for GlobalDocumentDB

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3568]
In the Azure panel I can see the connection strings alongside the keys, is it possible retrieve them in terraform for a GlobalGocumentDB?

**Comment by tombuildsstuff** [comment]
hi @cdesewell

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). In this instance [you should be able to access this using this property](https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html#connection_strings).

Thanks!
