### ISSUE TITLE
Application Gateway as module

### ISSUE THREAD

**Issue by SirWayne** [terraform-providers/terraform-provider-azurerm#3588]
We have a module for the Application Gateway. Now i would like to disable some  rule group with the inline block `disabled_rule_group`, but how can I make this configurable in the module?

Example
```
resource "azurerm_application_gateway" "AppGateway" {

# how can i make this 0-n block configurable 
disabled_rule_group {
  rule_group_name = "REQUEST-931-APPLICATION-ATTACK-RFI"
  rules           = [
    931100]
}

disabled_rule_group {
  rule_group_name = "REQUEST-942-APPLICATION-ATTACK-SQLI"
  rules           = [
    942100,]
}
```

Anybody an idea? We use terraform 0.11.x

**Comment by tombuildsstuff** [comment]
hi @SirWayne 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow).

Thanks!

**Comment by SirWayne** [comment]
Hi @tombuildsstuff,

but on  this way you will get no answer. Tried it more than 1 times.  There are no answer on the gitter channel.  But yes i could create a a stackoverflow question.
