### ISSUE TITLE
Issue #1635

### ISSUE THREAD

**Issue by kyle-winkelman** [terraform-providers/terraform-provider-azurerm#3595]
I have a similar issue as #2332 but I am unable to identify the current state or any additional information as issue #1635 appears to not exist, even though it is referenced in many other issues. I apologize for not following the outlined issue template, but thought it would be pointless to duplicate #2332. I am just hoping for an understanding of the outcomes of #1635 and any steps I can take to avoid the issue.

**Comment by kyle-winkelman** [comment]
I may have found my answer in terraform-providers/terraform-provider-azuread#4. It appears there is a replication/retry/timing issue when creating applications and service principals. Two PRs have been merged and targeted for the 0.4.0 release of the azuread provider.

If someone could confirm my findings that would be nice and giving an estimate when the 0.4.0 release will occur would be amazing!

**Comment by tombuildsstuff** [comment]
@kyle-winkelman it appears Github isn't auto-redirecting those issues, which is unfortunate - but yes they look to be the same underlying cause. That issue's been fixed by one of several PR's to handle the eventual consistencies in Azure Active Directory - so whilst I can't give a timeframe at this point, it's part of the 0.4.0 milestone which is mostly done :)

Since this appears to have been resolved I'm going to close this issue for the moment.

Thanks!

**Comment by kyle-winkelman** [comment]
Thank you for the confirmation! It's not just no auto-redirection, I even tried manually going through all issues and its like #1635 disappeared.
