### ISSUE TITLE
Add support for list* Resource Functions

### ISSUE THREAD

**Issue by stack72** [terraform-providers/terraform-provider-azurerm#3607]
This will allow the operations listed in https://docs.microsoft.com/en-us/azure/azure-resource-manager/resource-group-template-functions-resource#list to be added as datasources

These types of operations are necessary for operations like listing Query keys from Azure Search etc

**Comment by tombuildsstuff** [comment]
hi @stack72 

Thanks for opening this issue.

Rather than exposing these as separate Data Sources/Resources, since this information requires some additional information (for example, the App Service Name and Resource Group) - we're instead nesting this information within those Resources/Data Sources as appropriate. In the specific example above - the keys from Azure Search are available as a part of the Search Service resource, which were added in https://github.com/terraform-providers/terraform-provider-azurerm/issues/1873.

If that doesn't fit your needs (or you've got other examples) please feel free to open specific issues and we'll take a look - but unfortunately given this requires additional information to look this data up (which we require in the Data Sources anyway) - we have no plans to expose this information as separate Data Sources/Resources at this time.

Thanks!
