### ISSUE TITLE
'"os_profile_windows_config"; cannot have more than 1' Error for Azure Vm Creation in Terraform v0.12

### ISSUE THREAD

**Issue by petr-x** [terraform-providers/terraform-provider-azurerm#3622]
**Terraform (and AzureRM Provider) Version**
Terraform v0.12
provider.azurerm: version = "~> 1.28

**Affected Resource(s)**
azurerm_virtual_machine

**Error**
Error: too many items for attribute "os_profile_windows_config"; cannot have more than 1

**Root cause**
property: "provision_vm_agent = true" in

```
os_profile_windows_config { 
    provision_vm_agent = true
}
```

is only possible to add/change when creating new VM. Otherwise you will get the error above

**Proposal**
1. The property should be set to "true" as the VM without the Agent is limited (i.e. add extensions will fail without the agent). 
https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/agent-windows

2. Change of the property should force new resource

**Comment by osmanysahin** [comment]
HI Is there any development with this issue. I have the same problem and need to enable extensions.

**Comment by tombuildsstuff** [comment]
hi @petr-x @osmanysahin 

Thanks for opening this issue.

Taking a look through it appears this was a bug in an early version of Terraform 0.12 which has since been fixed where the correct error wasn't being raised here - would you be able to take a look and see if upgrading to the latest version of Terraform Core solves this for you?

Since this should be fixed by upgrading to the latest version of Terraform Core I'm going to close this issue for the moment however please let us know if that doesn't solve your issue and we'll take another look 👍 

Thanks!
