### ISSUE TITLE
Additional settings for API manager and stock Echo API / Products 

### ISSUE THREAD

**Issue by cdesewell** [terraform-providers/terraform-provider-azurerm#3649]
Currently looking at the docs it doesn't seem possible to: 

- Enable application insights 
- Disable subscription required

Additionally the stock 'Echo API' and 'Starter', 'Unlimited' products were created. Is there any way to prevent this via terraform?

https://www.terraform.io/docs/providers/azurerm/r/api_management_api.html

**Comment by tombuildsstuff** [comment]
hi @cdesewell 

Thanks for opening this issue.

We try and keep feature requests to one item per issue so that we can close features via the `fixes #XXX` text in PR's (rather than having meta issues which have historically remained open indefinitely) - as such since there's a specific issue open for the `Disable Subscription Required` feature request (#3863) I'm going to close this issue in favour of that one; would you mind subscribing to that one for updates?

For the configuring a connection between Application Insights and the API Management API - unfortunately the Application Insights API doesn't expose the functionality needed to link resources directly, however you should be able to achieve this using the `hidden-tags` [as outlined in this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1303).

Thanks!
