### ISSUE TITLE
Delete Subnet without first deleting NSG association, or create subnet with NSG association in one api call

### ISSUE THREAD

**Issue by ewierschke** [terraform-providers/terraform-provider-azurerm#3653]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm not sure if there is an easy terraform answer to this request but am looking for more control over potential creation and/or destruction sequence such that as an example, potentially a azurerm_subnet_network_security_group_association resource is created in the same API call(?) as the creation of the resource azurerm_subnet, and conversely that the destruction of the azurerm_subnet resource can not rely first on the successful destruction of the azurerm_subnet_network_security_group_association resource.

Background...
Our Azure environment has specific Azure Policy definitions associated that are outside of our control.
One such Azure Policy definition requires an NSG to be associated to each subnet.
With this policy definition applied to our subscription, terraform appears unable to create a azurerm_subnet with an NSG association in a 'single call' in order to meet the Azure Policy requirement.  A subnet can be created within the Azure Portal manually in what I might call a 'single call' as I'm able to create a new subnet to meet the Azure Policy definition requirement within the Portal.

The below example tf configuration fails to apply with the snippet of json representing part of the Azure Policy definition attached that has an effect of Deny.

```
    "policyRule": {
      "if": {
        "allOf": [
          {
            "value": "[resourcegroup().Name]",
            "notin": "[parameters('resourceGroupExceptions')]"
          },
          {
            "anyOf": [
              {
                "allOf": [
                  {
                    "field": "type",
                    "equals": "Microsoft.Network/virtualNetworks"
                  },
                  {
                    "not": {
                      "field": "Microsoft.Network/virtualNetworks/subnets[*].networkSecurityGroup.id",
                      "like": "/subscriptions/*"
                    }
                  }
                ]
              },
              {
                "allOf": [
                  {
                    "field": "type",
                    "equals": "Microsoft.Network/virtualNetworks/subnets"
                  },
                  {
                    "not": {
                      "field": "Microsoft.Network/virtualNetworks/subnets/networkSecurityGroup.id",
                      "like": "/subscriptions/*"
                    }
                  }
                ]
              }
            ]
          }
        ]
      },
      "then": {
        "effect": "Deny"
      }
    }
```

### New or Affected Resource(s)

* azurerm_subnet
* azurerm_subnet_network_security_group_association
* azurerm_subnet_route_table_association

### Potential Terraform Configuration

```hcl
data "azurerm_resource_group" "existingrg" {
  name     = "${var.rg_name}"
}

data "azurerm_network_security_group" "requiredNSG" {
  name     = "${var.nsg_name}"
  resource_group_name = "${data.azurerm_resource_group.existingrg.name}"
}

resource "azurerm_virtual_network" "newvnet" {
    name = "${var.vnet_name}"
    address_space = ["10.0.0.0/16"]
    location = "${data.azurerm_resource_group.existingrg.location}"
    resource_group_name = "${data.azurerm_resource_group.existingrg.name}"
}

resource "azurerm_subnet" "testsubnet" {
    name                 = "default"
    resource_group_name  = "${data.azurerm_resource_group.existingrg.name}"
    virtual_network_name = "${azurerm_virtual_network.newvnet.name}"
    address_prefix       = "10.0.0.0/24"
  }
  
resource "azurerm_subnet_network_security_group_association" "testsubnet" {
  subnet_id                 = "${azurerm_subnet.testsubnet.id}"
  network_security_group_id = "${data.azurerm_network_security_group.requiredNSG.id}"
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @ewierschke 

Thanks for opening this issue.

This is possible today by configuring the subnet association within the `azurerm_subnet` resource (using the `network_security_group_id` field (instead of using the `azurerm_subnet_network_security_group_association` resource) - however that functionality is deprecated and will be removed in version 2.0 of the Azure Provider. There's a bunch of reasons for this (mostly user experience related), but the main one is to work around a circular reference in Azure, where it's possible to create resources in any order; but on deletion you encounter an error where the Subnet deletion will fail unless the Network Security Group is detached first.

Whilst I understand this breaks the Azure Policy you've got here, the intention is to make this more reliable overall. Instead it should be possible to amend this policy to account for this, either:

* by only taking affect when the Subnet contains Network Interfaces (which should be accessible as a property on that)
* or by flipping this around and targeting Network Interfaces, to ensure that they're being attached to a Subnet with an NSG (in much the same manner you are today)

Since this is an intentional design decision to work around this circular reference in Azure (which the Portal does too in some places, since this can be detached in both places) - I'm not necessarily sure there's much more we can do for this unfortunately, and as such I'm going to close this issue for the moment.

Thanks!
