### ISSUE TITLE
Update of VM with managed disk fails

### ISSUE THREAD

**Issue by georgschmidtdumont** [terraform-providers/terraform-provider-azurerm#3656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12

### Affected Resource(s)

azurerm_virtual_machine

### Terraform Configuration Files

I am experiencing the same issue already covered by  #734. I am trying to implement the workaround mentioned in that issue and my question is how do I get the `image_reference_id` required by the `azurerm_managed_disk` resource?

My current setup is as follows:

Managed Disk
```hcl
resource "azurerm_managed_disk" "osdisk" {
  create_option        = "FromImage"
  name                 = "osdisk"
  location             = var.location
  resource_group_name  = var.resource_group_name
  storage_account_type = "Standard_LRS"
}
```

The VM
```hcl
resource "azurerm_virtual_machine" "JumphostVM" {
  location              = var.location
  name                  = "${var.environment}-jumphost-vm"
  network_interface_ids = [
    azurerm_network_interface.JumphostNetworkInterface.id]
  resource_group_name   = azurerm_resource_group.JumphostResourceGroup.name
  vm_size               = "Standard_DS1_v2"

  storage_image_reference {
    publisher = "microsoft_iot_edge"
    offer     = "iot_edge_vm_ubuntu"
    sku       = "ubuntu_1604_edgeruntimeonly"
    version   = "1.0.1"
  }

  plan {
    name      = "ubuntu_1604_edgeruntimeonly"
    product   = "iot_edge_vm_ubuntu"
    publisher = "microsoft_iot_edge"
  }

  storage_os_disk {
    create_option   = "Attach"
    name            = "osdisk"
    managed_disk_id = azurerm_managed_disk.osdisk.id
  }
}
```

I assume that I need to move the `storage_image_reference ` block into its own resource.

**Comment by tombuildsstuff** [comment]
hi @georgschmidtdumont 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow).

Thanks!
