### ISSUE TITLE
Error issuing create request for Redis Cache - InvalidApiVersionParameter

### ISSUE THREAD

**Issue by davidonus** [terraform-providers/terraform-provider-azurerm#3658]
Hi,

I am recieving an error that looks to be down to the create request using a no longer supported API version. Please see (edited) full error below:

Error: Error issuing create request for Redis Cache {REDIS-NAME} (resource group /subscriptions/{SUBID}/resourceGroups/{ResourceGROUP}): redis.Client#Create: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidApiVersionParameter" Message="The api-version '2018-03-01' is invalid. The supported versions are '2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

Is there anyway of me overcoming this or does it need a new release?

Apologies if this is my mistake and i've misunderstood it.

David Martin

**Comment by davidonus** [comment]
Seems very similar to this issue: 
https://github.com/hashicorp/terraform/issues/18100
There is also a reference to 2018-03-01 here which I assume is the underlying code? 
https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/resource_arm_redis_cache.go

**Comment by tombuildsstuff** [comment]
hi @davidonus 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

In this specific case it appears that one of the values (either `name` or `resource_group_name`) is an empty string (which would cause this misleading error; would you be able to double-check the value of these two fields? Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment, however please let us know if that doesn't work for you and we'll take another look.

Thanks!
