### ISSUE TITLE
Feature Request: API Management with virtual networks

### ISSUE THREAD

**Issue by NickMetz** [terraform-providers/terraform-provider-azurerm#3667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
It should be possible to use a API Management in combination with virtual network. This will make it more comfortable to use just internal backends instead of public backends with IP restrictions or client certificates. So this network configuration is not implemented in azurerm_api_management yet, it is also possible to use this feature with "Developer"  tier now (before it was only available in "Premium" tier).

### New or Affected Resource(s)

* azurerm_api_management

### Potential Terraform Configuration

```hcl
resource "azurerm_api_management" "test" {
  name                = "example-apim"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  publisher_name      = "My Company"
  publisher_email     = "company@terraform.io"

  network_type = "${networkType}"

  network_configuration {
    subnet_id  = "${subnetId}"
    vnet_id    = "${vnetId}"
    subnetname = "${subnetName}"
  }  

  sku {
    name     = "Developer"
    capacity = 1
  }
}
```

This is how it looks like from API prospective:
```
[...]
    "virtualNetworkType": "${networkType}"
    "virtualNetworkConfiguration": {
      "subnetResourceId": "${subnetId}",
      "vnetid": "${vnetId}",
      "subnetname": "${subnetName}"
    },
[...]
```

### References

* https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet

**Comment by tombuildsstuff** [comment]
hey @NickMetz 

Thanks for opening this issue :)

Whilst there's a PR which attempted to add support for this in https://github.com/terraform-providers/terraform-provider-azurerm/pull/2582 - unfortunately [this is blocked on a bug in the Swagger used to generate the Azure SDK](https://github.com/Azure/azure-rest-api-specs/pull/6065) - once that's fixed we'll be able to circle back around and take another look at this.

Since this is blocked on an upstream issue (but there's a PR blocked on this) - rather than keeping this issue open I'm going to close this issue in favour of the PR which adds support for this: https://github.com/terraform-providers/terraform-provider-azurerm/pull/2582 - once the upstream issue is resolved we'll re-open that PR and continue adding support for this.

Thanks!
