### ISSUE TITLE
azurerm_virtual_network does not delete inline block subnets

### ISSUE THREAD

**Issue by NickMetz** [terraform-providers/terraform-provider-azurerm#3693]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform Version: 0.12.2
AzureRM Provider Version 1.30.1

### Affected Resource(s)

* `azurerm_virtual_network`

### Terraform Configuration Files

```hcl
variable "subnet" {
  type        = list(map(string))
  description = "The subnet block support list of subnets"
  default = [
    {
      name           = "test1"
      address_prefix = "10.241.0.0/16"
    },
    {
      name           = "test2"
      address_prefix = "10.242.0.0/16"
    }
  ]
}
```

```hcl
resource "azurerm_resource_group" "netrg" {
  name     =  "example-rg"
  location =   "westeurope"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "example-vnet"
  location            = azurerm_resource_group.netrg.location
  resource_group_name = azurerm_resource_group.netrg.name
  address_space       = ["10.0.0.0/8"]

  dynamic "subnet" {
    for_each = var.subnet
    content {
      name           = lookup(subnet.value, "name", null)
      address_prefix = lookup(subnet.value, "address_prefix", null)
      security_group = lookup(subnet.value, "security_group", null)
    }
  }
}
```
```hcl 
output "vnet_subnet_id" {
  value = azurerm_virtual_network.vnet.subnet
}
```
### Expected Behavior
If we create a subnet with `azurerm_virtual_network` as inline block and remove this subnet inline block after vnet + subnet is created, i would expect terraform will destroy this subnets.  
Terraform should delete subnets if subnet block in `azurerm_virtual_network` is not defined anymore.

### Actual Behavior
Subnets still present even if not configured in `azurerm_virtual_network` anymore

* If we keep inline block an remove just one subnet this works without any problems
* If we just pass an empty subnet block, this will fail due "required fields is not set"

### Steps to Reproduce

1. Use above configuration and `terraform apply`
2. Remove configured subnets from variable subnet, so dynamic block is ignored.

### References

* #0000

**Comment by a-mcf** [comment]
Does anyone know of any workarounds for this?

**Comment by tombuildsstuff** [comment]
hi @NickMetz 

Thanks for opening this issue - apologies for the delayed response here!

Azure, and the Terraform Azure Provider allows Subnets to be specified in one of two ways:

1. Within the `azurerm_virtual_network` resource using the `subnets` block.
2. Using the separate `azurerm_subnet` resource

Since both use-cases are supported in Terraform, the `subnet` block within the `azurerm_virtual_network` resource is "Computed" - which means that if it's not specified we use the value provided by Azure, to account for this being managed by the separate resource (so that we don't for example, detect that these subnets should be deleted during a `terraform plan`).

As such, when defining subnets within the `azurerm_virtual_network` resource, rather than removing the `subnets` blocks (in which case we'll use the information from Azure) - you'll instead need to specify an empty array, for example:

```
resource "azurerm_resource_group" "netrg" {
  name     =  "example-rg"
  location =   "westeurope"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "example-vnet"
  location            = azurerm_resource_group.netrg.location
  resource_group_name = azurerm_resource_group.netrg.name
  address_space       = ["10.0.0.0/8"]
  subnet = []
}
```

Would you be able to take a look and see if that works for you? Since this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
