### ISSUE TITLE
Not able to add data disk in the vm when user input 2

### ISSUE THREAD

**Issue by pswalia06** [terraform-providers/terraform-provider-azurerm#3712]
resource "azurerm_managed_disk" "az_managed_disk" {
  count                = "${var.data_disk_count}"
  name                 = "${format("%s%02d", var.name, count.index + 1)}-datadisk"
  location             = "${var.location}"
  resource_group_name  = "${var.resource_group}"
  storage_account_type = "${var.managed_disk_type}"
  create_option        = "Empty"
  disk_size_gb         = "${var.data_disk_size}"

  tags = {
    environment = "staging"
  }
}

resource "azurerm_virtual_machine" "az_virtual_machine" {
  count                         = "${var.node_count}"
  name                          = "${var.name}-disk${count.index+1}"
  location                      = "${var.location}"
  resource_group_name           = "${var.resource_group}"
  network_interface_ids         = ["${element(azurerm_network_interface.az_network_interface.*.id, count.index)}"]
  vm_size                       = "${var.size}"
  delete_os_disk_on_termination = true

  resource "azurerm_virtual_machine_data_disk_attachment" "data_disk_attach" {
  count =   "${var.data_disk_count}"
  virtual_machine_id = "${azurerm_virtual_machine.az_virtual_machine[count.index - 1].name}"
  managed_disk_id    = "${azurerm_managed_disk.az_managed_disk[count.index].id}"
  lun                = "${floor((count.index +1) / ceil((count.index + 1) * 1.0 / var.data_disk_count)) - 1}"
  caching            = "ReadOnly"
  create_option      = "Attach"
}

Error: Invalid index

  on main.tf line 131, in resource "azurerm_virtual_machine_data_disk_attachment" "data_disk_attach":
 131:   virtual_machine_id = "${azurerm_virtual_machine.az_virtual_machine[count.index].id}"
    |----------------
    | azurerm_virtual_machine.az_virtual_machine is tuple with 1 element
    | count.index is 1

The given key does not identify an element in this collection value.

**Comment by tombuildsstuff** [comment]
hi @pswalia06 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) (such as Stack Overflow).

Thanks!
