### ISSUE TITLE
Terraform update is wiping app services

### ISSUE THREAD

**Issue by jkollin14** [terraform-providers/terraform-provider-azurerm#3734]
Hi,

When I run a `terraform update` on a module which contains app services which I have already created and configured, the update wipes the configuration of the app services. Is there a work around for this?

```
# App Service Plan
resource "azurerm_app_service_plan" "asp" {
  name                = "Name-${var.env}-01"
  location            = "${azurerm_resource_group.rg_ilb_ase.location}"
  resource_group_name = "${azurerm_resource_group.rg_ilb_ase.name}"

  sku {
    tier = "Isolated"
    size = "I1"
    capacity = 1
  }

  app_service_environment_id = "${var.ase_lookup_id}"
}

# App Service
resource "azurerm_app_service" "wap" {
  name                = "Name-${var.env}-02"
  location            = "${azurerm_resource_group.rg_ilb_ase.location}"
  resource_group_name = "${azurerm_resource_group.rg_ilb_ase.name}"
  app_service_plan_id = "${azurerm_app_service_plan.asp.id}"

  identity {
    type = "SystemAssigned"
  }  

  app_settings = {
      ....
  }
}
```

Thanks in advance for the help

**Comment by tombuildsstuff** [comment]
hi @jkollin14 

Thanks for opening this issue.

Existing Resources can be imported into Terraform [using the `terraform import` command](https://www.terraform.io/docs/import/index.html) which means that Terraform will manage all of the configuration settings for that resource. In this case the App Service has App Settings defined within Azure which aren't present in the Terraform Configuration defined in code; since running `terraform plan|apply` will ensure the state of the App Service in Azure matches the state defined in code - as such you'd need to update the Terraform Configuration to include these settings.

Thanks!
