### ISSUE TITLE
Error building AzureAD Client: 1 error occurred: * A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.

### ISSUE THREAD

**Issue by mikkoc** [terraform-providers/terraform-provider-azurerm#3772]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform 0.12.3
* Azure provider 1.31.0

### Affected Resource(s)

* `azurerm_client_config`

### Terraform Configuration Files

```hcl
variable "management_subscription_id" {}

provider "azurerm" {
  version = "=1.31.0"

  subscription_id = "${var.management_subscription_id}"
}

data "azurerm_client_config" "current" {}
```

### Expected Behavior

The Terraform Plan should proceed as normal.

### Actual Behavior

```
Error: Error building AzureAD Client: 1 error occurred:
	* A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
```

### Steps to Reproduce

1.  `export ARM_CLIENT_ID=my-client-id`
2.  `export ARM_CLIENT_SECRET=my-client-secret`
3.  `export ARM_TENANT_ID=my-tenant-id`
4.  `export TF_VAR_management_subscription_id=my-subscription-id`
5. `terraform plan`

**Comment by rouxton** [comment]
Same problem here, it seems the only way for TF to get the subscription_id is through the ARM_SUBSCRIPTION_ID variable. Everything else is ignored

**Comment by tombuildsstuff** [comment]
hi @mikkoc @rouxton 

Thanks for opening this issue.

Taking a look into this it appears that the AzureAD Provider is/was previously being used in this directory, which is why this error message is being returned. If Terraform is still tracking resources from AzureAD (they still exist in Terraform's State File) then Terraform needs to be able to connect to the AzureAD instance to be able to determine if they've been removed, or should be destroyed. As such you should be able to add a provider block for AzureAD for this to work:

```
provider "azuread" {
  version = "=0.6.0"
}
```

Would you be able to take a look and see if that works for you? Since this is a question rather than a bug in the AzureRM Provider I'm going to close this for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
