### ISSUE TITLE
Azure authentication not available in official Terraform Docker image

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#3781]
With the fix for #502 being a switch to relying on the Azure CLI (#2387) and running `az account get-access-token` in a separate shell, the Terraform container `hashicorp/terraform` can not be used for AzureRM resources with provider versions >= 1.20.

I wanted to open this for discussion on what the preferred route would be here. I see options like:
* maintain a custom image with the Azure CLI added
* use Docker compose or similar and include the Azure CLI container
* pass variables to the provider block

Are there any other methods that would be preferable? Maintaining a new Docker container adds overhead and Docker compose may not be feasible with existing pipelines. Passing variables conditionally works, but it's not clean depending on the implementation.

**Comment by tombuildsstuff** [comment]
hi @mbrancato 

Thanks for opening this issue.

When running Terraform in automation (such as within Docker) we only support using a Service Principal for authentication - rather than the Azure CLI, which means unfortunately this use-case is unsupported (which is why this unintentionally stopped working in v1.20).

Whilst the options you've listed above may work, since this isn't a feature we support unfortunately we're unable to provide usage guidance here - as such unfortunately I'm going to close this issue for the moment.

That said I believe you should be able to get some more suggestions for this use-case from folks more familiar with Docker on Stack Overflow. However please be aware that since this use-case is unsupported it could break in a future release, and as such we'd instead recommend switching to a Service Principal for this use-case.

Thanks!

**Comment by mbrancato** [comment]
Hi @tombuildsstuff - maybe I wasn't clear that I **am** using a service principal, which this issue also affects. The use of a service principal does not solve this issue. The problem is that the provider (>1.2.0) relies on the Azure CLI to verify all types of Azure credentials (user/pass, MSI, or SP), and doesn't really care how authentication occurred.

As I mentioned, passing variables works but is not clean from a security perspective. Passing secrets on the command-line and placing secrets in the `provider` block of the file are functional, but not best practice. Again, the actual implementation specifics will determine how insecure these methods are.

Specifically, I'm using this in a pipeline and to achieve Terraform + Azure authentication I must now expose the service principal secret as a value in the pipeline. What I was trying to achieve was a process where the Azure CLI performed the service principal authentication, and passing that authentication to the container runtime (see https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV1).

I hope this helps explain the use-case and we can come up with a secure solution for Terraform + Azure using the official container image.

**Comment by tombuildsstuff** [comment]
hi @mbrancato 

> The problem is that the provider (>1.2.0) relies on the Azure CLI to verify all types of Azure credentials (user/pass, MSI, or SP), and doesn't really care how authentication occurred.

Terraform has [a list of authentication methods it supports](https://github.com/hashicorp/go-azure-helpers/blob/master/authentication/builder.go#L52-L55), which it goes down until it finds one that works - the Azure CLI is the last of these, which means that we'll only shell out to the `az` cli if that authentication methods used (everything else is done internally within the Provider).

> What I was trying to achieve was a process where the Azure CLI performed the service principal authentication, and passing that authentication to the container runtime (see https://github.com/microsoft/azure-pipelines-tasks/tree/master/Tasks/AzureCLIV1).

Unfortunately we don't support using the Azure CLI to authenticate as a Service Principal, since it doesn't store the same information for that authentication method as it does for a user authentication

As such instead since you're running within Azure I'd suggest using Managed Service Identity of the Build Agent you're running on, or a Service Principal - however unfortunately we don't support authenticating using the Azure CLI to authenticate using a Service Principal (and Terraform should return an error when this is the case).

Thanks!

**Comment by mbrancato** [comment]
Thanks @tombuildsstuff 
From what I can tell, the only way to authenticate without passing vars or having the secret in the Terraform code would be to use MSI authentication. That is probably the solution here for best practice. MSI brings its own challenges, but for Terraform it makes sense. Thanks for following up.
