### ISSUE TITLE
azurerm_virtual_machine_scale_set: Document zones better....

### ISSUE THREAD

**Issue by lrosenman** [terraform-providers/terraform-provider-azurerm#3810]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

AZ's are poorly documented, and warnings, etc are still issued for regions that support them.

It would be nice to upgrade the code to not warn for regions that support it, and in the docs
give examples of what the parameters look like. 

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References
```
zones - (Optional) A collection of availability zones to spread the Virtual Machines over.

Please Note: Availability Zones are only supported in several regions at this time.
``` 
(from https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html#zones )

* #0000

**Comment by MattMencel** [comment]
Hi @lrosenman... I've been working on a new data resource that will let you find the AZs for a VM SKU based on location.

#3798 

There's a little bit of work yet to do...

**Comment by drewmullen** [comment]
@lrosenman any chance you know what type of value this is looking for? int, string, list? im about to test using that variable this week

**Comment by lrosenman** [comment]
I've used:
```
 zones                = ["1", "2", "3"]
```

**Comment by lrosenman** [comment]
I still think we need to document all the places that AZ's can be used (I ran into needing to put a zone(s) on a public_ip today and making sure it matched the vm's (which I had spread across all 3 zones in eastus2).

**Comment by tombuildsstuff** [comment]
👋 

At this point in time the older `azurerm_virtual_machine_scale_set` resource has been superseded by the `azurerm_linux_virtual_machine_scale_set` and `azurerm_windows_virtual_machine_scale_set` resources. Since the older `azurerm_virtual_machine_scale_set` resource has fallen out of sync from the behaviour of the Azure API, to avoid unintentionally breaking users relying on this behaviour the older resources are feature-frozen.

As this resource (and it's documentation) is feature-frozen to maintain compatibility, I'm going to close this issue for the moment - but I'd recommend instead checking out the `azurerm_linux_virtual_machine_scale_set` resource, which better represents how the Azure API behaves for this resource and includes better documentation/examples of how to use Zones.

Thanks!
