### ISSUE TITLE
Output a list of map

### ISSUE THREAD

**Issue by JamesDLD** [terraform-providers/terraform-provider-azurerm#3855]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

Is this possible to output a list of map? 
This would be useful when using count (or the future foreach feature).
Usage sample : 
![image](https://user-images.githubusercontent.com/18073917/61273043-dae07c00-a7a8-11e9-83ba-eaaf8a2b5441.png)

Output sample : 
```hcl
 [
   {
       "vnetname1" : "vnetid1"
   },
   {
       "vnetname2" : "vnetid2"
   }
]
```

**Comment by tombuildsstuff** [comment]
hey @JamesDLD 

Thanks for opening this issue.

Since is a feature which would need to be implemented in Terraform Core (rather than something specific to the Azure Provider) - would you mind [re-opening this on their repository](https://github.com/hashicorp/terraform/issues) where that team can take a look?

Thanks!

**Comment by JamesDLD** [comment]
Ok done : https://github.com/hashicorp/terraform/issues/22077

**Comment by tombuildsstuff** [comment]
@JamesDLD thanks 👍
