### ISSUE TITLE
Why cannot we use Back recovery vault created in one resource group to attach to the resources in other Resource group?

### ISSUE THREAD

**Issue by sunnynazar** [terraform-providers/terraform-provider-azurerm#3873]
I have a backup module with below code.

resource "azurerm_recovery_services_vault" "vm" {
  name                       = "${var.recovery_vault_name}"
  location                   = "${var.location}"
  resource_group_name        = "${var.resource_group_name}"
  sku                        = "Standard"
}

resource "azurerm_recovery_services_protection_policy_vm" "vm" {
  name                       = "${var.vm_backup_policy_name}"
  resource_group_name        = "${var.resource_group_name}"
  recovery_vault_name        = "${azurerm_recovery_services_vault.vm.name}"
  timezone                   = "${var.timezone}"

  backup {
    frequency = "Daily"
    time      = "23:00"
  }

  retention_daily {
    count = 10
  }
}

Once this module is executed , i refer them in below code for attaching it to a VM.

resource "azurerm_recovery_services_protected_vm" "vm" {
  count                            = "${length(var.vm_hostnames)}"
  resource_group_name              = "${var.resource_group_name}"
  recovery_vault_name              = "${var.recovery_vault_name}"
  source_vm_id                     = "${element(azurerm_virtual_machine.vm-windows-with-datadisk.*.id, count.index)}"
  backup_policy_id                 = "${var.backup_policy_id}"
}

But , when i try to use the same backup vault for other resource group , it does not work .
If you try to do same with Azure portal , its possible , then why not with terraform?

Error :

Error: Error creating/updating Recovery Service Protected VM "VM;iaasvmcontainerv2;RG-network-DEV;vm-odb-p05" (Resource Group "RG-network-DEV"): backup.ProtectedItemsGroupClient#CreateOrUpdate: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: Service returned an error. Status=404 Code="ResourceNotFound" Message="The Resource 'Microsoft.RecoveryServices/vaults/RG-RECOVERY-VAULT004' under resource group 'RG-network-DEV' was not found."

  on ..\..\modules\windowsvmmaster\main.tf line 49, in resource "azurerm_recovery_services_protected_vm" "vm":
  49: resource "azurerm_recovery_services_protected_vm" "vm" {

**Comment by tombuildsstuff** [comment]
hi @sunnynazar 

Thanks for opening this issue.

Taking a quick look into this it appears that the resources are being created in either order since there's no dependencies defined within the code. Terraform uses a graph to determine which order resources should be created in, and without any hints it assumes that these can be created in any order; as such you should be able to [use Terraform's Interpolation Syntax](https://www.terraform.io/docs/configuration/expressions.html) to define these dependencies; for example:

```
resource "azurerm_resource_group" "test" {
  name = "hello"
  location = "West Europe"
}

resource "azurerm_recovery_services_protection_policy_vm" "test" {
  # ..
  resource_group_name = azurerm_resource_group.test.name
  # ..
}
```

Which will ensure that the Resource Group is created before the Protection Policy - would you be able to take a look and see if this works for you?

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but if that doesn't work for you I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!

**Comment by sunnynazar** [comment]
I think my query has not been understood properly , my question is that if we have a recovery vault created in one resource group and is there a way in terraform to use same recovery vault across different resource groups with different resources?
