### ISSUE TITLE
Default tags support

### ISSUE THREAD

**Issue by atrauzzi** [terraform-providers/terraform-provider-azurerm#3874]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I have a set of tags I specify for all my resources, would be nice if I could just write them once at the provider level. 😊

**Comment by tombuildsstuff** [comment]
hey @atrauzzi 

Thanks for opening this issue.

Whilst we don't support this functionality today - int he next major version of the Azure Provider (2.0) the `tags` block will go from being `Optional` & `Computed` to just `Optional` to fix a bug with Sentinel where the `tags` block cannot be used in policies. Given default tags would require this field being Optional & Computed - unfortunately this means that we'd be unable to support defining these centrally (for example) within the Provider block

That said it should be possible to achieve the same thing using either a locals block:

```hcl
locals {
  tags = {
    Hello = "World"
  }
}

resource "azurerm_resource_group" "test" {
  name = "hello"
  name = "West Europe"
  tags = var.tags
}
```

or by using Variables:

```hcl
variable "tags" {
  type = "map"
  default = {
    Hello = "World"
  }
}

resource "azurerm_resource_group" "test" {
  name = "hello"
  name = "West Europe"
  tags = var.tags
}
```

Whilst I appreciate this isn't the solution you were requesting - it is one that should work both today and going forwards - and is our recommended suggestion here. Since this isn't something we can/plan to support in the Azure Provider - whilst I'd like to thank you for opening this Feature Request I'm going to close this issue for the moment.

Thanks!

**Comment by atrauzzi** [comment]
Not really helpful at all. Did you suggest this unrelated solution just to put a positive spin on a non-response?

The whole point is to reduce the repetition of tag directives, thus also reducing the likelihood of accidental omission.

This should be reopened and left as a feature on the backlog.
