### ISSUE TITLE
azurerm_network_security_group assign to subnet

### ISSUE THREAD

**Issue by mariojacobo** [terraform-providers/terraform-provider-azurerm#3884]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Would love the possibility of creating an Azure NSG and assign it to an existing subnet.  I've checked all over and there doesn't seem to be a way of doing this, unless you first create the NSG and then define it in the subnet creation.  

I've checked https://github.com/terraform-providers/terraform-provider-azurerm/issues/664, however my scenario is a bit more complex. I deploy a vnetwith subnet, then an AKS cluster, then create the NSG which needs to belong to the Resource Group created by AKS ( MC*), otherwise Ingress creation fails to add the required rules. So the issue is that I cannot create the NSG first, because the RG MC* is not yet created.  For the MC* RG to be created, it needs the subnet, so the order needs to be respected. 

### New or Affected Resource(s)

* azurerm_network_security_group

### Potential Terraform Configuration

```hcl
  resource "azurerm_network_security_group" "aks-subnet-nsg" {
  name                            = "aks-subnet-nsg"
  location                        = "${azurerm_resource_group.aks.location}"
  resource_group_name = "${azurerm_kubernetes_cluster.aks.node_resource_group}"
  NEW_BLOCK                = "${azurerm.subnet.something.id}
}
```

### References

* #664

**Comment by tombuildsstuff** [comment]
hey @mariojacobo 

Thanks for opening this issue :)

Taking a look into this I believe this should be possible in the next release of the AzureRM Provider which includes the ability to specify the custom resource group in which the Kubernetes Cluster should be provisioned in.

Using this feature (which is coming in #3785) and [the `azurerm_subnet_network_security_group_association` resource](https://www.terraform.io/docs/providers/azurerm/r/subnet_network_security_group_association.html) it should be possible to first provision the AKS cluster, then create the NSG inside that resource group and the associate them using the `azurerm_subnet_network_security_group_association` resource. That said - if you're managing the Subnet from within Terraform until v2.0 of the Azure Provider (#2807) for the moment the association needs to be specified in both places; as such you may need to use the `ignore_changes` metaparameter on the `azurerm_subnet` resource to ignore that.

Since this is a question rather than an issue with the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
