### ISSUE TITLE
Azure Container Service: agent pool managed disks

### ISSUE THREAD

**Issue by sjdweb** [terraform-providers/terraform-provider-azurerm#390]
### Terraform Version
Terraform v0.10.7

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_container_service

### Terraform Configuration Files
```hcl
resource "azurerm_container_service" "test" {
  name                   = "acctestcontservice1"
  location               = "${azurerm_resource_group.test.location}"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  orchestration_platform = "DCOS"

  master_profile {
    count      = 1
    dns_prefix = "acctestmaster1"
  }

  linux_profile {
    admin_username = "acctestuser1"

    ssh_key {
      key_data = "$$$"
    }
  }

  agent_pool_profile {
    name       = "default"
    count      = 1
    dns_prefix = "acctestagent1"
    vm_size    = "Standard_A0"
    # new field
    storage_profile = "ManagedDisks"
    # new field
    disk_sizes_gb = [128, 128, 128, 128]
  }
}
```

You're able to use managed disks on ACS for agents ([see here](https://github.com/Azure/ACS/tree/master/docs/ManagedDisks)). [Example in RM JSON](https://github.com/Azure/ACS/blob/master/docs/ManagedDisks/azuredeploy.json#L137).

This is great as you get encryption at rest for free, along with other features that make the normal storage options look obsolete.

Is it possible to get this added to the azurerm provider? There may be other features missing that they have added recently.

**Comment by tombuildsstuff** [comment]
Hey @sjdweb 

Thanks for opening this issue :)

Taking a quick look into this - it appears this is dependent on the next version of the Container Service API/Swagger, which is used to generate the Azure SDK for Go (which we use to provision Container Services in Terraform). There's a [Github issue for this](https://github.com/Azure/azure-rest-api-specs/issues/1386) here - where it's been advised this should be available in mid-November (and thus I'd presume this will be in the end of November release of the Azure SDK for Go). Once that's in - we can look at adding support for this :)

Thanks!

**Comment by sjdweb** [comment]
Hey @tombuildsstuff - thanks for getting back so quick. I suspected it might be the case the SDK was out of date! Lots of change in ACS since I've started using it and quite hard to keep up. Look forward to them releasing an update in November.

Cheers

**Comment by dcherniv** [comment]
Any news on this? https://www.terraform.io/docs/providers/azurerm/r/container_service.html still doesnt reflect the managed disks.

**Comment by sjdweb** [comment]
Hey @tombuildsstuff - looks like the issue blocking this has been closed due to a new PR with ACS/AKS related stuff. Will this SDK update make it into the azurerm provider?

**Comment by tombuildsstuff** [comment]
hi @sjdweb @dcherniv 

Apologies for the delayed update here!

Microsoft's recently announced [the deprecation of Azure Container Service in favour of Azure (Managed) Kubernetes Service](https://azure.microsoft.com/en-us/updates/azure-container-service-will-retire-on-january-31-2020/).

In preparation for this [we're deprecating the `azurerm_container_service` resource in version 1.20 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2481) - as such when using a `1.x` version of the AzureRM Provider the `azurerm_container_service` will continue to function until the API is removed on the 31st January 2020.

We plan to remove support for the `azurerm_container_service` resource in version 2.0 of the AzureRM Provider - should you wish to continue using the AzureRM Provider past this date you'll need to ensure your Provider block is pinned to a 1.x version, for example:

```
provider "azurerm" {
  version = ">= 1.0.0, <= 2.0.0"
}
```

alternatively you can pin the Provider block to a specific version ([more information about version pinning can be found on the Provider page](https://www.terraform.io/docs/configuration/providers.html)):

```
provider "azurerm" {
  version = "=1.19.0"
}
```

If you're using ACS with Kubernetes Microsoft's recommendation is to migrate to using Azure (Managed) Kubernetes Service (AKS) which is available as [the `azurerm_kubernetes_cluster` resource](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html) within Terraform.

Since the `azurerm_container_service` resource is being deprecated, I'm going to close this issue for the moment.

Thanks!
