### ISSUE TITLE
When creating kubernetes cluster I cannot label/tag the agents/nodes.

### ISSUE THREAD

**Issue by worldspawn** [terraform-providers/terraform-provider-azurerm#3907]
Theres no way (that I can see) to specify the labels to apply to the nodes created when provisioning a cluster. I would expect agent `agent_pool_profile` to accept a set of pairs.

Google's provider for example has this -> https://www.terraform.io/docs/providers/google/r/container_cluster.html#labels

https://kubernetes.io/docs/concepts/configuration/assign-pod-node/
https://www.terraform.io/docs/providers/kubernetes/r/deployment.html#node_selector

**Comment by lewalt000** [comment]
I am interested in this as well. I see it's possible to set `node_taints` in the `agent_pool_profile` settings, but there isn't a way to set labels.

https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#node_taints

**Comment by lewalt000** [comment]
@worldspawn - FYI, I realized AKS automatically creates a label with the agentpool name: `agentpool: <name>`.

So at least there is a default label that can be used to target node pools. Still, will be nice to be able to set additional labels via Terraform.

```
$ kubectl get nodes -l agentpool=small
NAME                            STATUS   ROLES   AGE     VERSION
aks-small-34239724-vmss000000   Ready    agent   3h52m   v1.12.8
```

**Comment by sagivle** [comment]
when can we expect this change?

**Comment by jluk** [comment]
Providing custom labels to persist on create/scale is on the roadmap, not available yet. Tracking issue via AKS is here: https://github.com/Azure/AKS/issues/1088

**Comment by MacTynow** [comment]
Hi @jluk, I'm confused because I can see references to custom labels in https://github.com/Azure/aks-engine/blob/master/examples/kubernetes-labels/kubernetes.json as well as https://github.com/Azure/aks-engine/blob/8f5de6d71f67c1b3f618338626f7e86a8ea98727/pkg/api/types.go#L547.

Do you mean that this doesn't work yet or that the behavior is different from using `--kubelet-extra-args '--node-labels=foo=bar`?

**Comment by tombuildsstuff** [comment]
hey @worldspawn @lewalt000  @MacTynow 

Thanks for opening this issue - apologies for the delayed response here!

Based on @jluk's comment since this functionality isn't available in AKS's public API yet, rather than leaving this open without an actionable task within this repository, I'm going to temporarily close this issue in favour of the upstream issue: https://github.com/Azure/AKS/issues/1088 - but once support for this is available in AKS's public API we should be able to re-open this and take another look

Thanks!
