### ISSUE TITLE
max_retries for provider "azurerm" 

### ISSUE THREAD

**Issue by Peter-Sternberger** [terraform-providers/terraform-provider-azurerm#3908]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When testing terraform deployments in an automated way, from time to time sporadic hiccups concerning the network connection to azure can be observed, e.g.:

14:23:44 * azurerm_resource_group.rg-cf: azurerm_resource_group.rg-cf: Error reading resource group: resources.GroupsClient#Get: Failure sending request: StatusCode=0 -- Original Error: Get https://management.azure.com/subscriptions/d3a8f57e-80fe-4ced-a1b1-c42b61584071/resourcegroups/rg-ci-iaas-02-azure?api-version=2018-05-01: read tcp 172.17.0.4:42336->13.87.15.139:443: read: connection reset by peer[0m

These break the tests showing false positives.

We realized that other providers, like e.g. AWS, can deal with this problem by defining "max_retries" in its provider  (https://www.terraform.io/docs/providers/aws/index.html):

provider "aws" {
  region = "…"
  access_key = "…"
  secret_key = "…"
  max_retries = 10
}

I assume that such feature could make terraform deployments on azure much more robust. Wouldn't it make sense to have such feature for azure, too?

### New or Affected Resource(s)

provider "azurerm"

### Potential Terraform Configuration

...

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @Peter-Sternberger 

Thanks for opening this issue.

The Azure Provider shells out to [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) - which in turn shells out to [Go-AutoRest](https://github.com/Azure/go-autorest) to communicate with Azure. The Azure SDK for Go then exposes methods (e.g. `Create` and `WaitForCompletion`) which then create/read/poll as required using the functionality available within Go-AutoRest ([using it's Future's, which handles that for us (example)](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.36.1/azurerm/resource_arm_virtual_network.go#L189-L196)) - which handles retrying in the case of scenarios like Internal Server Errors, Rate Limiting and Dropped Connections).

A recent update to Go-AutoRest [fixed a bug around dropped connections](https://github.com/Azure/go-autorest/blob/master/CHANGELOG.md#v1302), such that these are retried automatically - and we've upgraded the version of Go-AutoRest being used fairly recently. Whilst we've seen these errors in our test suite in the past - since upgrading to the latest version of Go-AutoRest we've not seen this error in a while - as such I believe it's been fully patched within Go-AutoRest.

Due to this I believe that the underlying issue here's been resolved - and that any remaining issues regarding polling should be handled within Go-AutoRest, rather than exposing this internal behaviour here. As such whilst I'd like to thank you for this suggestion - I'm going to close this issue for the moment; but please let us know if you're still seeing this (once 1.37.0 is out, since that's what I'm referencing) - and we'll take another look / report upstream as necessary.

Thanks!
