### ISSUE TITLE
Terraform apply fails to upgrade in place when an azurerm_management_lock is set to ReadOnly

### ISSUE THREAD

**Issue by musicislife08** [terraform-providers/terraform-provider-azurerm#3961]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.5
+ provider.azurerm v1.32.0

### Affected Resource(s)

All Lockable azurerm resources

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
resource "azurerm_application_gateway" "main" {
  # ASE Backend Pool
  backend_address_pool {
    name         = "bep-ase-xm-msdn-cus"
    ip_addresses = ["10.177.34.11"]
  }

  ## Example Kube Api App
  backend_address_pool {
    name         = "bep-ea-example"
    ip_addresses = ["10.177.2.96"]
  }
  backend_http_settings {
    name                  = "http-ea-example"
    cookie_based_affinity = "Disabled"
    path                  = "/"
    port                  = 80
    protocol              = "http"
    request_timeout       = 1
  }
  http_listener {
    name                           = "listener-ea-example"
    frontend_ip_configuration_name = "frontend-public"
    frontend_port_name             = "https"
    host_name                      = "example-api.example.com"
    protocol                       = "Https"
    require_sni                    = true
    ssl_certificate_name           = var.cert-name
  }
  request_routing_rule {
    name                       = "rule-ea-example"
    rule_type                  = "Basic"
    http_listener_name         = "listener-ea-example"
    backend_address_pool_name  = "bep-ea-example"
    backend_http_settings_name = "http-ea-example"
  }  

  # Do NOT modify anything below this line.
  tags = {
    MangedBy = "Terraform"
  }

  name                = "wafv2-${var.company-shortname}-dmz${var.id}-${var.environment}-${var.location-code}"
  resource_group_name = var.resource-group-name
  location            = var.location
  enable_http2        = true
  sku {
    name = "WAF_v2"
    tier = "WAF_v2"
  }

  autoscale_configuration {
    min_capacity = 3
    max_capacity = 25
  }

  zones = [1, 2, 3]

  ssl_policy {
    policy_name = "AppGwSslPolicy20170401S"
  }

  ssl_certificate {
    name     = var.cert-name
    data     = data.azurerm_key_vault_secret.cert.value
    password = data.azurerm_key_vault_secret.cert-password.value
  }

  waf_configuration {
    enabled              = true
    firewall_mode        = "Detection"
    rule_set_type        = "OWASP"
    rule_set_version     = "3.0"
    file_upload_limit_mb = 500
  }

  gateway_ip_configuration {
    name      = "gwcfg-${var.company-shortname}-dmz${var.id}-${var.environment}-${var.location-code}"
    subnet_id = data.azurerm_subnet.main.id
  }

  frontend_port {
    name = "https"
    port = 443
  }

  frontend_ip_configuration {
    name                 = "frontend-public"
    public_ip_address_id = azurerm_public_ip.main.id
  }

  frontend_ip_configuration {
    name                          = "frontend-private"
    subnet_id                     = data.azurerm_subnet.main.id
    private_ip_address_allocation = "Static"
    private_ip_address            = var.private-ip
  }
}

resource "azurerm_management_lock" "gateway" {
  name       = "lock-wafv2-${var.company-shortname}-dmz${var.id}-${var.environment}-${var.location-code}"
  scope      = azurerm_application_gateway.main.id
  lock_level = "ReadOnly"
  notes      = "Terraform Managed Resource: Changes only allowed via code"
}

resource "azurerm_management_lock" "gateway-ip" {
  name       = "lock-pia-${var.company-shortname}-dmz${var.id}-${var.environment}-${var.location-code}"
  scope      = azurerm_public_ip.main.id
  lock_level = "ReadOnly"
  notes      = "Terraform Managed Resource: Changes only allowed via code"
}
```

### Debug Output

https://gist.github.com/musicislife08/31a7799e1dfe0ae9e303a802d279f564

### Expected Behavior

Terraform should recognize that the resource is locked and unlock it before trying to update any settings 

### Actual Behavior

Terraform does not check for locks and fails to update in place due to the management lock

### Steps to Reproduce

Create any azurerm_* resource and then create an azurerm_management_lock resource to lock it.
Then make a non destroying change like updating a setting so terraform will try an update in place and watch it fail due to not removing the lock

### Important Factoids

We would love to have this working so that we can have the terraform managed resources in azure be locked from being changed in the portal to prevent any issues as we move the company to Infrastructure as code.

### References

* #0000

**Comment by musicislife08** [comment]
Anyone want to take a look?  I am surprised more people are not running into this use case.

**Comment by tombuildsstuff** [comment]
hi @musicislife08 

Thanks for opening this issue.

As you've mentioned, Locks in Azure allow changes to be prevented from being made to resources as required - and crucially can be set at a bunch of different levels (Management Groups, Subscriptions, Resource Groups and Resources). Given this and the way that Terraform works (insofar as the Provider is invoked for each resource) there's no way of determining which Lock would need to be removed at this time.

Unfortunately this means that at this time it's not really feasible for a Terraform Provider (in this case Azure) to dynamically lock/unlock resources prior to changes - without a change in Terraform Core that supports this. As such, whilst there's not a lot we can do to work around this in the Azure Provider at this time - I'm going to suggest [opening an issue on Terraform Core](https://github.com/hashicorp/terraform/issues) so this functionality could be added there.

In the interim there's (at least) a couple of different approaches here:

1. You could switch to a Delete lock, rather than a ReadOnly lock - since this'll allow changes to be made (but not deleting any resources)
2. If all changes are made through Terraform (and thus changes aren't made outside of Terraform: for example a CI Server runs Terraform) - you can use Terraform's `lifecycle` block to prevent this resource from being destroyed.
3. You can use a custom role in Azure to ensure that users are unable to delete resources manually

Since this functionality would require changes in Terraform Core to be usable - for the moment I'm going to close this issue and suggest opening an issue there instead.

Thanks!
