### ISSUE TITLE
Terraform Azure vm custom_data bash script 

### ISSUE THREAD

**Issue by mariojacobo** [terraform-providers/terraform-provider-azurerm#3972]
I'm deploying an Azure VM and trying to run a script to partition a data disk and mount it upon provisioning. I've been using _"custom_data"_, but for some reason it's not working. When I login into the VM, the script is nowhere to be found and nothing is executed.  Terraform apply succeeds without errors. Any clues ? or perhaps I have the wrong setup here.  

As per Terraform docs:  custom_data - (Optional) Specifies custom data to supply to the machine. On Linux-based systems, this can be used as a cloud-init script. On other systems, this will be copied as a file on disk. Internally, Terraform will base64 encode this value before sending it to the API. The maximum length of the binary array is 65535 bytes.

```
resource "azurerm_virtual_machine" "middleware_vm" {
    name                  = "${var.middleware_vm}"
    location              = "${var.location}"
    resource_group_name   = "${azurerm_resource_group.middleware.name}"
    network_interface_ids = ["${azurerm_network_interface.middleware.id}"]
    vm_size               = "Standard_DS4_v2"        

    storage_os_disk {
        name              = "centos_os_disk"
        caching           = "ReadWrite"
        create_option     = "FromImage"
        managed_disk_type = "Premium_LRS"
    }

    storage_data_disk {
        name                 = "managed_backup_disk"
        create_option        = "Empty"
        caching              = "ReadWrite"
        disk_size_gb         = "256"  
        managed_disk_type    = "Premium_LRS"
        lun                  = 0
    }

    storage_image_reference {
        publisher = "OpenLogic"
        offer     = "CentOS"
        sku       = "7.5"
        version   = "latest"
    }

    os_profile {
        computer_name  = "${var.middleware_vm}"
        admin_username = "middlewareadmin"
        custom_data    = "${file("scripts/middleware_disk.sh")}"
        #custom_data    = "${path.root}/scripts/middleware_disk.sh"
  }
```

**Comment by kgopi1** [comment]
Hi, 
Script would be copied to /var/lib/waagent/CustomData. Currently custom_data supports in Ubuntu.https://azure.microsoft.com/en-gb/blog/custom-data-and-cloud-init-on-windows-azure/. 

In My case , this custom data is copied to location in Windows VM and i'm running unattend_config to execute the powershell script , but only the script is copied and not excuting ..

**Comment by tombuildsstuff** [comment]
hi @mariojacobo 

Thanks for opening this issue - apologies for the delayed response here.

Taking a look into this as @kgopi1 has mentioned the behaviour of the Custom Data field changes depending on the underlying OS. For Linux systems - this is used as a Cloud Init script, and as such gets executed automatically, however on Windows systems this file is just written to disk (as you're seeing) and as such you'll need to call this script - there's several methods available to do this.

As such, you should be able to invoke this script via SysPrep (using the `additional_unattend_config` block ([as seen here](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/examples/virtual-machines/vm-joined-to-active-directory/modules/active-directory/2-virtual-machine.tf#L41-L54)), or by using the `azurerm_virtual_machine_extension` resource or a "remote-exec" provisioner.

Since this is a question rather than a bug in Terraform I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
