### ISSUE TITLE
IaaSDiagnostics Installation fails targeting to Windows server

### ISSUE THREAD

**Issue by con-ran** [terraform-providers/terraform-provider-azurerm#4008]
This is smiliar to the issue of:  "IaaSDiagnostics Installation fails targetting to Windows server #2943"

Hello All,

I'm having a similar issue but I think it's my terraform code. Any help is highly appreciated. I'm newbish into coding so I think I may be missing something. I did follow terraform's structure and the original post here for context. I did remove some items from the configuration as I didn't need them.

Am I supposed to be using a json config file where the "xmlCfg": "${base64encode(var.diagnostics_config)}" points to? or an xml file?

I've attached both my terraform config for the extension and my xml config file.

########################

Here's the error I receive:

Error: Code="VMExtensionProvisioningError" Message="VM has reported a failure when processing extension 'IaaSDiagnostics'. Error message: "Exception when parsing configuration: Error: The element 'PublicConfig' in namespace 'http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration' cannot contain text. List of possible elements expected: 'WadCfg, LocalResourceDirectory, StorageAccount, WadCfgBlob, StorageType' in namespace 'http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration'. line: 1 column: 100\r\n See the troubleshooting guide to diagnose the problem: https://go.microsoft.com/fwlink/?linkid=852271\"."

on APP.tf line 162, in resource "azurerm_virtual_machine_extension" "MicrosoftInsightsVMDiagnostics-app_vm":
162: resource "azurerm_virtual_machine_extension" "MicrosoftInsightsVMDiagnostics-app_vm" {

########################
[Azure Diagnostics Terraform Code.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/3468194/Azure.Diagnostics.Terraform.Code.txt)
[Azure Diagnsotics Extensions XML configuration file.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/3468195/Azure.Diagnsotics.Extensions.XML.configuration.file.txt)

**Comment by tombuildsstuff** [comment]
hi @con-ran 

Thanks for opening this issue.

Taking a look into this it appears that the XML Configuration being provided isn't valid, historically we've noticed that the Azure VM Extension API is very particular about the configuration passed to it - and as such unfortunately we're unable to answer specific questions about which configuration should be used (since Terraform is just relaying this error from the Azure API).

As such unfortunately I'm going to close this issue for the moment - however I believe you should be able to get an answer to this on [the Virtual Machine Extensions repository](https://github.com/Azure/azure-linux-extensions) where someone more familiar with the required configuration for this VM Extension should be able to help :)

Thanks!
