### ISSUE TITLE
Support ICMP protocol on Azure NSG rules

### ISSUE THREAD

**Issue by stefan-rapp** [terraform-providers/terraform-provider-azurerm#4068]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need to set rules with ICMP protocol on Azure Network Security Groups (NSG). Currently only TCP and UPD is supported.

`protocol - (Required) Network protocol this rule applies to. Possible values include Tcp, Udp or * (which matches both).`

--> Dedicated ICMP is needed as well to block for example ping between VMs!

### New or Affected Resource(s)

azurerm_network_security_rule

* azurerm_XXXXX

### Potential Terraform Configuration

https://www.terraform.io/docs/providers/azurerm/r/network_security_rule.html

protocol - (Required) Network protocol this rule applies to. Possible values include Tcp, Udp or * (which matches both).

### References

![ICMP](https://user-images.githubusercontent.com/45358082/62935100-7a078c00-bdc6-11e9-8686-f4afabb54d75.png)

**Comment by ScottSorrentino** [comment]
I had a similar problem, needing to support ICMP in order to fully manage NSGs with Terraform in Azure.  It appears upstream supports use of ICMP, based on the response from September 9 in the above linked feature request for azure-sdk-for-go.

Adding `string(network.SecurityRuleProtocolIcmp)` to the appropriate place in `azurerm/resource_arm_network_security_group.go` (resourceArmNetworkSecurityGroup()) and `azurerm/resource_arm_network_security_rule.go` (resourceArmNetworkSecurityRule()), and building a custom version of the azurerm provider, seems to work.  Did not have any issues with `plan` or `apply` with "Icmp" specified as the protocol, and the resulting NSG rules appear as expected.

Are there other places within the project that would require updates to fully support ICMP rules?

**Comment by katbyte** [comment]
This was fixed by #3937 and released in v1.36 of the provider! as such i am going to close it
