### ISSUE TITLE
AKS using VMSS doesn't have an attribute reference for VMSS ID

### ISSUE THREAD

**Issue by lanmalkieri** [terraform-providers/terraform-provider-azurerm#4079]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version:  0.11.13
Azure Provider version: latest

### Terraform Configuration Files

```hcl
  agent_pool_profile {
    vnet_subnet_id  = "${var.vnet_subnet_id}"
    name            = "${var.name}"
    count           = "${var.agent_count}"
    vm_size         = "${var.vm_size}"
    os_type         = "${var.os_type}"
    os_disk_size_gb = "${var.os_disk_size_gb}"
    type            = "VirtualMachineScaleSets"
  }
```

### Issue

Currently when creating VMSS via the AKS resource by specifying the type as VMSS, there is no way to attribute the resulting VMSS ID. This means that the VMSS ID is lost and there is no programmatic way (outside a custom data source) to reference the resulting VMSS ID for scenarios like when creating/using the Azure App GW Ingress controller, which requires information about the VMSS ID. 

When AKS creates VMSS, there should be possibility for outputting the VMSS ID as an output so it can be referenced as a module output or remote state object.

**Comment by tombuildsstuff** [comment]
hi @lanmalkieri 

Thanks for opening this issue.

Taking a look into this unfortunately it appears that this information isn't available in the Azure API - and as such whilst the ID of the VM Scale Set may be predictable (insofar as we could hard-code it) there's been sufficient breaking changes within the AKS API that it'd be better to retrieve this information from the API should this change under our feet.

As such I'd suggest [opening an issue on the AKS Repository](https://github.com/Azure/AKS/issues) where the AKS Team should be able to take a look into exposing this functionality. Once that's been added to the AKS API / Go SDK then we should be able to take a look into exposing this in Terraform - however since this is currently dependent on that functionality becoming available in the AKS API I'm going to close this issue for the moment.

Thanks!
