### ISSUE TITLE
Enable Continuous deployment Option with private registry (ACR) in Azure app service?

### ISSUE THREAD

**Issue by siddthota** [terraform-providers/terraform-provider-azurerm#4090]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

Just wondering, if there is an option to manage Continuous deployment in Azure App Service Container Settings Page. 
Is there any way to copy the webhook uri into a variable or a property like data, that I can make use of?

<img width="1452" alt="Screen Shot 2019-08-14 at 11 03 27 AM" src="https://user-images.githubusercontent.com/8191897/63032176-522a2e00-be83-11e9-8d87-b6057bfd56cd.png">

**Comment by tombuildsstuff** [comment]
hi @siddthota 

Unfortunately whilst this field may exist in the API we don't expose this today. That said it should be possible to add it - so that we can track this would you mind opening a Feature Request with the issue template filled out (e.g. a link to the documentation/use case you're trying to solve)?

Thanks!

**Comment by siddthota** [comment]
Sure... sounds good. Will open a Feature Request.

Thanks!
