### ISSUE TITLE
Add REST API Support For Missing Features

### ISSUE THREAD

**Issue by opticyclic** [terraform-providers/terraform-provider-azurerm#4120]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Not _everything_ in Azure is covered by this provider.

Until the feature requests/bugs are completed for the parts you need, current deployments need to be supplemented with az cli or calls to the MS REST API directly.

For instance, when you create an API Management instance with terraform it also creates an "Echo API" and "Starter" and "Unlimited" products that can't currently be deleted with terraform and have to be removed with the REST API (not even supported by az cli).

It's not clear how to do this cleanly. e.g. 
- should it be done within terraform using local-exec/null resource?
- should it be done separately after terraform has run?
- will using these tools potentially break the terraform state?

Therefore, a resource that provides first class support for calling the REST API and/or the az cli would be useful to work with features that aren't implemented yet.

**Comment by tombuildsstuff** [comment]
hi @opticyclic 

Thanks for opening this issue.

> should it be done within terraform using local-exec/null resource?

There's multiple ways you can achieve this and unfortunately it varies depending on the environment you're running in; you can use [the `azurerm_template_deployment` resource](http://terraform.io/docs/providers/azurerm/r/template_deployment.html) to deploy an ARM Template from within Terraform - or shell out to the Azure CLI using the `null_resource` as you've mentioned.

> will using these tools potentially break the terraform state?

They shouldn't (since the Schema's should still be the same) - but unfortunately the answer here is "it depends" - if you're changing a resource which Terraform has modified, if Terraform needs to change that resource (for example, updating a tag) - it's likely these changes will be reset.

Due to the Azure API's not necessarily returning responses matching the defined schema (the Azure API can return the representation of a resource at the last time it was modified, which could vary from the current schema) the Azure Provider is mostly coded defensively, which /should/ handle this (but we can't guarantee) will catch this.

> Therefore, a resource that provides first class support for calling the REST API and/or the az cli would be useful to work with features that aren't implemented yet.

Unfortunately Terraform requires that the Schema is defined statically upfront - as such these two examples are dynamic resources/schema's which aren't something we'd be able to statically define upfront. In addition whilst the Azure API has common status codes defined - unfortunately not all API's necessarily follow these or have the same behaviours (for example, some are eventually consistent, others aren't).

As such we're unable to support this functionality - but instead you can use an ARM Template (via the `azurerm_template_deployment` resource) or the `null_resource` to call out to the Azure CLI as required.

---

Since this is a question rather than something we can action in the Azure Provider I'm going to close this issue for the moment.

Thanks!
