### ISSUE TITLE
Example Service Fabric Cluster Template

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#4174]
### Description

A working example should be provided of using this resource type "azurerm_service_fabric_cluster". 

Without an equivalent sample to the ARM template this terraform resource is completely pointless and a red herring. I see several issues (all closed) reporting the resource doesn't work and all responses pointing back to "in theory it does...but go figure it out, test it for us, and let us know if it actually works".

This is unacceptable.

**Comment by tombuildsstuff** [comment]
hi @markti 

Thanks for opening this issue.

The `azurerm_service_fabric_cluster` resource in Terraform provisions a Service Fabric Cluster - but doesn't provision/configure any nodes since that's additional configuration required on top of this resource (as is the case when provisioning an ARM Template). Instead Nodes for a Service Fabric Cluster need to be provisioned and managed separately - using a Virtual Machine Scale Set (to provision the instances) and an associated Virtual Machine Extension (to configure the Service Fabric Agent).

Taking a look at [the Terraform Registry](https://registry.terraform.io) it appears there's a module for this [on the Terraform Registry](https://registry.terraform.io/modules/Bee-Projects/sfabric/azure/0.1.1) - which provisions a Linux Virtual Machine Scale Set with the Service Fabric Agent which I believe should help here.

Whilst I can appreciate it's frustrating that there isn't an example of this in the `./examples` folder in the repository - if this doesn't work for you since the configuration for the Virtual Machine Extension is a [1:1 mapping from the ARM Template](https://github.com/Azure/azure-quickstart-templates/blob/master/service-fabric-secure-cluster-5-node-1-nodetype/azuredeploy.json#L421-L441) it should be possible to map this to Terraform. We're currently focused [on the tasks required for 2.0](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2807) and as such we're unfortunately not going to be able to add examples of both Linux and Windows nodes in the short-term, but this is something we should do at some point, in particular we're always happy to add examples to [the `./examples` folder](https://github.com/terraform-providers/terraform-provider-azurerm/tree/master/examples) if someone gets to that before we do :)

It's worth noting that the next version of Service Fabric - Service Fabric Mesh - provisions and manages the nodes for you such that this would be possible using native Terraform Resources (which is being tracked in #2486) rather than provisioning these yourself - however at the time of writing we've not gotten to this yet.

Since I believe [the module on the Terraform Registry](https://registry.terraform.io/modules/Bee-Projects/sfabric/azure/0.1.1) should solve this issue, I'm going to close this issue for the moment; but please let us know if that (or mapping the Extension from the ARM Template linked above) doesn't solve your issue and we'll take another look.

Thanks!

**Comment by markti** [comment]
I am reverse engineering my ARM template here. https://github.com/markti/terraform-servicefabric-cluster
