### ISSUE TITLE
changing the existing log analytic workspace of Security Center fails after 30 mins timeout

### ISSUE THREAD

**Issue by LaurentLesle** [terraform-providers/terraform-provider-azurerm#4193]
If you change an existing azure security center workspace (azurerm_security_center_workspace) with a new workspace, it fails after 30 mins

![image](https://user-images.githubusercontent.com/4702224/63993515-780e2e80-cb23-11e9-8893-11161e187c22.png)

A similar issue was reported in closed bug #2718 for creation and the timeout was extended from 15m to 30m.

The scenario here is different as I need to deal with a situation where I have to change the workspace that was set to a security centre

A possible improvement is to implement the new timeout block to go beyond 30 mins?

```
timeouts {
    create = "60m"
    delete = "2h"
  }
```

If I redo a terraform apply after the initial failure it completes successfully.

**Comment by tombuildsstuff** [comment]
hey @LaurentLesle 

Thanks for opening this issue.

We're planning on adding support for custom timeouts to all resources as a part of 2.0 (which we're working on the dependencies for at the moment) - as such we should be able to tackle this then. If it's helpful in the interim it could be possible to bump this timeout to an hour (as an example) - however this will ultimately be solved via custom timeouts which are being tracked in #417.

Rather than having multiple issues open tracking the same thing (since we plan to support this across all resources at once, as this is a behavioural change) I'm going to close this issue in favour of #171 - would you mind subscribing to that issue for updates?

Thanks!
