### ISSUE TITLE
Invalid operation. ClusterId cannot be null or empty.

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#4198]
I have been trying to reverse engineer an RGT template into a Terraform template that will provision a Service Fabric cluster given the limitation that 'azurerm_service_fabric_cluster' will only provision the service fabric cluster resource (which literally does nothing on its own) and there are no published examples of 'azurerm_service_fabric_cluster' actually being used to provision a Service Fabric working cluster.

I went through the RGT line by line and tried to reproduce it in Terraform as closely as I could. I've gotten a template together that provisions everything correctly except the VM scaleset (really the only part that truly matters). I've had to do some hard coding in the extension EOT strings because i'm pretty weak with Hashi syntax. I've been unable to _consistently_ resolve resource properties inside the EOT strings. For example, in the "VMDiagnosticsVmExt" extension I resolve the name of the diagnostics storage account (using the $${} notation). However attempting the same thing in the "ServiceFabricNodeVmExt" trying to reference the subnet's address prefix fails. Maybe there is something about "azurerm_subnet"'s 'address_prefix' field that makes it not able to resolve within other resources.

However these all seem to be minor issues that could be worked around by extracting out variables.

The big problem is that when my VM Scaleset launches it gives me the following error:

VM has reported a failure when processing extension 'ServiceFabricNodeVmExt'. Error message: "Invalid operation. ClusterId cannot be null or empty.".

The only place where I can see the extension might be linked to the service fabric cluster are here:

1. Inside the 'ServiceFabricNodeVmExt' settings there is a property called 'clusterEndpoint'
2. The VM scaleset is tagged with a "resourceType"="Service Fabric" and "clusterName"="<your cluster name>" tags.

Other than that I don't see any other tangible references to the service fabric cluster.

Here is my [code](https://github.com/markti/terraform-servicefabric-cluster).

**Comment by markti** [comment]
@tombuildsstuff its also a bit related to VM Scaleset resource type as well...

**Comment by markti** [comment]
@tombuildsstuff added a link to my terraform code on github

**Comment by tombuildsstuff** [comment]
hi @markti 

Thanks for opening this issue.

Whilst we're unable to help with questions in this repository (we use the issues in this repository to track bugs/feature requests in the Azure Provider) - since the VMSS Extension takes a JSON Blob, it should be possible to debug this by creating a template and outputting that; for example:

```hcl
resource "azurerm_service_fabric_cluster" "test" {
  # ..
}

locals {
  template = <<JSON
{
  "example": "key",
  "id": "${azurerm_service_fabric_cluster.test.id}"
}
JSON
}

output "template" {
  value = "${locals.template}"
}
```

.. which should output this to screen; and you can then either reuse this variable in the resource itself, or move the HEREDOC string into the VM Extension configuration.

Taking a look at the specific error message being returned from the API: `"Invalid operation. ClusterId cannot be null or empty."` I have a feeling this is from a cached VM Extension. Unfortunately Azure treats VM Extensions slightly different to other resources, where they won't be re-run on existing machines (either Virtual Machines or VMSS Instances) - as such I've found it's generally better to recreate the VMSS when updating the Extension if possible. Whilst of course that takes a while - the simplest option to debug this will be to output this configuration to screen/disk first; then try it with a VMSS.

Since this is a question rather than an issue with the Azure Provider I'm going to close this issue for the moment - but I'm hopeful that should help solve this for you, but if that doesn't work for you I'd suggest checking out [one of the community resources instead](https://www.terraform.io/community.html) ([such as the community forum](https://discuss.hashicorp.com/c/terraform-providers/tf-azure)).

Thanks!
