### ISSUE TITLE
Option `os_profile_linux_config.ssh_keys` gets ignored when using managed disks

### ISSUE THREAD

**Issue by faucct** [terraform-providers/terraform-provider-azurerm#4207]
Let's say I have two machines with terraform installed.
First, while using the first terraform machine, I provision a VM and create its disk snapshot. When I am trying to provision another machine from this snapshot from first terraform machine, I am able to connect to it. But when I go to another terraform machine, create another VM from the snapshot and try to connect to it via SSH, I get an unknown pubkey error, as only first terraform machine's key is authorized there.
Here is an example config:

```
resource "azurerm_managed_disk" "manager" {
  name                 = "${var.prefix}-manager"
  location             = "${azurerm_resource_group.main.location}"
  resource_group_name  = "${azurerm_resource_group.main.name}"
  storage_account_type = "Standard_LRS"
  create_option        = "Copy"
  source_resource_id   = "${data.azurerm_subscription.current.id}/resourceGroups/FlamestreamBenchmarks/providers/Microsoft.Compute/snapshots/FlamestreamBenchmarks"
  disk_size_gb         = "30"
}

resource "azurerm_virtual_machine" "manager" {
  name                  = "${var.prefix}-manager"
  location              = "${azurerm_resource_group.main.location}"
  resource_group_name   = "${azurerm_resource_group.main.name}"
  network_interface_ids = ["${azurerm_network_interface.manager.id}"]
  vm_size               = "Standard_B1ms"

  delete_os_disk_on_termination = true
  delete_data_disks_on_termination = true

  storage_os_disk {
    name              = "${azurerm_managed_disk.manager.name}"
    caching           = "ReadWrite"
    create_option     = "Attach"
    managed_disk_id   = "${azurerm_managed_disk.manager.id}"
    os_type           = "Linux"
  }
  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      key_data = file("~/.ssh/id_rsa.pub")
      path = "/home/ubuntu/.ssh/authorized_keys"
    }
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @faucct 

Thanks for opening this issue.

Taking a quick look at this, in this case Azure configures SSH keys on the Virtual Machine using the VM Agent which runs on the machine. When creating images (or duplicating Virtual Machines) it's recommended to run `sysprep` on a Windows machine/[the VM agent deprovisioning script on a Linux machine `waagent -force -deprovision+user`](https://github.com/Azure/WALinuxAgent#commands) which I believe should be what's needed here.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!

**Comment by faucct** [comment]
I think this should solve my issue. Thanks!

**Comment by faucct** [comment]
It does not help: now I am unable to authenticate event from the machine a snapshot is created from. Do you have any ideas why?
