### ISSUE TITLE
List of PostgreSQL Server versions is not up2date?

### ISSUE THREAD

**Issue by florianrusch** [terraform-providers/terraform-provider-azurerm#4222]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.7
+ provider.azuread v0.6.0
+ provider.azurerm v1.28.0
```

### Affected Resource(s)

* `azurerm_postgresql_server`

### Expected Behavior

I would expect, that the docs are correct and up2date.

### Actual Behavior

The [documentation](https://www.terraform.io/docs/providers/azurerm/r/postgresql_server.html#version) says, that the version `9.5, 9.6, 10, 10.0, 11` are valid. If I try to provision a server with version `11`. I'm getting the following error message on a `terraform plan`:
```
Error: expected version to be one of [9.5 9.6 10 10.0 10.2], got 11

  on <...>/postgresql.tf line 2, in resource "azurerm_postgresql_server" "this":
   2: resource "azurerm_postgresql_server" "this" {
```

In the Azure Portal the following versions are selectable `9.5, 9.6, 10, 11`.

### Steps to Reproduce

1. Create a resource of type `azurerm_postgresql_server` with the version `11`
2. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @florianrusch 

Thanks for opening this issue.

Taking a look into this you appear to be using v1.28.0 of the Azure Provider which only supported some of these - support for PostgreSQL 11 was added in [v1.32.1 of the Azure Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1321-july-31-2019) as such this should be fixed by upgrading to the latest version - would you be able to take a look and see if that works for you? Unfortunately the documentation on the Terraform website unfortunately only refers to the latest version of each Provider, since the Terraform Website doesn't (yet) support versioned documentation (but there's a feature request open for it)

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by florianrusch** [comment]
@tombuildsstuff you are right 🙈 I haven't seen, that there are new releases of this provider. I've subscripted to be notified about new releases in the future. Thanks for your kindly response 🙂
