### ISSUE TITLE
Why does azurerm_role_definition require a scope?

### ISSUE THREAD

**Issue by Laassee** [terraform-providers/terraform-provider-azurerm#4247]
I have been working with a module to assign roles to scope with an option of creating a new role definition. During working on this module, I have been wondering about the scope argument in the azurerm_role_definition resource.

I do not understand why Terraform require this argument. When using either JSON or PSRoleDefinition object with Powershell, this is not a requirement. The only requirement needing a scope is the assignable scope, which is also in the azurerm_role_definition resource.

JSON and PSRoleDefinition reference:
https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azroledefinition?view=azps-2.6.0

Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @Laassee 

Thanks for opening this issue.

Scope [is a required field in the API (since it forms part of the URI)](https://docs.microsoft.com/en-us/rest/api/authorization/roledefinitions/createorupdate) which is why we expose this. Unfortunately we're unable to comment on the PowerShell implementation since there's no source code available, but it's possible it's defaulting this to some value (e.g. the subscription) instead, or is using an older API version which only supported creating role definitions at the subscription level.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment.

Thanks!

**Comment by Variour** [comment]
The scope seems to be generally insignificant for the end user. It is not necessary or shown when using [PowerShell ](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-powershell)of the [CLI](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-cli).
The REST API How-to advises that when [creating a custom role](https://docs.microsoft.com/en-us/azure/role-based-access-control/custom-roles-rest#create-a-custom-role) one should "replace {scope} with the first assignableScopes of the custom role".

I think ideally the Terraform provider should adopt the PowerShell/CLI way of setting the scope for the user. If this is not possible/desirable the docs should at least mention the recommendation of setting the scope to the first assignableScopes of the custom role.
