### ISSUE TITLE
How dynamically pass the resource block name in terraform?

### ISSUE THREAD

**Issue by DevallaSubbu** [terraform-providers/terraform-provider-azurerm#4289]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

How dynamically pass the resource block name in terraform?
example: here `codebuild` supposed to be dynamic . I want to able to pass codebuild into some variable and use it instead of hardcoded resource block name.
```
resource "aws_codebuild_project" "codebuild" {

[...]

  artifacts{
      type           = "${var.codebuild_artifacts_type}"
      location       = "${var.codebuild_artifacts_location}"
      name           = "${var.codebuild_artifacts_name}"
      namespace_type = "${var.codebuild_artifacts_namespace_type}"
      packaging      = "${var.codebuild_artifacts_packaging}"
      path           = "${var.codebuild_artifacts_path}"

  }
}
```
### Potential Terraform Configuration
Please let me if you need some examples?

**Comment by tombuildsstuff** [comment]
hi @DevallaSubbu 

Thanks for opening this issue.

Unfortunately the `label` used for the resource isn't dynamic and needs to be hard-coded - as such this isn't something that's possible today. That said - since this is only used as a reference within Terraform, it should be possible to set this to any value; instead the resource names within the resources can be dynamic, for example:

```hcl
variable "name" {}

resource "azurerm_virtual_machine" "main" {
  name = var.name
}
```

If you're provisioning multiple it's also possible to use the `count` field and the `count.index` to get the dynamic instance number to append this to the name, too:

```hcl
variable "count" {
  default = 3
}

resource "azurerm_virtual_machine" "main" {
  count = var.count
  name = "${var.name}${count.index}" # e.g. "name0", "name1", "name2"
}
```

You can use these within a module and then build the modules you need up as needed; would you be able to take a look and see if that works for you? Since this is a question about Terraform (Core) rather than something specific to the Azure Provider, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by DevallaSubbu** [comment]
Thank you for the response. I will work on your recommendations.

I have one more question, I have AMI (that includes multiple EBS volumes),
How can i  add the tags(terraform scripts. ) when i deployed new Ec2 node
with AMI using therefrom scripts.

*Thank you*



*Best Regards,*

*Subbu Devalla*

*425 615 9567*

**Comment by tombuildsstuff** [comment]
@DevallaSubbu I'm unfamiliar with the AWS resources - but it appears you can configure that using the `tags` field: https://www.terraform.io/docs/providers/aws/r/instance.html :)

**Comment by DevallaSubbu** [comment]
Not that way.

*Thank you*



*Best Regards,*

*Subbu Devalla*

*425 615 9567*
