### ISSUE TITLE
Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

### ISSUE THREAD

**Issue by andrudale** [terraform-providers/terraform-provider-azurerm#4301]
I'm getting this error when running terraform plan in MS Visual Studio Code.  I'm not using a service principal.  I'm logging straight into Azure CLI with az login --use-device-code.  Then terraform init runs fine.  Terraform plan fails with the error.  

I found a post about robocopying "$env:userprofile\.azure" to "$env:homeshare\.azure".  That didn't solve the problem.  I also tried setting an environmental variable pointing directly to .azure, and I also reinstalled AzureCLI.

I am using provider "azurerm".

**Comment by tombuildsstuff** [comment]
hi @andrudale 

Thanks for opening this issue.

Taking a quick look at this I have a feeling this is an issue specific to Visual Studio Code's terminal - do you also see this issue when running `terraform` in a regular terminal window? In addition can you confirm you're using the latest version of the Azure Provider and Terraform Core?

If Terraform works in a terminal window I'd suggest opening an issue on the Visual Studio Code repository but since this is a question rather than a bug I'm going to close this issue for the moment. This forum is intended to track feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html) but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by rajata07** [comment]
@tombuildsstuff I get this error from terminal too. I followed the steps mentioned [here](https://www.terraform.io/docs/providers/azurerm/auth/azure_cli.html ) 

Error: Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`.

  on main.tf line 1, in provider "azurerm":
   1: provider "azurerm" {
