### ISSUE TITLE
Does this provider respect `Retry-After` header from Azure?

### ISSUE THREAD

**Issue by johnsimons** [terraform-providers/terraform-provider-azurerm#4352]
I just wanted to know if this provider respect `Retry-After` header from Azure? Or do I need to do anything myself regarding it?

In short, I want to ensure we are not hitting api rate limits.

Cheers
John

**Comment by tombuildsstuff** [comment]
hi @johnsimons 

Thanks for opening this issue.

The Azure Provider communicates with the Azure API's using [the Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go), which under the hood uses [Go-AutoRest](https://github.com/Azure/go-autorest) which internally automatically handles the `Retry-Header` (and various other conditions, like internal server errors) as part of the request lifecycle - as such this functionality is supported by the Azure Provider.

Since this is a question rather than an issue in the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't solve your question and we'll take another look :)

Thanks!
