### ISSUE TITLE
Can't create vm behind lb with azurerm_lb_backend_address_pool

### ISSUE THREAD

**Issue by alk-rniveau** [terraform-providers/terraform-provider-azurerm#4359]
Hi guys,

I have a weird behavior when I try to create an azure lb with vm inside the backend pool in the same time.

I have on module to manage vm and one module to manage lb.
If I create lb first, all work fine but if I create both together, it doesn't work.

Here is my configuration (terraform 0.12.9, azure 1.33.1):

```hcl

resource "azurerm_network_interface_backend_address_pool_association" "vm-if-lb-public-association" {
  count                   = var.azure_lb_public_backend_id != "" ? var.countvm : 0
  network_interface_id    = element(azurerm_network_interface.vm-if.*.id, count.index)
  ip_configuration_name   = "${var.workspace_config.prefix}-${var.profile}-${count.index + 1}"
  backend_address_pool_id = var.azure_lb_public_backend_id
}

```

var.azure_lb_public_backend_id come from my lb module

```hcl

output "lb_id" {
  value = var.enable ? azurerm_lb_backend_address_pool.lb-backend[0].id : ""
}

resource "azurerm_lb_backend_address_pool" "lb-backend" {
  name                = "pool-1"
  count               = var.enable ? 1 : 0
  resource_group_name = azurerm_resource_group.lb-rg[0].name
  loadbalancer_id     = azurerm_lb.lb[0].id
}

```

When I run a plan I get the following:

```
Error: Invalid count argument

  on modules/vm/network.tf line 46, in resource "azurerm_network_interface_backend_address_pool_association" "vm-if-lb-public-association":
  46:   count                   = var.azure_lb_public_backend_id != "" ? var.countvm : 0

The "count" value depends on resource attributes that cannot be determined
until apply, so Terraform cannot predict how many instances will be created.
To work around this, use the -target argument to first apply only the
resources that the count depends on.
```

It's like the plan command doesn't understand vm creation depends on azurerm_lb_backend_address_pool

I voluntarily don't post all the code to avoid too big post, but doesn't hesitate to ask more if needed.

Do you have an idea why I get this behavior ?

**Comment by tombuildsstuff** [comment]
hi @alk-rniveau 

Thanks for opening this issue - apologies for the delayed response here.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
