### ISSUE TITLE
"tags": this field cannot be set

### ISSUE THREAD

**Issue by nicethomaslearngit** [terraform-providers/terraform-provider-azurerm#4360]
Hi Team,

  I am using the below code

data "azurerm_shared_image_version" "myimage" {
  name                = "1.0.1"
  image_name          = "windows"
  gallery_name        = "widows_galleries"
  resource_group_name = "windows-images"

  tags =    {
    name   = "DEV"
  }
}

And I am getting the error as 

Error: "tags": this field cannot be set
  on main.tf line 20, in data "azurerm_shared_image_version" "myimage":
  20: data "azurerm_shared_image_version" "myimage" {

How can I use tags here.. any help is appreciated.

Thank You

**Comment by tombuildsstuff** [comment]
hi @nicethomaslearngit 

The code snippet above shows a Data Source, which provides a read-only view of an existing resource - whereas I believe you're looking to use the Resource (which allows you to provision/manage something) with the same name instead - where you should be able to set the Tags for this Shared Image Version. Would you be able to take a look and see if [using the Resource instead}(https://www.terraform.io/docs/providers/azurerm/r/shared_image_version.html) works for you?

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment however please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by nicethomaslearngit** [comment]
Thanks @tombuildsstuff  , I was trying to filter the DataSource based on tag name already given. Is there a way I can do that?

**Comment by nicethomaslearngit** [comment]
Hi @tombuildsstuff  

As this ticket is closed can I expect any update here or do I need to create a new 'question'/ Is there a way to filter in Data Source as I shown initially

Thank You
