### ISSUE TITLE
"tags": this field cannot be set 

### ISSUE THREAD

**Issue by nicethomaslearngit** [terraform-providers/terraform-provider-azurerm#4362]
Hi All,

I am trying to set a filter in Data Source using "tags" and I am getting error. 

Could you kindly help me is there a way to add a filter/tag here?

data "azurerm_shared_image_version" "myimage" {
  name                = "1.0.1"
  image_name          = "windows"
  gallery_name        = "widows_galleries"
  resource_group_name = "windows-images"
  tags =    {
    name   = "DEV"
  }
}

Error: "tags": this field cannot be set

  on main.tf line 20, in data "azurerm_shared_image_version" "myimage":
  20: data "azurerm_shared_image_version" "myimage" {

**Comment by tombuildsstuff** [comment]
hi @nicethomaslearngit 

The `azurerm_shared_image_version` Data Source doesn't support filtering based on Tags at this this - taking a look into this this'd likely make more sense as a new data source for `azurerm_shared_image_versions` which supports filtering; since the existing data source expects a single version. If you're interested in seeing this new Data Source supported would you mind opening a new Feature Request so that someone can take a look into this? Since this is a a bug in the Azure Provider I'm going to close this issue for the moment.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html)

Thanks!

**Comment by nicethomaslearngit** [comment]
Hi @tombuildsstuff 
 
Thanks for your reply.. I have opened a new Feature request #4369
