### ISSUE TITLE
azurerm_mysql_server - add support for version 8.0

### ISSUE THREAD

**Issue by aberva** [terraform-providers/terraform-provider-azurerm#4380]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Can you add support for MySQL Server version 8.0 ?

### New or Affected Resource(s)

* azurerm_mysql_server

### Potential Terraform Configuration
resource "azurerm_mysql_server" "name" {
     ....
     version = "8.0" 
}

### References

Announces support for version 8.0 :
https://docs.microsoft.com/fr-fr/azure/mysql/overview

**Comment by aqche** [comment]
Taking a look at the Azure Go SDK, it doesn't seem like there is a [`ServerVersion` constant](https://github.com/Azure/azure-sdk-for-go/blob/0820c0553d6c410603056869f7b0e52d61ce5bee/services/mysql/mgmt/2017-12-01/mysql/models.go#L120-L127) for `8.0` available yet, but passing in `"8.0"` for version does properly create a MySQL server with a MySQL version of `8.0`.

Do we want to wait for the SDK to add a constant? Otherwise I can open a PR adding `"8.0"` as a valid input for the `version` argument and update the tests accordingly.

**Comment by tombuildsstuff** [comment]
@aqche 

> Do we want to wait for the SDK to add a constant? Otherwise I can open a PR adding "8.0" as a valid input for the version argument and update the tests accordingly.

The SDK's [generated from this Swagger file](https://github.com/Azure/azure-rest-api-specs/blob/master/specification/mysql/resource-manager/Microsoft.DBforMySQL/stable/2017-12-01/mysql.json#L1304) as such it should be possible to add the Constant there and then an SDK will be generated from that.

Generally speaking we'll try to do both - hard-code it in the Provider for the moment and then link to the Swagger/SDK PR as a TODO so that we can come back and switch over later when that's available :)

**Comment by aqche** [comment]
@tombuildsstuff 

Thanks for pointing me in the right direction. I opened PR #5019 to address this issue and also created a PR to the Swagger file [here](https://github.com/Azure/azure-rest-api-specs/pull/7864).
