### ISSUE TITLE
azurerm_service_fabric_cluster doesn't work

### ISSUE THREAD

**Issue by markti** [terraform-providers/terraform-provider-azurerm#4381]
### Terraform (and AzureRM Provider) Version

Terraform v0.12.7
+ provider.azuread v0.6.0
+ provider.azurerm v1.28.0
+ provider.random v2.2.0

### Affected Resource(s)

* `azurerm_service_fabric_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "test" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_service_fabric_cluster" "test" {
  name                 = "example-servicefabric"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  location             = "${azurerm_resource_group.test.location}"
  reliability_level    = "Bronze"
  upgrade_mode         = "Manual"
  cluster_code_version = "6.3.176.9494"
  vm_image             = "Windows"
  management_endpoint  = "https://example:80"

  node_type {
    name                 = "first"
    instance_count       = 3
    is_primary           = true
    client_endpoint_port = 2020
    http_endpoint_port   = 80
  }
}
```

### Expected Behavior

Provision a working cluster.

### Actual Behavior

it doesn't deploy a working service fabric cluster. There is no evidence that this resource works at all because there is no sample provided that produces even a working simple single node cluster. It checks a checkbox and gives the perception that many Azure services are supported by the terraform provider but for all practical purposes it is infeasible to deploy and manage service fabric cluster using terraform.

Microsoft should demonstrate this resource works or remove it from the terraform.io documentation which implies that it actually deploys a service fabric cluster.

**Comment by hbuckle** [comment]
@markti the documentation is lacking here, but basically you need to deploy all the other resources such as the vm scale set as well - the service fabric cluster object doesn't do anything on its own.
I'll post a working example later

**Comment by tedvanderveen** [comment]
Hi @hbuckle, did you share this working example somewhere? We are pulling out hair out trying to get any of this azurerm_service_fabric_cluster resource bits to work. So that example you refered to, would be great!

**Comment by tombuildsstuff** [comment]
👋 

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

Since this is a usage question about Service Fabric (and how to configure a cluster in Terraform) rather than a bug - I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by markti** [comment]
@tombuildsstuff with all due respect, isn't usage kind of the point? The service fabric resource is not at all usable. It's literally a checked checkbox. Which by itself, does little to help practitioners trying to use Microsoft's services.

**Comment by tombuildsstuff** [comment]
@markti unfortunately the Service Fabric service is one of the older services in Azure as such it's designed differently to other more modern services (such as AKS, or the newer Service Fabric Mesh).

Creating an Azure Service Fabric Cluster creates the control plane here - in this older resource the Virtual Machine Scale Sets used as Worker Nodes are defined outside of this resource, as such unfortunately this resource matches the API available in Azure here. I believe the newer Service Fabric Mesh offering (which is being tracked in #2486) instead supports managed worker nodes, but I've not used this and so can't confirm.

Ultimately this is a product question regarding the design of Azure Service Fabric, rather than something specific to Terraform - so I'd suggest reaching out to the Service Fabric team to discuss that, since the design of the service is unfortunately outside of Terraform's scope.
