### ISSUE TITLE
The client '****' with object id '****' does not have authorization to perform action 'Microsoft.MarketplaceOrdering/register/action' over scope '/subscriptions/****' or the scope is invalid

### ISSUE THREAD

**Issue by shurick81** [terraform-providers/terraform-provider-azurerm#4410]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.9
+ provider.azurerm v1.33.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "test" {
  name                     = "dmsspadapter${replace(terraform.workspace, "/\\W/","$1")}"
  location                 = "westeurope"
  resource_group_name      = "contoso-sharepoint-${var.environmentId}-rg"
  account_tier             = "Standard"
  account_replication_type = "LRS"

  tags = {
    environment = "${var.environmentId}"
    Satsning    = "IT01"
    ManagedBy   = "alexander.sapozhkov@contoso.se, qwer@contoso.se"
  }
}

```

### Debug Output

https://gist.github.com/shurick81/cc279c2eebe327c87943a442c3f71460

### Expected Behavior

Storage account creation

### Actual Behavior

throwing an error:

```
Error: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.MarketplaceOrdering with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '169c2180-2945-4eda-89ca-8b78285e312c' with object id '169c2180-2945-4eda-89ca-8b78285e312c' does not have authorization to perform action 'Microsoft.MarketplaceOrdering/register/action' over scope '/subscriptions/dd6ea0e3-3c04-480e-a002-236ac1c90db6' or the scope is invalid. If access was recently granted, please refresh your credentials.".
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Configuration works perfectly when specifying 1.33 version:

```
provider "azurerm" {
  version         = "=1.33.0"
```

However, after specifying 1.34 version, it throws an error:

```
provider "azurerm" {
  version         = "=1.34.0"
```

**Comment by tombuildsstuff** [comment]
hi @shurick81 

Thanks for opening this issue :)

The Azure Provider attempts to automatically register any Resource Providers which it supports to provide a better user experience (since the error messages returned from Azure when a Resource Provider is unregistered are unhelpful). Since there's no way for us to know within the Azure Provider which Resource Providers are needed (since this information isn't exposed in Terraform Core) we maintain [a list of all supported Resource Providers which we have Terraform Resources for](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/required_resource_providers.go#L16) and attempt to register them on launch.

As a part of the version 1.34 release of the Azure Provider since we now support accepting the T&C's for Marketplace Images (via the `azurerm_marketplace_agreement` resource) we've added the Resource Provider `Microsoft.MarketplaceOrdering` to this list - meaning we'll try and register this new Resource Provider if it isn't currently registered.

If you're running in an environment where the Service Principal doesn't have access to register Resource Providers you can configure Terraform to skip registering the Required Resource Providers using the `skip_provider_registration` setting (as you've seen) - albeit the error messages returned from Azure may be more unhelpful should you encounter a Resource Provider which is unregistered - but since this is an intentional behaviour I'm going to close this issue for the moment.

Thanks!
