### ISSUE TITLE
.net version options in app service

### ISSUE THREAD

**Issue by chlsmith** [terraform-providers/terraform-provider-azurerm#446]
The only allowed version are 2.0 and 4.0, but neither of these are current with the options available via the portal (v3.5 and v4.7)

**Comment by tombuildsstuff** [comment]
Hi @chlsmith 

Thanks for opening this issue :)

In [the `azurerm_app_service` resource](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#dotnet_framework_version) - the .net version corresponds to the latest supported .net CLR version within that release ([here's a Wikipedia article with more information](https://en.wikipedia.org/wiki/.NET_Framework_version_history#Overview)). Essentially .net 3.5 is the latest release on the .net CLR 2.0 - and .net 4.7.1 is the latest release on the .net CLR 4.0.

In time it may make sense to rename this field to `dotnet_clr_version` rather than `dotnet_framework_version` - however as we're matching the terminology used by the Azure API's I believe the best we can do for the moment is to document this behaviour. Currently the documentation shows the following:

> `dotnet_framework_version` - (Optional) The version of the .net framework used in this App Service. Possible values are `v2.0` (which corresponds to `v3.5`) and `v4.0` (which is `v4.7` at the time of writing). Defaults to `v4.0`.

I've opened #472 which updates the documentation to mention this is the CLR version - but in the meantime would you be able to take a look to see if this solves your issue?

Thanks!

**Comment by chlsmith** [comment]
That works.   Thanks for your response!!!
