### ISSUE TITLE
Error: Cannot register provider Microsoft.Kusto with Azure Resource Manager

### ISSUE THREAD

**Issue by sjentzsch** [terraform-providers/terraform-provider-azurerm#4488]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.9
+ provider.azuread v0.5.1
+ provider.azurerm v1.34.0
+ provider.external v1.1.2
+ provider.http v1.1.1
+ provider.kubernetes v1.6.2
+ provider.null v2.1.2
+ provider.random v2.1.2
+ provider.template v2.1.2

### Affected Resource(s)

* provider "azurerm" itself

### Expected Behavior

We can successfully `terraform init` and `terraform plan` our resources after upgrading from version `1.31.0` to the latest one (`v1.34.0`) of `azurerm` provider.

### Actual Behavior

When running `terraform plan`, the members of our team who are *not* Owners of the whole subscription on Azure run into the following authorization issue due to missing permissions:

```
Error: Error ensuring Resource Providers are registered: Cannot register provider Microsoft.Kusto with Azure Resource Manager: resources.ProvidersClient#Register: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client 'xxx@xxx' with object id 'xxx' does not have authorization to perform action 'Microsoft.Kusto/register/action' over scope '/subscriptions/xxx' or the scope is invalid. If access was recently granted, please refresh your credentials.".

  on main.tf line 107, in provider "azurerm":
 107: provider "azurerm" {
```
We do not have or maintain any Kusto-related resources.

Which role or permission (if ...) is now required to be able to "register provider Microsoft.Kusto with Azure Resource Manager"? And why do we need to register a provider we do not use at all in our resources? Thanks for any hint or direction!

### Steps to Reproduce

Not sure how to reproduce, but some undocumented permissions are now required with a recent version of `azurerm`, which were not required before.

**Comment by tombuildsstuff** [comment]
hi @sjentzsch 

Thanks for opening this issue :)

The Azure Provider attempts to automatically register any Resource Providers which it supports to provide a better user experience (since the error messages returned from Azure when a Resource Provider is unregistered are unhelpful). Since there's no way for us to know within the Azure Provider which Resource Providers are needed (since this information isn't exposed in Terraform Core) we maintain [a list of all supported Resource Providers which we have Terraform Resources for](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/required_resource_providers.go#L16) and attempt to register them on launch.

As a part of the version v1.34.0 release of the Azure Provider since we now support the Kusto resources (via the `azurerm_kusto_cluster` resource) we've added the Resource Provider `Microsoft.Kusto` to this list - meaning we'll try and register this new Resource Provider if it isn't currently registered.

If you're running in an environment where the Service Principal doesn't have access to register Resource Providers you can configure Terraform to skip registering the Required Resource Providers using the `skip_provider_registration` setting (as you've seen) - albeit the error messages returned from Azure may be more unhelpful should you encounter a Resource Provider which is unregistered - but since this is an intentional behaviour I'm going to close this issue for the moment.

Thanks!

**Comment by sjentzsch** [comment]
@tombuildsstuff Appreciate your prompt and detailed response, thanks for clarification!
Indeed, this issue can be closed then and we find a solution on our end.
