### ISSUE TITLE
assign variables of map in azurerm resource attributes

### ISSUE THREAD

**Issue by jontreynes** [terraform-providers/terraform-provider-azurerm#4504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
I'd like to pass a variable of map with a dynamic set of key value pairs. 

My use case is this

```
variable "image" {
  description = "This is the Azure Image ID to install onto the vmss"


  # You can either specify the Azure Image ID with the below metadata
  default = {
    id = "/subscriptions/xxx/resourceGroups/myredhat2/providers/Microsoft.Compute/images/mytfdisk"
  }

  # or use an image from the marketplace
  # default =     
  # {
  # publisher = "RedHat"
  # offer     = "RHEL"
  # sku       = "7.5"
  # version   = "latest"
  # }
}
```

as you can see from the comments above, image can be a map of any key value pair

I'd like to assign it like so
```
resource "azurerm_virtual_machine_scale_set" "test" {
storage_profile_image_reference = var.image
}
```

### New or Affected Resource(s)

* azurerm_XXXXX

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @jontreynes 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
