### ISSUE TITLE
azurerm_network_security_group in 0.3.0+ wants to continually reapply

### ISSUE THREAD

**Issue by clangaxon** [terraform-providers/terraform-provider-azurerm#455]
Upgrading from 0.2.2 to 0.3.1, Terraform always shows a pending modification on all azurerm_network_security_group objects. It appears to be that it now sorts the security rules by priority. This seems like a good thing going forward, but it disagrees with the existing state.  Apply won't fix this as there are no actual changes made.

Is there a possible fix or simple work around?

Thanks.

**Comment by dominik-lekse** [comment]
Thanks @clangaxon for opening this issue.

I can confirm this behavior appeared after upgrading from a 0.2.x to the recent version 0.3.1. Without too much investigation, I suspect a state migration is needed to fix this.

As a manual fix, you could try to reorder the corresponding items of the nsg objects in the Terraform state.

**Comment by clangaxon** [comment]
I suspect you are correct in that we could manually reorder them - however this would be hand editing thousands of lines, as we have many very large configs. :)

**Comment by amosdavis** [comment]
I have tried re-ordering as you suggested and it doesn't solve the problem.  I am still prompted to re-apply the same nsg.

**Comment by clangaxon** [comment]
I tried removing all the rules from an NSG and Terraform fails to do anything on apply. Seems like azurerm_network_security_group is completely broken in 0.3+.

**Comment by dominik-lekse** [comment]
@clangaxon Thanks for your research on this. I confirm that I also had no success when reordering the items in the Terraform state.

**Comment by privatwolke** [comment]
I had a look at the code responsible for handling network security groups and I believe that the commit that broke this was https://github.com/terraform-providers/terraform-provider-azurerm/commit/fbdcf746c8d8bf5b99b48764720432ac645c7bab#diff-02a62c4182918d899d123e535c80ac12L40 by @tombuildsstuff where the container type for handling security rules was changed from a set to a list. The desire might have been to simplify the handling and not having to compute hash values for security rules.

**Comment by dominik-lekse** [comment]
Might also be the case that the Azure API returns the list of rules in a nsg in a non-deterministic order. When the rules in the provider have been handled as a set this might not have mattered, but as far as I know, a list in a Terraform schema is order-aware.

This is an unverified guess, but I have learned that the Azure API is full of surprises.

**Comment by luisamador** [comment]
I'm hitting the same issue. We are on Terraform v0.10.8 and using the azurerm 0.3 provider. It is annoying because it's breaking Terraform's idempotency.

**Comment by VaijanathB** [comment]
One easy work around for this issue is to move the security rules outside of NSG. By this way we can ensure that the idempotency of terraform is restored. For example 

Before.: 
provider "azurerm" {
    version = "0.2.1"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-1"
  location = "South Central US"
}

resource "azurerm_network_security_group" "test" {
  name                = "acceptanceTestSecurityGroup1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }

  security_rule {
    name                       = "testDeny"
    priority                   = 101
    direction                  = "Inbound"
    access                     = "Deny"
    protocol                   = "Udp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

AFTER 

provider "azurerm" {
    version = "0.3.3"
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-1"
  location = "South Central US"
}

resource "azurerm_network_security_rule" "test123" {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
    resource_group_name        = "${azurerm_resource_group.test.name}"
    network_security_group_name = "${azurerm_network_security_group.test.name}"
}
resource "azurerm_network_security_rule" "testDeny" {
    name                       = "testDeny"
    priority                   = 101
    direction                  = "Inbound"
    access                     = "Deny"
    protocol                   = "Udp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
    resource_group_name        = "${azurerm_resource_group.test.name}"
    network_security_group_name = "${azurerm_network_security_group.test.name}"
}

resource "azurerm_network_security_group" "test" {
  name                = "acceptanceTestSecurityGroup1"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
}

**Comment by tombuildsstuff** [comment]
:wave: hey folks!

Just to let you know that the fix for this was merged in #893 and has just been released in v1.2.0 of the AzureRM Provider - full details of what's included are available here: https://github.com/terraform-providers/terraform-provider-azurerm/blob/v1.2.0/CHANGELOG.md#120-march-02-2018

Thanks!
