### ISSUE TITLE
azurerm_api_management_user state field appears case sensitive

### ISSUE THREAD

**Issue by jeanpaulsmit** [terraform-providers/terraform-provider-azurerm#4551]
### Terraform (and AzureRM Provider) Version
Terraform 0.12.9
AzureRM 1.34.0

### Affected Resource(s)

* `azurerm_api_management_user`

### Terraform Configuration

resource "azurerm_api_management_user" "user" {
  user_id             = "test-user"
  api_management_name = "${azurerm_api_management.apim.name}"
  resource_group_name = "${azurerm_resource_group.rg.name}"
  first_name          = "User"
  last_name           = "Lastname"
  email               = "email@test.com"
  state               = "Active"
}

### Expected Behavior
The documentation mentions for the 'state' field:
Possible values are Active, Cancelled, Expired, Rejected, Submitted and Suspended. Defaults to Submitted.

### Actual Behavior
When using 'Active' instead of 'active' for the state field, the output is an error:

"expected state to be one of [active blocked pending], got Active"

**Comment by joakimhew** [comment]
@jeanpaulsmit I'm assuming you meant `azurerm_api_management_subscription` as the values you listed are for that particular resource and not `azurerm_api_management_user` 🙂?

**Comment by jeanpaulsmit** [comment]
@joakimhew no, I meant azurerm_api_management_user. That resource also has a field called 'state'.
https://www.terraform.io/docs/providers/azurerm/r/api_management_user.html

**Comment by joakimhew** [comment]
> @joakimhew no, I meant azurerm_api_management_user. That resource also has a field called 'state'.
> https://www.terraform.io/docs/providers/azurerm/r/api_management_user.html

@jeanpaulsmit 
Hmm okay I think I see what you are trying to say. From the issue it appeared as if you meant that the documentation was incorrect:

> The documentation mentions for the 'state' field:
Possible values are Active, Cancelled, Expired, Rejected, Submitted and Suspended. Defaults to Submitted.

But what you are actually saying is that Terraform doesn't accept state values that are not all-lowercase, in your case when you are using `Active` instead of `active`. 

However,  this is the expected behaviour as Azure doesn't allow anything else than all-lowercase for state. If you were to use their API directly and try the value `Active` instead of `active`. The API would throw an error.

@katbyte Do we ever transform user input in Terraform to something else? Would we want to allow a user to write something like `Active` or `AcTiVe` and transform that internally to `active`?

**Comment by jeanpaulsmit** [comment]
@joakimhew now I see what you mean. I mentioned the user but in the issue report I describe the options which apply to subscriptions. I can understand that's a bit confusing. Anyway, my point was that it would be good to have the options documented in the way they're accepted. So in this case it would be better to have 'active' in the docs opposed to 'Active'.
