### ISSUE TITLE
Add Virtual Network Integration to the API Management service

### ISSUE THREAD

**Issue by jeffddix** [terraform-providers/terraform-provider-azurerm#4561]
Add the virtual_network_type property which allows None, Internal or External. This is a copy of [2582](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2582 ) that was closed because of a bug. 

- Add virtual_network_configuration object with property subnet_id which references the subnet to integrate with.

- See https://docs.microsoft.com/en-us/azure/api-management/api-management-using-with-vnet for details regarding API Management with Vnet integration

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_1.35.0

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/pull/2582

**Comment by tombuildsstuff** [comment]
hi @jeffddix 

Thanks for opening this issue.

As mentioned in #2582 unfortunately we're still waiting for the new release of the API Management API which will unblock us moving to the new API version - which is being tracked in https://github.com/Azure/azure-rest-api-specs/issues/6372.

Once that's available we can update to this API version and then look to use this functionality - but at the moment unfortunately this is blocked on https://github.com/Azure/azure-rest-api-specs/issues/6372. Rather than having this information tracked over multiple issues and trying to keep them up to date, I'm going to close this in favour of #2582 for the moment, where we'll post an update when this is available.

Thanks!
