### ISSUE TITLE
"route.1.next_hop_in_ip_address" must not be empty

### ISSUE THREAD

**Issue by ymash13** [terraform-providers/terraform-provider-azurerm#4571]
Hello,

I am trying to add some routes with the type virtualnetworkgateway. 

When I don't provide the next_hop_in_ip_address field I get this error
"next_hop_in_ip_address" is required.

When I provide next_hop_in_ip_address but leave it blank I get
"route.3.next_hop_in_ip_address" must not be empty

Per the links below, this was supposed to be fixed in version 1.19, I am running 1.33. Seems that it's supposed to be optional, but it's being required. 
https://github.com/terraform-providers/terraform-provider-azurerm/pull/2184
https://github.com/terraform-providers/terraform-provider-azurerm/issues/2736

**Comment by tombuildsstuff** [comment]
hi @ymash13 

Thanks for opening this issue.

Version 1.19 of the Azure Provider introduced validation for `next_hop_in_ip_address` field where the value needs to be a non-empty string if it's specified (since otherwise the Azure API will reject this value as invalid). Instead if you're looking to conditionally/not set this field you can either omit this field or set the value to `null` (which do the same thing) - for example:

```
locals {
  next_hop = "1.2.3.4"
}

resource "azurerm_route" "routes" {
  next_hop_in_ip_address = local.next_hop != "" ? local.next_hop : null
}
```

Would you be able to take a look and see if that works for you? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look :)

Thanks!
