### ISSUE TITLE
azurerm_app_service: mark app_settings as sensitive

### ISSUE THREAD

**Issue by PSanetra** [terraform-providers/terraform-provider-azurerm#4575]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform: 0.12.9
AzureRM: 1.35.0

### Affected Resource(s)

* `azurerm_app_service`

### Expected Behavior

The `app_settings` elements of the `azurerm_app_service` should be marked as sensitive. Because there may be sensitive values in the `app_settings`.

### Actual Behavior

The `app_settings` element values are printed to the terraform log during the terraform planning phase if a `azurerm_app_service` resource will be destroyed.

**Comment by StefanSchoof** [comment]
I disagree. 

Sensitive app settings belong into a key vault. And making this senetive, makes people think that the information is protected and make it harder to see changes of not senetive data.

**Comment by tombuildsstuff** [comment]
hi @PSanetra 

Thanks for opening this issue.

Whilst it's certainly possible to store sensitive information in the App Settings block - Microsoft recommends against doing so and (as @StefanSchoof has mentioned) suggests instead storing/retrieving sensitive information from Azure Key Vault instead ([you can find an example of how to do this here](https://medium.com/@patoncrispy/securing-settings-in-dot-net-core-apps-using-azure-key-vault-d4ec82de00b8)).

Unfortunately implementing this change would impact users who are following the recommended advise here (since any changes, for example changing a feature toggle, would be masked in the plan). As such whilst I'd like to thank you for opening this issue, since this behaviour is intentional (due to Microsoft's recommendation) I'm going to close this issue for the moment.

Thanks!

**Comment by PSanetra** [comment]
@tombuildsstuff The article you posted stores the `ClientSecret` for accessing the key vault in the `appSettings.json`. I don't think that is an option if you want to deploy your app as a container, is it?

@StefanSchoof is it possible to access the key vault without a client secret which would be stored inside the app settings and therefore logged in plain text by terraform?

**Comment by StefanSchoof** [comment]
Yes, you can use manged service identity and then a appsetting in the format `@Microsoft.KeyVault(SecretUri=https://myvault.vault.azure.net/secrets/mysecret/ec96f02080254f109c51a1f14cdb1931)`, see https://docs.microsoft.com/en-us/azure/app-service/app-service-key-vault-references

**Comment by StefanSchoof** [comment]
@PSanetra You may expieriens the bug #3129 (at least I did), when working with keyvault Uris.
