### ISSUE TITLE
azurerm_role_definition.vm: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400

### ISSUE THREAD

**Issue by shankarsundaram** [terraform-providers/terraform-provider-azurerm#4594]
**Error**:
"azurerm_role_definition.vm: authorization.RoleDefinitionsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidActionOrNotAction" Message="'Microsoft.Compute/hosts/delete' does not match any of the actions supported by the providers."
I'm performing the following rbac operation in terraform  which is mentioned in the below azure documentation but ended up with the above error.
https://docs.microsoft.com/en-us/azure/role-based-access-control/resource-provider-operations
**operations**:
Microsoft.Compute/hosts/delete
Microsoft.Compute/hosts/read
Microsoft.Compute/hosts/write

**Comment by Variour** [comment]
The resource provider operations page does not list any of the operations you have posted, which means they do not exist, which is why you can not use them in your template.

**Comment by tombuildsstuff** [comment]
hey @shankarsundaram 

As @Variour has mentioned this appears to be down to the roles being requested which don't exist - from what I can tell it appears you're probably looking for `Microsoft.Compute/virtualMachines/read`? There may be roles in the pipeline for Dedicated Hosts but they're not listed on that page yet - but presumably when they become available they'll be in the format `Microsoft.Compute/dedicatedHosts/read`.

Since this should be resolved by switching to the correct role I'm going to close this issue for the moment, however I'd suggest reaching out to Microsoft Support if you're looking for further clarification about the roles in question.

Thanks!

**Comment by shankarsundaram** [comment]
These roles archived were already it seems. i found the correct one . Thanks for your comments @Variour @tombuildsstuff.
