### ISSUE TITLE
azurerm_virtual_machine_extension creation procedure takes forever without stop in Azure Gov environment

### ISSUE THREAD

**Issue by gongjunhuang** [terraform-providers/terraform-provider-azurerm#4608]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `Terraform v0.12.10`

### Terraform Configuration Files

I want to install the OMS agent on linux machine, but it takes forever for the extension creation without stop

`vm.tf`
```hcl
resource "azurerm_log_analytics_workspace" "workspace" {
  name                = "workspace"
  location            = "${var.azure_location}"
  resource_group_name = "${data.azurerm_resource_group.parent_rg.name}"
  sku                 = "PerGB2018"
  retention_in_days   = 180
}

resource "azurerm_virtual_machine" "server" {
  name                  = "vm"
  vm_size               = "${var.jenkins_vm_size}"
  location              = "${var.azure_location}"
  resource_group_name   = "${azurerm_resource_group.rg.name}"
  network_interface_ids = ["${azurerm_network_interface.nic.id}"]
  ...
  }

  tags = "${local.vm_tags}"
}

resource "azurerm_virtual_machine_extension" "oms_mma" {
  name                       = "OMSExtension"
  location                   = "${var.azure_location}"
  resource_group_name        = "${azurerm_resource_group.rg.name}"
  virtual_machine_name       = "${azurerm_virtual_machine.server.name}"
  publisher                  = "Microsoft.EnterpriseCloud.Monitoring"
  type                       = "OmsAgentForLinux"
  type_handler_version       = "1.7"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
    {
      "workspaceId" : "${azurerm_log_analytics_workspace.workspace.workspace_id}"
    }
  SETTINGS

  protected_settings = <<PROTECTED_SETTINGS
    {
      "workspaceKey" : "${azurerm_log_analytics_workspace.workspace.primary_shared_key}"
    }
  PROTECTED_SETTINGS
}
```

### Debug Output

I write an ouput.tf to list the `workspace id` and `workspace key` variables, it is identical to the variables in the Azure portal.

`output.tf`
```
output "workspace_id" {
    value = "${azurerm_log_analytics_workspace.workspace.workspace_id}"
}

output "workspace_key" {
    value = "${azurerm_log_analytics_workspace.workspace.primary_shared_key}"
}
```
`Outputs`:
```
workspace_id = 4b1xxx46-22f6-xxx-8ff4-xxxxxa681
workspace_key = X2QhMLjnxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxHMpol7fxMGLGhqsVg==
```
### Expected Behavior

I have tested the same installation procedure on Azure commercial environment, the extension installation finished within 3 minutes:
```
azurerm_virtual_machine_extension.oms_mma: Creating...
azurerm_virtual_machine_extension.oms_mma: Still creating... [10s elapsed]
azurerm_virtual_machine_extension.oms_mma: Still creating... [2m0s elapsed]
azurerm_virtual_machine_extension.oms_mma: Creation complete after 2m0s [id=/subscriptions/xxxxxxxx/resourceGroups/rg/providers/Microsoft.Compute/virtualMachines/vm/extensions/OMSExtension]
```
### Actual Behavior

The installation for OMS agent installation on Azure Gov environment did not stop until I interrupt the process, it lasts for more than 30 minutes, and the extension in the VM is unavailable.

![image](https://user-images.githubusercontent.com/32806421/66739876-4d462280-eea4-11e9-9f51-564a25fbd5e0.png)

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @gongjunhuang 

Thanks for opening this issue.

Taking a look into this it appears that the OMS Agent may require additional configuration when running in clouds other than Azure Public - [this document](https://blogs.msdn.microsoft.com/nicole_welch/2017/05/the-oms-agent-for-azure-government-a-cheat-sheet/) outlines how to configure this for a Windows machine.

Whilst I can't find a similar guide for Linux with a quick search, searching the OMS agent for Linux codebase [shows this result](https://github.com/microsoft/OMS-Agent-for-Linux/blob/3cfb94e4684cc2878d7a8449a43adff0032a17b9/README.md) which sets an additional parameter for Azure Government `-d opinsights.azure.us` - which sends data to a separate (Azure Government) instance.

My understanding of the OMS agent is that it polls until it's able to connect successfully (which is why this is failing, since it's retrying) - but that behaviour may have changed since I last used it - however in either case I believe this additional parameter needs to be set.

Unfortunately I'm unaware of the specific syntax required to get this working with the VM Extension resource - the documentation for `d` here refers to `domain` - as such perhaps `WorkspaceDomain` would work as the key? (that's a guess more than anything) - I'd suggest reaching out to Microsoft Support / the OMS Team who should be able to answer that specifically - since it appears this is an issue with configuration rather than something specific to Terraform.

Thanks!
