### ISSUE TITLE
Enable Advanced Threat Protection for Azure CosmosDB

### ISSUE THREAD

**Issue by desreela** [terraform-providers/terraform-provider-azurerm#4614]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Enable Advanced Threat Protection for Azure CosmosDB. 

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
 enable_advanced_threat_protection = true
```

### References

* #0000

**Comment by tracypholmes** [comment]
This looks like it's going to be a new resource - not an enhancement to `cosmosdb`.

**Comment by desreela** [comment]
@tracypholmes , any tentative timelines for this feature?

**Comment by tombuildsstuff** [comment]
hi @desreela 

Thanks for opening this issue :)

Support for an independent resource for Advanced Threat Protection has been added in #4848 and will become available in version 1.40 of the Azure Provider - since support for this has been merged I'm going to close this issue for the moment; however I've assigned this to the 1.40 milestone so @hashibot will comment when the release is available.

Thanks!
