### ISSUE TITLE
please make possible to grant access to azure managed identity while creating azurerm_storage_account resource 

### ISSUE THREAD

**Issue by tetlika** [terraform-providers/terraform-provider-azurerm#4617]
when creating mentioned resource it is not possible to specify additional access for managed identity: https://www.terraform.io/docs/providers/azurerm/r/storage_account.html; would be beneficial to have it stated

**Comment by tombuildsstuff** [comment]
hi @tetlika  

Thanks for opening this issue :)

Taking a look into this it appears this functionality is available via [the `identity` block within the `azurerm_storage_account` resource](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#identity) - would you be able to take a look and see if that works for you? Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
