### ISSUE TITLE
terraform init - throws error for Azurerm

### ISSUE THREAD

**Issue by sanagareddy** [terraform-providers/terraform-provider-azurerm#4637]
$ terraform init

Initializing the backend...

Initializing provider plugins...
- Checking for available provider plugins...
- Downloading plugin for provider "Azurerm" (hashicorp/azurerm) 1.35.0...

Error installing provider "Azurerm": failed to find installed plugin version 1.35.0; this is a bug in Terraform and should be reported.

Terraform analyses the configuration and state and automatically downloads
plugins for the providers used. However, when attempting to download this
plugin an unexpected error occurred.

This may be caused if for some reason Terraform is unable to reach the
plugin repository. The repository may be unreachable if access is blocked
by a firewall.

If automatic installation is not possible or desirable in your environment,
you may alternatively manually install plugins by downloading a suitable
distribution package and placing the plugin's executable file in the
following directory:
    terraform.d/plugins/windows_amd64

Error: failed to find installed plugin version 1.35.0; this is a bug in Terraform and should be reported

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @sanagareddy 

Thanks for opening this issue.

Provider Name's are case-sensitive - in this instance the provider name is  `azurerm` rather than `Azurerm` - as such if you update the provider block like below and then re-running `terraform init` should work:

```hcl
provider "azurerm" {
  # ...
}
```

I've also asked the Terraform Core team if we should be raising a more helpful error here, since (as far as I know) all provider names are lower-cased. Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
