### ISSUE TITLE
Add permanent data disk to vm

### ISSUE THREAD

**Issue by Thomas999999** [terraform-providers/terraform-provider-azurerm#4650]
Hi,

I do not get it managed to attach a permanent disk to a Linux VM. as we need at least 300 GB disk space and want to use a cheap instance type (we use Standard_D16s_v3 with 32 GB diskspace ) .
I tried with:
Creating a managed data-disk:
###managed storage disk creation for jumphost#####
resource "azurerm_managed_disk" "jump_disk" {
  name = "jump_data1"
  resource_group_name = "${var.resource_group_name}"
  location = "${azurerm_resource_group.resource_group.location}"
  storage_account_type = "Standard_LRS"
  create_option = "Empty"
  disk_size_gb = "300"
}

And attach later to LInux VM:
...
storage_os_disk {
    name              = "${var.resource_group_name}-osdisk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
	
  **storage_data_disk {
  name              = "jump_data1"
  managed_disk_id   = "${azurerm_managed_disk.jump_disk.id}"
  disk_size_gb      = "300"
  create_option     = "Attach"
  lun               = 0
  }**
...

But getting on OS Level only /mnt/resource with information that this will be lost after restart for example...and we shutdown&restart often to save costs:
[root@d021970-md300 ~]# df -h
Filesystem      Size  Used Avail Use% Mounted on
/dev/sda2        32G  3.0G   29G  10% /
devtmpfs         63G     0   63G   0% /dev
tmpfs            63G     0   63G   0% /dev/shm
tmpfs            63G  9.1M   63G   1% /run
tmpfs            63G     0   63G   0% /sys/fs/cgroup
/dev/sda1       497M  101M  396M  21% /boot
/dev/sdb1       252G  2.1G  237G   1% /mnt/resource
tmpfs            13G     0   13G   0% /run/user/1000
[root@d021970-md300 ~]# cd /mnt/resource
[root@d021970-md300 resource]# ls
DATALOSS_WARNING_README.txt  lost+found  swapfile
[root@d021970-md300 resource]#

Does anybody know how to increase disk space not ephemeral?

Thanks,
Thomas

**Comment by tombuildsstuff** [comment]
hi @Thomas999999 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
