### ISSUE TITLE
An argument named "proximity_placement_group_id" is not expected in "azurerm_availability_set" 

### ISSUE THREAD

**Issue by jsapkota** [terraform-providers/terraform-provider-azurerm#4656]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.9
AzureRM 1.33.0

### Affected Resource(s)

* `azurerm_availability_set`

### Terraform Configuration Files

```hcl

resource "azurerm_availability_set" "vm" {
  count                        = var.availability_set == true ? 1 : 0
  name                         = "avset"
  location                     = azurerm_resource_group.vm.location
  resource_group_name          = azurerm_resource_group.vm.name
  platform_fault_domain_count  = var.platform_fault_domain_count
  platform_update_domain_count = var.platform_update_domain_count
  proximity_placement_group_id = var.proximity_placement_group_id 
  managed                      = var.managed
  tags                         = var.tags
}
```

### Debug Output

https://gist.github.com/jsapkota/25fd66869b7a780e3e9fa9b348fd10b8
### Expected Behavior

The resource should accept the parameter as per the documentation. https://www.terraform.io/docs/providers/azurerm/r/availability_set.html#proximity_placement_group_id

### Actual Behavior
```
Error: Unsupported argument

  on main.tf line 8, in resource "azurerm_availability_set" "vm":
  8:   proximity_placement_group_id = var.proximity_placement_group_id

An argument named "proximity_placement_group_id" is not expected here.
```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @jsapkota 

Thanks for opening this issue :)

Taking a look into this it appears [the `proximity_placement_group_id` field `azurerm_availability_set` was added in version v1.34 of the Azure Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1340-september-18-2019) - would you be able to try upgrading and seeing if that works for you? You can do this by changing the provider block like so and then running `terraform init`:

```
provider "azurerm" {
  version = "=1.35.0"
}
```

Since this should be fixed by upgrading I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
