### ISSUE TITLE
WAF Policy association to an Application Gateway 

### ISSUE THREAD

**Issue by rnogit** [terraform-providers/terraform-provider-azurerm#4667]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It seems that there is currently no ability to associate a web application firewall policy to an application gateway. It would be helpful not have to do that with the Azure CLI.

### New or Affected Resource(s)

* azurerm_web_application_firewall_policy
* azurerm_application_gateway

### References

* https://docs.microsoft.com/en-us/azure/application-gateway/configure-waf-custom-rules#create-an-application-gateway

**Comment by nmkleiberg** [comment]
Please add this as an option!

**Comment by hamzahshakeel** [comment]
is there an option via powershell to remove an association with an application gateway? I cant seem to find an option for this even on the portal and via powershell, so cant remove a policy until i disscoiate it from the gateway and cant find any documentation or powershell commands which will allow me to do this.

**Comment by RustyF** [comment]
You can manipulate it using the new Az* PowerShell commands but not with the older AzureRm* commands.

**Comment by hamzahshakeel** [comment]
I cant seem to find which Az PowerShell command it is. Ive done a search and i can find one to remove the policy itself BUT if that policy is associated with a gateway i cant seem to find how to remove that association so that i can remove the policy. The option to remove association to a listener is present on the portal (not sure about powershell) but for gateway association there doesnt seem to be a remove option for it on portal nor powershell.
