### ISSUE TITLE
More secure Delete Locks for Storage Accounts

### ISSUE THREAD

**Issue by eliasvakkuri** [terraform-providers/terraform-provider-azurerm#4681]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Edits
* 03 Feb 2020
  * Edited title
  * Added some more information based on investigation
  * Added more descriptive code

### Description

Azure offers the option of setting Locks on your resources in order to prevent accidental deletion (Delete lock) or modification (ReadOnly lock). When using a Delete lock with a Storage Account, the lock usually prevents deletion of also child resources within the Storage Account, such as Blob Containers where the actual data is located.

However, when using Terraform, the lock on the Storage Account for some reason does not impact operations on the the Blob Containers, i.e., you can delete containers within the Storage Account even though the Storage Account has a Delete lock. This is in contrast with using e.g. the Portal, which prevents the user from deleting containers if the Storage Account has a lock on it.

I feel that the experience with Terraform should be the same as with the Portal - if you try to delete a container within a Storage Account with a Delete lock, the operation should be stopped. Delete locks are used to prevent accidental deletions, and currently with Terraform they do not fulfill that role.

### New or Affected Resource(s)

* azurerm_storage_account
* azurerm_storage_container
* azurerm_management_lock

### Potential Terraform Configuration

```hcl
terraform {}

# Providers
provider "azurerm" {
  version = "~> 1.42"
}

# Resource group
resource "azurerm_resource_group" "rg" {
  name     = "elias-storagetest-rg"
  location = "westeurope"
}

# Blob Storage
resource "azurerm_storage_account" "blob_storage" {
  name                      = "eliasvteststorage"
  resource_group_name       = azurerm_resource_group.rg.name
  location                  = azurerm_resource_group.rg.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true
}

## Blob Container
resource "azurerm_storage_container" "blob_container" {
  name                 = "eliastestblobcontainer"
  storage_account_name = azurerm_storage_account.blob_storage.name
}

# Create delete lock for Storage Account
# --> When attempting delete through Azure Portal, this works as expected and
#     stops the delete.
# --> When attempting delete through Terraform, this DOES NOT work as expected
#     and delete goes through
# --> When attempting delete through local Azure Storage Explorer, this DOES
#     NOT work as expected and delete goes through
resource "azurerm_management_lock" "lock_storage_account" {
  name       = "BlobStorageDeleteLock"
  scope      = azurerm_storage_account.blob_storage.id
  lock_level = "CanNotDelete"
  notes      = "Locked to prevent accidental deletion"
}

# Data Lake Storage Gen 2
resource "azurerm_storage_account" "data_lake_storage" {
  name                      = "eliastestadls"
  resource_group_name       = azurerm_resource_group.rg.name
  location                  = azurerm_resource_group.rg.location
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "LRS"
  enable_https_traffic_only = true
  is_hns_enabled            = true
}

# Data Lake Storage Filesystem
resource "azurerm_storage_data_lake_gen2_filesystem" "filesystem" {
  name               = "eliastestfilesystem"
  storage_account_id = azurerm_storage_account.data_lake_storage.id
}

# Create delete lock for Data Lake Storage
# --> This DOES NOT prevent deleting filesystems in the ADLS with any of the 
#     tested tools - delete goes through from Portal, Terraform, local Storage
#     Explorer
resource "azurerm_management_lock" "lock_adls" {
  name       = "AdlsDeleteLock"
  scope      = azurerm_storage_account.data_lake_storage.id
  lock_level = "CanNotDelete"
  notes      = "Locked to prevent accidental deletion"
}

```

### References
* (none yet)

**Comment by eliasvakkuri** [comment]
Added some more information. Looks like locks on Storage Accounts / Data Lake Storage Gen 2's do not always work as expected with Microsoft tools either. As there are differences between tools despite doing the same operation, I would assume that there is some difference in the underlying API's that are being used. Maybe different API versions? Anyway, would be great if the correct behavior (always stopping the delete of Blob Containers / Filesystems if there is a Delete Lock on the Storage Account) could be supported in Terraform.

**Comment by tombuildsstuff** [comment]
@eliasvakkuri this is due to the authentication method (SharedKey) and API's (Data Plane) being used:

The Storage API's also support authenticating using AzureAD (which allows using the Resource Manager API's (rather than the Data Plane API's, which allow both AzureAD and SharedKey auth). Whilst we looked to use this previously there's a significant downside to this which is that the roles required for interacting with the Storage API's are added for new role assignments (e.g. assigning the Contributor/Owner role assignment to a user/service principal today) but haven't been retroactively been added to existing users with these roles). Last time we tried making that change unfortunately it ended up causing a significant amount of user confusion, since multiple accounts could look the same but have different behaviours.

I've not tried it, but given you can set locks at that level I'd wager that the Resource Manager API's take the locks into account - however as you've mentioned most clients don't use the Resource Manager API's and instead use the Data Plane API's; since the Resource Manager API's have only recently become available (and don't support all features e.g. uploading files, as an example).

Whilst we have plans to add a Feature Toggle to allow interaction using Azure AD rather than Shared Key authorization - unfortunately we're unable to switch across to the Resource Manager API's since they don't support authenticating using a Shared Key (which is required due to the permissions issue mentioned above).

Due to this unfortunately this isn't something we're likely to be able to action using the Azure Locks functionality anytime soon - however you should be able to achieve this [within Terraform using the Terraform Specific locking equivalent: `prevent_destroy`](https://www.terraform.io/docs/configuration/resources.html#prevent_destroy) - would you be able to take a look and see if that works for you?

Thanks!

**Comment by eliasvakkuri** [comment]
@tombuildsstuff thanks for the great explanation! I'll need to give the prevent_destroy a look.

**Comment by tombuildsstuff** [comment]
hey @eliasvakkuri 

Just to give an update here - ultimately as mentioned above this isn't something we're going to be able to fix for the foreseeable future (since this permission isn't assigned by default/is unclear) - we're now exposing a `resource_manager_id` field for the `azurerm_storage_container` and `azurerm_storage_share` resources - which should provide the Resource Manager ID needed to create this lock.

I've not tested this - but you may also wish to try creating a lock on both the Data Plane ID (`https://foo.blob.windows.net/bar`) and the Resource Manager ID (`/subscriptions/...`).

Since this isn't something we're going to be able to fix anytime soon (and ultimately is a bug/enhancement in the Storage API's more than something we can fix within Terraform) - I'm going to suggest that we close this issue for the moment.

That said, should the Azure Storage Data Plane API's support the Write Locks associated from the Resource Manager API's - this should start working automatically - as such I'd suggest [opening an issue on the Rest API specs Repository here](https://github.com/Azure/azure-rest-api-specs/issues) where the Storage API team should be able to take a look.

Thanks!

**Comment by eliasvakkuri** [comment]
Thanks again @tombuildsstuff ! Great update on the situation, this is much more than I was expecting :) I'll check your suggestions
