### ISSUE TITLE
azurerm_kubernetes_cluster/agent_pool_profile - Way to add additional storage.

### ISSUE THREAD

**Issue by hetii** [terraform-providers/terraform-provider-azurerm#4685]
Hi Guys.

Is it possible to define somehow additional storage that will be mounted to each vm nodes used for AKS?

My goal is to use rook or glusterfs on the same nodes that handle kubernetes.

Best Regards.

**Comment by tombuildsstuff** [comment]
hi @hetii 

Thanks for opening this issue.

Unfortunately it's not possible to configure this through the AKS API at this time - I'd suggest instead opening an issue [on the AKS Repository](https://github.com/Azure/AKS/issues) where a member of the AKS Team should be able to point you in the right direction here (perhaps there's something you can configure within Kubernetes itself).

However since this issue isn't specific to Terraform (but is more a usage question regarding AKS, which should be answered by the AKS Team) I'm going to close this issue in the moment.

Thanks!
