### ISSUE TITLE
Terraform docs giving 404s

### ISSUE THREAD

**Issue by pmcq** [terraform-providers/terraform-provider-azurerm#469]
Hi,

The azure resource manager docs seem to be broken (giving 404s on the provider) https://www.terraform.io/docs/providers/azurerm/index.html.  I'm not sure if this is related to a recent release from a couple hours ago or if that process is out-of-band and takes some time but I just stumbled onto that while refreshing a page on the docs.

**Comment by tristanstraub** [comment]
Also seeing this. Links from azure docs back to terraform azurerm provider are failing.

**Comment by tombuildsstuff** [comment]
Hey @pmcq @tristanstraub 

Thanks for opening this issue :)

The 404's you've seen were due to a configuration error in the website, which was deployed as part of the latest Terraform Core & AzureRM Provider releases. Apologies for the inconvenience - however the good news is this has since been fixed (and I can confirm the link above works as expected) - as such would you be able to take another look?

Thanks!

**Comment by tristanstraub** [comment]
@tombuildsstuff Works again. Thanks!

**Comment by pmcq** [comment]
Looks good, thanks!
