### ISSUE TITLE
Subnet route table association created by kubernetes resource is later removed

### ISSUE THREAD

**Issue by worldspawn** [terraform-providers/terraform-provider-azurerm#4719]
This isn't really a bug but more of a _gotcha_. I had a terraform file that defined a subnet and a kubernetes cluster and associated that subnet with the cluster's node pool.

```
resource "azurerm_subnet" "subnet" {
  name                 = "db-t-aksnodes-${local.region}-${local.env}"
  resource_group_name  = "${data.azurerm_resource_group.regiongroup.name}"
  address_prefix       = "10.1.${local.subnetstart}.0/24"
  virtual_network_name = "${data.terraform_remote_state.region_common.outputs.appnet}"
}
```

I ran into a problem when on a subsequent apply terraform saw that the subnet now had a route table on it that wasn't part of the original configuration so it removed that association (and i didn't pick up on it in the output).

Havent got around to checking yet but this can be probably be worked around by ignoring the route_table_id...

```
lifecycle {
    ignore_changes = [route_table_id]
  }
```

Just wanted to call it out though as it almost brought my cluster to a stop and was a real bastard to track down.

**Comment by tombuildsstuff** [comment]
hey @worldspawn 

Thanks for opening this issue.

In 1.x versions of the Azure Provider associating a Subnet to a Route Table requires doing so in both the `azurerm_subnet` (via the `route_table_id` field) and `azurerm_subnet_route_table_association ` resources. Version 2.0 of the Azure Provider (being tracked in #2807) removes the `route_table_id` field from the `azurerm_subnet` resource which means that you'll only need to use the `azurerm_subnet_route_table_association` resource to configure this association.

Whilst I appreciate the UX here isn't ideal, this is to ensure that we don't break a use-case where removing the `route_table_id` field from the `azurerm_subnet` resource removes the route table from the subnet - as such [we've documented this behaviour both in the `azurerm_subnet` and the Route Table & Network Security Group association resources](https://www.terraform.io/docs/providers/azurerm/r/subnet_route_table_association.html) (since the behaviour is the same for each).

Since this behaviour is intentional - rather than having multiple issues open tracking the same thing I'm going to close this in favour of #4719 - but ultimately this'll be fixed by #2807 in the near future.

Thanks!
