### ISSUE TITLE
Create MongoDB v3.6 with azurerm_cosmosdb_account 

### ISSUE THREAD

**Issue by CapoD** [terraform-providers/terraform-provider-azurerm#4757]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We need to create a CosmosDB with a MongoDB **3.6** API Version.

### New or Affected Resource(s)

* azurerm_cosmosdb_account

### Potential Terraform Configuration

```hcl
capabilities {
    name = "MongoDBv3.6"
}
```

### References
void

**Comment by peterbev** [comment]
I'm not a go developer but I'm assuming that the "good first issue" label is because at it's most basic, enabling MongoDB 3.6 simply needs EnableMongo adding to the capabilities:
```
"capabilities": {
	Type:     schema.TypeSet,
	Optional: true,
	Elem: &schema.Resource{
		Schema: map[string]*schema.Schema{
			"name": {
				Type:             schema.TypeString,
				Required:         true,
				DiffSuppressFunc: suppress.CaseDifference,
				ValidateFunc: validation.StringInSlice([]string{
					"EnableTable",
					"EnableGremlin",
					"EnableCassandra",
					"EnableMongo", // Enable MongoDB 3.6 wire protocol support
					"EnableAggregationPipeline",
					"MongoDBv3.4",
					"mongoEnableDocLevelTTL",
				}, true),
			},
		},
	},
	Set: resourceAzureRMCosmosDBAccountCapabilitiesHash,
},
```

However, as there is no validation of the capabilities I think it would only compound a situation that is already confusing: 

- `EnableTable`, `EnableGremlin` and `EnableCassandra` are only valid with kind `GlobalDocumentDB` and are all mutually exclusive.
- `EnableAggregationPipeline`, `MongoDBv3.4` and `mongoEnableDocLevelTTL` are only valid with kind `MongoDB` but are additive.

Adding `EnableMongo` which is not compatible  with `EnableAggregationPipeline`, `MongoDBv3.4` and `mongoEnableDocLevelTTL` as the latter are preview capabilities associated with the original MongoDB 3.2 to me just seems more confusing.

It's possible I'm over complicating things and it just needs calling out in the docs...

**Comment by peterbev** [comment]
Now I think about it, there's also the question of whether the resource needs to be recreated, `EnableAggregationPipeline`, `MongoDBv3.4` and `mongoEnableDocLevelTTL` can be added to an existing CosmosDB account assuming it's of kind MongoDB and `EnableMongo` hasn't been specified. In all other cases the CosmosDB account will need recreating if capabilities are updated.

**Comment by aristosvo** [comment]
I'm trying to pick this up, but I'm not used to Go. I'll do my best:)
