### ISSUE TITLE
azurerm_app_service_environment: possible to complete now?

### ISSUE THREAD

**Issue by ahukin** [terraform-providers/terraform-provider-azurerm#4817]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Given the upgrade to azure-sdk-for-go for 1.37.0 is it now possible to complete the work on the azure_app_service_environment resource?

### New or Affected Resource(s)

azure_app_service_environment

### References

[[WIP] New Resource: `azurerm_app_service_environment`  #869](https://github.com/terraform-providers/terraform-provider-azurerm/pull/869)
[CHANGELOG "Release" 1.37.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md)

* #0000

**Comment by tombuildsstuff** [comment]
hi @ahukin 

Thanks for opening this issue.

Support for App Service Environments is being tracked in #438 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one - would you mind subscribing to #438 for updates?

From our side we're currently focused on 2.0 (which is detailed in #2807) which is required to ship support for App Service Environments (since they have such a long deployment time). Once 2.0 is shipped we're planning to take another look into supporting App Service Environments - however at the moment unfortunately we're blocked until 2.0 is out (since Custom Timeouts are required, which ship in 2.0).

Thanks!
