### ISSUE TITLE
Is there a way to enable Continuous deployment with Web App for Containers

### ISSUE THREAD

**Issue by kdevesh** [terraform-providers/terraform-provider-azurerm#4856]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

I want to enable this below option outlined in red while creating Appservice through terrafrom.
It would be good if someone can guide me on how to do it as i cannot find any option in Tf modules for app service
![image](https://user-images.githubusercontent.com/23445849/68679650-4b947b00-0586-11ea-92cc-b865fd7c72cf.png)
@tombuildsstuff

**Comment by tombuildsstuff** [comment]
hi @kdevesh 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
