### ISSUE TITLE
How to create a webtest alert notification

### ISSUE THREAD

**Issue by TVH7** [terraform-providers/terraform-provider-azurerm#4861]
I've seen the following issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/3868 but the given solution is only for a 'group' of Alerts in application insights and also does't work reliably, for example; when a service is back up there is no 'resolved' message send. Is this just not supported yet, or is the API bugged, because like mentioned in the ticket above, using Microsoft.Insights/Webtests does not work properly.  

I'm basically trying to replicate the following rule from the azure portal (what you get when you create an alert manually within the portal) 

Condition: Whenever the failed locations is greater than or equal to 2 
Action: Inform action group 1 

If anything is unclear, please let me know I'll elaborate further. 

Thanks in advance.

**Comment by tombuildsstuff** [comment]
hi @TVH7 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!

**Comment by TVH7** [comment]
@tombuildsstuff This issue is not fully seen as a question, rather as feedback that we need better documentation on the alert_notification + we need out of the box for webtest support, as you can see the mentioned issue also mentioned this and nothing has changed ever since. 

Please reopen.
