### ISSUE TITLE
Enable Azure Monitor for Virtual machines using terraform.

### ISSUE THREAD

**Issue by Kanikamiglani31** [terraform-providers/terraform-provider-azurerm#4864]
I am trying to enable azure monitor feature for virtual machines which checks for health and performance of the VM using terraform but I am not able to find the right documentation for the same. Can you help me for the same because I want detailed monitoring for azure?

This is what I want to automate using terraform, enable health & performance using Azure Monitor for VM's

**Comment by priyaananthasankar** [comment]
+1. Looking for the same. I can find documentation for log analytics + VM Insights, but the existing VM onboarding into these is missing.

**Comment by tombuildsstuff** [comment]
hi @Kanikamiglani31 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
