### ISSUE TITLE
Support for zoneRedundant property of azurerm_eventhub_namespace

### ISSUE THREAD

**Issue by ablyler** [terraform-providers/terraform-provider-azurerm#4872]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for zone redundant eventhub namespaces.

### New or Affected Resource(s)

* azurerm_eventhub_namespace

### Potential Terraform Configuration

```hcl
resource "azurerm_eventhub_namespace" "test" {
  name                = "acceptanceTestEventHubNamespace"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"
  sku                 = "Standard"
  capacity            = 2
  zone_redundant      = true

  tags = {
    environment = "Production"
  }
}
```

### References

* https://azure.microsoft.com/en-us/blog/azure-event-hubs-is-now-offering-support-for-availability-zones-in-preview/

**Comment by tombuildsstuff** [comment]
Taking a look into this it appears this should be possible using an updated version of the EventHub SDK - https://github.com/Azure/azure-sdk-for-go/blob/v36.2.0/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub/models.go#L817-L818

**Comment by brunhil** [comment]
@tombuildsstuff , I'm interested in adding this enhancement. Since we'd be updating the EventHub SDK version, we would want to update the EventHub SDK for the following resources as well, correct?
- resource_arm_eventhub_authorization_rule
- resource_arm_eventhub_consumer_group
- resource_arm_eventhub_namespace_authorization_rule
- resource_arm_eventhub_namespace_disaster_recovery_config
- resource_arm_eventhub

That way we wouldn't fragment versions of the API across resources. Thoughts?

**Comment by katbyte** [comment]
Correct @brunhil, we would update them all to the latest SDK and add the propery

**Comment by brunhil** [comment]
Sounds good @katbyte. I can take a stab at this, just one follow up question. What is the teams thoughts on updating all Event Hub resources to the preview version of the SDK? I'm cautious to switch over completely due preview SDKs being able to be deprecated "at will".

**Comment by tombuildsstuff** [comment]
@brunhil generally speaking we avoid Preview's if there's a Stable API containing the same information - but if it's in Public Preview then we should be fine (since the API is more stable than a Private Preview) - so it should be fine 👍

**Comment by arvan-pritchard** [comment]
https://azure.microsoft.com/en-us/updates/service-bus-and-event-hubs-availability-zones-now-generally-available-ga/ says this is now GA

**Comment by rudolphjacksonm** [comment]
Would love if we could get this implemented--we're still using ARM templates to deploy redundant Event Hub namespaces and it's a bit of a pain.

**Comment by mguirao** [comment]
I started to implement that but it is not as easy as it seems because the api '2018-01-01-preview' doesn't include everything that is in the '2017-04-01'. 
DisasterRecovery stuff is missing from the preview api, so it would cause regressions (it actually can't build if you just replace it).

What would be the next step ?

**Comment by mguirao** [comment]
I just dig a bit more, and the 2 api versions have actually nothing in common when comparing the 2 package :
[preview/eventhub/mgmt/2018-01-01-preview/eventhub](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v41.2.0+incompatible/services/preview/eventhub/mgmt/2018-01-01-preview/eventhub)
[eventhub/mgmt/2017-04-01/eventhub](https://pkg.go.dev/github.com/Azure/azure-sdk-for-go@v41.2.0+incompatible/services/eventhub/mgmt/2017-04-01/eventhub)
