### ISSUE TITLE
Support for Failure Anomaly and Smart Detect Alerts

### ISSUE THREAD

**Issue by ahukin** [terraform-providers/terraform-provider-azurerm#4874]
Sorry for the question here: there didn't seem to be many answers on the other sites.

Is it possible to create Failure Anomaly and Smart Detect Alerts using the standard azurerm resources or must we use the azurerm_template_deployment resource?  If it's not an azurerm_template_deployment, which resource should we use (azurerm_monitor_metric_alert?) and what argument settings should we use?

Many thanks

**Comment by nejoyer** [comment]
I'm also interested.

**Comment by tombuildsstuff** [comment]
hi @ahukin @nejoyer 

Thanks for opening this issue - apologies for the delayed response here.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
