### ISSUE TITLE
Shared Image Gallery versions

### ISSUE THREAD

**Issue by nicethomaslearngit** [terraform-providers/terraform-provider-azurerm#4926]
Hi Team

Could you kindly help how to get all the image version numbers existing in my shared Image gallery.

Like I have 1.0.1 , 1.0.2 and 1.0.3.

How can I list all the versions.

I tried using azurerm_shared_image_gallery , shared_image and shared_image_version but no luck.

Could you please assist

**Comment by nicethomaslearngit** [comment]
Hi @tombuildsstuff 

Could you please assist on this

**Comment by tombuildsstuff** [comment]
hi @nicethomaslearngit 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!

**Comment by nicethomaslearngit** [comment]
Hi @tombuildsstuff 

 This is a bug with Azure provider - as not able to list the image versions using

https://www.terraform.io/docs/providers/azurerm/d/shared_image_gallery.html
https://www.terraform.io/docs/providers/azurerm/d/shared_image_version.html
https://www.terraform.io/docs/providers/azurerm/d/shared_image.html
