### ISSUE TITLE
Setting vnet_subnet_id while network_plugin is set to "kubenet" should raise an error

### ISSUE THREAD

**Issue by stromvirvel** [terraform-providers/terraform-provider-azurerm#4934]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* Terraform v0.11.13
* azurerm 1.36.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_network" "this" {
  name                 = "vnet01"
  location             = "${var.location}"
  resource_group_name  = "${azurerm_resource_group.this.name}"
  address_space        = ["10.112.0.0/21"]
}

resource "azurerm_subnet" "k8s_prod01" {
  name                 = "k8s_prod01"
  resource_group_name  = "${azurerm_resource_group.this.name}"
  address_prefix       = "10.112.0.0/24"
  virtual_network_name = "${azurerm_virtual_network.this.name}"
}

resource "azurerm_kubernetes_cluster" "prod01" {
  name                = "prod01"
  location            = "${var.location}"
  resource_group_name = "${azurerm_resource_group.this.name}"
  dns_prefix          = "prod01"
  kubernetes_version  = "${var.k8s_version}"

  agent_pool_profile {
    name                = "default"
    count               = "${var.k8s_nodes_count}"
    vm_size             = "Standard_DS3_v2"
    os_type             = "Linux"
    os_disk_size_gb     = 50
    vnet_subnet_id      = "${azurerm_subnet.k8s_prod01.id}"
  }

  service_principal {
    client_id     = "${var.provide_azurerm_client_id}"
    client_secret = "${var.provide_azurerm_client_secret}"
  }
}
```

### Expected Behavior

Terraform should raise an error, because `vnet_subnet_id` is set, and `network_policy` is unset (defaults to `kubenet`).

### Actual Behavior

Terraform doesn't raise an error, instead deploys an Kubernetes cluster in Azure (AKS service) with an invalid configuration. Pods are not able to communicate with Internet.

### Steps to Reproduce

1. `terraform apply` the code above

### References

* https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems we need more contexts for the scenario you pointed out. May I know is there any document is talking about this scenario is incorrect setting and how to check pods are not able to communicate with Internet? I think terraform shouldn't add restriction for api usage and api should return error if it doesn't support this scenario.

**Comment by mybayern1974** [comment]
@stromvirvel , I'd like to summarize Neil's investigation:
1. It's a valid scenario that subnet and network_policy = kubenet can co-exist, since the attached doc above in detail described how to config to make things work by this combination. So we may not expect TF throws errors against this valid scenario.
2. You mentioned things still did not work (Pods are not able to communicate with Internet), may I suggest you could firstly, w/o Terraform, ensure things could work by following that doc with getting how properties should be config-ed correctly, after which go back to Terraform to see whether there is any gap between Terraform and the expected property config. 
If you agree, would you mind we close this issue for now since this repo serves Terraform Azure Provider feature / bugs more than how to play with a specific Azure service. Feel free to reopen an issue if you believe it's Terraform related. Thank you.
