### ISSUE TITLE
azurerm_front_door

### ISSUE THREAD

**Issue by shan0809** [terraform-providers/terraform-provider-azurerm#4935]
The documentation for Azure Front Door has a type where in the Resource API should be "azurerm_frontdoor" rather than "azurerm_front_door" which is mentioned in the documentation.

if you use the boilerplate code mentioned in the document:
resource "azurerm_front_door" "example" {
  name                                         = "example-FrontDoor"
  location                                     = "${azurerm_resource_group.example.location}"
  resource_group_name                          = "${azurerm_resource_group.example.name}"
  enforce_backend_pools_certificate_name_check = false
}

The above code will fail while running terraform plan as it will say "it doesn't support the resource type"

However below code will work like a charm:
resource "azurerm_frontdoor" "example" {
  name                                         = "example-FrontDoor"
  location                                     = "${azurerm_resource_group.example.location}"
  resource_group_name                          = "${azurerm_resource_group.example.name}"
  enforce_backend_pools_certificate_name_check = false
}

**Comment by tombuildsstuff** [comment]
hey @shan0809 

Thanks for opening this issue.

The fix for this issue is available in the master branch and will be updated on the website once the Provider Release happens later this week. Since the fix for this has been merged I'm going to close this issue for the moment - but thanks for letting us know and this should be shipped in the next couple of days :)

Thanks!
