### ISSUE TITLE
Re run of Function App template is causing error

### ISSUE THREAD

**Issue by nikhilpulluri-gep** [terraform-providers/terraform-provider-azurerm#4939]
I am unable run the functionapp script second time after creating it for the first time like how i can run for Resource group how many times i want.
it is giving following error.
azurerm_function_app.test: The name "{Here name of functionapp}" used for the Function App needs to be globally unique and isn't available: Hostname '{Here name of functionapp}' already exists. Please select a different name.

Can you suggest me how it can be done.

**Comment by tombuildsstuff** [comment]
hi @nikhilpulluri-gep 

Thanks for opening this issue

When a resource is created with Terraform, it's added to a Statefile (generally `terraform.tfstate`) which tracks the state of all the resources Terraform's managing. 

Since the Statefile tracks these resources over time, we recommend storing Terraform's Statefile either in [Terraform Cloud](https://www.hashicorp.com/blog/announcing-terraform-cloud/) or using a Backend (such as [Azure Blob Storage](https://www.terraform.io/docs/backends/types/azurerm.html)).

If a resource isn't found in the State, when you run `terraform apply` Terraform will try and create it from scratch, which is what's happened here. It's also possible to import existing resources into Terraform's State using [the `terraform import` command](https://www.terraform.io/docs/commands/import.html), for instance [here's the command needed to import a Kubernetes Cluster](https://www.terraform.io/docs/providers/azurerm/r/function_app.html#import).

Specifically with the error being returned from the Azure API here:

> azurerm_function_app.test: The name "{Here name of functionapp}" used for the Function App needs to be globally unique and isn't available: Hostname '{Here name of functionapp}' already exists. Please select a different name.

Since Terraform isn't tracking this Function App in it's Statefile - it's trying to create it from scratch, which in the case of a Function App confirms that the Name being used is globally unique - since the error messages returned from the Azure API aren't overly helpful.

As such you should be able to work around this by importing the Function App into Terraform's Statefile ([example of how to do that](https://www.terraform.io/docs/providers/azurerm/r/function_app.html#import)) which will then allow you to track/modify this Function App as necessary; would you be able to take a look and see if this works for you?

The behaviour you're seeing with Resource Groups is a bug where resources can be "adopted" into the Statefile due to the Azure API design and will be fixed in 2.0 (more details can be found in #2807) - where you'll be required to import these resources into the state rather than "adopting" them into Terraform's State file as today.

Since this behaviour is intentional I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
