### ISSUE TITLE
There is no support for vnet_subnet_id in azurerm_api_management?

### ISSUE THREAD

**Issue by anonymous202020** [terraform-providers/terraform-provider-azurerm#4942]
Hello together,

I read many issues about azurerm_api_management support for subnet reference in the azurerm_api_management resource. But it looks like it's not implemented yet?

```
resource "azurerm_api_management" "api_gateway"{
...
  vnet_subnet_id = "subnetXY"
  vnet_type = "External"
...
}
```

[Like here](https://www.reddit.com/r/Terraform/comments/adn36r/terraform_with_azure_api_management/)
[and here](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1520)

Well, still after that time there is no solution in sight? Do we must workaround with an arm template in terraform...

I really appreciate any suggestions since I lost already one day.

https://www.terraform.io/docs/providers/azurerm/r/api_management.html

**Comment by tombuildsstuff** [comment]
hi @anonymous202020 

Thanks for opening this issue.

This functionality isn't supported at this time due to a bug in the Azure API - [the upstream issue tracking this is here](https://github.com/Azure/azure-rest-api-specs/issues/6372) but essentially when the new API version goes live (and is available in the Azure SDK for Go), it should be possible to upgrade to this and for someone to take a look into the API Management issues that are blocked by this ([example](https://github.com/terraform-providers/terraform-provider-azurerm/issues/2613)).

Unfortunately in the interim there's not a whole bunch we can do to work around this - support for this is being tracked in #3667, and rather than having multiple issues open tracking the same thing I'm going to close this in favour of #3667 - would you mind subscribing to that issue for updates?

Thanks!
