### ISSUE TITLE
SIG image versions issue

### ISSUE THREAD

**Issue by nicethomaslearngit** [terraform-providers/terraform-provider-azurerm#4943]
Hi @tombuildsstuff  / Team

Could you kindly help on the below.

currently I am giving image_version  =  latest . but the issue here is it is evaluating the azurerm_shared_image_version and the version ( name = 1.0.1 ) needs to be existing. If I gave name = 10.10.10 , which is a non existent image version in SIG - the script fails.

So is there a way to skip a complete data read set here. 

Also I am not seeing an option to list all the image versions in SIG

data "azurerm_shared_image" "centos7" {
  name                                  = "centos"
  gallery_name                        = "centos_galleries"
  resource_group_name           = "centos-galleries-rg"
}

data "azurerm_shared_image_version" "centos7" {
  name                                  = "1.0.1"  ## [ This block fails when provided a dummy number ]
  image_name                      = "centos"
  gallery_name                     = "centos_galleries"
  resource_group_name       = "centos-galleries-rg"
}

output "id" {
     value = "${var.image_version == "latest" ? data.azurerm_shared_image.centos7.id : data.azurerm_shared_image_version.centos7.id}"
    }

**Comment by tombuildsstuff** [comment]
hi @nicethomaslearngit 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
