### ISSUE TITLE
azurerm_role_assignment

### ISSUE THREAD

**Issue by sebastus** [terraform-providers/terraform-provider-azurerm#495]
### Terraform Version
terraform v0.10.7-dev
azurerm v0.3.2

### Affected Resource(s)
azurerm_role_assignment

### Terraform Configuration Files
```hcl
```data "azurerm_subscription" "primary" {}

data "azurerm_client_config" "test" {}

data "azurerm_builtin_role_definition" "test" {
  name = "Reader"
}

resource "azurerm_role_assignment" "test" {
  name               = "00000000-0000-0000-0000-000000000000"
  scope              = "${data.azurerm_subscription.primary.id}"
  role_definition_id = "${data.azurerm_subscription.primary.id}${data.azurerm_builtin_role_definition.test.id}"
  principal_id       = "${data.azurerm_client_config.test.service_principal_object_id}"
}

### Expected Behavior
create the role assignment

### Actual Behavior
* azurerm_role_assignment.test: authorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailed" Message="The client '06ce6bb4-51ed-4d42-8bac-7d0f53d2e1f4' with object id '06ce6bb4-51ed-4d42-8bac-7d0f53d2e1f4' does not have authorization to perform action 'Microsoft.Authorization/roleAssignments/write' over scope '/subscriptions/743f6ed6-83a8-46f0-822d-ea93b953952d'."

### Steps to Reproduce
1. `terraform apply`

**Comment by tombuildsstuff** [comment]
Hi @sebastus 

The error message you're seeing is because the User/AAD Application Terraform is running as doesn't have permissions to create the role assignment. From memory, I believe the `contributor` role doesn't have this permission - and you may need to use an account with `owner` rights (or use a custom role to grant this permission).

Would you be able to take a look and confirm which permissions the user/application has?

Thanks!

**Comment by tombuildsstuff** [comment]
@sebastus have you had a chance to look at this yet?

**Comment by tombuildsstuff** [comment]
Hey @sebastus 

I'm going to close this issue since we've not heard back from you here - but please feel free to re-open it if there's still an issue here and we'll take another look

Thanks!

**Comment by cwiggs** [comment]
I had this same issue and realized that the problem was that I had ARM* env variables set for a service account and forgot about them.  Even though I ran `az login` and `az account list` showed the correct credentials terraform was trying to use the ARM* env variables.

Once I unset the env variable terraform worked correctly.

**Comment by pavank** [comment]
For anyone coming here via a search engine, @tombuildsstuff is right, for `azurerm_role_assignment` to work the Service Prinicipal used by terraform must have Owner permissions (Contributor is not sufficient). I have not tried the Custom Role Definition option suggested.
