### ISSUE TITLE
Version 1.36.1 doesn't detect containers

### ISSUE THREAD

**Issue by jamesbannan** [terraform-providers/terraform-provider-azurerm#4969]
This is the same behaviour observed in #3919 - when executing a simple Terraform configuration which contains a Resource Group, Storage Account and Container with NO pre-existing state file and where all the resources have already been deployed, Terraform adds all resources to the plan but successfully verifies that the Resource Group and Storage Account already exist. However Terraform fails to verify that the container already exists and errors out when it attempts to create a container with the same name.

Enabling `ARM_PROVIDER_STRICT` is not an option because this configuration is responsible for deploying the resources in the first place, hence running `terraform import` is not possible as the resource IDs are unknown.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.16
+ provider.azurerm v1.36.1

### Affected Resource(s)

azurerm_storage_container

### Terraform Configuration Files

```hcl
resource "azurerm_storage_container" "customer" {
  name                  = "${local.customer_code_lower}-tf-state"
  storage_account_name  = azurerm_storage_account.state.name
  container_access_type = "private"
}
```

### Debug Output

Error: Error creating Container "xxx-tf-state" (Account "xxxxxx" / Resource Group "xxx-state"): containers.Client#Create: Failure sending request: StatusCode=409 -- Original Error: Error occurred unmarshalling JSON - Error = 'invalid character '<' looking for beginning of value' JSON = '<?xml version="1.0" encoding="utf-8"?><Error><Code>ContainerAlreadyExists</Code><Message>The specified container already exists.

### Expected Behavior

Terraform generates a new plan and expects to create all resources. When `terraform apply` is executed, because all resources already exist, nothing should be changed and Terraform should complete successfully.

### Actual Behavior

Terraform generates a new plan and expects to create all resources. When `terraform apply` is executed, Terraform does not attempt to recreate the Resource Group or Storage Account (these complete successfully) but Terraform attempts to deploy the container. Because this already exists, an error is received and Terraform fails.

### Steps to Reproduce

1. Create a simple configuration which deploys an `azurerm_resource_group`, `azurerm_storage_account` and `azurerm_storage_container`.
2. Deploy the configuration with `terraform apply`
3. Delete the state file
4. Redeploy the same configuration

**Comment by mbfrahry** [comment]
Hi @jamesbannan, many resources in the Azure sdk are upserts that overwrite what is currently being held in Azure. While this may seem handy in your use case, we could potentially overwrite someones infrastructure that uses the same name as what's in a Terraform configuration. In 2.0 of the provider, we are preventing people from automatically upserting new to Terraform resources and instead will guide users on how to import those into Terraform. Your use case currently doesn't work for `azurerm_storage_container` because unlike many resources where we have a unified CreateUpdate function that upserts this resource, we instead have separate create/update functions. Which means we fail on create because we only call the create API which fails since the resource already exists. We'll have a better error message in 2.0 for how to correctly handle this but this is by design for Terraform (not just the azure provider) that Terraform expects resources that already exist to be imported and Azure breaks that design by upserting most resources.

**Comment by jamesbannan** [comment]
Thanks @mbfrahry for the explanation. Much appreciated.
