### ISSUE TITLE
azurerm_api_management_product_api does not assign an API to a product if this assignment existed previously

### ISSUE THREAD

**Issue by eugeneromero** [terraform-providers/terraform-provider-azurerm#5002]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

1.37.0

### Affected Resource(s)

* `azurerm_api_management_product_api`

### Terraform Configuration Files

```hcl
resource "azurerm_api_management_product_api" "attach" {
  product_id = "test"
  api_name = "myAPI"
  api_management_name = "myAPImanager"
  resource_group_name = "rg"
}
```

### Expected Behavior

After creating an API and attaching it to a product with Terraform, one should be able to delete the API and, upon recreating it, the API should be attached to the product again.

### Actual Behavior

When recreating the API, Terraform creates the API succesfully, but does not see the need to add it to the product, so the API ends up with no product assignment. If one tries assigning it to a _different_ product however, this works successfully.

When performing the plan, terraform _does_ refresh the `product_api` state, but it thinks the API is still assigned to the product (from its previous assignment) so does not attempt to add it again.

### Steps to Reproduce

1. Declare a new API with `azurerm_api_management_api`
1. Add the API to an existing product with `azurerm_api_management_product_api`
1. `terraform plan` & `apply`, the API is created and added successfully to the product
1. Manually remove the API from the API Management
1. Run `terraform plan --refresh=true` and `apply` again
1. Terraform recreates the API but does not assign it to a product
1. Repeat the above three steps but change the `product_id` to a different one, TF successfully adds it to the product

### References

* #0000

**Comment by eugeneromero** [comment]
Pinging @tombuildsstuff since he is the original creator of this resource :)

**Comment by evertonmc** [comment]
bug seems to be related to the Plan checking if the *_product_api already exists before creating
https://github.com/terraform-providers/terraform-provider-azurerm/blob/0fd80ac109826ceb3c2cd6ca791b5943e45ec0c4/azurerm/resource_arm_api_management_product_group.go#L94-L96 
and never getting into because the client will return error==nil for NotFound status codes (when the *_product_api link doesn't exist yet)

https://github.com/terraform-providers/terraform-provider-azurerm/blob/0fd80ac109826ceb3c2cd6ca791b5943e45ec0c4/vendor/github.com/Azure/azure-sdk-for-go/services/apimanagement/mgmt/2018-01-01/apimanagement/productapi.go#L131-L139

In this stage, tf doesn't plan the creation of the `azurerm_api_management_product_api` because it ignores the _missing_ existence
