### ISSUE TITLE
azurerm_kubernetes_cluster with multiple agent_pool_profiles shows changes on every plan/apply

### ISSUE THREAD

**Issue by spanktar** [terraform-providers/terraform-provider-azurerm#5007]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.14, azurerm 1.37.0

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
resource "azurerm_kubernetes_cluster" "az_kubernetes_cluster" {
  dns_prefix          = "dns"
  kubernetes_version  = "1.14.7"
  location            = "westus2"
  name                = "aks"
  resource_group_name = "${azurerm_resource_group.aks_resource_group.name}"

  agent_pool_profile {
    count               = 1
    enable_auto_scaling = true
    max_count           = 12
    min_count           = 1
    name                = "default"
    os_disk_size_gb     = "100"
    os_type             = "Linux"
    type                = "VirtualMachineScaleSets"
    vm_size             = "Standard_B2ms"
  }

  agent_pool_profile {
    count               = 1
    enable_auto_scaling = true
    max_count           = 12
    min_count           = 1
    name                = "balanced"
    node_taints         = ["node=restricted:NoSchedule"]
    os_disk_size_gb     = "100"
    os_type             = "Linux"
    type                = "VirtualMachineScaleSets"
    vm_size             = "Standard_D2_v3"
  }
...
}
```

### Expected Behavior

apply with no changes shouldn't show changes (which cause a complete destroy/create of the AKS cluster)

### Actual Behavior

Terraform plan shows changes

### Steps to Reproduce

1. `terraform apply && terraform plan`

### References

**Comment by sasan-hashemi** [comment]
Microsoft is screwing us all over again:

>     ~ network_profile {
>             dns_service_ip     = "10.3.0.10"
>             docker_bridge_cidr = "172.17.0.1/16"
>           ~ load_balancer_sku  = "Standard" -> "standard"
>             network_plugin     = "azure"
>             network_policy     = "azure"
>           + pod_cidr           = (known after apply)
>             service_cidr       = "10.3.0.0/16"
>         }

For no reason, they have started changing the "Standard" to "standard" 
Similar to this issue:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/4774

**Comment by tombuildsstuff** [comment]
@jluk 👋🏻 looks like there's a breaking behavioural change to the response outside of a version bump?

**Comment by tombuildsstuff** [comment]
hey @spanktar 

Thanks for opening this issue.

In version 1.37 of the Azure Provider the `azurerm_kubernetes_cluster` resource went through a bunch of changes to account for the way the API now works. Due to this the `agent_pool_profile` block has been deprecated and replaced by the `default_node_pool` block and the separate `azurerm_kubernetes_cluster_node_pool` resource.

Whilst ultimately you'll need to switch from using the `agent_pool_profiles` block over to using the `default_node_pool` block & the new separate resource - in the interim you should be able to continue using the `agent_pool_profile` block by using Terraform's `ignore_changes` functionality, for example:

```
resource "azurerm_kubernetes_cluster" "test" {
   # ...
   
   agent_pool_profile { ... }

   lifecycle {
    ignore_changes = [
      "default_node_pool"
    ]
  }
}
```

Which should show no changes and continue to use the existing block.

Since the `agent_pool_profile` block will be removed in 2.0 - we'd suggest switching over to the `default_node_pool` block which you can do by adding that in and removing the `ignore_changes` element:

```
resource "azurerm_kubernetes_cluster" "test" {
   # ...
   
   default_node_pool { ... }
}
```

At which point you should be migrated across - would you be able to take a look and see if that works for you?

Thanks!

**Comment by jluk** [comment]
@sasan-hashemi / @tombuildsstuff the AKS RP will accept "standard" or "Standard" as input for the load balancer sku.

Could you detail the steps to reproduce this problem and the prior setup that accepted this input to help baseline investigation? Is there any case handling changes on the Terraform implementation side or info to help us diagnose?

From what I can tell the Azure Go SDK seems to not have any changes wrt casing for AKS either.
