### ISSUE TITLE
Support for setting mySQL server parameters

### ISSUE THREAD

**Issue by 0xErnie** [terraform-providers/terraform-provider-azurerm#5041]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When managing Azure Databases for MySQL I need to set timezone, character set and enable the event scheduler.
It would be great to set this with the terraform provider.

### New or Affected Resource(s)

* azurerm_mysql_server

### Potential Terraform Configuration

```hcl
resource "azurerm_mysql_server" "k8s" {
  name                = var.cluster_name
  location            = var.location
  resource_group_name = var.resource_group

  sku {
    ...
  }

  storage_profile {
    ...
  }

...

  server_parameters {
    time_zone = UTC
    character_set_server = UTF8
    event_scheduler = ON
  }

}
```

### References

I did not find any issues or pull requests mentioning anything smiliar.

**Comment by tombuildsstuff** [comment]
hi @0xErnie 

Thanks for opening this issue :)

Support for this is available via [the `azurerm_mysql_configuration` resource](https://www.terraform.io/docs/providers/azurerm/r/mysql_configuration.html) - which should allow you to configure these settings - would you be able to take a look and see if that works for you? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll look another look

Thanks!
