### ISSUE TITLE
Provider doesn't support data source: azurerm_automation_account_registration _info error while using azure automation account data source module

### ISSUE THREAD

**Issue by sbhat1** [terraform-providers/terraform-provider-azurerm#5097]
I am trying to use azurerm_automation_account_registration_info Terraform data source to retrieve the Automation account info as below. However receiving 

**The provider provider.azurerm does not support data source"azurerm_automation_account_registration_info".** when running terraform plan

I even tried with upgrading to latest version of Terraform still getting the same error

Below is the sample code

**data "azurerm_automation_account_registration_info" "aa" {
  name                = var.automation_account_name
  resource_group_name = var.automation_account_rg_name
}
output "automation_account_endpoint" {
  value = data.azurerm_automation_account_registration_info.aa.endpoint
}**

**Comment by katbyte** [comment]
Hi @sbhat1,

It seems that the documentation is correct, however the data source has been added to the provider as `data.azurerm_automation_account`. I've opened #5281 to rename it.

**Comment by tombuildsstuff** [comment]
hey @sbhat1 

Thanks for opening this issue.

Taking a look through here it appears this is a bug in the documentation, where the Data Source is named `azurerm_automation_account` rather than `azurerm_automation_account_registration_info` - I'll open a PR to fix this documentation bug shortly, which will go out as a part of the next release. Would you be able to take a look and see if switching to use `azurerm_automation_account` works for you in the interim?

Thanks!
