### ISSUE TITLE
Terraform-provider-azurerm - SQL database private link?

### ISSUE THREAD

**Issue by rubenandre1** [terraform-providers/terraform-provider-azurerm#5098]
Is it possible to set a private link to SQL DATABASE with Terraform?

**Comment by tombuildsstuff** [comment]
hi @rubenandre1 

Thanks for opening this issue.

Support for Private Link Endpoints has recently become available in version 1.38 of the Azure Provider - [which can be found in the documentation](https://www.terraform.io/docs/providers/azurerm/r/private_link_endpoint.html)). 

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but if that doesn't work for you then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
