### ISSUE TITLE
Continuously creating new K8S Cluster

### ISSUE THREAD

**Issue by Callum1201** [terraform-providers/terraform-provider-azurerm#5114]
We appear to be having an issue where a new Kubernetes Cluster is created each deployment and the old one deleted. Terraform plan reports:
'2019-12-09T20:54:43.6926588Z [1m  # azurerm_kubernetes_cluster.SelenityKubernetes[0m must be [1m[31mreplaced[0m[0m'

This is despite there being no changes at all.

The code for the cluster is as follows:
`## CREATE KUBERNETES CLUSTER ##
## Creates the Kubernetes Cluster

resource "azurerm_kubernetes_cluster" "__KubernetesClusterName__" {
	name = "__KubernetesClusterName__"
	location = "${azurerm_resource_group.__ResourceGroup__.location}"
	resource_group_name = "${azurerm_resource_group.__ResourceGroup__.name}"
	dns_prefix = "__dnsPrefix__"
	
	agent_pool_profile {
		name = "__PoolProfileName__"
		count = "__PoolProfileCount__"
		vm_size = "__KubernetesSize__"
		enable_auto_scaling = __autoscalingenabled__
		os_type = "__OSType__"
		type = "VirtualMachineScaleSets"
		vnet_subnet_id = "${azurerm_subnet.__Subnet__.id}"
		min_count = "__minScaling__"
		max_count = "__maxScaling__"
	}

	## Enable Kubernetes Dashboard for Testing
	addon_profile {
		kube_dashboard {
			enabled = true
		}
	}

	## This is required in order to allow communication with the registry
	service_principal {
		client_id = "__servicePrincipalClientID__"
		client_secret = "__servicePrincipalClientSecret__"
		}
}`

**Comment by mariojacobo** [comment]
Same issue here, it seems to happen only with the new azurerm provider 1.37.0; with 1.34.0 it's working as expected.

**Comment by tombuildsstuff** [comment]
hi @Callum1201 

As [mentioned in the changelog for the v1.37 release](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#1370-november-26-2019) - unfortunately due to a breaking change in the Azure API the `agent_pool_profiles` block has been replaced by the `default_node_pool` block:

> The azurerm_kubernetes_cluster resource has undergone substantial changes in this release to work around breaking behavioural changes in the Azure API. As such the agent_pool_profile block has been superseded by the default_node_pool block. Multiple Node Pools can instead be configured using the azurerm_kubernetes_cluster_node_pool resource.

It should be possible to fix this by switching over to using the `default_node_pool` block (and `azurerm_kubernetes_cluster_node_pool` resource, if you have multiple node pools) instead - would you be able to take a look and see if switching over works for you?

Whilst it's unfortunate we've had to ship a breaking behavioural change in a non-major version of the Azure Provider, unfortunately the Azure API changed substantially enough that this was the best way to account for this change. Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by mariojacobo** [comment]
@tombuildsstuff while we have no issues migrating to the new provider, just wanted to mention the behavior is a bit strange. I deploy the cluster with the "agent_pool_profile" using 1.37.0 without a problem. on the second run, that's when it actually wants to delete and recreate the cluster. just mentioning here in case other folks hit the same.
