### ISSUE TITLE
support for onpremise data connection gateway  for azurerm_analysis_services 

### ISSUE THREAD

**Issue by Nareshkg** [terraform-providers/terraform-provider-azurerm#5137]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I was able to create  azurerm_analysis_services_server, however I don't see the resource/arguments to create onpremise connection data gateway.

**Comment by r0bnet** [comment]
Hey @Nareshkg,

i implemented the `azurerm_analysis_services_server` resource back then and there is the possibility to set the ID of the Data Gateway in the underlying SDK. Unfortunately back then i wasn't able to test this functionality and i'm still not sure how to write a good test for it now.

I'd rather not add something to that resource that might be brittle due to lack of tests.

From my understanding i would need a Data Gateway and for that i'd also need something called installation? Can you provide some deeper information so that we could create test for it? Then the implementation shouldn't be a problem.

**Comment by tombuildsstuff** [comment]
hi @Nareshkg 

Since we've not heard back from you here I'm going to close this issue for the moment as unfortunately there isn't enough information for us to proceed here; however if you're able to provide that information then we can re-open this and take another look.

Thanks!
