### ISSUE TITLE
KeyVault access_policy.4.object_id" isn't a valid UUID ("")

### ISSUE THREAD

**Issue by manohar650** [terraform-providers/terraform-provider-azurerm#5155]
Error: "access_policy.4.object_id" isn't a valid UUID (""): uuid string is wrong length

HERE IS MY CODE:

```
data "azurerm_client_config" "current" {}

dynamic "access_policy" {
    for_each = var.vault_managers
    content {
      tenant_id = data.azurerm_client_config.current.tenant_id
      object_id = access_policy.value.object_id

      key_permissions = [
        "get", "list", "update", "create", "import", "delete", "recover", "backup", "restore"
      ]

      secret_permissions = [
        "get", "list", "set", "delete", "recover", "backup", "restore"
      ]

      certificate_permissions = [
        "get", "list", "update", "create", "import", "delete", "recover", "backup", "restore",
        "managecontacts", "manageissuers", "getissuers", "listissuers", "setissuers", "deleteissuers"
      ]
    }
  }
```

**Comment by tombuildsstuff** [comment]
hi @manohar650 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
