### ISSUE TITLE
azurerm_subnet disable_private_link_endpoint_network_policy_enforcement property is not expexted

### ISSUE THREAD

**Issue by bricebauer** [terraform-providers/terraform-provider-azurerm#5156]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- terraform 0.12.18

- provider.azurerm v1.38

### Affected Resource(s)

* `azurerm_subnet`

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "endpoint" {
  name                 = "endpoint"
  resource_group_name  = "azr-rsg-test-infra"
  virtual_network_name = "azr-vnet-infra"
  address_prefix       = "10.0.232.176/28"

  disable_private_link_endpoint_network_policy_enforcement = true
}
```

### Expected Behavior

apply on subnet with property disable_private_link_endpoint_network_policy_enforcement set to use private link

### Actual Behavior

Error: Unsupported argument

  on main.tf line 16, in resource "azurerm_subnet" "endpoint":
  16:   disable_private_link_endpoint_network_policy_enforcement = true

An argument named "disable_private_link_endpoint_network_policy_enforcement"
is not expected here.

### Steps to Reproduce

1. `terraform apply` or `terraform plan`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @bricebauer 

Thanks for opening this issue.

In Terraform this property is [exposed as `enforce_private_link_endpoint_network_policies`](https://www.terraform.io/docs/providers/azurerm/r/subnet.html#enforce_private_link_endpoint_network_policies) rather than as `disable_private_link_endpoint_network_policy_enforcement ` - would you be able to try using that field instead?

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
