### ISSUE TITLE
azurerm_container_service Swarm example fails during apply

### ISSUE THREAD

**Issue by jeffreyCline** [terraform-providers/terraform-provider-azurerm#518]
### Terraform Version
Terraform v0.10.9-dev (46d2b76e5f7d1591f66c45312d7a25be37dba7c8)
provider.azurerm v0.3.2

### Affected Resource(s)
azurerm_container_service

### Terraform Configuration Files
```hcl
resource "azurerm_resource_group" "test" {
  name     = "acctestRG1"
  location = "West US"
}

resource "azurerm_container_service" "test" {
  name                   = "acctestcontservice1"
  location               = "${azurerm_resource_group.test.location}"
  resource_group_name    = "${azurerm_resource_group.test.name}"
  orchestration_platform = "Swarm"

  master_profile {
    count      = 1
    dns_prefix = "acctestmaster1"
  }

  linux_profile {
    admin_username = "acctestuser1"

    ssh_key {
      key_data = "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCqaZoyiz1qbdOQ8xEf6uEu1cCwYowo5FHtsBhqLoDnnp7KUTEBN+L2NxRIfQ781rxV6Iq5jSav6b2Q8z5KiseOlvKA/RF2wqU0UPYqQviQhLmW6THTpmrv/YkUCuzxDpsH7DUDhZcwySLKVVe0Qm3+5N2Ta6UYH3lsDf9R9wTP2K/+vAnflKebuypNlmocIvakFWoZda18FOmsOoIVXQ8HWFNCuw9ZCunMSN62QGamCe3dL5cXlkgHYv7ekJE15IA9aOJcM7e90oeTqo+7HTcWfdu0qQqPWY5ujyMw/llas8tsXY85LFqRnr3gJ02bAscjc477+X+j/gkpFoN1QEmt terraform@demo.tld"
    }
  }

  agent_pool_profile {
    name       = "default"
    count      = 1
    dns_prefix = "acctestagent1"
    vm_size    = "Standard_A0"
  }

  diagnostics_profile {
    enabled = false
  }

  tags {
    Environment = "Production"
  }
}
```
### Debug Output
https://gist.github.com/jeffreyCline/8100be1086fada38f3831fefd5c9ca8c

### Expected Behavior
1. Successfully roll out the azurerm_container_service

### Actual Behavior
1. Error message stating "...Agent is not allowed in your subscription in location 'westus'..."

### Steps to Reproduce
1. `terraform apply`

**Comment by devigned** [comment]
Default VM size is not available in region:

> The VM Size of Master, Agent is not allowed in your subscription in location 'westus'. Master VM Size 'Standard_D2_v2' is available in locations: eastus, southcentralus, westeurope, southeastasia. Agent VM Size 'Standard_A0' is available in locations: eastus, southcentralus, westeurope, southeastasia.

Same as https://github.com/terraform-providers/terraform-provider-azurerm/issues/510

**Comment by tombuildsstuff** [comment]
Hey @jeffreyCline 

This issue is almost identical to #510 - as such I'm going to refer [to my comment there](https://github.com/terraform-providers/terraform-provider-azurerm/issues/510#issuecomment-341882682); I think the simplest thing to do to solve this is going to be updating the location to be `East US` rather than `West US`? In addition - do you think it's worth removing the Swarm example from the documentation and instead linking to an example for it in the `examples/` folder?

Thanks!

**Comment by jeffreyCline** [comment]
I did eventually get this to work by updating the location to East US, however when I run it again I get the error "...DNS record acctestmaster1.eastus.cloudapp.azure.com is already used by another public IP..." ( see the ![gist](https://gist.github.com/jeffreyCline/26291de303eb30c29af55db47a877b84) here). So I attempted to update the dns_prefix in the .tf file which gives me a different error when running apply "...Changing property 'agentProfile.dnsPrefix' is not allowed..."

**Comment by tombuildsstuff** [comment]
hi @jeffreyCline @devigned 

Apologies for the delayed update here!

Microsoft's recently announced [the deprecation of Azure Container Service in favour of Azure (Managed) Kubernetes Service](https://azure.microsoft.com/en-us/updates/azure-container-service-will-retire-on-january-31-2020/).

In preparation for this [we're deprecating the `azurerm_container_service` resource in version 1.20 of the AzureRM Provider](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2481) - as such when using a `1.x` version of the AzureRM Provider the `azurerm_container_service` will continue to function until the API is removed on the 31st January 2020.

We plan to remove support for the `azurerm_container_service` resource in version 2.0 of the AzureRM Provider - should you wish to continue using the AzureRM Provider past this date you'll need to ensure your Provider block is pinned to a 1.x version, for example:

```
provider "azurerm" {
  version = ">= 1.0.0, <= 2.0.0"
}
```

alternatively you can pin the Provider block to a specific version ([more information about version pinning can be found on the Provider page](https://www.terraform.io/docs/configuration/providers.html)):

```
provider "azurerm" {
  version = "=1.19.0"
}
```

If you're using ACS with Kubernetes Microsoft's recommendation is to migrate to using Azure (Managed) Kubernetes Service (AKS) which is available as [the `azurerm_kubernetes_cluster` resource](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html) within Terraform.

Since the `azurerm_container_service` resource is being deprecated, I'm going to close this issue for the moment.

Thanks!
