### ISSUE TITLE
storage account requires explicit dependency

### ISSUE THREAD

**Issue by drewmullen** [terraform-providers/terraform-provider-azurerm#5187]
`azurerm_storage_account` resource can no longer resolve rsg dependency. setting explicit is a current workaround but i figured id report it anyways since this used to work without it.

Error:
```
Error: Error creating Azure Storage Account "<mystorageaccountname>": storage.AccountsClient#Create: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceGroupNotFound" Message="Resource group 'drew-rsg' could not be found."
```

terraform code:
```
resource "azurerm_resource_group" "main" {
  name     = var.resource_group_name
  location = var.location
}


provider "azurerm" {
  version         = ">=1.30.0"
  subscription_id = var.arm_subscription_id
  tenant_id       = var.arm_tenant_id
  client_id       = var.arm_client_id
  client_secret   = var.arm_client_secret
}

resource "azurerm_storage_account" "main" {
  name                     = var.tfstate_storage_account_name
  location                 = var.location
  resource_group_name      = var.resource_group_name
  account_tier             = "Standard"
  account_replication_type = "GRS"
}

resource "azurerm_storage_container" "main" {
  name                  = "tfstate"
  storage_account_name  = azurerm_storage_account.main.name
  container_access_type = "private"
}
```

terraform version:
```
terraform version
Terraform v0.12.18
+ provider.azurerm v1.39.0
```

**Comment by msygmatic** [comment]
Have you tried doing something like this?

`resource "azurerm_storage_account" "main" {
  name                                 = var.tfstate_storage_account_name
  location                             = var.location
  resource_group_name      = **azurerm_resource_group.main.name**
  account_tier                      = "Standard"
  account_replication_type = "GRS"
}`

To enforce implicit dependencies?

I've tried that solution (and had done it successfully before) in my own code, but it doesn't work. I'm using modules in my case, but I wouldn't imagine that would cause a difference.

**Comment by tombuildsstuff** [comment]
hi @drewmullen 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through as @msygmatic has mentioned it should be possible to use an implicit dependency on the Resource Group to enforce the Resource Group to be created before the Storage Account. Alternatively as you've mentioned you can use an Explicit Dependency should you wish not to use an Implicit Dependency - however without a dependency of some form unfortunately Terraform is unable to determine which should be created in which order, and thus can end up creating them in parallel, where this'll fail.

Since this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.
Thanks!
