### ISSUE TITLE
Extend Data factory datasources/datasets, Linked services and triggers

### ISSUE THREAD

**Issue by svangeti** [terraform-providers/terraform-provider-azurerm#5223]
### Description

There are wide variety of datasources/ datasets/linked service types available for Azure Data factory but only very limited small set is available from terraform provider.

### New or Affected Resource(s)

* azurerm_data_factory
* azurerm_data_factory_linked_service
* azurerm_data_factory_trigger

### Potential Terraform Configuration

```hcl
The below reference APIs' have potential terraform configurations
```

### References

https://docs.microsoft.com/en-us/azure/templates/microsoft.datafactory/2018-06-01/factories/datasets#dataset-object
refer `type` enum set
https://docs.microsoft.com/en-us/azure/templates/microsoft.datafactory/2018-06-01/factories/datasets#dataset-object
refer `type` enum set

**Comment by stinkyfriend** [comment]
Yes. Currently there are:

azurerm_data_factory_dataset_[mysql || postgresql || sql_server_table]
azurerm_data_factory_linked_service_[data_lake_gen2 || mysql || postgresql || sql_server]

I really need **table_storage**.

**Comment by tombuildsstuff** [comment]
hi @svangeti 

Thanks for opening this issue.

Since there's a large number of these resources but some are more popular than others we've opted to add support for Data Factory Data Sources/Linked Services as they're requested/based on demand.

If you're looking for the Azure Provider to support additional Datasets/Linked Services please open a new Feature Request for each of the Linked Services containing some details about what you're looking for (the feature request template contains the data we need) and then someone should be able to take a look at this at some point; however since this is a question rather than bug in the Azure Provider I'm going to close this issue for the moment.

Thanks!
