### ISSUE TITLE
Error building AzureRM Client: Azure CLI Authorization Profile was not found. Please ensure the Azure CLI is installed and then log-in with `az login`. 

### ISSUE THREAD

**Issue by yanni1994** [terraform-providers/terraform-provider-azurerm#5245]
I'm getting this issue when i run in terraform cloud, I have setup service principal in azure, gave the needed cred in env variable in my work space.

**Comment by yupwei68** [comment]
Could you run `echo $ARM_CLIENT_ID` double check your environment variable?

**Comment by tombuildsstuff** [comment]
hi @yanni1994 

Thanks for opening this issue.

The issues on this repository are used to track issues and feature enhancements in the Azure Provider. Since this is a question around usage within Terraform Cloud, [would you mind reaching out to Terraform Cloud Support who should be able to assist](https://support.hashicorp.com/hc/en-us)? Since this is a question regarding Terraform Cloud rather than the Azure Provider directly - I'm going to close this issue for the moment, however the Terraform Cloud Support team should be able to assist here :)

Thanks!
