### ISSUE TITLE
Updating terraform files from version 1.22 to 1.39 with out changing manually in every file

### ISSUE THREAD

**Issue by venkey1000** [terraform-providers/terraform-provider-azurerm#5253]
Hi, We are largely dependent on Terraform for our infra launch in scale(like thousands of azure resources have been launched), we are looking to upgrade terraform provider version from 1.22 to 1.39(latest right now). Is there any way to upgrade this smoothly.
One way is updating tf files manually by checking the fields which are deprecated but this we can not do as there are so many resources present. Is there any better way for updating?

**Comment by vermaabhay** [comment]
I am also stuck at the same issue. Please help..!!

**Comment by katbyte** [comment]
@venkey1000, @vermaabhay,

What you can do is pin to the newest version of the provider (prior to 2.0) and run plan. It should then tell you what properties are deprecated allowing you to make the required changes (as well as see if there are any behaviour changes that may need addressing)

**Comment by venkey1000** [comment]
Hi @katbyte ,
We are able to figure out the deprecated fields by running the plan, there are three types of changes for update,
1) Deprecated fields 
2) route table association needs different resource to be created in 1.39
3) values for some fields are becoming case sensitive

As i have few hundreds of tf files, i can not do it manually, i need to do it programatically, In the above points i have mentioned i can do change #1 programatically , but change #2 and #3 are bit difficult to do programatically, i have to do manually. Is there any better automatic way(like any command for updating tf files to particular version) for updating?

**Comment by tombuildsstuff** [comment]
hi @venkey1000 

>  Is there any better automatic way(like any command for updating tf files to particular version) for updating?

We've put out an [upgrade guide for the 2.0 release](https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html) containing all removals, since this is a major release - however for deprecations we rely on the inline warnings and notes in the changelog.

Unfortunately there's no automated mechanism for doing so at this time - that said this sounds like something that'd be beneficial. So that the Terraform Core team can dig into this use-case further - would you mind [opening an issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) so that the Core Team can take a look and better understand the specific use-case you have in mind here? (e.g. if that's a command like `terraform provider config-upgrade` or similar)

For the moment since this isn't something directly actionable in the Azure Provider at this time, I'm going to close this issue for the moment - however should support for this become available in Terraform Core we'd look to use this for deprecations going forward

Thanks!
