### ISSUE TITLE
Terraform v0.12.18

### ISSUE THREAD

**Issue by rajgsdei** [terraform-providers/terraform-provider-azurerm#5266]
After updating to Terraform v0.12.18 I am getting the below error when I do **Terraform PLAN**, I login to Azure CLI using service principle. Before updating it was working fine. Any help would be appreciated.

**Error: Error building account: Error getting authenticated object ID: Error pars**
**ing json result from the Azure CLI: Error waiting for the Azure CLI: exit status**
 1

 **on <empty> line 0:**
 **(source code not available)**

**Comment by tombuildsstuff** [comment]
hi @rajgsdei 

Thanks for opening this issue.

The Azure Provider supports authenticating either directly with a Service Principal, using MSI or using a User Account with the Azure CLI. Unfortunately the Azure CLI behaves differently when authenticating as a user account vs a service principal - since [we support authenticating as a Service Principal directly](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html), we only support authenticating using the Azure CLI with a User Account.

Instead [we support authenticating directly using a Service Principal](https://www.terraform.io/docs/providers/azurerm/guides/service_principal_client_secret.html) - would you be able to take a look and see if switching to that authentication method works for you? 

Since authenticating using the Azure CLI and a Service Principal isn't supported I'm going to close this issue for the moment - however please let us know if switching to using the Service Principal directly doesn't work for you and we'll take another look.

Thanks!

**Comment by rakimsbi** [comment]
Hi,
I am facing the same issue. I tried user account & service principal. Could you guide me. Version i am using is - v0.12.18

**Comment by holmesb** [comment]
> "we only support authenticating using the Azure CLI with a User Account."

We can verify @rakimsbi's assertion that this is occurring for user account logins via az cli.  This issue needs reopening. 
Downgrading from v1.41.0 to v1.36.1 is a valid workaround.
