### ISSUE TITLE
Support for direct JWT token auth

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#5271]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, the arguments passed to the provider allow for Service Principal, MSI or CLI auth. The CLI auth actually just grabs the JWT token and requires that the Azure CLI also be installed, which it normally is.
https://github.com/hashicorp/go-azure-helpers/blob/34c41529a8327b89d14246895aa12a32e96d79b7/authentication/auth_method_azure_cli_token.go#L136

I see a benefit here in securing the client_id and client_secret, even from Terraform, and my use-case really involves automated pipelines where these are variables stored in the environment or similar. To that end, is there a way here to get rid of the Azure CLI use completely and allow an input to the provider called `token` and tied to an environment variable (`ARM_TOKEN`) that is used instead?

The benefit here is really attack surface reduction in organizations that are looking to keep the client secret out of variables, etc. The alternative method is that a JWT token has to be sourced prior to executing Terraform, and then the user or pipeline simply provides this valid token to Terraform. This is effectively what all of the auth methods are doing already - getting a token.

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  token = var.azure_token
}
```

**Comment by r0bnet** [comment]
Hey @mbrancato,

i understand what you're looking for and that is for sure possible. Question is if that really makes your pipelines more safe? I mean you just HAVE to get the JWT token in some prior step anyway. The only advantage i see is that you're not passing the creds to TF anymore.

I think you'd then try to get the token via az anyway or some custom stuff. This makes it less convenient for you i guess.

I think some of the main contributors should give their input to this. I currently don't see the big advantage but i'd let them decide.

**Comment by tombuildsstuff** [comment]
hi @mbrancato 

Thanks for opening this issue - apologies for the delayed response here!

From our side we'd generally recommend using a Service Principal with a Client Cert/Client Secret when running in an automated pipeline - whilst the Azure CLI may work here this isn't something we recommend since (amongst other reasons) the Azure CLI has a tendency to "move under your feet" where the CLI changes behaviour via the automatic updates, which isn't ideal in an automated environment.

Whilst we could look to accept a JWT in the provider block - in practice I think this'd end up causing more issues than it solved, since we need a means of refreshing said token (which in this instance would be by using the Azure CLI anyway).

Given the intention is to keep these credentials out of Terraform - this could also be achieved by introducing a means of specifying the contents of the Client Certificate via the Provider Block - which, whilst wouldn't fit into an Environment Variable would allow you to thread credentials from (say) Vault into the Azure Provider - ultimately solving this problem in a different way. That'd require some changes within [the hashicorp/go-azure-helpers repository](https;//github.com/hashicorp/go-azure-helpers) to be made prior to the changes being made in this repository.

As whilst we don't plan to support Direct JWT auth at this time - I'm going to close this issue for the moment - however if you'd instead be interested in this alternate approach outlined above then please [open an issue on the hashicorp/go-azure-helpers repository](https;//github.com/hashicorp/go-azure-helpers/issues) where we can take a look.

Thanks!
