### ISSUE TITLE
terraform_azurerm_appservice

### ISSUE THREAD

**Issue by Divya1388** [terraform-providers/terraform-provider-azurerm#5274]
Terraform Version: 0.12.7
Azurerm Version: 1.39.0

I am trying to create a web app inside an ASE ILB using the following configuration:
![Screen Shot 2019-12-28 at 4 21 49 PM](https://user-images.githubusercontent.com/47507148/71549602-3042cb00-298e-11ea-9e11-787220f565ac.png)

Everything works fine as long as i provide unique name for web app. I understand the fact that the webapp name should  be unique globally. 

However if we create a web app inside ase ilb using portal, we have option called region and if we specify ase ilb in the region attribute, it does not check for uniqueness globally, instead it will check for the uniqueness inside the ASE ILB. 
If i want to mimic the same using Terraform, I provide ase ilb in the location attribute, it errors. What is the way to address Region field in Azure web app

**Comment by tombuildsstuff** [comment]
hi @Divya1388 

Thanks for opening this issue :)

Taking a look through this functionality isn't supported today, but is being tracked in #3003 - rather than having multiple issues open tracking the same thing I'm going to close this issue in favour of that one; would you mind subscribing to #3003 for updates?

Thanks!
