### ISSUE TITLE
Support for Azure Databricks Clusters

### ISSUE THREAD

**Issue by D4zedC0der** [terraform-providers/terraform-provider-azurerm#5282]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Using the azurerm provider, I can create a Databricks workspace but I cannot create a Databricks cluster.

### New or Affected Resource(s)

* azurerm_databricks_workspace (existing)
* azurerm_databricks_cluster (new/proposed)

### Potential Terraform Configuration

```hcl
resource "azurerm_databricks_cluster" "example" {
  workspace_name = "${azurerm_databricks_workspace.example.name}"
  name = "My Test Cluster"
  mode = "Standard"
  databricks_runtime_version = "5.0"
  python_version = "3"

  autopilot_options = {
    autoscaling_enabled = true
    terminate_after_inactive_secs  = 120
    min_workers = "2"
    max_workers = "8"
  }

  driver_sku = "Standard_DS3_v2"
  worker_sku = "Standard_DS3_v2"

  spark_config = <<EOF
    spark.speculation true
    spark.kryo.registrator my.package.MyRegistrator
EOF

  environment_variables = <<EOF
    PYSPARK_PYTHON=python3.6
    JAVA_OPTS="-XX:MaxPermSize=256m"
EOF

  tags = {
    Environment = "QA"
  }

}
```

Perhaps it's better to have the autoscaling options be more consistent with other similar clusters, such as the "azurerm_batch_pool" resource?

### References
* https://docs.microsoft.com/en-us/azure/databricks/clusters/create

* #0000

**Comment by njuCZ** [comment]
I am working on this issue

**Comment by njuCZ** [comment]
for now, there is no rest api for databricks clusters
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databricks/resource-manager/Microsoft.Databricks/stable/2018-04-01/databricks.json

**Comment by rk-tbrigley** [comment]
Others are working on this, but not a lot of functionality yet, and we heard that databricks is doing their own providers, no

https://github.com/innovationnorway/terraform-provider-databricks

**Comment by lawrencegripper** [comment]
I might be in a position to pick up adding this as a PR into the Azure provider. If I was able to take on this work would there be a root to getting this merged?

@rk-tbrigley do you know anyone in Databricks working on their provider? Would be great to get in touch with them and make sure this isn't duplicated effort. 

In this space I also found another third party provider: https://github.com/betabandido/terraform-provider-databricks

**Comment by tombuildsstuff** [comment]
👋 hey @D4zedC0der @rk-tbrigley @lawrencegripper 

Thanks for opening this issue.

Whilst the AzureRM Provider supports creating a DataBricks Workspace (since this functionality is provided by the ARM API's) - configuration of resources within that Workspace are not specific to Azure/available in the ARM API's at this time.

Since this functionality isn't natively available in the Azure Resource Manager API's and also applies more generally to DataBricks - arguably these resources would make more sense in a DataBricks specific Terraform Provider, rather than being bundled into this one.

As such whilst I'd like to thank you for opening this issue (and the offer of PRing this @lawrencegripper) I'm going to close this issue for the moment in favour of the two DataBricks Providers linked above - however should support for this become available in the Azure Resource Manager API's we can re-open this and take a look.

Thanks!

**Comment by lawrencegripper** [comment]
Agree that makes sense, thanks @tombuildsstuff
