### ISSUE TITLE
azurerm_role_assignment is not state aware

### ISSUE THREAD

**Issue by sebader** [terraform-providers/terraform-provider-azurerm#5297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.18
azurerm provider 1.39.0

### Affected Resource(s)

* `azurerm_role_assignment`

### Terraform Configuration Files

```hcl
# this is just a sample. The same applies to any role assignment
resource "azurerm_role_assignment" "sp-acr-reader" {
  scope                = data.azurerm_container_registry.alwayson.id
  role_definition_name = "Reader"
  principal_id         = var.kubernetes_client_objectid
}
```

### Expected Behavior

Terraform should not fail if the role assignment already exists but rather take it into account for its state calculation.

### Actual Behavior
This is a recreated issue from this one, as it is closed but the issue is still there today: https://github.com/terraform-providers/terraform-provider-azurerm/issues/1857

"If a role is already assigned Terraform returns an Error saying that the role is already assigned.
Other Terraform resource like azurerm_resource_group or azurerm_virtual_network will just not return an error and the Terraform tfstate will integrate this resource as a compliant one."

```
019-12-18T16:03:33.4162579Z [1m[31mError: [0m[0m[1mauthorization.RoleAssignmentsClient#Create: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="RoleAssignmentExists" Message="The role assignment already exists."
2019-12-18T16:03:33.4163889Z [0m  on main.tf line 182, in resource "azurerm_role_assignment" "sp-acr-reader":
2019-12-18T16:03:33.4164377Z  182: resource "azurerm_role_assignment" "sp-acr-reader" [4m{[0m
```

### Steps to Reproduce

1. Assign a role manually
2. Try assigning it with Terraform, see this how to for example : https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @sebader 

Thanks for opening this issue.

As you've mentioned Terraform tracks the state of resources in it's Statefile and if it believes a resource hasn't been created (since it's not tracking it) it'll then look to re-create this resource. Generally speaking Terraform should be erroring if trying to create a resource which already exists - however there's a known issue in 1.x versions of the Azure Provider where certain resources may instead be "adopted" into the state (due to the majority of Azure's API's being Upserts, rather than separate Create/Update endpoints) rather than returning an error.

Whilst certain Azure API's are Upserts - unfortunately not all of them behave in the same manner (e.g. App Service, Storage) which means that we require to check for the presence of an existing resource prior to trying to create it to ensure that we can correctly track/update properties as required.

This is something we're looking to address in 2.0 (more details can be found in #2807) - which means that you'll be required to import existing resources into the state ([more details](https://www.terraform.io/docs/import/index.html) where they already exist, as v2.0 of the Azure Provider will now check for the presence of an existing resource when trying to create a new one.

Since this adoption behaviour isn't intentional and we're planning to remove this in the next major version of the Azure Provider (2.0) - unfortunately this isn't something we plan to add to additional resources; as such whilst I'd like to thank you for opening this issue, I'm going to close this for the moment.

Thanks!
