### ISSUE TITLE
Support for Azure VM host and host group

### ISSUE THREAD

**Issue by ssrirama-aka** [terraform-providers/terraform-provider-azurerm#5332]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure's Dedicated hosts service became generally available early December 2019. My team is evaluating this capability to run payloads on dedicated h/w. Our provisioning scripts are mostly Terraform-based. 

There are two new resource constructs enabled for dedicated hosts and a change to how a VM is placed on a dedicated host:
az vm host group create - _create a host group_
az vm host create - _create a host in a given host group_
az vm create --host-group _<associated host group>_ --host _<associated host>_

Specifying host-group and host with the vm create command places the VM on the particular host.

Are there plans to support these constructs in the Terraform provider? If yes, is there an anticipated time-frame to deliver support?

### New or Affected Resource(s)

* azurerm_virtual_machine

**Comment by magodo** [comment]
I have filed an PR #5307

**Comment by ssrirama-aka** [comment]
> I have filed an PR #5307

@magodo Thanks for the response. Am I correct in assuming the changes will enable these 3 things: create host group, create host in host group and associate new VM with the host?

**Comment by magodo** [comment]
@ssrirama-aka Sure, after dedicated host group PR is merged, I will submit another PR to support dedicated host. Afterwards, hopefully I will expose the `host` property in virtual machine resource(s) to associate with the host.

**Comment by tombuildsstuff** [comment]
👋

Since we're superseding the `azurerm_virtual_machine` resource in 2.0 (which I'm working on at the moment - more details can be found in #2807) - rather than adding a field to the existing `azurerm_virtual_machine` resource (which is now feature-frozen) it'd be better to instead look to add this to the replacement resources (which I'm working on at the moment).

Since I'm working on these new resources at the moment I'll look to include support for this in the new VM resources - which we should be able to do once support for Dedicated Host Group is added via #5307 (which we'll be merging shortly) and Dedicated Hosts are available in the near future 👍 

Thanks!

**Comment by ssrirama-aka** [comment]
@tombuildsstuff So the new host attribute would be added separately to the proposed `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources and be available only from 2.0 forward. This makes sense to me, though it means changes to our existing scripts.

**Comment by ssrirama-aka** [comment]
@tombuildsstuff  You indicated that `azurerm_virtual_machine` resource is feature frozen. So there's absolutely no chance of introducing the changes necessary for dedicated hosts into this resource in a 1.x release? 

The reason I ask is that our project needs to migrate to dedicated hosts as soon as possible. But we want to only go there with a clean, consistent azurerm Terraform provider version that fully supports dedicated hosts. With 2.0 being a significant release with many changes, some breaking, I was wondering if a 1.x version could be a vehicle for the dedicated host changes against `azurerm_virtual_machine`.

**Comment by tombuildsstuff** [comment]
👋 

Closing this out since support for these is now available in the form of [azurerm_dedicated_host](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dedicated_host) and [`azurerm_dedicated_host_group](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/dedicated_host_group)
