### ISSUE TITLE
Feature req: Allow for 'soft' image updates to VMSS

### ISSUE THREAD

**Issue by samirageb** [terraform-providers/terraform-provider-azurerm#536]
Presently, image updates to a VMSS trigger a full teardown & rebuild of the VMSS (and its instances) to match the configuration.

There are valid use cases where a non-destructive image update is preferred. In this instance the VMSS is updated with the appropriate image, but underlying VMSS instances are not automatically torn down and rebuilt as they may be in-use. Often auto-updating VMSS instances is left up to systems external to TF as they safely upgrade instances when appropriate.

I would propose some additional flag to allow this behavior to be 'soft' as an override, where the default behavior would be as it is today.

**Comment by tombuildsstuff** [comment]
hi @samirageb 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We've recently opened the PR for the first of these new resources #4518 - and I'm able to confirm that this new functionality is supported in the new Virtual Machine Scale Set resource - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine_scale_set` resource.

We've posted an update in #2807 with more information on this (we plan to release the new Virtual Machine / Virtual Machine Scale Set resources in a Beta form in a future 1.x version of the Azure Provider and subsequently release them as "GA" in 2.0) - but as we plan to post additional status updates for 2.0 in #2807 I'd suggest subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
