### ISSUE TITLE
How to use 'count' in "secondary" and "disaster_recovery_config" eventhub resources 

### ISSUE THREAD

**Issue by hisathya** [terraform-providers/terraform-provider-azurerm#5360]
We want to configure  "secondary" and "disaster_recovery_config" eventhub resources  only for Prod env.  So, I am using count for both resources in single .tf file.  However I see the count.index related errors when I perform 'terraform apply'.  How to resolve this ?

**Comment by tombuildsstuff** [comment]
hi @hisathya 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/docs/extend/community/index.html).

Thanks!
