### ISSUE TITLE
PrivateDNS API Version

### ISSUE THREAD

**Issue by colin-lyman** [terraform-providers/terraform-provider-azurerm#5395]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Having issues running TF v0.12 with Provider Azure 1.40 with private DNS as the API-version being used is 2018-09-01.  Can this be upgraded and tested with 2019-09-01?

**Comment by tombuildsstuff** [comment]
hi @colin-lyman

Thanks for opening this issue.

It's certainly possible that we could look to upgrade this - taking a quick look at our acceptance test suite for Private DNS it appears to be passing, as such I'm wondering what's the issue you're seeing that requires this?

Thanks!

**Comment by colin-lyman** [comment]
Hi @tombuildsstuff for the prompt response.

I've spent today troubleshooting with Microsoft around problems with creating and deleting Private DNS zones after trying and failing to attach a VNET Link.  

They suggested updating the API terraform use.  However, I've noticed MSFT has not yet updated the Azure SDK for Go which I'm assuming will be required before TF can be updated.

Error from MSFT for zone deletion:  Can not delete resource before nested resources are deleted.  On an online blog suggests Azure takes up to 24hours to clear.

Error from MSFT for Link creation: VNET already in use.  This is possible in case the virtual network was re-created.  Please delete all stale virtual network links and try again.

I'll keep this thread up to date of any updates.

**Comment by tombuildsstuff** [comment]
@colin-lyman 

> Can not delete resource before nested resources are deleted.

Unfortunately that sounds like a bug in the Delete API - generally speaking these API bugs tend to continue to exist in API versions until they're reported upstream - as such it's likely this'll require more work than just upgrading the API version, but we'll be able to confirm once we look into upgrading this.

So that we both diagnose this and confirm if upgrading the API version fixes this (or if we require some additional workarounds until the API bug is fixed) - would it be possible to show the Terraform Configuration being used here? Based on what you've mentioned above I'm assuming that's creating/deleting a Private DNS Zone with a Private Link (Endpoint)?

Thanks!

**Comment by tombuildsstuff** [comment]
hi @colin-lyman 

Since we've not heard back from you here I'm going to close this issue for the moment - but if you're able to provide the information requested above we'll circle around and take another look 👍 

Thanks!
