### ISSUE TITLE
azurerm_app_configuration access keys are lists and not maps...why?

### ISSUE THREAD

**Issue by rdbartram** [terraform-providers/terraform-provider-azurerm#5400]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

0.12.13
1.40.0

### Affected Resource(s)

* `azurerm_app_configuration

### Terraform Configuration Files

```hcl
output "appconfig_connection_str" {
  value = azurerm_app_configuration.vh.primary_read_key[0].connection_string
}

output "appconfig_connection_str_write" {
  value = azurerm_app_configuration.vh.primary_write_key.connection_string
}
```

### Debug Output

Error: Unsupported attribute

  on modules\AppConfiguration\outputs.tf line 2, in output "appconfig_connection_str":
   2:   value = azurerm_app_configuration.vh.primary_read_key.connection_string[0]

This value does not have any attributes.

### Expected Behavior

The *_key attributes returned from the resource should be maps not lists...from my understanding that there is only one of each key type.

### Actual Behavior

Error: Unsupported attribute

  on modules\AppConfiguration\outputs.tf line 6, in output "appconfig_connection_str_write":
   6:   value = azurerm_app_configuration.vh.primary_write_key.connection_string

This value does not have any attributes.

### Steps to Reproduce

1. `terraform validate`

**Comment by tombuildsstuff** [comment]
hi @rdbartram 

Thanks for opening this issue :)

Terraform uses Lists and Maps to represent different types of data - we use Lists for values when we know the keys/values of the inner properties and maps for when these keys are dynamic.

In this instance since each of the `(primary|secondary)_(read|write)_key` blocks have the same nested properties - rather than making these 12 top level properties we've opted to expose this as a List, since we know the three inner properties each of these blocks contains (`id`, `secret` and `connection_string`). Since these values are Lists of Blocks you should be able to access this data via:

```
azurerm_app_configuration.vh.primary_write_key.0.connection_string
```

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but please let us know if accessing the values in the manner mentioned above doesn't work for you and we'll take another look :)

Thanks!

**Comment by benbelow** [comment]
Hi @tombuildsstuff, I've just run into some confusion regarding this syntax myself, and thankfully this issue proved helpful in accessing the connection_string property. I'm aware you'd rather not re-open this particular issue, but would it be possible to update the documentation to make this usage a little clearer as it currently stands? https://www.terraform.io/docs/providers/azurerm/r/app_configuration.html doesn't make it clear that the values should be accessed as lists. 

If there is a better place to raise this please let me know as well :)
