### ISSUE TITLE
Install Linkerd in aks cluster

### ISSUE THREAD

**Issue by SidGrundfos** [terraform-providers/terraform-provider-azurerm#5408]
Hi Team,
Can I get some samples where I can install LinkerD service mesh using terraform into an aks cluster?

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. Seems it's not an issue/bug but a question about API usage. Suggests to submit the question to community.
* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @SidGrundfos 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
