### ISSUE TITLE
Azure Linux VM change passes plan but fails on apply during API call

### ISSUE THREAD

**Issue by dgsd-consulting** [terraform-providers/terraform-provider-azurerm#5418]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.19
+ provider.azurerm v1.40.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

```hcl
  os_profile_linux_config {
    disable_password_authentication = var.vm.disable-password-auth

    ssh_keys {
      path     = "/home/${var.vm.admin-user}/.ssh/authorized_keys"
      key_data = var.azure-secrets.public-key
    }
  }
```

### Debug Output (terraform plan)
```
      + os_profile_linux_config {
          + disable_password_authentication = false

          + ssh_keys {
              + key_data = "ssh-rsa *** OBFUSCATED ***"
              + path     = "/home/*** OBFUSCATED ***/.ssh/authorized_keys"
            }
        }
      - os_profile_linux_config {
          - disable_password_authentication = true -> null

          - ssh_keys {
              - key_data = "ssh-rsa *** OBFUSCATED ***" -> null
              - path     = "/home/*** OBFUSCATED ***/.ssh/authorized_keys" -> null
            }
        }
...
Plan: 0 to add, 1 to change, 0 to destroy.
------------------------------------------------------------------------
This plan was saved to: targets/dev-run
To perform exactly these actions, run the following command to apply:
    terraform apply "targets/dev-run"
```

### Expected Behavior
The plan expects to change the resource because I had changed `disable_password_authentication = var.vm.disable-password-auth` and I expected the apply to work successfully.

### Actual Behavior
The apply fails and produced the following output:
```
make apply
Acquiring state lock. This may take a few moments...
module.test-vm.azurerm_virtual_machine.vm[0]: Modifying... [id=/subscriptions/*** OBFUSCATED ***/resourceGroups/*** OBFUSCATED ***/providers/Microsoft.Compute/virtualMachines/VM-TEST-VM-1]

Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'linuxConfiguration.disablePasswordAuthentication' is not allowed." Target="linuxConfiguration.disablePasswordAuthentication"

  on lib-virtual-machine/main.tf line 1, in resource "azurerm_virtual_machine" "vm":
   1: resource "azurerm_virtual_machine" "vm" {
```

### Steps to Reproduce

1. Create any resource with `azurerm_virtual_machine` using Linux and set `disable_password_authentication = False`
2. Run the plan and apply
3. Change the resource and set `disable_password_authentication = True`
4. Run `terraform plan`
5. Run `terraform apply`

I think this should be trapped if it's not going to be honoured by Azure.

* #0000

**Comment by tombuildsstuff** [comment]
hey @dgsd-consulting 

Thanks for opening this issue.

We're superseding for the existing `azurerm_virtual_machine` resource in 2.0 (more details can be found in #2807) since the existing resources no longer adequately represent the Azure API's (and can't easily be brought up to date without breaking existing users).

Version 1.43 of the Azure Provider introduces an opt-in Beta for these new resources, which includes fixes for this issue in the new resources - more details [can be found in the Beta guide](https://www.terraform.io/docs/providers/azurerm/guides/2.0-beta.html). Unfortunately we have no plans to backport these changes to the existing `azurerm_virtual_machine` resource since they've been superseded in 2.0 - however this is fixed in the new [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources.

Since this bug is fixed in the new resources and is available in a Beta form I'm going to close this Github issue for the moment - but since this is in the 2.0 Milestone @hashibot will comment when this goes "GA" (which'll happen in the coming weeks) at which point this should be resolved for the moment - we'll also post an update in #2807 when that happens.

Thanks!
