### ISSUE TITLE
Changing provisionVMAgent should recreate windows vm

### ISSUE THREAD

**Issue by r0bnet** [terraform-providers/terraform-provider-azurerm#5447]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "app" {
  name                  = "${var.prefix}-app-vm"
  location              = var.location
  resource_group_name   = azurerm_resource_group.rg.name
  network_interface_ids = [azurerm_network_interface.nic.id]
  vm_size               = "Standard_D4s_v3"
  availability_set_id   = azurerm_availability_set.availability_set.id

  delete_os_disk_on_termination = true

  storage_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2019-Datacenter"
    version   = "latest"
  }

  storage_os_disk {
    name              = "${var.prefix}-app-os-disk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "StandardSSD_LRS"
  }

  os_profile {
    computer_name  = "${var.prefix}-app-vm"
    admin_username = "admin_user"
    admin_password = "mySup3r$ecr3t"
  }

  os_profile_windows_config {
    provision_vm_agent = true
  }
}
```

### Expected Behavior

Resource should be recreated since this property can't be changed.

### Actual Behavior

Error message is thrown:
```bash
Error: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'windowsConfiguration.provisionVMAgent' is not allowed." Target="windowsConfiguration.provisionVMAgent"
```

### Steps to Reproduce

1. `terraform apply` with `provision_vm_agent` set to false
2. `terraform apply` with `provision_vm_agent` set to true

**Comment by tombuildsstuff** [comment]
hi @r0bnet 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We recently opened #5550 which adds support for the new Virtual Machine resources - and I'm able to confirm that this is fixed in the new Virtual Machine resources - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine` resource.

In order to get feedback on these new resources we'll be launching support for these new resources as an opt-in Beta in an upcoming 1.x release of the Azure Provider and ultimately release these as "GA" in the upcoming 2.0 release. We'll post an update in #2807 when both the opt-in Beta (1.x) & GA (2.0) are available - as such I'd recommend subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
