### ISSUE TITLE
azurerm_sql_database : fails if server is in another resource group

### ISSUE THREAD

**Issue by hangar18rip** [terraform-providers/terraform-provider-azurerm#5448]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform: 0.12.19
azurerm: 0.1.40

### Affected Resource(s)
* azurerm_sql_database

### Terraform Configuration Files

```hcl
resource azurerm_sql_server shared_sql {
  name                = "myserver"
  resource_group_name = "serverresourcegroup"
  location            = "westeurope"

  version = "12.0"

  administrator_login          = "adminlogin"
  administrator_login_password = "adminpassword"
}

resource azurerm_sql_database mydb {
  name                = "mydb"
  resource_group_name = "dbresourcegroup"
  location            = "westeurope"
  server_name         = "myserver"

  edition = "Basic"
}
```

### Debug Output

Error: Error issuing create/update request for SQL Database "mydb" (Resource Group "dbresourcegroup", Server "myserver"): sql.DatabasesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ParentResourceNotFound" Message="Can not perform requested operation on nested resource. Parent resource 'myserver' not found."

### Expected Behavior

As Server and Database can be in distinct resource group, the provider should not be searching the server only in the resource group. Maybe the Server ID or its FQDN should be an option to specify the server

### Actual Behavior

The provider seems to search the server only the resource group where the database is located

### Steps to Reproduce

```terraform apply```

### References

* https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/sql/resource_arm_sql_database.go#L357

**Comment by NickMetz** [comment]
Hi @hangar18rip,

unfortunately it's not possible to create a PostgreSql Database in a different Resource Group than  Azure PostgreSql Server. From Azure prospective PostgreSql Database is not a dedicated resource and always depending on Azure PostgreSql Server and it's resource group. 

Of cause it's possible to pass in Server ID instead of resource group and server name. You may have seen such option on other resources. But behind the since terraform Create/Update function will parse this ID to there needs (serve name, resource group, etc.). So this will also not help to create a Postgresql Database in a different resource group than Postgresql Server.

More details can also be found here:
[Azure PostgreSQL API Spec](https://docs.microsoft.com/en-us/rest/api/postgresql/databases/createorupdate)
[Azure-GO-SDK - Postgresql Database Functions](https://github.com/Azure/azure-sdk-for-go/blob/master/services/postgresql/mgmt/2017-12-01/postgresql/databases.go)

**Comment by hangar18rip** [comment]
Hi @NickMetz ,
I am not talking about PostgreSQL. This issue is related to SQL Server
Regards

**Comment by NickMetz** [comment]
Hi @hangar18rip,

sorry your right, but the answer is still valid design in Azure is similar.

[Azure SQL Server - Databases API Spec](https://docs.microsoft.com/en-us/rest/api/sql/databases/createorupdate)
[Azure-GO-SDK - SQL Database Functions](https://github.com/Azure/azure-sdk-for-go/blob/master/services/sql/mgmt/2014-04-01/sql/databases.go)

**Comment by yupwei68** [comment]
Hi @hangar18rip , @NickMetz is right. We could not create database in a different resource group. You could try new database `azurerm_mssql_database`, which need only sql server id.

**Comment by hangar18rip** [comment]
Hi, @yupwei68. I will give it a try. I close the issue. Thanks
