### ISSUE TITLE
Support for Azure HPC Cache

### ISSUE THREAD

**Issue by tbugfinder** [terraform-providers/terraform-provider-azurerm#5504]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure released a new service `Azure HPC Cache` in Nov 2019. Please add this service to the implementation of the azurerm provider.
https://azure.microsoft.com/en-us/services/hpc-cache/

### New Resource(s)

* azurerm_hpc_cache

### Potential Terraform Configuration

```hcl
# N/A
```

### References

* https://azure.microsoft.com/en-us/services/hpc-cache/

**Comment by aqche** [comment]
I'd be interested in tackling this. Will keep you posted on how it goes.

**Comment by aqche** [comment]
So it turns out although it is GA, you need to [request access](https://docs.microsoft.com/en-us/azure/hpc-cache/hpc-cache-prereqs#azure-subscription) to be able to use Azure HPC Cache in your subscriptions. I have some code written but I'm unable to test until my request for access is approved. I'll open a draft PR with what I got so far so if anyone already has access to Azure HPC Cache and want to pick it up from there feel free. 

Heads up for project maintainers that you may want to request access to Azure HPC Cache for your subscriptions as well.

**Comment by aqche** [comment]
Got access to Azure HPC Cache in my subscription and finished getting the PR ready  👍

**Comment by magodo** [comment]
@aqche 
Do you have any plan to further support the storage target for hpc? If you have not started yet, then maybe I can help :smile:

**Comment by aqche** [comment]
@magodo sounds good to me, feel free to pick it up!
