### ISSUE TITLE
when creating a Redis resource the process stucks and never finishes

### ISSUE THREAD

**Issue by NoNameProvided** [terraform-providers/terraform-provider-azurerm#5527]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `terraform-provider-azurerm_v1.41.0_x4`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "~>1.41.0"
  subscription_id = var.subscription_id
  tenant_id       = var.tenant_id
}

resource "azurerm_resource_group" "root_rg" {
  name     = "my-redis-test-rg"
  location = "westeurope"
}

resource "azurerm_redis_cache" "central" {
  name                = "mytest-${var.environment}-redis"
  location            = azurerm_resource_group.root_rg.location
  resource_group_name = azurerm_resource_group.root_rg.name
  capacity            = 0
  family              = "C"
  sku_name            = "Basic"
  enable_non_ssl_port = true
  minimum_tls_version = "1.2"

  redis_configuration {
    enable_authentication = true
    maxmemory_policy      = "noeviction"
  }

  # There's a bug in the Redis API where the original storage connection string isn't being returned, 
  # which is being tracked in this issue: https://github.com/Azure/azure-rest-api-specs/issues/3037. 
  # In the interim you can use the ignore_changes attribute to ignore changes to this field.
  lifecycle {
    prevent_destroy = true
    ignore_changes  = [redis_configuration.0.rdb_storage_connection_string]
  }
}
```

### Debug Output

https://gist.githubusercontent.com/NoNameProvided/806aaf43f3d8cba9788f7eccf56761b1/raw/3824cba8a58e6f26a987e760208ea810db10221a/terraform-debug.log

(This is the raw link, as the normal one with syntax highlighting freezes slows down the browser)

### Panic Output

Terraform did not crash.

### Expected Behavior

The resource is created in a timely manner and Terraform continues to run the script.

### Actual Behavior

The resource is created under a minute in Azure (I can check it trough the portal, it's fully provisioned) but the Terraform script stucks at the "azurerm_redis_cache.central: Still creating... [x elapsed]" for up to an 15 minutes. (When I cancelled the script.) This is reproducible for me 100% of the time.

### Steps to Reproduce

Run the above provided script with `terraform apply --auto-approve`.

### Important Factoids

n/a

### References

#3015 - basically the same issue, but in that case it just took 10 minutes to create the redis resource
#5355 - basically the same, but closed by the reported as API error from Azure side?

**Comment by tombuildsstuff** [comment]
hi @NoNameProvided 

Thanks for opening this issue.

Taking a look at the debug log you've posted - it appears the Redis Cache is still in the process of being created (`"provisioningState":"Creating"`). There's two phases when creating most resources in Azure:

1) the initial upsert to create it
2) polling until it's actually finished

When the resource appears in the Azure Portal is dependent on the Resource Provider/API in question - but for most of them they appear during phrase 1 with a status of "creating" (as in this case); which we then need to poll until it's in a "successful" state so that the Redis Cache is ready to use.

From memory creating a Redis Cache in Azure takes somewhere from 15m-45m depending on the configuration being used - as such Terraform will continue to poll until the Redis Cache is fully available. Since this is a question rather than a bug in the Azure Provider here I'm going to close this issue for the moment - but you should be able to continue letting this poll until the Redis Cache has been fully provisioned at which point this should complete successfully.

Thanks!
