### ISSUE TITLE
Fails to delete data disk on disk count change.

### ISSUE THREAD

**Issue by lanrongwen** [terraform-providers/terraform-provider-azurerm#5545]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform Version 0.12.20
Provider Version 1.42.0

### Affected Resource(s)

* azurerm_virtual_machine
* storage_data_disk block in azurerm_virtual_machine

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine" "virtual_machine" {
...

  dynamic "storage_data_disk" {
    for_each = var.data_disks

    content {
      caching           = storage_data_disk.value.disk_cache
      create_option     = "Empty"
      disk_size_gb      = storage_data_disk.value.disk_size
      lun               = storage_data_disk.value.disk_lun
      managed_disk_type = storage_data_disk.value.disk_type
      name              = "${var.base_name}${count.index + 1}-datadisk${storage_data_disk.value.disk_lun}"
      # write_accelerator_enabled - (Optional) Specifies if Write Accelerator is enabled on the disk. This can only be enabled on Premium_LRS managed disks with no caching and M-Series VMs. Defaults to false.
    }
  }
}
```

### Expected Behavior

When using a dynamic block, it should let you add and remove disks based on the passed in parameters.

### Actual Behavior

Will let you add correctly.  When you reduce the count to remove a disk, it will remove it from the vm but will not delete the actual disk in the resource group.  Issue appears to be at this line, as it updates the VM config, but never calls the cleanup if the disk count shrinks. 
 https://github.com/terraform-providers/terraform-provider-azurerm/blob/fd6db944416b08d016794bbb12bced9380799ca0/azurerm/internal/services/compute/resource_arm_virtual_machine.go#L676

### Steps to Reproduce

1. Deploy a VM with data disks in a dynamic block.
1. Reduce the number or required data disks.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @lanrongwen 

Thanks for opening this issue.

As a part of the upcoming 2.0 version of the Azure Provider (detailed in #2807) we're currently working to introduce the replacement Virtual Machine resources.

In preparation for this a while back we introduced a new resource for attaching data disks to Virtual Machines - [the `azurerm_virtual_machine_data_disk_attachment` resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_data_disk_attachment.html) which (in the new resources) will be the only supported way to attach Data Disks to a Virtual Machine.  There's some additions coming to the `azurerm_virtual_machine_data_disk_attachment` in the next couple of releases too which will form part of the 2.0 release around disk resizing - as such this is our recommendation long-term.

As such rather than defining these inline within the existing `azurerm_virtual_machine` resource it should be possible to use this resource and the `azurerm_managed_disk` resource to attach data disk to the Virtual Machine and have it automatically add/destroy them as you scale the count - would you be able to take a look and see if that works for you?

Since this should be resolved by switching to the `azurerm_virtual_machine_data_disk_attachment` resource and the existing `azurerm_virtual_machine` resource is feature-frozen at this time - I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by lanrongwen** [comment]
That's cool, can you update the documentation https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html to indicate this?
