### ISSUE TITLE
Has anyone used Terraform to promote secondary region in case of Disaster recover in Azure

### ISSUE THREAD

**Issue by chetanchatrath** [terraform-providers/terraform-provider-azurerm#5567]
Has anyone used Terraform to promote secondary region in case of Disaster recover in Azure. I see there was a question related to this raised earlier Issue #971. So wanted to check if anyone has used Terraform for ASR
---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @chetanchatrath 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
