### ISSUE TITLE
Support for azurerm_data_box_job

### ISSUE THREAD

**Issue by neil-yechenwei** [terraform-providers/terraform-provider-azurerm#5770]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is a request here to support data box job, which lets you send terabytes of local data into Azure in a quick, inexpensive, and reliable way. Our team is working on the implementation.
Overview: https://docs.microsoft.com/en-us/azure/databox/data-box-overview
Rest api spec: https://github.com/Azure/azure-rest-api-specs/blob/master/specification/databox/resource-manager/Microsoft.DataBox/stable/2019-09-01/databox.json
PS: https://docs.microsoft.com/en-us/powershell/module/az.databox/new-azdataboxjob?view=azps-3.4.0

### Affected resource provider
Microsoft.DataBox

### New or Affected Resource(s)
* azurerm_data_box_job

### Potential Terraform Configuration
resource "azurerm_data_box_job" "test" {
  name                = "acctest-DataBox-Test"
  resource_group_name = "${azurerm_resource_group.test.name}"
  location            = "${azurerm_resource_group.test.location}"

  contact_details {
    contact_name = "DataBoxJobTester"
    emails = ["some.user@example.com"]
    phone_number = "+11234567891"
  }

  destination_account_details {
    data_destination_type = "StorageAccount"
    storage_account_id    = "${azurerm_storage_account.test.id}"
  }

  shipping_address {
    city    = "San Francisco"
    country = "US"
    postal_code = "94107"
    state_or_province = "CA"
    street_address_1 = "16 TOWNSEND ST"
  }

  sku_name = "DataBox"
}

**Comment by tombuildsstuff** [comment]
hi @neil-yechenwei 

Thanks for opening this issue.

Taking a look at Azure DataBox unfortunately it appears this isn't a service which makes sense in the Azure Provider. There's a couple of reasons for this:

1. This type of data migration is likely performed as one-off manual job by operators as required - rather than something likely to be provisioned repeatedly in an automated fashion
2. Since this box ships a physical box out to a given address, we're not going to be able to test this in an automated fashion (which is a requirement for supporting these resources) or if we do this is going to send large volumes of physical mail (which is unnecessary).

As such whilst I'd like to thank you for opening this issue, since unfortunately this service/resource doesn't make sense in Terraform I'm going to close this issue for the moment.

Thanks!
