### ISSUE TITLE
Output of templates can not be used after second apply

### ISSUE THREAD

**Issue by timbuchwaldt** [terraform-providers/terraform-provider-azurerm#578]
Redeploying this module fails with `* module.tenant-networking-dev.azurerm_template_deployment.it-connect: At column 52, line 1: map "azurerm_template_deployment.connect-setup.outputs" does not have any elements so cannot determine type. in:`

The module can be applied w/o problems when running without a known state.

### Terraform Version
Terraform v0.11.0
+ provider.azurerm v0.3.3

### Affected Resource(s)
- azurerm_template_deployment

### Terraform Configuration Files
```hcl
resource "azurerm_template_deployment" "connect-setup" {
  provider = "azurerm.customer"

  name                = "${var.name}-connect"
  resource_group_name = "networking"

  template_body = "${file("tenant-networking/tenant-network-template.json")}"
  parameters {
    remoteGatewayIP = "${var.it_ip}"
    azureVNetAddressPrefix = "${var.customer_ip_range}"
    # extends the /23 to the first /24
    subnetPrefix = "${cidrsubnet(var.customer_ip_range, 1, 0)}"
    # extends the /23 to the second /24
    gatewaySubnetPrefix = "${cidrsubnet(var.customer_ip_range, 1, 1)}"
  }
  deployment_mode = "Incremental"
  depends_on = ["azurerm_resource_group.customer-networking"]
}

resource "azurerm_template_deployment" "it-connect" {
  provider = "azurerm.it"
  name                = "it-${var.name}-connect"
  resource_group_name = "networking"
   template_body = "${file("tenant-networking/connection-template.json")}"
  parameters {
    sharedKey = "secretpsk"
    remoteGatewayIP = "${azurerm_template_deployment.connect-setup.outputs["gatewayIP"]}"
    connectionName = "${var.name}-connect"
    remoteIPRange = "${var.customer_ip_range}"
  }
  deployment_mode = "Incremental"
  depends_on = ["azurerm_template_deployment.connect-setup"]
 }
```

### Expected Behavior
It should work when applying multiple times

### Actual Behavior
It fails to reuse the output of the template

### Steps to Reproduce
1. `terraform apply`

CC
@sebastus @rcarun @harijayms @metacpp

**Comment by tombuildsstuff** [comment]
hey @timbuchwaldt 

> Redeploying this module fails with * module.tenant-networking-dev.azurerm_template_deployment.it-connect: At column 52, line 1: map "azurerm_template_deployment.connect-setup.outputs" does not have any elements so cannot determine type. in:

Just to ensure that I understand the steps needed to reproduce this - are you referring to creating the resource using Terraform 0.11 and then applying a secondary change using Terraform 0.11 - or upgrading from a previous version of Terraform (e.g. 0.10) and then applying a secondary change using Terraform 0.11?

In addition so that we can investigate this further would it be possible to display a full reproducible configuration for this (including the contents of `./tenant-networking/connection-template.json`)

In either case I'm wondering if this is to do with some recent changes to HCL/HIL - [which are detailed in the Terraform 0.11 upgrade guide](https://www.terraform.io/upgrade-guides/0-11.html#error-checking-for-output-values) - we should be able to tell further from the full configuration :)

Thanks!

**Comment by timbuchwaldt** [comment]
Hey @tombuildsstuff,
I apply with the same version of terraform, just updating the resources.
I'll try and export that stuff while not sharing all my work on monday :)
Doesn't seem like the 0.11 upgrade guide issue, the output I am talking about works on the first run, but maybe isn't saved in the state file (hence it works again after I delete the state)?

**Comment by timbuchwaldt** [comment]
I am trying to build a minimal case to reproduce this, sadly it doesn't seem to happen with the sample template I chose (I'd rather not publish the huge templates I built). The terraform.tfstate looks similar in regards to the output, nevertheless my internal repo reproducibly fails to apply with a terraform.tfstate present with this error:
```At column 52, line 1: map "azurerm_template_deployment.connect-setup.outputs" does not have any elements so cannot determine type. in: ${azurerm_template_deployment.connect-setup.outputs["gatewayIP"]}```

I will now try to make a terraform module out of my small sample, as my real world error also happens inside a module.

**Comment by pdf** [comment]
I'm guessing this may be something similar to #9858, unfortunately that was closed without being linked to the issues that supposedly exist to cover the root cause :confused:

**Comment by tombuildsstuff** [comment]
hey @pdf @timbuchwaldt 

Apologies for the delayed response here. Taking a quick look into this, I'm wondering if you still encounter this when attempting to access the output variables like so:

```
output "example" {
  value = "${lookup(azurerm_template_deployment.test.outputs, "example")}"
}
```

Would you be able to take a look and let me know if that solves your issue?

Thanks!

**Comment by schuyleroccm** [comment]
I'm having the same issue as the OP.  What I've witnessed is when the arm template is in incremental deploy mode and detects a modification, the output I'm using doesn't get created.  Delete the resource being deployed in arm, and viola, the output is there.

In my use case I'm creating a servicefabric cluster in arm (since there's not yet a native azurerm resource I could find) and then using the clusterendpoint from that as an output then input to the scaleset azurerm resource.

Delete every existing resource and deployment works fine - the output from the arm is captured and all is well.  It seems again to me to only happen on a modification run for the arm template deploy.

**Comment by tombuildsstuff** [comment]
@schuyleroccm out of interest, which syntax are you using to access these properties?

**Comment by tombuildsstuff** [comment]
@schuyleroccm thanks for that - do you still encounter this issue when using the following syntax:

```
output "clusterEndpoint" {
  value = "${lookup(azurerm_template_deployment.sf-arm.outputs, "clusterEndpoint")}"
}
```

**Comment by tombuildsstuff** [comment]
👋 

Just to let you know that since this is a configuration question rather than a bug in Terraform (and we've not heard back about [the original issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/578#issuecomment-371646405)) - I'm going to close this issue for the moment, but we'll continue to take a look into this.

Thanks!

**Comment by schuyleroccm** [comment]
@tombuildsstuff - so I'm using the output from the ARM deployment as a local variable.  The specific use case is I'm deploying a service fabric instance which uses a scale set.  Since there's not yet a service fabric resource in TF, I use an ARM template to deploy the SF bit.  However, the scale set resource requires the cluster endpoint  (created at the time of the ARM deploy) so it can register its instances with the SF cluster.

I'm not trying to use the output (from ARM) as an output (from TF) - just the ARM output as a local variable that then gets passed as a parameter to the scale set.

Here's the code where I use the cluster endpoint in creating an extension to the scale set:

```
extension {
    name                       = "ServiceFabricNodeVmExt-${local.vmNodeType0Name}"
    publisher                  = "Microsoft.Azure.ServiceFabric"
    type                       = "ServiceFabricNode"
    type_handler_version       = "1.0"
    auto_upgrade_minor_version = "true"

    settings = <<SETTINGS
        {
        "clusterEndpoint": "${azurerm_template_deployment.sf-arm.outputs["clusterEndpoint"]}",
        "nodeTypeRef": "${local.vmNodeType0Name}",
        "dataPath": "${local.nodeDataDrive}",
        "durabilityLevel": "${local.durabilityLevel0}",
        "nicPrefixOverride":"${local.subnet0cidr}",
        "certificate": {
            "thumbprint": "${local.certificateThumbprint}",
            "x509StoreName": "blah"
          }
        }
    SETTINGS

    protected_settings = <<PROTECTED_SETTINGS
      {
        "StorageAccountKey1": "${azurerm_storage_account.sf-support-log.primary_access_key}",
        "StorageAccountKey2": "${azurerm_storage_account.sf-support-log.secondary_access_key}"
      }
PROTECTED_SETTINGS
  }
```

**Comment by tombuildsstuff** [comment]
@schuyleroccm you should be able to use the same syntax within the `clusterEndpoint` property in the VM Extension e.g.

```
# ...
settings = <<SETTINGS
        {
        "clusterEndpoint": "${lookup(azurerm_template_deployment.sf-arm.outputs, "clusterEndpoint")}",
        "nodeTypeRef": "${local.vmNodeType0Name}",
# ...
```

which I believe should solve this for you?

Thanks!

**Comment by schuyleroccm** [comment]
@tombuildsstuff Interesting!  I'll try that - but just out of curiosity, why lookup vs interpolation - how does that change the issue?

**Comment by tombuildsstuff** [comment]
@schuyleroccm the way the graph is loaded in 0.11 has changed such that additional information is needed upfront which isn’t available when using the .property method (since the values don’t exist at that point, hence the error). Using the approach allows Terraform Core to understand that the values are a dynamic output value from the Template Deployment resource (and such doesn’t evaluate this expression until it’s needed. Hope that helps :)

**Comment by schuyleroccm** [comment]
@tombuildsstuff Fascinating and great explanation - thanks!

**Comment by alastairtree** [comment]
> Apologies for the delayed response here. Taking a quick look into this, I'm wondering if you still encounter this when attempting to access the output variables like so:
> 
> ```
> output "example" {
>   value = "${lookup(azurerm_template_deployment.test.outputs, "example")}"
> }
> ```

@tombuildsstuff if the outputs for template deploys has changed to using lookup could you update the docs please? https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html

**Comment by timja** [comment]
Hi @tombuildsstuff 

We just tried switching over to the new format, but it still failed:
https://github.com/hmcts/cnp-module-app-service-plan/pull/13
```
* module.asp.output.aspResourceID: lookup: lookup failed to find 'aspResourceID' in:

${lookup(azurerm_template_deployment.app_service_plan.outputs, "aspResourceID")}
```

In this case the arm template was already outputting it but the terraform module wasn't passing it on by doing a terraform output, when someone added the output then old builds started breaking on terraform plan

`value = "${azurerm_template_deployment.app_service_plan.outputs["aspResourceID"]}"`  was added to pass on the aspResourceId, but even after changing it to lookup the error appears to be the same

```
+ terraform -v
Terraform v0.11.7
```

Any ideas?

**Comment by timja** [comment]
Removing the output from the arm template and terraform, running apply once, and then re-adding it seems to have fixed it
