### ISSUE TITLE
AzureRM Authentication with Service Principal

### ISSUE THREAD

**Issue by ryanps1** [terraform-providers/terraform-provider-azurerm#5780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.9
AzureRM 1.38.0 (and later)

### Affected Resource(s)

* `AzureRM Authentication`

### Terraform Configuration Files

```hcl
provider "azurerm" { 
  version = "=1.38.0"
}
terraform {
 required_version = ">= 0.12" 
 backend "azurerm" {
  storage_account_name = "xxxxx"
  container_name       = "xxxxx"
  key                  = "xxxxx"
  access_key           = "xxxxx"
 }
}
```

### Debug Output

```hcl
[ERROR] <root>: eval: *terraform.EvalConfigProvider, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc00010fdd0), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:400, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc00010fd40)}
[ERROR] <root>: eval: *terraform.EvalSequence, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc00010fdd0), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:400, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc00010fd40)}
[ERROR] <root>: eval: *terraform.EvalOpFilter, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc00010fdd0), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:400, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc00010fd40)}
[ERROR] <root>: eval: *terraform.EvalSequence, err: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc00010fdd0), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:400, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc00010fd40)}
[TRACE] [walkPlan] Exiting eval tree: provider.azurerm
```
### Expected Behavior

The plan should complete successfully.

### Actual Behavior

The plan fails and reports the below error message:

Error: Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*azure.RequestError)(0xc00010fdd0), PackageType:"graphrbac.ServicePrincipalsClient", Method:"List", StatusCode:400, Message:"Failure responding to request", ServiceError:[]uint8(nil), Response:(*http.Response)(0xc00010fd40)}

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Authentication is being handled through the use of environment variables as shown below:

```hcl
$env:ARM_CLIENT_ID="XXX"
$env:TF_LOG="TRACE"
$env:ARM_CLIENT_SECRET="XXX"
$env:ARM_SUBSCRIPTION_ID="XXX"
$env:ARM_TENANT_ID="XXX"
terraform init
terraform plan -out="$(tfplanname).plan-$(Build.BuildNumber)"
```
This occurs in AzureRM 1.38.0 onwards, but as soon as I set AzureRM 1.37.0 or prior versions this works as expected.

### Other

Happy to share further logs/answer any queries regarding this issue.

**Comment by tombuildsstuff** [comment]
hi @ryanps1 

Thanks for opening this issue.

Upon startup the Azure Provider retrieves various information needed (e.g. an access token, the object id being used) from the Azure API's - what you're seeing here (and the change introduced in version 1.38) is the Azure Provider being unable to retrieve the Object ID for the current user which we now cache on launch, rather than retrieving during an apply (so that we can highlight a missing permission ahead of time, rather than erroring out half way through an apply).

This information is obtained from the Azure Graph API (located at `https://graph.windows.net`) - as such the Service Principal being used must have access to this, which I believe is the issue here - can you take a look and see if granting the Service Principal being used read-only access to this API works? From our side we make a call to `https://graph.windows.net/{tenantId}/servicePrincipals` to retrieve this information.

Unfortunately this error message being returned here isn't as clear as it should be - and I've [opened this issue](https://github.com/hashicorp/go-azure-helpers/issues/48) on the github.com/hashicorp/go-azure-helpers repository to update this error message with more helpful details going forward.

Since granting this Service Principal permissions to the Graph API should resolve this I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by cholm321** [comment]
I experience the same message in an Enterprise company exercising principles of least privileged access. On the other hand I can run the exact same workload on my own private Azure Subscription (without strict security in place).

In the Enterprise, the Service Principal has API permission Directory.Read.All (Application) on the Azure AD Graph API. 
But that is apparently not enough. 

Could you add a bit more detailed information than  

> as such the Service Principal being used must have access to this [graphapi]
 
As a work around (not ideal at all), I have returned to azurem provider v. 1.37, with environment variable  ARM_SKIP_PROVIDER_REGISTRATION = true  (which is needed to avoid a lot of other errors)

**Comment by danrb1978** [comment]
Hi @cholm321 , @tombuildsstuff , @ryanps1,

Thanks for this information, 

While researching this, I learned a condition that can cause this which was unexpected.

I am using the ARM_CLIENT_ID to set my service principle ID. Previous versions of azurerm allowed this to be a "friendly name", however now must be set to the appId/GUID for the service principal.

This misconfiguration causes the Graph API call to fail for these provider versions.

Thanks for the leads!
