### ISSUE TITLE
How to change VM state start/restart/deallocate

### ISSUE THREAD

**Issue by vijayraje23** [terraform-providers/terraform-provider-azurerm#5782]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

[root@localhost terraform]# terraform -v
Terraform v0.12.20
+ provider.azurerm v1.44.0

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @vijayraje23 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

The Azure Provider itself intentionally doesn't expose the Stop/Start/Deallocate states since this is outside of Terraform's sphere of influence - however the upcoming `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources will automatically stop/start the machine as required during an update and handle turning them on/off if required. Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment.

Thanks!
