### ISSUE TITLE
azurerm_sql_elasticpool vcores support

### ISSUE THREAD

**Issue by papagalu** [terraform-providers/terraform-provider-azurerm#5783]
does anyone plan to introduce the vcore configuration in the azurerm_sql_elasticpool resource?

i already saw an opened issue: [#1745](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1745) with a merged PR [2071](https://github.com/terraform-providers/terraform-provider-azurerm/pull/2071).

but if i search the codebase now, i can't find those changes, nor available documentation.

What is the plan for this resource?

**Comment by tombuildsstuff** [comment]
hi @papagalu 

Thanks for opening this issue.

Support for [the vCores pricing model for Elastic Pool can be found in this resource](https://www.terraform.io/docs/providers/azurerm/r/mssql_elasticpool.html) - can you take a look and see if that works for you? Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
