### ISSUE TITLE
import azurerm_app_service_plan error when copying url from azure website

### ISSUE THREAD

**Issue by Pmeholm** [terraform-providers/terraform-provider-azurerm#5787]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.20
+ provider.azurerm v1.44.0

### Affected Resource(s)

* `azurerm_app_service_plan`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior
the resource should be imported successfully

### Actual Behavior
azurerm_app_service_plan.doc: Importing from ID "/subscriptions/
GGGG/resourceGroups/xxx/providers/Microsoft.Web/serverFarms/yyy"...

Error: Error parsing Resource ID "/subscriptions/
GGGG/resourceGroups/xxx/providers/Microsoft.Web/serverFarms/yyy": ID was missing the `serverfarms` element

### Steps to Reproduce

1. create empty resource named doc
1. copy url from website
2. terraform import azurerm_app_service_plan.doc "URL copied from Azure website"

### Important Factoids
this happens becuase terraform expects "serverfarms" while azure uses "serverFarms" in the resourceID

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Pmeholm 

Thanks for opening this issue.

As you've mentioned this is due to the Resource ID for this App Service Plan containing `serverFarms` rather than `serverfarms` (which is what we're expecting/the Azure API defines) - as such you should be able to fix this by updating the segment in the URL from `serverFarms` to `serverfarms`. Whilst in some cases some of the Azure API's treat Resource ID's as case-sensitive this isn't the case for all API's and thus we have to treat them as case-sensitive due to bugs in the API behaviour when the casing is incorrect.

To try and provide a better user experience here & ensure these ID's are in the correct case we both [have examples of how to import these in the documentation](https://www.terraform.io/docs/providers/azurerm/r/app_service_plan.html#import) and we're working through adding validation during `terraform import` (and for any references) to call out the specific element that's missing where possible - which is what you're seeing here.

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment; however as mentioned above it should be possible to fix this by updating the ID from `serverFarms` to `serverfarms` - but please let us know if updating this doesn't work and we'll take another look.

Thanks!
