### ISSUE TITLE
 https://github.com/terraform-providers/terraform-provider-azurerm/issues/5266 still having the same behavior in 1.44.0

### ISSUE THREAD

**Issue by celloist** [terraform-providers/terraform-provider-azurerm#5802]
The ticket  https://github.com/terraform-providers/terraform-provider-azurerm/issues/5266 was closed but i had move to azurerm 1.36.1 to test locally. Version 1.44.0 still gives the same error.
To reproduce test locally with terraform plan.
```
Error: Error building account: Error getting authenticated object ID: Error parsing json result from the Azure CLI: Error waiting for the Azure CLI: exit status 1

  on tacx-backend-central-authentication.tf line 2, in provider "azurerm":
   2: provider "azurerm" {
```

**Comment by tombuildsstuff** [comment]
hi @celloist 

Thanks for opening this issue.

Upon startup the Azure Provider retrieves various information needed (e.g. an access token, the object id being used) from the Azure API's - what you're seeing here (and the change introduced in version 1.38) is the Azure Provider being unable to retrieve the Object ID for the current user which we now cache on launch, rather than retrieving during an apply (so that we can highlight a missing permission ahead of time, rather than erroring out half way through an apply).

This information is obtained from the Azure CLI which uses the Azure Graph API (located at `https://graph.windows.net`) - as such the User being used must have access to this, which I believe is the issue here. From our side that involves shelling out to `az ad signed-in-user show` - as such can you confirm that comes back with a JSON response? If not can you take a look and see if granting the user being used read-only access to this API works?

Since this is a question regarding permissions rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work and we'll take another look.

Thanks!

**Comment by celloist** [comment]
Thanks for clarification Tom!
