### ISSUE TITLE
Change Provision VM Agent default to true

### ISSUE THREAD

**Issue by RyanLWilliams** [terraform-providers/terraform-provider-azurerm#5861]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When deploying Windows Virtual Machines change the default behaviour of Provision VM Agent to "true". Provision VM agent is done by default from the Azure portal and is critical to allow for other numerous other Azure functions

### New or Affected Resource(s)

* azurerm_virtual_machine

**Comment by tombuildsstuff** [comment]
hi @RyanLWilliams 

Thanks for opening this issue.

In version 2.0 of the Azure Provider the existing `azurerm_virtual_machine` resource has been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources.

As these new resources are now generally available, to avoid introducing unexpected (breaking behavioural) changes to existing users we're no longer adding new making changes to the existing `azurerm_virtual_machine` (and `azurerm_virtual_machine_scale_set` resources) - instead we recommend checking out the new resources instead, which have updated this value so that this is now on by default.

Since this should be resolved by switching to the new `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources I'm going to close this issue for the moment - however you can enable this behaviour on the existing `azurerm_virtual_machine` resource by setting the `provision_vm_agent` flag within the `os_profile_windows_config` block to work around this in the interim if you're not able to upgrade to the new resources yet.

Thanks!
