### ISSUE TITLE
Azure Data factory linked services does not support all databases like oracle etc.

### ISSUE THREAD

**Issue by vinodsugur** [terraform-providers/terraform-provider-azurerm#5912]
The resource for linked service are very specific to source/target databases files. I see following linked services:
azurerm_data_factory_linked_service_mysql
azurerm_data_factory_linked_service_postgresql
azurerm_data_factory_linked_service_sql_server

The linked service resource name should not be tied to database otherwise this list will go on. I would suggest following resource name "azurerm_data_factory_linked_service", and all attributes should be part of connection string including the database name or any other source/target type.

Please suggest on the future plan on the linked services and its release.

**Comment by tombuildsstuff** [comment]
hi @vinodsugur 

Thanks for opening this issue.

Since there's a large number of these resources but some are more popular than others we've opted to add support for Data Factory Linked Services as they're requested/based on demand.

If you're looking for the Azure Provider to support additional Linked Services please open a new Feature Request for each of the Linked Services containing some details about what you're looking for (the feature request template contains the data we need) and then someone should be able to take a look at this at some point; however since this is a question rather than bug in the Azure Provider I'm going to close this issue for the moment.

Thanks!
