### ISSUE TITLE
Azure Keyvault acces denied when authenticating using SP

### ISSUE THREAD

**Issue by Chams91** [terraform-providers/terraform-provider-azurerm#5937]
I am using a Service Principle in order to authenticate with terraform in my CI pipeline.. 
i followed the steps listed in the official doc, therefore my provider looks like this.. 
`
```terraform
provider "azurerm" {
  subscription_id = var.ARM_SUBSCRIPTION_ID
  tenant_id       = var.ARM_TENANT_ID
  version         = "= 1.44"
  client_id       = "+++++++"
  client_secret   = "**********"
  skip_provider_registration = true
}
````

However with each terraform apply i get the following error : 
`Error: Error making Read request on Azure KeyVault Secret *******: keyvault.BaseClient#GetSecret: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="Forbidden" Message="Access denied. Caller was not found on any access policy.\r\nCaller: appid=############1;oid=##############;numgroups=0;iss=https://sts.windows.net/###################/\r\nVault: ###########=westeurope" InnerError={"code":"AccessDenied"}
`.. and so many oher similar errors regarding similar secrets in keyvault. Can anyone assist regarding this?

**Comment by tombuildsstuff** [comment]
hi @Chams91 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
