### ISSUE TITLE
network_interface in azurerm_linux_virtual_machine_scale_set

### ISSUE THREAD

**Issue by ShreyasNBS** [terraform-providers/terraform-provider-azurerm#6001]
Hi,

First of all, thanks for pushing out the  amazing provider upgrade.
Been reading through upgrade guide to azurerm 2.0 provider and I have a few questions:

1. What is the difference between network_interface block on azurerm_linux_virtual_machine_scale_set and azurerm_network_interface resource? There seems to be a lot of overlap between them. Can we skip creation of azurerm_network_interface and specify everything in network_interface block? If that is the case, then how do I specify private_ip_address_allocation to Dynamic in ip_configuration block for azurerm_linux_virtual_machine_scale_set?

2. load_balancer_backend_address_pool_ids and load_balancer_inbound_nat_rules_ids are going to be deprecated in favour of their equivalent association resources. However azurerm_network_interface_nat_rule_association resource does not seem to cater for "nat pool ids". Is my understanding correct, and if yes, how do I replace load_balancer_inbound_nat_rules_ids with an equivalent association block for nat pool id?

3. azurerm_linux_virtual_machine_scale_set seems to have a new public_ip_address block. Again this seems to overlap with azurerm_public_ip_address resource. Which one should be used?

I might have missed it, but it might be worth clarifying this in the docs. If I am wrong can you please point me the section in docs where the "overlap" is explained?

Lastly,

Is there an ETA for fixing the soource_image_id not working with shared image gallery paths?

Thanks,
Shreyas

**Comment by ShreyasNBS** [comment]
Any updates please?

**Comment by tombuildsstuff** [comment]
hi @ShreyasNBS 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
