### ISSUE TITLE
Provider alias causes "features": required field is not set

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#6006]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.21
+ provider.azuread v0.7.0
+ provider.azurerm v2.0.0
```

### Terraform Configuration Files

```
provider "azurerm" { 
  alias           = "rm"
  features {}
}

resource "azurerm_resource_group" "name" {
  name = "testa"
  location = "East US"
}

```

### Debug Output

```
Error: "features": required field is not set
```

### Expected Behavior

```
Terraform will perform the following actions:

  # azurerm_resource_group.name will be created
  + resource "azurerm_resource_group" "name" {
      + id       = (known after apply)
      + location = "eastus"
      + name     = "testa"
    }

Plan: 1 to add, 0 to change, 0 to destroy.
```

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`

**Comment by WodansSon** [comment]
@rohrerb thanks for opening this issue, and it is an interesting case. The way I see it this would be "by design" as a `feature` block is now required post 2.0 and since the `provider` block has been aliased and is not referenced in any `resource` blocks, which would in effect nullify the declaration of the aliased `provider` block.

I believe your configuration file would work as expected if you did one of the following actions below:

* remove the `alias` from the existing `provider` block, which would cause it to be associated with all of the `resource` blocks in the configuration file.
* add another `provider` block without an `alias`, which would cause it to be associated with all of the `resource` blocks in the configuration file that have not been associated to the aliased `provider` block.
* add the `alias` from the `provider` block to your `resource` block.

**Comment by rohrerb** [comment]
Makes Sense.  Thanks for clarification.
