### ISSUE TITLE
Importing module resources fails to initialize AzureRM SDK

### ISSUE THREAD

**Issue by andreireinus** [terraform-providers/terraform-provider-azurerm#6010]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request

### Terraform (and AzureRM Provider) Version

* Terraform Core version: v0.12.20
* AzureRM Provider version: v2.0.0

#### main.tf
```hcl
variable "subscription_id" {}

provider "azurerm" {
  subscription_id = var.subscription_id
  version = "=2.0"

  features {}
}

module "rgmod" {
  source = "./rgmod"

  subscription_id = var.subscription_id
}
```

#### ./rgmod/main.tf
```hcl
variable "subscription_id" {}

provider "azurerm" {
  subscription_id = var.subscription_id
  version = "=2.0"

  features {}
}

resource "azurerm_resource_group" "group" {
  name = "test-group"
  location = "West Europe"
}
```

### Description / Feedback

When importing already existing resource to the managed state using the command
```bash
> terraform import module.rgmod.azurerm_resource_group.group /subscriptions/00000000-0000-0000-0000-00000000000/resourceGroups/test-group

Error: Error building AzureRM Client: 1 error occurred:
        * A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.



  on rgmod\main.tf line 5, in provider "azurerm":
   5: provider "azurerm" {
```

When I add the default value to module subscription_id then the import is successful. I use this pattern of multiple azurerm providers due to the need to read from another subscription.

**Comment by tombuildsstuff** [comment]
hi @andreireinus 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with Terraform Core rather than one specific to the Azure Provider, since it appears that Terraform Core isn't correctly initializing a nested provider when importing to a module.

Whilst I can close and re-open this issue on that repository if I do so unfortunately that'd mean you're not fully subscribed to the issue - as such I'm going to close this issue for the moment and would you mind re-opening this issue on [the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone should be able to take a look (which'll mean you're fully subscribed to the issue)?

Thanks!
