### ISSUE TITLE
Support for data source azurerm_user_assigned_identity by other identifiers

### ISSUE THREAD

**Issue by mbrancato** [terraform-providers/terraform-provider-azurerm#6012]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

It would be useful if the data source for `azurerm_user_assigned_identity` could support using a resource ID, object ID, or other. The data source for `azuread_service_principal` supports a number of invocations.

The example use-case here is needing to create the identity before using it in a data source. I'm using the data source in a module, and the only way to pass this in is via the `name` and `resource_group` fields. These are not determined after creation, so if creating a `azurerm_user_assigned_identity` resource and passing the `name` into a module where a data source for `azurerm_user_assigned_identity` is used, it creates a race condition. The `name` is known so there is no dependency on creating the `azurerm_user_assigned_identity` resource before passing the `name` to the module.

When using this in a virtual machine or scale set, this results in an error like the following:

```
  85:     identity_ids = [data.azurerm_user_assigned_identity.consul.id]

Null values are not allowed for this attribute value.
```

### New or Affected Resource(s)

* azurerm_user_assigned_identity

### Potential Terraform Configuration

```hcl
data "azurerm_user_assigned_identity" "consul" {
  id                  = azurerm_user_assigned_identity.consul.id
  resource_group_name = data.azurerm_resource_group.consul.name
}

```

**Comment by tombuildsstuff** [comment]
👋 

Taking a look through here this appears to be a workaround for an issue in Terraform Core - as such whilst we could seek to fix this Core dependency bug here, ultimately this needs to be fixed within Terraform Core, at which point this fixed for all Data Sources. I believe this should be fixed with the latest changes in Terraform Core v0.14, however if your still seeing this using the latest version of Terraform Core (and the Azure Provider) - then [please open a new issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone from the Terraform Core team should be able to take a look.

Thanks!
