### ISSUE TITLE
azurerm_advanced_threat_protection support for Azure Database for PostgreSQL not working

### ISSUE THREAD

**Issue by s-jepsen** [terraform-providers/terraform-provider-azurerm#6018]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.21
+ provider.azurerm v2.0.0

### Affected Resource(s)

- azurerm_advanced_threat_protection
- azurerm_postgresql_server

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Advanced Threat monitoring for postgresql resource enabled.

### Actual Behavior

`security.AdvancedThreatProtectionClient#Create: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="Not Supported" Message="Atp settings are not supported on resources of type servers"`

### Steps to Reproduce

1. setup postgres-resource and apply ATP.

`
resource "azurerm_resource_group" "example" {
  name     = "api-rg-pro"
  location = "West Europe"
}

resource "azurerm_postgresql_server" "example" {
  name                = "postgresql-server-1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  sku_name = "B_Gen5_2"

  storage_profile {
    storage_mb            = 5120
    backup_retention_days = 7
    geo_redundant_backup  = "Disabled"
    auto_grow             = "Enabled"
  }

  administrator_login          = "psqladminun"
  administrator_login_password = "H@Sh1CoR3!"
  version                      = "9.5"
  ssl_enforcement              = "Enabled"
}

resource "azurerm_advanced_threat_protection" "atp" {
  enabled                  = true
  target_resource_id = azurerm_postgresql_server.example.id
}`

2. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @s-jepsen 

Thanks for opening this issue.

This error message is being returned from the Azure API: `Atp settings are not supported on resources of type servers` as such it appears that Advanced Protection Settings cannot be configured for PostgreSQL Servers at this time, instead this may be available on a nested item (such as a Database) - however this is limited by the service itself.

Since this is a limitation of the Azure API rather than something specific to Terraform I'm going to close this issue for the moment, but you should be able to confirm which of the PostgreSQL resources support Advanced Threat Protection via the Azure documentation for that service.

Thanks!
