### ISSUE TITLE
azurerm_key_vault_access_policy resource doesn't use service principal correctly

### ISSUE THREAD

**Issue by KristapsT** [terraform-providers/terraform-provider-azurerm#6021]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.21
+ provider.azurerm v2.0.0

Tested and got the same behaviour with azurerm version 1.44.0 too
### Affected Resource(s)

* azurerm_key_vault
* azurerm_key_vault_access_policy

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.0.0"
  features {}
}

data "azurerm_resource_group" "existing_rg" {
  name = "existing_rg"
}

resource "azurerm_key_vault" "keyvault" {
  name                        = "keyvault-name"
  location                    = data.azurerm_resource_group.existing_rg.location
  resource_group_name         = data.azurerm_resource_group.existing_rg.name

  tenant_id                   = "<redacted-UUID>"

  sku_name = "standard"
}

resource "azurerm_key_vault_access_policy" "keyvault_access_policy" {
  key_vault_id = azurerm_key_vault.keyvault.id

  object_id = "<redacted-UUID>"
  tenant_id = "<redacted-UUID>"

  secret_permissions = [
    "get"
  ]
}

```

### Expected Behavior

KeyVault with name keyvault-name created and access policy where an application with the redacted object ID has get permission for secrets in the KeyVault, through Azure portal access to KeyVault should look like so:
![Screenshot 2020-03-06 at 15 43 30](https://user-images.githubusercontent.com/25103540/76093464-4a69dc80-5fc1-11ea-9083-9af499c99445.png)

### Actual Behavior

KeyVault gets created as expected, but the access policy assigned looks like this:
![Screenshot 2020-03-06 at 15 36 38](https://user-images.githubusercontent.com/25103540/76092883-72a50b80-5fc0-11ea-9ea3-0e0079e0d1ca.png)
Interesting that the actual name is of the **Unknown** entity is set as it should - comes from the Application whose object ID is in the azurerm_key_vault_access_policy, but nevertheless, the service principal doesn't get the access to KeyVault 

I am using the marked values from the screenshot as tenant_id and object_id in the already existing Service Principal:
![Screenshot 2020-03-06 at 15 48 56](https://user-images.githubusercontent.com/25103540/76093988-2ce94280-5fc2-11ea-8a51-a97cfba8b2a9.png)

### Steps to Reproduce

1. `terraform apply`

**Comment by epomatti** [comment]
Not sure if is related by for me it appears as "Compound Identity"

![image](https://user-images.githubusercontent.com/6530769/85159834-5efe7780-b234-11ea-9b96-af7fe6d378ce.png)

**Comment by exmnewellwf** [comment]
Ran into the same issue with access policy being set to "COMPOUND IDENTITY" instead of "APPLICATION" as I expected, when specifying application_id. Through trial and error I found that setting only the object_id to your app's SP results in "APPLICATION" and setting both object_id and application_id results in "COMPOUND IDENTITY". Example...

Assuming:
"azuread_application.exampleapp" is my Azure AD Application
"azuread_service_principal.examplesp" is my app service principal for exampleapp

Creates an "APPLICATION" access policy:
```
resource "azurerm_key_vault_access_policy" "keyvault_access_policy" {
  key_vault_id = azurerm_key_vault.keyvault.id

  object_id       = azuread_service_principal.examplesp.object_id 

  secret_permissions = [
    "get"
  ]
}
```

Creates an "COMPOUND IDENTITY" access policy:
```
resource "azurerm_key_vault_access_policy" "keyvault_access_policy" {
  key_vault_id = azurerm_key_vault.keyvault.id

  object_id       = azuread_service_principal.examplesp.object_id 
  application_id  = azuread_application.exampleapp.application_id

  secret_permissions = [
    "get"
  ]
}
```

**Comment by TheKangaroo** [comment]
I came across this same behaviour.
After some testing I found out, that I specified the Object ID of App Registration instead of the Object ID of the Enterprise Application. 
Also note, that you do not want to specify the application_id. Details about this in the docs:
https://docs.microsoft.com/en-us/azure/key-vault/general/secure-your-key-vault#key-vault-authentication-options

If you specify object_id and application_id you get a compound identity permission like @epomatti showed above. This is correct behaviour according to the docs.

**Comment by tombuildsstuff** [comment]
hi @KristapsT 

Thanks for opening this issue.

Taking a look through here this appears to be a configuration question rather than bug in the Azure Provider - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
