### ISSUE TITLE
Power off VM before de-allocation

### ISSUE THREAD

**Issue by gcormier** [terraform-providers/terraform-provider-azurerm#6022]
This is a followup to #4920 which documents much of the use case (but is now locked).

In v2 of the provider, how do we tell terraform to power-off a VM before de-allocating it? This would eliminate paying for the resource while Azure takes 10-30 minutes to de-allocate the VM.

I've looked at the parameters in https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html but can't find anything.

**Comment by tombuildsstuff** [comment]
hi @gcormier 

Thanks for opening this issue.

Both the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources now [shut-down the Virtual Machine prior to deleting it](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/compute/linux_virtual_machine_resource.go#L922-L942). As such this functionality is enabled by default and doesn't need configuring - if we were to make this behaviour configurable [we'd look to add it to the `features` block within the provider block](https://www.terraform.io/docs/providers/azurerm/index.html#features-2) - but for now this isn't configurable and should work by default. Can you take a look and see if that works for you?

Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
