### ISSUE TITLE
OperationPreempted error with azurerm_virtual_machine_extension when using an availability set

### ISSUE THREAD

**Issue by ssemyan** [terraform-providers/terraform-provider-azurerm#6025]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.21
provider.azurerm v2.0.0

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
resource "azurerm_virtual_machine_extension" "master-1-ext" {
    name                 = "${var.master_1_hostname}-ext"
    virtual_machine_id   = azurerm_linux_virtual_machine.master-1.id
    publisher            = "Microsoft.Azure.Extensions"
    type                 = "CustomScript"
    type_handler_version = "2.1"
    auto_upgrade_minor_version = "false"

    protected_settings = <<PROT
    {
        "script": "${base64encode(file(var.userdata_master1))}"
    }
    PROT
}
```
Rest of script is here: https://gist.github.com/ssemyan/2feb63899fdcc2ca3f75d80566f39b25 

### Debug Output

https://gist.github.com/ssemyan/020f46c25399dc75eefc0233cc5644bf

### Panic Output
NA

### Expected Behavior
Expect that the VMs and their extensions would be created successfully. 

### Actual Behavior
Error: Code="OperationPreempted" Message="Operation execution has been preempted by a more recent operation." on main.tf line 102, in resource "azurerm_virtual_machine_extension" "master-1-ext": 102: resource "azurerm_virtual_machine_extension" "master-1-ext" //Unknown exception - creating Master from terraform

### Steps to Reproduce

1. `terraform apply`

### Important Factoids
The VMs are being created in an availability set and this may affect how extension modification works. 

### References

This may be related to this issue: https://github.com/Azure/azure-sdk-for-python/issues/5167 

> The behavior above occurs when operations are being executed on a VM which end up being serialized into the underlying azure hardware controllers. In this example, are there other operations that are being executed against the VM being created or, if the VM being created is in an AvailabilitySet, are other VMs in the same AvailabilitySet being modified?
If other changes are being made after making the request to create a VM, then you do need to retry the VM create action or you can wait until the VM is created before making a change on related VMs.

**Comment by manya0393** [comment]
Hello Team

I am trying to create the VMs with the extensions of log analytics and diagnostic settings:-

I am getting the error on extension creation-
**Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

  on ..\TerraformModules\VirtualMachine\main.tf line 275, in resource "azurerm_virtual_machine_extension" "log_analytics":       
 275: resource "azurerm_virtual_machine_extension" "log_analytics" {

Error: Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

  on ..\TerraformModules\VirtualMachine\main.tf line 248, in resource "azurerm_virtual_machine_extension" "storage":
 248: resource "azurerm_virtual_machine_extension" "storage" {**


Then i tried to add the timeout for 2hrs. Log analytics extension got executed after 95mins but storage extension didn’t get executed and still throws error pasted below

**Error: Code="VMExtensionProvisioningTimeout" Message="Provisioning of VM extension storage-diagnostics has timed out. Extension provisioning has taken too long to complete. The extension did not report a message. More information on troubleshooting is available at https://aka.ms/VMExtensionLinuxDiagnosticsTroubleshoot"

  on ..\TerraformModules\VirtualMachine\main.tf line 248, in resource "azurerm_virtual_machine_extension" "storage":
248: resource "azurerm_virtual_machine_extension" "storage" {**

Can anyone help me on on this?

**Comment by gianlucagravina** [comment]
same here, while creating a vm with extensions. is there a workaround ?

**Comment by Zenocolo** [comment]
I do have the same issue, but only if I create my linux with the azurerm_linux_virtual_machine object, same VM extension works fine when using azurerm_virtual_machine...

**Comment by Zenocolo** [comment]
Forget my previous comment, same happened with azurerm_virtual_machine object, the difference I noticed is that extension works for Ubuntu but not of RHEL. Same happens when I deploy it manually on RHEL over portal, extension installation seems to be successful but hast some errors when you look closer. In short, I think its an issue on Azure and not terraform.

**Comment by tombuildsstuff** [comment]
@manya0393 @Zenocolo @gianlucagravina unfortunately these are unrelated to the original issue - since VM Extensions are generic (and fail in different ways, depending on the VM Extension being used) - unfortunately we're unable to offer guidance for how to use these extensions. Instead I'd recommend filing a bug on the repository for the Azure VM Extension in question or reaching out to Microsoft Support who should be able to provide more granular information here.

**Comment by mikeclearbank** [comment]
hitting the same issue

**Comment by tombuildsstuff** [comment]
👋 

Apologies for the delayed response here!

Taking a look through here ultimately this is more of an issue within the Azure API rather than something specific to the Azure Provider - as such [I'd recommend opening an issue on the Azure API Specs repository](https://github.com/Azure/azure-rest-api-specs) where someone from the API team should be able to look into fixing this API issue.

Thanks!
