### ISSUE TITLE
Azure RM 2.0 - remove/drop required features{} block

### ISSUE THREAD

**Issue by tbugfinder** [terraform-providers/terraform-provider-azurerm#6027]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'm wondering about the now required features{} block (https://www.terraform.io/docs/providers/azurerm/index.html#features) within the provider definition. In our setup this is sort of conflicting with module development and usage. Creating self-tested modules might end up in provider definitions within the modules themselves. As per article https://www.terraform.io/docs/configuration/modules.html#providers-within-modules it is recommended to only specify the provider definition within the root module.

As version 2.0 was a major release, I'd have expected that features is still optional. It looks like we are ending up with many empty feature{} blocks.
### New or Affected Resource(s)

* provider block

### Potential Terraform Configuration

```hcl
provider {features{}}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @tbugfinder 

Thanks for opening this issue.

As [mentioned in the changelog, version 2.0 of the Azure Provider](https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/CHANGELOG.md#200-february-24-2020) now requires that a provider block be defined and a `features` block be defined within it. The `features` block is new in version 2.0 of the Azure Provider and allows controlling of the behaviour of certain resources (including whether data disks/key vaults should be purged).

Since this controls the behaviour of the Provider this block is now required as we believe it's important that folks are aware which Provider block is being used, since this was ambiguous as it was optional in 1.x (and thus we often saw confusion where users were using one provider block when they thought they were using another with modules).

When building Terraform Configurations we recommend defining Provider Blocks in the root directory (which is the directory where Terraform's called from) - which means these can be passed into modules from this level, for example:

```
provider "azurerm" {
  version = "=2.0.0"
  # ...
  features {}
}

module "example" {
  source = "modules/example"
  # ...

  providers = {
    "azurerm.default" = "azurerm"
  }
}
```

You can achieve the same thing for a module by using a `test` directory which calls into the module itself for testing, passing in the provider - [as shown in this example](https://github.com/tombuildsstuff/terraform-module-pandamonium), which has the advantage of (essentially) being how end-users will use the module too, so it's an up-to-date example. As such it should be possible to achieve this by allowing users to specify the provider (and thus features) block at the top-level then pass this in.

Since the `features` block is intentionally required to highlight which instance of a provider is being used, unfortunately we have no plans to make this optional - but I believe this approach should work for you :)

Thanks!
