### ISSUE TITLE
key vault delete fails due to incorrect sub-resource deletion order

### ISSUE THREAD

**Issue by khaliddermoumi** [terraform-providers/terraform-provider-azurerm#6032]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When deleting a key vault, the access policies belonging to this key vault are obviously deleted BEFORE secrets in this vault are deleted. As a result, deleting the secrets fails, as the caller does not have the permissions to list or delete secrets anymore.

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azuread v0.7.0
+ provider.azurerm v2.0.0

### Affected Resource(s)

* `azurerm_key_vault`

### Terraform Configuration Files

```hcl

resource azurerm_key_vault core_akv {
  name                = var.keyvault_name
  location            = var.locations.northeurope
  resource_group_name = module.core_arg.name
  tenant_id           = var.tenant_id
  sku_name            = var.keyvault_sku_name

  enabled_for_disk_encryption     = true
  enabled_for_deployment          = true
  enabled_for_template_deployment = true

  network_acls {
    bypass                     = "AzureServices"
    default_action             = "Allow"
    ip_rules                   = var.keyvault_ip_rule_cidr
    virtual_network_subnet_ids = []
  }
}

resource azurerm_key_vault_access_policy terraform_user {
  key_vault_id = azurerm_key_vault.core_akv.id
  tenant_id    = var.tenant_id
  // for an access policy for an app/sp, you need the object_id of the sp, not the app
  object_id = data.terraform_remote_state.subscription.outputs.terraform_sp.object_id

  certificate_permissions = [
    "backup",
    "create",
    "delete",
    "deleteissuers",
    "get",
    "getissuers",
    "import",
    "list",
    "listissuers",
    "managecontacts",
    "manageissuers",
    "purge",
    "recover",
    "restore",
    "setissuers",
    "update"
  ]

  key_permissions = [
    "backup",
    "create",
    "decrypt",
    "delete",
    "encrypt",
    "get",
    "import",
    "list",
    "purge",
    "recover",
    "restore",
    "sign",
    "unwrapKey",
    "update",
    "verify",
    "wrapKey"
  ]

  secret_permissions = [
    "backup",
    "delete",
    "get",
    "list",
    "purge",
    "recover",
    "restore",
    "set"
  ]
}

resource azurerm_key_vault_secret terraform_backend_key {
  key_vault_id = azurerm_key_vault.core_akv.id
  name         = "core-storage-account-access-key"
  value        = module.storage_account.primary_access_key
  content_type = "text/plain"
}
```

### Expected Behavior

The key vault should get deleted, in this order so it works:
1. delete secret
2. delete access policy
3. delete key vault

### Actual Behavior

The key vault deletion is performed in this order:
1. delete access policy
2. delete secret -> Error!

In step 2., a "permission denied" error is returned from the azurerm API, which makes sense, as the
permission to read/delete the secret has been deleted in step 1.

### Steps to Reproduce

1. first, create the resources: `terraform apply`
2. then, delete: `terraform destroy`

### Important Factoids

It is possible to avoid this error by using a "depends_on" block in the secret, pointing to the access policy. But still, the azurerm provider should know how to delete a key vault correctly, because knowing about azure RM resource is it's very own business domain, and nothing else.

**Comment by tombuildsstuff** [comment]
hi @khaliddermoumi 

Thanks for opening this issue.

If you're wanting to manage items inside a Key Vault you'll need to ensure that the Identity (e.g. User/Service Principal) being used to access the Key Vault has permissions to manage items within that Key Vault, due to the way the Key Vault API is designed.

This is easiest when using the in-lined permissions block, since this ensures that the permissions are configured prior to the Key Vault "child" (e.g. Cert/Key/Secret) resources being created. Alternatively you can use a `depends_on` between the Key Vault Child resources and the Key Vault Access Policy resources to ensure that the Identity being used to manage these resources has access to manage them, prior to the child resources being created.

Unfortunately due to the way the Key Vault API is designed there's no way to manage these resources when the identity being used by Terraform doesn't have access to it - as such it's required that the "child" resources here are dependent on the Access Policy resource.

Whilst it's possible that Terraform could automatically look to add and remove the Access Policy on demand - this isn't something we currently have plans to do unfortunately - and as such I'm going to close this issue for the moment; however it should be possible to achieve [this using a `depends_on` between these resources](https://learn.hashicorp.com/terraform/getting-started/dependencies.html) if you're using the external Access Policy resource.

Thanks!
