### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment worse performance comparing to use block storage_data_disk

### ISSUE THREAD

**Issue by rukawata** [terraform-providers/terraform-provider-azurerm#6082]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_2.1.0`

### Terraform Configuration Files

```hcl
# Apply complete! Resources: 15 added, 0 changed, 0 destroyed.

# real    8m16.341s
# user    0m9.526s
# sys     0m2.816s

# Initalizes Azure rm provider
provider "azurerm" {
  version = "~>2.0"
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "nancyc-w-disk-att"
  location = "westus2"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "nancyc-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  name                 = "nancyc-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "nic" {
  name                = "nancyc-nic"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.subnet.id
    private_ip_address_allocation = "Dynamic"
  }
}

# tag: azurerm 2.0.0
# Create managed data disk
resource "azurerm_managed_disk" "data-disk" {
  count                = 5
  name                 = join("-", ["data", "disk", count.index])
  location             = azurerm_resource_group.rg.location
  resource_group_name  = azurerm_resource_group.rg.name
  create_option        = "Empty"
  storage_account_type = "Standard_LRS"
  disk_size_gb         = 512
}

# tag: azurerm 2.0.0
# Manages Linux Virtual Machine for HANA DB servers
resource "azurerm_linux_virtual_machine" "vm-dbnode" {
  name                = "nancyc-vm"
  computer_name       = "nancyc-vm"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  network_interface_ids = [
    azurerm_network_interface.nic.id
  ]
  size                            = "Standard_D8s_v3"
  admin_username                  = "nancyc"
  admin_password                  = "Help4you"
  disable_password_authentication = false

  os_disk {
    name                 = "nancyc-os-disk"
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
    disk_size_gb         = 64
  }

  source_image_reference {
    publisher = "SUSE"
    offer     = "sles-sap-12-sp5"
    sku       = "gen1"
    version   = "latest"
  }
}

# tag: azurerm 2.0.0
# Manages attaching a Disk to a Virtual Machine
resource "azurerm_virtual_machine_data_disk_attachment" "vm-dbnode-data-disk" {
  count                     = 5
  managed_disk_id           = azurerm_managed_disk.data-disk[count.index].id
  virtual_machine_id        = azurerm_linux_virtual_machine.vm-dbnode.id
  caching                   = "None"
  write_accelerator_enabled = false
  lun                       = count.index
}

```

### Expected Behavior

`azurerm_linux_virtual_machine` no long supports `storage_data_disk`.
Therefore `azurerm_virtual_machine_data_disk_attachment` is used to connect VM with data disks.
One would expect performance wise more or less similar.

### Actual Behavior

Using `azurerm_virtual_machine_data_disk_attachment` has significant performance degradation.
The runtime increased from 4m30s (with below code) to 8m16s.
The reason I compared a sample with 5 data disk attach is, our [repo](https://github.com/Azure/sap-hana) focus on creating resources for SAP HANA scenario, where you would have at least 5 if not more disk attached to one VM. This change has an even larger impact on our repo if we migrate from `azurerm_virtual_machine` to `azurerm_linux_virtual_machine`.

```hcl
#Apply complete! Resources: 5 added, 0 changed, 0 destroyed.

#real    4m30.634s
#user    0m11.451s
#sys     0m3.579s

# Initalizes Azure rm provider
provider "azurerm" {
  version = "~>2.0"
  features {}
}

resource "azurerm_resource_group" "rg" {
  name     = "nancyc-wo-disk-att"
  location = "westus2"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "nancyc-vnet"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}

resource "azurerm_subnet" "subnet" {
  name                 = "nancyc-subnet"
  resource_group_name  = azurerm_resource_group.rg.name
  virtual_network_name = azurerm_virtual_network.vnet.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "nic" {
  name                = "nancyc-nic"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.subnet.id
    private_ip_address_allocation = "Dynamic"
  }
}

# Creates database VM
resource "azurerm_virtual_machine" "vm-dbnode" {
  name                          = "nancyc-vm"
  location                      = azurerm_resource_group.rg.location
  resource_group_name           = azurerm_resource_group.rg.name
  primary_network_interface_id  = azurerm_network_interface.nic.id
  network_interface_ids         = [azurerm_network_interface.nic.id]
  vm_size                       = "Standard_D8s_v3"
  delete_os_disk_on_termination = "true"

  storage_os_disk {
    name              = "nancyc-os-disk"
    caching           = "ReadWrite"
    managed_disk_type = "Standard_LRS"
    create_option     = "FromImage"
    disk_size_gb      = 64
  }

  storage_image_reference {
    publisher = "SUSE"
    offer     = "sles-sap-12-sp5"
    sku       = "gen1"
    version   = "latest"
  }

  dynamic "storage_data_disk" {
    iterator = disk
    for_each = range(5)
    content {
      name                      = join("-", ["data", "disk", disk.key])
      caching                   = "None"
      create_option             = "Empty"
      managed_disk_type         = "Standard_LRS"
      disk_size_gb              = 512
      write_accelerator_enabled = false
      lun                       = disk.key
    }
  }

  os_profile {
    computer_name  = "nancyc-vm"
    admin_username = "nancyc"
    admin_password = "Help4you"
  }

  os_profile_linux_config {
    disable_password_authentication = false
  }
}

```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ArcturusZhang** [comment]
Hi @rukawata thanks for this issue.
And this performance issue is caused by [this lock](https://github.com/terraform-providers/terraform-provider-azurerm/blob/7066eab51480cad38e2e321211eab222634e2d80/azurerm/internal/services/compute/resource_arm_virtual_machine_data_disk_attachment.go#L107).
The attachment of a data disk is achieved by update the existing VM, and the several attachments must be performed one by one if there is multiple attachments. Therefore a performance issue will be expected when there are a significant number of data disk attachments.

**Comment by tombuildsstuff** [comment]
hi @rukawata 

Thanks for opening this issue.

The Azure API's require that the list of data disks for a Virtual Machine are submitted in a monolithic API call, rather than having a separate API Endpoint for disk attachments - as such unfortunately to correctly map the behaviour of the Azure API here we've had to work around this using a "virtual resource", which updates the Virtual Machine resource (which to prevent concurrent updates interfering with each other uses a lock as @ArcturusZhang has mentioned above).

This does introduce a slight performance degradation depending on the number of disks being attached since these changes need to be made sequentially - however we felt that it's more important to be reliable here (and ensure these work) over being quick (submitting the update and potentially erroring, as before).

Due to there being no Azure API for managing disk attachments in parallel, unfortunately there isn't much we can do about this at this point in time - that said should a disk attachment become available in the future we'll look to switch over to this, which should fix this issue. I've [opened this issue in the Rest API Specs repository to track this Feature Request](https://github.com/Azure/azure-rest-api-specs/issues/8693). 

@ArcturusZhang unfortunately introducing a `disk attachments` resource (or exposing this functionality inside of the VM resources) would re-introduce the issue of being unable to correctly map the API behaviour, so this isn't a viable solution unfortunately.

Thanks!
