### ISSUE TITLE
Azure Resource Manager PowerShell Support Deprecation

### ISSUE THREAD

**Issue by aquibchiniwala** [terraform-providers/terraform-provider-azurerm#6089]
Azure RM is being replaced by AZ Module (source : https://azure.microsoft.com/en-in/blog/azure-powershell-cross-platform-az-module-replacing-azurerm/)

And as terraform uses Azure Resource Manager APIs, so how long can we rely for production on terraforms AzureRM Provider?

**Comment by tombuildsstuff** [comment]
hi @aquibchiniwala 

Thanks for opening this issue.

The phrase "AzureRM" itself is unfortunately a little ambiguous, whilst it stands for Azure Resource Manager; it's used to refer to the Azure Resource Manager API's, the concept of Resource Manager within Azure and the PowerShell module.

The link posted above refers to the PowerShell modules with this name `AzureRM-{XXX}` which have been replaced by the new PowerShell modules prefixed with `Az-{XXX}`. Internally both of these PowerShell modules (and Terraform) call into the Azure Resource Manager API's, which are not deprecated. As such this isn't something that'll affect the AzureRM Provider which remains fully supported - this only affects the older AzureRM PowerShell module.

Since this is a question rather than an issue in the AzureRM Provider I'm going to close this issue for the moment, however please let us know if you've still got questions around the deprecation of this PowerShell module and we'll take another look :)

Thanks!

**Comment by aquibchiniwala** [comment]
> hi @aquibchiniwala
> 
> Thanks for opening this issue.
> 
> The phrase "AzureRM" itself is unfortunately a little ambiguous, whilst it stands for Azure Resource Manager; it's used to refer to the Azure Resource Manager API's, the concept of Resource Manager within Azure and the PowerShell module.
> 
> The link posted above refers to the PowerShell modules with this name `AzureRM-{XXX}` which have been replaced by the new PowerShell modules prefixed with `Az-{XXX}`. Internally both of these PowerShell modules (and Terraform) call into the Azure Resource Manager API's, which are not deprecated. As such this isn't something that'll affect the AzureRM Provider which remains fully supported - this only affects the older AzureRM PowerShell module.
> 
> Since this is a question rather than an issue in the AzureRM Provider I'm going to close this issue for the moment, however please let us know if you've still got questions around the deprecation of this PowerShell module and we'll take another look :)
> 
> Thanks!
