### ISSUE TITLE
TF unable to replace azurerm_network_interface due to existing azurerm_network_interface association

### ISSUE THREAD

**Issue by Marcus-James-Adams** [terraform-providers/terraform-provider-azurerm#6112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform: 0.12.23
prvider.azurerm: 2.1

### Affected Resource(s)
azurerm_network_interface
azurerm_public_ip
azurerm_windows_virtual_machine
azurerm_linux_virtual_machine

### Expected Behavior
should update the azurerm_public_ip

### Actual Behavior
Error: Error deleting Public IP "my-public-ip" (Resource Group "my-rsg"): network.PublicIPAddressesClient#Delete: Failure sending request: StatusCode=400 -- Original Error: Code="PublicIPAddressCannotBeDeleted" Message="Public IP address /subscriptions/xxxxx/resourceGroups/my-rsg/providers/Microsoft.Network/publicIPAddresses/my-public-ip can not be deleted since it is still allocated to resource /subscriptions/xxxxxx/resourceGroups/my-rsg/providers/Microsoft.Network/networkInterfaces/my-vm-nic/ipConfigurations/my-vm. In order to delete the public IP, disassociate/detach the Public IP address from the resource.  To learn how to do this, see aka.ms/deletepublicip." Details=[]

### Steps to Reproduce
Have an existing Azure VM with azurerm_network_interface & azurerm_public_ip attached.
Make any change that requires the azurerm_public_ipto be replaced eg, changing it's sku setting zones etc but that does not require azurerm_network_interface to be replaced.

* terraform plan - OK
* terraform apply - error during apply
### Manual Workaround
In the Azure portal - disassociate the azurerm_network_interface  from the azurerm_public_ip first or terraform taint azurerm_network_interface

**Comment by yupwei68** [comment]
Hi @Marcus-James-Adams , thanks for opening this issue. It might be necessary to take steps in Terraform to treat the dependent resources sometimes. 
On fact, if you have created a NIC and PIP on portal and you want to force new the PIP, portal will show the error "PIP is in use and can't be delete" too. Then you'll need to disassociate the PIP from NIC, then force new PIP, and then associate PIP to NIC. 
In terraform, the same you'll need three steps to get that. First, you need to set the PIP field in NIC to empty string and terraform apply. Second, you need to force new PIP and terraform apply. Thirdly, you need to set PIP id in NIC to associate these two resources and terraform apply.
Could terraform core do all the three steps in one step? In this case, it seems reasonable if terraform core could merge the three steps into one. But in some dependent cases, for example, `azurerm_resource_group` and any resources in the resource group. We could not set the resource group field in any resource to empty string. So terraform core could not merge the three steps into one.

**Comment by Marcus-James-Adams** [comment]
Hi
I get this when i create all 3 items in terraform.
it should be expected that destroy would function in this case

I have to go to the portal to manually disassociate the nic from the pip
which kind breaks having automation tooling

Regards
Marcus

**Comment by tombuildsstuff** [comment]
hi @Marcus-James-Adams 

Apologies for the delayed response here.

Version 2.0 of the Azure Provider introduced the `azurerm_network_interface_security_group_association` resource which manages the association between a Network Interface and a Network Security Group, which enforces that this association is deleted in the relevant order.

Since in this instance the Network Security Group association is being managed outside of Terraform, unfortunately Terraform is unable to remove this association (since it doesn't manage it) - as such we'd recommend using [the `azurerm_network_interface_security_group_association` resource](https://www.terraform.io/docs/providers/azurerm/r/network_interface_security_group_association.html) to do so.

Since this should be fixed by using [the `azurerm_network_interface_security_group_association` resource](https://www.terraform.io/docs/providers/azurerm/r/network_interface_security_group_association.html) to manage this association inline within the configuration - I'm going to close this issue for the moment, but if your still having issues then you should be able to get further help for this [in the Community Forum](https://discuss.hashicorp.com)

Thanks!
