### ISSUE TITLE
azurerm_subnet_network_security_group_association & azurerm_subnet_route_table_association complain about existing subnet

### ISSUE THREAD

**Issue by chadif** [terraform-providers/terraform-provider-azurerm#6128]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.21
+ provider.azurerm v2.0.0

### Affected Resource(s)

* azurerm_subnet
* azurerm_subnet_network_security_group_association
* azurerm_subnet_route_table_association

### Terraform Configuration Files

```hcl
resource "azurerm_subnet" "shared-rdshost" {
  name                      = "shared-rdshost"
  virtual_network_name      = azurerm_virtual_network.shared.name
  resource_group_name       = azurerm_resource_group.net-shared.name
  address_prefix            = "10.10.64.0/28"
}

resource "azurerm_subnet_network_security_group_association" "shared-rdshost-nsg-association" {
  subnet_id                 = azurerm_subnet.shared-rdshost.id
  network_security_group_id = azurerm_network_security_group.shared-rdshost.id
}

* resource "azurerm_subnet_route_table_association" "shared-rdshost-rt-association" {
  subnet_id      = azurerm_subnet
  route_table_id = azurerm_route_table.shared-default.id
}
```

### Expected Behavior

It should associate the NSG and route table to the existing subnet

### Actual Behavior

I get this error:

azurerm_subnet_route_table_association.shared-rdshost-rt-association: Creating...
azurerm_subnet_network_security_group_association.shared-rdshost-nsg-association: Creating...

Error: A resource with the ID "/subscriptions/xxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/Net-Shared-RG/providers/Microsoft.Network/virtualNetworks/Shared-VNET/subnets/shared-rdshost" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_subnet_network_security_group_association" for more information.

  on dev-20-virtual-networks.tf line 41, in resource "azurerm_subnet_network_security_group_association" "shared-rdshost-nsg-association":
  41: resource "azurerm_subnet_network_security_group_association" "shared-rdshost-nsg-association" {

Error: A resource with the ID "/subscriptions/xxxxxx-xxxxx-xxxx-xxxx-xxxxxxxxxxxxx/resourceGroups/Net-Shared-RG/providers/Microsoft.Network/virtualNetworks/Shared-VNET/subnets/shared-rdshost" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_subnet_route_table_association" for 
more information.

  on dev-20-virtual-networks.tf line 46, in resource "azurerm_subnet_route_table_association" "shared-rdshost-rt-association":
  46: resource "azurerm_subnet_route_table_association" "shared-rdshost-rt-association" {

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The subnet has been created previously with Azure RM Provider 1.40.0 with the `network_security_group_id` and `route_table_id` attributes. Once I upgraded terraform to 0.12.21 it forced me to use the nsg and route table association objects but it is not applying successfully.

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @chadif 

Thanks for opening this issue.

If an association exists between the Subnet and the Network Security Group/Route Table resources when trying to create these associations - Terraform will fail during the creation of these resources with an error that they need to be imported into the Statefile (as you're seeing). Terraform tracks the state of resources it's managing in it's Statefile - which means that existing resources need to be imported into the State - this can be done [using `terraform import`](https://www.terraform.io/docs/import/index.html).

The specific format needed to import resources into the State can be found in the "import" section on the documentation page for each resource, for example here's the documentation for importing a [`azurerm_subnet_route_table_association`](https://www.terraform.io/docs/providers/azurerm/r/subnet_route_table_association.html#import).

Since this is a question around importing existing resources into the state rather than a bug in the Azure Provider - I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look.

Thanks!
