### ISSUE TITLE
Some data sources not supported for azurerm 

### ISSUE THREAD

**Issue by shahbhavya85** [terraform-providers/terraform-provider-azurerm#621]
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
- azurerm_network_security_group
- azurerm_virtual_network
- azurerm_subnet

Trying to use data source for above resources and it fails. 

Error: data.azurerm_network_security_group.test: Provider doesn't support data source: azurerm_network_security_group
Error: data.azurerm_subnet.test: "address_prefix": this field cannot be set
Error: data.azurerm_virtual_network.test: Provider doesn't support data source: azurerm_virtual_network

**Comment by tombuildsstuff** [comment]
Hey @shahbhavya85 

Thanks for opening this issue :)

To answer each question in-line:

> Error: data.azurerm_network_security_group.test: Provider doesn't support data source: azurerm_network_security_group

This is a good spot and I've opened #623 which includes a new data source for Network Security Groups - which should land in the next release

> Error: data.azurerm_subnet.test: "address_prefix": this field cannot be set

The `address_prefix` field is returned from this data source when a name/resource group name are specified - are you looking to be able to filter on this field? So that we can understand this further - would it be possible to share the use-case here?

> Error: data.azurerm_virtual_network.test: Provider doesn't support data source: azurerm_virtual_network

Support for this was merged in #533 which will be going out in the next release

Thanks!

**Comment by shahbhavya85** [comment]
Thanks for quick around! 

I found the error what I was doing wrong. Instead of using resource.azurerm_subnet.test was using data.azurerm_subnet.test. Updated and it resolved the issue for me.

**Comment by tombuildsstuff** [comment]
@shahbhavya85 awesome - thanks for confirming that. I've just released v1.0.0 of the AzureRM Provider which includes support for the network security group data source.

Given that I believe this issue is resolved and I'm going to close this issue for the moment; but please feel free to re-open it if you're still having issues and we'll take another look :)

Thanks!

**Comment by shahbhavya85** [comment]
@tombuildsstuff Awesome!!

**Comment by AhmedAZafar** [comment]
Hi same issue when using provider 1.22.0.


My terraform file contains:


```
provider "azurerm" {
    version = "=1.22.0"
}

resource "azurerm_resource_group" "test_resource_group" {
    name = "test_resource_group"
    location = "North Europe"
}

resource "azurerm_network_security_group" "test_network_security_group" {
    name = "test_network_security_group"
    location = "${azurerm_resource_group.test_resource_group.location}"
    resource_group_name = "${azurerm_resource_group.test_resource_group.name}"
}

resource "azurerm_virutal_network" "test_network" {
    name = "test_network"
    resource_group_name = "${azurerm_resource_group.test_resource_group.name}"
    location = "${azurerm_resource_group.test_resource_group.location}"
    address_space = ["10.0.0.0/16"]
}
```

Getting the following error:

<img width="42" alt="Screenshot 2019-01-15 at 13 41 02" src="https://user-images.githubusercontent.com/35378345/54932702-2c6fad00-4f13-11e9-8f54-c62e24dc73f9.png">



Any help would be greatly appreciated

**Comment by tombuildsstuff** [comment]
@AhmedAZafar the data source is `azurerm_virtual_network` and not `azurerm_virutal_network` (mis-spelling) 😄

Since this issue's been resolved for over a year now I'm going to lock this issue for the moment; however please open a new issue if that doesn't work for you and we'll take another look.

Thanks!
