### ISSUE TITLE
os_type in azurerm_function_app not working

### ISSUE THREAD

**Issue by Gadnief** [terraform-providers/terraform-provider-azurerm#6220]
### Description

I try to create an azure function app inside of an linux app service plan (Standard, S1, Linux).
It is impossible to set the os_type property inside of the terraform definition for the function app.

### Message

Error: Unsupported argument

  on modules/functionapp/functionapp.tf line 9, in resource "azurerm_function_app" "customer":
   9:     os_type = "linux"

**Comment by tombuildsstuff** [comment]
hi @Gadnief 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
