### ISSUE TITLE
data.azurerm_policy_definition lookup by definition_id

### ISSUE THREAD

**Issue by rohrerb** [terraform-providers/terraform-provider-azurerm#6249]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

DisplayName is not consistent across clouds (gov vs commerial) but policy_definition_id is consistent.  

### New or Affected Resource(s)

data "azurerm_policy_definition" "example" {
  policy_definition_id= "<some-guid>"
}

### Potential Terraform Configuration

```
data "azurerm_policy_definition" "example" {
  policy_definition_id= "<some-guid>"
}
```

**Comment by rohrerb** [comment]
This could also resolve https://github.com/terraform-providers/terraform-provider-azurerm/issues/5883

**Comment by ArcturusZhang** [comment]
Hi @rohrerb Thanks for this issue!
Actually the field you are intending to add should be `name` of the policy definition.
I am currently working on this. Should be able to open a PR fixing this.
Or are you meaning the full ID, like `/subscription/{subsID}/providers/Microsoft.Authorization/policyDefinitions/def1`? I suppose when you have the ID and want to get some information from the resource, you should use `import` rather than a data source.
