### ISSUE TITLE
Feature Request: Support for Shared Access Policies in Eventhub Namespaces

### ISSUE THREAD

**Issue by tanner-bruce** [terraform-providers/terraform-provider-azurerm#626]
### Terraform Version
0.11.1

### Affected Resource(s)
azurerm_eventhub_authorization_rule

### Terraform Configuration Files
Example from main docs works

`azurerm_eventhub_authorization_rule` requires a namespace name and eventhub name, however, in the Azure UI, it is possible to create authorization rules on the namespace itself, so `eventhub_name` should not be a required parameter.

**Comment by tombuildsstuff** [comment]
hey @tanner-bruce 

Thanks for opening this issue

> azurerm_eventhub_authorization_rule requires a namespace name and eventhub name, however, in the Azure UI, it is possible to create authorization rules on the namespace itself, so eventhub_name should not be a required parameter.

Taking a quick look into this - from what I can see this is what's called a `Shared Access Policy` in the Portal (but referred to in the SDK as an `Authorization Rule`). Support appears to exist for this on the Event Hub Namespaces Client in the SDK - so it should be possible to add a new resource supporting this functionality.

Thanks!

**Comment by iakko** [comment]
Hello, any update on this?

**Comment by tombuildsstuff** [comment]
hey @iakko 

Support for Eventhub Namespace Authorization Rules shipped in v1.10 of the AzureRM Provider and can be found here: https://www.terraform.io/docs/providers/azurerm/r/eventhub_namespace_authorization_rule.html

They're currently missing from the sidebar on the website due to a bug which I'll be pushing a commit to fix later today :)

Given support for this has shipped, I'm going to close this issue for the moment.

Thanks!

**Comment by RavulaChetan** [comment]
Hi @tombuildsstuff 

I am trying to use azurerm_eventhub_namespace_authorization_rule and i am getting error passing eventhub name "eventhub_name"

Error message
An argument named "eventhub_name" is not expected here.

I am able to create Auth rules on EventHub Namespace when i dont use eventhub_name. 

Can you look into this please.
