### ISSUE TITLE
eventhub_namespace throws an error "The argument "location" is required, but no definition was found". Location is depreciated in Azurerm provider 2.0

### ISSUE THREAD

**Issue by kerzey** [terraform-providers/terraform-provider-azurerm#6261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_eventhub_namespace`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @kerzey 

Thanks for opening this issue.

As [per the 2.0 upgrade guide](https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html#resource-azurerm_eventhub_namespace) this field has been deprecated in 1.x releases and removed in 2.0 since Azure no longer requires this value. As such you should be able to remove this field from your Terraform Configuration and this'll continue working as before.

Since this should be fixed by updating your Terraform Configuration I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
