### ISSUE TITLE
should terraform create function invoke create api and update api ?

### ISSUE THREAD

**Issue by njuCZ** [terraform-providers/terraform-provider-azurerm#6277]
This is a question about how to write resource provider.

Business Background:
1. user creates a data export job
2. the create rest api response contains address info (Computed: true)
3. user send their disk to the computed address, then user can update carrier info, carrier number info and state of the data export job

In the aspect of business, user must create the job first and then update delivery package fields. 
So I want to ask: in the create function of terraform resource, should we invoke create rest api and then invoke update rest api ? This will violate the business.
If we just invoke create rest api in read function and invoke update rest api in update function, some fields can not be set in create, Is it acceptable ?

**Comment by tombuildsstuff** [comment]
hi @njuCZ 
I'm not sure exactly which Resource Provider you're referring to - but in general we call the methods required to create a resource (even if that requires calling Create and subsequently Update via another API to fully provision the resource) within the Create function.
From the details you've given above (where this involves manual processes, and some fields can't be set/read) - it sounds like this resource probably isn't a good fit for Terraform - but it's hard to say for sure without knowing the specific Resource Provider/API's you're using; would you be able to provide some more details here?
Since this is a question rather than a bug in the Azure Provider I'm going to close this issue for the moment - but if you can provide some more information about the API's you're referring too then we can take another look.
Thanks!

**Comment by njuCZ** [comment]
@tombuildsstuff It's the storage import export RP.  I just found if user do the third step, the export_job resource can not be deleted by rest api. I think in terraform we can only do the first step.
