### ISSUE TITLE
azurerm 1.44.0 connection reset by peer

### ISSUE THREAD

**Issue by fzong76** [terraform-providers/terraform-provider-azurerm#6285]
according to https://github.com/terraform-providers/terraform-provider-azurerm/issues/3908 this issue has been fixed in 1.37.0. But we are seeing this issue very often in 1.44.0. 

one example

<code>
terraform get
terraform init -backend-config="storage_account_name=xxxxx" -backend-config="container_name=xxxx" -backend-config="key=xxx.tfstate" -backend-config="access_key=xxxxx" -get=false -reconfigure
 
Initializing the backend...
 
Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.
 
Error: Failed to get existing workspaces: Get https://xxx.blob.core.windows.net/xxxx?comp=list&prefix=xxxx.tfstateenv%3A&restype=container: read tcp 10.10.1.1:26822->4.8.1.4:443: read: connection reset by peer
</code>

**Comment by tombuildsstuff** [comment]
hi @fzong76 

Thanks for opening this issue.

This issue is related to the Azure Backend rather than the Azure Provider (which was fixed in #3908) - as such this issue needs to be opened on [the Terraform Core repository](https://github.com/hashicorp/terraform). Unfortunately since these repositories are in separate Github orgs, at this time there's no way to transfer these and keep you subscribed to this issue - as such would you mind [re-opening this issue on the Terraform Core repository](https://github.com/hashicorp/terraform)?

Thanks!
