### ISSUE TITLE
azurerm_virtual_machine_data_disk_attachment should be invalidated if VM does not exist

### ISSUE THREAD

**Issue by privatwolke** [terraform-providers/terraform-provider-azurerm#6297]
If external forces get rid of a VM the provider should also invalidate data disk attachments. A plan involving a VM + data disk attachment would then propose to create both resources.

### Reference
https://github.com/terraform-providers/terraform-provider-azurerm/blob/211a7324ff496d61ad6b95a365e025a4c6c83756/azurerm/internal/services/compute/resource_arm_virtual_machine_data_disk_attachment.go#L113

**Comment by tombuildsstuff** [comment]
hi @privatwolke 

Thanks for opening this issue :)

The fix for this got merged into #6237 which shipped in version 2.3.0 of the Azure Provider - would you be able to take a look and see if that works for you? Since this appears to be resolved I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
