### ISSUE TITLE
Unable to manage OmsAgentForLinux or MicrosoftMonitoringAgent with terraform

### ISSUE THREAD

**Issue by jeefberkey** [terraform-providers/terraform-provider-azurerm#6312]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.3.0
+ provider.random v2.2.1
```

### Affected Resource(s)

* `azurerm_windows_virtual_machine`
* `azurerm_linux_virtual_machine`
* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "main" {
  count = var.machines

  name                = "${var.purpose}-${format("%02d", count.index + 1)}-${var.environment}-${data.azurerm_resource_group.main.location}"
  location            = data.azurerm_resource_group.main.location
  resource_group_name = data.azurerm_resource_group.main.name

  size                       = var.instance_size
  network_interface_ids      = [azurerm_network_interface.main[count.index].id]

  source_image_reference {
    publisher = var.image_reference.publisher
    offer     = var.image_reference.offer
    sku       = var.image_reference.sku
    version   = var.image_reference.version
  }

  admin_username = var.admin_user
  admin_ssh_key {
    username   = var.admin_user
    public_key = file(var.admin_ssh_key)
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  tags = local.common_tags
}

resource "azurerm_virtual_machine_extension" "monitoring" {
  virtual_machine_id         = azurerm_linux_virtual_machine.main.id
  name                       = "OmsAgentForLinux"
  publisher                  = "Microsoft.EnterpriseCloud.Monitoring"
  type                       = "Microsoft.EnterpriseCloud.Monitoring.OmsAgentForLinux"
  type_handler_version       = "2.0"
  auto_upgrade_minor_version = true

  tags = local.common_tags
}
```

### Expected Behavior

I can set the Log Analytics Workspace and Automation Account used for the OmsAgentForLinux upon provisioning the VM, or manage the VM Extension separately with another resource.

### Actual Behavior

A new resource group and  Log Analytics workspace is generated for me, creating resources terraform can't manage. There's an option to disable the management extension (`provision_vm_agent`), but you can't disable that without also setting `allow_extension_operations` to false, which doesn't allow you to use any extensions. 

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @jeefberkey 

Thanks for opening this issue - apologies for the delayed response here!

The `azurerm_virtual_machine_extension` resource provides the option to specify both `settings` and `protected_settings` as a JSON string - the values for which differ by VM Extension and are case-sensitive. Unfortunately since this is open-ended (e.g. the values differ for each VM Extension, and there's quite a number of possible VM extensions available) - we're unable to offer more specific support for the configuration of this resource.

Based on what I can see [in the documentation](https://docs.microsoft.com/en-us/azure/virtual-machines/extensions/oms-linux) it appears that it's possible to specify values for the `workspaceId` and `workspaceKey` fields here - which should be configurable using Terraform's `protected_settings` and `settings` fields.

Since this appears to be possible by updating the Terraform Configuration I'm going to close this issue for the moment - that said the code behind [the OMS VM Extension is available in this repository](https://github.com/Microsoft/OMS-Agent-for-Linux) and as such I'd suggest raising an issue on that repository, where the team who own that extension should be able to help further :)

Thanks!
