### ISSUE TITLE
azurerm_subnet_network_security_group_association - Updating subnet and NSG with each refresh and apply

### ISSUE THREAD

**Issue by manojsgh** [terraform-providers/terraform-provider-azurerm#6317]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_2.3.0`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_subnet" "main" {
  name                 = var.subnet_name[count.index]
  address_prefix       = var.subnet_prefix[count.index]
  virtual_network_name = azurerm_virtual_network.main.name
  resource_group_name  = var.rg_name
  service_endpoints    = var.service_endpoints
  delegation {
    name = var.subnet_delegation
    service_delegation {
      name    = var.service_delegation_name
      actions = var.subnet_delegation_action
    }
  }
  count = var.subnet_count
}
resource "azurerm_network_security_group" "main" {
  name                = var.nsg_name
  location            = var.location
  resource_group_name = var.rg_name
  tags                = var.tags
security_rule{}
security_rule{}
security_rule{}
......
}

resource "azurerm_subnet_network_security_group_association" "main" {
  subnet_id                 = var.subnet_ids[count.index].subnet_id // 
  network_security_group_id = var.subnet_network_security_group_id
  count                     = var.subnet_count //subnet count
  depends_on                = [azurerm_subnet.main]
}

### Expected Behavior
I have created various modules and having issue with NSG association with subnet in Refresh and apply phase.
I have VNET, SUBNET, NSG and NSG association is already been created in Plan phase. However, whenever I update anything on different modules, it always delete the subnet and link the NSG even through there is no change in VNET, SUBNET, NSG and NSG association.

I read same issue on another thread and was supposed to fix in azurerm_2.0 however looks like issue is still persist.

### Actual Behavior

 module.networking.azurerm_subnet_network_security_group_association.main[0] must be replaced
 module.networking.azurerm_subnet_network_security_group_association.main[1] must be replaced

### Steps to Reproduce

1. `terraform refresh`
2. terraform apply

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @manojsgh 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html)

In this instance I believe you should be able to update your configuration to use a Resource For Each (as shown [in this example [section "Resource for_each"]](https://www.hashicorp.com/blog/hashicorp-terraform-0-12-preview-for-and-for-each/) or [in this example](https://ilhicas.com/2019/08/20/For-each-resource-terraform.html)) to pull the Subnet ID's out which should ensure the ordering of the Subnet ID's doesn't matter here.

Since this is a configuration question rather than a bug in the Azure Provider I'm going to close this issue for the moment, but if that doesn't work I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by manojsgh** [comment]
Thanks a lot. It helped. No more issue.
