### ISSUE TITLE
Does the example on the documentation page for azurerm_kubernetes_cluster work?

### ISSUE THREAD

**Issue by emacdona** [terraform-providers/terraform-provider-azurerm#6345]
### Current Terraform Version
```
terraform -v
Terraform v0.12.24
+ provider.azurerm v1.44.0
```

### Use-cases
When I try to create an AKS cluster by following the example here:
https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html

I get the following error when running "terraform plan":
Error: Error building AzureRM Client: 2 errors occurred:
	* A Subscription ID must be configured when authenticating as a Service Principal using a Client Secret.
	* A Tenant ID must be configured when authenticating as a Service Principal using a Client Secret.

**Comment by tombuildsstuff** [comment]
hi @emacdona 

Thanks for opening this issue.

Taking a look through here it appears that you're attempting to use a Client Secret to authenticate to Azure - and whilst you've specified the Client ID and Client Secret - the Subscription ID and Tenant ID aren't specified (which is why this error message is being returned). You should be able to fix this by specifying the Subscription ID and Tenant ID either inline (in the provider block) or using Environment Variables - [more details on how to do that can be found in the provider documentation](https://www.terraform.io/docs/providers/azurerm/index.html#authenticating-to-azure).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
