### ISSUE TITLE
v1.0.0 checksum mismatch error

### ISSUE THREAD

**Issue by aoggz** [terraform-providers/terraform-provider-azurerm#635]
When running a `terraform init` with v1.0.0 of the azurerm provider, an error is occurring.

### Terraform Version
0.11.1

### Affected Resource(s)
(entire provider)

### Debug Output
https://gist.github.com/aoggz/d63a891721262ce952f6428756787de9

### Expected Behavior
The workspace should have been initialized

### Actual Behavior
A checksum mismatch error was thrown

### Steps to Reproduce
1. `terraform init`

**Comment by tombuildsstuff** [comment]
Hey @aoggz 

Thanks for opening this issue - apologies about this.

This was due to a re-release, as the build agent didn't have permissions to push to the repository due to branch protection on the first attempt (but unfortunately did push the binaries). I've re-cleared the cache and believe this should now be fixed (it works for me as shown below) - would it be possible to try re-running `terraform init` to see if that works for you?

```
$ terraform init

Initializing provider plugins...
- Checking for available provider plugins on https://releases.hashicorp.com...
- Downloading plugin for provider “azurerm” (1.0.0)...

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running “terraform plan” to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
```

We'll be looking to update the build process to push the tag before pushing the binaries to avoid this issue in the future.

Thanks!

**Comment by antonydenyer** [comment]
Looks good our for us now. Thanks @tombuildsstuff

**Comment by mattpound808** [comment]
Works for me too. Thank you @tombuildsstuff

**Comment by tombuildsstuff** [comment]
@mattpound808 @antonydenyer awesome - thanks for confirming that 👍

I'm going to close this issue since it's resolved - but please feel free to re-open it if you're still seeing issues and we'll take another look :)

Thanks!

**Comment by aoggz** [comment]
Worked for me. Thanks @tombuildsstuff

**Comment by mstuivenberg** [comment]
Thanks! @tombuildsstuff
