### ISSUE TITLE
Upgrading to 2.x: Resource already existing on freshly made environment

### ISSUE THREAD

**Issue by topikettunen** [terraform-providers/terraform-provider-azurerm#6352]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
$ terraform version
Terraform v0.12.24
+ provider.azurerm v2.4.0
```

### Affected Resource(s)

Affected resources seem to more or less random but at least these I've stumbled upon:

* `azurerm_monitor_diagnostic_setting`

* `azurerm_resource_group`

* `azurerm_monitor_diagnostic_setting`

* `azurerm_subnet_network_security_group_association`

* `azurerm_dns_a_record`

Error associating `azurerm_subnet_network_security_group_association` seems to happen even on freshly made workspace while others have come up when trying to upgrade on existing workspaces.

### Actual Behavior

I'm personally developing and maintaining our relatively large IaC codebase and these issues seem to cause grey hairs for me. We use Terraform workspaces so we have multiple different workspaces for developers and also shared workspaces like dev, prod, etc. I first stumbled upon this when I was trying to upgrade to this new version of AzureRM provider after working through fixing the breaking changes. But unfortunately, I stumbled upon the following errors for multiple different resources:

```
Error: A resource with the ID "XXX" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for 
...
```

So straight upgrade from 1.44 to 2.x failed in an existing workspace. After that, I decided to test if I'm able to provision my own workspace from scratch by firstly deleting all the resources associated with it but that also ended up in the same error.

Then I thought to myself that there might be some old and wrong information under the subscription associated possibly with my workspace, albeit highly doubtful. Since our resources in Azure normally have the Terraform workspace's name associated with the resource name so we can map the owners of each resource more easily. So I decided to make a completely new workspace to test if this still occurs and unfortunately it still occurred.

I haven't yet tested in importing those resources manually since that is something that I don't necessarily want to do and why should I need to import some resources that I'm sure that they haven't been already existing before or they were already made with Terraform and they should already be in the corresponding workspace's state.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

There were no problems in 1.44, so I believe this somehow related to the new way of not importing resources in the provider.

**Comment by renereinert** [comment]
Hi, we got the same behaviour with our Application Gateway deployment.
Szenario: No Resources deployed. No Statefile existing.
Plan successfully -> RG + Public IP + AGW (including azurerm_monitor_diagnostic_setting).

During deployment: RG gets created, IP gets created, AGW gets created -> azurerm_monitor_diagnostic_setting failes because it already exist (azurerm 1.x works fine, azurerm 2.x doesnt work at all). I cant import a resource which is not exisitng. Therefore I think this one seems like a bug?

DevOps Log:
azurerm_application_gateway.appgateway: Still creating... [4m30s elapsed]
azurerm_application_gateway.appgateway: Creation complete after 4m32s [id=/subscriptions/xxxx/resourceGroups/xxx-agw-rg/providers/Microsoft.Network/applicationGateways/xxx-agw]
azurerm_monitor_diagnostic_setting.labagw: Creating...
Error: A resource with the ID "/subscriptions/xxx/resourcegroups/xxx-agw-rg/providers/microsoft.network/applicationgateways/xxx-agw/providers/microsoft.insights/diagnosticSettings/xxx-agw-diag" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_monitor_diagnostic_setting" for more information.
  on main.tf line 18, in resource "azurerm_monitor_diagnostic_setting" "appgateway":

**Comment by tombuildsstuff** [comment]
hi @topikettunen 

Thanks for opening this issue

In version 2.0 of the Azure Provider we fixed a bug where resources that already existed in Azure could be "adopted" by Terraform, since Azure has Upsert API's for a lot of API's (more details can be found in #2807). This is important because whilst some Azure API's have Upsert API's - certain fields can only be changed on existing resources by deleting/re-creating these resources.

As such when attempting to "create" a resource in version 2.0 or later of the Azure Provider, we first check for the presence of an existing resource with the same Name and Resource Group in Azure - and if this exists we ask that users import this via the error you're seeing.

Since Terraform is Stateful (and tracks the State of resources in it's Statefile) - these resources which Terraform may think it can "create" (but already exist) need to be imported into the Statefile via Terraform's Import functionality. 

As such you'll need to import these existing resources into the Statefile so that Terraform can detect changes to them - details of how to import each resource can be found in the documentation for each resource ([for example, here's how to import an App Service](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#import)) - [more details on Terraform Import can be found here](https://www.terraform.io/docs/import/index.html) - however since this is an intentional behaviour I'm going to close this issue for the moment.

Thanks!

**Comment by topikettunen** [comment]
Hi @tombuildsstuff !

Yeah, I figured that that might've been the case.

Unfortunately, this makes it more or less unusable for us. Mainly since we are running Terraform also in CI so if then some resource would need to get recreated and then would result in this error, we would need to run these manual imports on dozens of different workspaces and also the CI would constantly fail.

Is there some way this can be mitigated?

**Comment by tombuildsstuff** [comment]
@topikettunen sounds like the Terraform Statefile isn't being kept around - so you can store the Statefile in one of [Terraform's Backends](https://www.terraform.io/docs/backends/types/index.html) for example [AzureRM (to store the Statefile in a Blob Storage Container](https://www.terraform.io/docs/backends/types/azurerm.html) or [Terraform Cloud](https://www.terraform.io/docs/backends/types/remote.html) which should ensure these resources are tracked.

As such you may need to import these existing resources into the Statefile, but from then on they can be managed via Terraform.

Thanks!

**Comment by topikettunen** [comment]
State is in Azure
