### ISSUE TITLE
ComputeNodeFillType missing from Azure Provider for Terraform.

### ISSUE THREAD

**Issue by seniorpaul** [terraform-providers/terraform-provider-azurerm#6369]
Hi,

I don't seem to be able to find a reference to be able to set "ComputeNodeFillType" or equivalent of TaskSchedulingPolicy.  Setting up an autoscale pool with terraform severely limits the possibly of nodes being able to leave a pool when "spread" (the default) is set.  Is there a reason that this was ommitted - it seems to be in the azure-sdk-for-go has a model for it?

Regards.

Paul.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @seniorpaul 

Thanks for opening this issue.

Fields in the Azure SDK aren't automatically added to Terraform - since we not all fields necessarily make sense in Terraform - instead we add fields based on user requests/demand.

Unfortunately there's not enough information in this issue for us to determine which service this is related too - would you mind [opening a new Feature Request](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) with more details and we can take a look?

Thanks!
