### ISSUE TITLE
Terraform isn't aware of Dependency between Key Vault Access Policies and the Keys/Secrets/Certificates 

### ISSUE THREAD

**Issue by andydkelly-ig** [terraform-providers/terraform-provider-azurerm#6385]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform 0.12.18
Azure RM Version 2.4.0

### Affected Resource(s)

* `azurerm_key_vault_access_policy `

### Expected Behavior

Having a Terraform file that creates a Key Vault, Access Policy and Secret should then be able to be deleted.

### Actual Behavior

The Access Policy is deleted before the actual keys/secrets/certificates. This is a duplicate of issue #316 which was Closed despite it not being resolved. Granted there is a workaround by listing out your access policy inside the KeyVault resource but if the Access Policy resource is not to be deprectated this should be resolved. There are similar dependencies for AWS resources which have remediation steps for this - such as with EMR clusters and Security groups where the `revoke_rules_on_delete` permits the rules of a security group to be deleted before the security group which is the same kind of issue where Terraform is unaware of dependencies. 

### Steps to Reproduce

Create Terraform file containing `azurerm_key_vault`, `azurerm_key_vault_access_policy` and `azurerm_key_vault_key.

Run `Terraform Apply` to create everything.

Run `Terraform Delete` to delete everything.

The access policies will be deleted before the keys. And you will be stuck with an issue then that required GUI remediation.

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/3160

* #0000

**Comment by tombuildsstuff** [comment]
hi @andydkelly-ig 

Thanks for opening this issue.

As mentioned in #316 if you're wanting to manage items inside a Key Vault you'll need to ensure that the Identity (e.g. User/Service Principal) being used to access the Key Vault has permissions to manage items within that Key Vault, due to the way the Key Vault API is designed.

This is easiest when using the in-lined permissions block, since this ensures that the permissions are configured prior to the Key Vault "child" (e.g. Cert/Key/Secret) resources being created. Alternatively you can use a `depends_on` between the Key Vault Child resources and the Key Vault Access Policy resources to ensure that the Identity being used to manage these resources has access to manage them, prior to the child resources being created.

Unfortunately due to the way the Key Vault API is designed there's no way to manage these resources when the identity being used by Terraform doesn't have access to it - as such it's required that the "child" resources here are dependent on the Access Policy resource.

Whilst it's possible that Terraform could automatically look to add and remove the Access Policy on demand - this isn't something we currently have plans to do unfortunately - and as such I'm going to close this issue for the moment; however it should be possible to achieve [this using a `depends_on` between these resources](https://learn.hashicorp.com/terraform/getting-started/dependencies.html) if you're using the external Access Policy resource.

Thanks!
