### ISSUE TITLE
Unable to force-unlock state

### ISSUE THREAD

**Issue by CoRfr** [terraform-providers/terraform-provider-azurerm#640]
The error looks like that:
```
terraform force-unlock -force <id>
Failed to unlock state: failed to delete lock info from metadata: storage: service returned error: StatusCode=412, ErrorCode=LeaseIdMissing, ErrorMessage=There is currently a lease on the blob and no lease ID was specified in the request.
RequestId:6c8ebe08-001e-00d8-71c9-789fb8000000
Time:2017-12-19T12:58:50.4189788Z, RequestInitiated=Tue, 19 Dec 2017 12:58:49 GMT, RequestId=6c8ebe08-001e-00d8-71c9-789fb8000000, API Version=2016-05-31, QueryParameterName=, QueryParameterValue=
Lock Info:
  ID:        <id>
  Path:      terraform-state/dev.terraform.tfstate
  Operation: OperationTypeApply
  Who:       @jenkins
  Version:   0.11.1
  Created:   2017-12-19 12:53:08.462280312 +0000 UTC
  Info:
```
### Terraform Version
`0.11.1`

### Affected Resource(s)
Terraform State ?

### Expected Behavior
`terraform` should unlock the state, and it should be possible to run `terraform apply` again after.

### Actual Behavior
`terraform` raises an exception and the lock is still present.

### Steps to Reproduce
1. `terraform apply`
2. `Ctrl+C`
3. `terraform apply` (prints an error with the unlock id) 
3. `terraform force-unlock -force <id>

### References
Looks like this user had the same issue: https://groups.google.com/forum/#!topic/terraform-tool/we21XjC58pI

**Comment by tombuildsstuff** [comment]
Hey @CoRfr

Thanks for opening this issue (apologies for the delayed response to this over the Christmas break)

Since this issue is related to the Azure Backend / Terraform Core and not the AzureRM Provider - would you be able to [re-open this issue on the Terraform Core Repository](https://github.com/hashicorp/terraform/issues)? Whilst I can do this for you - if you migrate this over you'll be subscribed to updates for the new issue which will indicate when this is resolved.

Thanks!

**Comment by CoRfr** [comment]
Hey @tombuildsstuff ,

I'm not sure how this would be part from the Core and not the AzureRM provider, as it seems to me that an operation (breakage of the lease) is not performed by the ARM provider when we do the --force-unlock.
Could you detail why you think the problem is coming from the Core, so that I can eventually create the issue on the Core repository if appropriate.

Thanks

**Comment by tombuildsstuff** [comment]
hey @CoRfr 

Sure - so [the Azure Backend](https://www.terraform.io/docs/backends/types/azurerm.html) and [the Azure Provider](https://www.terraform.io/docs/providers/azurerm/index.html) whilst accessing the same API and using the same SDK) are housed in different repositories, with the Azure Provider being in this repository and Azure Backend being housed within the Terraform (Core) repository.

The [`force-unlock` command](https://www.terraform.io/docs/commands/force-unlock.html) is part of Terraform Core which calls into the Azure Backend to release the lock. As such, this issue is with the Azure Backend and not the Azure Provider - we need to migrate this issue over to the main (Core) repository.

Hope that helps :)

Thanks!

**Comment by CoRfr** [comment]
Thanks for the explanation @tombuildsstuff , I just opened https://github.com/hashicorp/terraform/issues/17046
