### ISSUE TITLE
Can not create cosmos db account

### ISSUE THREAD

**Issue by DaSenf** [terraform-providers/terraform-provider-azurerm#6427]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.23
+ provider.azurerm v2.5.0
+ provider.random v2.2.1
(running from Azure cloud shell)

### Affected Resource(s)
"azurerm_cosmosdb_account"

### Terraform Configuration Files

resource "azurerm_resource_group" "computervisionrg" {
  name     = var.resource_group_name
  location = var.location
}
resource "random_integer" "ri" {
  min = 10000
  max = 99999
}

resource "azurerm_cosmosdb_account" "mongodb" {
  name                = "mongodbb-account-${random_integer.ri.result}"
  location                = var.location
  resource_group_name     = azurerm_resource_group.computervisionrg.name
  offer_type          = "Standard"
  kind                = "MongoDB"

  capabilities {

    name = "EnableMongo"
  }

  consistency_policy {
    consistency_level       = "BoundedStaleness"
    max_interval_in_seconds = 400
    max_staleness_prefix    = 200000
  }

  geo_location {
    location          = var.failover_location
    failover_priority = 1
  }

  geo_location {
    prefix            = "state-demo-cosmos-db-${random_integer.ri.result}-customid"
    location                = var.location
    failover_priority = 0
  }

}

### Debug Output

Error: Error creating CosmosDB Account "mongodbb-account-41758" (Resource Group "computervisionboxterraform6"): Error waiting for the CosmosDB Account "mongodbb-account-41758" (Resource Group "computervisionboxterraform6") to finish creating/updating: Code="BadRequest" Message="Cannot add additional regions, since database account provision failed.\r\nActivityId: ec44f495-04b5-45c5-8d5d-b6cabc82a60a, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0, Microsoft.Azure.Documents.Common/2.10.0"

### Expected Behavior

I want to create a simple CosmosDB with mongoDB api

### Actual Behavior

The shown error is thrown and the resource is not added to the state.
Actually some service is created but in a failed state
![image](https://user-images.githubusercontent.com/15066410/78886853-29345a00-7a5f-11ea-89a8-4c168625885e.png)

When i rerun terraform apply    it obviously states that the resource is already there but not in the state and can´t update the resource or add databases etc.

### Steps to Reproduce
1. Use the config above and the following vars 
resource_group_name = "computervisionboxterraform6"
location = "East US"
failover_location = "East US 2"
2. terraform init 
3. terraform plan ...
4. terraform apply ...

### References

I also couldn´t make this https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html work
or this: 
https://medium.com/swlh/provisioning-azure-cosmos-db-resources-with-terraform-60c25b7bd52b

**Comment by tombuildsstuff** [comment]
hi @DaSenf 

Thanks for opening this issue.

Taking a look through here it appears that whilst certain Regions have provisioned (presumably East US) it appears that there isn't enough capacity in the other region (East US 2) to complete the deployment. Unfortunately this is an internal error within the Azure API - as such Terraform cannot automatically proceed here and thus we need operator input on how to proceed, either to delete the CoamoaDB account and retry, or import it into Terraform and then to add the second replica). 

As this is a capacity issue in the Azure API this should resolve itself in time, however you should also be able to work around this by provisioning in another region. Since this is an issue with Azure rather than something specific to the Azure Provider - I'm going to close this issue for the moment - however if you continue to have issues I'd recommend reaching out to Azure Support, since they should be able to confirm which region has sufficient capacity for CosmosDB at this time.

Thanks!
