### ISSUE TITLE
application gateway identity_ids always gets flagged as a change

### ISSUE THREAD

**Issue by markmqhr** [terraform-providers/terraform-provider-azurerm#6444]
azurerm version = 2.5.0
terraform version = 0.12.24

resource: azurerm_application_gateway

When specifying an identity_ids list of strings (with a single string) in the identity block, any subsequent plan or apply will always force a change of the identity_ids, even though no change has been specified in the value.

Relevant code:
```
  identity {
    identity_ids = ["/subscriptions/XXXXXX/resourcegroups/rgpnamehere/providers/Microsoft.ManagedIdentity/userAssignedIdentities/manageidnamehere"]
    type          = "UserAssigned"
  }
```

Relevant output from a plan or apply command:
```
      ~ identity {
          ~ identity_ids = [
              - "/subscriptions/XXXXXX/resourcegroups/rgpnamehere/providers/Microsoft.ManagedIdentity/userAssignedIdentities/manageidnamehere",
              + "/subscriptions/XXXXXX/resourceGroups/rgpnamehere/providers/Microsoft.ManagedIdentity/userAssignedIdentities/manageidnamehere",
            ]
            type         = "UserAssigned"
        }
```

**Comment by ArcturusZhang** [comment]
Hi @markmqhr thanks for this issue! 
But the root cause of this issue should be the inconsistency casing in the return value from the service. As you may notice that the IDs do have differences (`resourcegroups` vs `resourceGroups`)
I will take some time to see if I can provide a fix for this.

**Comment by ArcturusZhang** [comment]
Hi @markmqhr I have tried to reproduce your issue and it turns out despite the MSI id here returned from the service does have a segment of `resourcegroups` which is peculiar, but it is consistency with the ID that generated by the `azurerm_user_assigned_identity`.
Therefore to avoid your issue, I suggest you use a data source in your case, since you have already know the full ID of the identity, a data source should be totally equivalent and should work.

**Comment by markmqhr** [comment]
Thanks so much, I never saw the case difference in the resourceGroups portion, I can work around this on my end, thanks!
