### ISSUE TITLE
Encryption VM using terraform is failing or not supported

### ISSUE THREAD

**Issue by shahbhavya85** [terraform-providers/terraform-provider-azurerm#645]
### Terraform Version
Terraform v0.10.8

### Affected Resource(s)
Please list the resources as a list, for example:
- azurerm_virtual_machine

Error:
Error: azurerm_virtual_machine.test[0]: : invalid or unknown key: disk_encryption_key
Error: azurerm_virtual_machine.test[0]: : invalid or unknown key: encryption_settings

Code for tf: 

  encryption_settings {
    enabled = true
  }

  disk_encryption_key {
      secret_url      = "https://boxdevacceluswest.vault.azure.net/secrets/test/xxxx"
      source_vault_id = "subscriptions/xxxx/resourceGroups/rg_name/providers/Microsoft.KeyVault/vaults/vaultname"
    }

Couldnt find the above setting in official terraform doc but I did read up here: https://github.com/whiskeyjay/terraform-provider-azurerm/blob/3ff0c564e31e541844af381eb495e0346f82bfd6/website/docs/r/virtual_machine.html.markdown

**Comment by raghavanr** [comment]
have u provide key_encryption_key block as below:

key_encryption_key {
		key_url = "${azurerm_key_vault_key.vaultkey.id}"
		source_vault_id = "${azurerm_key_vault.zwpvault.id}"
}

**Comment by shahbhavya85** [comment]
@raghavanr I only provided disk_encryption_key block. Do I need to provide key_encryption_key block as well?

**Comment by raghavanr** [comment]
yes...@shahbhavya85 you need to provide both blocks for enabling encryption...

**Comment by tombuildsstuff** [comment]
hey @shahbhavya85 

Thanks for opening this issue :)

There's two steps to creating an encrypted VM - creating an Encrypted (Managed) Disk and then attaching this to the VM; at this point in time it's only possible to create an Encrypted (Managed) Disk natively in Terraform, whilst support for attaching this to a VM is on the roadmap.

Support for this had previously been contributed (as you've seen) but was waiting on native support for the Key Vault Secret resource (which is now natively supported) - as such it should be possible to add support for attaching encrypted disks in the near future (and as mentioned above, it's on the roadmap). In the interim you can achieve this using an ARM Template and [the `azurerm_template_deployment` resource](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html) to deploy an Encrypted VM - which can be [imported](https://www.terraform.io/docs/import/usage.html) into [Terraform's native `azurerm_virtual_machine` resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html) when it's supported natively.

Rather than tracking this in multiple issues - I'm going to close this issue in favour of #439 where we'll post updates about this (and I'd recommend subscribing too, for more information on when this is available).

Thanks!
