### ISSUE TITLE
identity_ids in azurerm_application_gateway tries to apply on every apply

### ISSUE THREAD

**Issue by krknopp** [terraform-providers/terraform-provider-azurerm#6456]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
✗ terraform -v
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.5.0
```

### Affected Resource(s)

* `azurerm_application_gateway`

### Terraform Configuration Files

Excerpt from my module
```
resource "azurerm_application_gateway" "main" {
  name                = var.name
  resource_group_name = var.resource_group_name
  location            = var.resource_group_location
  enable_http2        = var.enable_http2

  autoscale_configuration {
    max_capacity = var.autoscale_max
    min_capacity = var.autoscale_min
  }

  sku {
    name     = var.sku_name
    tier     = var.sku_tier
    capacity = var.sku_capacity
  }

  gateway_ip_configuration {
    name      = "appGatewayIpConfig"
    subnet_id = var.subnet_id
  }

  frontend_port {
    name = "port_443"
    port = 443 
  }

  frontend_port {
    name = "port_80"
    port = 80
  }

  frontend_ip_configuration {
    #name                 = local.frontend_ip_configuration_name
    name                 = "appGwPublicFrontendIp"
    public_ip_address_id = var.public_ip_id
  }

  identity {
    type                 = "UserAssigned"
    identity_ids         = ["/subscriptions/<sub-id>/resourceGroups/rg-web-appsvcs/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity_name>"]
  }

  dynamic "ssl_certificate" {
    for_each = var.ssl_certificates
    content {
      name                = ssl_certificate.value.name
      key_vault_secret_id = ssl_certificate.value.key_vault_secret_id
    }
  }
```
### Expected Behavior

if the `identity_ids` list of strings doesn't change, terraform shouldn't need to apply changes

### Actual Behavior

terraform continually want to apply the `identity_ids` setting every time.

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

I normally have the identity_ids data populated from a variable, but put it directly in the module for the purpose of proving out my module.

### References

https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html

**Comment by ArcturusZhang** [comment]
Hi @krknopp thanks for this issue. 
This issue should be a duplicate of #6444 
The root cause of this issue is that originally the MSI resource was created with the segment `resourcegroups` rather than `resourceGroups` in its ID, and so does the identity ID returned by application gateway. Therefore when you are hard coding an identity ID of `/subscriptions/<sub-id>/resourceGroups/rg-web-appsvcs/providers/Microsoft.ManagedIdentity/userAssignedIdentities/<identity_name>`, the application gateway will change it to `resourcegroups` to align the ID pattern of a MSI.
To solve this, I suggest you use a data source to retrieve the user assigned identity, and reference by its ID in the application gateway. In this way, this issue will go away. Or just changing the `resourceGroups` to `resourcegroups` in the hard-coded ID would also work.

**Comment by krknopp** [comment]
that was the ticket.  thank you.  Seems to be relatively common on the Azure stuff.  I should have caught that.
