### ISSUE TITLE
Support for "endpoint" option in Dev Spaces controller resource

### ISSUE THREAD

**Issue by Ant59** [terraform-providers/terraform-provider-azurerm#6469]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I'd like to deploy a Dev Spaces controller resource using Terraform with a private endpoint, but the controller resource doesn't allow this option.

### New or Affected Resource(s)

* azurerm_devspace_controller

### Potential Terraform Configuration

```hcl
resource "azurerm_devspace_controller" "dsc" {
  name                = "devspaces"
  location            = var.location
  resource_group_name = var.resource_group_name

  sku_name = "S1"

  endpoint = "private"

  target_container_host_resource_id        = azurerm_kubernetes_cluster.k8s.id
  target_container_host_credentials_base64 = base64encode(azurerm_kubernetes_cluster.k8s.kube_config_raw)
}
```

### References

* https://docs.microsoft.com/en-us/azure/dev-spaces/configure-networking#using-different-endpoint-options

**Comment by tombuildsstuff** [comment]
hi @Ant59 

Thanks for opening this issue.

Unfortunately the Service Team have opted to hard-deprecate this service, in such a manner that it's no longer possible to provision new DevSpace Controllers, due to this service being deprecated in 2023. Since it's not possible to provision new instances, unfortunately this means that we're unable to add a test to confirm this functionality works, since we can't run it - meaning that it's not possible to add support for this new field due to the Breaking API change here.

The `azurerm_devspace_controller` resource will continue to be available until the 3.0 release, which allows existing DevSpace Controllers to continue to be managed via Terraform - this resource will be deprecated in the next version of the Azure Provider (v2.42) and ultimately removed in version 3.0.

Whilst I'd like to thank you for opening this issue - unfortunately it's not possible to add support for this feature at this time and as such I'm going to close this issue for the moment.

Thanks!
