### ISSUE TITLE
Error: "microsoft.cache/redis is not a supported platform metric namespace"

### ISSUE THREAD

**Issue by casmeijer** [terraform-providers/terraform-provider-azurerm#6498]
In my current Azure release pipeline I get the following error:
"Code": "BadRequest",
  "Message": "{\"code\":\"BadRequest\",\"message\":\"microsoft.cache/redis is not a supported platform metric namespace, supported ones are 
<-Snip->
With a long list of supported names which is indeed missing "Microsoft.Cache/Redis".
This is strange because 

- according to the (Microsoft) site on [Supported Metrics](https://docs.microsoft.com/en-us/azure/azure-monitor/platform/metrics-supported#microsoftcacheredis) Microsoft.Cache/Redis **is** a supported namespace 
- this morning (4/16/2020, 11:08:26 AM CET) the same step in the same pipeline with the same ARM template **did** work .

Did somebody remove or renamed this namespace with updating the documentation?
If so What is the new name?

**Comment by tombuildsstuff** [comment]
hi @casmeijer 

Thanks for opening this issue.

Taking a look through this sounds like a change in the API at Microsoft's end - since it's possible to list other types of Monitoring resources, unfortunately this isn't something that's changed/can be fixed in Terraform. Instead I'm going to suggest opening an issue with Microsoft Support where they should be able to take a look into this - but as this isn't something that can be fixed in Terraform (since this is an Azure API issue) as such I'm going to close this issue for the moment.

Thanks!

**Comment by casmeijer** [comment]
Thanks Tom, 
Sorry for bothering you guy with this issue. I thought I saw similar issues so I hoped to get help here. 
I'll try and find the proper entry in Microsoft to get someone running over there.
Thanks again and sorry for the inconvenience
