### ISSUE TITLE
Enable Terraform to create a VPN-VPN connection

### ISSUE THREAD

**Issue by wawrzek** [terraform-providers/terraform-provider-azurerm#650]
I try to find to way to use Terraform to create VPN-VPN connection between Azure VNets in two different regions. Based on Azure docs (https://docs.microsoft.com/en-us/azure/vpn-gateway/vpn-gateway-howto-vnet-vnet-resource-manager-portal).
It requires 

1. GatewaySubnet (it seems to be normal subnet just names 'GatewaySubnet')
2. virtual network gateway. I don't see it in Terraform, but it's in GoSDK (https://godoc.org/github.com/Azure/azure-sdk-for-go/arm/network#VirtualNetworkGateway).

In Terraform I see only LocalNetworkGateway, which is different Azure object. Please add VirtualNetworkGateway (with VNet-VNet connection).

**Comment by tombuildsstuff** [comment]
Hey @wawrzek 

Thanks for opening this issue

Support for Virtual Network Gateways has previously been requested in #17 and has been implemented in #133. We've been blocked on an issue with the Azure API which has apparently been resolved over the Christmas break - and I'm planning on taking a look at this in the next few weeks.

In order to be able to keep updates for this in a single place - I'm going to close this issue in favour of #17 (where we'll post updates for this)

Thanks!
