### ISSUE TITLE
Adjust to Module compatibility and semantic versioning spec

### ISSUE THREAD

**Issue by fabianofranz** [terraform-providers/terraform-provider-azurerm#6507]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

* terraform version not applicable
* terraform-provider-azurerm v2.0.0 and higher

### Affected Resource(s)

* not applicable

### Terraform Configuration Files

* not applicable

### Background

The Terraform provider for Azure Resource Manager uses [Go modules](https://github.com/golang/go/wiki/Modules) and the current release stream version is **v2**. It must comply with the specification of "Releasing Modules for v2 or higher" available in the Modules documentation and enforced since the most recent versions of Go. Quoting the specification:

> A package that has opted in to modules *must* include the major version in the import path to import any v2+ modules

> To preserve import compatibility, the go command requires that modules with major version v2 or later use a module path with that major version as the final element. For example, version v2.0.0 of *example.com/m* must instead use module path *example.com/m/v2*.

https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher
 
I consider this a pretty **high severity** issue since not doing so **prevents any other Go project also using Go Modules** to properly require `terraform-providers/terraform-provider-azurerm` on versions higher than v2.0.0 as a dependency, resulting in errors like:

```
invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

Worth to mention that the `+incompatible` exception on the spec targets *non-modules* packages so it's **not a valid workaround** in this case.

### Steps to Reproduce

1. Under a project making use of Go modules, run `go get` targeting any v2 version of the terraform-provider-azurerm:

```bash
$ go get github.com/terraform-providers/terraform-provider-azurerm@v2.3.0
go: finding github.com v2.3.0
go: finding github.com/terraform-providers/terraform-provider-azurerm v2.3.0
go: finding github.com/terraform-providers v2.3.0
go: finding github.com/terraform-providers/terraform-provider-azurerm v2.3.0
go get github.com/terraform-providers/terraform-provider-azurerm@v2.3.0: github.com/terraform-providers/terraform-provider-azurerm@v2.3.0: invalid version: module contains a go.mod file, so major version must be compatible: should be v0 or v1, not v2
```

### Solution

* Patch the `go.mod` file to declare the `module` as `github.com/terraform-providers/terraform-provider-azurerm/v2` as [per the specs](https://github.com/golang/go/wiki/Modules#semantic-import-versioning).
* Adjust all internal imports.

### References

* https://github.com/golang/go/wiki/Modules#semantic-import-versioning
* https://golang.org/cmd/go/#hdr-Module_compatibility_and_semantic_versioning
* https://github.com/golang/go/wiki/Modules#releasing-modules-v2-or-higher

**Comment by tombuildsstuff** [comment]
hi @fabianofranz 

Thanks for opening this issue.

This repository hosts a plugin officially supported only for use with Terraform - as such the semantic versioning applied to this repository reflects the semantic versioning for downstream users of Terraform (e.g. Terraform users via HCL) - rather than a traditional Go Module. In order to reflect this, we've been gradually moving code into the `internal` package (and we'll likely end up moving the remaining code at some point in the future).

Whilst we only support using this Provider via Terraform Core - you should also be able to make use of this plugin via the same underlying mechanism, [hashicorp/go-plugin](https://github.com/hashicorp/go-plugin).

Alternatively you're welcome to include/make use of files from this Provider in your repository - however this use-case is unsupported and where this provider moves fairly quickly, we make no guarantees against drastically changing things without any sort of warning or notification.

As we don't officially support using the Provider in this fashion - unfortunately we have no plans to change how we version this module from using semantic versioning based on Terraform/HCL usage to based on the Go Module interpretation - and as such whilst I'd like to thank you for reaching out, I'm going to close this issue for the moment.

Thanks!
