### ISSUE TITLE
Azure Private endpoint AKS cluster recreation issue

### ISSUE THREAD

**Issue by msivarami** [terraform-providers/terraform-provider-azurerm#6508]
When i tried to create private endpoint AKS cluster by enabling "private_link_enabled = true".Initially, AKS cluster created without any issue.After creation,when i do "terraform plan" instead of showing zero resources to create and update.It is showing 1 create , 1 update and 1 destroy.It is forcefully asking to set "windows_profile" property.If i set this property it is working as expected.But windows_profile is optional property and mine is linux cluster node.I'm really not sure why i need to set forcefully during AKS cluster creation . Please let me know , if anyone come across this situation.
AzureRm version: 2.5.0
AKS verison: 1.15.10

**Comment by tombuildsstuff** [comment]
hi @msivarami 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by msivarami** [comment]
This is a bug in the provider itself.
