### ISSUE TITLE
Logic Apps : Need sample with parameters, how to use

### ISSUE THREAD

**Issue by GregoryFrance** [terraform-providers/terraform-provider-azurerm#6513]
Hello,

I'm starting deploying Logic Apps Resources using Terraform.

It's working fine but I don't understand how to set parameters, how it is working ?

Can't find any sample. Documentation says that each parameter should be is the shema JSON...

Anyone have a sample ?

**My goal:**

- Add string parameters

- Set a default value for each parameters.

Thanks for any help or idea !

**Comment by tombuildsstuff** [comment]
hi @GregoryFrance 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
