### ISSUE TITLE
Import requires sqlVirtualMachines not SqlVirtualMachines

### ISSUE THREAD

**Issue by haodeon** [terraform-providers/terraform-provider-azurerm#6533]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.6.0

### Affected Resource(s)

* `azurerm_mssql_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_mssql_virtual_machine" "sql" {
  for_each           = data.terraform_remote_state.xxx.outputs.sql
  virtual_machine_id = each.value["id"]
  sql_license_type   = "PAYG"
}
```

`terraform import 'azurerm_mssql_virtual_machine.sql["abcdef06"]' /subscriptions/eeeeeeee-3333-4444-bbbb-cccccccccccc/resourceGroups/xxxxxxxxxxxxxx/providers/Microsoft.SqlVirtualMachine/SqlVirtualMachines/abcdef06`

### Expected Behavior

Terraform should import the resource successfully. The resource ID specified was copied from the Azure portal.

### Actual Behavior

Terraform fails to import the resource. It gives error message ```ID was missing the `sqlVirtualMachines` element```

It appears the provider is checking for case sensitive sqlVirtualMachines. While the resource ID uses SqlVirtualMachines. Note, sqlVirtualMachines appears to be the normal naming convention in Azure for most resources. It isn't clear why SqlVirtualMachines was used instead.

Also if I change the resource ID to sqlVirtualMachines the import works fine anyway. Despite it being a different case to the real ID.

### Steps to Reproduce

1. Write a simple terraform config defining azurerm_mssql_virtual_machine.
1. `terraform import <resource> <resource_id>`

### References

* #0000

**Comment by neil-yechenwei** [comment]
@haodeon , Thanks for raising the issue. For this issue, I think you should get resource id by the output of creation or data source like below this.
![image](https://user-images.githubusercontent.com/19754191/79823437-6933ff00-83c6-11ea-9b23-1be0d612ee7e.png)

**Comment by haodeon** [comment]
Hi @neil-yechenwei thank you for responding.

I don't believe your suggestion is the right approach for two reasons.

1. It would lead to a chicken egg scenario. How would you get the resource ID from terraform before terraform created/managed the resource? The issue I am describing here is the import command fails.

2. The resource ID is clearly displayed in the portal. The resource ID terraform is outputting is not the actual resource ID. I have checked with Azure resource explorer and the ID in the portal is the correct format/capitalisation.

**Comment by neil-yechenwei** [comment]
@haodeon , seems it's a azure portal issue not terraform issue. Terraform directly returns resource id without conversion. After checked rest api doc (https://docs.microsoft.com/en-us/rest/api/sqlvm/sqlvirtualmachines/createorupdate), seems the correct resource ID is "Microsoft.SqlVirtualMachine/sqlVirtualMachines"

**Comment by haodeon** [comment]
@neil-yechenwei 

In portal it is "Microsoft.SqlVirtualMachine/SqlVirtualMachines"

In Azure Resource Explorer it is

```
    {
      "id": "/subscriptions/zzzzzzzz-1111-2222-3333-vvvvvvvvvvvv/resourceGroups/xxxxxxxxxx/providers/Microsoft.SqlVirtualMachine/SqlVirtualMachines/abcdef05",
      "name": "abcdef05",
      "type": "Microsoft.SqlVirtualMachine/SqlVirtualMachines",
      "location": "nnnnnnnnn",
      "tags": {}
    },
```

Can you please verify if two tools are wrong then? If they are wrong then, we can close this issue. However, I think most users would rely on these tools to get the resource ID when importing a resource that was created outside of terraform.

**Comment by tombuildsstuff** [comment]
hey @haodeon 

Thanks for opening this issue.

Resource ID's in Azure are an interesting problem - whilst some parts of Azure treat them as case-insensitive - other parts of Azure (and associated downstream tooling) doesn't - as such we're forced to treat them as case sensitive.

In order to clarify the expected format for importing resources, we show examples in the `import` documentation (for example [here's the import section for the `azurerm_mssql_virtual_machine` resource](https://www.terraform.io/docs/providers/azurerm/r/mssql_virtual_machine.html#import)). We're also gradually working through updating the import functions within the Azure Provider to explicitly call out the missing segments where required.

Unfortunately as mentioned above, we're forced to treat Resource ID's as case sensitive - as such this isn't something we plan to fix in Terraform; but as you've mentioned, you should be able to update the casing on this URI from `SqlVirtualMachines` to `sqlVirtualMachines` - which is the format [defined in the API](https://github.com/Azure/azure-rest-api-specs/blob/0d2db432215329409f038b6bcf01e646b2545130/specification/sqlvirtualmachine/resource-manager/Microsoft.SqlVirtualMachine/preview/2017-03-01-preview/sqlvm.json#L617) at which point Terraform should be able to import this resource.

Since this should be fixed by updating the casing for the `SqlVirtualMachines` segment to be `sqlVirtualMachines` I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look

Thanks!
