### ISSUE TITLE
Status Code:200; Disk Tags are update failure

### ISSUE THREAD

**Issue by RobinAggarwal** [terraform-providers/terraform-provider-azurerm#6542]
Terraform Version:
AzureRM Provider Version: 

Affected Resources:
azurerm_managed_disk

### Expected Behavior
Tags are updated in variable files; picked up well in plan phase; apply should make change to tags on disks.

### Actual Behavior
Updating tags failed always with following error.

Error: Error waiting for Deallocation of Virtual Machine "WB02-CR-EW-T2" (Resource Group "rg_eastus2_test_02"): Future#WaitForCompletion: context has been cancelled: StatusCode=200 -- Original Error: context deadline exceeded

  on ..\..\..\modules\managed_disk\main.tf line 6, in resource "azurerm_managed_disk" "disk":
   6: resource "azurerm_managed_disk" "disk" {

**Comment by tombuildsstuff** [comment]
hi @RobinAggarwal 

We've shipped in a fix for this in a recent version of the Azure Provider - as such you should be able to fix this by upgrading to the latest version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "= 2.6.0"
}
```

Since this should be fixed by updating the version of the Azure Provider being used, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
