### ISSUE TITLE
Error: no schema available for module.backup_policy.azurerm_recovery_services_protection_policy_vm.application

### ISSUE THREAD

**Issue by revchris** [terraform-providers/terraform-provider-azurerm#6547]
Upgrading from AzureRM 1.44.0 to 2.5.0, I am getting the following error on the plan: 

> Error: no schema available for module.backup_policy.azurerm_recovery_services_protection_policy_vm.application while reading state; this is a bug in Terraform and should be reported

Not sure if just renaming "azurerm_recovery_services_protection_policy_vm" to "azurerm_backup_policy_vm" in the state file will work or not.

**Comment by tombuildsstuff** [comment]
hey @revchris 

Thanks for opening this issue.

Version 2.0 of the Azure Provider includes several resources which have been renamed (which are detailed [in the upgrade guide](https://www.terraform.io/docs/providers/azurerm/guides/2.0-upgrade-guide.html) - however it appears the link to [the migration guide](https://www.terraform.io/docs/providers/azurerm/guides/migrating-between-renamed-resources.html) has gotten removed from that), apologies about this.

However you should be able to follow the migration guide to migrate from the old resource to the new one - essentially that's removing the old one from the state (running 1.x) and then re-importing it using the newer resource (using a 1.x or later release where that's available) - which should allow you to migrate from one resource to the other here, and then use v2.0 or later of the Azure Provider.

Since this should be fixed by removing the resources from the state/re-importing them - I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look

Thanks!
