### ISSUE TITLE
Cannot Refresh State After Updating to AzureRM v1.40 or v2.0

### ISSUE THREAD

**Issue by CodingAnarchy** [terraform-providers/terraform-provider-azurerm#6585]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform Version: 0.12.24
AzureRM Provider Version: 1.40.0 - 2.6.0

### Affected Resource(s)

* `azurerm_resource_group`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

Terraform refreshes state and plans the requested infrastructure changes.

### Actual Behavior

```
azurerm_resource_group.[resource_name]: Refreshing state... [id=https://portal.azure.com/#[redacted]/resource/subscriptions/[subscription id]/resourceGroups/[name]]

Error: ID contained more segments than required: "https://portal.azure.com/#[redacted]/resource/subscriptions/[subscription id]/resourceGroups/[name]"
```

### Steps to Reproduce

1. Updated from 1.39.0 of `azurerm` to 2.6.0 (or any version later than 1.39.0).
2. `terraform plan`

**Comment by CodingAnarchy** [comment]
Tracking this down, I have found that `func ParseAzureResourceID` followed by `func (id *ResourceID) ValidateNoEmptySegments` used by 1.40+ does not work for the FQDN format of the resource ID that was used when the resource group was originally created/imported in Terraform.

`ParseAzureResourceID` will need to be updated to handle that by stripping any `https://portal.azure.com/#@something.onmicrosoft.com/resource` prefix in the resource ID at the start. I'm not all that familiar with golang, but I could try to give it a shot if no one else will.

**Comment by tombuildsstuff** [comment]
hi @CodingAnarchy 

Thanks for opening this issue.

There's subtle differences between the Resource ID's available in Azure Resource Manager and the Azure Portal - where the Portal URI is (generally, but not always) in the format `{azure-resource-id}/overview`.

Terraform makes use of the ID from the Resource Manager API's to ensure this is consistent since these won't change over time - by contrast URI's in the Azure Portal (as you've mentioned in #6585) are subject to change whenever the Portal Team roll out a change.

Where Azure Resource Manager ID's are nested - for example a Resource Group may contain a Virtual Machine which may contain an extension - we're gradually introducing validation to ensure that the correct Resource ID is used for the correct resource - to ensure that a user cannot specify a Virtual Machine ID for a Resource Group, or a VM Extension ID for a VM, etc) - which is the purpose of the `ValidateNoEmptySegments` method.

Whilst the Azure Provider may have (unintentionally) worked with Resource ID's from the Azure Portal historically - this was a bug - and unfortunately isn't something we support/intended to support - and as such whilst I'd like to thank you for the contribution I'm going to close that PR & issue for the moment.

Unfortunately fixing this in your Statefile may be a little messy - you should be able to either:

a) using `terraform state rm [resource].[label]` then `terraform import` to import this into the statefile using the correct Resource ID (we show this on the "import" section of each resource: https://www.terraform.io/docs/providers/azurerm/r/resource_group.html#import)
b) manually update the ID's in the Statefile (either by hand, or using something like "sed" to manually remove the "https://portal.azure.com/#@something.onmicrosoft.com/resource" prefix from the ID of each resource

At which point this should use the ID format `/subscriptions/{id}/resourceGroups/{name}` which'll allow you to upgrade to later versions of the Azure Provider.

As mentioned above we're gradually working through adding this validation to all resources with the intention of checking that the Resource ID's are valid - and as such whilst it's unfortunate this bug existed, I believe this issue should be fixed for other resources over time.

Since this should be fixed by updating the ID's of the resources I'm going to close this issue for the moment - however please let us know if you're still having issues after doing so and we'll take another look

Thanks!

**Comment by CodingAnarchy** [comment]
@tombuildsstuff Understanding that this deprecation is the case, I would suggest that it is better to have the provider update that resource ID to the new API  in some fashion for the user rather than just subtly break updating of resources. My PR wouldn't fix that, and I wouldn't know enough Golang to add it in, but I think it should be considered.

I spent quite a lot of time tracking this issue down, and we have rather strong reasons to have a policy not to use any `terraform state ...` manipulation to avoid unintentional mistakes. Any manual modification of the Terraform state like that can definitely break things in ways that aren't immediately obvious. I would rather others did not have to repeat this sequence of events.

I've been able to get approval to make this change in this very selective circumstance, but I think these concerns should still be raised for consideration.
