### ISSUE TITLE
In-line NSG rules are not deleted if commented out

### ISSUE THREAD

**Issue by mbrijun** [terraform-providers/terraform-provider-azurerm#6623]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
provider.azurerm v2.7.0
```

### Affected Resource(s)

`azurerm_network_security_group`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

BEFORE
```
# Create Network Security Group and rule
resource "azurerm_network_security_group" "nsg" {
  name                = "myTFNSG"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  security_rule {
    name                       = "SSH"
    priority                   = 1001
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "22"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}
```

AFTER
```
# Create Network Security Group and rule
resource "azurerm_network_security_group" "nsg" {
  name                = "myTFNSG"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
}
```

### Expected Behavior

With the in-line NSG rule removed, "terraform apply" should have removed the previously created rule.

### Actual Behavior

The rule was not removed.

```
>terraform apply

azurerm_resource_group.rg: Refreshing state... [id=/subscriptions/6fb1c9f3-d6d9-4e63-910a-a0a4eb6cd23e/resourceGroups/myTFResourceGroup]
azurerm_virtual_network.vnet: Refreshing state... [id=/subscriptions/6fb1c9f3-d6d9-4e63-910a-a0a4eb6cd23e/resourceGroups/myTFResourceGroup/providers/Microsoft.Network/virtualNetworks/myTFVnet]
azurerm_network_security_group.nsg: Refreshing state... [id=/subscriptions/6fb1c9f3-d6d9-4e63-910a-a0a4eb6cd23e/resourceGroups/myTFResourceGroup/providers/Microsoft.Network/networkSecurityGroups/myTFNSG]
azurerm_subnet.subnet: Refreshing state... [id=/subscriptions/6fb1c9f3-d6d9-4e63-910a-a0a4eb6cd23e/resourceGroups/myTFResourceGroup/providers/Microsoft.Network/virtualNetworks/myTFVnet/subnets/myTFSubnet]

Apply complete! Resources: 0 added, 0 changed, 0 destroyed.

```
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by magodo** [comment]
@mbrijun Thank you for submitting this issue!
The short answer is: rather than deleting the snippet of inlined snippet of NSR, you have to explicitly  specify it as an empty slice like below:

```hcl
resource "azurerm_network_security_group" "nsg" {
  name                = "myTFNSG"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name

  security_rule = []
}
```

The complete answer is: to support both inline and standalone setting NSR inside an NSG (but not mixed, of course). We set the `security_rule` as `Optional+Computed` (also `ConfigMode: schema.SchemaConfigModeAttr`). This means if the user chooses to create NSR standalone, then when applying the NSG, the NSG resource will take whatever NSR as is and will not show any difference (as long as you didn't specify NSR inline). This is what actually happening in your case.
The `O+C` actually respect `O` first, meaning if you explicitly tell terraform to make the NSR empty, it will do it as you wish. That's why you need to explicitly specify an empty list in order to remove the NSR.

**Comment by mbrijun** [comment]
Thank you so much @magodo !
