### ISSUE TITLE
data.terraform_remote_state.remote does not have attribute outputs value

### ISSUE THREAD

**Issue by roshanp85** [terraform-providers/terraform-provider-azurerm#6632]
I'm using the below code to try and get the subnet id, which I need to utilise to deploy a virtual machine. But due to the reason, I need to keep the states isolated, I am using the **data.terraform_remote_state.remote** resource.

data "terraform_remote_state" "spi" {
  backend = "azurerm"

  config {
    storage_account_name = "${var.sa_name}"
    container_name       = "${var.sa_container_name}"
    key                  = "remote.tfstate"
    access_key           = ""
  }
}

remote.tfstate does contain the output variable: 

"outputs": {
                "project_subnet_id": {
                    "sensitive": false,
                    "type": "string",
                    "value": "valueexistis"
                }
            },

But I'm consistently getting the error : Resource 'data.terraform_remote_state.spi' does not have attribute 'outputs.project_subnet_id' for variable 'data.terraform_remote_state.spi.outputs.project_subnet_id'

I also tried to use directly the state value for subnet, and got the same issue: 

Resource 'data.terraform_remote_state.spi' does not have attribute 'azurerm_subnet.project_subnet.id' for variable 'data.terraform_remote_state.spi.azurerm_subnet.project_subnet.id'

**Comment by tombuildsstuff** [comment]
hi @roshanp85 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
