### ISSUE TITLE
Application Insight created by AzureRM not working

### ISSUE THREAD

**Issue by masonyc** [terraform-providers/terraform-provider-azurerm#6649]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform version: 0.12.17, 0.12.19, 0.12.24 
AzureRm version : 1.44.0

### Affected Resource(s)

* azurerm_application_insights
* azurerm_log_analytics_workspace
* azurerm_log_analytics_solution

### Expected Behavior

Application Insight should be able to log messages from Azure Function App/other services

### Actual Behavior

Nothing logged after I added the instrument key from Application Insight to Azure Function App

I tried to create an application insight manually (by portal without using Terraform) ,  and it can log the messages. 

### Steps to Reproduce
provider "azurerm" {
  version         = "~>1.44.0"
  subscription_id = var.subscription_id
}

provider "azuread" {

}

terraform {
  backend "azurerm" {

  }
}

resource "azurerm_resource_group" "rg" {
  name     = "PocAI"
  location = "australiaeast"
}

resource "azurerm_application_insights" "ai" {
  name                = "applicationInsight"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.rg_name
  application_type    = "Web"
  sampling_percentage = 0
}

resource "azurerm_log_analytics_workspace" "logworkspace" {
  name                = "logsapce"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.rg_name
  sku                 = "PerGB2018"
}

resource "azurerm_log_analytics_solution" "logsolution" {
  solution_name         = "ContainerInsights"
  location              = var.location
  resource_group_name   = azurerm_resource_group.rg.rg_name
  workspace_resource_id = azurerm_log_analytics_workspace.logworkspace.id
  workspace_name        = azurerm_log_analytics_workspace.logworkspace.name
  plan {
    publisher = "Microsoft"
    product   = "OMSGallery/ContainerInsights"
  }
}

**Comment by magodo** [comment]
@masonyc Thank you for submitting this issue!
I assume you have some existing `function_app` in azure, you want to create a `application_insights` via terraform and add that `function_app` into it. Then I think first you only need to create `resource_group` and `application_insights` in terraform (as analytics workspace/solution are not necessary for this use case):

```hcl
provider "azurerm" {
  version = "~>1.44.0"
  subscription_id = var.subscription_id
}

variable "location" {
  type    = string
  default = "australiaeast
}

resource "azurerm_resource_group" "rg" {
  name     = "PocAI"
  location = var.location
}

resource "azurerm_application_insights" "ai" {
  name                = "applicationInsight"
  location            = var.location
  resource_group_name = azurerm_resource_group.rg.name
  application_type    = "web"
  sampling_percentage = 0
}
```
One possible issue I find from config is that if you set `sampling_percentage` to `0`, then there will be no telemetry be picked by `application_insights`. Maybe you shall adjust it a bit.

After changing it to 100 (or remove it as 100 is the default value), I can see the `function_app` show up in the "Application Map" in `application_insghts` interface from portal.

Also wanna confirm the step you use to add `function_app` to `application_insights`. The step is like:

- Go to your function app
- Click on Function App Settings on the bottom left
- Under Application Settings click on "New Application Setting"
- Set the `name` to `APPINSIGHTS_INSTRUMENTATIONKEY` and set the value to the instrumentation key of `application_insights`
- Click OK and save

Normally you need to wait several seconds to minutes for the config take effect, then depending on your sampling rate, you shall see some telemetry from your `application_insights` interface.

BTW, since terraform azurerm provider v2.7.0, you can directly create a `function_app` with instrumentation key set so as to be added to `application_insights`. You may want to have a [look](https://www.terraform.io/docs/providers/azurerm/r/function_app.html#app_settings).

**Comment by masonyc** [comment]
@magodo Thanks for the quick reply. I can confirm it does work after I changed the sampling rate.

We have it like that for 4 months and it suddenly got broken from last week. My next question is any ideas why it stop working?

**Comment by magodo** [comment]
Good news!
For the reason why it got broken from last week, one possibility is that after the first provision for this resource via terraform, somehow the sampling rate got adjusted outside of terraform. Then I assume you have triggered another apply on last week, which changes the sampling rate to 0. That's just some hypothetic case I can imagine.
I scanned through the code and didn't see any change will cause this breaking change.

**Comment by masonyc** [comment]
That makes sense. Thank you for your help! @magodo
