### ISSUE TITLE
azurerm_storage_account :  how to Enable Identity-based access for file shares with AAD DS

### ISSUE THREAD

**Issue by Kumoservices** [terraform-providers/terraform-provider-azurerm#6687]
Hello

I cannot find how to enable Identity-based access for file shares with AAD DS i can see in the storage account azure console with terraform ?

is there a another ressource to use for enable this ?

Thanks for your help

**Comment by tombuildsstuff** [comment]
hi @Kumoservices 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
