### ISSUE TITLE
Subnet is not removed

### ISSUE THREAD

**Issue by JorgeFromPortugal** [terraform-providers/terraform-provider-azurerm#6715]
Terraform 0.12
azurerm 2.7.0

This works ok:
variable "vnetsubnets" {
  default = {
    Subnet1 = {
      name = "10.0.1.0_24"
      address_prefix = "10.0.1.0/24"
    }
  }
}
resource "azurerm_virtual_network" "bug"{
  resource_group_name           = "net-dev-rg-02-ne"
  location                      = "NorthEurope"
  name                          = "10.0.0.0_16"
  address_space                 = ["10.0.0.0/16"]

  dynamic "subnet" {
    for_each = var.vnetsubnets
    content {
      name            = subnet.value.name
      address_prefix  = subnet.value.address_prefix
    }
  }
}

Then when you execute this, the subnet is not removed:
variable "vnetsubnets" {
  default = {}
}
resource "azurerm_virtual_network" "bug"{
  resource_group_name           = "net-dev-rg-02-ne"
  location                      = "NorthEurope"
  name                          = "10.0.0.0_16"
  address_space                 = ["10.0.0.0/16"]

  dynamic "subnet" {
    for_each = var.vnetsubnets
    content {
      name            = subnet.value.name
      address_prefix  = subnet.value.address_prefix
    }
  }
}

Thanks
Jorge

**Comment by tombuildsstuff** [comment]
hi @JorgeFromPortugal 


Thanks for opening this issue - apologies for the delayed response here!

Both Azure and the Terraform Azure Provider allows Subnets to be specified in one of two ways:

1. Within the `azurerm_virtual_network` resource using the `subnets` block.
2. Using the separate `azurerm_subnet` resource

Since both use-cases are supported in Terraform, the `subnet` block within the `azurerm_virtual_network` resource is "Computed" - which means that if it's not specified we use the value provided by Azure, to account for this being managed by the separate resource (so that we don't for example, detect that these subnets should be deleted during a `terraform plan`).

As such, when defining subnets within the `azurerm_virtual_network` resource, rather than removing the `subnets` blocks (in which case we'll use the information from Azure) - you'll instead need to specify an empty array, for example:

```
resource "azurerm_resource_group" "netrg" {
  name     =  "example-rg"
  location =   "westeurope"
}

resource "azurerm_virtual_network" "vnet" {
  name                = "example-vnet"
  location            = azurerm_resource_group.netrg.location
  resource_group_name = azurerm_resource_group.netrg.name
  address_space       = ["10.0.0.0/8"]
  subnet = []
}
```

Would you be able to take a look and see if that works for you? Since this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by JorgeFromPortugal** [comment]
Hi Tom, thanks for your response!

I understand your explanation, but then in my case, I will have to use the separate azurerm_subnet Resource.
My configurations above were an example to demonstrate the issue I encountered.
What I have is a map of subnet data and I use the "dynamic subnet for_each content" to add or remove subnets.
Everything works fine except if I need to remove the last subnet using an empty map.

Thank you

**Comment by jmservianri** [comment]
Hi,

I'm having the same problem. I need to clear all subnets in a vnet but empty array is incompatible with dynamics blocks, so the unique alternative is using separated resources. I think that is more readable and clear using dynamics block instead of separated resources.

Thank you

**Comment by tombuildsstuff** [comment]
@jmservianri I'd suggest [opening a feature request in Terraform Core](https://github.com/hashicorp/terraform/issues) to allow "dynamic" lists of zero elements - since this is specific to when using dynamic blocks, rather than something specific to the Azure Provider
