### ISSUE TITLE
VM IP in DTL

### ISSUE THREAD

**Issue by matteodeg94** [terraform-providers/terraform-provider-azurerm#6735]
Terraform version
Terraform v0.12.24
Provider Azure v2.8.0

I am trying to create a VM in an Azure DevTest Lab using the resource `azurerm_dev_test_linux_virtual_machine` and then get its private IP address.

Unfortunately I have not been able to figure out how to get the private IP address of the NIC automatically created for the VM. Even though I can see the assigned IP from the Azure web portal opening the VM panel inside the DevTest Lab.

Below you can see the code that I am using to deploy the VM:
```
resource "azurerm_dev_test_linux_virtual_machine" "vmtest" {
 name = "TestVM"
 lab_name = var.azure_devtestlab_name
 resource_group_name = var.azure_resource_group
 location = var.azure_location
 size = "Standard_A1_v2"
 storage_type = "Standard"
 username = "adminuser"
 password = "Password"
 lab_virtual_network_id = var.azure_network_id
 lab_subnet_name = var.azure_subnet_name
 disallow_public_ip_address = true
 notes = "Managed by Terraform"
 gallery_image_reference {
    publisher = "RedHat"
    offer     = "RHEL"
    sku       = "7-LVM"
    version   = "latest"
  }
}
```
I had to set `disallow_public_ip_address = true` because of the limitations imposed by my organisation.

Since in the Azure web portal VM overview I am able to see the IP address under the section "IP address or FQDN", I was expecting to find the IP address in the exported attribute 'fqdn' of the Terraform resource (`azurerm_dev_test_linux_virtual_machine`), but it is empty. Apparently it gets a value only when a public IP address is used and hence a FQDN is assigned.

Do you have any idea about how to obtain the private IP address from Terraform? I will then need it for the future script steps.

**Comment by tombuildsstuff** [comment]
hi @matteodeg94 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
