### ISSUE TITLE
Cannot set app service to log to blob storage most likely because of SAS token

### ISSUE THREAD

**Issue by TamasSzerb** [terraform-providers/terraform-provider-azurerm#6755]
Hello,

With MS team, we investigated the MS Support Case # 120040622002997 when I set the app service to log to blob storage with terrafrom, it results authorization issues (reported by storage team). We diffed it with the same settings manually on the portal.azure.com, and we discovered the followings on https://resources.azure.com/ for the given app service: 

terraform sets (not working):
"sasUrl": "https://[REDACTED]/[REDACTED]-log/?sv=2018-11-09&sr=c&st=2020-03-31&se=2030-03-22&sp=racwdl&spr=https&sig=[REDACTED]",

portal sets (working):
"sasUrl": "https://[REDACTED]/[REDACTED]-log?sp=rwdl&st=2020-04-30T12:01:34Z&se=2220-04-30T12:01:34Z&sv=2019-10-10&sr=c&sig=[REDACTED]",

which suggests maybe that terraform obtains/generates invalid SAS token?

according to https://docs.microsoft.com/en-us/rest/api/storageservices/create-account-sas#specifying-account-sas-parameters SPEC ISO-8601 should be the format.

terraform version
Terraform v0.12.24
+ provider.archive v1.3.0
+ provider.azuread v0.8.0
+ provider.azurerm v2.6.0
+ provider.dns v2.2.0

resource "azurerm_app_service" "[REDACTED]" {
  name                  = "[REDACTED]"
  location              = azurerm_resource_group.[REDACTED].location
  https_only            = false
  resource_group_name   = azurerm_resource_group.[REDACTED].name
  app_service_plan_id   = azurerm_app_service_plan.[REDACTED].id

  site_config {
    default_documents = [ "index.html" ]
    dotnet_framework_version = "v4.0"
    scm_type                 = "None"
    always_on = true
    #windows_fx_version = "DOCKER|mcr.microsoft.com/dotnet/core/aspnet"
  }

  app_settings = {
    "WEBSITE_RUN_FROM_PACKAGE" = local.[REDACTED]-zip-url
  }
  logs {
    application_logs {
      azure_blob_storage {
        level = "Verbose" # Error, Warning, Information, Verbose and Off
        sas_url = local.[REDACTED]-log-url
        retention_in_days = "365"
      }
    }
    http_logs {
      #file_system {
      #  retention_in_days = "365"
      #  retention_in_mb = "100"
      #}
      azure_blob_storage {
        sas_url = local.[REDACTED]-log-url
        retention_in_days = "365"
      }
    }
  }

}

Cheers,

Tamas

**Comment by tombuildsstuff** [comment]
hey @TamasSzerb 

Thanks for opening this issue

Taking a look into this it appears that this is due to the App Service API's requiring a newer version of the SAS Token (2019-10-10, indicated via `sv` in the querystring) than we're currently using (2018-11-09).

Support for configuring that is being tracked [in this issue](https://github.com/terraform-providers/terraform-provider-azurerm/issues/6519) - rather than having multiple issues open tracking the same thing I hope you don't mind but I'm going to close this issue in favour of https://github.com/terraform-providers/terraform-provider-azurerm/issues/6519 - would you mind subscribing to that issue for updates?

Thanks!
