### ISSUE TITLE
custom_data forces VM recreation every time even if the data is the same

### ISSUE THREAD

**Issue by roeizavida** [terraform-providers/terraform-provider-azurerm#6756]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
```
Terraform v0.12.24
+ provider.azurerm v2.8.0
+ provider.external v1.2.0
+ provider.null v2.1.2
+ provider.random v2.2.1
+ provider.template v2.1.2
```

### Affected Resource(s)

* `azurerm_linux_virtual_machine`

### Terraform Configuration Files

```hcl
resource "azurerm_linux_virtual_machine" "vm" {
  name                         = var.name
  resource_group_name          = var.resource_group_name
  location                     = var.location
  size                         = var.size
  availability_set_id          = var.availability_set_id
  proximity_placement_group_id = var.proximity_placement_group_id

  network_interface_ids = [
    azurerm_network_interface.nic_0.id,
    azurerm_network_interface.nic_1.id,
    azurerm_network_interface.nic_2.id
  ]

  plan {
    name      = "bundle2"
    publisher = "paloaltonetworks"
    product   = "vmseries1"
  }

  source_image_reference {
    publisher = "paloaltonetworks"
    offer     = "vmseries1"
    sku       = "bundle2"
    version   = "9.0.4"
  }

  os_disk {
    name                 = "${var.name}-os"
    caching              = "ReadWrite"
    storage_account_type = "StandardSSD_LRS"
  }

  computer_name                   = var.name
  admin_username                  = var.admin_username
  admin_password                  = var.admin_password
  disable_password_authentication = false
  allow_extension_operations      = true

  admin_ssh_key {
      username   = var.admin_username
      public_key = var.public_key
  }

  custom_data = base64encode("storage-account=${data.azurerm_storage_account.bootstrap_storage_account.name},access-key=${data.azurerm_storage_account.bootstrap_storage_account.primary_access_key},file-share=${azurerm_storage_share.bootstrap_storage_share.name},share-directory=files")
}
```

### Expected Behavior

Terraform should check if `custom_data` base64 value was changed and mark the VM for redeployment only if it changed.

### Actual Behavior

Every `terraform apply`, the VM is marked for recreation even if the base64 value of `custom_data` is the same every time. When removing `custom_data` line, the VM is not recreated. 

### Steps to Reproduce

1. `terraform apply`

### References

Similar issue but this solution is not working although it was supposed to be fixed in version 2.0:
* [#1013](https://github.com/terraform-providers/terraform-provider-azurerm/issues/1013)

**Comment by asanCar** [comment]
It happens exactly the same for us, despite the `custom_data` property is not highlighted as the recreation cause.

Meanwhile we have added this block to the `azurerm_linux_virtual_machine` as a workarround: 
```
lifecycle {
    ignore_changes = [custom_data]
  }
```

**Comment by tombuildsstuff** [comment]
hi @roeizavida @asanCar 

Thanks for opening this issue.

The root-cause of this bug is an issue in Terraform Core where information from Data Sources isn't cached (and thus refreshed every time) - coupled with a limitation of the Azure API where the contents of the `custom_data` field aren't returned through the API - meaning that Terraform assumes this content has changed.

As @asanCar has mentioned it should be possible to use `ignore_changes` to workaround this in the interim (although that has issues where, for example, changes to the custom data are ignored). In Terraform Core there's two issues tracking this, the first [regarding Data Source Caching explicitly](https://github.com/hashicorp/terraform-plugin-sdk/issues/134) - and the other [for Data Resource Lifecycle Adjustments](https://github.com/hashicorp/terraform/issues/17034) (which is the current issue).

However since this is a bug in Terraform Core (and the Azure API doesn't return this information) unfortunately this isn't something we're able to fix in the Azure Provider at this time - and as such I'm going to close this issue [in favour of this issue in Terraform Core which should ultimately fix this](https://github.com/hashicorp/terraform/issues/17034) - would you mind subscribing to that issue for updates?

Thanks!
