### ISSUE TITLE
Invalid resource type azurerm_api_management_named_value

### ISSUE THREAD

**Issue by satyam9025** [terraform-providers/terraform-provider-azurerm#6765]
I am facing issue while using resource azurerm_api_management_named_value.

**Code**

> provider "azurerm" {
  version = "1.44"
} 

> resource "azurerm_api_management_named_value" "api_named_values" {
  name                = "${var.environment}-api-investments-logicapp"
  resource_group_name = var.api_management_resource_group
  api_management_name = var.api_management_name
  display_name        = "api-investments-logicapp"
  value               = "value"
  secret              = true
}

**Issue**

> Invalid resource type azurerm_api_management_named_value

> The provider provider.azurerm does not support resource type 
"azurerm_api_management_named_value".

I am very new in Terraform and Azurerm. Please help me to find out what did I wrong.

**Comment by tombuildsstuff** [comment]
hi @satyam9025 

Thanks for opening this issue.

Taking a look into this support for the `azurerm_api_management_named_value` resource was added in version v2.7.0 of the Azure Provider, however you're currently running v1.44.0 - you can upgrade to v2.7.0 by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=2.7.0"
}
```

.. which should solve this for you - would you be able to take a look and see if that works for you? Since this should be fixed by updating the Terraform Configuration I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
