### ISSUE TITLE
Support for HDInsight monitoring

### ISSUE THREAD

**Issue by kosinsky** [terraform-providers/terraform-provider-azurerm#6780]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

HDInsight clusters support [Azure Monitor](https://docs.microsoft.com/en-us/azure/hdinsight/hdinsight-hadoop-oms-log-analytics-tutorial) to monitoring logs.

It can be enabled or disable after cluster creation via extensions API including [Go]( https://godoc.org/github.com/Azure/azure-sdk-for-go/services/preview/hdinsight/mgmt/2018-06-01-preview/hdinsight#ExtensionsClient.EnableMonitoring)

### New or Affected Resource(s)

* azurerm_hdinsight_*_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_hdinsight_hadoop_cluster" "example" {
  name                = "example-hdicluster"
  resource_group_name = "${azurerm_resource_group.example.name}"
  location            = "${azurerm_resource_group.example.location}"
  cluster_version     = "3.6"
  tier                = "Standard"

  monitor {
    log_analytics_workspace_id = data.azurerm_log_analytics_workspace.example.workspace_id
    primary_key                = data.azurerm_log_analytics_workspace.example.primary_shared_key
  }

}
```

**Comment by ross-p-smith** [comment]
I have tested this as an update to the cluster and creating a brand new spark cluster and I get the following error. I am using HDInsight 4.0 Spark if that helps

Error: Error waiting for enabling monitor for  HDInsight Cluster "xx-02" (Resource Group "xxxx-rg-dev-02"): Code="InternalServerError" Message="ErrorCode: ScriptExecutionFailed; ErrorDescription: Execution of the following scripts failed :HDI_MONITORING_INSTALL_f906be"

  on dataanalytics.tf line 7, in resource "azurerm_hdinsight_spark_cluster" "hdi":
   7: resource "azurerm_hdinsight_spark_cluster" "hdi" {

**Comment by jackofallops** [comment]
Hi @ross-p-smith 

Thanks for the feedback on this issue.

That looks like it's an internal part of the HDInsight service, not something in Terraform's control?  

The API called by Terraform triggers processes in the service (rather than something Terraform actions directly), but their success/failure isn't governed by anything that Terraform can influence, just report on the feedback returned by the service.  We see similar failures intermittently in our nightly testing from various aspects of the service.  To the best of my knowledge, the same can happen via the portal or CLI also.
