### ISSUE TITLE
Azure Provider 2.0 first creates a SUBNET and then assign NSG – it fails if there is a policy that forbids creating the SUBNET without NSG.

### ISSUE THREAD

**Issue by MariuszFerdyn** [terraform-providers/terraform-provider-azurerm#6839]
There is a Policy that forbids creating SUBNET without NSG.

Azure Provider 1.37 during creating SUBNET assign NSG, so everything is working OK.

Azure Provider 2.0 first creates SUBNET and then assigns NSG, so it fails just because cannot create Subnet without NSG in the first step.

Any idea how to resolve this problem?

**Comment by tombuildsstuff** [comment]
hi @MariuszFerdyn 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

If you've got a policy which requires creating a Network Security Group at the same time as the Subnet, you should be able to make use of [the `security_group` field within the `subnet` block within the `azurerm_virtual_network` resource](https://www.terraform.io/docs/providers/azurerm/r/virtual_network.html) to provision this. Since this should be fixed by using the `subnet` block to provision this I'm going to close this issue for the moment.

Thanks!
