### ISSUE TITLE
Dollar sign in '$Default' ConsumerGroup Resource Name

### ISSUE THREAD

**Issue by xadcoh** [terraform-providers/terraform-provider-azurerm#6840]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

I'm using Pulumi 2.1.0 and pulumi_azure 3.4.0 module wich relies on this provider.

### Affected Resource(s)

EventhubDataConnection

### Debug Output

```
Diagnostics:
  azure:kusto:EventhubDataConnection (kusto-eventhub-dataconnection):
    error: azure:kusto/eventhubDataConnection:EventhubDataConnection resource 'kusto-eventhub-dataconnection' has a problem: invalid value for consumer_group (The consumer group name can contain only letters, numbers, periods (.), hyphens (-),and underscores (_), up to 50 characters, and it must begin and end with a letter or number.)
```

### Expected Behavior

Default name for ConsumerGroup in Basic tier is `$Default`

### Actual Behavior

Name is not valid because of dollar sign and error is fired

### Steps to Reproduce

https://github.com/pulumi/pulumi-azure/issues/557

### Important Factoids

No

### References

https://github.com/pulumi/pulumi-azure/issues/557
https://github.com/terraform-providers/terraform-provider-azurerm/blob/a177e53f7fd9f5b2502136dbe7ead8dae0d98ee2/azurerm/helpers/azure/eventhub.go#L29

**Comment by tombuildsstuff** [comment]
hi @xadcoh 

Thanks for opening this issue

Whilst Pulumi does vendor Terraform Providers they alter the functionality somewhat (e.g. changing validation functions) that unfortunately we're unable to isolate if this is a bug in the Azure Provider or a bug in Pulumi itself (and I can't tell which version of the Azure Provider is being used, since we don't ship a 3.4 release).

Since this appears to be a bug in Pulumi, whilst I'd like to thank you for opening this issue I'm going to close this in favour of https://github.com/pulumi/pulumi-azure/issues/557 - where this is being tracked on Pulumi's side.

Thanks!

**Comment by xadcoh** [comment]
Hi @tombuildsstuff 

Could you please clarify for me the terraform-provider-azurerm validation function named `ValidateEventHubConsumerName`. The regexp is `^[a-zA-Z0-9]([-._a-zA-Z0-9]{0,48}[a-zA-Z0-9])?$` and it says that name must begin with letter or number, not with a dollar sign. If I will use terraform instead of Pulumi I believe I will experience the same behavior and I won't be able to use `$Default` name which is created by default by Azure when Basic tier is used.

Thank you for answering my stupid questions.

Regards
