### ISSUE TITLE
Support for adding new pools to existing FrontDoor

### ISSUE THREAD

**Issue by obfu5c8** [terraform-providers/terraform-provider-azurerm#6891]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Bumping discussion around additional resources as outlined in #3186

It would be very useful to be able to add new front/backend pools and routes to an existing FrontDoor instance via terraform. As an example we have a single FrontDoor instance sat at the edge of our network provisioned/managed via a terraform deployment.
When product teams deploy a new service into our stack, it would be a lot easier if they could reference the existing FD instance from their own terraform templates and add in new backend pools and routing rules (rather than having to separately modify the FD iac project and deploy it alongside their own service).

Was there a particular reason the multiple separate resources described in #3186 were unable to be implemented?

**Comment by tombuildsstuff** [comment]
hi @obfu5c8 

Thanks for opening this issue

> Was there a particular reason the multiple separate resources described in #3186 were unable to be implemented?

Whilst the Front Door API's do expose endpoints to add additional sub-resources - unfortunately the Azure API's require specifying at least one of each nested block at creation time - meaning that it's not possible to split this out into separate resources (like we've done with Load Balancers) else you'd end up with conflicting changes between the internal blocks and the separate resources. We also encountered the same issue during the development of Application Gateways, which are designed in a similar manner - meaning that we've been forced to inline those resources too.

Since this is a limitation of the Azure API, unfortunately there's not much we can do about this at this point in time - however should this become available we'd look to switch over to using separate resources instead. As unfortunately this isn't something we can action at this time I'm going to close this issue for the moment - however I'd recommend providing feedback to the Microsoft/the Azure Networking Team who should be able to consider this in the future.

Thanks!
