### ISSUE TITLE
Connection Strings for SQL cosmos db not returned

### ISSUE THREAD

**Issue by davidobrien1985** [terraform-providers/terraform-provider-azurerm#6939]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

https://www.terraform.io/docs/providers/azurerm/r/cosmosdb_account.html#connection_strings mentions that for SQL Cosmos DB accounts the returned `connection_strings` object is empty.

Microsoft mentions that this is implemented in the SDK:
https://github.com/Azure/azure-sdk-for-go/issues/9382#issuecomment-628998138

Why is terraform returning empty in this scenario?

Thanks!

**Comment by tombuildsstuff** [comment]
hey @davidobrien1985 

Terraform uses those API's to retrieve this data from Azure: https://github.com/terraform-providers/terraform-provider-azurerm/blob/master/azurerm/internal/services/cosmos/cosmosdb_account_resource.go#L575-L621

Since the different CosmosDB "type's" are all provisioned through a common API which we're using for all CosmosDB Type's - taking a look at the suggestion in https://github.com/Azure/azure-sdk-for-go/issues/9382 the only difference between the two is the API Version - as such this information should be returned from the API from either API Version.

As this appears to be an issue in the Azure API, rather than something specific to Terraform - I'm going to close this issue in favour of [the upstream Azure SDK issue](https://github.com/Azure/azure-sdk-for-go/issues/9382), where the SDK Team should be able to raise a bug with the Service Team.

Thanks!
