### ISSUE TITLE
use_msi = true | ignored in provider block

### ISSUE THREAD

**Issue by Geartrixy** [terraform-providers/terraform-provider-azurerm#6981]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.23
azurerm 2.10.0

### Affected Resource(s)

* provider azurerm

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.10.0"
  use_msi = true
  features {}
  tenant_id = "12345" # 
  subscription_id = "12345" #the subscription i want to run terraform in
}
```

### Debug Output

`Error: Error building ARM Config: Authenticating using the Azure CLI is only supported as a User (not a Service Principal).
 To authenticate to Azure using a Service Principal, you can use the separate 'Authenticate using a Service Principal'
 auth method - instructions for which can be found here: 
 Alternatively you can authenticate using the Azure CLI by using a User Account.`

### Expected Behavior

Plan should have succeeded

### Actual Behavior

An error message as specified above in debug output^

### Steps to Reproduce

1. terraform init
2. terraform plan

### Important Factoids

The pipeline is running in gitlab.com.

The gitlab runner is on a VM in azure with a system managed identity enabled.

If the gitlab variable "ARM_USE_MSI=true" is set, then there are no problems. But according to the documentation https://www.terraform.io/docs/providers/azurerm/guides/managed_service_identity.html you should be able to configure the provider block by itself without an environment variable...?

"It's also possible to configure a managed identity within the provider block:
`provider "azurerm" {
  version = "~> 1.23"

  use_msi = true
  #...
}`
"

### References

* #0000

**Comment by magodo** [comment]
@Geartrixy Thank you for submitting this issue :+1: 
I have scanned the through the code and didn't find any suspicion. I also can not reproduce it locally.
From your description, the MSI auth method works if you are specifying the env var, then it should take same effect when you specify in the provider block. The error message you are seeing is because terraform considers you didn't set the `use_msi` (or setting it as `false`), then fall back to using the CLI token auth method.
So, is it possible to do me a favor to reproduce that on your side with my following instructions and provide the debug log here:
- Clone [go-azure-helper](https://github.com/hashicorp/go-azure-helpers) locally
- Apply [this patch](https://gist.github.com/magodo/29422178ca14b7e6713e1c43c959dc5c) to the cloned project from the root directory of the project, which simply add the `[DEBUG]` prefix to the log message so that we can see it in the terraform log output
- Modify the azurerm provider's *go.mod* file to [replace](https://github.com/golang/go/wiki/Modules#gomod) the `go-azure-helpers` to using your local one
- Build the provider
- Use the built provider to reproduce your issue. Remember to enable debug log by exporting `TF_LOG=DEBUG` env var.

**Comment by tombuildsstuff** [comment]
hey @Geartrixy 

Terraform supports using the Azure CLI (and MSI etc) for authentication in multiple places - both the Azure Provider (via the Provider block) and in the AzureRM Backend.

It's worth noting that if you're using multiple instances of the Azure Provider then each instance would need to be configured to use MSI (for example, if you're defining a provider block within a module rather than passing it in, you'd need to define this there too).

As such would you be able to confirm if you're using the Azure Backend (e.g. to store Statefiles) / multiple instances of a provider/modules, without passing the providers into the module ([as described in this document](https://www.terraform.io/docs/configuration/modules.html#passing-providers-explicitly))?

Thanks!

**Comment by tombuildsstuff** [comment]
👋 

Since we've not heard back here I'm going to close this issue for the moment - but if you're able to confirm the information above we should be able to take another look here.

Thanks!
