### ISSUE TITLE
'azurerm_key_vault_secret' required read permission for secret value

### ISSUE THREAD

**Issue by schuettecarsten** [terraform-providers/terraform-provider-azurerm#6997]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

`azurerm_key_vault_secret` requires read permission to the secret value. This is a security problem because it breaks it impossible to reference a secret and assign it to another resource without reading the secret value to the client.

I think there should be two data resources: `azurerm_key_vault_secret` and `azurerm_key_vault_secret_value`. The first one should only reference the secret, but not read the value. The second should also read the secret value. Or `azurerm_key_vault_secret` should provide an option to not read the value data.

The same for `azurerm_key_vault_key`.

**Comment by tombuildsstuff** [comment]
hi @schuettecarsten 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through here, unfortunately the only API call available for us to be able to look up a specific version of a Key Vault Secret is the `GetSecret` API (and `GetKey` for a Key Vault Key) - as such I don't think it's possible to split this out in this manner, since this call returns the `value`.

That said, there's two other API methods available here, `GetSecretVersions` and `GetKeyVersions` - which should enable us to return the ID including the Version - which could form a couple of new Data Sources e.g. `azurerm_key_vault_key_versions` and `azurerm_key_vault_secret_versions` which allowed returning only the latest, or filtering by a tag, or specific version (or something else), returning a list of ID's matching those filters which I believe would ultimately fix this in a slightly different manner to what's proposed above.

Since the requested functionality above doesn't appear to be possible based on what we've got in the Azure API - I'm going to close this issue for the moment, but if the Data Sources above sound intriguing [would you mind opening a new Feature Request](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) where we can take a look at those specifically.

Thanks!
