### ISSUE TITLE
Error parsing Resource ID - ID contained more segments than required

### ISSUE THREAD

**Issue by dmitri-o** [terraform-providers/terraform-provider-azurerm#7005]
```
provider "azurerm"{
  version = "=2.10.0"
}
```

```
$ terraform import azurerm_resource_group.xxxxx /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxx-xxx-xxx-xxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxxxxxxxxxxxx

Error: Error parsing Resource ID "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxx-xxx-xxx-xxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxxxxxxxxxxxx": ID contained more segments than required: "/subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxx-xxx-xxx-xxxxxx/providers/Microsoft.Storage/storageAccounts/xxxxxxxxxxxxxxxx"
```

Apparently this should've been fixed since version 2.1.0 of the provider as per #5998 however appears to be not! Please help.

EDIT: Also not working  for provider "azurerm" (hashicorp/azurerm) 2.1.0 - so must be unrelated.

**Comment by tombuildsstuff** [comment]
hi @dmitri-o 

Thanks for opening this issue

Terraform requires that you use the Resource ID for the specific Resource that's being imported - in this instance, the Resource ID of an Resource Group - whereas you're specifying the Resource ID for a Storage Account, which is why Terraform is returning this error.

Instead you should be able to use the ID of the Resource Group, namely:

```
$ terraform import azurerm_resource_group.xxxxx /subscriptions/xxxxxxxx-xxxx-xxxx-xxxx-xxxxxxxxxxxx/resourceGroups/xxx-xxx-xxx-xxxxxx
```

Rather than the ID of the Storage Account and this import should work - would you be able to take a look? Since this should be fixed by updating the Resource ID being used, I'm going to close this issue for the moment.

Thanks!

**Comment by dmitri-o** [comment]
hi @tombuildsstuff thanks so much for explaining this, I apologise for raising this as an issue, got my wires crossed somehow. Thank you.
