### ISSUE TITLE
data science VM reference

### ISSUE THREAD

**Issue by danseo-reisys** [terraform-providers/terraform-provider-azurerm#7006]
the following reference does not work in govcloud.

data "azurerm_platform_image" "image" {
   location  = data.azurerm_resource_group.rg.location
   publisher = "microsoft-ads"
   offer     = "windows-data-science-vm"
   sku       = "windows2016byol"
}

can you give me correct publisher/offer/sku for gov account?

**Comment by tombuildsstuff** [comment]
hi @danseo-reisys 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
