### ISSUE TITLE
KeyVault - Secret without Managing Value

### ISSUE THREAD

**Issue by KSLiquid** [terraform-providers/terraform-provider-azurerm#7019]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As the infrastructure guy I often want to manage which secrets exist in which keyVault.
But I do not nessessarily want to manage the values, since the dev team provides the values themselfes. I just want to create the empty secrets and do not care about the values they put in there.

I suggest a flag named "manageValue" with is true by default.
If it is false, the field "value" is not required.
If it is true, the secret will not change the value. If the secret does not exist yet, it will be created with a dummy value (e.g. empty string).

Sadly I am not capable of implementing this feature myself - but maybe there is someone else who has this need as well and is willing to implement it? :)
Thanks alot in advance!

### New or Affected Resource(s)

* azurerm_key_vault_secret

### Potential Terraform Configuration

```hcl
resource "azurerm_key_vault_secret" "example" {
  name         = "secret-sauce"
  manageValue = false
  key_vault_id = azurerm_key_vault.example.id
}
```

**Comment by tombuildsstuff** [comment]
hi @KSLiquid 

Thanks for opening this issue.

You should be able to achieve this today by using `ignore_changes` to ignore any changes to the value of the secret after the initial creation.

Since the Azure API requires creating a value by default - whilst we could provide a default value here (either hard-coded or generated) - it sounds like this should be achievable using the resource as it stands by taking advantage of the `ignore_changes` functionality to ignore changes to the value.

For example:

```
resource "azurerm_key_vault_secret" "example" {
  name         = "secret-sauce"
  value        = "szechuan"
  key_vault_id = azurerm_key_vault.example.id

  lifecycle {
    ignore_changes = [ value ]
  }
}
```

At which point this secret can be rotated outside of Terraform (e.g. by the developers in this case) - would you be able to take a look? Since this should be fixed by using `ignore_changes` here I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
