### ISSUE TITLE
Azure Still creating ...

### ISSUE THREAD

**Issue by ravirachamadugucap** [terraform-providers/terraform-provider-azurerm#7032]
Hi,

The build is not getting completed, getting the below output

Terraform v0.12.20
provider.azurerm v1.42.0

[buildScript.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/4659249/buildScript.txt)
[terraform.log](https://github.com/terraform-providers/terraform-provider-azurerm/files/4659252/terraform.log)

azurerm_virtual_machine.avm_genie05: Still creating... [14m41s elapsed]
azurerm_virtual_machine.avm_genie05: Still creating... [14m51s elapsed]

**Comment by tombuildsstuff** [comment]
hi @ravirachamadugucap 

Thanks for opening this issue.

The length of time it takes to create a Virtual Machine in Azure depends on a whole bunch of different things (for example, which the Region you're deploying in, Size/Image of the Virtual Machine, including whether SysPrep scripts are being used) - as such it's possible that it can take some time to provision the Virtual Machine.

Azure itself has a 3-hour timeout for starting a Virtual Machine - since Azure does not consider a machine fully "provisioned" until it's fully booted (e.g. through Sysprep) - as such Terraform will continue polling until Azure considers the machine "ready" (or booted).

Since this behaviour is coming from Azure I'm going to close this issue for the moment - however I'd suggest reaching out to Microsoft if you have specific questions, since we're delegating to the Azure API here.

Thanks!
