### ISSUE TITLE
I fixed this issue. Apparently it's not a bug but I was using it wrong. Here is the code that worked

### ISSUE THREAD

**Issue by shan0809** [terraform-providers/terraform-provider-azurerm#7066]
I fixed this issue. Apparently it's not a bug but I was using it wrong. Here is the code that worked

```tf
resource "azurerm_monitor_metric_alert" "alert" {
  name                = "my-endpoint-health-alert"
  resource_group_name = "my-RG"
  //Application Insights ID, not Web Test ID 👇 
  scopes              = ["${var.application_insights_id}"]
  frequency           = "PT1M"
  window_size         = "PT15M"
  criteria {
    metric_namespace  = "Microsoft.Insights/Components"
    metric_name       = "availabilityResults/availabilityPercentage"
    aggregation       = "Average"
    operator          = "LessThan"
    threshold         = 1
    dimension {
      name = "availabilityResult/location"
      operator = "Include"
      values = ["*"]
    }
  }
  action = "${var.action_groups}"
  severity = 3
}
```

_Originally posted by @andreicristianpetcu in https://github.com/terraform-providers/terraform-provider-azurerm/issues/3868#issuecomment-513150938_

**Comment by shan0809** [comment]
what is the value of var.application_insights_id, from where it has been picked? is it the instrumentation key or application insights id from the access key?

**Comment by tombuildsstuff** [comment]
hi @shan0809 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
