### ISSUE TITLE
azurerm_windows_virtual_machine.availability_set_id should handle empty string as "not set"

### ISSUE THREAD

**Issue by schuettecarsten** [terraform-providers/terraform-provider-azurerm#7068]
As terraform does not (yet?) support conditional attributes, the attrribute azurerm_windows_virtual_machine.availability_set_id should handle an empty string as "not set". Otherwise, it's really hard to pass an availability set value as optional variable into a VM module.

Terraform:

```
resource "azurerm_windows_virtual_machine" "vm" {
  name                  = local.resource_name
  location              = local.location
  resource_group_name   = local.resource_group_name
[...]
  availability_set_id   = var.availability_set.id
```

Error:

```
Error: Can not parse "availability_set_id" as a resource id: [ERROR] Unable to parse Availability Set ID "": Cannot parse Azure ID: parse "": empty url

  on ..\sharedmodules\vm_windows\vm.tf line 2, in resource "azurerm_windows_virtual_machine" "vm":
   2: resource "azurerm_windows_virtual_machine" "vm" {```

**Comment by tombuildsstuff** [comment]
hi @schuettecarsten 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

In this instance you should be able to set this value to null using a coalesce statement, for example:

```
resource "azurerm_windows_virtual_machine" "vm" {
  # ...
  availability_set_id   = var.availability_set.id != "" ? var.availability_set.id : null
  # ...
}
```

Would you be able to take a look and see if that works for you? Since this should be fixed by updating the Terraform Configuration being used here I'm going to close this issue for the moment, but that doesn't work for you then you should be able to get an answer for this from one of the [community resources](https://www.terraform.io/community.html).

Thanks!
