### ISSUE TITLE
Support for comma-separated ports in security rules in Network Security Groups

### ISSUE THREAD

**Issue by mkarebski** [terraform-providers/terraform-provider-azurerm#7081]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently, while creating Network Security Group in Terraform, one can specify in security rule single port or port range. My case is a little bit different. I needed a Network Security Group around VM Scale Set with installed Consul. I wanted to have one security rule with all ports, instead of 6 ([Consul Ports](https://headincloud.be/blog/article/consul-ports-and-what-they-are-used-for/index.html)) security rules. It is not possible due to Terraform not supporting comma-separated ports. On the other hand, configuration with comma-separated ports is available through Azure Resource Manager and Azure Portal.

### New or Affected Resource(s)

* azurerm_network_security_group

### Potential Terraform Configuration

```hcl
resource "azurerm_network_security_group" "consul_nsg" {
  name                = "consul_nsg"
  location            = "westeurope"
  resource_group_name = "ExampleResourceGroup"

  security_rule {
    name                       = "ExampleSecurityRule"
    priority                   = 4010
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "*"
    source_port_range          = "*"
    destination_port_range     = "8300,8301,8302,8400,8500,8600" <--- something like this is not possible
    source_address_prefix      = "*"
    destination_address_prefix = "VirtualNetwork"
  }

```

### References

* [Comma-separated ports in NSGs](https://docs.microsoft.com/en-us/azure/virtual-network/manage-network-security-group#create-a-security-rule)

* [Consul Ports](https://headincloud.be/blog/article/consul-ports-and-what-they-are-used-for/index.html)

* [AzureRM Network Security Group ports description](https://www.terraform.io/docs/providers/azurerm/r/network_security_group.html#source_port_range)

**Comment by tombuildsstuff** [comment]
hi @mkarebski 

Thanks for opening this issue

The `azurerm_network_security_group` and `azurerm_network_security_rule` resources support configuring both a single and multiple ports via two distinct fields, a singular port via `destination_port_range` (as you've mentioned) and multiple ports via the plural `destination_port_ranges` - as such it should be possible to switch over to using this, which takes an array of ports (e.g. `destination_port_ranges = [1, 2, 3]` - would you be able to take a look and see if that works for you? The singular/plural fields are available for the other fields in this resource too (for example `source_address_prefixes`).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As this should be fixed by switching to use the `destination_port_ranges` field, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by mkarebski** [comment]
You are right! Thank you for a quick response.
