### ISSUE TITLE
Adding private ip address reference to azurerm application gateway

### ISSUE THREAD

**Issue by AlexBevan** [terraform-providers/terraform-provider-azurerm#711]
Similar issue that was fixed for network interface, however this time for application gateway
https://github.com/hashicorp/terraform/pull/6538

This is required for our internally facing application gateways.

**Comment by katbyte** [comment]
Hi @AlexBevan,

Thank you for opening this issue, just to let you know that we're holding off doing any improvements to the Application Gateway resource until [this bug is resolved](https://github.com/Azure/azure-rest-api-specs/issues/2187) - since it's making it extremely challenging to test changes work as expected (since, there's about an 80% failure rate deleting Application Gateways at the moment). Once that issue's been resolved we can look into scheduling some time to add this property.

Thanks!

**Comment by tombuildsstuff** [comment]
hey @AlexBevan 

Taking a quick look into this - it appears we've already got support for [setting the Private IP Address on an Application Gateway](https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#private_ip_address) - would you be able to take a look and see if that solves your issue?

Thanks!

**Comment by tombuildsstuff** [comment]
Closing since we've not heard back here and this appears to be fixed.
