### ISSUE TITLE
Is it possible to use multiple azurerm_sql_active_directory_administrator's?

### ISSUE THREAD

**Issue by Rookian** [terraform-providers/terraform-provider-azurerm#7117]
Is it possible to use **multiple** `azurerm_sql_active_directory_administrator`s for one Sql Server?

I am coming from Pulumi and retrieve the following error message, when I define multiple admins:

> A resource with the ID "/subscriptions/***/resourceGroups/ppwe-dev/providers/Microsoft.Sql/servers/***/administrators/activeDirectory" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_sql_active_directory_administrator" for more information.

**Comment by yupwei68** [comment]
Hi @Rookian , thanks for opening this issue. No, there is one auread admin allowed in one sql server.

**Comment by tombuildsstuff** [comment]
hi @Rookian 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by Rookian** [comment]
> Hi @Rookian , thanks for opening this issue. No, there is one auread admin allowed in one sql server.

Yes, thank you. You have to add all necessary Security Principles to an AAD group. You can add any type of Security Principle in an AAD group.
