### ISSUE TITLE
Traffic manager error while apply

### ISSUE THREAD

**Issue by thalenin** [terraform-providers/terraform-provider-azurerm#7190]
Error: trafficmanager.ProfilesClient#CreateOrUpdate: Failure sending request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=<nil> <nil>

  on main.tf line 53, in resource "azurerm_traffic_manager_profile" "traffic":
  53: resource "azurerm_traffic_manager_profile" "traffic" {

**code screenshot
![image](https://user-images.githubusercontent.com/66360016/83632855-92090000-a5d2-11ea-94b2-6d1dc1d189f6.png)

**Comment by tombuildsstuff** [comment]
hi @thalenin 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
