### ISSUE TITLE
r/virtual_network: support for `route_table_id` within the `subnets` block

### ISSUE THREAD

**Issue by D4zedC0der** [terraform-providers/terraform-provider-azurerm#7196]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
When creating a resource of type azurerm_subnet, the route_table is missing. This is available through [the Azure API](https://docs.microsoft.com/en-us/rest/api/virtualnetwork/subnets/createorupdate) (you can see the properties.reouteTable property in the request body).

The reason this is urgently required is that my organisation have implemented an Azure policy (as recommended by MS) which prevents the creation of a subnet without specifying a routing table. The reason given for the Azure policy is to prevent application teams from subverting firewalls and other network routing - essentially it has been deemed a security risk. As such, we cannot use an [azurerm_subnet_route_table_association](https://www.terraform.io/docs/providers/azurerm/r/subnet_route_table_association.html) as the initial call to create the subnet in the first place is denied by policy.

### New or Affected Resource(s)

* azurerm_subnet
* azurerm_route_table
* azurerm_subnet_route_table_association

### Potential Terraform Configuration

```hcl
resource "azurerm_subnet" "example" {
  name                 = "testsubnet"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefixes     = ["10.0.1.0/24"]

  route_table_id = azurerm_route_table.example.id

}
```

### References

* https://docs.microsoft.com/en-us/rest/api/virtualnetwork/subnets/createorupdate
* #6382

**Comment by tombuildsstuff** [comment]
hi @D4zedC0der 

Thanks for opening this issue.

The `azurerm_subnet_route_table_association` resource was introduced to work around bugs within the Azure API where resources could be created in one order but then not deleted due to conflicts within the Azure backend.

When using Azure Policy you can instead use the `subnets` block within the `azurerm_virtual_network` resource to set this at initial creation time - however it appears this block doesn't currently expose the `route_table_id` field.

Whilst we don't have plans to reintroduce the `route_table_id` field within the `azurerm_subnet` resource (since this would re-introduce the Azure API bugs) - adding this to the `subnets` block within the `azurerm_virtual_network` resource should achieve the same thing and workaround the bugs in the Azure API's, as such I'm going to update this as an enhancement for the `azurerm_virtual_network` resource instead.

Thanks!

**Comment by tombuildsstuff** [comment]
Actually I've just spotted #6382 in the description above, as such I'm going to close this in favour of #6382 - would you mind subscribing to that issue for updates?

**Comment by D4zedC0der** [comment]
Hi,

That wouldn't help in my case as I my organisation do not allow my service principal (or me) to modify vnets, only the subnets within them. Again this is due to security and our enterprise federated model.

I please ask you to reconsider and follow the API which allows this param in the subnet resource.

**Comment by gchagan36** [comment]
I would like this issue to be reconsidered as well. We are trying to automate Azure resource deployments (VMs, containers, etc.). My org creates the VNET as part of the subscription before they hand it off to me and have similar policies that deny subnets that don't have a route table or NSG attached to it. Using the azurerm_virtual_network resource requires that we first import the vnet since its already created and then add subnet blocks. This is not ideal for automation purposes.
