### ISSUE TITLE
Minimal permission set required for terraform to operate (avoid skip_provider_registration)

### ISSUE THREAD

**Issue by axelthimm** [terraform-providers/terraform-provider-azurerm#7206]
Hello,

> skip_provider_registration - (Optional) Should the AzureRM Provider skip registering the Resource Providers it supports? This can also be sourced from the ARM_SKIP_PROVIDER_REGISTRATION Environment Variable. Defaults to false.
> 
> By default, Terraform will attempt to register any Resource Providers that it supports, even if they're not used in your configurations to be able to display more helpful error messages. If you're running in an environment with restricted permissions, or wish to manage Resource Provider Registration outside of Terraform you may wish to disable this flag; however please note that the error messages returned from Azure may be confusing as a result (example: API version 2019-01-01 was not found for Microsoft.Foo).

We would like to craft a role based on "Reader" or "Contributor" to allow using terrafrom w/o skipping registration, but cannot find the proper documentation for it.

Could you point us to how to setup terraform firendly roles? Or outline in this issue the procedure and required permissions?

Many thanks!

**Comment by tombuildsstuff** [comment]
hi @axelthimm 

Thanks for opening this issue.

It's hard for us to give specifics here without knowing exactly which resources you're using and in which combinations, but you'd likely need Read/Write on the specific Resource Providers, and potentially other operations (for example when rotating the Virtual Machines in a Scale Set requires a different permission). You may be able to determine this information by running a `terraform apply` using a Contributor role, and picking out the permissions required using the Activity Log/Azure Logs, but I've not tried this so I'm unsure.

Unfortunately since this isn't something we're able to help with directly here (since the answer is it depends on the resources/configuration being used, which varies per user) - I'm going to close this issue for the moment - however you may wish to checkout [the Community Resources](https://www.terraform.io/community.html) or [the Microsoft Documentation for the build-in Roles](https://docs.microsoft.com/en-us/azure/role-based-access-control/built-in-roles) as a next step to working out this information.

Thanks!
