### ISSUE TITLE
new feature request - mark an Azure Windows VM as Generalized

### ISSUE THREAD

**Issue by darrens280** [terraform-providers/terraform-provider-azurerm#7209]
Does not seem possible to mark a Windows VM as Generalized in Azure. Currently it can only be done using PowerShell commands, but this will not work when running the Terraform build in an automated pipeline fashion.

- Terraform creates the VM
- Terraform initiates a Powershell script on the new VM to customize itself, then generlize and shutdown
- VM is left shut down, but Terraform resource "azurerm_image" does not work as it does not recognize the VM as generalized

Error: compute.ImagesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="OperationNotAllowed" Message="The operation 'Create Image' requires the Virtual Machine 'test-azure2016-vm' to be Generalized."

**Comment by tombuildsstuff** [comment]
hi @darrens280 

Thanks for opening this issue.

The use-case you're describing sounds like you're building machine images - and hoping to capture (and potentially publish) that image using Terraform?

Terraform's an infrastructure-as-code tool - as such whilst we do expose the `azurerm_image` resource, this is primarily intended to be used when creating an image from an existing disk image (that's been generalized) - rather than for creating new Virtual Machine images. By contrast [Packer is a specialized tool for building machine images](https://www.packer.io) (which also supports Azure and Shared Image Galleries etc, amongst other things).

Whilst there is crossover between Packer and Terraform when building/deploying machine images - generally speaking we'd recommend using Packer (or another tool/process) to build an image and then use Terraform to deploy it. As such whilst we could look to support generalizing machine images within Terraform, this falls outside of Terraform's scope (and towards a tool like Packer) - meaning that unfortunately this isn't something we plan to support at this time.

Since this isn't something we plan to support at this time, whilst I'd like to thank you for opening this issue I'm going to close this issue for the moment.

Thanks!

**Comment by darrens280** [comment]
Makes sense - thank you for the prompt and detailed response
