### ISSUE TITLE
Failed Azure VM doesn't update Terraform state

### ISSUE THREAD

**Issue by adhipgupta** [terraform-providers/terraform-provider-azurerm#7236]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

I mistakenly created an azurerm_virtual_machine without the `plan {}` and it righfully gave me an error that the plan isn't present.

```hcl
resource "azurerm_virtual_machine" "veosVm1" {
  name                          = vm1
  location                      = local.rg_location
  resource_group_name           = local.rg_name
  primary_network_interface_id  = azurerm_network_interface.allIntfs[0].id
  network_interface_ids         = azurerm_network_interface.allIntfs.*.id
  vm_size                       = var.vm_size
  delete_os_disk_on_termination = true

  storage_image_reference {
    publisher = "arista-networks"
    offer     = var.cloudeos_image_offer
    sku       = var.cloudeos_image_name
    version   = var.cloudeos_image_version
  }
  storage_os_disk { ... }
  os_profile { ... }
}
```

### Panic Output

After the first apply, Terraform complained that the plan {} isn't present
```Error: Code="VMMarketplaceInvalidInput" Message="Creating a virtual machine from Marketplace image requires Plan information in the request. VM: '/subscriptions/ba0583bb-4130-4d7b-bfe4-0c7597857323/resourceGroups/AzureLeaf1ad/providers/Microsoft.Compute/virtualMachines/Azureleaf1veos1'."```

### Expected Behavior
After I added the plan {} to my resource and ran `terraform apply` again the resource should have been created.

### Actual Behavior
I added the plan {} and ran `terraform apply` again, but TF complained that the virtual_machine with that name exists. 
```Error: A resource with the ID "/subscriptions/ba0583bb-4130-4d7b-bfe4-0c7597857323/resourceGroups/AzureLeaf1ad/providers/Microsoft.Compute/virtualMachines/Azureleaf1veos1" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_machine" for more information.```

When I looked at `terraform state list` I couldn't find the resource, however the resource was present on my Azure portal in Failed state. The only way I could get around this situation was to manually destroy the VM from the portal and then run `terraform apply` again.

This issue seems to appear every time there is a failed Azure VM deployment.
### Steps to Reproduce

1. `terraform apply` ( without plan {} in the resource )
2. `terraform apply` ( with plan {} in the resource )

### References

* #0000

**Comment by ArcturusZhang** [comment]
Hi @adhipgupta 

Thanks for opening this issue. 

After the azure provider 2.0, the resource `azurerm_virtual_machine` is currently deprecated and feature-freezed in favor of the two new resources `azurerm_linux_virtual_machine` and `azurerm_windows_vritual_machine`.

But I suppose the issue described in the title `Failed Azure VM doesn't update Terraform state` would not be resolved by switching to `azurerm_windows_virtual_machine` or `azurerm_linux_virtual_machine`. This problem is that Azure is using the provisioning state `Failed` to represent so many circumstances, not only to show the virtual machine is unusable. Particular in this case, Azure returns an error when it found that the configuration is not so right, but it still created the resource behind the curtain. And usually it is by-design to just fast-fail whenever the service returns an error.

There were some issues seeking for the ways that terraform could automatically taint the `Failed` resource, but since the configuration varies per environment, how this should be "recovered" varies depending on the resources involved. As such we need to delegate to users on the best path forward for your specific applications here - in some circumstances that may be automatically tainting, but in others that could be automatically deleting/recreating - it's not really something that we can generalize in the Azure Provider specifically.

Back to this case, when this happens, you could import the failed resource in by using the command `terraform import <resource id>`, where the resource id should be in the error message of the previous `terraform apply` command. And then since in the new VM resources, `plan` block is a `ForceNew` block, terraform will automatically destroy the old resource and create a new one. If you choose to continue on the old VM resource, before your second apply, you will have to use `terraform taint <resource.label>` to manually taint this VM resource to let terraform automatically destroy and recreate this resource.

Based on the reasons I have explained above, I do not think this is really a provider bug or there is any enhancement we can do, therefore I will close this issue for now hope you would mind.

Thank you.

**Comment by adhipgupta** [comment]
@ArcturusZhang : thanks for your detailed answer. Wouldn't the enhancement be that the Azure TF provider needs to get the state of what has actually been deployed in Azure. So, you don't have to actually "recover" the instance as you mentioned above and understand the various configuration issues. Instead, just have terraform.tfstate be in sync with the state in Azure.
