### ISSUE TITLE
Feature Request: azurerm_storage_account add name_prefix

### ISSUE THREAD

**Issue by jansepke** [terraform-providers/terraform-provider-azurerm#724]
Hi,

because the name of a azurerm_storage_account must be unique, it would be great to let terraform generate parts of it using a prefix. this would be the same behavior as in [aws_s3_bucket]
(https://www.terraform.io/docs/providers/aws/r/s3_bucket.html) with bucket and bucket_prefix.

### Terraform Version
Terraform v0.11.1
+ provider.azurerm v1.0.0

### Affected Resource(s)
- azurerm_storage_account

**Comment by tombuildsstuff** [comment]
hey @jansepke 

Apologies for the delayed response here!

As discussed in #767 - I'm going to close this in favour of hashicorp/terraform#17389 since this is a Core issue; chatting about this internally, I believe that @katbyte's suggestion of an interpolation function could be a nice solution to this.

Thanks!
