### ISSUE TITLE
Please Reopen Issue #7229

### ISSUE THREAD

**Issue by vishal8k** [terraform-providers/terraform-provider-azurerm#7245]
Please reopen Issue #7229 I believe my code (mentioned in that issue) is perfectly fine and it is a bug that the expected result did not occur. As suggested there I did reach out to community resources and none of them had answers too which pretty much indicates the possibility of a bug. 

https://stackoverflow.com/questions/62227567/terraform-azure-unable-to-create-private-ip-configuration-for-application-gatewa

**Comment by tombuildsstuff** [comment]
hi @vishal8k 

As mentioned in #7229 this appears to be an issue with the Terraform Configuration being used (where only a Public IP block is being defined) - rather than a bug in Terraform. Taking a look through here it appears that [this suggestion should resolve this question](https://stackoverflow.com/a/62254049) - as such I'm going to close this issue for the moment.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html) ([such as the Discussion Forums](https://discuss.hashicorp.com)).

Thanks!
