### ISSUE TITLE
AzureRM and VMSS - update error

### ISSUE THREAD

**Issue by marcelkmfst** [terraform-providers/terraform-provider-azurerm#7253]
Hi,

I am using AzureRM 2.8. and VMScale Sets with custom image in shared image gallery. Provisioning works fine, however, whenever i perform an update, i get this error:

_Error: Error updating LWindowsinux Virtual Machine Scale Set "vmss-app" (Resource Group "RG-TFCICDAPP105"): compute.VirtualMachineScaleSetsClient#Update: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidParameter" Message="Required parameter 'imageReference' is missing (null)." Target="imageReference"_

  on vmss.tf line 5, in resource "azurerm_windows_virtual_machine_scale_set" "vmss":
   5: resource "azurerm_windows_virtual_machine_scale_set" "vmss" {

This is strange, again, the first run works and the image is specified as described in the documentation:

 source_image_id = data.azurerm_shared_image.vmss2019iis.id

This is the reason why I don´t use the source_image block.

Any idea?

**Comment by tombuildsstuff** [comment]
hi @marcelkmfst 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by sonofhammer** [comment]
I'm seeing the same error when I change os_disk caching type from say `None` to `ReadOnly` and try to update the vmss resource.

**Comment by marcelkmfst** [comment]
I am sure it´s a bug...

**Comment by LarsOL** [comment]
I am also seeing the same behavior on `2.15`. `azurerm_windows_virtual_machine_scale_set` is a native `azurerm` provider  resource, not sure why this was closed? 
@marcelkmfst Did you manage to find a work around for the mean time?

**Comment by marcelkmfst** [comment]
Hi,

no, still dealing with the issue, no workarround yet.

**Comment by LarsOL** [comment]
FYI moving back to `azurerm_virtual_machine_scale_set` rather than `azurerm_windows_virtual_machine_scale_set` is working in my tests.
