### ISSUE TITLE
application gateway condition with http header

### ISSUE THREAD

**Issue by zffocussss** [terraform-providers/terraform-provider-azurerm#7260]
Hi team:
    I am using azure application gateway as the door to my backend service.now I want to maintain the configuration on terraform.The question is how to set complex condition with rewrite actions.

the logic is below.

![image](https://user-images.githubusercontent.com/46145695/84138430-ce2fdb00-aa80-11ea-859f-d42d75828796.png)

how to enable the above setting on terraform file?

I only can see the simple condition set.

![image](https://user-images.githubusercontent.com/46145695/84138509-f15a8a80-aa80-11ea-9cfc-945628c01493.png)

any help will be thankful.

my terraform version
```
Terraform v0.11.11

```
azure provider  version
```
provider "azurerm" {
    version = "~> 2.8.0"
}
```

**Comment by tombuildsstuff** [comment]
hi @zffocussss 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
