### ISSUE TITLE
Feature Request: split azurerm_application_gateway into multiple resources

### ISSUE THREAD

**Issue by jansepke** [terraform-providers/terraform-provider-azurerm#727]
Hi,

would it be possible to split the azurerm_application_gateway resource into multiple other? so that one can create backends, listeners and rules in another file. Also then one could use count in the sub-resources, which is not possible right now. Maybe you could start with backend_address_pool because this has relations to other terraform azure resources.

### Terraform Version
Terraform v0.11.1
+ provider.azurerm v1.0.0

### Affected Resource(s)
- azurerm_application_gateway

**Comment by tombuildsstuff** [comment]
hey @jansepke 

Thanks for opening this issue

> would it be possible to split the azurerm_application_gateway resource into multiple other? so that one can create backends, listeners and rules in another file. Also then one could use count in the sub-resources, which is not possible right now. Maybe you could start with backend_address_pool because this has relations to other terraform azure resources.

So back when we were first supporting this resource we were hoping to take this approach - however after some investigation it appears the API is set up different from the Load Balancer API (which uses the approach you've specified) such that it's not possible.

In the Load Balancer resources we essentially create an empty Load Balancer with all sub-fields (such as the Probes) as empty lists - and then when making any changes we pull the latest information about the Load Balancer and update the relevant field, for instance we add a new Probe.

Unfortunately the Application Gateway API requires almost all of the Application Gateway sub-objects to be specified, such that whilst we could do this for a few of the sub-objects (from memory fields like `url_path_map`, `application_certificate` and the `waf_configuration` blocks) - most of the benefit would come from splitting out the other fields (as you've outlined above).

In order to proceed with this we'd need the API to be updated to handle this - I'll raise this through our internal channels, but it might be worth opening an issue on [the Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs) so that the Application Gateway team could better understand the use-case.

---

Separately to this there's a feature request in Terraform Core which may help with this that you may be interested in/wish to subscribe to: https://github.com/hashicorp/terraform/issues/2275

---

Given there's not a lot we can do with this issue in the foreseeable future, I'm going to close this issue for the moment. However should support become available for this in the API (and/or the SDK) - we'll certainly look to support this.

Thanks!

**Comment by boillodmanuel** [comment]
Asked on azure feedback site : https://feedback.azure.com/forums/217313-networking/suggestions/39634519-allow-creation-of-an-empty-application-gateway
If people following this issue could vote on it, it will be great 👍

**Comment by boillodmanuel** [comment]
Asked also for related feature request: https://feedback.azure.com/forums/217313-networking/suggestions/39634588-add-rest-apis-and-sdk-to-manage-application-gatewa
If people following this issue could vote on it, it will be great 👍
