### ISSUE TITLE
Creating General Purpose azurerm_mysql_server times out.

### ISSUE THREAD

**Issue by emeka** [terraform-providers/terraform-provider-azurerm#7280]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.26
+ provider.azurerm v2.12.0

### Affected Resource(s)

* `azurerm_mysql_server"`

### Terraform Configuration Files

```hcl
provider "azurerm" {
  version = "=2.12.0"
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "issue-example"
  location = "westeurope"
}

resource "azurerm_mysql_server" "example" {
  name                = "issue-mysql-server"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  administrator_login          = "mysqladmin"
  administrator_login_password = "Test1234"

  sku_name   = "GP_Gen5_2"
  storage_mb = 5120
  version    = "5.7"

  auto_grow_enabled                 = true
  backup_retention_days             = 7
  geo_redundant_backup_enabled      = true
  infrastructure_encryption_enabled = true
  public_network_access_enabled     = true
  ssl_enforcement_enabled           = true
  ssl_minimal_tls_version_enforced  = "TLS1_2"
}
```

### Debug Output

https://gist.github.com/emeka/56c902dd9ab173030c6a0092d7f36ce8

### Panic Output

N/A

### Expected Behavior

Resource is created

### Actual Behavior

Azure does not create the resources and times out.  This is only for the General Purpose sku.
It works with the Basic sku.

### Steps to Reproduce

1. `terraform plan -out plan`
2. `terraform apply plan`

### Important Factoids

I can create the General Purpose mysql database using the Azure portal or using the following `az` command:

```
az mysql up -u mysqladmin -p Test1234 --geo-redundant-backup Enabled -l westeurope -g emeka-cluster -s test-gp --sku-name GP_Gen5_2 --storage-size 5120
```

I am logged to Azure with the same user as the one used when running the terraform commands.

I have tried with different backup, geo-redundancy, encryption, ssl and public nework access configurations without success.

### References

N/A

**Comment by tombuildsstuff** [comment]
hi @emeka 

Thanks for opening this issue :)

Taking a look through, the error being returned from the Azure API here:

```
The operation timed out and automatically rolled back. Please retry the operation.
```

.. means that the provisioning of this MySQL Server has failed on Azure's side - and it should be safe to delete it & retry. Unfortunately where this is a provisioning error on Azure's side, this error could be returned for either the Azure CLI, Portal, or any other consumer of the Azure API such as Terraform.

Since this is a temporary failure on Azure's side - re-running `terraform apply` should create this MySQL Server - but as mentioned above unfortunately this is an error coming back from the Azure API.

As different Azure Resources have different failure modes - some of which are retryable/recoverable, some of which aren't - Terraform doesn't delete/re-create resources when they fail to provision (since for example, were this error to be returned during an outage, it'd be repeatedly hit) and instead falls back to the operator determining how to proceed / re-validate a Terraform Plan.

Since this is a temporary issue in the Azure API which should be fixed by re-running `terraform apply` here, I'm going to close this issue for the moment - but please let us know if you're still seeing this after re-running `terraform apply` and we'll take another look 👍 

Thanks!

**Comment by emeka** [comment]
Hi @tombuildsstuff,

Thanks for your reply.

I am trying to deploy this GP mysql database for several days and it does not look like just a temporary issue, even if the trace log that I have also read carefully seems to indicate so.  As mentioned, deploying the database instance using az cli or the portal succeed every time.  Hence the possibility that the use of the Azure REST API is maybe missing something on your side.

Could you please try to run the provided main.tf and verify that you cannot reproduce the problem?

Thanks in advance.

**Comment by emeka** [comment]
Hi @tombuildsstuff,

I got an answer from Azure support and the issue was due to a combination of parameters.
Removing `ssl_minimal_tls_version_enforced  = "TLS1_2"` and setting `infrastructure_encryption_enabled = false` resolved the problem.

We still need to check if we really disable encryption at rest by doing this.  However, this is not a terraform problem.

This is FYI.

Thanks for looking at this.

**Comment by KevinBrooke** [comment]
FYI, `ssl_minimal_tls_version_enforced = "TLS1_2"` was OK for me, I only had to set `infrastructure_encryption_enabled = false`.
Another day, another Azure API issue.

**Comment by catay** [comment]
> FYI, `ssl_minimal_tls_version_enforced = "TLS1_2"` was OK for me, I only had to set `infrastructure_encryption_enabled = false`.

Does it in your case apply the TLS 1.2  ?   The terraform apply works but it doesn't seem to apply the TLS setting.
It keeps showing after reach run: 

~ ssl_minimal_tls_version_enforced  = "TLSEnforcementDisabled" -> "TLS1_2"
