### ISSUE TITLE
Validation errors on XmlLink and XmlContent for API Management policies with C# code

### ISSUE THREAD

**Issue by UnoSD** [terraform-providers/terraform-provider-azurerm#7288]
#7055 # Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Latest

### Affected Resource(s)

* `azurerm_apim_` any policy (Api/Operation)

This issue was already present here: Creating a API Management policy for an API gives an ValidationError #3918

For some reason it was closed with no resolution

### Expected Behavior

Passing validation and uploading the XML

### Actual Behavior

Validation error

### Steps to Reproduce

Include quotes or other special characters in an XML attribute inside a C# block @() or @{}

### References

https://github.com/terraform-providers/terraform-provider-azurerm/issues/3918

* #3918

**Comment by yupwei68** [comment]
Hi @UnoSD , thanks for opening this issue. As for issue https://github.com/terraform-providers/terraform-provider-azurerm/issues/3918, it's closed because it's fixed by https://github.com/terraform-providers/terraform-provider-azurerm/pull/4140 (released in v1.37.0), which adds format `Raw XML` in `api_management_api_policy`. And in that case, I have tested with success in the latest version of Azurerm. Would you mind uploading your policy xml configuration if you have checked it's fine to be accepted on Portal or other tools?

**Comment by UnoSD** [comment]
Hi @yupwei68, thank you for your response.

I am actually using Pulumi which uses this provider under the hood. I have opened an issue on their side just now as I suspect they may not be using the latest version, hence the error.

https://github.com/pulumi/pulumi-azure/issues/611

I am awaiting confirmation from them (that is an issue on their side) before closing.

Thanks.

**Comment by tombuildsstuff** [comment]
hi @UnoSD 

Thanks for opening this issue

Whilst Pulumi does vendor Terraform Providers they alter the functionality somewhat (e.g. changing validation functions) that unfortunately we're unable to isolate if this is a bug in the Azure Provider or a bug in Pulumi itself (and I can't tell which version of the Azure Provider is being used, since that information is omitted above).

Since this appears to be a bug in Pulumi, whilst I'd like to thank you for opening this issue I'm going to close this in favour of https://github.com/pulumi/pulumi-azure/issues/611 - where this is being tracked on Pulumi's side.

Thanks!
