### ISSUE TITLE
Terraform azure data "azurerm_image" regex cannot get both 2 and 3 digits.

### ISSUE THREAD

**Issue by nallanisai** [terraform-providers/terraform-provider-azurerm#7291]
data "azurerm_image" "prod_image" {
    name_regex          = "^test-${var.os}-b\\d+"
    resource_group_name = "${data.azurerm_resource_group.unix_rg.name}"
    sort_descending     = true
 }
 
we have  centos and ubuntu images with build numbers like below, above code looks for only 2 digits after "b" and gets highest number, how to looks for both 2 and 3digits and get highest number

Images names in storage are like below:

test-ubuntu-b1
.
.
test-ubuntu-b45
test-ubuntu-b46 -- need to get this latest image

For centos we have like below 3 digits:

test-centos-b1
.
.
test-centos-b120
test-centos-b121  -- need to get this latest image

How to match regex for both 2 and 3 digits.

Terraform version 0.11.14

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behavior

test-ubuntu-b46
(or)
test-centos-b121

### Actual Behavior

test-ubuntu-b46
and
test-centos-b99

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @nallanisai 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
