### ISSUE TITLE
Attachnig additional network interface to the existing VM in azure

### ISSUE THREAD

**Issue by ubsujit** [terraform-providers/terraform-provider-azurerm#7293]
Is there any option in terraform to attach additional network interface to the existing vm in azure ?

**Comment by tombuildsstuff** [comment]
hi @ubsujit 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
