### ISSUE TITLE
Feature Request: Add Cassandra as a kind for CosmosDB

### ISSUE THREAD

**Issue by zxjinn** [terraform-providers/terraform-provider-azurerm#732]
Hey, we've been using this provider with great success over the last year or so, thank you for all your hard work.

### Description
I don't believe that this feature request is possible to complete until the upstream go SDK supports creating Cassandra in CosmosDB, but I'm opening this so I can keep track of the progress for myself and anyone else that is interested in this feature.
The upstream issue appears to be Azure/azure-sdk-for-go#864, but I could very well be wrong.

### Terraform Version
Terraform v0.11.2
azurerm provider v1.0.1

### Affected Resource(s)
`cosmosdb_account`

### References
- Azure/azure-sdk-for-go#864

**Comment by tombuildsstuff** [comment]
hey @zxjinn 

Thanks for opening this issue.

So the `kind` field gets populated with Enum's/Constants from the Azure SDK for Go (which is generated from [the Swagger repository](https://github.com/Azure/azure-rest-api-specs)) - however the `DatabaseAccountKind` for `Cassandra` isn't available in the SDK at this time:

https://github.com/Azure/azure-sdk-for-go/blob/f5ae63259c88c590a6ebbf6afef0123f1daaa9d7/services/cosmos-db/mgmt/2015-04-08/documentdb/models.go#L29-L39

Given the SDK is generated from the Swagger, in order to add support for this field in the Azure SDK for Go we'd need to get the additional value for Cassandra added to this list in the Swagger definition:

https://github.com/Azure/azure-rest-api-specs/blob/d2bb2feadd0deb1c7212706aa65cab2f56adccc7/specification/cosmos-db/resource-manager/Microsoft.DocumentDB/stable/2015-04-08/cosmos-db.json#L993-L1015

In order to do that, I'd suggest opening an issue on the [Azure Rest API Specs Repository](https://github.com/Azure/azure-rest-api-specs) - which when merged should be added to a subsequent release of the Go SDK (which we can then consume).

Issue Azure/azure-sdk-for-go#864 is referring to exposing a Golang Client for Cassandra in the Azure SDK for Go - which whilst related would be a secondary issue since it'd be used to create other resources (such as `azurerm_cosmosdb_database` or `azurerm_cosmosdb_trigger`, for instance) with Terraform.

Thanks!

**Comment by gunndabad** [comment]
@tombuildsstuff It looks like Cassandra and other APIs are selected via the Capabilities property instead of Kind (see https://github.com/Azure/azure-sdk-for-go/blob/dev/services/cosmos-db/mgmt/2015-04-08/documentdb/models.go#L148-L151). Any chance this could be added?

**Comment by scottrangerio** [comment]
Hey,

While the cassandra capability can be selected, it doesn't seem to actually work currently. I was messing around with cosmos and the go sdks recently and tried to create a cosmos account with the Cassandra API. I've just rerun it and the issue still seems to exist. The gist for the code I used is here 

https://gist.github.com/scottrangerio/9619259d809fba282504b4dee756b5b4

however the deployment just fails. If you look in the portal, you'll probably see the following 
![screenshot 2018-04-18 at 19 15 22](https://user-images.githubusercontent.com/7337433/38950433-6c7d73d8-433d-11e8-8356-e46a1aa624ba.png)

This code did work for Gremlim and Table capabilities, just not Cassandra. Anyway, I'm not sure if this affects everyone, or maybe it's something to do with where you try to deploy the account or some other variable, just figured I'd mention this for relevance.

**Comment by tombuildsstuff** [comment]
@scottrangerio it's possible to see the generated ARM Template for Cassandra in the Portal when creating a new CosmosDB account (see below), which should identify which fields are required (or, once one is provisioned, the JSON from the API can be seen at `https://resources.azure.com`) - which may help identify if there's any additional settings required.

<img width="657" alt="screen shot 2018-04-18 at 22 59 27" src="https://user-images.githubusercontent.com/666005/38958130-a1f29dee-435c-11e8-88d3-68064fe74210.png">

Hope that helps :)

**Comment by zxjinn** [comment]
Oh man I am a terrible person. I never filed tickets for this against those other repo. I'm sorry I dropped the ball :\

**Comment by scottrangerio** [comment]
@tombuildsstuff Hey, thanks for taking a look and sharing! I'd never considered that, would definitely explain things. I've signed up for the preview as well now, providing I get access to it and everything works, I'd be happy to take on this issue in the foreseeable future and make a PR if no one else is able to sooner. Cheers 👍

**Comment by zxjinn** [comment]
@scottrangerio To put a wet blanket on the excitement we (I currently work at Adobe) requested access to the Cassandra API for CosmosDB on the 19th of Jan, when this Issue was created, and none of the four subscriptions we requested have been given access yet.

I would like to think that Adobe has a [pretty](https://news.microsoft.com/2016/09/26/adobe-and-microsoft-partner-in-the-azure-cloud-to-help-businesses-transform-customer-engagement/) [good](https://techcrunch.com/2017/09/07/microsoft-and-adobe-announce-an-expanded-partnership-around-adobe-sign-and-microsoft-teams/) [relationship](https://www.adobe.com/enterprise/microsoft-partnership.html) with Microsoft, and even after all this time, including many phone calls and in-person meetings with the Cosmos product team, we are still waiting 😢 

I am not trying to throw shade on Microsoft or Azure, or puff myself up to look important, just sharing the experiences we've had so far. I hope it doesn't take you as long as it's (so far) taken us.

**Comment by justinhauer** [comment]
@zxjinn is there an example creating cosmos?
