### ISSUE TITLE
No available provider "azure" plugins are compatible with this Terraform version.

### ISSUE THREAD

**Issue by shareKnowledge** [terraform-providers/terraform-provider-azurerm#7360]
I am running terraform v0.12.26, azurerm provider v2.14.0 is getting downloaded by running terraform init but its failing in installing the same.
Error:
No available provider "azure" plugins are compatible with this Terraform version.

Could you please help me in getting this resolved.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by ArcturusZhang** [comment]
Hi @shareKnowledge thanks for this issue!
Our provider should be `azurerm` rather than `azure`. Could you please try the following config?
```
provider "azurerm" {
  version = "2.14.0"
  features {}
}

resource "azurerm_resource_group" "test" {
  name = "test-rg"
  location = "westus"
}
```

BTW, if I change the `azurerm` to `azure` and remove the `version` constraint in the provider block, I could get exactly the same error message as yours.
```
No available provider "azure" plugins are compatible with this Terraform version.
```

**Comment by tombuildsstuff** [comment]
hi @shareKnowledge 

As @ArcturusZhang has alluded to - there's several different Azure Providers that Terraform supports:

* `azure` (classic)
* `azuread` - for Azure Active Directory
* `azurerm` - for Azure Resource Manager
* `azurestack` - for Azure Stack

In this instance it appears you're attempting to use the provider for Azure Classic - which [is no longer supported](https://azure.microsoft.com/en-us/updates/azure-portal-updates-for-classic-portal-users/) since this service has been deprecated by Microsoft.

Instead (as @ArcturusZhang has mentioned) it should be possible to update the code to reference the `azurerm` provider. Since this should be fixed by updating the Terraform Configuration being used, I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by shareKnowledge** [comment]
I have figured out that due to error in child module I was getting that error. After fixing that child module code, this error was fixed.
The error mg was confusing.
Thank you all.
