### ISSUE TITLE
Move resource from one resource group to another by terraform

### ISSUE THREAD

**Issue by LoofahBu** [terraform-providers/terraform-provider-azurerm#7391]
Is there a way can move resource from one resource group to another? We have a machine in the `rg_one` but want to move it to `rg_two` and delete remaining resources in `rg_one`. It can be done on the azure portal but seems `azurerm-provider` doesn't have such solution?

**Comment by favoretti** [comment]
I believe there's no API support for moving resources..

**Comment by WodansSon** [comment]
@LoofahBu, the Azure team has recently release(03/02/2020) a new API that allows a very limited number of resources to be "moved" between `resource groups` and `subscriptions`, you can find which resources which currently support this functionality [here](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription). That said, while it is currently supported for some of these resources via the portal, it is not currently available via Terraform at this time.

**Comment by magodo** [comment]
Since supporting the [move resource functionality](https://docs.microsoft.com/en-us/azure/azure-resource-manager/management/move-resource-group-and-subscription) is something we can hardly support in terraform (see #1733 for details), I'm gonna close this issue for now.

If you have further questions, please feel free to using one of the [Community Resources](https://www.terraform.io/community.html) to ask.
