### ISSUE TITLE
Looking to enable Oauth2.0 for API Management API using terraform

### ISSUE THREAD

**Issue by swapnilbjadhav** [terraform-providers/terraform-provider-azurerm#7410]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

resource "azurerm_api_management_api" "my_api" {
  name                = "example-api"
  resource_group_name = azurerm_resource_group.example.name
  api_management_name = azurerm_api_management.example.name
  revision            = "1"
  display_name        = "Example API"
  path                = "example"
  protocols           = ["https"]

  **oauth2_authorization {
    authorization_server = azurerm_api_management_authorization_server.my_oauth_server.id
    scope_override = "foo"
  }**
}

If you have a support request or question please submit them to one of these resources:
@brunhil  @markti 

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @swapnilbjadhav 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
