### ISSUE TITLE
Under Backup Section Include Database is missing

### ISSUE THREAD

**Issue by kernelv5** [terraform-providers/terraform-provider-azurerm#7427]
![image](https://user-images.githubusercontent.com/8419859/85248146-9498a000-b482-11ea-8e8c-471440898bda.png)

Include Datbaase undrbackup Section.

**Comment by tombuildsstuff** [comment]
hi @kernelv5 

Thanks for opening this issue.

Unfortunately there's not enough information in the screenshot above for us to determine the specific changes needed here, as such I'm going to close this issue for the moment - but would you mind [opening a new issue using the Feature Request issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) (which contains the information we need) so that we can take a look into this?

Thanks!

**Comment by kernelv5** [comment]
@tombuildsstuff : Using Azure Portal we can enable Azure App Service Backup and close Include Database. 
terraform dont have Include backup option.
