### ISSUE TITLE
refer multiple azure Key vault secrets using list in a resource azurerm_sql_server

### ISSUE THREAD

**Issue by praveenops** [terraform-providers/terraform-provider-azurerm#7428]
Hi,

I have stored multiple secrets in azure keyvault and the  same I am able to pull via datasource and it is working as expected, when I refer the values as below under resource "azurerm_sql_server"( integers)

  administrator_login                 = data.azurerm_key_vault_secret.creds.0.value
  administrator_login_password = data.azurerm_key_vault_secret.creds.1.value

The variable entry..

variable "secrets" {
  type        = list(string)
  default = ["sqluser", "sqlpassword"]
}

The main.tf entry...

data "azurerm_key_vault_secret" "creds" {
  count        = length(var.secrets)
  name         = var.secrets[count.index]
  key_vault_id = "${data.azurerm_key_vault.main.id}"
}

resource "azurerm_sql_server" "main" {
  name                                     = "${var.server_name}-${var.environment}"
  resource_group_name          = data.azurerm_resource_group.rgname.name
  location                                  = data.azurerm_resource_group.rgname.location
  version                                   = "12.0"
  administrator_login                 = data.azurerm_key_vault_secret.creds.0.value
  administrator_login_password = data.azurerm_key_vault_secret.creds.1.value
}

But when I replace the integer values with strings like the below under resource "azurerm_sql_server section, 

administrator_login                 = data.azurerm_key_vault_secret.creds.sqluser.value
administrator_login_password = data.azurerm_key_vault_secret.creds.sqlpassword.value

the following error appeared:

Error: Unsupported attribute

  on main.tf line 51, in resource "azurerm_sql_server" "main":
  51:   administrator_login          = data.azurerm_key_vault_secret.creds.datasourceUsername.value

This object has no argument, nested block, or exported attribute named
"datasourceUsername".

Can you guide me how can I pass the string instead of integer ..

**Comment by yupwei68** [comment]
hi @praveenops ,Thanks for opening this issue.
This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the Community Resources. I'd like to suggest to raise interpolation syntax issue in https://github.com/hashicorp/terraform/issues.

**Comment by tombuildsstuff** [comment]
hi @praveenops 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
