### ISSUE TITLE
azurerm_postgresql_firewall_rule fails to find the server

### ISSUE THREAD

**Issue by rrey** [terraform-providers/terraform-provider-azurerm#7432]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

`Terraform v0.12.26`
`azurerm = 2.15`

### Affected Resource(s)

* `azurerm_postgresql_firewall_rule `
* `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
[...]
resource "azurerm_postgresql_server" "assie_paas_postgresql_server" {
  count               = var.module_create ? 1 : 0
  name                = local.l_db_server_name
  location            = local.l_rg_location
  resource_group_name = local.l_rg_name

  sku_name = var.module_skuName

  storage_mb                   = var.module_storageMb
  backup_retention_days        = var.module_bkRetDays
  geo_redundant_backup_enabled = var.module_geoRBk

  administrator_login          = var.module_paasDbUserName
  administrator_login_password = module.create_random_secret.outputSecret
  version                      = var.module_serverVersion
  ssl_enforcement_enabled      = var.module_serverSsl

  tags = local.l_tags
}

resource "azurerm_postgresql_database" "assie_paas_postgresql_database" {
  count               = var.module_create && var.module_dbCreate ? 1 : 0
  name                = local.l_db_name
  resource_group_name = local.l_rg_name
  server_name         = azurerm_postgresql_server.assie_paas_postgresql_server[0].name
  charset             = var.module_dbCharset
  collation           = var.module_dbCollation
}

resource "azurerm_postgresql_firewall_rule" "assie_paas_postgresql_firewall_rule" {
  for_each            = var.firewall_rules
  name                = format("%s-%s", local.l_db_fw_rule_name, each.key)
  resource_group_name = local.l_rg_name
  server_name         = local.l_db_server_name
  start_ip_address    = each.value.start_ip_address
  end_ip_address      = each.value.end_ip_address
}
```

### Debug Output

https://gist.github.com/rrey/47dae1a9297c87680371e30fa0b0d330

### Expected Behavior

The `azurerm_postgresql_firewall_rule` is created.

### Actual Behavior

When running terraform for the first time, the apply fails everytime because the server resource is not found.
Re-running the apply immediatly after the failure makes the apply succeeds.

```
       Error: postgresql.FirewallRulesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.DBforPostgreSQL/servers/azpsypsql02' under resource group 'azrgp-int-01' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
       
         on ../../main.tf line 76, in resource "azurerm_postgresql_firewall_rule" "assie_paas_postgresql_firewall_rule":
         76: resource "azurerm_postgresql_firewall_rule" "assie_paas_postgresql_firewall_rule" {
       
       
       
       Error: postgresql.FirewallRulesClient#CreateOrUpdate: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.DBforPostgreSQL/servers/azpsypsql02' under resource group 'azrgp-int-01' was not found. For more details please go to https://aka.ms/ARMResourceNotFoundFix"
       
         on ../../main.tf line 76, in resource "azurerm_postgresql_firewall_rule" "assie_paas_postgresql_firewall_rule":
         76: resource "azurerm_postgresql_firewall_rule" "assie_paas_postgresql_firewall_rule" {
       
```

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @rrey 

Thanks for opening this issue.

Taking a look into the Terraform Configuration provided above, it appears there's no dependency between the Firewall Rule and the Server - meaning that Terraform doesn't know that these resources depend on one another and so believes it can create them both in parallel. This is due to using a variable directly:

```hcl
resource "azurerm_postgresql_firewall_rule" "assie_paas_postgresql_firewall_rule" {
  resource_group_name = local.l_rg_name
  server_name         = local.l_db_server_name
}
```

By contrast the Database resource has a dependency on the Server via Terraform's Interpolation Syntax:

```hcl
resource "azurerm_postgresql_database" "assie_paas_postgresql_database" {
  server_name         = azurerm_postgresql_server.assie_paas_postgresql_server[0].name
}
```

Which means that Terraform knows that the Server needs to be created before the Database - however since there's no dependency between the Firewall Rule and the Server, Terraform believes that it can create the Firewall Rule at the same time as the Server - which fails. As such it should be possible to fix this by using the Interpolation Syntax to pass through the value for the Server Name, rather than the variable - for example:

```hcl
resource "azurerm_postgresql_firewall_rule" "assie_paas_postgresql_firewall_rule" {
  resource_group_name = local.l_rg_name
  server_name         = azurerm_postgresql_server.assie_paas_postgresql_server[0].name
}
```

Would you be able to take a look and see if that works for you?

Since this should be fixed by updating the Terraform Configuration being used here I'm going to close this issue for the moment, but please let us know if that doesn't work for you and we'll take another look :)

Thanks!

**Comment by rrey** [comment]
@tombuildsstuff that was indeed my issue !
