### ISSUE TITLE
How to send "azure devops predefined variables" to my powerShell script.

### ISSUE THREAD

**Issue by motycak** [terraform-providers/terraform-provider-azurerm#7441]
Hi,
I want to ask. How to send "azure devops predefined variables" to my powerShell script,
Azure devops predefined variables https://docs.microsoft.com/en-us/azure/devops/pipelines/build/variables?view=azure-devops&tabs=yaml
I want to send an Agent.TempDirectory.

local-exec provisioner {
     command = "MyPowershellScript.ps1"
     interpreter = ["PowerShell", "-File"]
     environment = {
       temp_directory = $ (Agent.TempDirectory) # How to write it?
     }
   }

**Comment by mybayern1974** [comment]
Thanks for opening this issue.
 
Per the provided contexts, may I assume it's not Terraform Azure provider related? If it's core related with PowerShell, you can ask at the [PowerShell community](https://github.com/Azure/azure-powershell/issues).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that. Broader questions are raised using one of the Community Resources. As such please allow me to close this issue for the moment, but I believe you should be able to get an answer for this using one of the Community Resources.

- [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
- [HashiCorp support](https://support.hashicorp.com)

**Comment by tombuildsstuff** [comment]
hi @motycak 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
