### ISSUE TITLE
Understanding child module variables and variables from parent module.

### ISSUE THREAD

**Issue by shareKnowledge** [terraform-providers/terraform-provider-azurerm#7451]
Hi,

I am quite new in using Terraform, please bear with me if my questions are silly. 
My code structure is as follows:
Root:-----------
main.tf
variables.tf
main_values.tfvars
nva-------(/* child module folder */)
      create_firewall.tf
      variables.tf
      firewall_values.tfvars

I have tried executing just the child module as a separate standalone one, it worked successfully.
As a next step I wanted to try out module configuration.
Root: ---- consists of only creation of vnet and subnets.
Child Module ----- creates AzureFirewall subnet in vnet created in parent .
                               and Azure Firewall in that subnet.
My issues:
1. How to refer to the vnet that is created in parent.
2. Although all values are provided in firewall_values.tfvars, it is still asking the values from the main.tf in parent where child module is getting called.

I know as per the module configuration I need to pass all the values at the time of calling the module. Is there any way I can point to values defined in firewall_values.tfvars file. If this is possible, then child module variables definitions can be segregated.

Thanks in advance.

**Comment by tombuildsstuff** [comment]
hi @shareKnowledge 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by shareKnowledge** [comment]
Thanks Tom, by directing me to the right forum.
