### ISSUE TITLE
azurerm_managed_disk documentation - Disk Encryption Set must have the Reader Role Assignment 

### ISSUE THREAD

**Issue by mleziva** [terraform-providers/terraform-provider-azurerm#7476]
On the azurerm_managed_disk documentation page there is the below note:

`
NOTE: The Disk Encryption Set must have the Reader Role Assignment scoped on the Key Vault - in addition to an Access Policy to the Key Vault`

I can't find references in the Microsoft documentation that key vault reader role is required for disk encryption sets. Is this role actually required? The reason this issue is important is because having the ability to assign roles requires a specific role be assigned to the service principal in Azure which is a security concern. 

link to page: https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html

**Comment by tombuildsstuff** [comment]
hi @mleziva 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by mleziva** [comment]
Thanks @tombuildsstuff, I have created the topic here: https://discuss.hashicorp.com/t/azurerm-managed-disk-disk-encryption-set-must-have-the-reader-role-assignment/10772
