### ISSUE TITLE
unable to create azurerm_site_recovery_replication_policy 

### ISSUE THREAD

**Issue by ChristoferLee** [terraform-providers/terraform-provider-azurerm#7479]
I'm following this document (https://www.terraform.io/docs/providers/azurerm/r/site_recovery_replicated_vm.html) to create vm-vm site recovery but it errors out while trying to create the site recovery policy.  The resource group and vault names are correct as the fabric and container are created just fine prior to the attempt to create this policy resource.

### Affected Resource(s)

* `azurerm 2.0.0`
* `Terraform v0.12.24`

### Terraform Configuration Files

```
resource "azurerm_site_recovery_replication_policy" "policy" {
  name                                                 = "test-policy"
  resource_group_name                                  = var.site_recovery.vault_resource_group
  recovery_vault_name                                  = var.site_recovery.site_recovery_vault
  recovery_point_retention_in_minutes                  = 90 * 60
  application_consistent_snapshot_frequency_in_minutes = 24 * 60
}
```

### Debug Output

https://gist.github.com/ChristoferLee/cc58c838e485afb319ed1e61a089aba7

Error: Error creating site recovery replication policy test-policy (vault my-test-vault): Code="150261" Message="Replication policy creation failed."

### Expected Behavior

Terraform to create the site recovery policy

### Actual Behavior

Error: Error creating site recovery replication policy test-policy (vault my-test-vault): Code="150261" Message="Replication policy creation failed."

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @ChristoferLee 

Thanks for opening this issue.

Taking a look into this, the error message being returned here is from the Azure API:

```
Code="150261" Message="Replication policy creation failed."
```

Unfortunately due to the nature of the Azure API, we're unable to determine how to proceed automatically when the Azure API fails (for example, in some circumstances it could be safe to delete this & re-try creating it - but in other circumstances this could cause other issues).

Since this bug is coming from the Azure API I'm going to suggest retrying this deployment, and opening an issue with Microsoft Support if you see this again, since this is something which'd need to be investigated/fixed on their end. However since this isn't something we can fix in Terraform (since this is an issue in the Azure API) - I'm going to close this issue for the moment.

Thanks!
