### ISSUE TITLE
Building application gateway fails when local variable is used for name.

### ISSUE THREAD

**Issue by wimpienortje** [terraform-providers/terraform-provider-azurerm#748]
### Terraform Version
Terraform v0.11.2
+ provider.azurerm v1.0.1

### Affected Resource(s)
azurerm_application_gateway

### Terraform Configuration Files
Use the application gateway example (https://www.terraform.io/docs/providers/azurerm/r/application_gateway.html#example-usage).

Add the following at the top:

```hcl
locals {
  app_gateway_name = "my-application-gateway-12345"
}
```

Replace the gateway's name with:

```hcl
resource "azurerm_application_gateway" "network" {
  #name                = "my-application-gateway-12345"
  name                = "#{local.app_gateway_name}"

```

### Debug Output
(removed by @tombuildsstuff)

### Expected Behavior
Application gateway is created.

### Actual Behavior
Terraform exits with the following error from Azure:

```bash
Error: Error applying plan:

1 error(s) occurred:

* azurerm_application_gateway.network: 1 error(s) occurred:

* azurerm_application_gateway.network: Error Creating/Updating ApplicationGateway network.ApplicationGatewaysClient#CreateOrUpdate: Failure responding to request: StatusCode=405 -- Original Error: autorest/azure: Service returned an error. Status=405 Code="" Message="The requested resource does not support http method 'PUT'."
```

### Steps to Reproduce
1. Use the application gateway example configuration with modifications.
2. `terraform apply`

### Important Factoids
Changing the application gateway name back to string constant successfully creates the app gateway.

**Comment by tombuildsstuff** [comment]
hey @wimpienortje 

Thanks for opening this issue

Taking a quick look into this this appears to be a typo in the configuration rather than a bug with the Application Gateway resource; currently the variable's being referenced like so:

```
resource "azurerm_application_gateway" "network" {
  name = "#{local.app_gateway_name}"
  # ...
}
```

However this should be done using a `$` rather than a `#` ([associated documentation from the local values page](https://www.terraform.io/docs/configuration/locals.html) e.g.

```
resource "azurerm_application_gateway" "network" {
  name = "${local.app_gateway_name}"
  # ...
}
```

As such - currently the literal value `#{local.app_gateway_name}` is being sent to Azure (albeit URI-Encoded) - as can be seen in the URI from the logs you've provided  below:

> https://management.azure.com/subscriptions/0fb4e2a3-357d-4894-b1a4-c861c1fac7de/resourceGroups/my-rg-application-gateway-12345/providers/Microsoft.Network/applicationGateways/%23%7Blocal.app_gateway_name%7D?api-version=2017-09-01:

Would you be able to update the `#` to `$` and see if that fixes your issue?

Thanks!

(p.s. given the logs posted above contain the `Authentication` header, which is a sensitive field - I've removed the link for the moment)

**Comment by wimpienortje** [comment]
Hi @tombuildsstuff 

Thanks, that fixes the issue. Sorry for waisting your time with typos.

Is there a way to create logs that don't contain sensitive information?

**Comment by tombuildsstuff** [comment]
@wimpienortje no worries :)

> Is there a way to create logs that don't contain sensitive information?

Not yet - but it's something we've been thinking about for a while (the Authorization header is only needed there in certain circumstances e.g. provider dev - so we could probably put it behind a flag or something)

Given this issue is resolved I'm going to close this issue - but please feel free to reopen it if needed

Thanks!
