### ISSUE TITLE
azure function zip deployment

### ISSUE THREAD

**Issue by callppatel** [terraform-providers/terraform-provider-azurerm#7494]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

I am looking to deploy Azure function by using Terraform, in the same way which is mentioned here in the MS docs. https://docs.microsoft.com/en-us/azure/azure-functions/deployment-zip-push

One of my need to store and Storage SAS key to Key Vault. I have seen some example where we can below setting is used, but I can't use sas key without storing to Key Vault.

WEBSITE_RUN_FROM_ZIP = "https://${azurerm_storage_account.this.name}.blob.core.windows.net/${azurerm_storage_container.this.name}/${azurerm_storage_blob.this.name}${data.azurerm_storage_account_sas.this.sas}"

Above setting can't be use as I must need to store sas key to key vault. Any suggestion?

Thank you !
---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @callppatel 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by callppatel** [comment]
Thanks @tombuildsstuff , I raised this as "question" not as issue to get the expert advise. I am suspecting this may turn to be enhancement request. Anyway I have raised this to another forum as of now.
