### ISSUE TITLE
extended_auditing_policy supports only storage based auditing.

### ISSUE THREAD

**Issue by CharmanderJieniJieni** [terraform-providers/terraform-provider-azurerm#7501]
extended_auditing_policy supports only storage based auditing. 
What about Log Analytics and Event Hub based auditing?

_Originally posted by @tomjosekal in https://github.com/terraform-providers/terraform-provider-azurerm/issues/2217#issuecomment-596739079_

**Comment by CharmanderJieniJieni** [comment]
I am not able to do export to log analytics, seems only storage account option is available

**Comment by tombuildsstuff** [comment]
hi @CharmanderJieniJieni 

Thanks for opening this issue.

As you've mentioned at this time we don't support this - if you're looking for support for this feature then [please open a Feature Request to track this, which contains the information we need](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) to be able to support this.

Since this is a question rather than a bug/feature request in the Azure Provider I'm going to close this issue for the moment - but as mentioned above if you're looking for the Azure Provider to support this functionality then we should be able to track this in a new issue with the Feature Request template containing all of the information we need.

Thanks!
