### ISSUE TITLE
azure_linux_virtual_machine - Allocation failure of VM requires deleting or importing resource

### ISSUE THREAD

**Issue by KimShepherdVibrato** [terraform-providers/terraform-provider-azurerm#7516]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.24
+ provider.azurerm v2.3.0

### Affected Resource(s)

* `azurerm_linux_virtual_machine`

This likely affects `azurerm_windows_virtual_machine` and possibly `azurerm_virtual_machine` as well.

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_virtual_network" "example" {
  name                = "example-network"
  address_space       = ["10.0.0.0/16"]
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
}

resource "azurerm_subnet" "example" {
  name                 = "internal"
  resource_group_name  = azurerm_resource_group.example.name
  virtual_network_name = azurerm_virtual_network.example.name
  address_prefix       = "10.0.2.0/24"
}

resource "azurerm_network_interface" "example" {
  name                = "example-nic"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  ip_configuration {
    name                          = "internal"
    subnet_id                     = azurerm_subnet.example.id
    private_ip_address_allocation = "Dynamic"
  }
}

resource "azurerm_linux_virtual_machine" "example" {
  name                = "example-machine"
  resource_group_name = azurerm_resource_group.example.name
  location            = azurerm_resource_group.example.location
  size                = "Standard_F2"
  admin_username      = "adminuser"
  network_interface_ids = [
    azurerm_network_interface.example.id,
  ]

  admin_ssh_key {
    username   = "adminuser"
    public_key = file("~/.ssh/id_rsa.pub")
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  source_image_reference {
    publisher = "Canonical"
    offer     = "UbuntuServer"
    sku       = "16.04-LTS"
    version   = "latest"
  }
}
```

### Debug Output
```
Error: Error waiting for creation of Linux Virtual Machine "example-machine" (Resource Group "example-resources"): Code="AllocationFailed" Message="Allocation failed. We do not have sufficient capacity for the requested VM size in this region. Read more about improving likelihood of allocation success at http://aka.ms/allocation-guidance"

  on ../../modules/vm/main.tf line 32, in resource "azurerm_linux_virtual_machine" "example":
 32: resource "azurerm_linux_virtual_machine" example" {
```

### Expected Behavior

I am not sure of the expected behaviour, as I am not sure the correct way to handle this.

My feeling is the resource should be added to the state, but tainted.  Another option would be to simply have the VM exist in a deallocated state.  A subsequent deployment could initiate the allocation if it is not already done.

### Actual Behavior

The VM resource is created, but exists in a deallocated state.  Subsequent deployments fail because the resource exists, it must be manually imported or deleted in order for the deployment to succeed.

### Steps to Reproduce

This is difficult to reproduce because it only occurs when an otherwise valid VM configuration cannot be allocated.

**Comment by georgemihaescu** [comment]
Is it possible to revert `ShouldResourcesBeImported` to a Feature Flag, rather then `required`?

If a resource is created but not written to state, a subsequent run would error with "Resource already exists". Terraform would not adopt the resource, but would leave it an orphan.

I have a Linux Custom Script Extension that runs a bash. If that bash throws an error, Terraform will exit. Just fixing the script/retrying is not enough anymore, because I have to manually delete the Extension from Azure Portal, which kind of breaks automation.

**Comment by smurfralf** [comment]
This definitely happens with linx vm's. Another option is to avoid the condition in the first place by adding configuration to *_virtual_machine resources for retry count and retry interval so it will be adaptable to slow azure behavior after the first timeout condition.

**Comment by tombuildsstuff** [comment]
hey @KimShepherdVibrato 

Thanks for this issue - apologies for the delayed response here.

Unfortunately the Azure API (and in particular the Compute API) misuses the "Failed" state to mean several things, including "this won't recover" and "this took longer than the hard-coded hypervisor timeout to boot, but may recover", "this has failed and will be automatically cleaned up" and "this is fine, but the internal healthcheck failed".

Whilst it appears that the "Failed" state should be Terminal - unfortunately since this state isn't reliable Terraform isn't able to guarantee if a particular state is recoverable or not (or if it'll recover, or if it's safe to apply changes) - as such we intentionally require the operator to decide how to proceed here to prevent causing further issues.

In the case of this particular issue, I believe the Data Source requested in #7952 should ultimately solve this (by returning a list fo VM sizes which are actually available) - as such whilst I'd like to thank you for opening this issue, I'm going to close this in favour of #7952, would you mind subscribing to that issue for updates?

Thanks!
