### ISSUE TITLE
Azure Cognitive Services Anomaly Detector Not Supported

### ISSUE THREAD

**Issue by djmcalister** [terraform-providers/terraform-provider-azurerm#7518]
When will Azure Cognitive Services Anomaly Detector be supported?

**Comment by tombuildsstuff** [comment]
hi @djmcalister 

Thanks for opening this issue.

For Feature Requests there's several bits of information we need, which is why we ask users to fill out the issue template when creating a new Feature Request - as such would you mind [opening a new issue using the Feature Request issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) (which contains the information we need) so that we can take a look into this?

Thanks!
