### ISSUE TITLE
Improper state on AllocationFailed

### ISSUE THREAD

**Issue by CoRfr** [terraform-providers/terraform-provider-azurerm#753]
Hi,

I'm facing an issue that occurs when Azure returns an AllocationFailed error when creating a new VM.
Error looks like this:

* azurerm_virtual_machine.node.23: compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=200 -- Original Error: Long running operation terminated with status 'Failed': Code="AllocationFailed" Message="Allocation failed. Please try reducing the VM size or number of VMs, retry later, or try deploying to a different Availability Set or different Azure location."

Following that error, from the Terraform side, the VM does not exist. Even after a `terraform refresh` it is still not there.
From the Azure side, the VM does exist, but in a 'Failed' state.
Any operation after that requires the manual deletion of the VMs in Azure.
For instance, terraform tries to remove some resources associated to that VM (data disk, nic, ...) and fails because they are 'in use':

* azurerm_managed_disk.node_data.23: disk.DisksClient#Delete: Failure responding to request: StatusCode=409 -- Original Error: autorest/azure: Service returned an error. Status=409 Code="OperationNotAllowed" Message="Disk node23-data is attached to VM /subscriptions/<x>/resourceGroups/<x>/providers/Microsoft.Compute/virtualMachines/node23."

### Terraform Version
Terraform v0.11.2
+ provider.azurerm v1.0.1
+ provider.template v1.0.0

### Affected Resource(s)
- azurerm_virtual_machine

### Exected Behavior
I would expect terraform to 'know' about the failed VMs and provide a way to delete them.
If doing `terraform apply` after a while, I would expect terraform to try to recreate the VM (a little bit like a tainted VM).

### Actual Behavior
terraform doesn't know/ about/ignores the VM.

### Steps to Reproduce
To reproduce the AllocationFailed error, I guess you could do the exact opposite of what https://docs.microsoft.com/en-us/azure/virtual-machines/windows/allocation-failure recommends.
Maybe create an availability set (that's the issue in my case I think) and try to create VMs until it fails to do so.
For me that happens when instantiating about 30 `Standard_DS13_v2_Promo` in `WestUS`. But sometimes it happens when requesting 5. 
Note that for the problem to become annoying, the VM must have a resource associated with it, such as a NIC or data disk.

**Comment by CoRfr** [comment]
Issue also occurs on OSProvisioningTimedOut, and I assume any kind of VM failure:
-  Provisioning failed. OS provisioning failure has reached terminal state and is non-recoverable for VM 'prod-node14'. Consider deleting and recreating this virtual machine. Additional Details: {
 "resourceType": "Microsoft.WindowsAzure.ComputeResourceProvider.Core.Shared.Strings, CRP.Core.Shared, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null",
 "ResourceCode": "OSProvisioningTimedOut",
 "ResourceParameters": [
 "prod-node14"
 ]
 }. OSProvisioningTimedOut

**Comment by jambt** [comment]
The same behaviour can be seen with an AKS cluster (failed state due to wrongly specified machine type).

**Comment by tombuildsstuff** [comment]
hi @CoRfr @jambt 

Thanks for opening this issue :)

Terraform only manage resources that have been successfully provisioned by Terraform (or resources which have been imported into the State). When a provisioning failure happens (such as in this case) the Operator needs to decide how to proceed - such as deleting the failed resource (such as when there's a capacity issue in Azure) or by Importing it back into Terraform using [the `terraform import` command](https://www.terraform.io/docs/import/index.html).

Whilst we may be able to do something to determine how to recover automatically (for instance destroying & recreating the VM), there's no guarantee that wouldn't cause issues elsewhere since no two environments are the same (which is why the operator needs to decide how to proceed). In the future additional validation may help to prevent some of these issues (such as the wrong machine type for AKS) - however since this isn't something we're going to be able to fix anytime soon - I'm going to close this issue for the moment. 

Thanks!
