### ISSUE TITLE
Support for providing whole Logic App JSON definition in azurerm_logic_app_workflow

### ISSUE THREAD

**Issue by ZachTB123** [terraform-providers/terraform-provider-azurerm#7542]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Logic Apps can be created using the `azurerm_logic_app_workflow` resource and then you can define the workflow using the various trigger and action resources. As someone who creates a workflow first using the `Logic app designer` in the portal, it would be beneficial if I could just copy and paste the JSON that is available in the portal (under `Logic app code view`) into a resource rather than deconstructing that into separate trigger and action resources. For this reason, I am currently deploying all my Logic Apps using an ARM template from the [azurerm_template_deployment](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html) resource.

### New or Affected Resource(s)

* `azurerm_logic_app_trigger_custom`

### Potential Terraform Configuration

```hcl
resource azurerm_resource_group example {
  name     = "workflow-resources"
  location = "East US"
}

resource azurerm_logic_app_workflow example {
  name                = "workflow1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  definition = <<EOF
{
# Logic App definition here
}
EOF
}
```

### References

This would end up being similar to how handling the definition works for [aws_sfn_state_machine](https://www.terraform.io/docs/providers/aws/r/sfn_state_machine.html).

* #0000

**Comment by tombuildsstuff** [comment]
hi @ZachTB123 

Thanks for opening this issue.

Before diving into this, I think it's probably worth explaining why the resources are designed the way they are.

Logic Apps have primarily been designed with the expectation they'll be managed in the GUI inside the Azure Portal. Whilst they do support being managed through the ARM API's (and Templates) - this arguably isn't the primary interaction model - and the API's aren't really designed with this model in mind.

Ultimately this means the integration options for this are essentially submitting a giant JSON blob and hoping it works, which whilst can work in some circumstances ends up causing other issues around chaining dependencies (either during creation, or destroy). In order to correctly map dependencies you'd need to first apply one workflow, then configure the dependencies, then re-configure the workflow to include the dependencies.

Whilst that model works for ARM Templates, since most folks (in my experience) are wrapping the Template Deployment with either a Bash/PowerShell script anyway - this isn't something that works in Terraform, since this'd lead to either conflicting/circular reference between resources.

---

For comparison - Data Factory has a similar scope to Logic Apps insofar as it supports interacting/plugging into a large number of external sources; however the key difference between the two is the way the API's designed, insofar as there's endpoints to add new Data Sets/Linked Services to this.

What this means is that it's possible to create composable resources together, for example creating a Data Factory, then the Database and then link the services as required in a single run.

---

Due to the way the Logic Apps API is currently designed, unfortunately adding a field for `definition` won't work in Terraform, since users will either end up with circular references between resources - or be unable to detect drift between these resources. As such unfortunately at this point in time we're forced to implement these as virtual resources to be able to correctly represent dependencies between resources (and track diff's).

Whilst I appreciate this does diverge from the Azure API - to be able to correctly represent Logic Apps in Terraform we need to manage the `definition` field via these Virtual Resources.

Ultimately this comes down to the design of the Logic Apps API being unsuited to Terraform - where the Logic Apps API needs endpoints for managing connections, parameters and actions (amongst other things). As such I'd suggest the best path forward here would be to work with the Service Team to expose the necessary API's to fully support Logic Apps as Code going forward (which'll aid everybody integrating with Logic Apps, rather than just Terraform).

However for the reasons outlined above unfortunately we have no plans to expose the `definition` field in the `azurerm_logic_app_workflow` and as such I'm going to close this issue for the moment.

Thanks!
