### ISSUE TITLE
Create AKS cluster using node_resource_group option

### ISSUE THREAD

**Issue by LTomer** [terraform-providers/terraform-provider-azurerm#7562]
Hi,

I am trying to create a cluster using node_resource_group option that refers to a resource group.
Example: node_resource_group = azurerm_resource_group.k8s-node-rg.name

After I run terraform apply I received the error:
Error: creating Managed Kubernetes Cluster "AKS-Platform-Cluster-test" (Resource Group "RG-aks-platform-test"): containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="NodeResourceGroupAlreadyExists" Message="Node resource group 'MC_RG-aks-platform-test_AKS-Platform-Cluster-test_westeurope' under subscription 'XXX' already exists, please provide a new one."

I am using:
+ Terraform v0.12.28
+ provider.aws v2.68.0
+ provider.azurerm v2.16.0

Any idea who I can solve this?

**Comment by tombuildsstuff** [comment]
hi @LTomer 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
