### ISSUE TITLE
I'm having the same issue as well on: InvalidLoadBalancerProfile

### ISSUE THREAD

**Issue by sagivle** [terraform-providers/terraform-provider-azurerm#7564]
I'm having the same issue as well on:
- Terraform v0.11.8
- provider.azurerm v1.44.0
When I do a re-apply after adding a tags block in the code, I was getting the same error message:
```
Error: Code="InvalidLoadBalancerProfile" Message="Load balancer profile must
specify one of ManagedOutboundIPs, OutboundIPPrefixes and OutboundIPs." 
Target="networkProfile.loadBalancerProfile"
```
My network_profile block is below:
```
  network_profile {
    network_plugin     = var.cluster_network_plugin
    dns_service_ip     = var.cluster_dns_service_ip
    docker_bridge_cidr = var.cluster_docker_bridge_cidr
    service_cidr       = var.cluster_service_cidr

    # Standard LoadBalancer is required for multiple nodepools.
    load_balancer_sku = "standard"

    # Use a single IP for outbound traffic
    load_balancer_profile {
      outbound_ip_address_ids = [azurerm_public_ip.outbound.id]
    }
  }
```

_Originally posted by @nivhty in https://github.com/terraform-providers/terraform-provider-azurerm/issues/6525#issuecomment-630580065_

**Comment by tombuildsstuff** [comment]
hi @sagivle 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by sagivle** [comment]
its a bug so why are you sending me somewhere else?
