### ISSUE TITLE
Provider "features" required field

### ISSUE THREAD

**Issue by brettcurtis** [terraform-providers/terraform-provider-azurerm#7572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

This is problematic if you're working on module development. We do not use providers at the module level only on a root module like described [here](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules.).

This makes running testing pipelines for these more difficult then it needs to be. I found [this](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7013) but I just don't feel like it aligns. Having a required field in something that's not required nor recommended. We should be able to develop on a child module without using a root module. We do this on Google for sure and I think AWS, seems azure is the odd one out here. Thoughts? 

### References

* #7013

**Comment by tombuildsstuff** [comment]
hi @brettcurtis 

Thanks for opening this issue.

Reading through here I think there's a two points to respond to here:

> 1. Why is the Features block required?

Version 2.0 of the Azure Provider introduced the `features` block within the `provider` block to be able to control the behaviour of the Provider. For example this allows Terraform to roll the nodes in a VM Scale Set when cycling the image using a Manual upgrade policy - or to delete/retain the OS Disk on Virtual Machines as necessary.

This is located on the Provider rather than the individual resources for a number of reasons - however having this in a single place does ensure that users are aware of which instance of a Provider, with which behaviour is being used - since for example deleting the OS Disks for Virtual Machines automatically may be fine in some environments but an issue in others.

Prior to version 2.0 of the Azure Provider, it was possible to  technically avoid specifying a Provider block (by specifying all the values necessary via Environment Variables or using Azure CLI auth) - which, whilst helpful in some circumstances (such as this one) ended up causing significant confusion to new users unaware they were using multiple instances of a provider.

It's worth noting that other Terraform Providers also require defining arguments (by default) in their Provider blocks - for example the AWS Provider requires the Region is specified in the Provider block.

Whilst we could look to introduce an Environment Variable to source the Features block (as mentioned in #5866) - unfortunately that just brings us back to the same issue, which caused a large number of issues/confusion previously - as such unfortunately that isn't something we plan to support at this time.

> 2. What's the recommendation for building Terraform Modules for AzureRM?

When building Terraform Modules (in general) we [recommend defining a Provider block in the root and then passing this into the module](https://www.terraform.io/docs/configuration/modules.html#providers-within-modules), for example:

```
provider "azurerm" {
  version = "=2.17.0"
  features {}
}

module "test" {
  source   = "./modules/example"
  prefix   = "example22"
  location = "West Europe"

  providers = {
    "azurerm.default" = "azurerm"
  }
}
```

Whilst (as mentioned above) in some circumstances it's possible to avoid threading providers through from the root module - that's arguably a bug in Terraform Core.

When building modules one option to be able to accurately reflect this is to include a `./test` folder containing example usage ([for example](https://github.com/tombuildsstuff/terraform-module-pandamonium)) - which passes both the Provider block (and any values necessary) through to the module being called.

---

Since the `features` block is intentionally marked as Required to make it explicit which instance of a Provider is being used - unfortunately this isn't something we plan to make Optional and as such I'm going to close this issue for the moment.

Thanks!

**Comment by brettcurtis** [comment]
This is perfect, thanks for the example!
