### ISSUE TITLE
terraform cloud run error: "features" required field is missing

### ISSUE THREAD

**Issue by sensei-wu** [terraform-providers/terraform-provider-azurerm#7577]
I am currently evaluating tf cloud and get the following error
![Screenshot from 2020-07-03 14-07-00](https://user-images.githubusercontent.com/5805667/86467923-a3ab0800-bd36-11ea-9a36-4cec671c9235.png)

My code looks like below

```
provider "azurerm" {
  version = "=2.0.0"
  features {}
}

terraform {
  backend "remote" {
    hostname = "app.terraform.io"
    organization = "zen-poc"

    workspaces {
      name = "zen-azure"
    }
  }
}
```

So I was already following the recommendation to include an empty features block.

It used to work when I run with a different remote backend (azure state store)

thanks!

**Comment by tombuildsstuff** [comment]
hi @sensei-wu 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
