### ISSUE TITLE
Azure provider 2.x not working on smb

### ISSUE THREAD

**Issue by Aschenbecher** [terraform-providers/terraform-provider-azurerm#7595]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

I made already an Issue report here:

### References
* #7326 
* https://github.com/terraform-providers/terraform-provider-azurerm/issues/7326#issuecomment-653519105

To help pointing this issue take a look here:
* https://github.com/hashicorp/terraform/issues/17115

Meanwhile I know, that the reason for the error is, that the Terraform files are on a smb share. Since the new Provider Version it's not working anymore from smb. Please check my first report and last comment for details !

**Comment by tombuildsstuff** [comment]
hi @Aschenbecher 

Thanks for opening this issue!

Taking a look through here it appears that this is an issue regarding Terraform Core, rather than something specific to the Azure Provider (so it'd need to be fixed in Terraform Core or one of it's dependencies) - as such [would you mind opening an issue on the Terraform Core repository](https://github.com/hashicorp/terraform) so that the Terraform Core team can take a look?

Thanks!

**Comment by Aschenbecher** [comment]
@tombuildsstuff Oh sorry, but this is not a Terraform problem, it just happens with the azure provider and just since the upgrade to 2.x . We still using other providers from smb shares....
