### ISSUE TITLE
Including 'Name' in network restriction under Access restrictions in App Service

### ISSUE THREAD

**Issue by kalyanrajsista** [terraform-providers/terraform-provider-azurerm#7611]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

How can I specify Name for the ip being restricted for an app service? For now, I can use ip_address. It would be good to have an associated name to the ip_address.

### New or Affected Resource(s)

* azurerm_app_service
* site_config
* ip_restrictions

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume this request has been implemented. See the [implementation](https://github.com/terraform-providers/terraform-provider-azurerm/blob/5398042b0c7e3e2fb618ae69bb3abe39ff1b19db/azurerm/helpers/azure/app_service.go#L319).

**Comment by tombuildsstuff** [comment]
hi @kalyanrajsista 

Thanks for opening this issue.

Support for this is [available the `name` field within the `ip_restrictions` block](https://www.terraform.io/docs/providers/azurerm/r/app_service.html#name-3) - would you be able to take a look and see if that works for you? Since support for this is already available I'm going to close this issue for the moment but if that doesn't work for you I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
