### ISSUE TITLE
Output from azurerm_public_ip fails on first run

### ISSUE THREAD

**Issue by PleaseStopAsking** [terraform-providers/terraform-provider-azurerm#764]
### Terraform Version

```
Terraform v0.11.2
+ provider.azurerm v1.0.1
```

### Terraform Configuration Files

```hcl
resource "azurerm_public_ip" "GWPublicIP" {
		name                          = "${var.customerAcronym}-${var.environment}-applicationGateway-ip"
		location                      = "${var.location}"
		resource_group_name           = "${azurerm_resource_group.rg.name}"
		public_ip_address_allocation  = "dynamic"

		tags {
    	environment = "${var.environment}"
  	}
}

output "public_ip" {
  	value = "${azurerm_public_ip.GWPublicIP.fqdn}"
}
```

### Expected Behavior

The output should show the FQDN the first time it is run.

### Actual Behavior

The template fails with the error `* output.public_ip: Resource 'azurerm_public_ip.GWPublicIP' does not have attribute 'fqdn' for variable 'azurerm_public_ip.GWPublicIP.fqdn'`

### Steps to Reproduce

1. `terraform init`
2. `terraform plan`
3. `terraform apply`
4. Once deployment fails, run `terraform apply` again which will succeed and the output value will include the FQDN.

**Comment by PleaseStopAsking** [comment]
*Updated issue to reflect that issue is not with Application Gateway but with the Public IP module.

**Comment by tombuildsstuff** [comment]
hi @PleaseStopAsking @bingosummer 

Thanks for opening this issue :)

The error messages you're seeing are because a Dynamic Public IP Address isn't given an IP Address until it's attached to a (powered on) device, such as a Virtual Machine.

Whilst this isn't ideal, it's a known behaviour of Azure - as such we can't work around this automatically; instead [we document this behaviour on the `azurerm_public_ip` resource page](https://www.terraform.io/docs/providers/azurerm/r/public_ip.html#ip_address) in which we suggest using [the `azurerm_public_ip` data source](https://www.terraform.io/docs/providers/azurerm/d/public_ip.html) to access the IP Address of the Public IP once it's attached to a device. [Here's an example of how you can use the Data Source to retrieve the Public IP of a Dynamic Public IP Address](https://www.terraform.io/docs/providers/azurerm/d/public_ip.html#example-usage-retrieve-the-dynamic-public-ip-of-a-new-vm-).

Since this is a known issue (with a workaround) - I'm going to close this issue for the moment - but please feel free to reopen this issue if that doesn't work and we'll take another look :)

Thanks!

**Comment by PleaseStopAsking** [comment]
Hi @tombuildsstuff 

I tested this alongside the deployment of an App Gateway as well as a VM that gets associated with the public ip and it still seems to be failing on the first run. I simply stripped the resources down to the bare minimum for the issue.

I am happy to test it again and provide output if needed but I think the issue is still present even if the ip is attached to a device.

Thanks!

**Comment by toorog** [comment]
The initial issue was about the property `fqdn` and not `ip_address`. For IP it is documented now, but FQDN should be available immediately as it is specified in the resource. So what would be the way to get the FQDN of a dynamic IP that is not associated yet?
