### ISSUE TITLE
Role assignment on a resource with CanNot delete lock

### ISSUE THREAD

**Issue by rajnemani** [terraform-providers/terraform-provider-azurerm#7668]
i am running into this issue running Terraform destroy.  I have a storage account that is deployed via different deployment (different TF workspace and different RG in Azure.  This Storage account is locked for a good reason. I have another deployment that creates a role assignment for an MSI to this storage account .  All this works fine except when doing a destroy it complains that it cannot delete the role assignment because the storage account is locked.  Currently i have to remove the lock on the storage account, then run destroy and go and put the lock back. https://github.com/terraform-providers/terraform-provider-azurerm/pull/1887 says it is fixed.  Any thoughts are appreciated.
---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @rajnemani 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
