### ISSUE TITLE
Make default_node_pool in azurerm_kubernetes_cluster optional

### ISSUE THREAD

**Issue by davelosert** [terraform-providers/terraform-provider-azurerm#7686]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

With the introduction of the custom system-node-pools, it would be great if the `default_node_pool` setting could be made optional. This would make the configuration of several node pools easier and more clear. 

In our scenario, we have 3 "custom" node pools (configured with `azurerm_kubernetes_cluster_node_pool`) that we provision with a `for_each` loop for convenience.

We created the `default_node_pool` more or less only because it was a required field.
However, now we'd like to promote one of our existing "custom" node pools to be the `system` node pool and get rid of the default one.

As of right now, this would only be possible by splitting the configuration for `for_each` (see an example below) and also by defining pools in two different locations (`azurerm_kubernetes_cluster.default_node_pool` and `azurerm_kubernetes_cluster_node_pool).

Would this be possible? Or is there a reason I don't see that the `default_node_pool` still exists? 

### New or Affected Resource(s)

* azurerm_kubernetes_cluster
* azurerm_kubernetes_cluster_node_pool 

### Potential Terraform Configuration

```hcl


resource "azurerm_resource_group" "example" {
  name     = "example-resources"
  location = "West Europe"
}

resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  service_principal {
    client_id     = "00000000-0000-0000-0000-000000000000"
    client_secret = "00000000000000000000000000000000"
  }
}

locals {
  node_pools = [
     {
        name = "nodepool-1"
        mode = "system"
     },
     {
        name = "nodepool-2"
        mode = "user"
     },
     {
        name = "nodepool-3"
        mode = "user"
     }
  ]
}

resource "azurerm_kubernetes_cluster_node_pool" "example" {
  for_each             = local.node_pools
  name                  = each.name
  mode                  = each.mode
  kubernetes_cluster_id = azurerm_kubernetes_cluster.example.id
  vm_size               = "Standard_DS2_v2"
  node_count            = 1

  tags = {
    Environment = "Production"
  }
}

```

### References

* https://docs.microsoft.com/en-us/azure/aks/use-system-pools
* https://docs.microsoft.com/en-us/azure/aks/use-system-pools#delete-a-system-node-pool

**Comment by davelosert** [comment]
As this now got flagged as question - it actually is a feature request 🙈 

Deleting the default pool is possible in AKS - even if you initially need to create it, see:
https://docs.microsoft.com/en-us/azure/aks/use-system-pools#delete-a-system-node-pool 

> To use system node pools on AKS clusters before API version 2020-03-02, add a new system node pool, then delete the original default node pool.
Previously you could not delete the system node pool, which was the initial default node pool in an AKS cluster. You now have the flexibility to delete any node pool from your clusters. Since AKS clusters require at least one system node pool, you must have at least two system node pools on your AKS cluster before you can delete one of them.

Would be great if this would be possible with Terraform as well. 
It also should not cause a cluster recreation (which I think is default right now when changing something with the `default_node_pool`).

**Comment by tombuildsstuff** [comment]
hi @davelosert 

Thanks for opening this issue.

At this time the AKS API requires creating a System Node Pool by default - as such whilst we've raised this use-case with the AKS Team - unfortunately this isn't something that's possible right now (which is why this is Required).

As mentioned above we've raised this with the AKS Team - so they're aware of this request - however there's not much we can do about this until the API supports this behaviour. Whilst we could look to provision a "fake" system node pool by default - we'd also need to add this back in were all system node pools removed - it's certainly possible but is going to require a lot of testing/thought to confirm the behaviour makes sense here (including, likely locking on provisioning node pools which has other downsides).

For the moment I'm going to close this issue in favour of #7093 - which is tracking replacing the system node pool (e.g. cycling it without it being ForceNew) - since I believe this'll ultimately be fixed at the same time - would you mind subscribing to that issue for updates?

Thanks!
