### ISSUE TITLE
Azure Shared Image Gallery: Code="PropertyChangeNotAllowed" Message="Changing property 'zoneResilient' is not allowed."

### ISSUE THREAD

**Issue by archmangler** [terraform-providers/terraform-provider-azurerm#7707]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform `v0.11.11`
azurerm `1.32.0`  (tested same behaviour up to provider `1.32.8`)

### Affected Resource(s)

* `azurerm_image`

### Terraform Configuration Files

```hcl


resource "azurerm_image" "instance2" {

  count    = "${length(var.image_blobs)}"

  name     = "img-${var.buCode}-${var.subCode}-az1-${element(split(" ",var.image_blobs[count.index]),0)}"

  location = "${var.location}"

  resource_group_name = "rsg-${var.buCode}-${var.subCode}-az1-managedimages"

  os_disk {

    os_type = "${element(split(" ",var.image_blobs[count.index]),2)}"
    os_state = "Generalized"

    blob_uri = "https://sta${var.buCode}${var.subCode}az1osimages.blob.core.windows.net/osimage/${element(split(" ",var.image_blobs[count.index]),1)}"

    size_gb  = 120

  }

}
```

### Debug Output

 https://gist.github.com/archmangler/ccf511e7478040261105faacd3a4e5e7

### Panic Output

n/a

### Expected Behavior

Azure Shared Image should be created without any objection to changing the zone_resilient parameter.

### Actual Behavior

- Shared image creation fails with this error:

```
azurerm_image.instance2.0: compute.ImagesClient#CreateOrUpdate: Failure sending request: StatusCode=0 -- Original Error: autorest/azure: Service returned an error. Status=<nil> Code="PropertyChangeNotAllowed" Message="Changing property 'zoneResilient' is not allowed." Target="zoneResilient"
```

### Steps to Reproduce

1. `terraform apply`

### Important Factoids

Region: Azure Southeast Asia Region.

### References

* #0000

**Comment by ArcturusZhang** [comment]
Hi @archmangler thanks for this issue!

First thing is that based on the script you posted and the output logs, you are using the `azurerm_image` resource, which is totally different from the shared image gallery and the shared image resource. Could you please double check your title?

And second thing is that the `zoneResilient` indeed does not allow changing by the design of the Azure API. Therefore in terraform we marked that attribute as ForceNew, meaning that if you want to change that attribute, you will have to recreate the whole resource. From the output log you posted, you are using a predefined plan, in that plan, terraform is attempting to an in-place create by changing the  `zoneResilient` from null to `false`. And `zoneResilient` has a default value `true, this is equivalent as you are updating `zoneResilient` from `true` to `false`.

I suggest you try a new plan rather than using this existing one and see if this problem persists.

**Comment by tombuildsstuff** [comment]
hi @archmangler 

Taking a look into this this has been fixed in a newer version of the Azure Provider - we're currently on version v2.21.0 - which you can upgrade to by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=2.21.0"
  features {}
}
```

.. which should solve this for you - would you be able to take a look and see if that works for you?

Since this should be fixed by updating the version of the Azure Provider being used here I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
