### ISSUE TITLE
Error: Upload failed: wait: remote command exited without exit status or exit signal

### ISSUE THREAD

**Issue by chandan8893** [terraform-providers/terraform-provider-azurerm#7710]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

Hi Team, I am getting the below error while copying a file from local to provisioner VM using file provisioner. I have been stuck for a while on this
Pleas help
Terraform v0.12.28

[error.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/4910829/error.txt)

**Comment by tombuildsstuff** [comment]
hi @chandan8893 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
