### ISSUE TITLE
Invalid value for "lists" parameter: list of string required.

### ISSUE THREAD

**Issue by akoliya01** [terraform-providers/terraform-provider-azurerm#7732]
Hello, I am facing an issue while I am trying to join multiple strings.

Ultimately my goal is, I want to create a different resource group in azure with the help of the same set of code.

For Example, I want to create below four resource group.
    1.  rg-14-westindia-app
    2.  rg-15-westindia-app
    3.  rg-24- centralus-app
    4.  rg-25-centralus-app

So, my variable.tf file looks like below one

```

variable "env" {
  description = "env : dev or test"
}

variable "number" {
  description = "number : four or five"
}


variable "resource_group" {
  type = map(string)
    default = {
      dev = "rg-1"
      test = "rg-2"
      four = "4"
      five = "5"    
    }  
}

variable "resource_group_webapp" {
  type = map(string)
    default = {
      dev = "-westindia-app"
      test =  "centralus-app
      four = "4"
      five = "5"
    }  
}


variable "location" {
  type = map(string)
    default = { 
      dev  = "westindia"
      test = "centralus"
      four = 4
      five = 5
    }  
}

```

My main.tf file looks like below one.

```
provider "azurerm" {
 version = "=2.14.0"
 features { }  
}

resource "azurerm_resource_group" "portal" {
    name        =    "${join("${lookup(var.resource_group, var.env)}" , "${lookup(var.resource_group, var.number)}", "${lookup(var.resource_group_webapp, var.env)}")}"
    location = "${lookup(var.location, var.env)}"
}
```

**Comment by tombuildsstuff** [comment]
hi @akoliya01 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
