### ISSUE TITLE
Is anybody able to create internal load balancer in azure using terraform..

### ISSUE THREAD

**Issue by bhushangholve2006** [terraform-providers/terraform-provider-azurerm#774]
This is an open question about azurerm provider.
1) I need to create internal load balancer without front end IP configuration using terraform script is this possible?
If yes please provide me link....
When I try this I get error
 `Error Creating/Updating LoadBalancer network.LoadBalancersClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="LoadBalancerWithoutFrontendIPCantHaveChildResources" Message="Load Balancer /subscriptions/0000000-0000-0000-0000-000000000/resourceGroups/myresourcegr/providers/Microsoft.Network/loadBalancers/vmss-lb does not have Frontend IP Configuration, but it has other child resources. This setup is not supported." Details=[]`

2) If above is possible I need to attach private IP to my internal load balancer.
How anyone should do it.

**Comment by bpoland** [comment]
To attach a private IP to your internal load balancer, you still need a frontend_ip_configuration block.  But instead of a public_ip_address_id, you put a subnet_id (and specify a private IP address if you want it to be static).  See the doc here: https://www.terraform.io/docs/providers/azurerm/r/loadbalancer.html

**Comment by bhushangholve2006** [comment]
@bpoland 
worked well.
Thank you for your response on this.

**Comment by bpoland** [comment]
Cool, no problem.
