### ISSUE TITLE
FQDN for azurerm_firewall_network_rule_collection

### ISSUE THREAD

**Issue by 2mol** [terraform-providers/terraform-provider-azurerm#7743]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Azure Firewall now supports setting FQDN rules (rules based on domain names) directly under the Network Rules. This is in addition to IP address rules and Service Tags.

It would be great to be able to set FQDN rules via Terraform.

For context, Network Security Groups accept strings like service tags in the destination address fields.

### New or Affected Resource(s)

- `azurerm_firewall_network_rule_collection`

**Comment by annerajb** [comment]
No wonder I can't find it <_<.

Would also love to be able to set this on Terraform

**Comment by magodo** [comment]
@2mol and @annerajb Thank you for submitting this :+1:
In order to enable FQDN on network rules, one will need to enable DNS proxy on the firewall.

Both functionalities are now in the preview state, accordingly, there is no dedicated property defined, for example, DNS setting. Instead, the current API put those settings in the `additionalProperties`, which is not ideal to be involved in provider codebase, unfortunately.

After this functionality is stabalized in API, then we shall begin to implement that.

**Comment by annerajb** [comment]
Ah thanks for reminding me about DNS settings on the firewall.
