### ISSUE TITLE
Cannot login using AAD credentials when using Microsoft.Azure.ActiveDirectory.AADLoginForWindows extension

### ISSUE THREAD

**Issue by hugo-paredes** [terraform-providers/terraform-provider-azurerm#7748]
### Terraform (and AzureRM Provider) Version

```bash
Terraform v0.12.28
+ provider.azurerm v2.18.0
```

### Affected Resource(s)

* `azurerm_virtual_machine_extension`

### Terraform Configuration Files

```hcl
resource "azurerm_windows_virtual_machine" "scheduler" {
  name                = "vm-${local.resource_name_suffix}"
  computer_name       = var.vm_computer_name
  resource_group_name = azurerm_resource_group.default.name
  location            = azurerm_resource_group.default.location
  size                = var.vm_size

  admin_username = var.vm_admin_username
  admin_password = azurerm_key_vault_secret.vm_admin_password.value

  network_interface_ids = [
    azurerm_network_interface.default.id,
  ]

  identity {
    type = "SystemAssigned"
  }

  os_disk {
    caching              = var.vm_os_disk_caching
    storage_account_type = var.vm_os_disk_storage_account_type
  }

  source_image_reference {
    publisher = var.vm_image_publisher
    offer     = var.vm_image_offer
    sku       = var.vm_image_sku
    version   = var.vm_image_version
  }

  tags = local.tags
}

resource "azurerm_virtual_machine_extension" "aad" {
  name                       = "aad-${local.resource_name_suffix}"
  publisher                  = "Microsoft.Azure.ActiveDirectory"
  type                       = "AADLoginForWindows"
  type_handler_version       = "1.0"
  auto_upgrade_minor_version = true
  virtual_machine_id         = azurerm_windows_virtual_machine.scheduler.id

  tags = local.tags
}
```

### Expected Behavior

All resources are created without any problems. When I try to login to the Windows VM, via remote desktop, using the AAD user, I expect that Windows let's me login.

### Actual Behavior

When I attempt to login, I get an error message saying the following:

* The credentials that were used to connect to XXX.XXX.XXX.XXX did not work. Please enter new credentials.

Now, when I create another VM using the portal in the same resource group and select the AAD option, I'm able to login using the same credentials. The only difference, from what I saw, is that the handler version of the extension created via terraform is 1.0 and the one created via portal is 0.4.1. If I set version 0.4 in terraform, I have an error and I cannot proceed.

Any ideas why I cannot login?

Thanks.

**Comment by ArcturusZhang** [comment]
Hi @hugo-paredes thanks for opening this issue!

Since the one works created by portal and the one that does not work created by terraform is not exactly the same and the difference between them sounds to be quite an important factoid, could you please try on the portal to create an extension with version 1.0? (I assume maybe you cannot create it on portal, it may have a reason, for instance, it has known issue and will not work in some circumstances, only guessing).

Therefore to me the part that may be an issue in terraform should be "If I set version 0.4 in terraform, I have an error and I cannot proceed.". Could you please provide some error message about this error?

**Comment by hugo-paredes** [comment]
Hi @ArcturusZhang.

When I said that they look the same, it's because the only difference, according to the `az vm extension show` command. 
For the extension created via Terraform, I get this:

```shell script
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/...",
  "instanceView": null,
  "location": "westeurope",
  "name": "aad-d-we1-wherescape-poc",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.ActiveDirectory",
  "resourceGroup": "rg-d-we1-wherescape-poc",
  "settings": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "1.0",
  "virtualMachineExtensionType": "AADLoginForWindows"
}
```

And this is for the extension created by Azure via the portal:

```shell script
{
  "autoUpgradeMinorVersion": true,
  "forceUpdateTag": null,
  "id": "/subscriptions/...",
  "instanceView": null,
  "location": "westeurope",
  "name": "AADLoginForWindows",
  "protectedSettings": null,
  "provisioningState": "Succeeded",
  "publisher": "Microsoft.Azure.ActiveDirectory",
  "resourceGroup": "rg-d-we1-wherescape-poc",
  "settings": null,
  "tags": null,
  "type": "Microsoft.Compute/virtualMachines/extensions",
  "typeHandlerVersion": "0.3",
  "virtualMachineExtensionType": "AADLoginForWindows"
}
```

Now, when I update the version in Terraform, as you can see below, this is the error I get:

```hcl
resource "azurerm_virtual_machine_extension" "aad" {
  name                       = "aad-${local.resource_name_suffix}"
  publisher                  = "Microsoft.Azure.ActiveDirectory"
  type                       = "AADLoginForWindows"
  type_handler_version       = "0.3"
  auto_upgrade_minor_version = true
  virtual_machine_id         = azurerm_windows_virtual_machine.scheduler.id

  tags = local.tags
}
```

```shell script
azurerm_virtual_machine_extension.aad: Creating...
azurerm_virtual_machine_extension.aad: Still creating... [10s elapsed]
azurerm_virtual_machine_extension.aad: Still creating... [20s elapsed]
azurerm_virtual_machine_extension.aad: Still creating... [30s elapsed]
azurerm_virtual_machine_extension.aad: Still creating... [40s elapsed]
azurerm_virtual_machine_extension.aad: Still creating... [50s elapsed]
azurerm_virtual_machine_extension.aad: Still creating... [1m0s elapsed]

Error: Code="VMExtensionHandlerNonTransientError" Message="The handler for VM extension type 'Microsoft.Azure.ActiveDirectory.AADLoginForWindows' has reported terminal failure for VM extension 'aad-d-we1-wherescape-poc' with error message: 'Install failed for plugin (name: Microsoft.Azure.ActiveDirectory.AADLoginForWindows, version 0.4.1.1) with exception Command C:\\Packages\\Plugins\\Microsoft.Azure.ActiveDirectory.AADLoginForWindows\\0.4.1.1\\AADLoginForWindowsHandler.exe of Microsoft.Azure.ActiveDirectory.AADLoginForWindows has exited with Exit code: -2145648639'.\r\n    \r\n'Install handler failed for the extension. More information on troubleshooting is available at https://aka.ms/vmextensionwindowstroubleshoot'"

  on src/virtual_machine.tf line 34, in resource "azurerm_virtual_machine_extension" "aad":
  34: resource "azurerm_virtual_machine_extension" "aad" {
```

It doesn't matter which version I use, `0.3` or `0.4`. And these are the versions I've available:

```shell script
$ az vm extension image list-versions --publisher Microsoft.Azure.ActiveDirectory -l westeurope -n AADLoginForWindows -otable
Location    Name
----------  -------
westeurope  0.3.0.0
westeurope  0.3.1.0
westeurope  0.4.1.0
westeurope  0.4.1.1
westeurope  1.0.0.0
```

Cheers.

**Comment by hugo-paredes** [comment]
Hi.
Did anyone had the opportunity to have an extra look at this?
Thanks.
Hugo

**Comment by ShahradGH** [comment]
Hello All,

I can confirm the same behaviour as @hugo-paredes and only v1.0 handler working but failing to install due to error messages such as "This OS is not supported by MDM" when it is installed on VMs that are Windows 2019/Windows 10.

When other versions are specified, it is then claimed in terraform apply that the wrong typehandler is presented, so its locked into requiring 1.0

I have had to go around this with a mid-pipeline (I am using DevOps here) step to check and install AAD Extension using AzCLI to move past this.

Supporting @hugo-paredes here, please see me code below 

Note. Ignore count.index, it is to allow it to install to the number of specified VMs in this stack.
Note 2. Despite no reference, the mdmId was required to progress this to the error messages based on handler version and it is obtained via the export of the virtual machine principal ID when the vm was built using the flag for SystemAssigned Identitiy

`#deploys extension to enable aad login for windows
 resource "azurerm_virtual_machine_extension" "aadlogin" {
    name = "ext-aadlogin-${count.index}"
    count = var.instance_count
    virtual_machine_id = element(azurerm_virtual_machine.vm.*.id,count.index)
    publisher = "Microsoft.Azure.ActiveDirectory"
    type = "AADLoginForWindows"
    type_handler_version = "1.0"
    auto_upgrade_minor_version = true
      
    settings = <<SETTINGS
    {
      "mdmId": "${azurerm_virtual_machine.vm[count.index].identity.0.principal_id}"
    }
    SETTINGS
    protected_settings = <<PROTECTED_SETTINGS
    {
    }
   PROTECTED_SETTINGS
 }`

**Comment by ArcturusZhang** [comment]
Hi @hugo-paredes @ShahradGH quite weird behaviour and I suppose most likely that this is caused by something wrong from the service side. And a note that terraform is using REST API to make those requests, but the portal does not have to use the same REST API as we do in terraform.

I have tagged this issue as `upstream-microsoft` and will soon raise an issue about this in the azure-rest-api-specs repo to let the corresponding service team to have a look at this.

**Comment by ArcturusZhang** [comment]
Upstream issue opened: https://github.com/Azure/azure-rest-api-specs/issues/10234

**Comment by ArcturusZhang** [comment]
Hi @hugo-paredes the service team has replied in [this upstream issue](https://github.com/Azure/azure-rest-api-specs/issues/10234), could you please provide some feedback regarding on their responses?

**Comment by ArcturusZhang** [comment]
Hi @hugo-paredes could you please have a try again? The service team said this has been resolved.

**Comment by hugo-paredes** [comment]
Hi @ArcturusZhang 

I've already tried and was partially successful. I don't get the error anymore, but I cannot login, I get this error:

![image](https://user-images.githubusercontent.com/40466699/91447581-23f27300-e879-11ea-8fbd-e8e32a1f4caa.png)

Is there something extra I need to enable?

Greetings.
Hugo

**Comment by tombuildsstuff** [comment]
@hugo-paredes I'm not sure if you fully tore down/reprovisioned the VM's for that test or not, but for clarification you'll need to fully cycle to be ensure that's applied; due to the way VM Extensions work the server-side changes don't automatically update existing instances

Since this appears to be an upstream issue, rather than something specific to Terraform - I'm going to suggest we consolidate this issue [in favour of the upstream issue](https://github.com/Azure/azure-rest-api-specs/issues/10234) where the Service Team should be able to help identify the differences here

Thanks!

**Comment by hugo-paredes** [comment]
Hi @tombuildsstuff 

I've destroyed the entire infrastructure associated with it, VM, managed disks, etc. The result was I've described.
