### ISSUE TITLE
Azure Database for PostgreSQL server - locks

### ISSUE THREAD

**Issue by jmturwy** [terraform-providers/terraform-provider-azurerm#7752]
Would like to be able to set a "Lock" on an Azure Postgres Database.
This would stop someone from deleting a DB

**Comment by tombuildsstuff** [comment]
hi @jmturwy 

Thanks for opening this issue.

Taking a look here this is available as [the `azurerm_management_lock` resource](https://www.terraform.io/docs/providers/azurerm/r/management_lock.html) - would you be able to take a look?

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html) and as such I'm going to close this issue for the moment.

Thanks!
