### ISSUE TITLE
Incorrect error message for azurerm_storage_share_directory name field

### ISSUE THREAD

**Issue by taylorturner** [terraform-providers/terraform-provider-azurerm#7788]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.10
+ provider.azurerm v2.19.0
```

### Affected Resource(s)

* `azurerm_storage_share_directory`

### Terraform Configuration Files

```hcl
resource "azurerm_resource_group" "this" {
  name     = "staging-platform-001"
  location = "East US"
}

resource "azurerm_storage_account" "this" {
  name                     = "stagingplatformstorage"
  location                 = azurerm_resource_group.this.location
  resource_group_name      = azurerm_resource_group.this.name
  account_tier             = "Standard"
  account_replication_type = "GRS"
}

resource "azurerm_storage_share" "datalake" {
  name                 = "element-platform-data-lake-share"
  storage_account_name = azurerm_storage_account.this.name
  quota                = 200
}

resource "azurerm_storage_share_directory" "taglabeling" {
  name                 = "tagLabeling"
  share_name           = azurerm_storage_share.datalake.name
  storage_account_name = azurerm_storage_account.this.name
}

resource "azurerm_storage_share_directory" "datasets" {
  name                 = "tagLabeling/datasets"
  share_name           = azurerm_storage_share.datalake.name
  storage_account_name = azurerm_storage_account.this.name
}

resource "azurerm_storage_share_directory" "uploads" {
  name                 = "tagLabeling/datasets/uploads"
  share_name           = azurerm_storage_share.datalake.name
  storage_account_name = azurerm_storage_account.this.name
}
```

### Debug Output

```
terraform plan

Error: name must contain only uppercase and lowercase alphanumeric characters, numbers and hyphens. It must start and end with a letter and end only with a number or letter

  on main.tf line 61, in resource "azurerm_storage_share_directory" "uploads":
  61: resource "azurerm_storage_share_directory" "uploads" {

```

### Expected Behavior

Terraform prints the plan to build these resources.

### Actual Behavior

Terraform returns error about the name being an issue.

### Steps to Reproduce

1. `terraform init`
1. `terraform plan`

**Comment by taylorturner** [comment]
@mbfrahry Do you know what the issue is? I don't know why it was ok with the first 2 share names and not the 3rd.

**Comment by mbfrahry** [comment]
Hey @taylorturner, the issue is that storage share directory names can only be nested once. Your third name is nested twice.

**Comment by taylorturner** [comment]
@mbfrahry that's interesting. Is that a limitation of Terraform? I'm able to create all of those shares with the same name using the Azure CLI `az storage directory create`.

**Comment by mbfrahry** [comment]
It looks like a limitation on the api. Here's what the api returns when I try to pass the name `dir/dir2/dir3`

```
Status=404 Code="ParentNotFound" Message="The specified parent path does not exist.
```

**Comment by taylorturner** [comment]
Thank you @mbfrahry

**Comment by taylorturner** [comment]
@mbfrahry The error message is explaining the parent path doesn't exist.

What if you...

1. create dir1
2. create dir1/dir2
3. create dir1/dir2/dir3

I can verify that the following command works fine with Azure CLI assuming you've created the parents first.

`az storage directory create --share-name example --name dir1/dir2/dir3`

**Comment by mbfrahry** [comment]
I don't think we should take this approach for a number of reasons but let's look at what Terraform should do if we try to delete this resource with the cli approach. 

Since we created all the nested directories through Terraform, we could delete all the directories too but what if Terraform didn't create `dir1`? We could inadvertently delete something the user didn't want deleted. 

What if we just delete `dir3`? At that point, we could be leaving resources behind that Terraform created to get the functionality that matches the cli. 

From a maintainer standpoint, we can't know what the user created versus what Terraform created which makes it difficult to decide how best to actually build the functionality you want. Unfortunately, matching what the cli does isn't always 1-1 like we want it to be. A user should know exactly what Terraform is doing and by making extra calls, we're masking what Terraform is doing and turning it into a black box that could have unintended side effects. 

Your best bet would be to have 2-3 resources that mirror the child/parent relationship you're looking for. At that point, you're in control of all aspects of the resource and can manage it as you see fit rather than masking it inside of a single Terraform resource.

**Comment by taylorturner** [comment]
I'm not disagreeing with anything you're saying. 

This is one of those situations where we've been using scripted `az` commands and we're trying to migrate what we have into Terraform. 

We are actively reworking this logic since Terraform doesn't support it. However, this is the first time I've run into something that the CLI can do that Terraform won't. I just assumed this was a bug but if it's the intended effect then I guess that's it.
