### ISSUE TITLE
Azure key vault resources breaking with move to Terraform 0.12.9 and AzureRM provider 2.20.0

### ISSUE THREAD

**Issue by AtwoodTM** [terraform-providers/terraform-provider-azurerm#7967]
When attempting to create any Azure key vault related resource (key vault access policy, key vault secret, key vault certificate, etc.), the Terraform apply responds stating "Error: configuration for [resource] still contains unknown values during apply (this is a bug in Terraform; please report it!)

## Environment

-Terraform v.0.12.29
- AzureRM provider v2.20

The error happens both on Windows 10 2004 and in Ubuntu 20.04 (via WSL 2.0).

I have created a public github repo with sample templates that replicate the issue.  The README.md also has a screenshot to show the error on terraform apply.  The repo reproducing the bug can be found here: https://github.com/TMAtwood/terraform-azurerm-key-vault-bugs

**Comment by tombuildsstuff** [comment]
hi @AtwoodTM 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look through this appears to be an issue in Terraform Core rather than the Azure Provider - notably there's been some larger changes to the way that dependencies are calculated in Terraform 0.14, so I'd suggest upgrading to Terraform 0.14 and seeing if that works for you. Since this should be fixed by updating to the latest version of Terraform Core, I'm going to close this issue for the moment but if that doesn't work then please open [a new issue on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where someone from that team should be able to take a look.

Thanks!
