### ISSUE TITLE
Add possibility to specify Network/Application Security Group when creating network interface

### ISSUE THREAD

**Issue by aimclourd** [terraform-providers/terraform-provider-azurerm#7987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

We have an Azure policy that prevents us to create virtual network interfaces without any NSG attached to it.
Before using Terraform we use to specify the Network Security Group in our ARM template , in the network interface part (            "type" : "Microsoft.Network/networkInterfaces" , microsoft reference : https://docs.microsoft.com/en-us/azure/templates/microsoft.network/networkinterfaces
),  like this : 
"networkSecurityGroup": {
				"id": "[resourceId(variables('nsgResourceGroupName'), 'Microsoft.Network/networkSecurityGroups', parameters('networkSecurityGroupName'))]",
			},
And we also specify Application Security Group in the properties > ipConfigurations > like this : 
"applicationSecurityGroups": "[variables('applicationSecurityGroupID')]"

Now we're using Terraform, we are stuck at network interface creation because of the nsg policy.

Indeed the only possibility offered by terraform is : 
#1 => Building/requesting the Network Security Group
#2 => Building the network interface
#3 => Associate Network Interface with Network Security Group

### New or Affected Resource(s)

All virtual machines we have to create with terraform

* azurerm_v2.13.0_x5

### Potential Terraform Configuration

Add optional network_security_group_id in resource "azurerm_network_interface"
Add optional application_security_group_id in resource "azurerm_network_interface"

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by yupwei68** [comment]
Hi @aimclourd , thanks for opening this issue. Sorry that we may not implement this feature in the near future. The reason that we separate the `azurerm_network_interface_security_group_association` from `azurerm_network_interface` is to avoid dependency error message by deleting NSG. Besides, normally we try to avoid the existence of a separate resource and an internal block representing the same resource.

**Comment by tombuildsstuff** [comment]
hi @aimclourd 

The `azurerm_network_interface_application_security_group_association` `azurerm_network_interface_application_security_group_association` resources exists to workaround failures at destroy-time, where it's possible to create resources but not destroy them - due to the design of the Azure API (which returns an error along the lines of `InUseApplicationSecurityGroupCannotBeDeleted` during deletion).

Whilst we could look to reintroduce these inline fields, supporting both this and the separate resources (or potentially as a separate resource) - unfortunately this'd just reintroduce this issue during destroy-time and so ultimately isn't as quick a fix as it may appear.

Instead I've opened #9022 which looks to add an example of how to use Azure Policy with these "association" resources - which I'm going to close this issue in favour of, would you mind subscribing to that issue for updates?

Thanks!
