### ISSUE TITLE
Regarding azurerm_servicebus_namespace resource 

### ISSUE THREAD

**Issue by irfanjs** [terraform-providers/terraform-provider-azurerm#8003]
Hi,
I am using `azurerm_servicebus_namespace` resource and would like to add the diagnostic setting in the Azure service bus . 
I tried searching for the same in 
https://www.terraform.io/docs/providers/azurerm/r/servicebus_namespace.html

however, did not find any. 

Please suggest , if there is any resource for, to add diagnostic setting in Azure service bus. if yes, please redirect me to the correct URL. Thanks

**Comment by irfanjs** [comment]
please suggest . Thanks

**Comment by tombuildsstuff** [comment]
hi @irfanjs 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by irfanjs** [comment]
Thanks. I posted the query in the community forum. 
Can we please keep this post open for few days, till we resolve that ... ?
