### ISSUE TITLE
Nested level directory in azure file share.

### ISSUE THREAD

**Issue by Abhishekqwerty** [terraform-providers/terraform-provider-azurerm#8070]
Hello All,

Please help in creating nested level directory for an azure file share using terraform. We can pass only one nested level directory.
Ex: Creating two nested directory

- dir1/dir2/dir3

- a/b/c

And also can terraform add a feature for uploading files in a file share.

**Comment by tombuildsstuff** [comment]
hi @Abhishekqwerty 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
