### ISSUE TITLE
azurerm_function_app does not start function if it was stopped outside of Terraform

### ISSUE THREAD

**Issue by ZachTB123** [terraform-providers/terraform-provider-azurerm#8073]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_function_app`

### Terraform Configuration Files

```hcl
resource azurerm_function_app app {
    name = "my-app"
    ...
    enabled = true
}
```

### Expected Behavior

When I have a Function App created via Terraform with `enabled` set to `true` and then I stop the Function App outside of Terraform (via the portal for example) and then re-run my Terraform, the Function App should be set back to `enabled`.

### Actual Behavior

The Function App remains stopped.

### Steps to Reproduce

1. Create a Function App using Terraform and set the state to `enabled`.
2. Stop the Function App manually in the portal.
3. Re-run Terraform.

### References

* #0000

**Comment by neil-yechenwei** [comment]
@ZachTB123, Thanks for opening this issue. After tested, seems I cannot repro it with below repro steps. Could you have a try below tfconfig and repro steps to check whether the issue still exists? And one more question, may I know how you disable the Function App manually in the azure portal since I didn't find any button to disable it?

Step 1 - Run tf apply:
```
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-funcapp-test01"
  location = "eastus2"
}

resource "azurerm_storage_account" "test" {
  name                     = "acctestsatest01"
  resource_group_name      = azurerm_resource_group.test.name
  location                 = azurerm_resource_group.test.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource "azurerm_app_service_plan" "test" {
  name                = "acctestASP-test01"
  location            = azurerm_resource_group.test.location
  resource_group_name = azurerm_resource_group.test.name

  sku {
    tier = "Standard"
    size = "S1"
  }
}

resource "azurerm_function_app" "test" {
  name                       = "acctest-func-test01"
  location                   = azurerm_resource_group.test.location
  resource_group_name        = azurerm_resource_group.test.name
  app_service_plan_id        = azurerm_app_service_plan.test.id
  storage_account_name       = azurerm_storage_account.test.name
  storage_account_access_key = azurerm_storage_account.test.primary_access_key
  enabled                    = true
}
```

Step 2 - Sent http request to disable app:
```
PUT https://management.azure.com/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-funcapp-test01/providers/Microsoft.Web/sites/acctest-func-test01

{
	"kind": "functionapp",
	"location": "eastus2",
	"properties": {
		"enabled": false,
		"serverFarmId": "/subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-funcapp-test01/providers/Microsoft.Web/serverfarms/acctestASP-test01",
		"siteConfig": {
			"appSettings": [
				{
					"name": "AzureWebJobsStorage",
					"value": "xxxxx"
				},
				{
					"name": "FUNCTIONS_EXTENSION_VERSION",
					"value": "~1"
				},
				{
					"name": "AzureWebJobsDashboard",
					"value": "xxxxx"
				}
			]
		},
		"clientAffinityEnabled": false,
		"dailyMemoryTimeQuota": 0,
		"httpsOnly": false
	},
	"tags": {}
}
```

Step 3 - Run `tf refresh`:
```
terraform refresh
```

Step 4 - Run `tf plan`:
![image](https://user-images.githubusercontent.com/19754191/90087494-7eef7a80-dd4f-11ea-9451-748c1deb0d19.png)

Step 5 - Run `tf apply`:
![image](https://user-images.githubusercontent.com/19754191/90087427-4f407280-dd4f-11ea-8f41-80cd66c5a548.png)

Step 6 - Run `tf plan`:
![image](https://user-images.githubusercontent.com/19754191/90087460-654e3300-dd4f-11ea-9a18-71eac8ca0a9b.png)

**Comment by ZachTB123** [comment]
Here is my Terraform:

```hcl
provider azurerm {
  version = "2.21.0"
  features {}
}

resource azurerm_resource_group example {
  name     = "example-rg"
  location = "centralus"
}

resource azurerm_storage_account example {
  name                     = "funcapptestsa"
  resource_group_name      = azurerm_resource_group.example.name
  location                 = azurerm_resource_group.example.location
  account_tier             = "Standard"
  account_replication_type = "LRS"
}

resource azurerm_app_service_plan example {
  name                = "azure-functions-test-service-plan"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  kind                = "FunctionApp"

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource azurerm_function_app example {
  name                      = "test-azure-functions-57023"
  location                  = azurerm_resource_group.example.location
  resource_group_name       = azurerm_resource_group.example.name
  app_service_plan_id       = azurerm_app_service_plan.example.id
  storage_connection_string = azurerm_storage_account.example.primary_connection_string
  enabled                   = true
  version                   = "3.0.14191.0"
  https_only                = true
}
```

Steps to reproduce:

1.`terraform init`
2. `terraform plan`
3. `terraform apply`
4. Find the Function App in the portal and hit `Stop`:

<img width="507" alt="Screen Shot 2020-08-13 at 5 56 16 PM" src="https://user-images.githubusercontent.com/17228033/90195128-5470e200-dd8e-11ea-9f13-ed81b01df332.png">

5. Run `terraform plan`.

In this case, plan detects that there are no changes.

The portal explicitly mentions `Start`/`Stop` but the Terraform configuration is for `enabled`. I was under the impression that if I stop the function in the portal like I showed above, the next `terraform plan` would detect changes since I have `enabled` set to `true`.

**Comment by neil-yechenwei** [comment]
`enabled` is to disable or enable app, which is totally not related with "Start/Stop". They are not the same thing. So terraform cannot detect the diff via `enabled` property after "Start/Stop" it. If you want to "start/stop" app, you have to use "[Web Apps - Start](https://docs.microsoft.com/en-us/rest/api/appservice/webapps/start)" but it hasn't been implemented by terraform. I assume it's expect since we cannot support it in terraform as it's just an operation api during runtime. It's not a real terraform resource. So it's not appropriate to be as TF candidate.

After set `enabled=false`:
![image](https://user-images.githubusercontent.com/19754191/90199435-5d51ca00-de07-11ea-9be0-470280e5b737.png)

After manually stop app in azure portal:
![image](https://user-images.githubusercontent.com/19754191/90199510-938f4980-de07-11ea-9d64-05f005fa71d6.png)
