### ISSUE TITLE
Error building account: Error getting authenticated object ID: Error listing Service Principals

### ISSUE THREAD

**Issue by SubhakarKotta** [terraform-providers/terraform-provider-azurerm#8082]
Terraform v0.12.24
provider "azurerm" {
  version = "~> 2.12.0"
  features {}
}

terraform apply throws below error.

Error building account: Error getting authenticated object ID: Error listing Service Principals: autorest.DetailedError{Original:(*errors.errorString)(0xc00115d100), PackageType:"azure.BearerAuthorizer", Method:"WithAuthorization", StatusCode:0, Message:"Failed to refresh the Token for request to https://graph.windows.net/0159e9d0-09a0-4edf-96ba-a3deea363c28/servicePrincipals?%24filter=appId+eq+%27af9d7c2f-f3f5-4495-bb43-46696946c39e%27&api-version=1.6", ServiceError:[]uint8(nil), Response:(*http.Response)(nil)}

**Comment by tombuildsstuff** [comment]
hi @SubhakarKotta 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
