### ISSUE TITLE
Deployment template validation failed: 'The template 'copy' definition at line '1' and column '8153' has an invalid copy count.

### ISSUE THREAD

**Issue by prakash12305** [terraform-providers/terraform-provider-azurerm#8090]
### Terraform (and AzureRM Provider) Version
terraform -v
Terraform v0.13.0

Azure RM
 version = "=2.22.0"

### Terraform Configuration Files
variable.tf
main.tf
terraform.tfvars
[Ribbon_SWELite_Azure_ARM.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5060057/Ribbon_SWELite_Azure_ARM.zip)

### Expected Behavior

VM creation should be successful
The same template works with Powershell 

### Actual Behavior

ARM Template deployment via Terraform - Template validation fails

### Steps to Reproduce
terrraform init
terrraform validate
terrraform plan
`terraform apply`

Error: Error validating Template for Deployment "PKTemplate-01" (Resource Group "PKSWELITE-RG"): Deployment template validation failed: 'The template 'copy' definition at line '1' and column '8153' has an invalid copy count. The copy count must be a positive integer value and cannot exceed '800'. Please see https://aka.ms/arm-copy for usage details.'.

### References

Note: If vmSize choosen as Standard_DS3_v2 it works fine. but for other vmSize it throws error as mentioned above

"Standard_B1ms",
 "Standard_B2s",
 "Standard_DS1_v2",

[Ribbon_SWELite_Azure_ARM.zip](https://github.com/terraform-providers/terraform-provider-azurerm/files/5060104/Ribbon_SWELite_Azure_ARM.zip)

**Comment by tombuildsstuff** [comment]
hi @prakash12305 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
