### ISSUE TITLE
Unsupported block type "logging" for storage account using 2.22.0

### ISSUE THREAD

**Issue by frbar** [terraform-providers/terraform-provider-azurerm#8112]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```
Terraform v0.12.24
+ provider.azuread v0.8.0
+ provider.azurerm v2.22.0
```

### Affected Resource(s)

* `azurerm_storage_account`

### Terraform Configuration Files

```hcl
resource "azurerm_storage_account" "xxx" {
  name                     = "xxx"
  resource_group_name      = azurerm_resource_group.xxx.name
  location                 = azurerm_resource_group.xxx.location
  
  account_kind              = "StorageV2"
  account_tier              = "Standard"
  account_replication_type  = "RAGRS"
  access_tier               = "Hot"
  enable_https_traffic_only = true
  min_tls_version           = "TLS1_2"
  allow_blob_public_access  = false

  network_rules {
    default_action = "Allow"
  }

  logging {
    read                  = true
    write                 = true
    delete                = true
    version               = 1.0
    retention_policy_days = 365
  }

}
```

### Debug Output

```
Error: Unsupported block type

  on xxx.tf line 186, in resource "azurerm_storage_account" "xxx":
 186:   logging {

Blocks of type "logging" are not expected here.
```

### Expected Behavior

No error, and logging properties set as expected.

### Actual Behavior

An error happens.

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

Nothing in particular.

### References

* https://www.terraform.io/docs/providers/azurerm/r/storage_account.html
* It said to be available at least in `2.2` (https://github.com/terraform-providers/terraform-provider-azurerm/issues/6258)

**Comment by tombuildsstuff** [comment]
hi @frbar 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

In this instance the `logging` block can be specified within the `queue_properties` block - as such updating your Terraform Configuration to account for this should fix this issue. Since this should be fixed by updating the Terraform Configuration being used here, I'm going to close this issue for the moment, but if that doesn't work for you then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
