### ISSUE TITLE
Node_labels in "azurerm_kubernetes_cluster_node_pool" not working as expected

### ISSUE THREAD

**Issue by vishal8k** [terraform-providers/terraform-provider-azurerm#8118]
the `node_labels` property in `azurerm_kubernetes_cluster_node_pool` displaying weird errors as below. 
**Provider Version** =1.44

**ERROR:**
```
  on aks.tf line 75, in resource "azurerm_kubernetes_cluster_node_pool" "app":
  75:         node_labels = {

An argument named "node_labels" is not expected here.
```
Below is my Terraform code:
```
resource "azurerm_kubernetes_cluster_node_pool" "app" {
        name = "mynp"
        kubernetes_cluster_id = azurerm_kubernetes_cluster.akscluster[0].id
        vm_size = var.clusternodevmsize
        enable_auto_scaling = "true"
        max_count = "6"
        min_count = "1"
        node_count = "1"
        max_pods  = var.maxpodspernode
        os_type = "Linux"
        vnet_subnet_id = var.kubesubnetid
        node_labels = {
           app = "nginx"
        }
}
```

**Comment by tombuildsstuff** [comment]
hi @vishal8k 

Thanks for opening this issue.

Taking a look into this - [version 1.44 of the Provider was released in February 2020](https://github.com/terraform-providers/terraform-provider-azurerm/releases/tag/v1.44.0) - support for this functionality requires a newer version of the Azure Provider. At the time of writing the latest release is v2.23.0 - which you can upgrade to by updating the version in the Provider block (as shown below) and then running `terraform init -upgrade`:

```
provider "azurerm" {
  version = "=2.23.0"
  features {}
}
```

.. which should solve this for you - would you be able to take a look and see if that works for you?

Since this should be fixed by updating to the latest version of the Azure Provider I'm going to close this issue for the moment but please let us know if that doesn't work for you and we'll take another look.

Thanks!
