### ISSUE TITLE
Conditional frontend_endpoint

### ISSUE THREAD

**Issue by valkyrjaa** [terraform-providers/terraform-provider-azurerm#8119]
I am trying to add a frontend_endpoint to my azure frontdoor resource.
I only need to add the frontend_endpoint if the environment is production so I added a variable is_prod.
I wanted to use count to only add the frontend endpoint like this:
`
    frontend_endpoint {
    count = var. is_prod ? 1 : 0

    name = "prodDomain"
    host_name = "xyz.ch"
    custom_https_provisioning_enabled = false
    web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.front-door-waf-policy.id
  }`

this however doesn't work because the frontend endpoint doesn't accept the count argument. I haven't found a way to conditionally add a frontend_endpoint.
Is there a way of doing that?

**Comment by darrenk13** [comment]
I was able to accomplish somthing similar to what you are looking to do by using a dynamic block like this:
```
  dynamic "frontend_endpoint" {
    for_each = var.is_prod ? [1] : []
    content {
      name = "prodDomain"
      host_name = "xyz.ch"
      custom_https_provisioning_enabled = false
      web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.front-door-waf-policy.id
    }
  }
```

**Comment by tombuildsstuff** [comment]
hi @valkyrjaa 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by valkyrjaa** [comment]
> I was able to accomplish somthing similar to what you are looking to do by using a dynamic block like this:
> 
> ```
>   dynamic "frontend_endpoint" {
>     for_each = var.is_prod ? [1] : []
>     content {
>       name = "prodDomain"
>       host_name = "xyz.ch"
>       custom_https_provisioning_enabled = false
>       web_application_firewall_policy_link_id = azurerm_frontdoor_firewall_policy.front-door-waf-policy.id
>     }
>   }
> ```

this worked. thanks @darrenk13 you're a lifesaver :)
