### ISSUE TITLE
Terraform 0.13 azurerm_lighthouse_definition Error: Invalid resource type

### ISSUE THREAD

**Issue by mpjtaylor** [terraform-providers/terraform-provider-azurerm#8157]
Hi this was working fine in 0.12.29:

Acquiring state lock. This may take a few moments... 

Error: Invalid resource type 

 on lighthouse.tf line 2, in resource "azurerm_lighthouse_definition" "definition": 

 2: resource "azurerm_lighthouse_definition" "definition" { 

The provider provider.azurerm does not support resource type 
"azurerm_lighthouse_definition". 
Error: Invalid resource type 
 on lighthouse.tf line 13, in resource "azurerm_lighthouse_assignment" "assignment": 

 13: resource "azurerm_lighthouse_assignment" "assignment" { 

The provider provider.azurerm does not support resource type 
"azurerm_lighthouse_assignment".
 
 CreateFile plan: The system cannot find the file specified.

**Comment by tombuildsstuff** [comment]
hi @mpjtaylor 

Thanks for opening this issue.

At this time the Azure Provider doesn't support the lighthouse resources - so it's possible that you're using a custom version of the provider here, as such unfortunately we're unable to offer support for resources we've not shipped.

The way that custom plugins works has changed in Terraform 0.13 - as such if you're using this you may need to change your local setup to handle that.

Since Lighthouse isn't currently supported I'm going to close this in favour of #6560 where this is currently being tracked - would you mind subscribing to that for updates?

Thanks!
