### ISSUE TITLE
Error when trying to retrieve azurerm_policy_set_definition

### ISSUE THREAD

**Issue by mcanevet** [terraform-providers/terraform-provider-azurerm#8159]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

```shell
$ terraform -v
Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azuread v0.11.0
```

### Affected Resource(s)

* datasource `azurerm_policy_set_definition`

### Terraform Configuration Files

```hcl
data "azurerm_policy_set_definition" "restricted" {
  display_name = "[Preview]: Kubernetes cluster pod security restricted standards for Linux-based workloads"
}
```

### Debug Output

https://gist.github.com/mcanevet/82e869ca9fe441047c0409565bdf771b

### Expected Behavior

Resource should be looked up

### Actual Behavior

Error in terraform provider

### Steps to Reproduce

1. `terraform plan`

**Comment by tombuildsstuff** [comment]
From the log:

```
2020/08/18 17:30:33 [ERROR] eval: *terraform.evalReadDataRefresh, err: setting `policy_definition_reference`: policy_definition_reference.2.parameters.maxPort: '' expected type 'string', got unconvertible type 'float64'
2020/08/18 17:30:33 [ERROR] eval: *terraform.EvalSequence, err: setting `policy_definition_reference`: policy_definition_reference.2.parameters.maxPort: '' expected type 'string', got unconvertible type 'float64'
```

**Comment by mcanevet** [comment]
Indeed, but I can't do anything about it. I'm just trying to retrieve a pre-defined policy set by its display name.

**Comment by tombuildsstuff** [comment]
@mcanevet sorry, that was posted for other contributors to be able to fix this without digging through the logs rather than something you can fix

**Comment by ArcturusZhang** [comment]
Hi @mcanevet sorry for the inconvenience - this should be introduced by my contribution. And now it makes more sense why the parameters in the root level we have to implement it in plain JSON string rather than a map - terraform map only support string as its values, if there are some entries that have non-string typed, we will get to a problem.

It is very easy to make some changes to let terraform convert everything in the parameter values from the service to string (in the way out), but the problems may be in the way if we have defined everything in the parameter values using string - would the service recognize this? For instance, in your case, a parameter value is a float, we could convert it into string when we are reading this from the service, but if we are setting a parameter whose value should be in float format, I do not find a way to do so.

@tombuildsstuff could you please provide some insights here? Or we have to change the parameter from a map to a JSON string like in policy definition?

**Comment by tombuildsstuff** [comment]
@ArcturusZhang changing the type of this field would be a breaking change - so unfortunately that'd have to wait for the next major version (3.0) - however in the interim we'll need to update the `parameters` to expand/flatten only strings and highlight this limitation in the documentation?

It appears this information should be available via the field `policy_definitions` - so it should be possible to access this by `jsondecode`-ing it?
