### ISSUE TITLE
Will azure blueprint management be supported soon?

### ISSUE THREAD

**Issue by Jelledb** [terraform-providers/terraform-provider-azurerm#8170]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

I would like to create blueprints using Terraform but I see that there is not yet a functionality to do so. I did find this PR (https://github.com/terraform-providers/terraform-provider-azurerm/pull/4829) which looks perfect for my use case, but unfortunately it is closed. Is it still on the roadmap to support this functionality?

**Comment by tombuildsstuff** [comment]
hi @Jelledb 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
