### ISSUE TITLE
"features": required field is not set

### ISSUE THREAD

**Issue by julienym** [terraform-providers/terraform-provider-azurerm#8174]
Tried with 2.9.0 and 2.23.0.
We have the same result:
`:10 [TRACE] vertex "module.keyvault.azurerm_key_vault_access_policy.azure_pipeline": evaluating
2020/08/19 13:25:10 [TRACE] [walkValidate] Entering eval tree: module.keyvault.azurerm_key_vault_access_policy.azure_pipeline
2020/08/19 13:25:10 [TRACE] module.keyvault: eval: *terraform.EvalSequence
2020/08/19 13:25:10 [TRACE] module.keyvault: eval: *terraform.EvalGetProvider
2020/08/19 13:25:10 [TRACE] [walkValidate] Entering eval tree: module.keyvault.output.keyvault_name
2020/08/19 13:25:10 [TRACE] module.keyvault: eval: *terraform.EvalValidateResource
2020/08/19 13:25:10 [TRACE] module.keyvault: eval: *terraform.EvalSequence
2020/08/19 13:25:10 [TRACE] module.keyvault: eval: *terraform.EvalOpFilter
2020/08/19 13:25:10 [TRACE] module.keyvault: eval: *terraform.EvalWriteOutput
2020/08/19 13:25:10 [TRACE] EvalWriteOutput: Removing module.keyvault.output.keyvault_name from state (it is now null)
2020/08/19 13:25:10 [TRACE] EvalWriteOutput: Saving Create change for module.keyvault.output.keyvault_name in changeset
2020/08/19 13:25:10 [TRACE] [walkValidate] Exiting eval tree: module.keyvault.output.keyvault_name
2020/08/19 13:25:10 [TRACE] vertex "module.keyvault.output.keyvault_name": visit complete
2020/08/19 13:25:10 [TRACE] GRPCProvider: ValidateResourceTypeConfig
2020/08/19 13:25:10 [TRACE] [walkValidate] Exiting eval tree: module.keyvault.azurerm_key_vault_access_policy.full
2020/08/19 13:25:10 [TRACE] vertex "module.keyvault.azurerm_key_vault_access_policy.full": visit complete
2020/08/19 13:25:10 [TRACE] [walkValidate] Exiting eval tree: module.keyvault.azurerm_key_vault_access_policy.azure_pipeline
2020/08/19 13:25:10 [TRACE] vertex "module.keyvault.azurerm_key_vault_access_policy.azure_pipeline": visit complete
2020/08/19 13:25:10 [TRACE] dag/walk: visiting "module.keyvault.provider.azurerm (close)"
2020/08/19 13:25:10 [TRACE] vertex "module.keyvault.provider.azurerm (close)": starting visit (*terraform.graphNodeCloseProvider)
2020/08/19 13:25:10 [TRACE] vertex "module.keyvault.provider.azurerm (close)": evalError: "features": required field is not set`

Our terraform code worked before, but now doesn't, even if we fix TF version and provider.

Any hints could be helpful, thanks!

**Comment by tombuildsstuff** [comment]
hi @julienym 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

Version 2.0 of the Azure Provider requires that you define a `features` block within the `provider` block - [as shown in this example](https://www.terraform.io/docs/providers/azurerm/index.html#example-usage) which controls the behaviour of certain resources within the provider - as such you'll need to specify the `provider` and the `features` block to fix this.

Since this should be fixed by updating the Terraform Configuration being used to include a `provider` (and `features`) block - I'm going to close this issue for the moment, but if that doesn't work for you then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by julienym** [comment]
Hi @tombuildsstuff, sorry I was too hasty in my ticket. We do use features {} in our provider {}.
