### ISSUE TITLE
App Service Emvironment questions

### ISSUE THREAD

**Issue by xlj1000** [terraform-providers/terraform-provider-azurerm#8176]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)
Please advise why dnsSuffix property is left out from azurerm_app_service_environment. I would also like to have cluster_settings as well.

Also I am not if and how azurerm_app_service_certificate can be used here to set up ASE

Thanks

**Comment by tombuildsstuff** [comment]
hi @xlj1000 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
