### ISSUE TITLE
azurerm_template_deployment - add parameters value to be an array of strings

### ISSUE THREAD

**Issue by LaurentLesle** [terraform-providers/terraform-provider-azurerm#8180]
Add list of strings for parameter's value

```hcl
resource "azurerm_template_deployment" "resource" {
  name                = var.name
  resource_group_name = var.resource_group_name
  template_body = file(local.arm_filename)

  parameters = {
    "name"   = var.name
    "zones"   = ["1","3"]
  }
}
```

**Comment by tombuildsstuff** [comment]
hi @LaurentLesle 

Thanks for opening this issue

Unfortunately at this time Terraform Core requires that all values within a map are of the same type - in this instance strings - which means that this isn't possible at this time. That said it should be possible to achieve this by passing in a ARM Template variable file for these using the `parameters_json` file (for example using a templated file).

Since unfortunately this isn't a bug that we can fix within this Provider directly, I'm going to close this issue for the moment - however I believe the workaround should allow you to achieve this.

Thanks!

**Comment by LaurentLesle** [comment]
Thanks Tom. Let me use that workaround. That should fix my issue indeed
