### ISSUE TITLE
Support for ACR integration with AKS clusters

### ISSUE THREAD

**Issue by hungtran84** [terraform-providers/terraform-provider-azurerm#8198]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Add support for the ACR integration for AKS clusters. 
### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "example" {
  name                = "example-aks1"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name
  dns_prefix          = "exampleaks1"

  default_node_pool {
    name       = "default"
    node_count = 1
    vm_size    = "Standard_D2_v2"
  }

  identity {
    type = "SystemAssigned"
  }

 acr {
   attached = true
   name     = azurerm_container_registry.example.name
 }

```

### References

* https://docs.microsoft.com/en-us/azure/aks/cluster-container-registry-integration/

**Comment by tombuildsstuff** [comment]
hi @hungtran84 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

In this instance this can be achieved by adding a [Role Assignment](https://www.terraform.io/docs/providers/azurerm/r/role_assignment.html) (using a role similar to `AcrPull`, or another "Reader" role) between the AKS Cluster and the Container Registry such that the AKS Cluster can pull images, where these are then sourced from the Kubernetes Deployment Manifests.

Since this is possible using the existing resources I'm going to close this issue for the moment, however should you have further questions about this then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
