### ISSUE TITLE
azurerm_bot_channel_directline import and site issues

### ISSUE THREAD

**Issue by jamessmith21-insight** [terraform-providers/terraform-provider-azurerm#8200]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
* `terraform v0.13.0`
* `azurerm v2.23.0`

### Terraform Configuration Files

```hcl
resource "azurerm_bot_channel_directline" "flexbotdl" {
  bot_name            = azurerm_bot_channels_registration.flexbotcr.name
  location            = azurerm_bot_channels_registration.flexbotcr.location
  resource_group_name = var.azure_rg[terraform.workspace]

  site {
    name    = "Default Site"
    enabled = true
  }
}
```
### Expected Behavior

Azure Bot Direct Line channel should have the default site section populated when it is imported and/or default site should not be marked as optional when it is required.

### Actual Behavior

The site section is imported as an empty value - "site": [] - even if the site section is populated. the 'site' section is also required, contrary to the documentation. A subsequent terraform plan will show that the channel requires an update. It will update the channel and reset the Direct Line keys if terraform apply is executed.

### Steps to Reproduce

1. Import an existing Direct Line channel using import command here: https://www.terraform.io/docs/providers/azurerm/r/bot_channel_directline.html
2. Inspect state. Site will be empty.
3. Run terraform plan. The channel will be updated regardless of site configuration.

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. I assume you don't need to explicitly add azurerm_bot_channel_directline block to create `Default Site` since the default site would be automatically created by API. So suggest to remove the block azurerm_bot_channel_directline for default site.

**Comment by jamessmith21-insight** [comment]
> 
> 
> Thanks for opening this issue. I assume you don't need to explicitly add azurerm_bot_channel_directline block to create `Default Site` since the default site would be automatically created by API. So suggest to remove the block azurerm_bot_channel_directline for default site.

Are you referring to the 'site' section above? It's required and Terraform will return an error if it is not defined.

**Comment by neil-yechenwei** [comment]
Could you have a try below tfconfig which can create successfully? Thanks.
```
provider "azurerm" {
  features {}
}

data "azurerm_client_config" "current" {
}

resource "azurerm_resource_group" "test" {
  name     = "acctestRG-bot-test07"
  location = "eastus2"
}

resource "azurerm_bot_channels_registration" "test" {
  name                = "acctestdftest07"
  location            = "global"
  resource_group_name = azurerm_resource_group.test.name
  sku                 = "F0"
  microsoft_app_id    = data.azurerm_client_config.current.client_id
}

resource "azurerm_bot_channel_directline" "test" {
  bot_name            = azurerm_bot_channels_registration.test.name
  location            = azurerm_bot_channels_registration.test.location
  resource_group_name = azurerm_resource_group.test.name
  
  site {
    name    = "TestSite"
    enabled = true
  }
}
```

**Comment by jamessmith21-insight** [comment]
This will work fine. The issue is with existing DL channels and Terraform. Remove the resource from Terraform state. Remove 'TestSite' from the DL channel in Azure so it only has the default site.  Import the updated resources into Terraform and then run a plan. Terraform will throw an error as there will be no 'site' block configured. It will want to update the channel even if you add a 'Default Site' to the config. The update should be unnecessary and will regenerate the DL keys if applied. My assumption is that the import command should pull in the 'Default Site' created by the API.

**Comment by neil-yechenwei** [comment]
I assume terraform cannot handle default site since it's created automatically by api so that terraform would suppress it. And seems I cannot repro your issue. Could you have a try below repro steps to check whether the issue still exists? 
1. Create bot channel directline with above tfconfig I provided
2. Remove the azurerm_bot_channel_directline block from state file
3. Delete "TestSite" DL channel from Azure portal
4. Run `tf import` with command "terraform import azurerm_bot_channel_directline.example /subscriptions/xx-xx-xx-xx/resourceGroups/acctestRG-bot-test07/providers/Microsoft.BotService/botServices/acctestdftest07/channels/DirectLineChannel"
![image](https://user-images.githubusercontent.com/19754191/91048324-186f3400-e64e-11ea-96bb-5178b1e982d6.png)
5. Run `tf plan` without error
![image](https://user-images.githubusercontent.com/19754191/91048459-4e141d00-e64e-11ea-8103-104e5e4fa73c.png)
6. Run `tf apply` without error
![image](https://user-images.githubusercontent.com/19754191/91048521-5ec49300-e64e-11ea-861d-af43f171d5ac.png)

**Comment by jamessmith21-insight** [comment]
These steps are correct. This is what I see. This is the issue. 

My assumption is that import will handle the default site. It doesn't, so terraform wants to update the channel once it's imported on the next plan/apply cycle. This is undesired behavior because the update will regenerate the Direct Line keys for the channel, immediately breaking any bot using the channel because the keys are out of sync. It is also forcing the addition of another site, which is unnecessary. We only use the default site.

There is no way that I have found for terraform to handle the default site. My expectation is that an imported DL channel should not require an immediate update. Please let me know if that is correct.

The other issue is that the 'site' block is marked optional according to the documentation: https://www.terraform.io/docs/providers/azurerm/r/bot_channel_directline.html#site. 'site' is required. Terraform will produce an error if the 'site' block is not present and populated.

**Comment by neil-yechenwei** [comment]
The "Default Site" is created automatically by API so that I assume terraform cannot handle it. So currently terraform would suppress it. As the non-default site "TestSite" is removed from azure portal and state file, so the update operation is triggered. It's not related with "Default Site". I assume it's expected behavior. If you expect the change from default site isn't detected, suggest to use ignore_changes while updating.
```
resource "azurerm_bot_channel_directline" "example" {
  bot_name            = azurerm_bot_channels_registration.example.name
  location            = azurerm_bot_channels_registration.example.location
  resource_group_name = azurerm_resource_group.example.name
  
  site {
    name    = "Default Site"
    enabled = true
  }
  
  lifecycle {
    ignore_changes = ["site"]
  }
}
```

Yes, you're right. I assume it's a document issue since no any site within DL channel is not meaningful. So I assume it should be required. I will submit a [PR](https://github.com/terraform-providers/terraform-provider-azurerm/pull/8236) to fix it.
