### ISSUE TITLE
Could not retrieve the list of available versions for provider 1.42.0 azurerm

### ISSUE THREAD

**Issue by vishnu-anil** [terraform-providers/terraform-provider-azurerm#8215]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

Based on PR: https://github.com/terraform-providers/terraform-provider-azurerm/pull/5325

azurerm provider version 1.42.0 is required so as to by default install the cosmosdb account with server version 3.6. To achieve this i have added the below in my template which unfortunately fails with the below error.

`provider "azurerm" {
    version = "~> 1.42.0"
}`

My terraform version: 0.12.9. Also tried with 0.13.0

**ERROR**
`
hashicorp/azurerm: no available releases match the given constraints 1.35.0,
~> 1.35.0, ~> 1.42.0, ~> 1.35.0
Could not retrieve the list of available versions for provider
`
---

Could someone please point out what is wrong here

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @vishnu-anil 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
