### ISSUE TITLE
Support for exporting resource ids of auto-generated resources by AKS

### ISSUE THREAD

**Issue by topikettunen** [terraform-providers/terraform-provider-azurerm#8220]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

I would like to have ids of auto-generated resources, such as Virtual Machine Scale Sets, Load Balancer etc., created by AKS so I can add further configurations to those resources. 

Correct me if this is possible already, at least I wasn't able to find a possible solution for this. I see it currently exports the node resource group so I guess you can at least build the id manually. So is that the way currently?

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
resource "azurerm_kubernetes_cluster" "aks" {
  resource_group_name = var.resource_group_name
  name                = "example-aks1"
  location            = var.location
  tags                = var.tags
  dns_prefix          = "exampleaks1"
  kubernetes_version  = var.kubernetes_version

  default_node_pool {
    name            = "examplepool"
    node_count      = 3 
    vm_size         = "Standard_B2s"
    os_disk_size_gb = 30
    vnet_subnet_id  = var.subnet_id
    type            = "VirtualMachineScaleSets"
  }
}

resource "azurerm_monitor_diagnostic_setting" "aks_vmss_logs" {
  name               = "aks_vmss_logs"
  target_resource_id = azurerm_kubernetes_cluster.aks.virtual_machine_scale_set.id
  storage_account_id = azurerm_storage_account.sa.id

  log {
    category = "AuditEvent"
    enabled  = true

    retention_policy {
      enabled = true
      days = 365
    }
  }

  log {
    category = "OperationalLogs"
    enabled  = true

    retention_policy {
      enabled = true
      days    = 365
    }
  }

  metric {
    category = "AllMetrics"

    retention_policy {
      enabled = true
      days    = 365
    }
  }

  log_analytics_workspace_id = azurerm_log_analytics_workspace.log_analytics.id
}
```

**Comment by tombuildsstuff** [comment]
hi @topikettunen 

Thanks for opening this issue.

The specific resources provisioned by AKS are implementation details of that service and subject to change at any time - as such unfortunately this isn't something we plan to expose unless Azure exposes that information through the AKS API (so that this is long-lived). For the `node_resource_group` field this is exposed through the API to allow overriding the name used for the resource group where the AKS Cluster gets provisioned - and thus is returned and so we can expose it.

However since these fields are an implementation detail (and thus subject to change at any time) unfortunately we have no plans to expose these fields and as such I'm going to close this issue for the moment. Instead I'd suggest [opening an issue on the AKS Repository](https://github.com/Azure/AKS/issues) where the AKS Team should be able to consider exposing this information (at which point there's more of a long-term guarantee this won't be replaced and we can look to expose it.

Thanks!
