### ISSUE TITLE
"features": required field is not set

### ISSUE THREAD

**Issue by julienym** [terraform-providers/terraform-provider-azurerm#8224]
I'm reopening a new issue for this. Previous one was closed quickly.

Az DevOps TF Extension: 0.0.142
Terraform 0.12.24
AzureRM provider: tested on 2.0.0, 2.9.0, 2.23.0

My code use an empty features block as required since 2.0.0+
But I get the error: "features": required field is not set

**Comment by tombuildsstuff** [comment]
hi @julienym 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

Version 2.0 of the Azure Provider requires that you define a `features` block within the `provider` block - [as shown in this example](https://www.terraform.io/docs/providers/azurerm/index.html#example-usage) which controls the behaviour of certain resources within the provider - as such you'll need to specify the `provider` and the `features` block to fix this.

Since this should be fixed by updating the Terraform Configuration being used to include a `provider` (and `features`) block - I'm going to close this issue for the moment, but if that doesn't work for you then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
