### ISSUE TITLE
issue with terraform:compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id 'element(azurerm_network_interface.network-interface.*.id, count.index)' at path 'properties.networkProfile.networkInterfaces[0].id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."

### ISSUE THREAD

**Issue by dineshmallepalli** [terraform-providers/terraform-provider-azurerm#8255]

**Comment by tombuildsstuff** [comment]
hi @dineshmallepalli 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
