### ISSUE TITLE
Destroy kubernetes_node_pool: Error waiting for the deletion. Operation was overriden and canceled by later operation

### ISSUE THREAD

**Issue by Bessonov** [terraform-providers/terraform-provider-azurerm#8260]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.20
+ provider.azuread v0.11.0
+ provider.azurerm v2.22.0
+ provider.kubernetes v1.10.0
+ provider.local v1.4.0
+ provider.null v2.1.2
+ provider.random v2.2.1

### Affected Resource(s)

Reopen https://github.com/terraform-providers/terraform-provider-azurerm/issues/5638 . Still happens on CI, but now with an ID:

```
Error: waiting for the deletion of Node Pool "memory3" (Managed Kubernetes Cluster "build_cluster" / Resource Group "build_aks"): Code="Canceled" Message="The operation was overriden and canceled by a later operation c794ba84-73d1-4901-a484-2d6cebdf7286."
```

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @Bessonov 

Thanks for opening this issue.

Taking a look into this, since this appears to be an issue in the AKS API (and there's an Operation ID available here) - unfortunately this would require the AKS Team to investigate/track this down, as such I'm going to close this issue for the moment but I'd recommend reopening this on [the AKS Repository](https://github.com/Azure/AKS/issues) where a member from that team should be able to take a look.

Based on the scenarios mentioned in #5638, my guess would be this is rate-limit related (the AKS VMSS Reconciler is very aggressive - we've got issues provisioning more than 6 single node pool clusters at a time in a subscription, I'm unsure of the sizes of your clusters/pools) - but unfortunately this would require the AKS Team to investigate/confirm the issue here - however should they confirm this is an issue in Terraform then we can reopen this and take another look.

However for the moment would you mind [opening an issue on the AKS Repository](https://github.com/Azure/AKS/issues) so that the AKS Team could look into this?

Thanks!

cc @jluk for info

**Comment by Bessonov** [comment]
Hey @tombuildsstuff thank you very much for your quick and very precise/helpful response!

We have 3 node pools + default node pool and at the time the issue is happening this was only operation we run in the subscription. But yeah, you're right - this seems like an api issue and not terraform/azurerm. Sorry about opening the issue in this repo.

**Comment by thpang** [comment]
@Bessonov what issue did you open to replace this one? I am having the same issue, please provide the link here.
