### ISSUE TITLE
Azure Policy is interfering with network security group association

### ISSUE THREAD

**Issue by iverberk** [terraform-providers/terraform-provider-azurerm#8261]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.0
+ provider registry.terraform.io/hashicorp/azurerm v2.24.0

### Affected Resource(s)

* azurerm_subnet
* azurerm_subnet_network_security_group_association

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_subnet" "issue" {
  name                 = "subnet"
  resource_group_name  = "vNet"
  virtual_network_name = "vNet"
  address_prefixes     = ["10.1.2.0/24"]
}

resource "azurerm_network_security_group" "issue" {
  name                = "issue"
  location            = "West Europe"
  resource_group_name = "issue"

  security_rule {
    name                       = "test123"
    priority                   = 100
    direction                  = "Inbound"
    access                     = "Allow"
    protocol                   = "Tcp"
    source_port_range          = "*"
    destination_port_range     = "*"
    source_address_prefix      = "*"
    destination_address_prefix = "*"
  }
}

resource "azurerm_subnet_network_security_group_association" "issue" {
  subnet_id                 = azurerm_subnet.issue.id
  network_security_group_id = azurerm_network_security_group.issue.id
}
```

### Debug Output

```
azurerm_subnet.issue: Creating...
azurerm_network_security_group.issue: Creating...
azurerm_subnet.issue: Creation complete after 0s [id=xxx]
azurerm_network_security_group.issue: Creation complete after 1s [id=xxx]
azurerm_subnet_network_security_group_association.issue: Creating...

Error: A resource with the ID "/subscriptions/xxxx/resourceGroups/vNet/providers/Microsoft.Network/virtualNetworks/vNet/subnets/subnet" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_subnet_network_security_group_association" for more information.

  on main.tf line 31, in resource "azurerm_subnet_network_security_group_association" "issue":
  31: resource "azurerm_subnet_network_security_group_association" "issue" {
```

### Expected Behavior

The network security group should be associated with the newly created subnet.

### Actual Behavior

Terraform is complaining that the newly created subnet is not in the statefile and provides the above error. As you can see, the subnet was created just before. The reason why this happens, is explained below.

### Steps to Reproduce

Terraform spits out this error because we have an Azure policy active on the subscription. This policy does the following:

1. Check if the subnet has no associated NSG
2. If no NSG is associated, it appends a default (restrictive) NSG to the subnet
3. If an NSG is associated, it does nothing

If we disable the policy, it all works fine but we need this policy for compliance reasons. Obviously it is interfering with Terraform housekeeping. We would like to know why Terraform spits out this error and if there is any way that we can use compliance policies, while managing the resource with Terraform.

We also have other 'append' policies active which do not cause issues with Terraform. Is there anything special here?

With the old version of the resource it was possible to directly add a NSG to the subnet, but that option has been removed. This makes it a two-step process which does not sit well with our policies.

**Comment by tombuildsstuff** [comment]
hey @iverberk 

Thanks for opening this issue.

The Azure API's are mostly Upserts - meaning that if a resource doesn't exist when you try and create it, you'll get a new one - otherwise the existing resource will be updated. Unfortunately the behaviour of many fields differs in the Azure API between Create and Update in that trying to pass a new value to a field in some API's will return a generic "400" error, with no detail of what's gone wrong. In other cases (with this functionality disabled) this has led to users unintentionally adopting resources into the state - and then ultimately being confused when Terraform destroys unrelated items when deleting a Resource Group (which is Azure's default behaviour).

As such in version 2.0 of the Azure Provider we require that all "existing" resources are imported into the state - which brings this Provider into line with other Terraform Providers which means that we'll raise the error you're seeing if an existing resource exists - where we now prompt a user to import this resource to be able to use it in Terraform, so that we can ensure we're tracking/applying these changes correctly.

Ultimately there's two suggestions here: firstly, you can import the existing NSG Association that's being added here and then update it, but that's clearly not ideal since it'd be a two-phased apply. Alternative you should be able to update the Azure Policy to take effect only when an item is being provisioned within the Subnet, specifically when a NIC starts getting added to the subnet, rather than on subnet creation - which should achieve the same thing.
Without seeing the Policy in question it's hard to provide the specifics for that, but the Subnet API exposes that information, so it should be possible to add a condition to the Policy to apply that when `len(networkInterfaces)>0` - which'd be called during the creation of the Network Interface (and achieve the same thing, even for managed services) - however if you can provide an example of that then we should be able to take a look here.

Thanks!

**Comment by iverberk** [comment]
Hi @tombuildsstuff 

Thanks for the quick and elaborate answer.

I'm not quite sure if I understand what is happening with the upserts here. In my mind the provisioning process is as follows (this assumes an empty starting environment, so no existing resources):
 
1. Terraform creates the plan and notices that it needs to create the resources in the following order: subnet, NSG, NSG-association (or NSG, subnet, NSG-assocation). Either way, the NSG-association is the last resource to provision.
2. It creates the subnet or NSG
3. It creates the NSG or subnet
4. It now tries to create an association of the NSG with the subnet. This will probably result in an upsert to the subnet resource. However, for some reason TF does not recognize that it is in fact already managing the subnet even though it just created the subnet. Somehow there is a mismatch between the Azure API and the TF state file? Maybe based on some hash or property that is not matching anymore after our policy adjusted the subnet out-of-band without TF knowing. Or is TF spitting out a totally irrelevant error message based on the fact that it gets a generic 400 reply from the API while updating the subnet NSG?

In any case, we'll probably need to think out-of-the-box on this one. I like your suggestion and we'll investigate if we can apply the policy on another resource level. Here is our policy: https://gist.github.com/iverberk/58f28c75c274f83de7a3466cfa66150f

**Comment by tombuildsstuff** [comment]
@iverberk at step 4 we check for the presence of an existing NSG <-> Subnet association - since that's being added by the Azure Policy (in step 3) we'll detect one as pre-existing on the Subnet and raise the "please import an existing resource" error - hope that helps clarify that?

Taking a look at the Policy provided above - and an example subnet response:

```
{
  "name": "internal",
  "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-200827003752911797/providers/Microsoft.Network/virtualNetworks/acctestnw-200827003752911797/subnets/internal",
  "etag": "W/\"00000000-0000-0000-0000-000000000000\"",
  "properties": {
    "provisioningState": "Succeeded",
    "addressPrefix": "10.0.2.0/24",
    "ipConfigurations": [
      {
        "id": "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/acctestRG-200827003752911797/providers/Microsoft.Network/networkInterfaces/acctestnic-200827003752911797/ipConfigurations/internal"
      }
    ],
    "serviceEndpoints": [],
    "delegations": []
  },
  "type": "Microsoft.Network/virtualNetworks/subnets"
}
```

I believe this should be achievable (although I haven't tested this) with something along the lines of:

```
      "count": {
        "field": "Microsoft.Network/virtualNetworks/subnets[*].ipConfigurations[*].id",
        "greater": 0
      }
```

[within the first block](https://gist.github.com/iverberk/58f28c75c274f83de7a3466cfa66150f#file-policy-json-L55-L74) to enable this to work (and only fire when someone (or the Azure API's) tries to add an IP Configuration [e.g. NIC/LB etc] to the Subnet) - which I believe should get this working, would you be able to take a look?

Thanks!

**Comment by iverberk** [comment]
Hi Tom, if we are going the NIC route, isn't it going to suffer the same fate? We put a default policy on it and the customer specifies a 'azurerm_network_interface_security_group_association' resource, isn't that going to error out and tell us to import first?

Can you elaborate on why the functionality was removed that allowed specifying a subnet and NSG in one resource, or at least keep both options (with a warning if it might results in conflicts)?

**Comment by tombuildsstuff** [comment]
hi @iverberk 

The `azurerm_subnet_network_security_group_association` resource exists to workaround failures at destroy-time, where it's possible to create resources but not destroy them - due to the design of the Azure API (which returns an error along the lines of `InUseSubnetCannotBeDeleted` during deletion).

Whilst we could look to reintroduce the older `network_security_group_id` field, supporting both this and the `azurerm_subnet_network_security_group_association` resource (or potentially as a separate resource) - but unfortunately this'd just reintroduce this issue during destroy-time and so ultimately isn't as quick a fix as it may appear.

Instead I've opened #9022 which looks to add an example of how to use Azure Policy with these "association" resources - which I'm going to close this issue in favour of, would you mind subscribing to that issue for updates?

Thanks!
