### ISSUE TITLE
Error setting the draft Automation Runbook, azurerm_automation_runbook fails with 404 Error

### ISSUE THREAD

**Issue by cmptscpeacock** [terraform-providers/terraform-provider-azurerm#8264]
Referencing this issue: https://github.com/terraform-providers/terraform-provider-azurerm/issues/4403

This issue still occurs.

Debug Output

azurerm_automation_runbook.runbook_start: Error setting the draft Automation Runbook automation.RunbookDraftClient#ReplaceContent: Failure sending request: StatusCode=404 -- Original Error: Code="ResourceNotFound" Message="The Resource 'Microsoft.Automation/automationAccounts/testaccount/runbooks/Conncetionscript' under resource group 'loggingRG' was not found." "

Expected Behavior
Runbook should be created

Actual Behavior
Looking for creating runbook which doesn't exist

Steps to Reproduce
terraform apply

Terraform Version
Terraform v0.12.12

provider.azurerm v2.21.0

**Comment by tombuildsstuff** [comment]
hi @cmptscpeacock 

Unfortunately there's not enough information for us in the issue description to be able to determine the root cause of this - if this is still an issue can you please [open a new issue completing the issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Bug_Report.md) which has all of the information we need.

Thanks!
