### ISSUE TITLE
Support for geo-replicas in azurerm_mssql_database/azurerm_mssql_server

### ISSUE THREAD

**Issue by simonwhybrow-cbre** [terraform-providers/terraform-provider-azurerm#8276]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### New or Affected Resource(s)

* azurerm_mssql_database & azurerm_mssql_server

### Potential Terraform Configuration

Terraform v0.12.28
provider.azurerm v2.23.0

It's currently possible to create a primary/secondary configuration and failover group containing all necessary databases.

However it doesn't seem possible to subsequently add those databases to additional geographical secondaries to provide mutiple geo-replication targets.

I have attempted this with the below terraform code.
 A primary server and databases have been configured. A secondary server and associated failover group have also been created. That code isn't shown, but below is the attempt to create the additional geo-secondaries.

```hcl
# set up a map variable for the information for the geo-secondaries
geo_secondaries = {
    westeurope = {        
        geo_server_name     = "euwest_server"
        geo_server_username = "euwest_server_admin"
    }
   uksouth = {
        geo_server_name     = "uksouth_server"
        geo_server_username = "uksouth_server_admin"
    }
}
# list of databases to be created
db_names = ["db1", "db2"]


resource "random_string" "geo_passwords" {
  for_each = var.geo_secondaries

  length           = 16
  special          = true
  override_special = "!#$%&*()-_=+[]{}<>:?"
}

resource "azurerm_mssql_server" "geo_mssql" {
  for_each = var.geo_secondaries

  name                         = each.value["geo_server_name"]
  resource_group_name          = var.rg_name
  location                     = each.key
  version                      = var.server_version
  administrator_login          = each.value["geo_server_username"]
  administrator_login_password = random_string.geo_passwords[each.key].result

  tags = var.tags
}

resource "azurerm_mssql_database" "geo_db" {
  for_each = var.geo_secondaries != null ? toset(var.db_names) : []

  name = each.key

  server_id = [ for server in azurerm_mssql_server.geo_mssql[*] : server.id ]

  sku_name   = var.sku_name
  read_scale = false

  create_mode = "Secondary"

  collation   = var.collation
  max_size_gb = var.max_size_gb

  tags = var.tags

}
```

### Result
You can create the multiple databases in geo_db by looping through the list of databases, however the server_id is expecting a single server id as a string not a list which would be provided from the for expression:

```
Inappropriate value for attribute "server_id": string required.
```

Would changing server_id to take a list solve the problem? or is there another way to create these multiple secondaries?

### References

* https://docs.microsoft.com/en-us/azure/azure-sql/database/active-geo-replication-overview

**Comment by tombuildsstuff** [comment]
hi @simonwhybrow-cbre 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by simonwhybrow-cbre** [comment]
Hi @tombuildsstuff ,

Maybe I didn't phrase my question correctly.

I was actually asking if an enhancement could be made to azurerm_mssql_database module to change the server_id parameter to take a list rather than a string.

If that parameter could take multiple values (which it currently can't) then it would allow multiple databases to be created on multiple secondaries.

Thanks

Thanks
Simon

**Comment by tombuildsstuff** [comment]
@simonwhybrow-cbre unfortunately that's not how the Azure API works, which expects a single server here (since the DB is created within a single Server).

Instead it should be possible to achieve this by updating the Terraform Configuration to support this, presumably using `count` instead of a `for_each` since you'll need to multiply the database names by the server names here and then pick the relevant item - as such the community forum should be able to assist further with this.

Thanks!
