### ISSUE TITLE
Terraform denied access to storage accounts when storage vnet security has been applied

### ISSUE THREAD

**Issue by amcguign** [terraform-providers/terraform-provider-azurerm#828]
### Terraform Version
Terraform v0.11.3
AzureRM Provider 1.1.1

### Expected Behavior
An extensive deployment fully created and maintained by Terraform now has storage net security applied. 

Terraform is now unable to read the state of the storage accounts unless I add my laptop's public IP into the storage account firewall. All other existing resources (VMs, NSGs, etc etc) are readable. It's a chicken and egg situation really. Ideally I would like to use Terraform to whitelist specific IPs… to be able to use Terraform ... 

### Actual Behavior
```* azurerm_storage_container.XXXXXXr: azurerm_storage_container.XXXXXXXr: Error querying existence of storage container "XXXXXXX" in storage account "XXXXXXX": storage: service returned error: StatusCode=403, ErrorCode=403 This request is not authorized to perform this operation., ErrorMessage=no response body was available for error status code, RequestInitiated=Tue, 13 Feb 2018 15:10:48 GMT, RequestId=d9909597-001e-003d-1ddc-a4874f000000, API Version=, QueryParameterName=, QueryParameterValue=```

### Steps to Reproduce
`terraform plan` 

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- https://github.com/terraform-providers/terraform-provider-azurerm/issues/787

**Comment by khushil** [comment]
Bump. This is a PITA for any environment that isn't trivial as running without VNET security is dumb.

**Comment by carlin-q-scott** [comment]
Thanks for pointing out that the vnet security group isn't working for this resource. To get around this issue I had to add my public ip to the network_rules.ip_rules property of my azurerm_storage_account resource, like so:
```tf
resource "azurerm_storage_account" "example" {
  ...
  network_rules {
    ip_rules = ["my.public.ip.address"]
  }
}
```

There's also an error in [the documentation](https://www.terraform.io/docs/providers/azurerm/r/storage_account.html#ip_rules) for this property, which is that Azure does not accept CIDR format for it.

**Comment by tombuildsstuff** [comment]
hey @amcguign 

Thanks for opening this issue - apologies for the delayed response here!

As @carlin-q-scott has mentioned, it should be possible to achieve this using the `ip_rules` field within the `network_rules` block for a newly created Storage Account. Whilst this is by design in the Azure API (and as such I don't believe there's much we can do in Terraform to work around this) - it should be possible to work around this by running Terraform from within one of these Subnets (which, I appreciate isn't necessarily ideal). One other option would be to temporarily add/remove a firewall rules for the users current Public IP - but that's less than ideal (for example, what happens if multiple users manage different Storage Containers within the same account across machines, but modify the firewall rules?)

Given this is by design in the Azure API - I'm going to suggest [filing an issue on the Azure Rest API Specs repository](https://github.com/Azure/azure-rest-api-specs/issues) (which is where bugs and enhancements are tracked for the Azure API's) - since it feels like it should be possible to override this via the Resource Manager API's temporarily via some kind of access token, for instances such as this.

Thanks!
