### ISSUE TITLE
Support for Azure AD integration for Postgresql

### ISSUE THREAD

**Issue by googol** [terraform-providers/terraform-provider-azurerm#8291]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

The active directory integration for postgres on azure has become a GA feature that my team would like to use. However I was unable to find a way to enable it via terraform

### New or Affected Resource(s)

* azurerm_postgresql_server

### Potential Terraform Configuration

```hcl
# Copied from the example in the documentation with the addition of the last block

resource "azurerm_postgresql_server" "example" {
  name                = "example-psqlserver"
  location            = azurerm_resource_group.example.location
  resource_group_name = azurerm_resource_group.example.name

  administrator_login          = "psqladminun"
  administrator_login_password = "H@Sh1CoR3!"

  sku_name   = "GP_Gen5_4"
  version    = "9.6"
  storage_mb = 640000

  backup_retention_days        = 7
  geo_redundant_backup_enabled = true
  auto_grow_enabled            = true

  public_network_access_enabled    = false
  ssl_enforcement_enabled          = true
  ssl_minimal_tls_version_enforced = "TLS1_2"

  azure_ad_admin_id = "31e81e95-cbe1-4a44-8546-94673ef2bbae"
}

```

### References

* https://docs.microsoft.com/en-us/azure/postgresql/howto-configure-sign-in-aad-authentication

**Comment by tombuildsstuff** [comment]
hi @googol 

Thanks for opening this issue :)

Taking a look through here I believe this functionality is available via [the `azurerm_postgresql_active_directory_administrator` resource](https://www.terraform.io/docs/providers/azurerm/r/postgresql_active_directory_administrator.html) - would you be able to take a look and see if that works for you? Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by googol** [comment]
Thanks @tombuildsstuff for the quick and helpful reply!

That resource seems to do exactly what I want, I was so expecting that functionality to be a part of the server resource that I didn't even check the other resources!
