### ISSUE TITLE
azurerm_kubernetes_cluster_node_pool vnet_subnet_id is mandatory, not setting it leads to terraform recreating the node pool

### ISSUE THREAD

**Issue by omichels** [terraform-providers/terraform-provider-azurerm#8297]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.29
+ provider.azurerm v2.3.0
+ provider.helm v1.2.4
+ provider.kubernetes v1.11.1

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

per documention vnet_subnet_id is optional and is expected to inherit it from the default node pool, but not setting it
leads to a recreation of the second node pool

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Debug Output
```hcl
resource "azurerm_kubernetes_cluster_node_pool" "second-pool" {
      - availability_zones    = [] -> null
      - enable_auto_scaling   = false -> null
      - enable_node_public_ip = false -> null
      ~ id                    = "/subscriptions/00000000-0000-0000-0000-00000000/resourcegroups/elknodepooltestresourcegroup/providers/Microsoft.ContainerService/managedClusters/elknodepooltestk8s/agentPools/internal" -> (known after apply)
        kubernetes_cluster_id = "/subscriptions/00000000-0000-0000-0000-00000000/resourcegroups/elknodepooltestresourcegroup/providers/Microsoft.ContainerService/managedClusters/elknodepooltestk8s"
      - max_count             = 0 -> null
        max_pods              = 30
      - min_count             = 0 -> null
        name                  = "internal"
        node_count            = 2
      - node_labels           = {} -> null
      - node_taints           = [] -> null
        os_disk_size_gb       = 128
        os_type               = "Linux"
      - tags                  = {} -> null
        vm_size               = "Standard_DS2_v2"
      - vnet_subnet_id        = "/subscriptions/00000000-0000-0000-0000-00000000/resourceGroups/elknodepooltestresourcegroup/providers/Microsoft.Network/virtualNetworks/elknodepooltestnetvnetwork/subnets/default" -> null # forces replacement
    }
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @omichels 

Thanks for opening this issue.

At this time AKS only supports node pools located on the same virtual network - as such unfortunately AKS will provision this node pool on this virtual network by default, even if this field is unspecified. Whilst we could add validation to ensure that this is the same as other node pools on the cluster - we've been told (albeit a while ago now) that support for node pools on different subnets/networks is coming soon - as such we've opted to intentionally expose these fields to support this upcoming functionality.

In this instance it should be possible to fix this by updating the Terraform Configuration to include the ID of the Virtual Network here - in future when AKS ships support for node pools on multiple (internal/external networks) it should be possible to omit this field; however since this behaviour [is documented](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#vnet_subnet_id) I'm going to close this issue for the moment.

Thanks!
