### ISSUE TITLE
VMSS with Automatic OS Update and Shared Images

### ISSUE THREAD

**Issue by marcelkmfst** [terraform-providers/terraform-provider-azurerm#8301]
Hi,

AzureRM 2.24.

Shared Image Gallery and VMSS with automatic OS Upgrade enabled.

existing Shared Image Gallery version imported with Name "latest" like described in the documentation.

https://www.terraform.io/docs/providers/azurerm/d/shared_image_version.html

VMSS provisioning fails with

Error: Error creating Windows Virtual Machine Scale Set "vmss-app" (Resource Group "RG-TFCICDAPP105"): compute.VirtualMachineScaleSetsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="virtualMachineScaleSets with Automatic OS Upgrade enabled must use Platform or Gallery Image with version set to 'latest'."

Seems like that TF is not using the latest Version as expected. Tried recent as well, this is also not working...

**Comment by tombuildsstuff** [comment]
hi @marcelkmfst 

Thanks for opening this issue.

Unfortunately there's no Terraform Configuration posted here so it's hard for us to confirm the specific issue here; so that we can take a look into this can you please open a new issue [completing information requested in the bug report form](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Bug_Report.md) which has all of the information we need to look into this.

Thanks!
