### ISSUE TITLE
Terraform Azure Blob

### ISSUE THREAD

**Issue by asonitis365** [terraform-providers/terraform-provider-azurerm#835]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.3
AzureRM Provider 1.1.1

### Terraform Configuration Files
beconf.tfvars
resource_group_name = ""
storage_account_name = ""
container_name = ""
access_key = ""

### Expected Behavior
Being able to run terraform plan after moving backend to Azure blob

### Actual Behavior
Successfully configured the backend "azurerm"! Terraform will automatically
use this backend unless the backend configuration changes.

Initializing provider plugins...

The following providers do not have any version constraints in configuration,
so the latest version was installed.

To prevent automatic upgrades to new major versions that may contain breaking
changes, it is recommended to add version = "..." constraints to the
corresponding provider blocks in configuration, with the constraint strings
suggested below.

* provider.azurerm: version = "~> 1.1"

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.
[xxxxx@EMEAxxxxx azurerm]$ sudo terraform plan

Error: Error loading state: storage: service returned error: StatusCode=400, ErrorCode=InvalidUri, ErrorMessage=The requested URI does not represent any resource on the server.
RequestId:83729ef7-001e-001e-17e8-a45e07000000
Time:2018-02-13T16:37:05.6530684Z, RequestInitiated=Tue, 13 Feb 2018 16:37:05 GMT, RequestId=83729ef7-001e-001e-17e8-a45e07000000, API Version=, QueryParameterName=, QueryParameterValue=

[xxxxx@EMEAxxxxx azurerm]$ sudo terraform init -backend-config=beconf.tfvars

Initializing the backend...
Error refreshing state: storage: service returned error: StatusCode=400, ErrorCode=InvalidUri, ErrorMessage=The requested URI does not represent any resource on the server.
RequestId:863d5d5b-001e-0098-77e8-a492be000000
Time:2018-02-13T16:37:15.4518604Z, RequestInitiated=Tue, 13 Feb 2018 16:37:14 GMT, RequestId=863d5d5b-001e-0098-77e8-a492be000000, API Version=, QueryParameterName=, QueryParameterValue=

### Steps to Reproduce
1. `terraform plan`

### References
Are there any other GitHub issues (open or closed) or Pull Requests that should be linked here? For example:
- GH-1234

**Comment by tombuildsstuff** [comment]
hi @asonitis365 

Thanks for opening this issue - apologies for the delayed response here!

At this time Interpolations (e.g. variables) can't be used in the configuration for a Backend or a Provider - support for this is being tracked in https://github.com/hashicorp/terraform/issues/4149. As such, the configuration you're attempting to use is invalid - which is why you're seeing this error.

The `-backend-config=` command line switch you're using is to determine which path to source the backend configuration from if it's downloaded external to Terraform (such as generated from Vault - [there's an example in the documentation](https://www.terraform.io/docs/backends/config.html#partial-configuration)). When changing the backend file to use statically defined variables this works as expected - would you be able to take a look?

Thanks!
