### ISSUE TITLE
Azurerm_application_insights_web_test always forces replacement after resource is changed in Portal

### ISSUE THREAD

**Issue by lyubomirr** [terraform-providers/terraform-provider-azurerm#8356]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Both 2.24.0 and 2.23.0

### Affected Resource(s)
azurerm_application_insights_web_test

### Terraform Configuration Files
```
resource "azurerm_application_insights_web_test" "availability_test" {
...
  kind = "ping"
...
```
### Expected Behavior

There shoudn't be change detected in "kind" property after changing some setting in Azure Portal.

### Actual Behavior

`terraform plan` says that the argument "kind" is added with value of "ping" and needs replacement:

```+ kind = "ping" # forces replacement```

### Steps to Reproduce

1. Create new azurerm_application_insights_web_test with kind "ping"
2. Run `terraform apply`
3. Go to portal and change something - e.g add another region and then remove it (thats what I did)
4. Run `terraform plan`

**Comment by magodo** [comment]
@lyubomirr Thank you for submitting this!

The problem derives from the fact that Portal will not keep the `.kind` property in the API request when you editing the webtest, while it should do. #8372 will workaround this errornous behavior of Portal.

Besides, after you editing on Portal, the timeout will be changed into another default value picked by Portal, 120sec, and you will ends up seeing diff. Also, the test config will also be changed since Portal will change it. But those are in-place update fields, so you will not see terraform mark the resource to be replaced in that case.

Ultimately, we suggest Terraform users to manage Azure resource using Terraform only. A mix use of Terraform and Portal will cause problems like what you already encounted.

**Comment by lyubomirr** [comment]
@magodo Thank you very much for the quick answer and the pending fix!
