### ISSUE TITLE
Azurerm Features block error on Terraform v0.13.2

### ISSUE THREAD

**Issue by gautam-ramini** [terraform-providers/terraform-provider-azurerm#8375]
When features block is not added on Azurerm provider, below error is received on executing terraform plan command:

Error: "features": required field is not set

After adding features block as below, terraform init command gives the error:

```
terraform {
	required_providers {
		azurerm = {
			source = "hashicorp/azurerm"
			version = "2.26.0"
			features {}
		}
	}
}
```

There are some problems with the configuration, described below.

The Terraform configuration must be valid before initialization so that
Terraform can determine which modules and providers need to be installed.

Error: Missing key/value separator

  on providers.tf line 17, in terraform:
  14:     azurerm = {
  15:       source = "hashicorp/azurerm"
  16:       version = "2.26.0"
  17:           features {}

Expected an equals sign ("=") to mark the beginning of the attribute value.

Please suggest if  i'm incorrect on syntax here or if there is a workaround for this.

**Comment by tombuildsstuff** [comment]
hi @gautam-ramini 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
