### ISSUE TITLE
Dissociate a static public IP+network interface from a VM in Azure 

### ISSUE THREAD

**Issue by harshagv** [terraform-providers/terraform-provider-azurerm#8381]
How to dissociate a static public IP/network interface or both of it from a VM and attach it to another VM using **terraform** in **MS Azure** just like an Elastic IP in AWS?

If azure terraform does not works, azure CLI is also feasible.

I was only able to find a way to detach an IP using azure CLI but could not be able to attach it to a new VM, due to an error - **NicInUse**.

**Comment by tombuildsstuff** [comment]
hi @harshagv 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
