### ISSUE TITLE
How do I create an WebJob?

### ISSUE THREAD

**Issue by colutti** [terraform-providers/terraform-provider-azurerm#8390]
I would like to create a WebJob on a Webapp on Azure, but I was not able to find any documentation regarding this. Is this possible? If so, can somebody provide a snippet?

**Comment by tombuildsstuff** [comment]
hi @colutti 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
