### ISSUE TITLE
Azure provider - keys for keyVault

### ISSUE THREAD

**Issue by omershliva** [terraform-providers/terraform-provider-azurerm#8406]
How do I add via terraform more than one key secret for my key vault?
Thanks,
Omer

**Comment by tombuildsstuff** [comment]
hi @omershliva 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
