### ISSUE TITLE
Error while trying container_access_type to be public

### ISSUE THREAD

**Issue by omershliva** [terraform-providers/terraform-provider-azurerm#8421]
provider "azurerm" {
version = "=2.25.0"
features {}
}

resource "azurerm_resource_group" "storage" {
  name     = "tfstorageresourcegroup"
  location = "North Europe"
}

resource "azurerm_virtual_network" "Vnet" {
  name                = "virtnetforstorage"
  address_space       = ["10.0.0.0/16"]
  location            = "${azurerm_resource_group.storage.location}"
  resource_group_name = "${azurerm_resource_group.storage.name}"
}

resource "azurerm_subnet" "main" {
  name                 = "subnetforstorage"
  resource_group_name  = "${azurerm_resource_group.storage.name}"
  virtual_network_name = "${azurerm_virtual_network.Vnet.name}"
  address_prefix       = "10.0.2.0/24"
  service_endpoints    = ["Microsoft.Sql", "Microsoft.Storage"]
}

resource "azurerm_storage_account" "account" {
  name = "${azurerm_resource_group.storage.name}"
  location = "${azurerm_resource_group.storage.location}"
  account_tier = "Standard"
  resource_group_name = "${azurerm_resource_group.storage.name}"
  account_replication_type = "LRS"
  enable_https_traffic_only = true
  account_kind             = "BlobStorage"
  allow_blob_public_access = true

  network_rules {
    default_action             = "Deny"
    ip_rules                   = ["100.0.0.1"]
    virtual_network_subnet_ids = [azurerm_subnet.main.id]
  }
}

resource "azurerm_storage_container" "container" {
    name = "tftestcontainer"
    storage_account_name = "${azurerm_storage_account.account.name}"
    container_access_type = "blob"
}

resource "azurerm_storage_blob" "blob" {
    name = "tftestblob"
    storage_account_name = "${azurerm_storage_account.account.name}"
    storage_container_name = "${azurerm_storage_container.container.name}"
    type = "Page"
    size = "5120"
}

Error: Error retrieving Container "tftestcontainer" (Account "tfstorageresourcegroup" / Resource Group "tfstorageresourcegroup"): containers.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: Service returned an error. Status=403 Code="AuthorizationFailure" Message="This request is not authorized to perform this operation.\nRequestId:324f564a-301e-002e-7f6d-875c79000000\nTime:2020-09-10T12:29:09.1095587Z"

Is this Terraform's issue or Azure?

**Comment by magodo** [comment]
@omershliva 

The error is because you have specified the `network_rules` in the storage account, which will deny any request form the host running Terraform. You must identify the internet facing IP addresses used by your network and list them in the `ip_rules` ([more info](https://docs.microsoft.com/en-us/azure/storage/common/storage-network-security?toc=/azure/storage/blobs/toc.json#configuring-access-from-on-premises-networks)).

As this is an Azure question, while this forum here is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised using one of the [Community Resources](https://www.terraform.io/community.html). Hence I'm gonna close this issue for now.

**Comment by magodo** [comment]
@omershliva I received your Email and tried to provision the config you provided above with `network_rules` removed.

The provision still failed because [BlobStorage account type doesn't support page blob service](https://docs.microsoft.com/en-us/azure/storage/common/storage-account-overview?toc=/azure/storage/blobs/toc.json#types-of-storage-accounts). You shall choose another account type (`account_kind`) that supports page blob service, e.g. `StorageV2`.
