### ISSUE TITLE
Missing options for storage accounts?

### ISSUE THREAD

**Issue by blindzero** [terraform-providers/terraform-provider-azurerm#8468]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

Hey everybody,

am I too blind or are there options missing on storage accounts to set the following options:

- connectivity method (public all, public selected, private)
- data protection options (soft delete, tracking, ...)

Thanks,
M.

**Comment by tombuildsstuff** [comment]
hi @blindzero

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by blindzero** [comment]
But why do you have a category question then?
