### ISSUE TITLE
Load Balancer backend address pool configuration

### ISSUE THREAD

**Issue by joaquinpretell** [terraform-providers/terraform-provider-azurerm#8494]
Hello, 

Im making a load balancer module and i saw on the backend_address_pool resource, theres only a way to create it, but not to assign a scale set or the vms. 

resource "azurerm_lb_backend_address_pool" "example" {
  resource_group_name = azurerm_resource_group.example.name
  loadbalancer_id     = azurerm_lb.example.id
  name                = "acctestpool"
}

I did some investigation and i found, i can add the vms associating the network interface with the backend pool. I want to know if this is the only way for vms or theres another.
https://www.terraform.io/docs/providers/azurerm/r/network_interface_backend_address_pool_association.html

resource "azurerm_network_interface_backend_address_pool_association" "example" {
  network_interface_id    = azurerm_network_interface.example.id
  ip_configuration_name   = "testconfiguration1"
  backend_address_pool_id = azurerm_lb_backend_address_pool.example.id
}

For scale sets, i can attach it when i create it with a complete scale set module, following the example, but im not developing an entire scale set module inside the load balancer. I want to know if theres a way to associate it with some of the code or theres another way for this case.
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html

Best Regards

**Comment by tombuildsstuff** [comment]
hi @joaquinpretell 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
