### ISSUE TITLE
Continuous Deployment

### ISSUE THREAD

**Issue by felipefrocha** [terraform-providers/terraform-provider-azurerm#8530]
Was this issue already implemented?

https://github.com/terraform-providers/terraform-provider-azurerm/issues/4090

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by njuCZ** [comment]
@felipefrocha Could you please opening a Feature Request following the template, so we could track it conveniently

**Comment by tombuildsstuff** [comment]
hi @felipefrocha 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
