### ISSUE TITLE
how to remove trailing new line in key vault after using heredoc syntax

### ISSUE THREAD

**Issue by sanjeevsharma-1** [terraform-providers/terraform-provider-azurerm#8548]
we are trying to create keyvault secret using Terraform at runtime and we after building the code, it looks something like this

resource "azurerm_key_vault_secret" "AggregatorsKeySpaceName" {
  name         = "AggregatorsKeySpaceName"
  value        = <<EOT
KV_SECRET_VALUE
EOT
  key_vault_id = azurerm_key_vault.keyvault.id
}

the issue is that, heredoc syntax adds a trailing new line at the end of the "value", hence the value is stored something like this 

![image](https://user-images.githubusercontent.com/68319188/93772641-af72e000-fc3c-11ea-9cd8-ccc1304f2808.png)

As you can see in the image, the secret value 5 is trailed with new line and it kind of changes the meaning of value, in case of passwords and other KV secret stored.
when we try reading this KV secret value, it consists of new line, which kind of actually changes the context of the KV secret.

**Comment by tombuildsstuff** [comment]
hi @sanjeevsharma-1 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
