### ISSUE TITLE
How, if possible, to add “Archive to a storage account” in terraform?

### ISSUE THREAD

**Issue by omershliva** [terraform-providers/terraform-provider-azurerm#8574]
Is there an option to enable "Archive to a storage account" in Keyvault diagnostic in Azure provider of Terraform?

**Comment by tombuildsstuff** [comment]
hi @omershliva 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
