### ISSUE TITLE
Network security rules order in NSG

### ISSUE THREAD

**Issue by sylr** [terraform-providers/terraform-provider-azurerm#858]
Hi,

I failed to determine how the rules are sorted into a `network security group` object in terraform.

This is problematic since the ID generation has changed from v0.2.2 to v1.1.1 and now terraform show me huge diff cause the ID are not the same as they were previously.

Also if the rules are not written in the "same order" as they are stored in terraform, you will have a diff in the plan that you can't get rid cause applying this plan won't have any effect.

I suggest that terraform sort the rules by `direction` and then by `priority` as this combination is unique.

Regards.

**Comment by sylr** [comment]
@tombuildsstuff I'd need your input on this.

I see diffs like that :

```
      security_rule.1400690338.access:                                       ""               => "Allow"
      security_rule.1400690338.description:                                  ""               => ""
      security_rule.1400690338.destination_address_prefix:                   ""               => "*"
      security_rule.1400690338.destination_address_prefixes.#:               "0"              => "0"
      security_rule.1400690338.destination_application_security_group_ids.#: "0"              => "0"
      security_rule.1400690338.destination_port_range:                       ""               => "15672"
      security_rule.1400690338.destination_port_ranges.#:                    "0"              => "0"
      security_rule.1400690338.direction:                                    ""               => "Inbound"
      security_rule.1400690338.name:                                         ""               => "rabbitmngt"
      security_rule.1400690338.priority:                                     ""               => "1020"
      security_rule.1400690338.protocol:                                     ""               => "*"
      security_rule.1400690338.source_address_prefix:                        ""               => ""
      security_rule.1400690338.source_address_prefixes.#:                    "0"              => "1"
      security_rule.1400690338.source_address_prefixes.757194839:            ""               => "217.109.68.123"
      security_rule.1400690338.source_application_security_group_ids.#:      "0"              => "0"
      security_rule.1400690338.source_port_range:                            ""               => "*"
      security_rule.1400690338.source_port_ranges.#:                         "0"              => "0"
      security_rule.213218834.access:                                        "Allow"          => ""
      security_rule.213218834.description:                                   ""               => ""
      security_rule.213218834.destination_address_prefix:                    "*"              => ""
      security_rule.213218834.destination_address_prefixes.#:                "0"              => "0"
      security_rule.213218834.destination_application_security_group_ids.#:  "0"              => "0"
      security_rule.213218834.destination_port_range:                        "15672"          => ""
      security_rule.213218834.destination_port_ranges.#:                     "0"              => "0"
      security_rule.213218834.direction:                                     "Inbound"        => ""
      security_rule.213218834.name:                                          "rabbitmngt"     => ""
      security_rule.213218834.priority:                                      "1020"           => "0"
      security_rule.213218834.protocol:                                      "*"              => ""
      security_rule.213218834.source_address_prefix:                         ""               => ""
      security_rule.213218834.source_address_prefixes.#:                     "2"              => "0"
      security_rule.213218834.source_address_prefixes.757194839:             "217.109.68.123" => ""
      security_rule.213218834.source_address_prefixes.83011556:              "178.238.62.254" => ""
      security_rule.213218834.source_application_security_group_ids.#:       "0"              => "0"
      security_rule.213218834.source_port_range:                             "*"              => ""
```

Here `1400690338` & `213218834` is the same rule modified (unique tuple [direction, priority] is the same) but for some unknown reason (at least to me), plan says it's going to remove `213218834` & create `1400690338` instead of just updating `213218834` with the new values.

**Comment by sylr** [comment]
@tombuildsstuff @apparentlymart guys, if you could enlighten me I'd like to work on that.

Thanks.

**Comment by sylr** [comment]
Hi @mbfrahry @katbyte could you help me out ?

**Comment by sylr** [comment]
Hi @katbyte,

Forget the original issue, It's more about https://github.com/terraform-providers/terraform-provider-azurerm/issues/858#issuecomment-382340450.

When I change a security rule, add or remove properties, the key of the security rule (`213218834` in the previous comment) is recomputed (to `1400690338`)  leading to a big diff, entirely removing the previous security rule and recreating it with the new properties.

What I expect is that that the key of the security rule stays the same and and the diff show the only the changes to properities added/modified/deleted.

Regards.

**Comment by sylr** [comment]
@katbyte I've tried to make a HashFunction for the security rules keys https://github.com/terraform-providers/terraform-provider-azurerm/pull/1152 that only hash the tuple of properties that are supposed to be unique.

Unfortunately with that function `terraform plan` says there is no diff when I make change to security rules locally because it seems that the function that does the diff of TypeSet attributes only looks if there is a change of keys. i.e.  :

https://github.com/hashicorp/terraform/blob/c1bc0be7b2c990ae0d95a72e560bc814db2ce60c/helper/schema/schema.go#L1056-L1058

**Comment by sylr** [comment]
@katbyte we chose on purpose to use `security_rule` inside `azurerm_security_group` because it has the incredible advantage to delete rules that could have been manually added.

So, the solution to improve the situation would be to combine the custom Hash Function with a CustomizeDiff ?

**Comment by katbyte** [comment]
@sylr,

Thats a very valid reason! 

To improve the situation you will need to change to a `TypeList` so that when a security rule changes it doesn't create an entirely new entry. Next you will need to normalize the order of the list data: from terraform in a `CustomizeDiff`, from azure on read and write a `MigrateState` function to ensure any existing state files are migrated to the new format and ordering.

**Comment by tombuildsstuff** [comment]
hey @sylr

Thanks for opening this issue.

To add a some additional context to the comments above:

1. We changed `security_rule` from a Set to a List in v0.2.2 -> v0.3.3 and then from a List to a Set in a later release, since Rules can be returned in different orders (which is why we need a Set rather than a List).
2. New fields have been added to the Set recently (`source_application_security_group_ids` as an example) which forces a recomputation of the Hash Value (the integer seen above)

Whilst we could work around this by using a State Migration to update the Hash Value, in general we don't when we add a new field to a Set (rather than changing a value) - since the Plan should show no changes apart from the Hash Value change (as above). This is because this field could be being managed outside of Terraform, and could have changes (e.g. it's been set via an ARM Template, and so Terraform should clear it since the configuration doesn't match).

As such whilst we could potentially add a State Migration to update the Hash Value between versions - this isn't the right place to use a `CustomizeDiff` approach here since this is intentional (as it's consistent in the other providers), where running `terraform apply` will make no changes here (technically it'll re-submit the Security Rules to Azure, but that shouldn't actually make any changes, at least from what I can see).

Thanks!

**Comment by robfrut135** [comment]
Hi,
I'm getting the same error/problem/bug using azurerm_network_security_rule

If you run the templates at the first time TF creates the new rules perfectly 

>>> Apply complete! Resources: 7 added, 0 changed, 0 destroyed.

but if you run again without performs any change (manual in cloud or in code) TF delete all rules applied with azurerm_network_security_rule. TF does that because detect changes in azurerm_network_security_group.

>>> Apply complete! Resources: 0 added, 1 changed, 0 destroyed.

thanks

**Comment by tombuildsstuff** [comment]
👋 

Since there's a workaround mentioned above (upgrading to the latest version of the provider & applying) I'm going to close this issue for the moment.

Thanks!
