### ISSUE TITLE
Error in TF plan when reading from Azure blob storage

### ISSUE THREAD

**Issue by sanjeevsharma-1** [terraform-providers/terraform-provider-azurerm#8582]
we are trying to aks namespace in AKS cluster with TF and in order to do so, we are trying to fetch TF state file of AKS cluster which is already created before this step.

below is the code present in main.tf file 

data "terraform_remote_state" "aks_config" {
  backend = "azurerm"
  config = {
    storage_account_name = var.blobStorageAccount
    container_name       = "terraformstate"
    key                  = "AKS/${var.env}/terraform.tfstate"
    resource_group_name  = var.GenericResourceName
  }
}

we are getting error in TF plan step

Error: Error loading state error

  on main.tf line 10, in data "terraform_remote_state" "aks_config":
  10:   backend = "azurerm"

error loading the remote state: Error retrieving keys for Storage Account
"***": storage.AccountsClient#ListKeys: Invalid input:
autorest/validation: validation failed: parameter=accountName
constraint=MaxLength value="***" details: value length
must be less than or equal to 24

the problem is that, same code works for other environment we created before and it's not working for a particular environment only.

**Comment by tombuildsstuff** [comment]
hi @sanjeevsharma-1 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
