### ISSUE TITLE
Terraform script for application gateway v2 with multiple listeners.

### ISSUE THREAD

**Issue by srusru** [terraform-providers/terraform-provider-azurerm#8585]
I have a requirement to create a terraform script for application gateway v2 which have 50 different hostnames.(test.com, test1.com, test2.com etc)Does terraform support having listeners for 50 sites in an application gateway using different state files instead of a single state file? how does incremental terraform apply work? Any help is appreciated. Thanks in advance.

**Comment by tombuildsstuff** [comment]
hi @srusru 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
