### ISSUE TITLE
azurerm_policy_set_definition does not like list

### ISSUE THREAD

**Issue by yellowhat** [terraform-providers/terraform-provider-azurerm#8597]
### Terraform (and AzureRM Provider) Version
```
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0
```

### Terraform Configuration Files
```hcl
terraform {
  required_version = ">= 0.12"
}

provider "azurerm" {
  environment = "public"
  version     = ">= 2.0.0"
  features {}
}


resource "azurerm_policy_set_definition" "test" {
  name         = "testPolicySet"
  policy_type  = "Custom"
  display_name = "Test Policy Set"

  parameters = <<PARAMETERS
    {
        "VMimages": {
            "value": [
                "/subs/.../1",
                "/subs/.../2"
            ]
        }
    }
PARAMETERS

  # Audit Dependency agent deployment - VM Image (OS) unlisted
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/11ac78e3-31bc-4f0c-8434-37ab963cea07"
    parameters = {
      listOfImageIdToInclude_windows = []
      listOfImageIdToInclude_linux = "[parameters('VMimages')]"
    }
  }
}
```

### Debug Output
```
Error: Incorrect attribute value type

  on a.tf line 31, in resource "azurerm_policy_set_definition" "test":
  31:     parameters = {
  32:       listOfImageIdToInclude_windows = []
  33:       listOfImageIdToInclude_linux = "[parameters('VMimages')]"
  34:     }

Inappropriate value for attribute "parameters": element
"listOfImageIdToInclude_windows": string required.
```

### Expected Behavior
Validate sucessfully

### Actual Behavior
Does not recognise the `parameters` as string.

### Steps to Reproduce
1. `terraform init`
2. `terraform validate`

**Comment by ArcturusZhang** [comment]
Hi @yellowhat thanks for this issue!

This is a known issue that has been reported in https://github.com/terraform-providers/terraform-provider-azurerm/issues/8159 and should have been fixed by https://github.com/terraform-providers/terraform-provider-azurerm/pull/8270 which should be released in v2.29.0.

Since this has been fixed by https://github.com/terraform-providers/terraform-provider-azurerm/pull/8270, I am going to close this PR and could you please have a try when the new version of the provider is released? Please feel free to comment if any issues still persist.

**Comment by yellowhat** [comment]
Dear @ArcturusZhang,
I have just retried with the 2.29 version and got the same error.

```
Initializing the backend...

Initializing provider plugins...
- Finding hashicorp/azurerm versions matching ">= 2.0.0"...
- Installing hashicorp/azurerm v2.29.0...
- Installed hashicorp/azurerm v2.29.0 (signed by HashiCorp)

Terraform has been successfully initialized!

You may now begin working with Terraform. Try running "terraform plan" to see
any changes that are required for your infrastructure. All Terraform commands
should now work.

If you ever set or change modules or backend configuration for Terraform,
rerun this command to reinitialize your working directory. If you forget, other
commands will detect it and remind you to do so if necessary.

Error: Incorrect attribute value type

  on a.tf line 31, in resource "azurerm_policy_set_definition" "test":
  31:     parameters = {
  32:       listOfImageIdToInclude_windows = []
  33:       listOfImageIdToInclude_linux = "[parameters('VMimages')]"
  34:     }

Inappropriate value for attribute "parameters": element
"listOfImageIdToInclude_windows": string required.
```

Is my syntax wrong?

Thanks

**Comment by yellowhat** [comment]
May I ask to reopen this bug?

**Comment by ArcturusZhang** [comment]
Hi @yellowhat this issue was fixed by introducing a new attribute to replace this `parameters` attribute since the map in terraform does not support its values to have different types - therefore in the implementation of `parameters` attribute, we are assuming all the entries have the type of string (which is wrong and lack of consideration, my apologies).

Changing of the type of an attribute is considered as a breaking change therefore we have to introduce the new `parameter_values` to supersede it. You could try this:
```
resource "azurerm_policy_set_definition" "test" {
  # omitting irrelevant part

  # Audit Dependency agent deployment - VM Image (OS) unlisted
  policy_definition_reference {
    policy_definition_id = "/providers/Microsoft.Authorization/policyDefinitions/11ac78e3-31bc-4f0c-8434-37ab963cea07"
    parameter_values = <<VALUES
    {
      "listOfImageIdToInclude_windows": {
         "value": []
      }
      "listOfImageIdToInclude_linux": {
         "value": "[parameters('VMimages')]"
      }
    }
   VALUES
  }
}
```
Please note that the `parameter_values` is a JSON string and has the same syntax as the `parameters` in `azurerm_policy_assignment` resource.

**Comment by yellowhat** [comment]
Dear @ArcturusZhang,
thanks for the explanation.
Sorry I did not read the updated documentation.
