### ISSUE TITLE
Terraform template_file resource not detecting the changes when we do some changes on template file

### ISSUE THREAD

**Issue by suriya91** [terraform-providers/terraform-provider-azurerm#8604]
Tried to change the content of template file (change the vars). i did terraform plan it says "No changes. Infrastructure is up-to-date." 
i am using the template as custom data for VM . (data.template_file.custom_data.rendered)

code :
data "template_file" "custom_data" {
  template = file("../custom_data/test.tpl")
  vars = {
    azure_login_identity            = "xxxx"
  }
}
---------------------------------------------------------------
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.28.0
+ provider registry.terraform.io/hashicorp/template v2.1.2
+ hashicorp/template v2.1.2

Did anyone find the same issue and any workaround or bugfix helps ?

**Comment by tombuildsstuff** [comment]
hi @suriya91 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
