### ISSUE TITLE
Error: Incompatible provider version

### ISSUE THREAD

**Issue by soumyaraja** [terraform-providers/terraform-provider-azurerm#8683]
Failed to instantiate provider
"registry.terraform.io/terraform-providers/azure" to obtain schema: unknown
provider "registry.terraform.io/terraform-providers/azure"
terraform version  0.13.3
following two provider.tf failed
1# 
provider "google" {
  version = "~> 3.19.0"
  credentials = file(var.gcp_credentials_file_path)
  project = var.gcp_project_id
  region = var.gcp_region

  }

  provider "aws" {
  version = "~> 3.0"
  region  = "us-west-2"
  }

  terraform {
    required_providers {
      azurerm = {
        source = "hashicorp/azurerm"
        version = "2.29.0"
      }
    }
  }

2 #

  provider "google" {
  version = "~> 3.19.0"
  credentials = file(var.gcp_credentials_file_path)
  project = var.gcp_project_id
  region = var.gcp_region

  }

  provider "aws" {
  version = "~> 3.0"
  region  = "us-west-2"
  }

  provider "azurerm" {
  # whilst the `version` attribute is optional, we recommend pinning to a given version of the Provider
  version = "=2.20.0"
  features {}
}

**Comment by tombuildsstuff** [comment]
hi @soumyaraja 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
