### ISSUE TITLE
azurerm provider doesn't work with terraform 0.13.3 or 0.12.29

### ISSUE THREAD

**Issue by rturnbull1977** [terraform-providers/terraform-provider-azurerm#8685]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.12.29
+ provider.azuread v0.7.0
+ provider.azurerm v1.44.0

Alternatively
Terraform v0.13.3
+ provider.azuread v1.0.0
+ provider.azurerm v2.29.0

### Affected Resource(s)

For version v0.12.29

always returns Error: rpc error: code = Unavailable desc = transport is closing

For version v0.13.3

always returns Error: "features": required field is not set - even when I have gone through and configured a empty feature block = features {}

### Expected Behavior

Should have been able to run terraform validate without the feature error. Should have been able to run terraform plan without the rpc error.

### Steps to Reproduce

terraform validate .

terraform plan

**Comment by tombuildsstuff** [comment]
hi @rturnbull1977 

Thanks for opening this issue.

When using version 2.0 of the Azure Provider or later you need to define a Provider block:

```
provider "azurerm" {
  features {}
}
```

Which we use to determine the behaviour of the provider - as such you should be able to update the Terraform Configuration to include this and this should start working. Since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but if that doesn't work for you then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by rturnbull1977** [comment]
Ah I have added that all over the place in my configuration.

provider "azurerm" {
  alias = "azurerm-test"
  features {}
  skip_provider_registration = "true"
}

This added all over the place in my code where I use 'azurerm' has provided me with NO SOLUTION.

Still have error:

Error: "features": required field is not set

Any suggestions for this would be helpful as I don't think I'm getting the support .
