### ISSUE TITLE
Mandatory "features" block is breaking best-practice usage of "terraform validate" (revisited)

### ISSUE THREAD

**Issue by gchappell99** [terraform-providers/terraform-provider-azurerm#8727]
https://github.com/terraform-providers/terraform-provider-azurerm/issues/7359 is unfortunately locked so I can't discuss it here, but I feel like this may warrant further discussion.

With Terraform 0.13.x support for module-level `depends_on` functionality exists. But this requires that the module being depended on _must not_ have a `provider {}` block and the `plan`/`apply` will fail if this is present. So the "solution" is to remove all of those blocks from our modules which will allows our modules to be depended upon if necessary and receive their provider configuration from the calling module. But this breaks two things:

* Terratest tests, which I've worked around by "injecting" an `empty_features.tf` file into the test directory that contains `provider "azurerm" { features {}}` so that when there _is_ no calling module, the modules can still be tested individually
* pre-commit Git hooks for `terraform validate` because this step will always fail, citing the missing `features {}` as the issue. I currently have no workaround for this apart from disabling/skipping this pre-commit hook entirely on commit, which I don't see as a good solution

I don't currently have a simple reproduction for this issue and I hope the explanation of the issue is enough, but if there is a need then I can put something together.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @gchappell99 

Thanks for opening this issue.

The `features` block is explicitly required since this controls the behaviour of the Azure Provider and is destructive by default - to be able to increase the reliability of certain operations (for example, trying to recreate a VM with an existing OS disk will fail, unless you update the "create_mode" field from "Empty" to "Attach" - however updating this configuration in other cases isn't valid - so the Azure API is designed in such a manner that it's not possible to create idempotent resources).

Whilst having this block be mandatory isn't ideal - in practice where this needs to be destructive by default, it's intentionally required so that users are aware of this. It's worth noting that prior to 2.0, many users were confused as to which provider instance was being used when using modules - due to the Subscription ID etc being optional and sourced from the Azure CLI.

As mentioned in #7359 ultimately this is a bug in Terraform Core regarding `terraform validate` [which is being tracked in this issue](https://github.com/hashicorp/terraform/issues/21408) - as such whilst I'd like to thank you for opening this issue, I'm going to close this issue in favour of that one. In the interim you should be able to work around this [using the pattern shown in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7359#issuecomment-648711339).

Thanks!
