### ISSUE TITLE
Required "features" field in provider configuration block breaks isolated module validation

### ISSUE THREAD

**Issue by cpdohert** [terraform-providers/terraform-provider-azurerm#8733]
Consider the below (incomplete) terraform config file.  According to https://www.terraform.io/docs/configuration/modules.html, the following things are true:

>"A module intended to be called by one or more other modules **must not contain any provider blocks** [...]"

>"For backward compatibility with configurations targeting Terraform v0.10 and earlier Terraform **does not produce an error for a provider block in a shared module** if the module block only uses features available in Terraform v0.10, but that is a legacy usage pattern that is no longer recommended. "

`terraform -help validate` says:
>Validate runs checks that verify whether a configuration is syntactically valid and internally consistent, regardless of any  provided variables or  existing state. It is thus **primarily useful for general verification of reusable modules**, including correctness of attribute names and value types.

Prior to azurerm 2.0, I could run `terraform validate` within my reusable module directory and get the appropriate response.  With 2.0, since I _must_ have a `provider "azurerm" { features {} }` block, `terraform validate` throws an error even though the module syntax is correct.

As a workaround I can add a `provider "azurerm" { features {} }` block to the module main.tf, but this is explicitly disallowed and at some point will presumably cause a validation failure all on its own.  Also I have to remember to remove it before finalizing the module.

Alternately, I can create a root module that calls the reusable module under development, but this doubles my work as I refine the interface to the module because I have to update all the variables and outputs in two places.  It's also overkill, as _all_ I want to do is run `terraform validate` to verify syntax and types.

I note that `azurerm` is the _only_ major cloud provider to have a **required** top-level parameter.  It seems an obvious fix would be to make the block optional, since every parameter it could currently contain is optional and has a default.

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.2
+ provider registry.terraform.io/hashicorp/azuread v1.0.0
+ provider registry.terraform.io/hashicorp/azurerm v2.30.0
+ provider registry.terraform.io/hashicorp/random v2.3.0

### Affected Resource(s)

N/A: problem with provider syntax

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = ">= 2.30.0"
    }
    azuread = {
      source  = "hashicorp/azuread"
      version = ">= 1.0.0"
    }
    random = {
      source  = "hashicorp/random"
      version = ">= 2.3.0"
    }
  }
}

# External resources

data "azurerm_public_ip" "firewall" {
  name                = var.public_ip_name
  resource_group_name = var.public_ip_resource_group_name
}

data "azurerm_key_vault" "foo" {
  name                = var.key_vault_name
  resource_group_name = var.resource_group_name
}

# Virtual network to contain the firewall and container instances
resource "azurerm_virtual_network" "bar" {
  name                = "bar-${var.unique_tag}"
  resource_group_name = var.resource_group_name
  location            = var.resource_group_location
  address_space       = ["10.0.0.0/16"]

  tags = local.common_tags
}
[...]
```

### Expected Behavior

`terraform validate` returns `Success! The configuration is valid.`

### Actual Behavior

`terraform validate` returns `Error: "features": required field is not set`

### Steps to Reproduce

1. `terraform apply`

### References

None

**Comment by tombuildsstuff** [comment]
hi @cpdohert

Thanks for opening this issue.

The `features` block is explicitly required since this controls the behaviour of the Azure Provider and is destructive by default - to be able to increase the reliability of certain operations (for example, trying to recreate a VM with an existing OS disk will fail, unless you update the "create_mode" field from "Empty" to "Attach" - however updating this configuration in other cases isn't valid - so the Azure API is designed in such a manner that it's not possible to create idempotent resources).

Whilst having this block be mandatory isn't ideal - in practice where this needs to be destructive by default, it's intentionally required so that users are aware of this. It's worth noting that prior to 2.0, many users were confused as to which provider instance was being used when using modules - due to the Subscription ID etc being optional and sourced from the Azure CLI.

As mentioned in #7359 ultimately this is a bug in Terraform Core regarding `terraform validate` [which is being tracked in this issue](https://github.com/hashicorp/terraform/issues/21408) - as such whilst I'd like to thank you for opening this issue, I'm going to close this issue in favour of that one. In the interim you should be able to work around this [using the pattern shown in this comment](https://github.com/terraform-providers/terraform-provider-azurerm/issues/7359#issuecomment-648711339).

Thanks!
