### ISSUE TITLE
default values for postgresql_server threat policy attributes are list with empty string instead of empty list

### ISSUE THREAD

**Issue by fgarcia-cnb** [terraform-providers/terraform-provider-azurerm#8738]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

terraform v0.12.24
azurerm v2.30.0

### Affected Resource(s)

* `azurerm_postgresql_server`

### Terraform Configuration Files

```hcl
variable "threat_policy_disabled_alerts" {
  default     = []
  type        = list(string)
  description = "List of alerts to disable."
}

variable "threat_policy_email_addresses" {
  default     = []
  type        = list(string)
  description = "List of email addresses to alert."
}

resource "azurerm_postgresql_server" "postgres_sql" {
...
  dynamic "threat_detection_policy" {
      for_each = var.threat_policy_enabled == true ? [1] : []

      content {
        enabled                    = true
        disabled_alerts            = var.threat_policy_disabled_alerts
        email_account_admins       = var.threat_policy_email_account_admins
        email_addresses            = var.threat_policy_email_addresses
        retention_days             = var.threat_policy_retention_days
        storage_account_access_key = var.threat_policy_sa_key != "" ? var.threat_policy_sa_key : null
        storage_endpoint           = var.threat_policy_sa_endpoint != "" ? var.threat_policy_sa_endpoint : null
      }
  }
}
```
### Expected Behavior

Expect list of disabled alerts and list of email addresses set to empty list. re-applying should see no infrastructure changes

### Actual Behavior

initial apply succeeds. subsequent applies detect the following changes
```hcl
~ threat_detection_policy {
          ~ disabled_alerts      = [
              - "", //should be empty list, not list with empty string
            ]
            email_account_admins = false
          ~ email_addresses      = [
              - "", //should be empty list, not list with empty string
            ]
            enabled              = true
            retention_days       = 0
        }
```
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

tried setting default values to [""], instead of empty list but get the following error:
```hcl
Error: expected threat_detection_policy.0.disabled_alerts.0 to be one of [Sql_Injection Sql_Injection_Vulnerability Access_Anomaly Data_Exfiltration Unsafe_Action], got 
```

**Comment by sigv** [comment]
The upstream API returns an array with one empty string, so this is not an API parsing issue:

```text
AzureRM Response for https://management.azure.com/subscriptions/b7d789f4-c24d-4837-9a23-38bd810ad3dc/resourceGroups/Example/providers/Microsoft.DBforPostgreSQL/servers/example/securityAlertPolicies/Default?api-version=2017-12-01
{"properties":{"disabledAlerts":[""],"emailAddresses":[""]}}
```

While the `email_addresses` issue can indeed be worked around by setting that value to `[""]`, you will always have `disabled_alerts` trying to change from `[""]` to `[]` on every plan.

**Comment by sigv** [comment]
#7992 appears to be a duplicate with a not-so-well-constructed name.

**Comment by sigv** [comment]
It looks like this logic should be in [azurerm/internal/services/postgres/postgresql_server_resource.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/490186dff26abd2eca87ed5a0e486fa1b27b1905/azurerm/internal/services/postgres/postgresql_server_resource.go) but I can't seem to figure out where in the chain (between potential schema definition changes, [`expandSecurityAlertPolicy`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/490186dff26abd2eca87ed5a0e486fa1b27b1905/azurerm/internal/services/postgres/postgresql_server_resource.go#L852-L858) and [`flattenSecurityAlertPolicy`](https://github.com/terraform-providers/terraform-provider-azurerm/blob/490186dff26abd2eca87ed5a0e486fa1b27b1905/azurerm/internal/services/postgres/postgresql_server_resource.go#L901-L902)) the transformation should take place so that defaults work.

SDK model reference: [vendor/github.com/Azure/azure-sdk-for-go/services/postgresql/mgmt/2020-01-01/postgresql/models.go](https://github.com/terraform-providers/terraform-provider-azurerm/blob/db74aaf220696d6ef3daa7bdf517a2325e7019d4/vendor/github.com/Azure/azure-sdk-for-go/services/postgresql/mgmt/2020-01-01/postgresql/models.go#L1271-L1274)

**Comment by sigv** [comment]
I take the comments back, considering the previously linked issues - upstream MS issue was opened as result of previous (rejected/closed) Pull Request, which just had the conclusion that this should be fixed upstream.
