### ISSUE TITLE
Support for tagging resources created under azurerm_kubernetes_cluster (e.g load balancer, disks, IP addresses)

### ISSUE THREAD

**Issue by yaronya** [terraform-providers/terraform-provider-azurerm#8754]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When creating an `azurerm_kubernetes_cluster` resource there is an auto-generated `MC_` prefixed resource group that is being created for the node pool of the kubernetes cluster. That resource group includes the VMSS, Public IP Addresses, Disks and a Load Balancer.
It seems like there is no way to tag those resources (besides VMSS via tha `default_node_pool.tags`) while Azure does have tag support for those resources.
It'd be great if there would be a way to define those tags via terraform. For example, for the load balancer we can add a `tags` attribute under the `load_balancer_profile` block 💡 

### New or Affected Resource(s)

* azurerm_kubernetes_cluster

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  version = "~>2.0"
  features {}
}

resource "azurerm_resource_group" "rg1" {
  name     = "rg1"
  location = "northeurope"
}

resource "azurerm_kubernetes_cluster" "k8s" {
  name                = "aks1"
  location            = azurerm_resource_group.rg1.location
  resource_group_name = azurerm_resource_group.rg1.name
  dns_prefix          = "aks1"

  service_principal {
    client_id     = "XXXXX"
    client_secret = "YYYYY"
  }

  default_node_pool {
    name       = "pool"
    node_count = 2
    vm_size    = "Standard_D2_v2"
    tags = {
       "test" = "one"
     }
  }

  network_profile {
    load_balancer_sku = "Standard"
    network_plugin    = "kubenet"
  }

  tags = {
    "test" = "two"
  }
}
```

**Comment by local-master** [comment]
Also tag the Route Table and NSG created along with the AKS using terraform. This blocks deployment when there is Azure Policy that requires resources to be tagged.

**Comment by tombuildsstuff** [comment]
hi @yaronya @local-master 

Thanks for opening this issue.

The specific resources provisioned by AKS are implementation details of that service and subject to change at any time - notably these fields aren't exposed through the AKS (Resource Manager) API (which would give some guarantee to these resources being available). Whilst it's possible to go through and manage these resources once they've been created - unfortunately they're an implementation detail and thus can change at any time, what this means is that we intentionally don't expose these resources because we can't guarantee they'll exist.

As the AKS API controls the provisioning/lifetime of these resources and doesn't expose a means of setting the Tags (or many other configuration options) for these nested resources - unfortunately we're unable to manage these (or even expose this information, since the options could differ between AKS Clusters, as is the case for many other options within AKS). One option would be to [open an issue on the AKS Repository](https://github.com/Azure/AKS/issues) requesting that the AKS Team consider exposing this information (at which point there's more of a long-term guarantee this won't be replaced and we can look to expose it) and/or configure tags for these resources via the AKS API (which'll solve this creation issue).

It's worth noting that the AKS API itself internally uses the open-source project AKS Engine to generate an ARM Template for the deployment of these resources. Whilst it won't help you if you want to take advantage of the managed control plane, this should allow you to provision the same type of cluster with the same kind of functionality (to the best of my knowledge) as the AKS Service itself, albeit you'd be managing the control plane not Microsoft. Whilst that's quite a trade-off, that would allow you to customise the ARM Template (or provision/manage these resources in Terraform) - which is an alternative to waiting for Microsoft to support managing these through the API.

Unfortunately since this isn't possible at this time (for the reasons defined above) I'm going to close this issue for the moment, but hopefully that should help both long-term (via adding this functionality to the AKS API, so these can be set at creation time) and short-term (to provision a Kubernetes Cluster via AKS Engine).

Thanks!
