### ISSUE TITLE
invalid or unknown key on terraform script

### ISSUE THREAD

**Issue by Vj1422github** [terraform-providers/terraform-provider-azurerm#8755]
Error: azurerm_virtual_machine_extension.enable-routes: "virtual_machine_id": required field is not set

Error: azurerm_virtual_machine_extension.enable-routes: : invalid or unknown key: location

Error: azurerm_virtual_machine_extension.enable-routes: : invalid or unknown key: resource_group_name

Error: azurerm_virtual_machine_extension.enable-routes: : invalid or unknown key: virtual_machine_name

**Comment by tombuildsstuff** [comment]
hi @Vj1422github 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
