### ISSUE TITLE
VMSS fails when using the extension property

### ISSUE THREAD

**Issue by PleaseStopAsking** [terraform-providers/terraform-provider-azurerm#876]
### Affected Resource(s)
 - azurerm_virtual_machine_scale_set

### Terraform Configuration Files
```hcl
resource "azurerm_virtual_machine_scale_set" "ServerScaleSet" {
    name = "${var.customerProject}${var.environment}${var.machineAcronyms["Server"]}"
    location = "${var.location}"
    resource_group_name = "${azurerm_resource_group.rg.name}"
    upgrade_policy_mode	= "Manual"

    sku {
        name = "${var.Server_Specs["ServerType"]}"
    	tier = "Standard"
    	capacity = 1
    }

    storage_profile_image_reference {
        publisher = "${var.Server_Specs["Image_Publisher"]}"
        offer = "${var.Server_Specs["Image_Offer"]}"
	sku = "${var.Server_Specs["Image_sku"]}"
	version = "${var.Server_Specs["Image_Version"]}"
    }

    plan {
	name = "${var.Server_Specs["Plan_Name"]}"
	publisher = "${var.Server_Specs["Plan_Publisher"]}"
	product = "${var.Server_Specs["Plan_Product"]}"
    }

    storage_profile_os_disk {
	name = ""
	managed_disk_type = "${var.Server_Specs["OS_Disk_Type"]}"
	caching = "${var.Server_Specs["OS_Disk_Caching"]}"
	create_option = "${var.Server_Specs["OS_Disk_Create_option"]}"
    }

    storage_profile_data_disk {
	managed_disk_type = "${var.Server_Specs["Data_Disk_Type"]}"
	caching = "${var.Server_Specs["Data_Disk_Caching"]}"
	create_option = "${var.Server_Specs["Data_Disk_Create_Option"]}"
	disk_size_gb = "${var.Server_Specs["Data_Disk_Disk_Size"]}"
	lun = "${var.Server_Specs["Data_Disk_Disk_Lun"]}"
    }

    os_profile {
	computer_name_prefix = "${var.customerProject}${var.environment}${var.machineAcronyms["Server"]}"
	admin_username = "${var.EmcsAdminCredentials["Username"]}"
	admin_password = "${var.EmcsAdminCredentials["Password"]}"
    }

    os_profile_windows_config {
	provision_vm_agent  = "true"
    }

    network_profile {
	name = "${var.customerProject}${var.environment}${var.machineAcronyms["Server"]}"
	primary = true

	ip_configuration {
	    name = "${var.customerProject}${var.environment}${var.machineAcronyms["Server"]}"
	    subnet_id   = "${azurerm_subnet.PrivateSubnet.id}"
	}
    }
    
    extension {
        name = "LogAnalytics"
	publisher = "Microsoft.EnterpriseCloud.Monitoring"
	type = "MicrosoftMonitoringAgent"
	type_handler_version = "${var.log_analytics_extension}"
	auto_upgrade_minor_version = true
	settings = <<SETTINGS
	{
	    "workspaceId": "${var.azureCredentials["omsWorkspaceId"]}"
	}
	SETTINGS
	protected_settings = <<PROTECTED_SETTINGS
	{
	    "workspaceKey": "${var.azureCredentials["omsWorkspaceKey"]}"
	}
	PROTECTED_SETTINGS
	}
    }
```

### Expected Behavior
The scale set should deploy successfully

### Actual Behavior
It fails with the following message.
```
Error: Error applying plan:

1 error(s) occurred:

* azurerm_virtual_machine_scale_set.ServerScaleSet: 1 error(s) occurred:

* azurerm_virtual_machine_scale_set.ServerScaleSet: Long running operation terminated with status 'Failed': Code="NetworkingInternalOperationError" Message="Unknown network allocation error."
```

### Important Factoids
I tested both the Log Analytics and DSC extensions with the same behavior. If I remove the extension without changing anything else, it works with no issues.

The error message indicates that a long running operation terminated when in reality, it fails with 60 seconds of starting the vmss deployment.

**Comment by tombuildsstuff** [comment]
hey @PleaseStopAsking 

Thanks for opening this issue

To give some context to the error message, the "Long Running Operation" mentioned in the message is any operation in Azure that isn't synchronous (which is most operations). The issue you've described  is unfortunately an issue with the running/configuration of the VM Extension - and not something specific to Terraform - as such you'll need to dig into the debug logs on the machine (I believe they're in `C:\WindowsAzure\` on Windows and `/var/lib/waagent` on Linux) to find out more information about this error.

Unfortunately the VM Extensions in Azure are inconsistent, with some being case sensitive for the keys, and others being case insensitive (whilst others care about a valid exit code, and others don't). As such, I believe you'll find more information about the issue you're seeing in the logs on the machine - and given this isn't an issue with Terraform I'm going to close this issue for the moment. Apologies that we can't be more help, but since this is an issue with Azure - Microsoft Support may be the best point of contact for more information.

Thanks!

**Comment by PleaseStopAsking** [comment]
Hi @tombuildsstuff 

Can you elaborate on why this is an issue with Azure and not Terraform. The same extensions work with no issues if I deploy them using azurerm_virtual_machine_extension or via an ARM template. The only common factor in the failure is they are both failing through the scale set. When I say they are failing through the scale set, the actual scale set is failing, not just the extensions.

While I do agree that machine logs are usually the best option for troubleshooting these extensions (DSC & Log Analytics), the machines are never created for me to check because the entire scale set fails. This is why I believe this is an issue with Terraform and not Azure.

Thanks,

**Comment by sampcoug** [comment]
Hello,

Is it possible to use 'azurerm_virtual_machine_extension' with 'azurerm_virtual_machine_scale_set'? If it is, then how do the "name" and "virtual_machine_name" get defined because in 'azurerm_virtual_machine_scale_set' we do directly pass the machine name or the virtual machine name? 

`resource "azurerm_virtual_machine_extension" "test" {
  name                 = "hostname"
  location             = "${azurerm_resource_group.test.location}"
  resource_group_name  = "${azurerm_resource_group.test.name}"
  virtual_machine_name = "${azurerm_virtual_machine.test.name}"
  publisher            = "Microsoft.Azure.Extensions"
  type                 = "CustomScript"
  type_handler_version = "2.0"

  settings = <<SETTINGS
    {
        "commandToExecute": "hostname && uptime"
    }
SETTINGS

  tags {
    environment = "Production"
  }
}`

Any idea folks?

**Comment by tombuildsstuff** [comment]
hi @sampcoug 

> Is it possible to use 'azurerm_virtual_machine_extension' with 'azurerm_virtual_machine_scale_set'?

No - this is specifically for use with Virtual Machines and not Virtual Machine Scale Sets - where the extension can be configured within the VMSS resource itself. Please take a look [at the documentation](https://www.terraform.io/docs/providers/azurerm/r/virtual_machine_scale_set.html) for more information.

Since this issue is over a year old - I'm going to lock this issue for the moment.

Thanks!
