### ISSUE TITLE
Incorrect output displayed for managed disk name

### ISSUE THREAD

**Issue by harshagv** [terraform-providers/terraform-provider-azurerm#8760]
**Issue: Running `terraform refresh` after `terraform apply` displays incorrect output for managed disk name**

### Terraform (and AzureRM Provider) Version
```
- random v2.3.0
- template v2.1.2
- azurerm v2.26.0
- terraform v0.13.2
```

### Affected Resource(s)
`azurerm_managed_disk.generic_purpose_mgd_disk.*.name`

### Terraform Configuration Files
```hcl
provider "azurerm" {
  version = "~>2.0"
  features {}
}

data "azurerm_resource_group" "azresgroup" {
  name = var.az_res_group
}

data "azurerm_subnet" "azsubnet" {
  name = var.az_subnet
  virtual_network_name = var.az_virtual_nw_name
  resource_group_name  = var.az_res_group
}

data "azurerm_network_security_group" "nsg_name" {
  name = var.az_nsg_name
  resource_group_name = var.az_res_group
}

data "template_file" "vm_init_script" {
  template = file("../scripts/initialize_setup.sh")
}

resource "random_string" "randomId" {
  length = 4
  upper = false
  number = true
  lower = false
  special = false
}

resource "random_string" "vm-name" {
  length = 5
  upper = false
  number = false
  lower = true
  special = false
}

resource "azurerm_public_ip" "generic_purpose_public_ip" {
  name = "${var.az_vm_name}${var.az_public_ip_name}${random_string.randomId.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  allocation_method = "Dynamic"

  tags = {
    vmname = var.az_vm_name,
    owner = "gvhcicd"
  }
}

resource "azurerm_network_interface" "nw_interface_name" {
  name = "${var.az_vm_name}${var.az_nw_interface_name}${random_string.vm-name.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  ip_configuration {
    name = "${var.az_ip_configuration}${random_string.vm-name.result}"
    subnet_id = data.azurerm_subnet.azsubnet.id
    private_ip_address_allocation = "Dynamic"
    public_ip_address_id = azurerm_public_ip.generic_purpose_public_ip.id
  }

  tags = {
    vmname = var.az_vm_name,
    owner = "gvhcicd"
  }
}

resource "azurerm_network_interface_security_group_association" "nw_interface_nsg_assoc" {
  network_interface_id = azurerm_network_interface.nw_interface_name.id
  network_security_group_id = data.azurerm_network_security_group.nsg_name.id
}

resource "azurerm_managed_disk" "generic_purpose_mgd_disk" {
  count = var.attach_managed_disk ? 1 : 0
  name = "${var.az_vm_name}${var.az_managed_disk_name}${random_string.vm-name.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  storage_account_type = var.az_storage_acc_type
  create_option = "Empty"
  disk_size_gb = var.az_managed_disk_size

  tags = {
    vmname = var.az_vm_name,
    owner = "gvhcicd"
  }
}

resource "azurerm_linux_virtual_machine" "generic-purpose-vm" {
  name = "${var.az_vm_name}${random_string.vm-name.result}"
  location = var.az_location
  resource_group_name = var.az_res_group
  size = var.az_vm_size
  network_interface_ids = [ azurerm_network_interface.nw_interface_name.id ]
  admin_username = var.az_vm_admin_user_name
  computer_name = "${var.az_vm_name}${random_string.vm-name.result}"
  disable_password_authentication = true
  custom_data = base64encode(data.template_file.vm_init_script.rendered)

  admin_ssh_key {
    username = var.az_vm_admin_user_name
    public_key = file("../scripts/ssh-key-azure.pub")
  }

  os_disk {
    name = "${var.az_vm_name}${var.az_os_disk_name}${random_string.randomId.result}${random_string.randomId.result}"
    caching = "ReadWrite"
    storage_account_type = var.az_storage_acc_type
    disk_size_gb = var.az_os_disk_size
  }

  source_image_reference {
    publisher = "Canonical"
    offer = "UbuntuServer"
    sku = "18.04-LTS"
    version = "latest"
  }

  tags = {
    vmname = var.az_vm_name,
    owner = "gvhcicd"
  }
}

resource "azurerm_virtual_machine_data_disk_attachment" "attach_managed_disk" {
  count = var.attach_managed_disk ? 1 : 0
  managed_disk_id = azurerm_managed_disk.generic_purpose_mgd_disk[count.index].id
  virtual_machine_id = azurerm_linux_virtual_machine.generic-purpose-vm.id
  lun = "10"
  caching = "ReadWrite"
}

variable "az_managed_disk_name" {
  description = "Azure VM Managed Disk name"
  type = string
  default = "-vm-DataDisk"
}

variable "az_vm_name" {
  description = "Azure VM name"
  type = string
  default = "acatus"
}

variable "attach_managed_disk" {
  description = "Flag to check if managed data disk to be created"
  type = string
  default = "true"
}

output "generic-purpose-vm-name" {
  value = azurerm_linux_virtual_machine.generic-purpose-vm.name
}

output "generic-purpose-managed-disk-name" {
  value = azurerm_managed_disk.generic_purpose_mgd_disk.*.name
}
```

### Expected Behavior
The managed disk name should be displayed with an empty list
```
Outputs:

generic-purpose-managed-disk-name = []
generic-purpose-vm-name = gvh-vid
```

### Actual Behavior
The managed disk name is actually displayed with the value of the variable name set in variables.tf

```
Outputs:

generic-purpose-managed-disk-name = [
  "gvh-vm-DataDisksjeai",
]
generic-purpose-vm-name = gvh-vid
```

### Steps to Reproduce
```bash
$ az login
$ az account set -s <id>
$ export TF_VAR_attach_managed_disk=false
$ terraform init
$ terraform plan
$ terraform apply -input=false -auto-approve
$ terraform refresh   # running this is as a workaround for https://github.com/terraform-providers/terraform-provider-azurerm/issues/8445
```

### References
https://www.terraform.io/docs/providers/azurerm/r/virtual_machine.html
https://www.terraform.io/docs/providers/azurerm/r/managed_disk.html

![#1589F0](https://via.placeholder.com/15/1589F0/000000?text=+)`#1589F0`

**Comment by ArcturusZhang** [comment]
Hi @harshagv thanks for this issue!

Curious that I could not reproduce this issue - I am using exactly the same config you posted here, adding some variables and giving them default values. As for the data sources I just created some empty resources. Here is the result I am getting:
![image](https://user-images.githubusercontent.com/10554446/95650781-46360c80-0b18-11eb-8880-8c7bed5238ea.png)
which should be the same as you are expecting.
I also added a n output "how-many-disk" as the following:
```
output "how-many-disk" {
  value = length(azurerm_managed_disk.generic_purpose_mgd_disk)
}
```
And I have to ask, have you ever applied with `attach_managed_disk=true` and now updated to `attach_managed_disk=false`? At least it works fine if I get started from an empty resource group with `attach_managed_disk=false`.

**Comment by harshagv** [comment]
Hello @ArcturusZhang,

The issue does not occur after running `terraform apply` but rather when we run `terraform refresh` as mentioned in Steps to Reproduce.

**Comment by ArcturusZhang** [comment]
Hi @harshagv I have been following your steps to reproduce and it gives me the same result as above.

I am not sure if there is any difference between directly setting a variable value in the config or setting it using env variables, also I am not sure if the `-input=false` flag matters. Therefore could you please reduce the aspects here for example just hard code the variable value of `attach_managed_disk` to `false` by assigning a default value to it, and also remove the `-input=false` flag, since you should already have all of your variables with proper values.

**Comment by harshagv** [comment]
@ArcturusZhang,
Yes, this issue is reproducible only with setting the variable default value to `true` in .tf script and when the user forcibly set to this variable value to `false` using an environment variable `TF_VAR_attach_managed_disk=false` before running `terraform apply` and `terraform refresh`. But this is still a valid case and needs to be fixed right?

**Comment by ArcturusZhang** [comment]
Thanks for the update @harshagv 
And I just had another test - using `-var attach_managed_disk=false` instead of the environment variables and it is working fine. I will have another try on the environment variable approach very soon

**Comment by ArcturusZhang** [comment]
Hi @harshagv still I did not reproduce this but confirmed the environment variable works fine to assign value to variables in config.

Given that you should have been applied with `attach_managed_disk=true`, to get your expected result, you must have done one step of apply with `attach_managed_disk=false` and get the result of the destruction of the managed disk. Could you please double check have you applied with `attach_managed_disk=false` and confirmed the managed disk in your state file has disappeared before you run refresh? Please note that terraform refresh will not change your infrastructure

**Comment by ArcturusZhang** [comment]
Hi @harshagv that reminds me. I am using terraform v0.12.29. Let me switch to 0.13.2 and have another try.

I started with an *empty* resource group with a vnet, subnet and nsg (to provide the data sources), then I run the following commands (I am using powershell but it should the same command as yours):
- `$env:TF_VAR_attach_managed_disk="false"`
- `terraform init`
- `terraform plan` (shows no managed disk will be created)
- `terraform apply -input=false -auto-approve` (no managed disk is created, and output with empty managed disk names)
- `terraform refresh` (output empty managed disk names)

Then I started with an *empty* resource group with a vnet, subnet and nsg, then I run the following commands:
- `terraform init`
- `$env:TF_VAR_attach_managed_disk=""` (now `attach_managed_disk=true`)
-  `terraform apply -input=false -auto-approve` (managed disk created)
- `$env:TF_VAR_attach_managed_disk="false"`
- `terraform plan` (shows managed disk will be destroyed)
- `terraform apply -input=false -auto-approve` (managed disk is destroyed, and output with empty managed disk names)
- `terraform refresh` (output empty managed disk names)

Either way, I still cannot reproduce this. Is there anything else I am missing?
Also, this issue does not look like an issue with provider, if you could confirm that the state file is correct (does not have the managed disk after apply with `attach_managed_disk=false`), it looks more like an issue with the output part which belongs to terraform itself. Could you please double confirm that after the apply with `attach_managed_disk=false`, there is no managed disk in your state? If so, I assume maybe I should categorize this as `upstream-terraform`

My config is the same as yours except the variables and also since I do not have a ssh_key, I switch your vm config to password, other than these two differences, exactly the same as yours including the tags. Variables I am using:
```
variable "az_res_group" {
    default = "arczhang-8760"
}

variable "az_location" {
    default = "westus2"
}

variable "az_virtual_nw_name" {
    default = "arczhang-vnet"
}

variable "az_subnet" {
    default = "internal"
}

variable "az_nsg_name" {
    default = "arczhang-nsg"
}

variable "az_vm_name" {
  default = "vm"
}

variable "az_ip_configuration" {
  default = "ipcon"
}

variable "attach_managed_disk" {
  default = true
}

variable "az_vm_admin_user_name" {
  default = "azadmin"
}

variable "az_managed_disk_size" {
  default = 30
}

variable "az_public_ip_name" {
  default = "pip"
}

variable "az_managed_disk_name" {
  default = "disk000"
}

variable "az_storage_acc_type" {
  default = "Standard_LRS"
}

variable "az_nw_interface_name" {
  default = "arczhang-nic"
}

variable "az_vm_size" {
  default = "Standard_F1"
}

variable "az_os_disk_name" {
  default = "osdisk"
}

variable "az_os_disk_size" {
  default = 30
}
```

**Comment by harshagv** [comment]
@ArcturusZhang It seems that not sure what changed but I could not reproduce this issue again and you could mark it as closed. Thank you.

**Comment by ArcturusZhang** [comment]
Thanks @harshagv , glad to help
