### ISSUE TITLE
Mismatch between schema output and documentation for azurerm_api_management policy attribute

### ISSUE THREAD

**Issue by borys86** [terraform-providers/terraform-provider-azurerm#8793]
Dear team

I am working on automation tool that helps users to streamline terraform use on enterprise level. For this I need to to show some metadata of available resources to an end user like what is an input type. 

For programmatical access I used `terraform providers schema` command to output **azurerm** provider schema in json file format.
I used **2.29.0** provider version for that.

After an attempt to comprehend output with documentation and resolve some issues I ended up with one specific case that did make a lot of sense.

for the resource `azurerm_api_management` output shows **policy as attribute** but in the documentation that can be found here https://www.terraform.io/docs/providers/azurerm/r/api_management.html policy is **listed as block.**. In the schema output policy is also set to be computed value which implies that this is actually an output.

```json
 "policy": {
                "type": [
                    "list",
                    [
                        "object",


                        {
                            "xml_content": "string",
                            "xml_link": "string"
                        }
                    ]
                ],
                "optional": true,
                "computed": true
            }
```

Could you please advise if this is the issue with documentation or something is wrong with schema output and how this could be mitigated.

**Comment by yupwei68** [comment]
Hi @borys86 , thanks for opening this issue. 

On fact, "policy" is a block, it's a computed optional block, which means that it'll be assigned a default value by the service. 

Since it's computed, terraform could not detect the change once we want to remove the block to remove the "policy". Then we add a `SchemaConfigModeAttr` attribute to "policy", which means you could remove the "policy" block by the following configuration:
```
{
  ...
  policy = []
 ...
}
```
I hope I have explained your confusion.

**Comment by borys86** [comment]
hi @yupwei68 
Thank you for your reply. Very much appreciated. I am not completely sure I fully comprehend your explanation, but is it not a violation of a schema to assign an attribute `SchemaConfigModeAttr  `to a block, could it be that is something internal to terraform that marking a block with `SchemaConfigModeAttr  `makes it appear to be an attribute in schema?

Again, I am just looking into a way to programmatically resolve this issue without a need to have a whole set of special exception cases to handle situation in code to  "is `azurerm_api_management `resource then treat policy as a block".

I guess terraform schema is here to stay, is there other ways to solve your issue but keep schema aligned with actual state?

**Comment by tombuildsstuff** [comment]
hi @borys86 

Thanks for opening this issue.

The `terraform providers schema` command is unfortunately part of Terraform Core and so whilst this does call into the Provider unfortunately we're unable to comment on the specifics here, since it's outside the scope of this provider. Instead I'm going to redirect you to [the community forum](https://discuss.hashicorp.com/c/terraform-core/27) where someone from the Core/Plugin SDK team should be able to assist you further.

Thanks!
