### ISSUE TITLE
Unable to reference any attributes for data.azurerm_app_service_environment

### ISSUE THREAD

**Issue by anuradhaarao** [terraform-providers/terraform-provider-azurerm#8842]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.12.3
+ provider.azurerm v2.14.0

### Affected Resource(s)

* `data.azurerm_app_service_environment`

### Terraform Configuration Files

```hcl
data "azurerm_app_service_environment" "test-ase" {
  name                = "xxx-app-service-environment"
  resource_group_name = "xxx"
}

output "ase-property" {
  value = data.azurerm_app_service_environment.test-ase.internal_ip_address
}

```

### Expected Behavior

Should have referenced the outbound ip address

### Actual Behavior

Error: Unsupported attribute

  on cosmosdbtest.tf line 185, in output "ase-property":
 185:   value = data.azurerm_app_service_environment.test-ase.internal_ip_address

This object has no argument, nested block, or exported attribute named
"internal_ip_address".

### Steps to Reproduce

1. `terraform plan`

### Important Factoids

In this instance, I am just trying to reference an ASE that already exists in the environment. So the resource attributes must be retrievable.

### References

* #0000

**Comment by neil-yechenwei** [comment]
Thanks for opening this issue. After checked, seems the [azurerm provider 2.14](https://github.com/terraform-providers/terraform-provider-azurerm/blob/v2.14.0/azurerm/internal/services/web/app_service_environment_data_source.go) you are using doesn't include this property. Suggest to use[ latest version 2.35.0](https://github.com/terraform-providers/terraform-provider-azurerm/blob/2f5ef7b540ad107de0bf0423346ea105ee6e7377/azurerm/internal/services/web/app_service_environment_data_source.go#L39) since it includes this property. Thanks.
