### ISSUE TITLE
azurerm_availability_set behaves inconsistently inside a module with 'count' applied on it

### ISSUE THREAD

**Issue by ak58588** [terraform-providers/terraform-provider-azurerm#8843]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
terraform  v0.13.4
azurerm v2.30.0

### Affected Resource(s)

* `azurerm_availability_set`
* `azurerm_windows_virtual_machine`

### Terraform Configuration Files

Hello,

We are using our root module, which has a count parameter and contains resources as well as other module references inside. 
Generally, this module creates a VM (or several VMs) along with some required infrastructure and adds them to an availability set. The count parameter in the root module regulates the number of VMs to be created. The names of VMs depend on the 'count', while the name of the availability set is a constant string. 

During the initial terraform apply (no matter how high the 'count' value is), the needed number of VMs will be created and added to an availability set. Actually, the terraform state contains two resources, but they have the same Azure ID, so as an output there is one availability set containing several VMs in the end. 

Then we want to increase the 'count' and run the terraform apply again. This time, we are getting an error, saying that the availability set with this ID already exists. 

Thank you very much for your help

main.tf root file
```hcl
module "windows_server" {
  count                 = 2
  source                = <some-source>
  ...
  ...
}
```
main.tf of the module, containing the VM resource: 
```
resource "azurerm_windows_virtual_machine" "virtual_machine" {
    name                  = "SomeString_${count.index + 1}"
    location              = <region>
    resource_group_name   = <rg_name>
    network_interface_ids = [module.network_interface.nic_id]
    size                  = <vm_size>
    admin_username        = <username>
    admin_password        = <password>
    computer_name         = <comp_name>
    availability_set_id   = module.availability_set.availability_set_id

    source_image_reference {
        ...
    }

    os_disk {
        ...
    }

    boot_diagnostics {
        ...
    }

   tags = {
        ...
    }
}
```
finally, the main.tf file of the module with the availability set itself: 
```
resource "azurerm_availability_set" "availab_set" {
  name                         = "ConstantString" 
  location                     = <location>
  resource_group_name          = <rg_name>
  platform_fault_domain_count  = var.fault_domain_count
  platform_update_domain_count = var.update_domain_count
  managed                      = true
}
```

### Expected Behavior
We would expect that terraform acts similarly to the initial deployment (`terraform apply`) and adds the newly created VM to the existent availability set. 

### Actual Behavior
Terraform throws an error saying that the resource already exists.

### Steps to Reproduce

1. Set the count in the initial module to some value - 1 or 2, for example
2. `terraform apply`
3. increase the value of 'count' (for example to 3)
4. `terraform apply`

* #0000

**Comment by tombuildsstuff** [comment]
hi @ak58588 

Thanks for opening this issue.

Taking a look at the Terraform Configuration above, the name for the Availability Set needs to be unique within the resource group, however only a single Availibility Set is being created:

> resource "azurerm_availability_set" "availab_set" {
>   name                         = "ConstantString" 

As such you should be able to work around this by adding a unique identifier to each Availability Set as is being done when provisioning the Windows VM's:

> resource "azurerm_windows_virtual_machine" "virtual_machine" {
>     name                  = "SomeString_${count.index + 1}"

As such updating the Terraform Configuration should be all that's needed here. From Terraform's perspective we lookup resources before creating them to ensure we don't unintentionally "adopt" resources - since this can be unintentional (as in this instance) - requiring that they're imported if users want to use an existing resource.

However if you're looking to create a single Availability Set and use this for all of the Windows VM's, you'll need to use the Daa Source to look this up (or pass its ID into the module).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). Ultimately since this is a question regarding Terraform Configuration rather than a bugin the Azure Provider I'm going to close this for the moment - but if that doesn't work for you then I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by ak58588** [comment]
Thanks a lot, @tombuildsstuff, for your reply! 
Still, when I create several instances of a module, containing the resource, hence, several instances of resources, their terraform addresses differ, but IDs are the same:  
```
module.[0].av_set.azurerm_availability_set.availab_set.id = module.[1].av_set.azurerm_availability_set.availab_set.id 
```
During the first, initial ```terraform apply ``` it works fine. Is there something behind it?
