### ISSUE TITLE
azurerm_frontdoor: frontend endpoints should be added as a separate resource

### ISSUE THREAD

**Issue by sonersari** [terraform-providers/terraform-provider-azurerm#8848]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There is no way to add `frontend_endpoints` after terraform is created. But it is currently needed for configuring frontdoor with apex domain. If you want to configure the frontdoor with apex domain you need to create frontdoor first then you should add a dns record after that you need to add your custom domains to the frontdoor service. But you can't do it with terraform because the `frontend_endpoints` can be only added on frontdoor resource's creation. 

It should be added separately like `azurerm_frontdoor_custom_https_configuration`  

### Potential Terraform Configuration

```
resource "azurerm_frontdoor_frontend_endpoint" "custom_endpoint" 
{
    name         = "exampleFrontendEndpoint1"
    host_name    = "example-custom-domain"
   
    custom_https_configuration {}
}
```

### Affected Resource(s)

* `azurerm_frontdoor`

### New Resource(s)

* `azurerm_frontdoor_frontend_endpoint`

### References

* #6781

**Comment by tombuildsstuff** [comment]
Cross-posting from #10514: this is blocked on support in the Azure API - once that's available we can take a look into this https://github.com/terraform-providers/terraform-provider-azurerm/issues/10514#issuecomment-776082109

**Comment by michaelelleby** [comment]
@sonersari Azure created a workaround for apex domains: You have to create a regular CNAME record in your DNS, mapping `afdverify.<yourdomain>` to `afdverify.<your front door name>.azurefd.net` and then you can deploy Azure Front Door with a frontendEndpoint listening on that apex domain.

**Comment by OmnipotentOwl** [comment]
Looking ahead would this be something that could be better supported under the new Azure Front Door Sku based resources that are managed under the CDN resource provider? Looking at the rest API documentation it does look like the frontends will be configurable individually instead of in a single API call for the entire frontdoor definition. https://docs.microsoft.com/en-us/rest/api/cdn/azurefrontdoorstandard/premium(preview)/afdendpoints and https://docs.microsoft.com/en-us/rest/api/cdn/azurefrontdoorstandard/premium(preview)/afdcustomdomains

As for the support under terraform it does look like the release 2.56.0 updated the azure sdk for go to a version that includes the new CDN management API calls for the new frontdoor version.

**Comment by WodansSon** [comment]
I am going to go ahead and close this issue as this is not possible with the current API, however as @OmnipotentOwl mentioned we will be beginning work on adopting the new Frontdoor X and CDN X API in the future where doing this would be possible. Thanks for opening this issue! 🚀
