### ISSUE TITLE
Storage configuration in Azure SQL VM provisioning

### ISSUE THREAD

**Issue by naveenchandani** [terraform-providers/terraform-provider-azurerm#8866]
I am trying to provision an Azure SQL VM and have to specify the disk for logs and transaction. Could you please share an example containing the configuration blocks.

**Comment by tombuildsstuff** [comment]
hi @naveenchandani 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
