### ISSUE TITLE
How can I declare an existing VNet using azurerm_dev_test_virtual_network 

### ISSUE THREAD

**Issue by CedSadowski** [terraform-providers/terraform-provider-azurerm#8885]
Hello everybody,

I've a question concerning Devtest lab ressources management under Azure with Terraform.
I have declare a resource azurerm_dev_test_lab like this : 

```
provider "azurerm" {
  features {
  }
  version = ">=2.0.0"
}

resource "azurerm_resource_group" "VNetResourceGroup" {
  name     = "VNet-ResourceGroup"
  location = "FranceCentral"
}

resource "azurerm_resource_group" "VMResourceGroup" {
  name     = "VM-ResourceGroup"
  location = "FranceCentral"
}

resource "azurerm_virtual_network" "VNet" {
  name                = "MyVnet"
  location            = azurerm_resource_group.VNetResourceGroup.location
  resource_group_name = azurerm_resource_group.VNetResourceGroup.name
  address_space       = ["10.0.0.0/16"]
}

resource "azurerm_dev_test_lab" "DevTestLab" {
  name                = "DevTestLab"
  location            = azurerm_resource_group.VMResourceGroup.location
  resource_group_name = azurerm_resource_group.VMResourceGroup.name
}
```

Now, I want to declare my existing VNet (aka MyVNet) as a dev_test_virtual_network but it seems that is not possible :-(
I can do it via Azure portal but not via Terraform ...
![Capture](https://user-images.githubusercontent.com/43379479/95974540-66661400-0e15-11eb-9867-acb1c82ca054.PNG)

Please could you help me and confirm or not this information ?

Regards.

Cédric

**Comment by tombuildsstuff** [comment]
hi @CedSadowski 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
