### ISSUE TITLE
Application Insights instance not being applied correctly to Azure Function

### ISSUE THREAD

**Issue by mgressman** [terraform-providers/terraform-provider-azurerm#8909]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Terraform v0.13.4
AzureRM v2.27.0

### Affected Resource(s)

azurerm_function_app

### Terraform Configuration Files

```hcl
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "2.27.0"
    }
  }
}

provider "azurerm" {
  features {}
}

locals {
  function_settings = {
    "APPINSIGHTS_INSTRUMENTATIONKEY"        = azurerm_application_insights.ai.instrumentation_key
  }
  location = "North Central US"
  name = "vHJvXcrFuRY6BPodpggRD2V9"
}

resource "azurerm_resource_group" "rg" {
  location = local.location
  name     = local.name
}

resource "azurerm_application_insights" "ai" {
  name                = local.name
  location            = local.location
  resource_group_name = azurerm_resource_group.rg.name
  application_type    = "web"
}

resource "azurerm_storage_account" "sa" {
  account_replication_type = "LRS"
  account_tier             = "Standard"
  location                 = local.location
  min_tls_version          = "TLS1_2"
  name                     = lower(local.name)
  resource_group_name      = azurerm_resource_group.rg.name
}

resource "azurerm_app_service_plan" "asp" {
  name                = local.name
  location            = local.location
  resource_group_name = azurerm_resource_group.rg.name
  kind                = "FunctionApp"

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

resource "azurerm_function_app" "function" {
  app_service_plan_id        = azurerm_app_service_plan.asp.id
  app_settings               = local.function_settings
  https_only                 = true
  location                   = local.location
  name                       = local.name
  resource_group_name        = azurerm_resource_group.rg.name
  storage_account_access_key = azurerm_storage_account.sa.primary_access_key
  storage_account_name       = azurerm_storage_account.sa.name
  version                    = "~3"
}
```

### Expected Behavior

The Application Insights resource that is created should be connected to the Azure Function.

### Actual Behavior

When navigating to the Settings/Configuration > Application Settings section of the newly created Azure Function in the Azure portal, there is an application setting with the name APPINSIGHTS_INSTRUMENTATIONKEY as expected. However, navigating to the Settings/Application Insights section of the newly created Azure Function, it shows that the Application Insights resource is actually not connected. A screen is presented where I am able to either create a new Application Insights resource, or select an existing one. The Application Insights instance that is created as a part of this Terraform project is shown in the list of available resources to select from, so I know that it was created correctly. I also verified that the APPINSIGHTS_INSTRUMENTATIONKEY is correct for the Application Insights instance that was created. The only way I can get data from the Azure Function to flow through to the Application Insights section is to go through the process of selecting the existing resource and then saving that configuration

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by ricohomewood** [comment]
This issue also applies to web apps too as there are two ways to connect App Insights to your Function App / Web App. Via Instrumentation key (which would require this library in code) or connection via the function / app service itself (which doesn't require a code change or redeploy of your app)

**Comment by mgressman** [comment]
This looks to be a fundamental Azure issue. There are two other open issues from two other sources that point to the same problem.

Can't do it from [Azure CLI](https://github.com/Azure/azure-cli/issues/15176).

Can't do it from the [Azure portal](https://docs.microsoft.com/en-us/answers/questions/131172/application-insights-not-connected-to-azure-functi.html).

Since it can't be done with the Azure CLI, and it can't even be done in the Azure portal, I am going to guess all methods will suffer the same issue until it is fundamentally fixed within the Azure ecosystem.

**Comment by tombuildsstuff** [comment]
hi @mgressman 

Thanks for opening this issue.

Application Insights is connected to other resources in a couple of ways, generally via a hidden tag (`"hidden-link:[appinsights-arm-resource-id]" = "Resource"`) and (in the case of App Service/Function Apps) using a connection string to pipe this data across. As such it's likely you need to add this tag to link the two resources here, which should be in the format:

>      - "hidden-link:/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/my-resource-group/providers/microsoft.insights/components/my-appinsights-instance" = "Resource" -> null

Unfortunately since this is the ID of the Application Insights instance - and the Tags are present on the Function App resource (at the top level) - referencing these using the Application Insights `id` attribute will introduce a circular reference (which isn't ideal..) - however these Resource ID's are predictable and so building this up should provide a suitable workaround here, for example:

> "${azurerm_resource_group.test.id}/providers/microsoft.insights/components/{var.application_insights_name}"

Which I believe should solve this for you - would you be able to take a look and see if that works for you?

Whilst we've requested a better means of integration for these resources (e.g. a separate API to connect the two - as it stands today this is the only means of doing so, albeit it's not particularly clear. We could introduce a separate resource to add this specific tag in a future version of the Azure Provider (and omit this tag from existing resources) - but we're trying to avoid that here, since that becomes more complicated than it first seems (each resource would need to pull the list of "omitted" tags and then re-introduce them to the top-level [e.g. App Service] resource on the fly) and ultimately would cause other issues (for example, requiring introducing locking on resources). As such whilst we appreciate this isn't ideal, unfortunately this doesn't appear to be a viable option at this time - meaning we're still waiting for another API from the Service Team here.

Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider - and this forum is intended to be used for feature enhancements and bugs in the Azure Provider - I'm going to close this issue for the moment. However if that hasn't solve this for you, then you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
