### ISSUE TITLE
Creation of workspace folder ?

### ISSUE THREAD

**Issue by BertrandDechoux** [terraform-providers/terraform-provider-azurerm#8914]
Hi,

I am wondering if workspace folders can be created with Terraform ?

I did not find much about this topic.

The [documentation of databricks_permissions](https://github.com/databrickslabs/terraform-provider-databricks/blob/master/docs/resources/permissions.md#folder-usage) describes how to manage the folder permission. But even there, the folder is not created. The folder is expected to already have been created. However, for all other permission examples (cluster, policy, pool and notebook), the test resource is created within the example.

Is it simply not yet supported ?

Regards

**Comment by tombuildsstuff** [comment]
hi @BertrandDechoux 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by BertrandDechoux** [comment]
It was the right usage. But I used the wrong repository. It was meant for Databricks Terraform provider.... Thanks for the quick feedback.
