### ISSUE TITLE
Support for adding Document to CosmosDb collections (azurerm_cosmosdb_sql_container)

### ISSUE THREAD

**Issue by massimolpc** [terraform-providers/terraform-provider-azurerm#8916]
Having a new Terraform resource to add Items/Documents to a CosmosDB collection, to provision base data, would be a great feature.
Similar as the “aws_dynamodb_table_item” resource for AWS.

**Comment by tombuildsstuff** [comment]
hi @massimolpc 

Thanks for opening this issue.

Unfortunately there's not enough information in this to be able to triage this - would you mind [reopening this issue and completing the issue template](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) so that we have all the information we need here?

Thanks!
