### ISSUE TITLE
AzureRM "azurerm_security_center_subscription_pricing" set multiple resource types

### ISSUE THREAD

**Issue by nikydobrev** [terraform-providers/terraform-provider-azurerm#8918]
As described in the following documentation https://www.terraform.io/docs/providers/azurerm/r/security_center_subscription_pricing.html 
"azurerm_security_center_subscription_pricing" can set only one resouce type: "AppServices ContainerRegistry KeyVaults KubernetesService SqlServers SqlServerVirtualMachines StorageAccounts VirtualMachines" 

Is there a way to set multiple resource types at the same time, e.g:

resource "azurerm_security_center_subscription_pricing" "azure_security_center_tier" {
  tier = "Standard"
  resource_type = "AppServices, KeyVaults, SqlServers"
}

 Thanks in advance!

**Comment by tombuildsstuff** [comment]
hi @nikydobrev 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
