### ISSUE TITLE
azurerm_lb_rule probe_id now invalid argument

### ISSUE THREAD

**Issue by Adampeterjones** [terraform-providers/terraform-provider-azurerm#8929]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* Terraform v0.13.4
* `azurerm_2.32.0`

azurerm_lb_rule
### Terraform Configuration Files

```hcl
resource "azurerm_lb_rule" "web_lb_rule" {
  resource_group_name            = azurerm_resource_group.rg.name
  loadbalancer_id                = azurerm_lb.web_lb.id
  name                           = "${azurerm_lb.web_lb.name}-Rule"
  probe_id                       = azurerm_lb_probe.web_probe.probe_id
  protocol                       = "Tcp"
  frontend_port                  = 80
  backend_port                   = 80
  frontend_ip_configuration_name = azurerm_lb.web_lb.frontend_ip_configuration[0].name
  backend_address_pool_id        = azurerm_lb_backend_address_pool.web_pool.id
  load_distribution              = "SourceIPProtocol"
}
```

### Expected Behavior

should have passed plan stage as probe_id is an optional requirement from the provider as specified by the syntax guide here:
[terraform syntax](https://www.terraform.io/docs/providers/azurerm/r/lb_rule.html)

### Actual Behavior

error returned as follows:
````
Error: Unsupported attribute

  on network.tf line 120, in resource "azurerm_lb_rule" "web_lb_rule":
 120:   probe_id                       = azurerm_lb_probe.web_probe.probe_id

This object has no argument, nested block, or exported attribute named
"probe_id".

````

Additionally,  if you remove the probe_id the rule builds successfully but doesnt show in the portal against the resource as Rules "Must have a probe associated with them"
### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @Adampeterjones 

Thanks for opening this issue.

Taking a look at the output from Terraform here:

```
Error: Unsupported attribute

  on network.tf line 120, in resource "azurerm_lb_rule" "web_lb_rule":
 120:   probe_id                       = azurerm_lb_probe.web_probe.probe_id

This object has no argument, nested block, or exported attribute named
"probe_id".
```

This is stating that the `azurerm_lb_probe` resource doesn't have an attribute/argument named `probe_id`, rather than the `azurerm_lb_rule` resource doesn't support this argument. As such it should be possible to fix this by updating this line to be:

```hcl
resource "azurerm_lb_rule" "web_lb_rule" {
  # ...
  probe_id = azurerm_lb_probe.web_probe.id
}
``` 

Which will return the ID of the Load Balancer Probe - which should allow this to work.

Since this is a question regarding the Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment, however should you have further questions then you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
