### ISSUE TITLE
Diagnostic Settings already exists - Error upon re creating resources

### ISSUE THREAD

**Issue by techadmin1982** [terraform-providers/terraform-provider-azurerm#8930]
Hello Good People of Hashicorp, 
I am designing some terraform files to create a Migration Landing Zone in Azure. I have experienced a strange behavior while redeploying these resources. It is my personal test subscription so I would copy and paste the error as is. I do not get this error upon running it for the first time on a fresh subscription. Then i remove the resources using terraform destroy. After that when i try to redeploy the resources again using terraform apply i get this error. Technically, this means Terraform may not be able to remove the resources completely or maybe this is an Azure limitation. 

In my case the "Error" is coming up for Diagnostic Settings on a Virtual network and Azure Firewall.

Note, the terraform files still run fine with the resources getting created perfectly. However this "Error" message is strange and should not appear. Please let me know any information you want , I would be glad to provide you. Thanks.
![Capture](https://user-images.githubusercontent.com/42249185/96369782-6d748580-1179-11eb-9e5c-c77dba705571.JPG)

**Comment by techadmin1982** [comment]
After some investigation i know what the problem is. I remember because of some issues i had to manually delete the resources (yes, without running terraform destroy). That caused all the trouble. I then removed the state files from storage account and also local state file. NEVER DO THIS in live environment. Anyways, i have fixed the problem after i cleansed the resources again with terraform destroy and tried recreating i did not get the problem.

**Comment by tombuildsstuff** [comment]
hi @techadmin1982 

Due to the behaviour of the Azure API (where it's possible to adopt existing resources, due to the API's being Upserts), the Azure Provider requires that existing resources are imported into the state, to avoid unintentionally overwriting unmanaged resources - as per the error message being returned here. As such, whilst you've solved this by deleting these resources, in future it should be possible to fix this by importing these existing resources as described in the error message.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
