### ISSUE TITLE
Managing restored disks

### ISSUE THREAD

**Issue by lukaszgolebiewski** [terraform-providers/terraform-provider-azurerm#8931]
By default, we use the standard backup mechanism for our VMs on Azure (https://docs.microsoft.com/en-us/azure/backup/backup-azure-vms-first-look-arm). Because of specific settings (e.g. networking) we would like to restore our machines with a replace option. Recently we did it for one of our linux vm. We succeeded but instead of having the same machine, we got the one with different disks attached.
Unfortunately, this is correct behavior of the replace option – confirmed with Microsoft. One would expect that all resources attached to VM should be restored to the given state with the same physical resources.
But, how to deal with such mechanism using Terraform? In a state file, which holds info of whole deployed infrastructure, we have initial discs attached and Terraform wants to rewind changes after restoring.

**Comment by tombuildsstuff** [comment]
hi @lukaszgolebiewski 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by waxb** [comment]
It would be nice to have a link to the discussion about this 'issue' for future reference.
