### ISSUE TITLE
Feature Request: AzureRM_Application_Gateway - SSL Policy

### ISSUE THREAD

**Issue by mb290** [terraform-providers/terraform-provider-azurerm#898]
Through PowerShell today you can create an SSL Policy on an application gateway. Ideally on the azurem_application_gateway module you should be able to specify an ssl_policy block as such:

```
ssl_policy {
	min_protocol_version = "TLSv1_2"
	cipher_suite = ["TLS_ECDHE_ECDSA_WITH_AES_128_GCM_SHA256", 
					"TLS_ECDHE_ECDSA_WITH_AES_256_GCM_SHA384", 
					"TLS_RSA_WITH_AES_128_GCM_SHA256",
	]
}
```

Here is the documentation from azure-docs [https://github.com/MicrosoftDocs/azure-docs/blob/master/articles/application-gateway/application-gateway-configure-ssl-policy-powershell.md]

**Comment by tombuildsstuff** [comment]
Hey @mb290 

Thanks for opening this issue :)

Support for this has previously been requested in #451 - as such I'm going to close this issue in favour of that one. Just to let you know that we've got a few enhancements we want to do for the Application Gateway resource - but we're actually waiting on [a critical bug to be fixed in the Application Gateway API](https://github.com/Azure/azure-rest-api-specs/issues/2187) before we extend this resource further - but we'll be sure to take a look when that's resolved.

Thanks!
