### ISSUE TITLE
tags in azurerm_backup_policy_vm are ... well ... useless

### ISSUE THREAD

**Issue by DenWin** [terraform-providers/terraform-provider-azurerm#8981]
I had setup azurerm_backup_policies to set tags, thought each time I re-run the configuration terraform claims, there are no tags and wants to add them.
Also there is no option to set a tag for Backup Policies in Azure anyway.

**Comment by tombuildsstuff** [comment]
hi @DenWin 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by DenWin** [comment]
@tombuildsstuff : This was not intended as a question! **It is a bug.**

Fact A) In Azure you are not able to set tags!
Fact B) Even if you set this manage resource up to set tags, they won't be acepted by Azure and thus will cause Terraform to ALWAYS "change" this resource, because it expects the tags to be there.
Also once you setup tags, they won't be
