### ISSUE TITLE
No Drift Detection When Removing availability_set_id From azurerm_virtual_machine

### ISSUE THREAD

**Issue by Bourne-ID** [terraform-providers/terraform-provider-azurerm#8987]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

$ terraform version
Terraform v0.12.29
+ provider.azurerm v2.32.0

### Affected Resource(s)

* `azurerm_virtual_machine`

### Terraform Configuration Files

Before: 
```hcl
resource "azurerm_virtual_machine" "first" {
  location              = var.region
  name                  = "${local.prefix}-first"
  network_interface_ids = [azurerm_network_interface.firstnic[0].id]
  resource_group_name   = azurerm_resource_group.masterrg.name
  vm_size               = "Standard_B2s"
  
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  availability_set_id = azurerm_availability_set.master.id

  storage_image_reference {
    publisher = var.node_definition.publisher
    offer     = var.node_definition.offer
    sku       = var.node_definition.sku
    version   = var.node_definition.version
  }

  storage_os_disk {
    name              = "${local.prefix}-0-os-disk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = var.node_definition.disk-type
  }
  os_profile {
    computer_name  = "${local.prefix}-0-vm"
    admin_username = var.node_definition.admin-username
  }
  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      path     = "/home/${var.node_definition.admin-username}/.ssh/authorized_keys"
      key_data = file(var.node_definition.ssh-keypath)
    }
  }
}
```

After:
```hcl
resource "azurerm_virtual_machine" "first" {
  location              = var.region
  name                  = "${local.prefix}-first"
  network_interface_ids = [azurerm_network_interface.firstnic[0].id]
  resource_group_name   = azurerm_resource_group.masterrg.name
  vm_size               = "Standard_B2s"
  
  delete_os_disk_on_termination    = true
  delete_data_disks_on_termination = true

  storage_image_reference {
    publisher = var.node_definition.publisher
    offer     = var.node_definition.offer
    sku       = var.node_definition.sku
    version   = var.node_definition.version
  }

  storage_os_disk {
    name              = "${local.prefix}-0-os-disk"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = var.node_definition.disk-type
  }
  os_profile {
    computer_name  = "${local.prefix}-0-vm"
    admin_username = var.node_definition.admin-username
  }
  os_profile_linux_config {
    disable_password_authentication = true
    ssh_keys {
      path     = "/home/${var.node_definition.admin-username}/.ssh/authorized_keys"
      key_data = file(var.node_definition.ssh-keypath)
    }
  }
}
```
### Debug Output
[will generate on request, should be easy to replicate]

### Expected Behavior

Terraform plan should have detected the drift when the AV set was removed from the VM - even if this is a Forces New Resource. 

### Actual Behavior

Terraform does not detect this drift, instead showing no difference. 
`No changes. Infrastructure is up-to-date.`

This is the same when removing the attribute, giving it Null or giving it blank ("")

### Steps to Reproduce

1.  Create a azurerm_virtual_machine with a VM inside an AVset
2. Run terraform apply, create the resource
3. Remove the availability_set_id definition, or set to blank/null
4. Rerun terraform plan/apply. This is where no drift is detected. 

### Important Factoids

I are aware there are updates to the azurerm_linux_virtual_machine however I still have a large number of 'legacy' VMs on the old definition, and drift detecting the AVSet (especially when removed) is required. 

When changing the AVset to another value, the drift is detected. My theory is https://github.com/terraform-providers/terraform-provider-azurerm/blob/2dc4b9efcabeb71900fdd7b64a78d6ee898b4909/azurerm/internal/services/compute/virtual_machine_resource.go#L106-L115 is the issue - the field is defined as Computed. As such when removing the AVset, it will compute the value from the resource. I need to build a custom version of the provider to confirm if this is correct. 

This also poses a question: When an azurerm_virtual_machine has been defined with an AV set - how does one remove the VM from the AVset through terraform (even if it needs to recreate) without resorting to a Taint?

**Comment by tombuildsstuff** [comment]
hi @Bourne-ID 

Thanks for opening this issue.

In this instance since this field is Optional and Computed (which is why removing this retains the value) - as such it should be possible to force this to an empty value by setting this field to an empty string, for example:

```hcl
resource "azurerm_virtual_machine" "test" {
  availability_set_id = ""
}
```

As you've mentioned, at this point in time the `azurerm_virtual_machine` resource has been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources - and whilst it continues to remain available it'll be deprecated in version 3.0 of the Azure Provider (but continue to be available in that release). Since these resources have been superseded (which is due to the behaviour of the Virtual Machine API's changing substantially since they were introduced) - unfortunately we have no plans to introduce changes to these resources to ensure they remain compatible for existing users - and recommend migrating over to the newer `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources where possible instead, which (from memory) don't have this issue.

Since these resources have been superseded here and our recommendation is to migrate over to the replacement resources (as we can't fix this without potentially breaking behaviour that other users are relying on) - I'm going to close this issue for the moment, but I believe that setting this to an empty string should work around this in the interim.

Thanks!

**Comment by Bourne-ID** [comment]
HI @tombuildsstuff - thanks for the detailed response.

I can confirm the new VM resource (at least the Linux one) does behave as expected when removing an AVset. Unfortunately setting 
```hcl 
resource "azurerm_virtual_machine" "test" {

availability_set_id = "" # previously defined
# or 
availability_set_id = null # previously defined
```

Both report with no drift if the resource was created with an AVSet defined. 

This is an edge case as the usual use case is to move or migrate to AVsets or Zones - as far as I'm aware there's no real benefit for moving away from AVsets. However the lack of drift detection is what tripped me up; it's one of the fundamental features of Terraform however I accept this resource has been superseded, and therefore migrating seems the correct option at this time.

**Comment by tombuildsstuff** [comment]
@Bourne-ID 

> Both report with no drift if the resource was created with an AVSet defined.

Apologies, I've just recalled [this bug in Terraform's Plugin SDK](https://github.com/hashicorp/terraform-plugin-sdk/issues/282) which means this won't work for string fields (but does for other types of fields) which is likely the root-cause of this.

Taking a look through at that, the Plugin SDK have opted to fix this in the next major version of the Plugin SDK (which requires larger changes) - so unfortunately that's not likely to happen anytime soon.

> This is an edge case as the usual use case is to move or migrate to AVsets or Zones - as far as I'm aware there's no real benefit for moving away from AVsets. However the lack of drift detection is what tripped me up; it's one of the fundamental features of Terraform however I accept this resource has been superseded, and therefore migrating seems the correct option at this time.

Definitely - Terraform should be able to track these resources, we use "Optional & Computed" fields to represent fields where these can be configured in multiple places (for example, Subnets can be configured within a Virtual Network, or using a separate resource) - they shouldn't (generally) be used for top-level fields, which is why this isn't Computed in the replacement resources.

If these resources weren't feature-frozen we'd look to remove "Computed" from these resources which should fix this (with presumably some other minor changes necessary) - however since these resources map some older scenarios (unmanaged disks and the older encryption approach) which we don't (currently) plan to migrate to the new resources (since these have been superseded on the Azure's side), we're less likely to break existing scenarios if this resource remains feature-frozen at this time.

Ultimately we want to avoid forcing folks over to the new resources / having to rework working functionality - since these resources still work for older scenarios - so whilst we will be deprecating the older VM/VMSS resources in 3.0, they'll continue to remain available for the foreseeable future, so that users can migrate across as systems are upgraded (rather than being forced over).

As such, apologies there's no other workaround here - but I'm glad to hear this is working for you in the new resources 👍
