### ISSUE TITLE
Custom Data is not created

### ISSUE THREAD

**Issue by k7faq** [terraform-providers/terraform-provider-azurerm#9013]
When attempting to create a "custom_data" aka Cloud Init script the AzureRM provider is failing to create it. Following is the example code block and the resulting output.

```
resource "azurerm_linux_virtual_machine_scale_set" "dockervmss" {
  # https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine_scale_set.html
  custom_data                                       = base64encode("HELLO WORLD")
}
```

Notice the "customData" field below is not populated:

```
> az vmss list-instances --name ueaim-dkr \
  --resource-group UE-TST-TESTSERVERS \
  --expand instanceView --output json --query '[].osProfile'
[
  {
    "adminPassword": null,
    "adminUsername": "<redacted>",
    "allowExtensionOperations": true,
    "computerName": "test-dkr000005",
    "customData": null,
    "linuxConfiguration": {
      "disablePasswordAuthentication": false,
      "patchSettings": {
        "patchMode": "ImageDefault"
      },
      "provisionVmAgent": true,
      "ssh": {
        "publicKeys": []
      }
    },
    "requireGuestProvisionSignal": true,
    "secrets": [],
    "windowsConfiguration": null
  }
]

```

```
❯ terraform version                                                                                                                         
Terraform v0.12.29
+ provider.azuread v0.11.0
+ provider.azurerm v2.33.0
```

**Comment by tombuildsstuff** [comment]
hi @k7faq 

Thanks for opening this issue.

Unfortunately this is a limitation of the Azure API - where the `customData` field can be set (created/updated) but not retrieved due to it potentially containing sensitive data. The customData gets written out to a specific path dependent on the OS being used, as such it should be possible to confirm this is being set by checking this file - more information can be found here: https://docs.microsoft.com/en-us/azure/virtual-machines/custom-data.

Since this is a question regarding Terraform Configuration/the Azure API I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!
