### ISSUE TITLE
Support for azurerm_sql_database - Add ability to define DB cores and storage

### ISSUE THREAD

**Issue by gchagan36** [terraform-providers/terraform-provider-azurerm#9028]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Need a way to specify the specs of a SQL database (cores, storage, etc). Currently there is no way to do this. This is incredibly important as database core and storage sizing are crucial parts of deploying a SQL database resource. 

### New or Affected Resource(s)

azurerm_sql_database

### Potential Terraform Configuration

```hcl
resource "azurerm_sql_database" "example" {
  name                = var.db_name
  resource_group_name = var.resource_group_name
  location            = var.location
  server_name         = azurerm_sql_server.example.name
  create_mode         = "Default"
  edition             = "GeneralPurpose"
  sku = "GP_Gen5_4"  # Similar to how it's done in azurerm_postgresql_server
  storage_mb = 640000  # Similar to how it's done in azurerm_postgresql_server
}
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @gchagan36 

Thanks for opening this issue.

Support for [this is available in the `azurerm_mssql_database` resource](https://www.terraform.io/docs/providers/azurerm/r/mssql_database.html), which supersedes the `azurerm_sql_database` resource - can you take a look and see if that works for you?

Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider I'm going to close this issue for the moment but if that doesn't work for you then please let us know and we'll take another look.

Thanks!
