### ISSUE TITLE
How to merge two blocks [data, locals] to apply Azure Policy

### ISSUE THREAD

**Issue by patelvi1** [terraform-providers/terraform-provider-azurerm#9064]
I would like to apply multiple Azure Policies to AKS. It seems to be complex to achieve in loop
e.g. 

```
locals {
  policylist = [
    { name = "Do not allow privileged containers in Kubernetes cluster", foldername = "folder0" },
    { name = "Enforce HTTPS ingress in Kubernetes cluster", foldername = "folder1" },
     ]
data "azurerm_policy_definition" "example" {
  count = "${length(local.policylist)}"
  display_name = "${local.policylist[count.index].name}"

}

resource "azurerm_policy_assignment" "example" {
    count                = "${length(local.policylist)}"
    name                 = data.azurerm_policy_definition.example[count.index].name
    policy_definition_id = data.azurerm_policy_definition.example.id
    parameters           = file("${path.module}/policyjson/${local.policylist[count.index].fname}/params.json")
    scope                = azurerm_resource_group.example.id
}

```

This logic may create more issue since count index would be different in `local.policylist` and `data.azurerm_policy_definition`

How can I append ID values back to `local.policylist` only after matching correct name? 
```
e.g. 
policylist = [
  {name = "", foldername="", id=""}
]
```

**Comment by tombuildsstuff** [comment]
hi @patelvi1 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
