### ISSUE TITLE
Destroying load balancer errors due to CannotRemoveRuleUsedByProbeUsedByVMSS

### ISSUE THREAD

**Issue by rakeshsiet** [terraform-providers/terraform-provider-azurerm#9076]
I am facing the below error :
Error: Creating/Updating Load Balancer <name>: network.LoadBalancersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="CannotRemoveRuleUsedByProbeUsedByVMSS" Message="Load balancer rule <name> cannot be removed because the rule references the load balancer probe <name> that is used as health probe by VM scale set <name>. To remove this rule, please update VM scale set to remove the reference to the probe."

My configuration is similar to the issue #4398 which seems to be fixed, in the earlier releases.
I am using the azurerm provider version = "2.33.0" and still getting the issue.
I have tried with depends_on as suggested in the issue #4398 , but of no use.
Have found one more issue similar to the #4398 , which is #4769 even this seems to be fixed in the version 2.0.0 but it is not working.

**Comment by tombuildsstuff** [comment]
hi @rakeshsiet 

Thanks for opening this issue.

Unfortunately there's not enough information above to answer this question - since this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
