### ISSUE TITLE
Terraform Cannot Create blob gen 2 storage account

### ISSUE THREAD

**Issue by jeffrey-d-lipkowitz** [terraform-providers/terraform-provider-azurerm#9088]
Code

esource "azurerm_storage_account" "example" {
  name                     = "examplestorageacc2334"
  resource_group_name      = "${azurerm_resource_group.tf_azure_guide.name}"
  location                 = "${azurerm_resource_group.tf_azure_guide.location}"
  account_tier             = "Standard"
  account_replication_type = "LRS"
  account_kind             = "StorageV2"
  is_hns_enabled           = "true"
}

resource "azurerm_storage_data_lake_gen2_filesystem" "example" {
  name               = "example2332432"
  storage_account_id = azurerm_storage_account.example.id
}
------------------------------
Output:

Error: Error checking for existence of existing File System "example2332432" (Account "examplestorageacc2334"): datalakestore.Client#GetProperties: Failure 
responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

  on main.tf line 92, in resource "azurerm_storage_data_lake_gen2_filesystem" "example":
  92: resource "azurerm_storage_data_lake_gen2_filesystem" "example" {

**Comment by JADawson** [comment]
Same error here:

Error: Error checking for existence of existing File System "landing" (Account "xxx"): datalakestore.Client#GetProperties: Failure responding to request: StatusCode=403 -- Original Error: autorest/azure: error response cannot be parsed: "" error: EOF

  on main.tf line 37, in resource "azurerm_storage_data_lake_gen2_filesystem" "adls_fs_l":
  37: resource "azurerm_storage_data_lake_gen2_filesystem" "adls_fs_l" {

**Comment by tombuildsstuff** [comment]
hi @jeffrey-d-lipkowitz @JADawson 

Thanks for opening this issue.

Taking a look through this appears to be an issue with the credentials/Terraform Configuration being used here - this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
