### ISSUE TITLE
How to add pre authorised applications in an Azure AD app registration via terraform

### ISSUE THREAD

**Issue by RanjithMahadevan** [terraform-providers/terraform-provider-azurerm#9103]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---
Hi Team,

I'm creating Azure AD App  & expose API's,  also i wanted to authorise same AD APP client id in pre authorised applications permission  which will update the manifest file like below.
```
"preAuthorizedApplications": [
		{
			"appId": "5e3ce6c0-2arf-4285-8s23b-75ee78787346",
			"permissionIds": [
				"434b0aae-77b3-481a-b78f-4dfds29b"
			]
		},
		{
			"appId": "1fec8e78-bce4-4aaf-dsq12b-5451cc387264",
			"permissionIds": [
				"434b0aae-77b3-481a-b78f-4dfds29b"
			]
		} 
```

plase confirm if this can be achieved through TF, if yes please advise with some examples.
Thanks,
Ranjith

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

**Comment by tombuildsstuff** [comment]
hi @RanjithMahadevan 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
