### ISSUE TITLE
azurerm_app_service section ip_restriction requires attributes that contradict the documentation

### ISSUE THREAD

**Issue by vap78** [terraform-providers/terraform-provider-azurerm#9118]
Hi

Terraform Version: v0.13.5
AzureRM Version: v2.34.0

I have following block in a asurerm_app_service resource:

```
ip_restriction           = [
  {
    ip_address = "xxx.xxx.xxx.xxx/32"
    name = "IP 1"
    priority = 100
    action = "allow"
  },
  {
    ip_address = "yyy.yyy.yyy.yyy/32"
    name = "IP 2"
    priority = 200
    action = "allow"
  }
]

```

When I run the script following error occurs:

> Inappropriate value for attribute "ip_restriction": element 0: attributes  "subnet_id" and "virtual_network_subnet_id" are required.

However the documentation of the resource at https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service  :

- does not mention the subnet_id attribute at all 
- states that either one of the ip_address or virtual_network_subnet_id should be present. 

I attempted downgrading the version of the provider all the way to 2.0.0 and the only effect was that at some point the "subnet_id" potion of the error message disappears. 

Any ideas? 

Thank you
Vasil

update:

We found a  workaround that looks like this:
```
variable "ip_addresses" {
  type = list(object({ip=string, name=string, action=string}))
  default = [
    {
      ip = "xxx.xxx.xxx.xxx/32"
      name = "IP 1",
      action = "Allow"
    },
    {
    ip_address = "yyy.yyy.yyy.yyy/32"
      name = "IP 2",
      action = "Allow"
    }]
}

  dynamic "ip_restriction" {
      for_each = var.ip_addresses
      content {
        ip_address  = ip_restriction.value.ip
        name = ip_restriction.value.name
        action = ip_restriction.value.action
    }
```

Then the error appears no more. Still this is very confisuing.

**Comment by tombuildsstuff** [comment]
hi @vap78 

Thanks for opening this issue.

Terraform Core requires when using the "dynamic" block that all fields within this block are specified - as such this is a question around Terraform (Core) rather than a bug in the Azure Provider. This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
