### ISSUE TITLE
azurerm_virtual_machine_extension JsonADDomainExtension Failure

### ISSUE THREAD

**Issue by erik5starg** [terraform-providers/terraform-provider-azurerm#9146]
JsonADDomainExtension error due to backslash in password field. Works properly when back slash is removed.

Error: "protected_settings" contains an invalid JSON: invalid character 'Y' in string escape code

  on Modules\Virtual_Machine\domain-join\vm_join_domain.tf line 13, in resource "azurerm_virtual_machine_extension" "ADD2AD":
  13: resource "azurerm_virtual_machine_extension" "ADD2AD" {

**Terraform Version:**
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0`

```
resource "azurerm_virtual_machine_extension" "ADD2AD" {
    name                 = "ADD2AD"
    virtual_machine_id   = var.vm-id
    publisher            = "Microsoft.Compute"
    type                 = "JsonADDomainExtension"
    type_handler_version = "1.3"
 
    settings = <<SETTINGS
        {
            "Name": "${var.domainname}",
            "OUPath": "${var.oupath}",
            "User": "user",
            "Restart": "true",
            "Options": "3"
        }
    SETTINGS
  protected_settings = <<PROTECTED_SETTINGS
    {
      "Password": "password"
    }
  PROTECTED_SETTINGS
```

**Comment by tombuildsstuff** [comment]
hi @erik5starg 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by erik5starg** [comment]
Is this not considered a bug?

**Comment by tombuildsstuff** [comment]
@erik5starg not if the JSON isn't escaped correctly, which is the error being raised here, for example, for the following:

```
{
	"hello": "\world"
}
```

and

```
{
	"hello": "\\world"
}
```

validating both on jsonlint.com (or any other json linter/parser, such as Terraform) will fail for the first one, but pass for the second - since `\` is an escape character in JSON, and so needs to be encoded appropriately (with two backslashes in this instance), which is why the second example works

Hope that helps :)

**Comment by erik5starg** [comment]
That did the trick actually so thank you very much!
