### ISSUE TITLE
Hdinsight Version 4.0 Incompatible with Hbase version

### ISSUE THREAD

**Issue by vinaykeenable** [terraform-providers/terraform-provider-azurerm#9152]
Hello, I'm Vinay,

I'm using multiple azure modules with Terraform. I thought to automate HDInsight cluster with terraform which i was creating using azure portal. I have defined below configuration:
`resource "azurerm_hdinsight_hbase_cluster" "HbaseHDInsightCluster" {
  cluster_version = "4.0.1000"
  location = var.location
  name = var.hdp_clustname
  resource_group_name = var.hdp_rgname
  tier = "Standard"

  component_version {
    hbase = "2.1.6"
  }`

When i apply above configuration, i found version not compatible error

Error: failure creating HDInsight HBase Cluster "test-dev-hdp" (Resource Group "dhdp-rg"): hdinsight.ClustersClient#Create: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="HDI Version'4.0' is not supported for clusterType 'hbase' and componentVersion '2.1.6'.,Invalid component version for HDInsight version: 4.0 cluster type: HBase"

Could someone assist me to get rid of it?

**Comment by tombuildsstuff** [comment]
hi @vinaykeenable 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
