### ISSUE TITLE
How use azurerm_virtual_machine_extension resource running custom script with a specific user instead root account

### ISSUE THREAD

**Issue by venkattoluchuri** [terraform-providers/terraform-provider-azurerm#9186]
I am looking for how to use azurerm_virtual_machine_extension resource with a specific non-user account. Custom script running with a root account. This is I am referring to for Linux VM

**Comment by tombuildsstuff** [comment]
hi @venkattoluchuri 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
