### ISSUE TITLE
Blocks of type "os_profile_windows_config" are not expected here

### ISSUE THREAD

**Issue by yashkv1** [terraform-providers/terraform-provider-azurerm#9219]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform Configuration Files

```
resource "azurerm_windows_virtual_machine" "example" {
  name                  = "myvm1"
  location              = "eastus"
  resource_group_name   = azurerm_resource_group.rg.name
  network_interface_ids = [azurerm_network_interface.myvm1nic.id]
  size                  = "Standard_B2s"
  admin_username        = "****"
  admin_password        = "****"

  source_image_reference {
    publisher = "MicrosoftWindowsServer"
    offer     = "WindowsServer"
    sku       = "2016-Datacenter"
    version   = "latest"
  }

  os_disk {
    caching              = "ReadWrite"
    storage_account_type = "Standard_LRS"
  }

  os_profile_windows_config {    
      provision_vm_agent  = true          
  }

}
```

### Debug Output

Error: Unsupported block type

  on main.tf line 108, in resource "azurerm_windows_virtual_machine" "example":
 108:   os_profile_windows_config {    

Blocks of type "os_profile_windows_config" are not expected here.

**Comment by tombuildsstuff** [comment]
hi @yashkv1 

Thanks for opening this issue.

The fields available on the `azurerm_windows_virtual_machine` resource differ from the older `azurerm_virtual_machine` resource and some fields have been moved to the top level, in this instance the `provision_vm_agent` field has been moved to the top-level: https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine#provision_vm_agent

Since this is a question regarding Terraform Configuration rather than a bug in the Azure Provider, I'm going to close this issue for the moment - however you can find the fields supported on [the `azurerm_windows_virtual_machine` resource in the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/windows_virtual_machine).

Thanks!
