### ISSUE TITLE
The azurerm 2.x provider no longer allows multiple azurerm_virtual_machine_extension of the same name

### ISSUE THREAD

**Issue by jkattmann** [terraform-providers/terraform-provider-azurerm#9220]
Using terraform `0.11.9` and azurerm `1.44` provider I was previously able to use multiple `azurerm_virtual_machine_extension` resources with the same name and type which would create the initial extension and then replace it with the subsequent extensions in the order defined by the depends_on property. For example:

```
resource "azurerm_virtual_machine_extension" "extension_1" {
  lifecycle {
    ignore_changes = ["protected_settings", "settings"]
  }

  name                 = "Microsoft.Powershell.DSC"
  location             = "${var.azure_location}"
  resource_group_name  = "${var.resource_group_name}"
  virtual_machine_name = "${var.virtual_machine_name}"
  publisher            = "Microsoft.Powershell"
  type                 = "DSC"
  type_handler_version = "2.77"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
  {
    "configuration": {
      "function": "Function1",
      "script": "Function1.ps1",
      "url": "${var.Function1_url}"
    },
    "configurationArguments": {
      "Parameter": "${var.Parameter}"
    }
  }
  SETTINGS
  protected_settings = <<PROTECTED_SETTINGS_JSON
    {
      "configurationUrlSasToken": "${var.sas_token}"
    }
PROTECTED_SETTINGS_JSON
}

resource "azurerm_virtual_machine_extension" "extension_2" {
  depends_on = ["azurerm_virtual_machine_extension.extension_1"]

  lifecycle {
    ignore_changes = ["protected_settings", "settings"]
  }

  name                 = "Microsoft.Powershell.DSC"
  location             = "${var.azure_location}"
  resource_group_name  = "${var.resource_group_name}"
  virtual_machine_name = "${var.virtual_machine_name}"
  publisher            = "Microsoft.Powershell"
  type                 = "DSC"
  type_handler_version = "2.77"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
    {
      "configuration": {
        "function": "Function2",
        "script": "Function2.ps1",
        "url": "${var.Function2_url}"
      },
      "configurationArguments": {
        "Parameter": "${var.Parameter}"
      }
    }
  SETTINGS
  protected_settings = <<PROTECTED_SETTINGS_JSON
    {
      "configurationUrlSasToken": "${var.sas_token}"
    }
PROTECTED_SETTINGS_JSON
}

resource "azurerm_virtual_machine_extension" "extension_3" {
  depends_on = ["azurerm_virtual_machine_extension.extension_2"]

  lifecycle {
    ignore_changes = ["protected_settings", "settings"]
  }

  name                 = "Microsoft.Powershell.DSC"
  location             = "${var.azure_location}"
  resource_group_name  = "${var.resource_group_name}"
  virtual_machine_name = "${var.virtual_machine_name}"
  publisher            = "Microsoft.Powershell"
  type                 = "DSC"
  type_handler_version = "2.77"
  auto_upgrade_minor_version = true

  settings = <<SETTINGS
{
  "configuration": {
    "function": "Function3",
    "script": "Function3.ps1",
    "url": "${var.Function3_url}"
  },
  "configurationArguments": {
    "Parameter": "${var.Parameter}"
  }
}
SETTINGS
  protected_settings = <<PROTECTED_SETTINGS_JSON
    {
      "configurationUrlSasToken": "${var.sas_token}"
    }
PROTECTED_SETTINGS_JSON
}
```

Using terraform `0.12.26` and azurerm `2.20.0` provider this approach now fails with the Error `Error: A resource with the ID "/.../Microsoft.Powershell.DSC" already exists - to be managed via Terraform this resource needs to be imported into the State. Please see the resource documentation for "azurerm_virtual_machine_extension" for more information.`

Is there a way to achieve the behavior with the latest version?

**Comment by tombuildsstuff** [comment]
hi @jkattmann 

As of version 2.0 of the Azure Provider Terraform checks for the presence of an existing resource with the same name prior to creating the resource - since it was possible to unintentionally "adopt" resources (as is being done in this example) prior to this functionality being added.

Instead it should be possible to give these unique names, so that these are executed as separate deployments - for example `phase1`, `phase2` and `phase3` - which should allow these to be deployed/managed as separate VM extensions, rather than updating the existing VM Extension. Can you take a look and see if that works for you?

Since updating the Terraform Configuration will update this, I'm going to close this issue for the moment - but please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by jkattmann** [comment]
Hi @tombuildsstuff 
Azure only allows a single extension of any handler type to be attached to a VM at once. If you change the names it will fail with the following error.
```
Error: compute.VirtualMachineExtensionsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="BadRequest" Message="Multiple VMExtensions per handler not supported for OS type 'Windows'. VMExtension 'Microsoft.Powershell.DSC.phase2' with handler 'Microsoft.Powershell.DSC' already added or specified in input."
```

Not wanting to combine all the code into a single extension, I was hoping there was a way replicate the previous behavior.

**Comment by tombuildsstuff** [comment]
@jkattmann whilst that's unfortunate in that this breaks your previous scenario - unfortunately that wasn't an intentionally supported behaviour - so there's no means of opting out of the "requires import" feature, since existing resources need to be imported into the state to ensure that we can track the behaviour for these fields correctly (e.g. if they can be updated, or if this needs to be ForceNew, or done via another API etc).

From memory certain VM Extensions (at least custom script extensions, I can't recall for others) can be provisioned multiple times, it's unfortunate that the DSC Extension isn't one of these - however it should be possible to achieve the same thing with minimal changes by using a Custom Script Extension to invoke DSC as 3 extensions (as your doing today) - rather than converting these into a single script.

Alternatively it's possible to work around this by using a variable for the configuration to load and running `terraform apply` three times to deploy the first, change this to the second variable and finally the third variable - but that's not ideal.

As mentioned above I believe switching to call DSC via a CustomScriptExtension would be the least amount of changes to get this working, so that's likely what I'd recommend here.

Hope that helps :)

**Comment by jkattmann** [comment]
@tombuildsstuff thanks for the information, I assumed it was unintentional behavior I was taking advantage of but figured it was worth checking in case there was another path in v.12.

Unfortunately calling the DSC from a custom extension is not possible as the DSC has requirements to reboot the VM which custom script extensions do not support. I think we will be best served to combine the DSC into a single module that can be called once. We could also use a null resource to add and remove the DSC extensions using an external script but think a single DSC extension is preferable. 

Thanks again for the info!
