### ISSUE TITLE
Issue in azurerm_kubernetes_cluster_node_pool module

### ISSUE THREAD

**Issue by jacknblak** [terraform-providers/terraform-provider-azurerm#9267]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

 Terraform v0.12.29

### Affected Resource(s)

* `azurerm_kubernetes_cluster_node_pool`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```
resource "azurerm_kubernetes_cluster_node_pool" "pepnodepool" {
  name                  = "pepagent"
  kubernetes_cluster_id = azurerm_kubernetes_cluster.aks_cluster.id
  vm_size               = var.pep_vm_size
  min_count             = var.pep_node_min_count
  max_count             = var.pep_node_max_count
  enable_auto_scaling   = true
  
  tags       = var.common_tags
  depends_on = [azurerm_kubernetes_cluster.aks_cluster]
  lifecycle {
    ignore_changes = [
      tags,
      id,
      max_pods,
      node_count,
      orchestrator_version,
      os_disk_size_gb
    ]
  }
}

### Debug Output

Every time terraform recreates the additional nodepool without any changes in the terraform script
=====
pat/agentPools/pepagent, 1m30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still destroying... [id=/subscriptions/345xxxx-0409-49c4-8697-...ms-aks-cluster-pat/agentPools/pepagent, 1m40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still destroying... [id=/subscriptions/345xxxx-0409-49c4-8697-...ms-aks-cluster-pat/agentPools/pepagent, 1m50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still destroying... [id=/subscriptions/345xxxx-0409-49c4-8697-...ms-aks-cluster-pat/agentPools/pepagent, 2m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Destruction complete after 2m2s
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Creating...
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [20s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [30s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [40s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [50s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [1m0s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [1m10s elapsed]
module.aks_cluster.azurerm_kubernetes_cluster_node_pool.pepnodepool: Still creating... [1m20s elapsed]

### Expected Behavior
terraform should never recreate the additional nodepool, unless there is a change in the tf module script

terraform should never recreate the additional nodepool, unless there is a change in the tf module script

### Actual Behavior

terraform recreates the additional nodepool, even without any changes in the module.

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by favoretti** [comment]
Can you post a plan output please that shows which property change forces recreation?

**Comment by jacknblak** [comment]
Plan details are shown in this screenshot, pls let me know, for more information.

![image](https://user-images.githubusercontent.com/22939777/98801784-53f0f180-2438-11eb-84a1-c1630cc0d3d7.png)

**Comment by tombuildsstuff** [comment]
Hey @jacknblak

Thanks for opening this issue and providing the plan output above.

At this time AKS only supports node pools located on the same virtual network - as such unfortunately AKS will provision this node pool on this virtual network by default, even if this field is unspecified. Whilst we could add validation to ensure that this is the same as other node pools on the cluster - we've been told (albeit a while ago now) that support for node pools on different subnets/networks is coming soon - as such we've opted to intentionally expose these fields to support this upcoming functionality.

In this instance it should be possible to fix this by updating the Terraform Configuration to include the ID of the Virtual Network here - in future when AKS ships support for node pools on multiple (internal/external networks) it should be possible to omit this field; however since this behaviour [is documented](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster_node_pool.html#vnet_subnet_id) I'm going to close this issue for the moment.

Thanks!
