### ISSUE TITLE
Support for key vault secrets as Terraform parameters

### ISSUE THREAD

**Issue by swgriffith** [terraform-providers/terraform-provider-azurerm#927]
For various scenarios (ex. Domain admin credentials in domain join) it would be great to have the ability to access a secret in Azure key vault for a Terraform parameter.

**Comment by tombuildsstuff** [comment]
hey @swgriffith 

Thanks for opening this issue :)

There's been two Feature Requests related to this area which kind of conflict - accessing the value of a Key Vault Secret as a Data Source in Terraform; and threading through a `key_vault_secret_id` parameter onto each resource.

After thinking about this for a while, we've opted to the approach of exposing the Key Vault Secret as a Data Source - which whilst not ideal (since secret values are stored in the Statefile) - it's more practical in terms of detecting changes to secrets; it also means it can be used on any resource today vs waiting for support to be added to each independent resource.

Since support for [the `azurerm_key_vault_secret` Data Source](https://www.terraform.io/docs/providers/azurerm/d/key_vault_secret.html) shipped in v1.5.0 of the AzureRM Provider - I'm going to close this issue for the moment.

Thanks!
