### ISSUE TITLE
Terraform takes more than 1 hour to update Azure frontdoor

### ISSUE THREAD

**Issue by veteixei** [terraform-providers/terraform-provider-azurerm#9295]
Hello Team,
	
During the updates customer find that terraform takes more than 1 hour to update frontdoor and eventually leading to timeout as the azure devops agent timeout after 1 hour.
	
- Customer is using azurerm provider 2.23.0
- Cx want to upgrade to 2.24.0 but seems there's a bug in azurerm provider 2.24.0 : https://github.com/terraform-providers/terraform-provider-azurerm/issues/8208
	
So he can't upgrade from 2.23.0 to 2.24.0 due to bug above

Could you please let me know if this bug was already fixed and if cx can upgrade? Or if cx can upgrade to a different version to get rid of the problem: " terraform takes more than 1 hour to update frontdoor"?

I can see that the most recent release is 2.35.0. Can cx upgrade from 2.23.0 to 2.35.0 at once?

Cx is claiming that the bug prevents him from updating the provider version.

Many thanks

**Comment by ajklotz** [comment]
I recently worked with the azurerm_front_door resource and found that the terrform apply was taking a long time after I started configuring the frontend_endpoints with custom_https_provisioning_enabled = true and associating a web_application_firewall_policy_link_id and setting custom_https_configuration.certification_source = "Front Door"

Would you say that this is the same for you?

**Comment by tombuildsstuff** [comment]
hi @veteixei 

Thanks for opening this issue.

As per [the documentation](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor#timeouts) provisioning a FrontDoor can take up to 6 hours - as such it's likely this will take more than 1 hour, due to the provisioning speed of the Azure Service unfortunately.

As you've mentioned #8208 is tracking an issue with FrontDoor which stems from an issue in the Azure Portal, since this is being tracked in that issue, to avoid posting updates in multiple places, please subscribe to that issue for updates - however once the Azure Portal team have rolled out the fix this should be fixed.

Since as mentioned above it's expected for a FrontDoor to take a significant amount of time to provision - due to the underlying Azure Service taking this time to provision it - I'm going to close this issue for the moment. We use this forum to track bugs and feature requests in the Azure Provider, but should you have further questions I'd direct you towards [the community discuss forum](https://discuss.hashicorp.com).

Thanks!

**Comment by veteixei** [comment]
Hello @tombuildsstuff !

Thank you for you answer. 

In the documentation it is described the timeouts that can be specified:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/frontdoor#timeouts
"
The timeouts block allows you to specify timeouts for certain actions:
create - (Defaults to 6 hours) Used when creating the FrontDoor.
update - (Defaults to 6 hours) Used when updating the FrontDoor.
read - (Defaults to 5 minutes) Used when retrieving the FrontDoor.
delete - (Defaults to 6 hours) Used when deleting the FrontDoor.
"

As per my understanding it is to define the timeout and not the duration of the update.

By the other hand, per Microsoft's documentation, "A new Front Door creation or any updates to an existing Front Door **takes about 3 to 5 minutes** for global deployment. That means in about 3 to 5 minutes, your Front Door configuration will be deployed across all of our POPs globally."

https://docs.microsoft.com/en-gb/azure/frontdoor/front-door-faq#how-long-does-it-take-to-deploy-an-azure-front-door-does-my-front-door-still-work-when-being-updated

How can we explain the the 3 hours that we are having?

Many thanks,
Vera

**Comment by veteixei** [comment]
Hello Team,

Does anyone can help on this question?

Thanks,
Vera

**Comment by veteixei** [comment]
> I recently worked with the azurerm_front_door resource and found that the terrform apply was taking a long time after I started configuring the frontend_endpoints with custom_https_provisioning_enabled = true and associating a web_application_firewall_policy_link_id and setting custom_https_configuration.certification_source = "Front Door"
> 
> Would you say that this is the same for you?

Hello @ajklotz , my cx is doing some updates. Don't know specifically which activity.
They want to upgrade terraform but can't do it because there's a bug in azurerm provider 2.24.0.
