### ISSUE TITLE
Error when creating App Service Plan via Azure Devops Ci/CD

### ISSUE THREAD

**Issue by kay07949** [terraform-providers/terraform-provider-azurerm#9305]
I am getting this error when I run my ci/cd pipeline for terraform:

Error creating/updating App Service Plan "azure-functions-service-plan" (Resource Group "TestTerraformCiCD"): web.AppServicePlansClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="LinkedInvalidPropertyId" Message="Property id '' at path 'properties.hostingEnvironmentProfile.id' is invalid. Expect fully qualified resource Id that start with '/subscriptions/{subscriptionId}' or '/providers/{resourceProviderNamespace}/'."

I am running the simple terraform script below via Azure DevOps CI/CD pipeline:

resource "azurerm_app_service_plan" "appplan" {
  name                = "azure-functions-service-plan"
  location            = var.location
  resource_group_name = var.rg
  kind                = "FunctionApp"

  sku {
    tier = "Dynamic"
    size = "Y1"
  }
}

**Comment by tombuildsstuff** [comment]
hi @kay07949 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
