### ISSUE TITLE
Feature Request: OMS log analytics solution

### ISSUE THREAD

**Issue by pixelicous** [terraform-providers/terraform-provider-azurerm#931]
Would be really happy to see support for OMS long analytics solutions.
Right now it's pretty pointless to create OMS using terraform

**Comment by tombuildsstuff** [comment]
hey @pixelicous 

Thanks for opening this issue :)

Would you be able to clarify exactly what functionality you're looking for within OMS/Log Analytics? [Looking at the information available in the API](https://docs.microsoft.com/en-us/rest/api/loganalytics/) - I have a feeling we may need to request to Microsoft to expose extra API's in order to add support for this

Thanks!

**Comment by pixelicous** [comment]
@tombuildsstuff I have been talking about this-[management solutions](https://docs.microsoft.com/en-us/azure/operations-management-suite/operations-management-suite-solutions)
But yeah, i cannot find any mention on the api page as well.. i will try to take it with ms directly to expose it first.. thanks!

**Comment by pixelicous** [comment]
opened - Azure/azure-rest-api-specs#2598

**Comment by tombuildsstuff** [comment]
cool, thanks @pixelicous - I'll keep and eye on that and mark this as `upstream` for now

**Comment by pixelicous** [comment]
@tombuildsstuff hey! i saw you also noticed microsoft responded and they do have those endpoints exposed.. can we place it in the feature request bin/queue?

**Comment by tombuildsstuff** [comment]
@pixelicous given this service is still in Preview, we'd need to tread carefully here. We generally don't support Preview services/functionality until they're in the self-registration Public Preview phase, since prior to that time there can be breaking changes which makes upgrade paths tricky. I notice this functionality is in Preview - do you know if this is available for customers to self-register for, or is it still in the invite-only phase?

Looking at our roadmap, we're not scheduled to get to this until later in the year - that said we'd be happy to help with a community PR for this before then :)

Thanks!

**Comment by tombuildsstuff** [comment]
@whytoe it is, thanks for highlighting that - in which case I'll close this issue for the moment :)

**Comment by pixelicous** [comment]
@whytoe @tombuildsstuff when i opened the issue this wasn't available.
Funny thing is, the first commit of the documentation happened 3 days after i opened the issue:
[History for terraform-provider-azurerm/website/docs/r/log_analytics_solution.html.markdown](https://github.com/terraform-providers/terraform-provider-azurerm/commits/master/website/docs/r/log_analytics_solution.html.markdown)

**Comment by whytoe** [comment]
Well I'm glad it's all fixed and working :) I'm just glad I don't have to
add them using the portal :)

**Comment by yves-vogl** [comment]
Maybe I'm missing something… but what's the point for just creating the solution resource without being able to connect data sources in Azure? Or do you handover to another solution for configuration management as it's not provisioning?

**Comment by pixelicous** [comment]
@yves-vogl Good point, I thought we would be able to do both.

**Comment by mb290** [comment]
With VMs you’d use the Azure VM Extension to configure the OMS agent, this then hooks it into said workspace. The one area that looks to be lacking is configuring what data sources are collected, maybe we need a resource for this [https://docs.microsoft.com/en-us/rest/api/loganalytics/datasources](https://docs.microsoft.com/en-us/rest/api/loganalytics/datasources). Another piece of functionality I want to look into is with other logging in Azure, NSG flow logs for example.

**Comment by whytoe** [comment]
@mb290 Microsoft is currently moving OMS portal back into Azure and deprecating features. I am still trying to find a way to hook Application Insights into it using the Rest API but that does not appear to be supported as a data source or what Microsoft calls "Linked Services"
