### ISSUE TITLE
azurerm_container_group not redeploy when docker image is updated in registry

### ISSUE THREAD

**Issue by daloulou** [terraform-providers/terraform-provider-azurerm#9322]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

v2.36.0

### Affected Resource(s)

*azurerm_container_group

### Terraform Configuration Files

```hcl
provider "azurerm" {
  features {}
}

resource "azurerm_resource_group" "example" {
  name     = "${var.prefix}-resources"
  location = "${var.location}"
}

resource "azurerm_container_group" "example" {
  name                = "${var.prefix}-continst"
  location            = "${azurerm_resource_group.example.location}"
  resource_group_name = "${azurerm_resource_group.example.name}"
  ip_address_type     = "public"
  os_type             = "linux"

  image_registry_credential {
    server   = "hub.docker.com"
    username = "yourusername1"
    password = "yourpassword"
  }

  image_registry_credential {
    server   = "private-registry"
    username = "2yourusername1"
    password = "2yourpassword"
  }

  container {
    name   = "hw"
    image  = "private-regisrty/aci-helloworld:latest"
    cpu    = "0.5"
    memory = "1.5"
    port   = "80"
  }


  tags = {
    environment = "testing"
  }
}
```

### Expected Behaviour

If image is updated on private registry between two terraform apply, with a `docker push private-registry/aci-helloworld:latest` image should have a new hash and container should be redeployed

### Actual Behaviour

`terraform apply` return : Apply complete! Resources: 0 added, 0 changed, 0 destroyed.
### Steps to Reproduce

1. `terraform apply`
2. `docker build`
3. `docker push private-registry/aci-helloworld:latest`
4. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @daloulou 

Thanks for opening this issue.

From Terraform's perspective this is providing this information to the Azure API which is taking "latest" at deployment time (which is understandable), but not detecting that there's an update available here. Unfortunately from Terraform's perspective since the Azure API is returning that this is the latest version available, we're unable to detect a diff here - that said it should be possible to for Terraform to detect this change should a Data Source be used to determine the latest version of the Container present in the Container Registry.

It should be possible to use [the `docker_registry_image` resource](https://www.terraform.io/docs/providers/docker/d/registry_image.html) to look this Docker Image up in the Azure Container Registry, using the `:latest` version there to get the actual version number for "latest" - at which point Terraform should detect this change (since version `old` should be replaced by version `new` when a new image is pushed and `terraform plan` is ran).

Whilst in this instance this is a limitation of the Azure API - I believe it should be possible to workaround this by using the Data Source above to lookup the latest version of this image - and as such I'm going to close this issue for the moment, however should you have further questions you should be able to get further assistance on the [community forum](https://discuss.hashicorp.com).

Thanks!
