### ISSUE TITLE
Kubernetes cluster: cannot get effective_outbound_ips value

### ISSUE THREAD

**Issue by wired-R** [terraform-providers/terraform-provider-azurerm#9328]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

 ```
terraform version                                                                                                   
Terraform v0.13.3
+ provider registry.terraform.io/hashicorp/azurerm v2.20.0`
```
### Terraform Configuration Files

```hcl

resource "azurerm_virtual_network" "default" {
  name                = "${azurerm_resource_group.default.name}-vnet"
  address_space       = ["172.16.0.0/16"]
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
}

resource "azurerm_subnet" "internal" {
  name                 = "private_interface"
  resource_group_name  = azurerm_resource_group.default.name
  virtual_network_name = azurerm_virtual_network.default.name
  address_prefix       = "172.16.2.0/24"
}

resource "azurerm_kubernetes_cluster" "cluster" {
  name                = "${var.aks_dns_prefix}-aks"
  location            = azurerm_resource_group.default.location
  resource_group_name = azurerm_resource_group.default.name
  kubernetes_version  = "1.18.8"
  dns_prefix          = var.aks_dns_prefix

  network_profile {
    network_plugin      = "kubenet"
    load_balancer_sku   = "Standard" 
  }
  
  default_node_pool {
    name            = "master"
    node_count      = var.master_nodepool_node_count
    vm_size         = var.master_node_pool_vm_size
    vnet_subnet_id  = azurerm_subnet.internal.id
    node_labels = {
      "role" = "manager"
    }
  }

  service_principal {
    client_id     = var.appId
    client_secret = var.password
  }

  role_based_access_control {
    enabled = true
  }
}

data "azurerm_public_ip" "cluster" {
  name                = reverse(split("/", tolist(azurerm_kubernetes_cluster.cluster.network_profile.0.load_balancer_profile.0.effective_outbound_ips)[0]))[0]
  resource_group_name = azurerm_resource_group.default.name
}

output "cluster_egress_ip" {
  value = data.azurerm_public_ip.cluster.ip_address
}
```

### Debug Output

```
Error: Error: Public IP "83d***************************b1" (Resource Group "rg_name") was not found

  on ../terraform/dev/aks-cluster.tf line 84, in data "azurerm_public_ip" "cluster":
  84: data "azurerm_public_ip" "cluster" {

```

### Expected Behaviour

Expecting the first and only public_ip name to be returned in the output

### Steps to Reproduce

    `terraform init`
    `terraform plan`

1. `terraform apply`

### References

* #7276

**Comment by tombuildsstuff** [comment]
hi @wired-R 

Thanks for opening this issue.

Taking a look through this appears to be an issue with the Terraform Configuration, where an explicit dependency is necessary between the Public IP Data Source and the Kubernetes Cluster to force the ordering, this can be achieved using [Terraform's `depends_on` functionality](https://learn.hashicorp.com/tutorials/terraform/dependencies).

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
