### ISSUE TITLE
Please re-add support for enable_pod_security_policy in azurerm_kubernetes_cluster

### ISSUE THREAD

**Issue by t3mi** [terraform-providers/terraform-provider-azurerm#9336]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_kubernetes_cluster`

### Terraform Configuration Files

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key: https://keybase.io/hashicorp
```

### Expected Behaviour

AKS cluster should be created successfully with pod security feature enabled.

### Actual Behaviour

Creation restricted.
### Steps to Reproduce

1. `terraform apply`

### Important Factoids

The Azure Kubernetes Service pod security policy (preview) feature will be retired on [February 1st 2021](https://github.com/Azure/AKS/releases/tag/2020-11-09).
### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @t3mi 

Thanks for opening this issue.

Since this functionality is approaching it's end-of-life and has already been removed from the Provider - whilst we could look to reintroduce this functionality, we'd ultimately be pulling this out in a couple of months anyway since this is no longer available as of 1st February 2021, and as such unfortunately we don't plan to re-introduce this functionality at this time.

Whilst that's unfortunate if you're still using this deprecated functionality, you should be able to continue doing so by pinning to the older version of the Provider until this functionality is removed by Microsoft, namely version `2.34.0` of the Azure Provider.

Thanks!

**Comment by t3mi** [comment]
@tombuildsstuff I agree that its marked deprecated only but that deprecation date could shift again as currently no replacement exists for pod security policies. That's not a big change and removal of it could be done anytime.

**Comment by t3mi** [comment]
Date shifted again -> The Azure Kubernetes Service pod security policy (preview) feature will be [retired](https://github.com/Azure/AKS/releases/tag/2020-11-16) on **May 31st, 2021.**
