### ISSUE TITLE
"api-version is invalid" on role assignment

### ISSUE THREAD

**Issue by vgazzola** [terraform-providers/terraform-provider-azurerm#9341]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_XXXXX`

### Terraform Configuration Files

providers :
```hcl
provider "azurerm" {
  version = "2.36.0"
  features {}

  subscription_id = var.subscription_id
  client_id       = var.client_id
  client_secret   = var.azure_client_secret
  tenant_id       = var.tenant_id
}
```

role assignment:
```hcl
resource "azurerm_role_assignment" "example" {
  scope              = "/subscriptions/${var.subscription_id}/resourceGroups/${azurerm_resource_group.example.name}/provider/Microsoft.Storage/storageAccounts/${azurerm_storage_account.example.name}/blobServices/default/ }"
  principal_id       = var.principal_id
  role_definition_id = azurerm_role_definition.blob-writer.id
}

```

### Debug Output

https://gist.github.com/vgazzola/c4534e03ce4ecee25f21749da1de2dcc

### Expected Behaviour

assign custom role  "blob-writer" to principal  "var.principal_id" on the provided scope
### Actual Behaviour

The following error (see gist above) is given
```bash
Error: Error checking for presence of existing Role Assignment ID for "00000000-0000-0000-0000-000000000000" (Scope "/subscriptions/00000000-0000-0000-0000-000000000000/resourceGroups/abcd-dev-adls/provider/Microsoft.Storage/storageAccounts/abcd/blobServices/default/ }"): authorization.RoleAssignmentsClient#Get: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="InvalidApiVersionParameter" Message="The api-version '2018-09-01-preview' is invalid. The supported versions are '2020-07-01,2020-06-01,2020-05-01,2020-01-01,2019-11-01,2019-10-01,2019-09-01,2019-08-01,2019-07-01,2019-06-01,2019-05-10,2019-05-01,2019-03-01,2018-11-01,2018-09-01,2018-08-01,2018-07-01,2018-06-01,2018-05-01,2018-02-01,2018-01-01,2017-12-01,2017-08-01,2017-06-01,2017-05-10,2017-05-01,2017-03-01,2016-09-01,2016-07-01,2016-06-01,2016-02-01,2015-11-01,2015-01-01,2014-04-01-preview,2014-04-01,2014-01-01,2013-03-01,2014-02-26,2014-04'."

  on acls.tf line 8, in resource "azurerm_role_assignment" "example":
   8: resource "azurerm_role_assignment" "example" {
```

### Steps to Reproduce

1. replace in the config above an *Existing* principal id, and an *existing* role_definition_id 
2. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @vgazzola 

Thanks for opening this issue.

Taking a look through here unfortunately this is an unhelpful error message being returned from the Azure API, where because the scope is incorrect it's returning a 404, to look at the code above:

>   scope              = "/subscriptions/${var.subscription_id}/resourceGroups/${azurerm_resource_group.example.name}/provider/Microsoft.Storage/storageAccounts/${azurerm_storage_account.example.name}/blobServices/default/ }"

needs to be:

>   scope              = "/subscriptions/${var.subscription_id}/resourceGroups/${azurerm_resource_group.example.name}/providers/Microsoft.Storage/storageAccounts/${azurerm_storage_account.example.name}/blobServices/default/ }"

(changing `provider` -> `providers`)

When creating the role assignment [this scope gets prefixed to the Request URI as a part of the request](https://github.com/Azure/azure-sdk-for-go/blob/57c63988ef69356866c7530c0a15e4e5917d0aca/services/authorization/mgmt/2015-07-01/authorization/roleassignments.go#L114) - since Role Assignments are scoped to the "scope".

Unfortunately in this instance this error message is coming from the Azure API, since the Scope used as a Prefix doesn't exist - and whilst this error message isn't great, unfortunately we're limited by the Azure API here.

Since it should be possible to fix this by updating `provider` to `providers` in the Scope and re-running this Terraform Configuration, I'm going to close this issue for the moment - but please let us know if that doesn't work and we'll take another look.

Thanks!
