### ISSUE TITLE
Terraform Azure SQL Database with serverless edition

### ISSUE THREAD

**Issue by mdzierzecki** [terraform-providers/terraform-provider-azurerm#9360]
Hey,

do you know guys how can I create a SQL Database on Azure using Terraform with Serverless edition? I need to provision max/min CPU cores info etc.

I could not find anything in documentation :/ Any thoughts?

**Comment by tombuildsstuff** [comment]
hi @mdzierzecki 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
