### ISSUE TITLE
azurerm_network_security_rule value for source port ranges warning

### ISSUE THREAD

**Issue by almir0** [terraform-providers/terraform-provider-azurerm#9377]
Running and setting source port range to * will create source port range: 0-65535 in Azure resulting in a warning saying: The recommended value for source port ranges is * (Any). Port filtering is mainly used with destination port.

resource "azure_security_group" "web" {
  # ...
}

resource "azure_security_group" "apps" {
  # ...
}

resource "azure_security_group_rule" "ssh_access" {
  name                       = "ssh-access-rule"
  security_group_names       = ["${azure_security_group.web.name}", "${azure_security_group.apps.name}"]
  type                       = "Inbound"
  action                     = "Allow"
  priority                   = 200
  source_address_prefix      = "100.0.0.0/32"
  source_port_range          = "*"
  destination_address_prefix = "10.0.0.0/32"
  destination_port_range     = "22"
  protocol                   = "TCP"
}

**Comment by tombuildsstuff** [comment]
hi @almir0 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
