### ISSUE TITLE
Deploying AKS failed 

### ISSUE THREAD

**Issue by seitosana** [terraform-providers/terraform-provider-azurerm#938]
Hi there,

i have an issue with terraform AKS deployment. 

### Terraform Version
Terraform v0.11.4
+ provider.azurerm v1.1.2

### Error : 
Error: Error applying plan:

1 error(s) occurred:

* azurerm_kubernetes_cluster.test: 1 error(s) occurred:

* azurerm_kubernetes_cluster.test: containerservice.ManagedClustersClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="PropertyChangeNotAllowed" Message="Changing property 'agentPoolProfile.vmSize' is not allowed."

**Comment by tombuildsstuff** [comment]
hi @seitosana 

Thanks for opening this issue

Taking a look into this, the error message that you're seeing: `Changing property 'agentPoolProfile.vmSize' is not allowed.` is being returned since terraform isn't tracking the state of the Kubernetes Cluster. 

When a resource is created with Terraform, it's added to a Statefile (generally `terraform.tfstate`) which tracks the state of all the resources Terraform's managing. If a resource isn't found in the State, we try and recreate it, which is what's happened here. It's also possible to import existing resources into Terraform's State using [the `terraform import` command](https://www.terraform.io/docs/commands/import.html), for instance [here's the command needed to import a Kubernetes Cluster](https://www.terraform.io/docs/providers/azurerm/r/kubernetes_cluster.html#import).

In the code this field is a `ForceNew` - which means when it's changed Terraform will delete and recreate the Kubernetes cluster since we know it can't be changed:

https://github.com/terraform-providers/terraform-provider-azurerm/blob/b389391f181708b9c9ae78a6d2b67c7bd821931b/azurerm/resource_arm_kubernetes_cluster.go#L112-L116

However since in this case it appears Terraform doesn't know about the state, it's trying to recreate it (using the Upsert API available in Azure) which is why you're seeing this failure.

I'd suggest the best way forward here would be to Import the resource into the Terraform Statefile and then attempt to make this change; where Terraform will then prompt you to destroy/recreate the cluster.

Would you be able to take a look and see if that solves your problem?

Thanks!

**Comment by seitosana** [comment]
Hi @tombuildsstuff  

thanks for your answer. I try again with your explanation. 

all's work.

thanks a lot

best regards
