### ISSUE TITLE
Error getting certificate specifying version

### ISSUE THREAD

**Issue by jullianoacqio** [terraform-providers/terraform-provider-azurerm#9386]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

* `azurerm_v2.36.0_x5`

### Terraform Configuration Files

```hcl
data azurerm_key_vault keyvault {
  name                = "dev-br-keyvault-kv"
  resource_group_name = "dev-br-keyvault-rg"
}

data azurerm_key_vault_certificate acqionet {
  name         = "acqionet"
  key_vault_id = data.azurerm_key_vault.keyvault.id
  version      = "e79dbe8689d64940acf1a85cc0d78dd5"
}
```

### Debug Output

https://gist.github.com/jullianoacqio/187f3ab2aa1e0b4cbe06080336504926

### Steps to Reproduce

1. `terraform apply`

### References

* #0000

**Comment by tombuildsstuff** [comment]
hey @jullianoacqio 

Thanks for opening this issue.

This issue was previously raised in #9352 and has been fixed in #9355 which will ship in v2.37.0 of the Azure Provider later today - as such I'm going to close this issue for the moment, but I've assigned this to the v2.37.0 milestone so @hashibot will comment when that's been released.

Thanks!
