### ISSUE TITLE
One remote terraform state file and 2 different plans. 

### ISSUE THREAD

**Issue by kethasid** [terraform-providers/terraform-provider-azurerm#9407]
I've imported statefile for 2 of the azure resources. After editing the statefile at the remote backend which is azure blob storage, When the ci/cd pipeline runs the terraform plan shows 2 resources to add instead of 'No change in infrastructure' 

I tried the below. 

 I've  tried to do a tf plan on the same statefile which the pipeline is generating. Below are the screenshots of the 2 different tf plans for same statefile. one is thru pipeline and one thru my local machine. 2 different plans

![image](https://user-images.githubusercontent.com/49861388/99781101-b7091500-2b17-11eb-9fcb-fb8976d88b28.png)

![image](https://user-images.githubusercontent.com/49861388/99781146-c38d6d80-2b17-11eb-9021-57e79d3fad60.png)

Dont know where I'm going wrong. When i edit the statefile and run tf plan at local it does recognize the changes in file but not the ci/cd pipleine on az devops 

Please let me know if I'm missing out on something

**Comment by tombuildsstuff** [comment]
hi @kethasid 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
