### ISSUE TITLE
Specify use_managed_identity for linked service on Azure Datafactory via Terraform

### ISSUE THREAD

**Issue by trafferty20** [terraform-providers/terraform-provider-azurerm#9411]
Hi All,

I've created a linked service for an Azure SQL Database via terraform for my Azure Data Factory, but as far as I can see, theres no way to specify use_managed_identity. You can specify it for other things, such as data lake storage, but for an Azure SQL Database it just defaults to SQL Authentication. When setting it up manually in the portal, you can select to use a managed ID as the Authentication type. Does anyone know if this is possible via terraform? 

Thanks

**Comment by tombuildsstuff** [comment]
hi @trafferty20 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by trafferty20** [comment]
Hi Tom,

Thanks for getting in touch, however I think you have closed this off prematurely. The issue/ question I raised was about a feature enhancement (however I appreciate my wording could have been more accurate).

The feature enhancement I was asking about was a feature to be able to specify/ set the authentication type to use managed ID for the Azure sql database linked service in Data Factory, when using terraform. This can be done for other linked services, but it appears not for Azure SQL Databases.

Can this issue be reopened, or am I best creating a new one?

Thanks,

Tom Rafferty
DevOps Engineer
Infrastructure Tax | Solutions & Digital
' +44 (0)7778240872
@   Tom.Rafferty@kpmg.co.uk<mailto:Tom.Rafferty@kpmg.co.uk>

KPMG UK LLP
Manchester Technology Centre,
130 Oxford Road,
Manchester
M1 7ED
