### ISSUE TITLE
Create IoT Hub Device

### ISSUE THREAD

**Issue by EPilz** [terraform-providers/terraform-provider-azurerm#9416]
Is it possible to create a single IoT Hub device with terraform?
As it is possible with Azure CLI: `az iot hub device-identity create --device-id myDeviceId --hub-name {Your IoT Hub name}`

**Comment by tombuildsstuff** [comment]
hi @EPilz 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
