### ISSUE TITLE
StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed"

### ISSUE THREAD

**Issue by VGzsysadm** [terraform-providers/terraform-provider-azurerm#9418]
Hi

I'm retrieving this error during the deploy of azurerm_virtual_machine
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.36.0

I can deploy this same image directly through portal azure. But the errorn throw if if try to use this image using terraform. We use francecentral as region ( there's no ES region ) the only thing that appears 'ES' is on billing/country region
Billing country/region
:
ES

Maybe this cause the error?

### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Affected Resource(s)

azurerm_virtual_machine

### Terraform Configuration Files

```hcl
variable "region" {
   description = "Region selected for deploy infrastructure"
   default = "francecentral"
}
storage_image_reference {
    publisher = "OpenLogic"
    offer     = "CentOS"
    sku       = "7.5"
    version   = "latest"
  }
plan {
    name = "7.5"
    publisher = "OpenLogic"
    product = "CentOS"
  }
```

### Debug Output

compute.VirtualMachinesClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="ResourcePurchaseValidationFailed" 
Message="User failed validation to purchase resources. Error message: 'The Publisher: 'OpenLogic' does not make available Offer: 'CentOS', Plan: '7.5' in your Subscription/Azure account’s region: 'ES'. Correlation Id: 'XXXXXXXXXXXXXXXXXXXX'.'"

### Expected Behaviour

Machine deployed

### Actual Behaviour

VM will not deploy

### Steps to Reproduce

1. `terraform apply`

**Comment by tombuildsstuff** [comment]
hi @VGzsysadm 

Thanks for opening this issue.

Taking a look through this appears to be a usage question rather than a bug in the Azure Provider, the `ES` being returned from the API is unrelated to the region where this is being deployed.

It's worth noting that the `azurerm_virtual_machine` resource has since been superseded by the `azurerm_linux_virtual_machine` and `azurerm_windows_virtual_machine` resources. Whilst the existing `azurerm_virtual_machine` resource continues to be available in 2.x releases of the Provider, it's feature-frozen and thus no longer receiving any bugfixes or enhancements to maintain compatibility.

As such I'm going to close this issue for the moment - but I'd recommend looking into the [`azurerm_linux_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/linux_virtual_machine.html) and [`azurerm_windows_virtual_machine`](https://www.terraform.io/docs/providers/azurerm/r/windows_virtual_machine.html) resources going forward. With regards to the usage question, this forum is intended to be used for Bug Reports and Feature Requests in the Azure Provider - but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
