### ISSUE TITLE
Support for Azurerm_app_service -> site_config -> Platform-settings -> HTTP Version (1.0/2.0)

### ISSUE THREAD

**Issue by roshanp85** [terraform-providers/terraform-provider-azurerm#9422]
I could not find a terraform settings for the attached image. Could you please guide us for the below, and if we don't have terraform configurations for this, can we create one, over the next Terraform provider. Please advise.

Go to App-service->Configuration->General Settings->HTTP Version

![image](https://user-images.githubusercontent.com/53309302/99998853-4f5bff80-2d8d-11eb-8960-c4a3b0c014e4.png)

**Comment by Jsoconno** [comment]
I am having this same issue.

**Comment by deaksa** [comment]
Use the http2_enabled property as described here:
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/app_service#http2_enabled

**Comment by roshanp85** [comment]
So we have to set http2_enabled to true ?

**Comment by tombuildsstuff** [comment]
hi @roshanp85 

Thanks for opening this issue.

Taking a look through here this appears to be a discussion around the Terraform Configuration necessary to use this functionality, rather than a Bug or Feature Request in the Azure Provider.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
