### ISSUE TITLE
Support for overriding the subscriptionID on individual resources/data sources

### ISSUE THREAD

**Issue by BrendanThompson** [terraform-providers/terraform-provider-azurerm#9428]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

As the provider stands today it is not possible to override the Subscription in which the resource(s) are being provisioned or referenced. Terraform Core offers the functionality of utilising Provider Aliases, this is capable of solving a lot of issues around this, however, not all.

There are many instances within large organisations where the executing identity has permissions scoped to a management group and is required to perform actions across numerous subscriptions. In this scenario using the functionality provided currently by Terraform Core an alias **must** be provisioned for each subscription, and then that alias must be applied to an additional resource/data source declaration. This means that there will inevitably be a lot of code duplication.

What I am proposing is allowing the ability to pass in a `subscription_id` onto resources/data sources that override what is configured within the provider block. As long as the executing identity has the required permissions to perform the desired actions this will work perfectly. An example of this is within the Google provider it allows you to configure the `project` on the provider block and then override that within any calls to resources/data sources.

Allowing this `subscription_id` to be passed into resources/data sources means that consumers would be able to use `for_each` loops on a resource declaration and have those resources deployed into seperate subscriptions. 

One place I see this as incredibly valuable is within the network stack. Adhering to Microsoft's recommended Hub & Spoke approach, I have single TFE workspace that controls the spoke networks for a given environment, this environment spans approximately 20 subscriptions. Currently this means I need to re-declare the same things numerous times, the override solves this.

The above is just one example of where this is useful for large enterprise clients.

I have created an implementation of this how I think it could work, it has been done only to the data source for `azurerm_storage_account`. I would really appreciate some feedback on this as an idea and the implementation.

### New or Affected Resource(s)

* azurerm_*

### Potential Terraform Configuration

```hcl
provider "azurerm" {
  subscription_id = "00000000-0000-0000-0000-000000000000"

  features = {}
}

data "azurerm_storage_account" "this" {
  name                = "blt0"
  resource_group_name = "RG-MEL-BLT-0"
}

data "azurerm_storage_account" "that" {
  name                = "blt1"
  resource_group_name = "RG-MEL-BLT-1"

  subscription_id = "11111111-1111-1111-1111-111111111111"
}
```

### References

* #9429

**Comment by hbuckle** [comment]
Can't you just create a second provider?

```hcl
provider "azurerm" {
  subscription_id = "00000000-0000-0000-0000-000000000000"
  features {}
}

provider "azurerm" {
  subscription_id = "00000000-0000-0000-0000-000000000001"
  alias           = "secondary"
  features {}
}

data "azurerm_storage_account" "that" {
  name                = "blt1"
  resource_group_name = "RG-MEL-BLT-1"
  provider            = azurerm.secondary
}
```

**Comment by dpbustos** [comment]
> Can't you just create a second provider?
> 
> ```terraform
> provider "azurerm" {
>   subscription_id = "00000000-0000-0000-0000-000000000000"
>   features {}
> }
> 
> provider "azurerm" {
>   subscription_id = "00000000-0000-0000-0000-000000000001"
>   alias           = "secondary"
>   features {}
> }
> 
> data "azurerm_storage_account" "that" {
>   name                = "blt1"
>   resource_group_name = "RG-MEL-BLT-1"
>   provider            = azurerm.secondary
> }
> ```

The simply answer for the outlined scenario is 'no'.

What if you wanted a single data source block using the `for_each` iterator that's able to run against multiple subscriptions in a management group?

Sure, you could add an additional block per subscription, but that creates a lot of code duplication and means the code has to be updated as new subscriptions are on-boarded (code which is fundamentally identical other than the subscription it targets).

**Comment by BrendanThompson** [comment]
@hbuckle thanks for your reply here. @dpbustos is correct it is not something that is feasible in all situations. This is also something I call out in my original description of the issue:

> In this scenario using the functionality provided currently by Terraform Core an alias must be provisioned for each subscription, and then that alias must be applied to an additional resource/data source declaration. This means that there will inevitably be a lot of code duplication.

Using something such as a subscription override is really the only way to solve this problem without having to use an external tool or function to build out template files, which would result in duplicate code anyway.

**Comment by BrendanThompson** [comment]
@tombuildsstuff just thought I'd follow up here 😄

**Comment by tombuildsstuff** [comment]
hi @BrendanThompson 

Thanks for opening this issue.

Taking a look through here ultimately this issue is trying to work around a lack of support for dynamically creating provider instances within Terraform Core, for example using `for_each` on a Provider block.

At this point in time the architecture of both the Azure Provider, and the SDK's which we use to interact with Azure (both Giovanni and the Azure SDK for Go) all assume that a single SDK Client is being used to interact with a specific subscription. Whilst it's possible to workaround that by constructing a Client instance on-demand (as you've done in #9429) - since this is ultimately a hack to workaround a limitation of Terraform Core, unfortunately this isn't something we plan to support within the Azure Provider at this time.

I believe this ultimately needs to be fixed in Terraform Core, so I'm going to suggest [opening a Feature Enhancement on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where, once ForEach/Dynamic Provider Initialization is supported this functionality should be supported across all providers including Azure.

Whilst I appreciate that doesn't help in the short term, it means that every Provider doesn't need to implement this workaround in every Resource (since once this is available on a single Data Source/Resource, users would expect this to become available on other Resources too) - until this functionality is available in Terraform Core, at which point we'd then need to deprecate/remove it.

Since this functionality ultimately needs to become available in Terraform Core, I'm going to close this issue for the moment - but as mentioned above I'd suggest [opening a Feature Enhancement on the Terraform Core repository](https://github.com/hashicorp/terraform/issues) where somebody from that team should be able to take a look.

Thanks!
