### ISSUE TITLE
know publishURL after create app_service

### ISSUE THREAD

**Issue by trotroyanas** [terraform-providers/terraform-provider-azurerm#9436]
how to get the url of the FTP/S of an app_service ?
for use for publish war file (for java app_service)

credential it's ok with azurerm_app_service.XXX.site_credential

I saw that apparently it is publishURL, but in terraform i have found no information for this ...

**Comment by tombuildsstuff** [comment]
hi @trotroyanas 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by trotroyanas** [comment]
Ok i'm sorry 
do you know a forum to ask questions about terraform via azurerm ?
