### ISSUE TITLE
`azurerm_postgresql_server`: update to new pricing schema

### ISSUE THREAD

**Issue by jambt** [terraform-providers/terraform-provider-azurerm#948]
Azure has converted to a new pricing schema for the Azure Database for PostgreSQL server (see [this blog post](https://azure.microsoft.com/en-us/blog/updates-to-azure-database-for-mysql-and-azure-database-for-postgresql/)).

Thus, the current method to deploy a server no longer reflects that pricing model.

### Terraform Configuration Files

This is the current block:
```hcl
resource "azurerm_postgresql_server" "test" {
  name                = "test-server"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    name = "PGSQLB50"
    tier = "Basic"
    capacity = 50
  }

  administrator_login = "psqladminun"
  administrator_login_password = "P@ssw0rd"
  version = "9.6"
  storage_mb = "51200"
  ssl_enforcement = "Enabled"
}
```

while the new schema would call for 

```hcl
resource "azurerm_postgresql_server" "test" {
  name                = "test-server"
  location            = "${azurerm_resource_group.test.location}"
  resource_group_name = "${azurerm_resource_group.test.name}"

  sku {
    name = "Gen4"
    tier = "Basic"
    vCore = 2
  }

  administrator_login = "psqladminun"
  administrator_login_password = "P@ssw0rd"
  version = "9.6"
  storage_mb = "5000"
  ssl_enforcement = "Enabled"
}
```
Note that smaller storage sizes are supported now.

**Comment by Andre-Freitas** [comment]
after the failed creation of postgresql trough terraform, i created them with az cli and tried to terraform import with no success.  After a few test i was able to confirm that the problem was in the api version used in azurerm (api-version=2017-04-30-preview). When making new request to REST API, using api-version=2017-12-01, i got the correct response

**Comment by tombuildsstuff** [comment]
hey @jambt @Andre-Freitas 

Thanks for opening this issue :)

Support for the new pricing schemas for both MySQL and Postgres is being tracked in #1004 - which I'm going to close this in favour of (rather than having multiple issues tracking the same thing); we're looking into this at the moment so this should be updated soon.

Thanks!
