### ISSUE TITLE
azurerm_sql_database - by default database is geo redundant and fails on azure policy

### ISSUE THREAD

**Issue by vinaynv26** [terraform-providers/terraform-provider-azurerm#9492]
Hi Team,
We are trying to spin up azure sql server and sql database from Terraform azurerm version 2.22.0
There is azure policy configured not to allow geo redundancy. On creating the database we are getting the error "SQL Database should avoid using GRS backup redundancy" . Would really be helpful if there is an alternative for this. Is there a way through terraform to set the "Backup storage redundancy".
[SQLDB_Policy1.txt](https://github.com/terraform-providers/terraform-provider-azurerm/files/5601438/SQLDB_Policy1.txt)

PFA the azure policy json and below is the error message.
Error: Error issuing create/update request for SQL Database "dbname" (Resource Group "rg-db-sql", Server "sqlserver001"): 
sql.DatabasesClient#CreateOrUpdate: Failure sending request: StatusCode=403 -- Original Error: Code="RequestDisallowedByPolicy" Message="Resource 
'dbname' was disallowed by policy. Policy identifiers: 

Thanks and Regards,
Vinay N V

**Comment by ruandersMSFT** [comment]
@vinaynv26 

The issue you reference is an [Azure Policy](https://docs.microsoft.com/en-us/azure/governance/policy/overview) enabled on your Azure Subscription, either to the subscription directly or through [Management Groups](https://docs.microsoft.com/en-us/azure/governance/management-groups/) (i.e. policy applied at a higher organizational level).  As you have noted, the [built in Azure Policy](https://docs.microsoft.com/en-us/azure/azure-sql/database/policy-reference) titled "[SQL Database should avoid using GRS backup redundancy](https://portal.azure.com/#blade/Microsoft_Azure_Policy/PolicyDetailBlade/definitionId/%2Fproviders%2FMicrosoft.Authorization%2FpolicyDefinitions%2Fb219b9cf-f672-4f96-9ab0-f5a3ac5e1c13)" is enabled preventing you from deploying an Azure SQL Database where the [_storageAccountType_ property](https://docs.microsoft.com/en-us/rest/api/sql/databases/createorupdate#storageaccounttype) is either LRS or ZRS (GRS not allowed).  GRS is the first (default) value of the _storageAccountType_ property, and since the AzureRM [azurerm_sql_database](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database) object doesn't provide control of the _storageAccountType_ property yet, the default value of GRS is utilized (which is then disallowed in your environment per Azure Policy).

Next steps should be for the _azurerm_sql_database_ object to add control of the _storageAccountType_ property so that you can specify either LRS or ZRS instead of GRS.

This needs to be implemented and then you would have to upgrade your AzureRM Provider from 2.22.0 to that new supported release to utilized this via Terraform.  Because this unspecified value is defaulting to GRS and cannot be defined/controlled via the AzureRM provider yet, consider performing initial deployment of your database via PowerShell, CLI or the Azure Portal and then [Import](https://www.terraform.io/docs/import/index.html) the object into your Terraform State.

**Comment by vinaynv26** [comment]
@ruandersMSFT : Thank you for the detailed information. Really appreciate. May I know the tentative plan or date or version when the azurerm_sql_database will have the property storageAccountType so we can set via Terraform.

**Comment by ruandersMSFT** [comment]
Development progression findings:

The StorageAccountType enum is not defined as part of the [2017-03-01-preview azure-sdk-for-go sql enum](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sql/mgmt/2017-03-01-preview/sql/enums.go); therefore, this property cannot be brought to the [azurerm_sql_database](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/sql_database) resource which utilizes 2017-03-01-preview.

The StoreageAccountType enum is defined as part of the [v3.0 azure-sdk-for-go sql enum](https://github.com/Azure/azure-sdk-for-go/blob/master/services/preview/sql/mgmt/v3.0/sql/enums.go); therefore, the StoreageAccountType argument can be added to the [azurerm_mssql_database](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database) resource which utilizes v3.0.

**Comment by vinaynv26** [comment]
@ruandersMSFT noted with thanks. so can please advice in which azurermversion the property StorageAccountType in azurerm_mssql_database is be added. Since observe this property is still not there in Terraform docs : https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/mssql_database

**Comment by Tenseiga** [comment]
@ruandersMSFT , any help on this. we are also facing the same issue.

**Comment by ruandersMSFT** [comment]
@tombuildsstuff What is the process for getting the [Azure SDK for Go](https://github.com/Azure/azure-sdk-for-go) version updated in the AzureRM Provider?  I can help fix this, but I need to have an updated version of the Azure SDK for Go referenced.

**Comment by ruandersMSFT** [comment]
Awaiting #10042 completion to be able to fix.

**Comment by Tenseiga** [comment]
@ruandersMSFT  good news az sdk for go has been updated..

**Comment by ruandersMSFT** [comment]
Looks like they just tagged v2.43.0, thus won't be included until v2.44.0
