### ISSUE TITLE
Cannot change osDisk.name, resource azurerm_virtual_machine should be destroyed an re-created

### ISSUE THREAD

**Issue by jnancel-claranet** [terraform-providers/terraform-provider-azurerm#956]
Hi there,

I'm trying to change the name of the `storage_os_disk` of my instance and plan says it'll only be an update in-place but it ends up as an error since it's not permitted to change it, even in the console. Consequently, I think it should be destroy/recreate when that change occurs.

### Terraform Version
Tested on 0.10.8 and 0.11.3

### Affected Resource(s)
azurerm_virtual_machine

### Terraform Configuration Files
```hcl
resource "azurerm_virtual_machine" "my_instance" {
...
  storage_os_disk {
    name              = "${var.custom_disk_name}"
    caching           = "ReadWrite"
    create_option     = "FromImage"
    managed_disk_type = "Standard_LRS"
  }
...
}
```

### Debug Output
Here is the result of plan and apply : 
https://gist.github.com/jnancel-claranet/c5f7f986d829214402c28fcb017e7437

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Change name attribute in `os_storage_disk` in `azurerm_virtual_machine`
2. `terraform plan`
3. `terraform apply`

**Comment by katbyte** [comment]
Hi @jnancel-claranet,

Thank you for discovering this issue and bringing it to our attention, it does indeed seem changing this property should force a new resource. 

A fix has been merged and will be released in 1.3.0 🙂

**Comment by katbyte** [comment]
Reverted as it having force new there causes new data disks to create a new resource. Will have to add a `CustomizeDiff` function to selectivity recreate the resource.

**Comment by tombuildsstuff** [comment]
hi @jnancel-claranet 

We're currently working on version 2.0 of the Azure Provider which we previously announced in #2807.

As a part of this we're introducing five new resources which will supersede the existing `azurerm_virtual_machine` and `azurerm_virtual_machine_scale_set` resources:

* `azurerm_linux_virtual_machine`
* `azurerm_linux_virtual_machine_scale_set`
* `azurerm_virtual_machine_scale_set_extension`
* `azurerm_windows_virtual_machine`
* `azurerm_windows_virtual_machine_scale_set`

We recently opened #5550 which adds support for the new Virtual Machine resources - and I'm able to confirm that this is fixed in the new Virtual Machine resources - however unfortunately we have no plans to backport this to the existing `azurerm_virtual_machine` resource.

In order to get feedback on these new resources we'll be launching support for these new resources as an opt-in Beta in an upcoming 1.x release of the Azure Provider and ultimately release these as "GA" in the upcoming 2.0 release. We'll post an update in #2807 when both the opt-in Beta (1.x) & GA (2.0) are available - as such I'd recommend subscribing to that issue for updates.

This issue's been assigned to the milestone "2.0" since this is where this will ship - however (due to the way that closing Github Issues from PR's works, to be able to track this back for future users) this issue will be closed once the first of the new resources have been merged.

Thanks!
