### ISSUE TITLE
azurerm_monitor_autoscale_setting: Recurrence, frequency not expected. 2.38.0

### ISSUE THREAD

**Issue by BradPoq** [terraform-providers/terraform-provider-azurerm#9572]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform v0.13.5
+ provider registry.terraform.io/hashicorp/azurerm v2.38.0

### Affected Resource(s)

* `azurerm_monitor_autoscale_settings`

### Terraform Configuration Files

```hcl
recurrence {
      frequency = "Week"
      timezone = "UTC"
      days     = ["Monday", "Tuesday", "Wednesday", "Thursday", "Friday", "Saturday", "Sunday"]
      hours    = [0]
      minutes  = [0]
    }
```

### Debug Output
https://gist.github.com/BradPoq/cf8d2d5871bdf5c3999e54e87c4b4b7f

### Expected Behaviour
Should add a weekly recurrence.

### Actual Behaviour
Errors.

### Steps to Reproduce

1. `terraform plan`

**Comment by tombuildsstuff** [comment]
hi @BradPoq 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by BradPoq** [comment]
Hi @tombuildsstuff 

This is a bug as on the documentation (https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/monitor_autoscale_setting) it states that this is a feature and using the newest version of the provider the feature is non-existent/not working.

Hope you can re-open this as a Bug/Issue.

Thanks!
