### ISSUE TITLE
Virtual Hub Express Route Connection with Express Route circuit

### ISSUE THREAD

**Issue by asichaib** [terraform-providers/terraform-provider-azurerm#9596]
Hello,

I'm trying to connect a virtual hub Express route gateway with a circuit but didn't find the resource to achieve it in terraform. I used the "azurerm_virtual_network_gateway_connection" but doesn't seem to work. 

module.tdf_az_virtual_network_gateway_connection_module.azurerm_virtual_network_gateway_connection.XXXXX: Creating...      
Error: Error Creating/Updating AzureRM Virtual Network Gateway Connection "XXXXX" (Resource Group "XXXX"): network.VirtualNetworkGatewayConnectionsClient#CreateOrUpdate: Failure sending request: StatusCode=400 -- Original Error: Code="InvalidRequestFormat" Message="Cannot parse the request." Details=[{"code":"InvalidJsonReferenceWrongType","message":"Reference Id /subscriptions/XXXXXXXXXXXXXXXXXXXXXXXX/resourceGroups/XXXXX/providers/Microsoft.Network/expressRouteGateways/XXXXXXis referencing resource of a wrong type. The Id is expected to reference resources of type virtualNetworkGateways. Path properties.virtualNetworkGateway1."}]

Could anyone help on this ? 
Thanks in advance

**Comment by tombuildsstuff** [comment]
hi @asichaib 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding Terraform Configuration, this forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
