### ISSUE TITLE
Add identity MSI SystemAssigned to azurerm_recovery_services_vault

### ISSUE THREAD

**Issue by LaurentLesle** [terraform-providers/terraform-provider-azurerm#9619]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Managed identity identity is required to enable private endpoint to ASR
Require also the identity to be exported.

### New or Affected Resource(s)

* azurerm_recovery_services_vault

### Potential Terraform Configuration

```hcl
resource "azurerm_recovery_services_vault" "vault" {
  name                = "example_recovery_vault"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  sku                 = "Standard"

 identity {
  type = "SystemAssigned"
 }
  soft_delete_enabled = true
}
```

### References

* #0000

**Comment by LaurentLesle** [comment]
Do you know if it is possible to fast track this new feature?

**Comment by timlharrison** [comment]
+1

**Comment by favoretti** [comment]
@LaurentLesle kinda fast-tracked :)

**Comment by aharden** [comment]
I'm trying to migrate an AzureRM template definition of a Recovery Services vault to this updated resource in the new provider since, like the original reporter, I need to allocate a system-managed identity to use the vault with private endpoints.  The documentation doesn't list `identity` as an exported attribute, and my initial attempts to use that attribute are telling me that it's a list of maps, whereas I believe it should just be a string corresponding to the object ID (as reported in the Azure Portal).  Based on the commit that added this feature, I'm trying to access that using azurerm_recovery_services_vault.vault.identity[0].principal_id.  We'll see how that goes.
