### ISSUE TITLE
Enable "Bypass Firewall for Azure Trusted Services" option for Cosmosdb and EventHub

### ISSUE THREAD

**Issue by vsabella** [terraform-providers/terraform-provider-azurerm#9623]
It currently doesn't seem to be possible, via  Terraform, to set the Bypass Firewall for Azure Trusted Services in EventHub Firewall or CosmosDB Firewall

It is possible for Azure Keyvault

![image](https://user-images.githubusercontent.com/2106153/100863619-673b2e00-34c7-11eb-9554-2ffe3bf11b85.png)

**Comment by tombuildsstuff** [comment]
hi @vsabella 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by vsabella** [comment]
@tombuildsstuff  This isn't a question. It's a bug in the Azure Provider. The Terraform does not give the ability to set that setting.

For example Azure Keyvault gives you this configuration for network_acls:

```terraform
  network_acls {
    default_action = "Deny"
    bypass         = "AzureServices"
  }
```

However the EventHub and CosmosDB use different terraform configuration to configure the firewall that does not give the ability to set the bypass to AzureServices.

Despite EventHub, CosmosDB, and other features having the same Firewall configuration capabilities, they are expressed differently in the AzureRM Terraform provider and thus there is no feature parity.

(network_rulesets): https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/eventhub_namespace
