### ISSUE TITLE
How can I pass values for Custom Azure APIPA BGP IP address in azurerm_virtual_network_gateway

### ISSUE THREAD

**Issue by imrannayer** [terraform-providers/terraform-provider-azurerm#9630]
Issues on GitHub are intended to be related to bugs or feature requests with provider codebase,
so we recommend using our other community resources instead of asking here 👍.

---

If you have a support request or question please submit them to one of these resources:

* [HashiCorp Community Forums](https://discuss.hashicorp.com/c/terraform-providers)
* [HashiCorp support](https://support.hashicorp.com) (Terraform Enterprise customers)

`bgp_settings` block in `azurerm_virtual_network_gateway` sets value "Default Azure BGP peer IP address". I cant find fiedl which will polupate "Custom Azure APIPA BGP IP address". 

```
resource "azurerm_virtual_network_gateway" "vnet_gw" {
  name                = "${var.prefix}-vnet-gw"
  location            = azurerm_resource_group.rg.location
  resource_group_name = azurerm_resource_group.rg.name
  type                = "Vpn"
  sku                 = "VpnGw1"
  vpn_type            = "RouteBased"
  enable_bgp          = true

  bgp_settings {
    asn             = 65515
    peering_address = var.bgp_azure_interface_ip_0
  }
  ip_configuration {
    name                          = "${var.prefix}-vnetGatewayConfig"
    public_ip_address_id          = azurerm_public_ip.gw_public_ip.id
    private_ip_address_allocation = "Dynamic"
    subnet_id                     = azurerm_subnet.gw_subnet.id
  }
  tags = var.labels
}

```

**Comment by tombuildsstuff** [comment]
hi @imrannayer 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by imrannayer** [comment]
Did some research and found that APIPA is a new feature in Azure. Is it possible to change this question into feature request? This feature is needed to connect Azure von gateway to aws and GCP.
