### ISSUE TITLE
Support for azurerm_sql_server

### ISSUE THREAD

**Issue by x264243** [terraform-providers/terraform-provider-azurerm#9687]
### Description

The properties **ssl_minimal_tls_version_enforced**  and **public_network_access_enabled** are included in the azurerm_mysql_server module and you need to know if it is intended for the module **azurerm_sql_server**.

### New or Affected Resource(s)

azurerm_sql_server

### Potential Terraform Configuration

Properties:
   
ssl_minimal_tls_version_enforced   
public_network_access_enabled

**Comment by tombuildsstuff** [comment]
hi @x264243 

Thanks for opening this issue :)

Taking a look through here support for this is available via the `azurerm_mssql_server` resource which supersedes the `azurerm_sql_resource` - would you be able to take a look and see if that works for you? Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!

**Comment by x264243** [comment]
Thanks @tombuildsstuff but we need use de module azurerm_sql_resource.

Thanks in advance
