### ISSUE TITLE
Terraform Azure Site Recovery

### ISSUE THREAD

**Issue by minneapolis29** [terraform-providers/terraform-provider-azurerm#971]
Hello Guys,
quick question: anybody used terraform with ASR vault creation and such?
Thanks again.

**Comment by tombuildsstuff** [comment]
hey @minneapolis29 

Thanks for opening this issue :)

Recovery Service Vaults aren't natively supported at this time (although, there's a feature request being tracked in https://github.com/terraform-providers/terraform-provider-azurerm/issues/576) - and as such it's only currently possible to deploy these [using an ARM Template via the `azurerm_template_deployment` resource](https://www.terraform.io/docs/providers/azurerm/r/template_deployment.html). Rather than have multiple feature requests for the same thing - I'm going to close this in favour of https://github.com/terraform-providers/terraform-provider-azurerm/issues/576

Thanks!
