### ISSUE TITLE
Adding field OnErrorDeployment enables creating a deployment that will redeploy another deployment on failure for azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by neil-yechenwei** [terraform-providers/terraform-provider-azurerm#9718]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description
Currently `azurerm_resource_group_template_deployment` doesn't support to create a deployment that will redeploy another deployment on failure. So we have to add this property `OnErrorDeployment` to support this scenario.

### New or Affected Resource(s)

* azurerm_resource_group_template_deployment

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group_template_deployment" "example" {
  name                = "acctest-UpdatedDeployment-example"
  resource_group_name = azurerm_resource_group.example.name
  deployment_mode     = "Complete"
  on_error_deployment {
    type = "LastSuccessful"
  }

  template_content = <<TEMPLATE
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {},
  "variables": {},
  "resources": []
}
TEMPLATE

  depends_on = [azurerm_resource_group_template_deployment.example2]
}
```

### References

The link of this new property: https://github.com/Azure/azure-rest-api-specs/blob/1c100daabed6a008c76f3e4e0cae4e7eac5a5bf4/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L5107

**Comment by tombuildsstuff** [comment]
👋 

On reflection the `on error deployment` field doesn't really make sense in Terraform, should this template deployment fail then Terraform will highlight this error and they can opt how to proceed - this property will just result in another diff (and longer-term an error since the result didn't match the apply) - which just hides this error and doesn't make much sense in Terraform. As such I'm going to close this issue for the moment, since this field doesn't appear to make sense in Terraform in it's current state.

Thanks!
