### ISSUE TITLE
Adding field ParametersLink enables creating a deployment with template content and parameters file for azurerm_resource_group_template_deployment

### ISSUE THREAD

**Issue by neil-yechenwei** [terraform-providers/terraform-provider-azurerm#9719]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `azurerm_resource_group_template_deployment` only supports to create a deployment using template content and parameters content. But it doesn't support to create a deployment using template content and parameters file. So we have to add field `ParametersLink` to support this scenario.

### New or Affected Resource(s)

* azurerm_resource_group_template_deployment

### Potential Terraform Configuration

```hcl
resource "azurerm_resource_group_template_deployment" "example" {
  name                = "acctest-UpdatedDeployment-example"
  resource_group_name = azurerm_resource_group.example.name
  deployment_mode     = "Complete"
  template_content = <<TEMPLATE
{
  "$schema": "https://schema.management.azure.com/schemas/2015-01-01/deploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "rgName": {
      "type": "String",
      "metadata": {
        "description": "Test Description"
      }
    }
  },
  "variables": {},
  "resources": [
    {
      "type": "Microsoft.Network/publicIPAddresses",
      "apiVersion": "2015-06-15",
      "name": "[parameters('rgName')]",
      "location": "[resourceGroup().location]",
      "properties": {
        "publicIPAllocationMethod": "Dynamic"
      }
    }
  ]
}
TEMPLATE

  parameters_link {
    uri             = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/subscription-deployments/create-rg/azuredeploy.parameters.json"
    content_version = "1.0.0.0"
  }
}
```

### References

The link of new property ParametersLink: https://github.com/Azure/azure-rest-api-specs/blob/1c100daabed6a008c76f3e4e0cae4e7eac5a5bf4/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L4426

**Comment by tombuildsstuff** [comment]
👋 

Chatting about this internally we've come the conclusion that whilst there's some benefits to sourcing the Template Body from a URI (e.g. Template Spec / reusing the templates themselves) - the Parameters themselves are likely to vary per deployment. As such whilst we could seek to source these Parameters from a URI, since these could contain sensitive information, and are unlikely to be reused across deployments - on reflection there's more potential downsides to sourcing these from a URI) than upsides for supporting this field, and so we don't believe this field makes sense in Terraform at this time.

Specifically regarding the `Content Version` field - I can't recall seeing an example where this isn't `1.0.0.0` (similar to the Template Content Version) - as such I think we could avoid exposing that until a valid use-case was surfaced. Instead were we to expose this functionality we could likely make this a top-level field for `parameters_uri`, avoiding the need for the nested block.

As we don't believe it makes sense to expose this field in Terraform at this time, I'm going to close this issue for the moment - however should there be a compelling use-case to add this field in the future we can take another look.

Thanks!
