### ISSUE TITLE
Adding field ParametersLink enables creating a deployment with parameters file for azurerm_subscription_template_deployment

### ISSUE THREAD

**Issue by neil-yechenwei** [terraform-providers/terraform-provider-azurerm#9721]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Currently `azurerm_subscription_template_deployment` only supports to create a deployment using template_content and parameters_content. But it doesn't support to create a deployment using template_content and `parameters file`. So we have to add field `ParametersLink` to support this scenario.
### New or Affected Resource(s)

* azurerm_subscription_template_deployment

### Potential Terraform Configuration

```hcl
resource "azurerm_subscription_template_deployment" "test" {
  name             = "acctest-SubDeploy-test"
  location         = "West Europe"

  template_content = <<TEMPLATE
{
  "$schema": "https://schema.management.azure.com/schemas/2018-05-01/subscriptionDeploymentTemplate.json#",
  "contentVersion": "1.0.0.0",
  "parameters": {
    "rgName": {
      "type": "String",
      "metadata": {
        "description": "Name of the resourceGroup to create"
      }
    }
  },
  "resources": [
    {
      "type": "Microsoft.Resources/resourceGroups",
      "apiVersion": "2020-06-01",
      "name": "[parameters('rgName')]",
      "location": "West Europe",
      "tags": {
        "Note": "subscription level deployment"
      },
      "properties": {}
    }
  ]
}
TEMPLATE

  parameters_link {
    uri = "https://raw.githubusercontent.com/Azure/azure-quickstart-templates/master/subscription-deployments/create-rg/azuredeploy.parameters.json"
   content_version = "1.0.0.0"
  }
}
```

### References

The link of new property ParametersLink: https://github.com/Azure/azure-rest-api-specs/blob/1c100daabed6a008c76f3e4e0cae4e7eac5a5bf4/specification/resources/resource-manager/Microsoft.Resources/stable/2020-06-01/resources.json#L4426

**Comment by tombuildsstuff** [comment]
hi @neil-yechenwei 

Similar to #9719 - after chatting about this internally we believe there's more downsides than upsides to supporting sourcing content from a URI at this time, since these variables are unlikely to be reused across deployments and may contain sensitive variables (which would have to be available at a publically available URI).

As such whilst I'd like to thank you for opening this issue - at this point in time we don't plan to support the `parameters_link` field within the `azurerm_subscription_template_deployment` resource and as such I'm going to close this issue for the moment - however should a compelling use-case become available we can take another look.

Thanks!
