### ISSUE TITLE
Support for HashiCorp Consul Service on Azure

### ISSUE THREAD

**Issue by tbugfinder** [terraform-providers/terraform-provider-azurerm#9731]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

Few weeks ago HashiCorp Consul Service on Azure was released.
I'd like to provision HCS using a ready to use resource within my environment.
https://www.hashicorp.com/products/consul/service-on-azure 

### New or Affected Resource(s)

* new resource needed

### Potential Terraform Configuration

```hcl
new code needed
```

### References

https://www.hashicorp.com/products/consul/service-on-azure

* N/A

**Comment by Lucretius** [comment]
You can actually already create this with the `azurerm_managed_application` resource (I spun this exact service up for my team using it).  For the parameters of the actual managed application (i.e. `numServers`), I just spun up the service manually first.  Then, just go to the "Parameters and Outputs" section, and add those to the `parameters` block.  For the plan properties, after you make the service manually just use the Azure CLI to look up the necessary plan values.  Then you can tear down the manual one and make the same resource programmatically.

**Comment by tbugfinder** [comment]
Hi @Lucretius ,
sounds like I didn't properly research before opening this issue.
I haven't used the resource you're referring to before. There's even a prebuilt module for HCS on Azure https://registry.terraform.io/modules/cpu601/hcs/azurerm/latest ( ref https://link.medium.com/ad1tmnSY1bb ).

Thank you !

**Comment by tombuildsstuff** [comment]
hey @tbugfinder 

Thanks for opening this issue / apologies for the delayed response here.

As @Lucretius has mentioned it's possible to deploy HCS either using an `azurerm_managed_application` (for example, using the module above) - or via [the new `hashicorp/hcs` Terraform Provider](https://registry.terraform.io/providers/hashicorp/hcs/latest/docs/resources/cluster) which was released recently

Since support for this is available the new `hashicorp/hcs` provider, I'm going to close this issue for the moment - but should you have further questions I'd point you towards [the community discuss forum](https://discuss.hashicorp.com).

Thanks!
