### ISSUE TITLE
How to use terraform validate for modules

### ISSUE THREAD

**Issue by bcochofel** [terraform-providers/terraform-provider-azurerm#9761]
How can I run `terraform validate` on modules?

I have the block

```
terraform {
  required_providers {
    azurerm = {
      source  = "hashicorp/azurerm"
      version = "~> 2.30.0"
    }
  }

  required_version = ">= 0.13.0"
}
```

on my modules but whenever I run `terraform validate` I get the following issue:

```
Error: "features": required field is not set
```

**Comment by tombuildsstuff** [comment]
hi @bcochofel 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
