### ISSUE TITLE
Update Network Connectivity in azurerm_managed_disk

### ISSUE THREAD

**Issue by x264243** [terraform-providers/terraform-provider-azurerm#9777]
We need to update by terraform the Connectivity Method property in the azurerm_managed_disk module. 

Is there any property for it? I can't find any that fit in the documentation.

![image](https://user-images.githubusercontent.com/75305828/101612521-05208280-3a0b-11eb-847d-68419032f8ae.png)

**Comment by tombuildsstuff** [comment]
hi @x264243 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

In this instance it appears the Azure Provider doesn't support this functionality, as such I'd suggest opening [a Feature Request, which contains all of the information we need](https://github.com/terraform-providers/terraform-provider-azurerm/issues/new?template=Feature_Request.md&title=Support+for+%5Bthing%5D) in order for someone to take a look at this at some point - however since this is a question however I'm going to close this issue for the moment.

Thanks!
