### ISSUE TITLE
azurerm_managed_disk

### ISSUE THREAD

**Issue by x264243** [terraform-providers/terraform-provider-azurerm#9782]
I would need to know if it is possible to modify the Connectivity Method in the azurerm_managed_disk module.

Attached screenshot of what we want to update via terraform. 

![image](https://user-images.githubusercontent.com/75305828/101645890-2b5c1780-3a37-11eb-89a1-db061d324511.png)

It's possible?

Thanks in advance.

**Comment by tombuildsstuff** [comment]
hi @x264243 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
