### ISSUE TITLE
Azure Backend Blob Should Be Deleted when removing backend

### ISSUE THREAD

**Issue by berney** [terraform-providers/terraform-provider-azurerm#979]
When you use the azurerm backend it creates a blob in a container in a storage account. When you remove the backend and re-run `terraform init` it will offer to pull the remote state local. However it does not delete the remote container/blob, and I cannot find a command or option to make it do this. The remote container/blob needs to be removed manually using other tools like Azure CLI. I'd like either re-init to offer to remove it (or just remove it), or a command or argument or similar to have terraform clean up after itself.

Terraform did not work the way I expected, so this is more of a feature request than a bug.

### Terraform Version
Terraform v0.11.3

### Affected Resource(s)
Please list the resources as a list, for example:
- terraform.backend

### Terraform Configuration Files
```hcl
terraform {
    backend "azurerm" {
        storage_account_name = "storage"
        container_name       = "container"
        key                  = "key"
        resource_group_name  = "rg"
    }
}
```

### Expected Behavior
Terraform should delete the blob it created

### Actual Behavior
blob "key" under container "container" under storage account "storage" still exists.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. configure the azurerm backend
2. `terraform init`
3. remove the azurerm backend config
4. `terraform init`

### References

Re-reading the documentation it doesn't state it will delete the backend.
https://www.terraform.io/docs/backends/config.html#unconfiguring-a-backend

**Comment by kjhosein** [comment]
FWIW, I'd rather the `azurerm` provider *not* automatically remove the blob of the state file.
Agreed about offering to delete it though!

**Comment by tombuildsstuff** [comment]
hi @berney 

Thanks for opening this issue - apologies for the delayed response here!

Taking a look into this this is a feature request for Terraform Core (since this is a behavioural feature request for Backends in general, which is handled by Core). As such I believe this feature request belongs [on that repository](https://github.com/hashicorp/terraform) - would you be able to migrate this across to that repository? (Whilst I can do this for you, you won't be subscribed to the new issue for updates unfortunately - but I can if you'd like 😄)

Since this feature request is for Terraform Core rather than something we can implement in the AzureRM Provider - I'm going to close this issue for the moment.

Thanks!
