### ISSUE TITLE
Error creating Application Insights

### ISSUE THREAD

**Issue by cloudhubzawsaz** [terraform-providers/terraform-provider-azurerm#9791]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version
Terraform version 0.13.5
Terraform azure rm provider version  "2.20.0"

### Affected Resource(s)

* `azurerm_application_insights`
* `azurerm_app_service`

### Terraform Configuration Files

```hcl
resource "azurerm_application_insights" "project" {
  name                = var.projectappinsights
  location            = var.location
  resource_group_name = var.rg
  application_type    = "java"
  disable_ip_masking  = "true"
}

  resource "azurerm_app_service" "project" {
  name                    = var.app_service_name_backend
  location                = var.location
  resource_group_name     = var.rg
  app_service_plan_id     = azurerm_app_service_plan.project.id
  https_only              = true
  client_affinity_enabled = true
  app_settings = {
    always_on                        = true
    "APPINSIGHTS_INSTRUMENTATIONKEY" = azurerm_application_insights.project.instrumentation_key
  }
```

Terraform should have enabled app insights for the app service.

Terraform failed with error
Error: Error creating Application Insights "" (Resource Group "Project"): insights.ComponentsClient#CreateOrUpdate: Failure responding to request: StatusCode=400 -- Original Error: autorest/azure: Service returned an error. Status=400 Code="UnsupportedResourceOperation" Message="The resource type 'components' does not support this operation."

1. `terraform apply`

### Important Factoids

NA -Standard deployment

**Comment by tombuildsstuff** [comment]
hi @cloudhubzawsaz 

Thanks for opening this issue.

Taking a look through here this appears to be an issue with the Terraform Configuration, looking at the error message above the name is empty: `Error creating Application Insights "" (Resource Group "Project")`, meaning presumably the variable `var.projectappinsights` has an empty value? Since this appears to be an issue with the Terraform Configuration being used I'm going to close this issue for the moment, but should that not work please let us know and we'll take another look.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
