### ISSUE TITLE
active-directory server not promoting

### ISSUE THREAD

**Issue by kendrickcc** [terraform-providers/terraform-provider-azurerm#984]
Hi there,

Thank you for opening an issue. Please note that we try to keep the Terraform issue tracker reserved for bug reports and feature requests. For general usage questions, please see: https://www.terraform.io/community.html.

### Terraform Version
Terraform v0.11.3
+ provider.azurerm v1.1.2

### Expected Behavior
What should have happened? Active Directory promotion to create first forest.

### Actual Behavior
What actually happened? AD DS installs, but forest is not established. 

### Important Factoids
Are there anything atypical about your accounts that we should know? Running Azure against a usgovvirginia location.

**Comment by nbering** [comment]
Your report is a little vague... do you think you could provide some details about the configuration? Preferably filtered down to the problematic area?

Since you're talking about Active Directory (the Windows Service), and not Azure AD (the cloud service), I presume this is for a Virtual Machine. I mostly work with Linux VMs, so I'm not much help to you, but I'm pretty sure there's not enough here for someone who could help to start out with.

**Comment by tombuildsstuff** [comment]
hi @kendrickcc 

Thanks for opening this issue

As @nbering has requested - would it be possible for you to show us the configuration you're using? I believe this is an issue either with the Terraform Configuration being used or an Azure issue, rather than something specific to Terraform; as such I'm going to close this issue for the moment.

Thanks!

**Comment by kendrickcc** [comment]
I gather I need to open a new issue with more information?

**Comment by kendrickcc** [comment]
new issue opened.
