### ISSUE TITLE
link application insight with logs analytics workspace ?

### ISSUE THREAD

**Issue by trotroyanas** [terraform-providers/terraform-provider-azurerm#9867]
hi,
i don't found this option in azureRM terraform provider.
https://docs.microsoft.com/fr-fr/azure/azure-monitor/app/create-workspace-resource

i search to link logs analytics workspace with application insigth.

this option exist in terraform ?

this option exist in web interface when i add application insight
![image](https://user-images.githubusercontent.com/4205983/102194676-e2381780-3ebd-11eb-93b6-9dc17a51790c.png)

**Comment by tombuildsstuff** [comment]
hi @trotroyanas 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by trotroyanas** [comment]
ok sorry thank's
