### ISSUE TITLE
Error when trying to create more than one Azure Application Insights API Key

### ISSUE THREAD

**Issue by scp-mb** [terraform-providers/terraform-provider-azurerm#9877]
Seeing the same problem as the following issue, would prefer that one to be reopened and this closed if necessary:

https://github.com/terraform-providers/terraform-provider-azurerm/issues/8472

**Comment by tombuildsstuff** [comment]
hi @scp-mb 

Thanks for opening this issue.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!

**Comment by scp-mb** [comment]
@tombuildsstuff This is not a question. It's a valid, outstanding bug that has been closed automatically but is still relevant.
