### ISSUE TITLE
InvalidParameter Error when turning azurerm_shared_image_version into azurerm_managed_disk

### ISSUE THREAD

**Issue by Robzzson** [terraform-providers/terraform-provider-azurerm#9880]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

- Terraform v0.14.2
- azurerm v2.40.0

### Affected Resource(s)

* `azurerm_managed_disk`

### Terraform Configuration Files

```hcl
resource "azurerm_managed_disk" "example" {
  name                 = "abm-disk"
  location             = azurerm_resource_group.example.location
  resource_group_name  = azurerm_resource_group.example.name
  storage_account_type = "Standard_LRS"
  create_option        = "FromImage"
  image_reference_id   = azurerm_shared_image_version.example.id
}
```

### Debug Output

[Debug Output Gist](https://gist.github.com/Robzzson/792a070452828d4a2d77b705ece287d3)

### Expected Behaviour

Managed disk should've been created on Azure.

### Actual Behaviour

`terraform apply` of given resource fails with InvalidParameter Error, but what I understand is that one can create *managed disk* out of *shared image version* when using [FromImage](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/managed_disk#FromImage) create option.

Moreover I'm able to create *managed disk* with `az`:<br>
`az disk create --resource-group AppSource-sandbox --location northeurope --name test-disk --gallery-image-reference /subscriptions/<subscription_id>/resourceGroups/AppSource-sandbox/providers/Microsoft.Compute/galleries/image_gallery/images/shared-abm-image/versions/1.0.0`

P.S. This is my *shared image version* resource:

```hcl
resource "azurerm_shared_image_version" "example" {
  name                = "1.0.0"
  gallery_name        = azurerm_shared_image.example.gallery_name
  image_name          = azurerm_shared_image.example.name
  resource_group_name = azurerm_shared_image.example.resource_group_name
  location            = azurerm_shared_image.example.location
  managed_image_id    = data.azurerm_image.packer-image.id

  target_region {
    name                   = azurerm_shared_image.example.location
    regional_replica_count = 2
    storage_account_type   = "Standard_LRS"
  }
}
```

**Comment by EAS-Rhys** [comment]
Just came across this issue myself today too, from a bit of research people are reporting it is to do with the Azure API version being used.

https://social.technet.microsoft.com/Forums/ie/en-US/88bd9ca8-0e35-46f2-888c-3df05000cfb4/azure-arm-deployment-vm-creation-from-shared-image-gallery-image-errors?forum=iaas

**Comment by Robzzson** [comment]
> Just came across this issue myself today too, from a bit of research people are reporting it is to do with the Azure API version being used.
> 
> https://social.technet.microsoft.com/Forums/ie/en-US/88bd9ca8-0e35-46f2-888c-3df05000cfb4/azure-arm-deployment-vm-creation-from-shared-image-gallery-image-errors?forum=iaas

Interesting point. Unfortunately Azure API version is hard-coded into the `azurerm` provider code and therefore cannot be changed. From skimming the debug output it turns out that `azurerm v2.40.0` uses API version *2020-05-01*.

**Comment by tombuildsstuff** [comment]
hi @Robzzson 

Thanks for opening this issue.

Unfortunately Azure overloads the term "image" multiple times, there's an "Image" (which is a snapshot of a Virtual Machine) and a "Shared Image" (which is a reusable version of said image, housed inside a Shared Image Gallery). In this instance the `FromImage` value for this refers to an `azurerm_image` rather than an `azurerm_shared_image` or `azurerm_shared_image_version` - which is why this is returning a ParameterError from the Azure API here.

Within Terraform we're gradually working through the Provider adding more specific validation for resources to try and make this clearer - however there's no timeframe for this to be completed across all resources, as such I believe that this'd be caught at `terraform plan` time in the future - and as such I'm going to close this issue for the moment.

A Shared Image (Version) can be provisioned using a Virtual Machine onto a new OS Disk - my understanding is that it's not possible to do this without provisioning a Virtual Machine ahead of time. That said, it should be possible to use a tool [like Packer](https://packer.io) to provision a Virtual Machine using this Shared Image (Version) and capture this OS Disk should you need to do so.

Since this is a question regarding usage, rather than a bug in the Azure Provider - I'm going to close this issue for the moment - but should you have further questions I'd point you towards [the community forum](https://discuss.hashicorp.com) where someone should be able to assist further.

Thanks!

**Comment by Robzzson** [comment]
Dear @tombuildsstuff 

Thank you for your explanation.

Lemme express one more thing before we close this issue. I did a little more research and stumbled upon [this article](https://arsenvlad.medium.com/creating-vhd-azure-blob-sas-url-from-azure-managed-image-2be0e7c287f4) (see "Create Azure Managed Disk from Shared Image Gallery" section of the article), where the author is doing a very similar thing to mine. There's even an [author's comment](https://arsenvlad.medium.com/hi-yes-absolutely-you-can-easily-create-sas-from-a-managed-disk-using-az-disk-grant-access-ec0fbb052c2e) suggesting that the conversion `shared image version -> OS disk` is indeed possible without spinning up entirely new VM. This is by the way what I showcased in my initial comment when using `az disk create ...`. Having said that, wouldn't this issue turn into feature request, where such a conversion using Terraform is possible?

**Comment by tombuildsstuff** [comment]
@Robzzson it's possible that we could expose a new field to support this use-case specifically - feel free to open a new Feature Request if your looking for support for that :)

**Comment by EAS-Rhys** [comment]
@Robbzzson please can you mention me on that, would be happy to raise a PR
for it

**Comment by Robzzson** [comment]
@EAS-Rhys I'm just creating a feature request and I'll mention you as soon as I submit.
