### ISSUE TITLE
azurerm_resource_group_template_deployment what-if

### ISSUE THREAD

**Issue by matt-garner-nw** [terraform-providers/terraform-provider-azurerm#9907]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

When doing a "terrraform plan" on the resource "azurerm_resource_group_template_deployment", it uses the what-if API to show what will change once deployed. 

https://docs.microsoft.com/en-us/rest/api/resources/deployments/whatif

### New or Affected Resource(s)

azurerm_resource_group_template_deployment
https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/resource_group_template_deployment

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @matt-garner-nw 

Thanks for opening this issue.

At this time Terraform's Plan functionality diffs only based on the properties between the state (which gets refreshed/updated with the latest values form the API) and the Terraform Configuration on disk, unfortunately there's no "hooks" to integrate with an external tool, such as this API - meaning this'd require some (fairly large) structural changes within Terraform Core to accomplish.

Based on what we can see at this point in time the `What-If` functionality within the API appears to be fairly rudimentary, diffing the objects rather than the meaning of the diff, for example if you're defining a virtual network and subnets as two resources with an ARM Template then the What-If functionality incorrectly identifies all of the Subnets as being removed rather than an empty diff.

Since this'd be a not-insignificant amount of changes to the way that Terraform works and given the false-positives returned from the API here (which'd end up affecting other resources should something be unintentionally marked as being recreated) - so to be honest I don't think this is something we'd look to integrate with at this time.

As such whilst I'd like to thank you for opening this issue, since I don't believe this is something we're going to support integrating with anytime soon I'm going to close this issue for the moment.

Thanks!
