### ISSUE TITLE
Support for [Terraform modules for Azure NetApp Files]

### ISSUE THREAD

**Issue by y-halim** [terraform-providers/terraform-provider-azurerm#9942]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Description

There are no Terraform modules for Azure NetApp Files. They are important for uses needs them to switch to Production mode with the implementation of a Dev and QA environment.
### New or Affected Resource(s)

* azurerm_netapp

### Potential Terraform Configuration

```hcl
# Copy-paste your Terraform configurations here - for large Terraform configs,
# please use a service like Dropbox and share a link to the ZIP file. For
# security, you can also encrypt the files using our GPG public key.
```

### References

* #0000

**Comment by tombuildsstuff** [comment]
hi @y-halim 

Thanks for opening this issue :)

Taking a look through here it appears that support for NetApp is available via [the `azurerm_netapp_*` resources](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/netapp_account) - would you be able to take a look and see if that works for you?Since this functionality appears to be supported I'm going to close this issue for the moment - however please let us know if that doesn't work for you and we'll take another look.

Thanks!
