### ISSUE TITLE
http_application_routing always tries to change to null

### ISSUE THREAD

**Issue by flmmartins** [terraform-providers/terraform-provider-azurerm#9944]
### Community Note

* Please vote on this issue by adding a 👍 [reaction](https://blog.github.com/2016-03-10-add-reactions-to-pull-requests-issues-and-comments/) to the original issue to help the community and maintainers prioritize this request
* Please do not leave "+1" or "me too" comments, they generate extra noise for issue followers and do not help prioritize the request
* If you are interested in working on this issue or have submitted a pull request, please leave a comment

### Terraform (and AzureRM Provider) Version

Provider:
2.41.0 & also was happening in 2.40.0

Terraform: 0.14.2

### Affected Resource(s)

* azurerm_kubernetes_cluster

### Actual Behaviour

In the past inside my cluster I used to set http_application_routing to enabled . Then I dropped the idea and I removed the code from the resource.

I ran apply and it removed the http_application routing. BUT when I ran plan again this always keeps showing:

```hcl
 ~ addon_profile {

          - http_application_routing {
              - enabled = false -> null
            }

            # (1 unchanged block hidden)
        }
```

So it tries to ser from false to null. Even if I apply, next plan it tries to changes that always, all the time.

### What was expected

That I would remove the code. During the apply http_routing would be removed from the infrastructure and then when I plan again, no changes would be shown.

### Workaround

I had to add this block of code without needing of it only so the change doesn't appear all the time.

```hcl
   http_application_routing {
      enabled = false
    }
```

**Comment by tombuildsstuff** [comment]
hi @flmmartins 

Thanks for opening this issue.

Taking a look through here this appears to be a question regarding the Terraform Configuration - notably the `http_application_routing` block is being added (albeit disabled) by Azure and is unspecified in the Terraform config (since this option can either be omitted (outside of Azure Public, iirc) or Enabled/Disabled - which is why this is marked as `null` here (since it's present in Azure but not present in the config). As you've mentioned this is coming back with a value since this is being returned from Azure as disabled, as such to remove the drift shown in the plan you'll need to add this block, albeit configured as Disabled.

This forum is intended to be used for feature enhancements and bugs in the Azure Provider - so that we can keep this forum focused on that we instead ask that broader questions are raised [using one of the Community Resources](https://www.terraform.io/community.html). As such I'm going to close this issue for the moment, but I believe you should be able to get an answer for this [using one of the Community Resources](https://www.terraform.io/community.html).

Thanks!
