### ISSUE TITLE
azurerm_postgressql_server does not support create_mode

### ISSUE THREAD

**Issue by SidGrundfos** [terraform-providers/terraform-provider-azurerm#9978]
Using 2.41 azurerm version
![image](https://user-images.githubusercontent.com/53938860/102902524-661a7280-446f-11eb-8082-3089a283ab13.png)

Getting following error
![image](https://user-images.githubusercontent.com/53938860/102902572-7b8f9c80-446f-11eb-96b6-55fe217ad9e9.png)

Please help ASAP, this is stalling Prod deployment

**Comment by AliAllomani** [comment]
@SidGrundfos seems your problem is that the parameter/variable is not defined in the module, not the resource.

Otherwise i would recommend you to send a full test example

**Comment by GoSiddhartha** [comment]
yep, found it, my bad. Thanks for your reply

**Comment by tombuildsstuff** [comment]
👋 

Closing this out since this appears to be resolved, and is a Terraform Configuration question rather than a bug in the Azure Provider - but should you have further questions I'd point you towards [the community forum](https://discuss.hashicorp.com) where someone should be able to assist :)

Thanks!
