### ISSUE TITLE
"No valid (unexpired) Azure CLI Auth Tokens found" when using azurerm service principal authentication.

### ISSUE THREAD

**Issue by sukstansky** [terraform-providers/terraform-provider-azurerm#998]
### Terraform Version
Terraform v0.11.4
+ provider.azurerm v1.2.0

### Affected Resource(s)
Authentication mechanism in general.

### Terraform Configuration Files
```
provider "azurerm" {
  alias = "default"
  client_id = "xxx..."
  client_secret = "yyy..."
  tenant_id = "zzz..."
  subscription_id = "id..."
}

resource "azurerm_resource_group" "rg" {
  provider = "azurerm.default"
......
```

### Expected Behavior
I have working service principal credentials (client, secret, tenant IDs), that when used with Azure CLI work just fine. When used in provider definition mentioned above, I expect it to work without necessity to perform "az Login" first.  azure-cli (2.0.27) Also, even when az login --service-principal performed successfully terraform plan|apply still gives error: No valid (unexpired) Azure CLI Auth Tokens found. Please run `az login`. With regular "az login" tf configuration works fine.

### Actual Behavior
------------------------------------------------------------------------

Error: Error running plan: 1 error(s) occurred:

* provider.azurerm: No valid (unexpired) Azure CLI Auth Tokens found. Please run `az login`.

### Steps to Reproduce
Please list the steps required to reproduce the issue, for example:
1. Get client_id, client_secret, tenant_id and subscription_id from using Azure console or CLI.
2. Logout from CLI and login with credentials using service principal auth method to make sure that credentials are valid. Run some test "az" commands.
3. Run terraform plan or apply on tf config with azurerm provider been set with service principal credentials.
Error message shown: No valid (unexpired) Azure CLI Auth Tokens found. Please run `az login`.

**Comment by TomPallister** [comment]
I'm having the same problem! Sorry can't be any help first time using terraform!

**Comment by cpear** [comment]
The whole point of **az login --service-principal** is that you shouldn't have to put all of that stuff in your config file though right?

**Comment by tombuildsstuff** [comment]
hi @sukstansky @TomPallister @cpear 

Thanks for opening this issue :)

Authenticating using a Service Principal via the Azure CLI isn't supported by Terraform (which is why this doesn't work). Instead we suggest people authenticate via the Service Principal directly ([as detailed here](https://www.terraform.io/docs/providers/azurerm/authenticating_via_service_principal.html)) - would it be possible to take a look and see if specifying these values either as Environment Variables or via specifying them in the config works for you?

I'm also going to open a PR which clarifies this in the documentation - so that it's clearer that users need to use Service Principal authentication directly, rather than via the Azure CLI.

Thanks!

**Comment by sukstansky** [comment]
Hi. My problem was not in the fact that as login --service principle is not supported. It just obfuscated problem a bit more. My case is that even when I provide all parameters in azurerm provider definition - it doesn't work and keep saying that as login required.

**Comment by sukstansky** [comment]
The new issue was created as requested:
https://github.com/terraform-providers/terraform-provider-azurerm/issues/1097

All help will be greatly appreciated.
